### ISSUE TITLE
[Feature Request] Autopromotion of literal types to concrete types

### ISSUE THREAD

**Issue by Mogball** [modularml/mojo#100]
There are a large handful of issues that fall into the same category, so I am combining them into a super-issue to make tracking easier.

The core problem is that we need to "autopromote" literal types to concrete types in certain situations. 
```[tasklist]
- [ ] For example, string literals should be autopromoted to `String` when creating a variable from `StringLiteral`: https://github.com/modularml/mojo/issues/9
- [ ] List literals cannot be iterated or indexed, because they should be promoted to some dynamic list type:  https://github.com/modularml/mojo/issues/88, https://github.com/modularml/mojo/issues/89
```

**Comment by willghatch** [comment]
At this point we have proper IntLiteral and FloatLiteral.  The nonmaterializable feature is ready for similar behaviors by things like StringLiteral and ListLiteral.  But I don't think those necessarily need compiler-specific support -- I think it can all be implemented now in the stdlib.  I tried making our current StringLiteral be `@nonmaterializable(String)`, and it gave a lot of errors where `StringLiteral` is used dynamically in the stdlib.  So I think this can be handed off to the stdlib team now.  Thoughts @JoeLoser @Mogball ?

**Comment by willghatch** [comment]
Well, this specific issue has all of its sub-issues completed, so I'm going to close this one.  I think we should make issues to make these other literal types be nonmaterializable and convert to their dynamic counterpart, but I still think that that can move to stdlib now.
