### ISSUE TITLE
[BUG]: Installation not finishing on Windows 10 and mojo partially installed

### ISSUE THREAD

**Issue by astreck275** [modularml/mojo#1003]
### after several attempts i don't come further than this and no matter what i try it's always the same output. if I abort the  install at the point where it freezes, then mojo is partially installed but doesn't work. after using "mojo"  command i see some error messages and can't do anything in the terminal until restart.

# Install log:
PQJQPH5:~$ modular auth mut_48898ca985a5493dbc3638b93423263a && modular install mojo
[708:708:20231006,114855.984112:ERROR exception_handler_server.cc:361] getsockopt: Invalid argument (22)
[706:706:20231006,114855.984648:ERROR socket.cc:153] unhandled cmsg 0, 0
Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: crashpad failed to start handler
[713:713:20231006,114856.020151:ERROR exception_handler_server.cc:361] getsockopt: Invalid argument (22)
[711:711:20231006,114856.020636:ERROR socket.cc:153] unhandled cmsg 0, 0
Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: crashpad failed to start handler
 Found release for https://packages.modular.com/mojo @ 0.4.0
 Installing to /home/alex/.modular/pkg/packages.modular.com_mojo
 Downloading artifacts. Please wait...
 Downloads complete, setting configs...
 Configs complete, running post-install hooks...
Collecting find_libpython==0.3.0
  Using cached find_libpython-0.3.0-py3-none-any.whl (8.5 kB)
Collecting papermill==2.4.0
  Using cached papermill-2.4.0-py3-none-any.whl (38 kB)
Collecting jupyter_client>=8.3.0
  Using cached jupyter_client-8.3.1-py3-none-any.whl (104 kB)
Collecting ipykernel>=6.25.0
  Using cached ipykernel-6.25.2-py3-none-any.whl (154 kB)
Collecting tenacity
  Using cached tenacity-8.2.3-py3-none-any.whl (24 kB)
Collecting click
  Using cached click-8.1.7-py3-none-any.whl (97 kB)
Collecting requests
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting nbformat>=5.1.2
  Using cached nbformat-5.9.2-py3-none-any.whl (77 kB)
Collecting tqdm>=4.32.2
  Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)
Collecting ansiwrap
  Using cached ansiwrap-0.8.4-py2.py3-none-any.whl (8.5 kB)
Collecting entrypoints
  Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
Collecting nbclient>=0.2.0
  Using cached nbclient-0.8.0-py3-none-any.whl (73 kB)
Collecting pyyaml
  Using cached PyYAML-6.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (705 kB)
Collecting pyzmq>=23.0
  Using cached pyzmq-25.1.1-cp310-cp310-manylinux_2_28_x86_64.whl (1.1 MB)
Collecting traitlets>=5.3
  Using cached traitlets-5.11.2-py3-none-any.whl (83 kB)
Collecting jupyter-core!=5.0.*,>=4.12
  Using cached jupyter_core-5.3.2-py3-none-any.whl (28 kB)
Collecting tornado>=6.2
  Using cached tornado-6.3.3-cp38-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (427 kB)
Collecting python-dateutil>=2.8.2
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting nest-asyncio
  Using cached nest_asyncio-1.5.8-py3-none-any.whl (5.3 kB)
Collecting comm>=0.1.1
  Using cached comm-0.1.4-py3-none-any.whl (6.6 kB)
Collecting packaging
  Using cached packaging-23.2-py3-none-any.whl (53 kB)
Collecting debugpy>=1.6.5
  Using cached debugpy-1.8.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
Collecting psutil
  Using cached psutil-5.9.5-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (282 kB)
Collecting ipython>=7.23.1
  Using cached ipython-8.16.1-py3-none-any.whl (806 kB)
Collecting matplotlib-inline>=0.1
  Using cached matplotlib_inline-0.1.6-py3-none-any.whl (9.4 kB)
Collecting jedi>=0.16
  Using cached jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)
Collecting prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30
  Using cached prompt_toolkit-3.0.39-py3-none-any.whl (385 kB)
Collecting pexpect>4.3
  Using cached pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Collecting pickleshare
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting decorator
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting exceptiongroup
  Using cached exceptiongroup-1.1.3-py3-none-any.whl (14 kB)
Collecting backcall
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting stack-data
  Using cached stack_data-0.6.3-py3-none-any.whl (24 kB)
Collecting pygments>=2.4.0
  Using cached Pygments-2.16.1-py3-none-any.whl (1.2 MB)
Collecting platformdirs>=2.5
  Using cached platformdirs-3.11.0-py3-none-any.whl (17 kB)
Collecting fastjsonschema
  Using cached fastjsonschema-2.18.1-py3-none-any.whl (23 kB)
Collecting jsonschema>=2.6
  Using cached jsonschema-4.19.1-py3-none-any.whl (83 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting textwrap3>=0.9.2
  Using cached textwrap3-0.9.2-py2.py3-none-any.whl (12 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.0.6-py3-none-any.whl (123 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2023.7.22-py3-none-any.whl (158 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.3.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (138 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting parso<0.9.0,>=0.8.3
  Using cached parso-0.8.3-py2.py3-none-any.whl (100 kB)
Collecting referencing>=0.28.4
  Using cached referencing-0.30.2-py3-none-any.whl (25 kB)
Collecting attrs>=22.2.0
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting jsonschema-specifications>=2023.03.6
  Using cached jsonschema_specifications-2023.7.1-py3-none-any.whl (17 kB)
Collecting rpds-py>=0.7.1
  Using cached rpds_py-0.10.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
Collecting ptyprocess>=0.5
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting wcwidth
  Using cached wcwidth-0.2.8-py2.py3-none-any.whl (31 kB)
Collecting pure-eval
  Using cached pure_eval-0.2.2-py3-none-any.whl (11 kB)
Collecting executing>=1.2.0
  Using cached executing-2.0.0-py2.py3-none-any.whl (24 kB)
Collecting asttokens>=2.1.0
  Using cached asttokens-2.4.0-py2.py3-none-any.whl (27 kB)
Installing collected packages: wcwidth, textwrap3, pure-eval, ptyprocess, pickleshare, find_libpython, fastjsonschema, executing, backcall, urllib3, traitlets, tqdm, tornado, tenacity, six, rpds-py, pyzmq, pyyaml, pygments, psutil, prompt-toolkit, platformdirs, pexpect, parso, packaging, nest-asyncio, idna, exceptiongroup, entrypoints, decorator, debugpy, click, charset-normalizer, certifi, attrs, ansiwrap, requests, referencing, python-dateutil, matplotlib-inline, jupyter-core, jedi, comm, asttokens, stack-data, jupyter_client, jsonschema-specifications, jsonschema, ipython, nbformat, ipykernel, nbclient, papermill
Successfully installed ansiwrap-0.8.4 asttokens-2.4.0 attrs-23.1.0 backcall-0.2.0 certifi-2023.7.22 charset-normalizer-3.3.0 click-8.1.7 comm-0.1.4 debugpy-1.8.0 decorator-5.1.1 entrypoints-0.4 exceptiongroup-1.1.3 executing-2.0.0 fastjsonschema-2.18.1 find_libpython-0.3.0 idna-3.4 ipykernel-6.25.2 ipython-8.16.1 jedi-0.19.1 jsonschema-4.19.1 jsonschema-specifications-2023.7.1 jupyter-core-5.3.2 jupyter_client-8.3.1 matplotlib-inline-0.1.6 nbclient-0.8.0 nbformat-5.9.2 nest-asyncio-1.5.8 packaging-23.2 papermill-2.4.0 parso-0.8.3 pexpect-4.8.0 pickleshare-0.7.5 platformdirs-3.11.0 prompt-toolkit-3.0.39 psutil-5.9.5 ptyprocess-0.7.0 pure-eval-0.2.2 pygments-2.16.1 python-dateutil-2.8.2 pyyaml-6.0.1 pyzmq-25.1.1 referencing-0.30.2 requests-2.31.0 rpds-py-0.10.4 six-1.16.0 stack-data-0.6.3 tenacity-8.2.3 textwrap3-0.9.2 tornado-6.3.3 tqdm-4.66.1 traitlets-5.11.2 urllib3-2.0.6 wcwidth-0.2.8

# Error Log when trying to run "mojo" command:
PQJQPH5:~$ mojo
[1259:1259:20231006,120316.181225:ERROR exception_handler_server.cc:361] getsockopt: Invalid argument (22)
[1257:1257:20231006,120316.181694:ERROR socket.cc:153] unhandled cmsg 0, 0
Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: crashpad failed to start handler
[1273:1273:20231006,120316.253309:ERROR exception_handler_server.cc:361] getsockopt: Invalid argument (22)
[1257:1257:20231006,120316.253818:ERROR socket.cc:153] unhandled cmsg 0, 0
Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: crashpad failed to start handler

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ? Windows 10
- Provide version information for Mojo by pasting the output of `mojo -v` mojo 0.4.0 (9e33b013)
- Provide Modular CLI version by pasting the output of `modular -v`  modular 0.2.0 (355ea9c0)
```

**Comment by gryznar** [comment]
Unfortunately Mojo is currently supported only on Ubuntu, so if you are trying to do that natively it won't work. Option is WSL2 / VM with Ubuntu

**Comment by Jaymbo** [comment]
I got the same problem and haven't found a way to solve it, i reinstalled the ubuntu 22.04.2 LTS many times, but it didnt help. My Internet sometimes fails during the installation of mojo. crashpad isn't working and i havent found a way of installing it either. 

im using:
windows 10
ubuntu 22.04.2 LTS
WSL 1

my latest attempt:

______@Laptop-1:~$ modular install mojo
[28:28:20231006,135601.231507:ERROR exception_handler_server.cc:361] getsockopt: Invalid argument (22)
[26:26:20231006,135601.235261:ERROR socket.cc:153] unhandled cmsg 0, 0
Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: crashpad failed to start handler
# Found release for https://packages.modular.com/mojo @ 0.4.0
# Installing to /home/______/.modular/pkg/packages.modular.com_mojo
# Downloading artifacts. Please wait...
modular: error: failure detected - please run `modular clean` and try again
==========================
Failure Information:
        - Creating symlink for /home/______/.modular/pkg/packages.modular.com_mojo/lib/liblldb.so.18.0.0git -> /home/______/.modular/pkg/packages.modular.com_mojo/lib/liblldb.so failed: File exists
        - Creating symlink for /home/______/.modular/pkg/packages.modular.com_mojo/lib/libMojoJupyter.so.18git -> /home/______/.modular/pkg/packages.modular.com_mojo/lib/libMojoJupyter.so failed: File exists
        - Creating symlink for /home/______/.modular/pkg/packages.modular.com_mojo/lib/liblldb.so.18.0.0git -> /home/______/.modular/pkg/packages.modular.com_mojo/lib/liblldb.so.18git failed: File exists
        - Creating symlink for /home/______/.modular/pkg/packages.modular.com_mojo/lib/libKGENCompilerRTShared.so.18git -> /home/______/.modular/pkg/packages.modular.com_mojo/lib/libKGENCompilerRTShared.so failed: File exists
        - Creating symlink for /home/______/.modular/pkg/packages.modular.com_mojo/lib/libMojoLLDB.so.18git -> /home/______/.modular/pkg/packages.modular.com_mojo/lib/libMojoLLDB.so failed: File exists
        - Creating symlink for /home/______/.modular/pkg/packages.modular.com_mojo/lib/libLLCLRuntimeGlobals.so.18git -> /home/______/.modular/pkg/packages.modular.com_mojo/lib/libLLCLRuntimeGlobals.so failed: File exists
        - Creating symlink for /home/______/.modular/pkg/packages.modular.com_mojo/lib/libMSupportGlobals.so.18git -> /home/______/.modular/pkg/packages.modular.com_mojo/lib/libMSupportGlobals.so failed: File exists
==========================

______@Laptop-1:~$ modular clean
[212:212:20231006,142828.570762:ERROR exception_handler_server.cc:361] getsockopt: Invalid argument (22)
[210:210:20231006,142828.577149:ERROR socket.cc:153] unhandled cmsg 0, 0
Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: crashpad failed to start handler
______@Laptop-1:~$

______ is placeholder

**Comment by astreck275** [comment]
> Unfortunately Mojo is currently supported only on Ubuntu, so if you are trying to do that natively on Windows it won't work. Option is WSL2 / VM with Ubuntu Or maybe you give to less information about your environment

I forgot to mention that I was using WSL with the right Ubuntu distro and the Installation was inside of the WSL

**Comment by gryznar** [comment]
@Jaymbo Modular mentioned, that only WSL2 is supported oficially

**Comment by Jaymbo** [comment]
> @Jaymbo Modular mentioned, that only WSL2 is supported oficially

thanks for the quick reply, how do i use wsl2 i just klicked on the link they gave me:
https://apps.microsoft.com/detail/ubuntu-22042-lts/9PN20MSR04DW?hl=de-de&gl=DE

**Comment by astreck275** [comment]
> @Jaymbo Modular mentioned, that only WSL2 is supported oficially

That was my problem, the WSL version is set to 1, i changed it though command prompt
![image](https://github.com/modularml/mojo/assets/65851426/2bd19a20-19bb-4d5e-b3c0-6c1ec2d95fc1)

**Comment by gryznar** [comment]
@astreck275 does it helped?

**Comment by Jaymbo** [comment]
[mojo] Testing: `mojo repl` [FAIL] 
it stays in a loop

**Comment by gryznar** [comment]
I've seen somewhere problems relating to testing phase. But they should be fixed in 0.3.1. Maybe cause of this problem is different or it's a regression in 0.4.. I don't know

**Comment by Jaymbo** [comment]
it once run to the end, and had a different error, but i wasn't able to recreate that

**Comment by astreck275** [comment]
> @astreck275 does it helped?

Yes after changing the version i could install mojo now and it's working fine, thank you very much!

**Comment by gryznar** [comment]
@astreck275 nice to here that. You can close this task ;)
