### ISSUE TITLE
[BUG]: Error with dynamic string message: free(): double free detected in tcache 2

### ISSUE THREAD

**Issue by guidorice** [modularml/mojo#1004]
### Bug description

- In 0.4.0 there is a [new feature for dynamic messages in Errors](https://docs.modular.com/mojo/changelog.html#v0.4.0-2023-10-05). It causes a crash when trying to get the string out of the Error. print() of the Error may also be bugged here as well. Repro script below.

- Separately there is also a [docs bug in the changelog](https://docs.modular.com/mojo/changelog.html#v0.4.0-2023-10-05), which has `e.message()` a method which does not exist on Error.

### Steps to reproduce

repro.mojo

```mojo
from testing import assert_equal

fn foo(x:String) raises:
    raise Error("Failed on: " + x)

fn main():
    try:
        foo("Hello")
    except e:
        print(e)
        if assert_equal(e.__str__(), "Failed on: Hello"):
            print("OK")
```

```
$ mojo repro.mojo 
free(): double free detected in tcache 2
[1303:1303:20231006,140540.846196:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[1303:1303:20231006,140540.846377:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.	Program arguments: mojo[1303:1304:20231006,140540.847668:ERROR directory_reader_posix.cc:42] opendir /home/rice_guido/.modular/crashdb/attachments/430ab08b-bdbf-49db-a5f5-5b2c2b438196: No such file or directory (2)
 repro.mojo
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  mojo            0x000055564e5bca57
1  mojo            0x000055564e5ba62e
2  mojo            0x000055564e5bd12f
3  libpthread.so.0 0x00007f92ad8a2140
4  libc.so.6       0x00007f92ad360ce1 gsignal + 321
5  libc.so.6       0x00007f92ad34a537 abort + 291
6  libc.so.6       0x00007f92ad3a23a8
7  libc.so.6       0x00007f92ad3a969a
8  libc.so.6       0x00007f92ad3aac95
9  libc.so.6       0x00007f925c001205
Aborted
rice_guido@mojo-dev:~/geo-features$ [1303:1304:20231006,140541.108051:ERROR http_transport_libcurl.cc:483] HTTP status 404

echo $?
134

```

### System information

```shell
Linux mojo-dev 5.10.0-25-cloud-amd64 #1 SMP Debian 5.10.191-1 (2023-08-16) x86_64 GNU/Linux
mojo 0.4.0 (9e33b013)
modular 0.2.0 (355ea9c0)
```

**Comment by jackos** [comment]
@scottamain @arthurevans see above on docs, can print `e` directly.

@guidorice you can use a StringLiteral to avoid the double free:
```pythonl
fn foo(x: StringLiteral) raises:
    raise Error("Failed on: " + x)

fn main():
    try:
        foo("This Works")
    except e:
        print(e)
```
@abduld see above double free when using a heap allocated `String` inside an except block

**Comment by jackos** [comment]
This will be fixed in next release thanks @guidorice

**Comment by arthurevans** [comment]
Got it. Looks like the change removing e.message() was in v0.4.0, will add a note and remove the reference to `message()` in the code example for v0.4.0.

**Comment by guidorice** [comment]
> you can use a StringLiteral to avoid the double free

@jackos hey, looks like that's not a useful workaround because I'm just trying to wrap testing.assert_true to make it more useful:

```mojo
fn assert_true(cond: Bool, message: StringLiteral) raises:
    """
    Wraps testing.assert_true, raises Error on assertion failure.
    """
    if not testing.assert_true(cond, message):
        raise Error(message)  # message is printed by testing.assert_true()
```

^ that also fails with free(): double free detected in tcache 2 because assert_true takes a String?

This seems like a broader issue with dynamic strings?

**Comment by jackos** [comment]
Hi @guidorice there was a double free problem when passing a heap allocated string through an error, it was fixed but isn't in the current release yet.
