### ISSUE TITLE
[BUG]: no module named 

### ISSUE THREAD

**Issue by ThirstB1ood** [modularml/mojo#1006]
### Bug description

Unhandled exception caught during execution: No module named 'pandas'
mojo: error: execution exited with a non-zero result: 1

### Steps to reproduce

Code:
from python import Python

fn main() raises:
  let pd = Python.import_module("pandas")

### System information

```shell
- What OS did you do install Mojo on ? MacOS
- Provide version information for Mojo by pasting the output of `mojo -v` 0.4.0
- Provide Modular CLI version by pasting the output of `modular -v` 0.2.0
```

**Comment by jackos** [comment]
Hi @ThirstB1ood just checking, have you tried installing `pandas`?
```bash
pip install pandas
```
If it still doesn't work, this blog goes into details for how you can fix it: https://www.modular.com/blog/using-mojo-with-python

**Comment by ThirstB1ood** [comment]
@jackos, I'm used to the fact that it's initially installed and forgotten. Thanks
