### ISSUE TITLE
[Dev Console]:

### ISSUE THREAD

**Issue by jackywww** [modularml/mojo#1012]
### Issue description

mojo matmul.mojo 
Throughput of a 128x128 matrix multiplication in Python: 
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.	Program arguments: mojo matmul.mojo
#0 0x000055b6d4b58657 (/home/jacky/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5b6657)
#1 0x000055b6d4b5622e (/home/jacky/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5b422e)
#2 0x000055b6d4b58d2f (/home/jacky/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5b6d2f)
#3 0x00007fe7ba62e520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
Segmentation fault (core dumped)

### Steps to reproduce

- Add screenshots if possible, to help explain the problem.
- Include anything that might help us debug the issue.

**Comment by guidorice** [comment]
Consider adding some system info? (bug report template) https://github.com/modularml/mojo/blob/main/.github/ISSUE_TEMPLATE/mojo_bug_report.yaml

works on my machine:
```
$ mojo matmul.mojo 
Throughput of a 128x128 matrix multiplication in Python: 
0.001389015180814244 GFLOP/s
Throughput of a 512x512 matrix multiplication in Mojo using a naive algorithm: 
2.5667467623652445 GFLOP/s <> 1847 x speedup over Python
Throughput of a 512x512 matrix multiplication in Mojo using vectorization: 
18.042038446108176 GFLOP/s <> 12989 x speedup over Python
Throughput of a 512x512 matrix multiplication in Mojo using the stdlib `vectorize`: 
17.447379667166945 GFLOP/s <> 12560 x speedup over Python
Throughput of a 512x512 {vectorized + parallelized} matrix multiplication in Mojo: 
6.9730310523597403 GFLOP/s <> 5020 x speedup over Python
Throughput of a 512x512 {tiled + vectorized + parallelized} matrix multiplication in Mojo: 
5.8918970908452222 GFLOP/s <> 4241 x speedup over Python
Throughput of a 512x512 {tiled + unrolled + vectorized + parallelized} matrix multiplication in Mojo: 
6.1362076922473792 GFLOP/s <> 4417 x speedup over Python
```
