### ISSUE TITLE
[BUG]: Possible bug? Should parameterized T be recognized as type?

### ISSUE THREAD

**Issue by jloveric** [modularml/mojo#1016]
### Bug description

I was expecting the following definition to be valid
```
fn some_func[T:DType](tolerance : T):
    pass
```
turns out I get the error
```
error: expected a type, not a value
    tolerance: T,
```
The same thing seems to at least run when I use
```
tolerance : Tensor[T]
```
mojo 0.4.0

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by lattner** [comment]
You can write things like this:

```
fn some_func[T: AnyType](tolerance : T):
    pass
```

but it isn't very useful right now because we lack traits so there are no operations you can perform on `tolerance`.  They're coming, stay tuned :-)

**Comment by paugier** [comment]
How I am supposed to write this (which gives the same issue "expected a type, not a value" with Mojo 0.0.5):

```
@register_passable
struct SimpleContainer[dtype: DType]:

    var data: DTypePointer[dtype]
    var size: Int

    fn __init__(size: Int) -> Self:
        let data = DTypePointer[dtype].alloc(size)
        memset_zero[dtype](data, size)
        return Self {data: data, size: size}

    fn __setitem__(inout self, idx: Int, value: dtype):
        self.data.store(idx, value)

    fn __del__(owned self):
        self.data.free()
```

Here I can't write `struct SimpleContainer[dtype: AnyType]:`. Moreover, it seems to me that it would make sense that a `DType` instance would be a type, wouldn't it?

**Comment by paugier** [comment]
Ah this works:

```python
    fn __setitem__(inout self, idx: Int, value: SIMD[dtype, 1]):
```

but it seems suboptimal and the error message is not that helpful.
