### ISSUE TITLE
[Modular CLI]: No module named 'numpy'

### ISSUE THREAD

**Issue by modwedar** [modularml/mojo#1017]
### Issue description

```
from python import Python

fn main() raises:
    let np = Python.import_module("numpy")
    a = np.array([1, 2, 3])
    
```
    
Unhandled exception caught during execution: No module named 'numpy'
mojo: error: execution exited with a non-zero result: 1

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### Version Info

modular 0.2.0 (355ea9c0)

**Comment by gryznar** [comment]
You have to have "numpy" installed in you r Python environment. Mojo do not install it automatically.

**Comment by gryznar** [comment]
Could be this task closed? :)

**Comment by modwedar** [comment]
yes, thx
