### ISSUE TITLE
[BUG]: modular: error: unable to bootstrap the TUF repository, missing bootstrap.json

### ISSUE THREAD

**Issue by Dunckleosteus** [modularml/mojo#1025]
### Bug description

I ran the recommended: 
```shell
sudo apt-get update
sudo apt-get install modular
modular clean
modular install mojo
```
And I get the following error: 
 modular: error: unable to bootstrap the TUF repository, missing bootstrap.json

I have tried removing and reinstalling modular but I keep on getting the same error. 

### Steps to reproduce

Steps described in bug report

### System information

```shell
- What OS did you do install Mojo on ?

OS: TUXEDO OS 2 x86_64 
Host: NB02 GMxRGxx 
Kernel: 6.2.0-10025-tuxedo 
AMD Ryzen 7 6800H with Radeon Graphics (16) @ 3.200GHz 
GPU: AMD ATI Radeon 680M 
GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q 
Memory: 6168MiB / 15218MiB 

- Provide version information for Mojo by pasting the output of `mojo -v`
Mojo did not install 
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.2.0
```

**Comment by Dunckleosteus** [comment]
Update: I fixed the problem by removing root.json in the .modular directory now it just stays stuck on: 
❯ modular install mojo
# Found release for https://packages.modular.com/mojo @ 0.4.0
# Installing to /home/throgg/.modular/pkg/packages.modular.com_mojo
# Downloading artifacts. Please wait...

This can go on for hours with no signs of progress

**Comment by jackos** [comment]
Resolved, please try again and reopen if you still have issues
