### ISSUE TITLE
[BUG]: Types in aliases do not work as expected

### ISSUE THREAD

**Issue by RickieBlaese** [modularml/mojo#1028]
### Bug description

Using aliases for types produces errors unexpectedly, when the user would expect them to be essentially substituted.

### Steps to reproduce

The following fails:
```
fn nothing() -> None: pass

fn main():
    alias T = fn() -> None
    let f: T = nothing
```
with:
```
error: cannot implicitly convert 'fn() -> None' value to 'T' in 'let' initializer
    let f: T = nothing
               ^~~~~~~
```
The types here seem to be completely identical from hovering over them in VS Code. Additionally, this seems to be the case for many function types, not just the basic `fn() -> None`. Any alias that one would expect to be essentially substituted into a function type appears to fail.

However, the following works:
```
fn nothing() -> None: pass

fn main():
    let f: fn() -> None = nothing
```

### Revision
This appears to be the case for not just function types, but many types. Apologies for not catching this.
For example, the following also fails:
```
fn main():
    let a = 3
    alias T = Int
    let other: T = a
```

### System information

```shell
- What OS did you do install Mojo on ?
Kali Linux on WSL2 on Windows 11

- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.4.0 (9e33b013)

- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.2.0 (355ea9c0)
```

**Comment by Mogball** [comment]
Hey, thanks for filing! This is a known issue at the moment. Please use an `alias` outside of functions.
