### ISSUE TITLE
[BUG]: tensorprint(t) fails to print the tensor info.

### ISSUE THREAD

**Issue by ajayspatil7** [modularml/mojo#1039]
### Bug description

...modules import
...alias type

```
t = rand[type][2,3,3]
tensorprint(t)
```

Should print the tensor information on the notebook output cell. But, compiling successfully not printing anything.

### Steps to reproduce

- Code snippet
```
from tensor import tensor
from tensorutils import tensorprint
from random import rand

alias type = DType.float32

t = rand[type](2, 3,3)

tensorprint(t)
```
- Screenshot.
<img width="1117" alt="Screenshot 2023-10-11 at 2 09 35 PM" src="https://github.com/modularml/mojo/assets/51265917/b1d475e3-c59b-4137-9462-6e60e0dadaf7">

- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
<b>Notebook name : mojo.ipynb</b>
- Include anything else that might help us debug the issue.
<i>nothing as of now</i>

### System information

```shell
- What OS did you do install Mojo on ?
Docker container with Ubuntu running
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.4.0 (9e33b013)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.2.0 (355ea9c0)
```

**Comment by ChenLi2049** [comment]
The function `tensorprint` is defined in https://github.com/modularml/mojo/blob/main/examples/blogs-videos/tensorutils/tensorutils.mojo, you need to import this file first or copy the content in this file to your code before use this function.

**Comment by ajayspatil7** [comment]
> The function `tensorprint` is defined in https://github.com/modularml/mojo/blob/main/examples/blogs-videos/tensorutils/tensorutils.mojo, you need to import this file first or copy the content in this file to your code before use this function.

Yes. The library has been imported  and is working. But, unable to produce the output.

**Comment by ChenLi2049** [comment]
1. In the first line, it should be `from tensor import Tensor`, with capital "T". I tried your code with `from tensor import Tensor` and `from tensor import tensor` in Mojo playground, and they both work.
2. I'm guessing it's the problem with your environment or VSCode. Please try `print(t.shape().__str__())`

**Comment by ajayspatil7** [comment]
> 1. In the first line, it should be `from tensor import Tensor`, with capital "T". I tried your code with `from tensor import Tensor` and `from tensor import tensor` in Mojo playground, and they both work.
> 
> 2. I'm guessing it's the problem with your environment or VSCode that fail to print. Please try `print(t.shape().__str__())`

I just rechecked my code. I've imported it correctly as you've mentioned. But still not working. I'll probably check once with my environment/docker and see.
Thank you :)

**Comment by admercs** [comment]
I get the following error:

```
error: unable to locate module 'tensorutils'
```

**Comment by ChenLi2049** [comment]
According to [changelog of v0.5.0](https://docs.modular.com/mojo/changelog.html#new-1):

>The built-in print() function now works on the [Tensor](https://docs.modular.com/mojo/stdlib/tensor/tensor.html) type.

For example:

```mojo
from tensor import Tensor
from random import rand

alias type = DType.float32
t = rand[type](2, 3, 3)

print(t)
```

will get:

```Bash
Tensor([[[0.1315377950668335, 0.458650141954422, 0.21895918250083923],
[0.67886471748352051, 0.93469291925430298, 0.51941639184951782],
[0.034572109580039978, 0.52970021963119507, 0.007698186207562685]],
[[0.066842235624790192, 0.68677270412445068, 0.93043649196624756],
[0.52692878246307373, 0.65391898155212402, 0.70119059085845947],
[0.76219803094863892, 0.047464512288570404, 0.3282342255115509]]], dtype=float32, shape=2x3x3)
```

**Comment by ematejska** [comment]
Closing this out per the comment above.
