### ISSUE TITLE
Mojo speed boost non-visible

### ISSUE THREAD

**Issue by Rong-Tao** [modularml/mojo#1046]
### Hi, I am running some torch matrix multiplication test with compiled mojo, direct running mojo and using python.

The mojo code is provided below:

```python
from python import Python
fn main() raises:
    let torch = Python.import_module('torch')
    let time = Python.import_module('time')
    let device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(device)
    alias size = (10000,10000)
    let A_cpu = torch.randn(size)
    let B_cpu = torch.randn(size)
    let A_cuda = A_cpu.cuda()
    let B_cuda = B_cpu.cuda()
    var start_time = time.time()
    for i in range(5):
        let result_cpu = torch.matmul(A_cpu, B_cpu)
    var end_time = time.time()
    print('CPU Time: ', end_time-start_time, 'seconds')
    start_time = time.time()
    for i in range(5):
        let result_cuda = torch.matmul(A_cuda, B_cuda)
    end_time = time.time()
    print('CUDA Time: ', end_time-start_time, 'seconds')
```

And the end result is shown here:

```bash
(cv) (base) (cv) rong@rong-laptop:~/Study/mojo$ make
mojo build main.🔥
(cv) (base) (cv) rong@rong-laptop:~/Study/mojo$ make run
MOJO_PYTHON_LIBRARY=/home/rong/miniconda3/envs/cv/lib/libpython3.11.so ./main
cuda
CPU Time:  20.45246195793152 seconds
CUDA Time:  0.43241119384765625 seconds
(cv) (base) (cv) rong@rong-laptop:~/Study/mojo$ mojo main.🔥
cuda
CPU Time:  20.251466989517212 seconds
CUDA Time:  0.42893290519714355 seconds
(cv) (base) (cv) rong@rong-laptop:~/Study/mojo$ python main.py
cuda
CPU Time:  20.70795750617981 seconds
CUDA Time:  0.43175220489501953 seconds
(cv) (base) (cv) rong@rong-laptop:~/Study/mojo$
```

The performance is almost identical, what's wrong here?

### System Info
OS: Ubuntu 20.04
mojo: mojo 0.3.0 (f64f9601)
modular: modular 0.2.0 (355ea9c0)

**Comment by gryznar** [comment]
To execute python code, local CPython is used under the hood. Mojo works here like a wrapper

**Comment by Rong-Tao** [comment]
Hoi, I am following this from [https://www.youtube.com/watch?v=5Sm9IVMet9c&t=5527s&ab_channel=freeCodeCamp.org](mojo tutorial) at 1:28:55 . We have almost identical code with slight difference. That guy managed to get 3x speed by compileling, why?

**Comment by gryznar** [comment]
Good question. Someone from Modular (company behind Mojo) should respond here

**Comment by lattner** [comment]
We don't expect mojo to run external pytorch code faster than python does.  To get a speedup, you have to pull the computation heavy lifting into mojo itself

**Comment by Rong-Tao** [comment]
I thought the compilation would speed up the exe time? In this case no? Does that mean that only Mojo native code can get speed boost from compilation？
