### ISSUE TITLE
Mojo VS code extension give error messages at random times[BUG]: 

### ISSUE THREAD

**Issue by Marcus-Peterson** [modularml/mojo#1050]
### Bug description

It's hard to replicate the errors that the VS code extension throws. Since they are so random. The code works fine and can easily be compiled.

For example this piece of code:

```
def main():
    print("hello")
```

gives me these random error messages:

```
unable to locate module 'builtin'mojo
could not find builtin 'Error' typemojo
could not find an 'object' typemojo
expected 'main' function to return 'None'mojo
```

**And now just literally 2 seconds later after I moved my cursor one line under they all disappear**
I have no idea what's going on. This isn't the first time. Sometimes the error messages persist seemingly at random, and appear at random.

I honestly don't know if this is a feature or a bug. But I wanted to report it.

### Steps to reproduce

* Include relevant code snippet or link to code that did not work as expected.
* If applicable, add screenshots to help explain the problem.
* If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
* Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
Using windows together with Ubuntu 22.04.2 LTS
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.4.0 (9e33b013)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.2.0 (355ea9c0)
```

```[tasklist]
### Tasks
```

**Comment by walter-erquinigo** [comment]
Hi, @Marcus-Peterson , could you share how you set up your VSCode extension and how it knows the location of the SDK? Besides that, when the errors go away, do docstrings via hovering work? And finally, could you share the contents of the Mojo Output Channel on VScode (that's where we write the logs)? 
This might help me figure out what could be going on.

```
unable to locate module 'builtin'mojo
could not find builtin 'Error' typemojo
could not find an 'object' typemojo
expected 'main' function to return 'None'mojo
```
These complaints mean that the parser within the LSP cannot identify the builtin package that is bundled in the SDK for some reason.
