### ISSUE TITLE
[Mojo]: Cannot have a submodule called "stdlib_extensions.os"

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [modularml/mojo#1052]
### Issue description

If I have a submodule called `os`, then I cannot run any script and I get an error. If I rename this directory to something else, then there is no issue. Also,  this bug only triggers if I have an `__init__.mojo` file alongside another mojo file (in my reproducible example, `hello.mojo`). If the second file is removed, everything works correctly.

```
 $ tree ./
./
|-- run_all_tests.mojo
`-- stdlib_extensions
    |-- __init__.mojo
    `-- os
        |-- __init__.mojo
        `-- hello.mojo

2 directories, 4 files
```

I managed to craft a minimal reproducible example (who doesn't like that?).

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

To reproduce the issue:

```
git clone https://github.com/gabrieldemarmiesse/mojo-stdlib-extensions.git
cd mojo-stdlib-extensions
git checkout minimal_reproducible_example
mojo run_all_tests.mojo
```
The error message is the following:
```
/projects/open_source/mojo-stdlib/mojo_stdlib/__init__.mojo:0:0: error: redefinition of symbol named '$__init__'
/projects/open_source/mojo-stdlib/mojo_stdlib/__init__.mojo:0:0: note: see current operation:
"lit.file_module"() ({
^bb0:
}) {sym_name = "$__init__"} : () -> ()
/projects/open_source/mojo-stdlib/mojo_stdlib/__init__.mojo:0:0: note: see existing symbol definition here
mojo: error: failed to parse the provided Mojo
```

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
modular -v
modular 0.2.0 (355ea9c0)
mojo -v
mojo 0.4.0 (9e33b013)

- What OS did you install modular CLI on ?
docker container running ubuntu 22.04 under WSL
```

**Comment by Mogball** [comment]
Closing in favour of #1248
