### ISSUE TITLE
[BUG]: Strings returned by chr() can't be concatenated

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [modularml/mojo#1058]
### Bug description

As the title says. From the mojo REPL:

```
  5> print(chr(97))
a
  6> print(chr(98))
b
  7> print(chr(97) + chr(98))
  8.
a
```

I was expecting to get "ab" as the output here. I double checked with python:

```python
>>> print(chr(97) + chr(98))
ab
```
So it's indeed a mojo bug.

I found this bug while I was trying to reconstruct a `String` from a pointer of C char.

### Steps to reproduce

See above

### System information

```shell
- What OS did you do install Mojo on ?
Ubuntu 22.04 in a docker container under WSL
- Provide version information for Mojo by pasting the output of `mojo -v`
0.4.0
- Provide Modular CLI version by pasting the output of `modular -v`
0.2.0
```

**Comment by jasecoulls** [comment]
I hit this same bug tonight and my solution was to remove the null terminator.  For example, this String can be concatenated to another string, as it's just a single character: 
`let current_char: String = input_string.__getitem__(idx)`
... yet, the chr() generated string could only be concatenated if I took the first byte.
`new_char = chr(new_value)[0]    # knock off the null terminator`

macOS: Sonoma 14.0
CPU: Apple M1 Pro
mojo: mojo 0.4.0 (9e33b013)
modular: modular 0.2.1 (5144fffe)

**Comment by willghatch** [comment]
Thanks for posting!  I can reproduce this on 0.4.0, but in the latest development branch it seems to be already fixed.  So you should get the fix with the next release.
