### ISSUE TITLE
[BUG] Mojo happily parsers code that has messed up indentation

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [modularml/mojo#1060]
### Bug description

I was already at the point of banging my head against a wall for this one. Consider the following code:

```python
def main():
    print("evaluating a")
    a = 3
    if a == 4:
        print("a is 4")
     print("a is NOT 4")
```

This code, if executed with mojo will print this:

```
evaluating a
```

You might be wondering (like me during the last 20 minutes) what the hell is going on. Because the code looks absolutly correct. Except that the line `print("a is NOT 4")` has 5 leading spaces, not 4...

Since this is super duper difficult to spot, python crashes on the same code snippet:

```
  File "/projects/open_source/mojo-stdlib/trying_stuff.py", line 6
    print("a is NOT 4")
                       ^
IndentationError: unindent does not match any outer indentation level
```

Even `mojo format` crashes on this:
```
error: cannot format stdlib_extensions/builtins/_bytes.mojo: unindent does not match any outer indentation level (<tokenize>, line 334)

Oh no! 💥 💔 💥
3 files reformatted, 22 files left unchanged, 1 file failed to reformat.
```

Could you please make mojo crash instead of executing the code? (sadly thinking about how I nearly went to an alysum because of this...)

### Steps to reproduce

Code snippet above

### System information

```shell
- What OS did you do install Mojo on ?
ubuntu 22.04 in a docker container in wsl
- Provide version information for Mojo by pasting the output of `mojo -v`
0.4.0
- Provide Modular CLI version by pasting the output of `modular -v`
0.2.0
```

**Comment by gabrieldemarmiesse** [comment]
I know. This is not the problem. The problem is that mojo runs it without crashing.

**Comment by Mogball** [comment]
The Mojo parser is not very strict on whitespaces, but mojo format actually uses a different tool to do the formatting, hence the difference. I think it is worth serious discussion as to how strict Mojo should be with whitespacing. For bootstrapping, it was easier not to really worry about it.

**Comment by lattner** [comment]
This is on my todo list to look at

**Comment by lattner** [comment]
This is fixed in the next release, we now produce:

```
test.🔥:9:6: error: statement has excess indentation
     print("a is NOT 4")
     ^
test.🔥:7:5: note: indentation should match previous statement
    if a == 4:
    ^
```

Thank you for filing this!

**Comment by gabrieldemarmiesse** [comment]
Thanks for the fix! This bug was brutal
