### ISSUE TITLE
[Modular CLI]: 

### ISSUE THREAD

**Issue by tokamohamedQC** [modularml/mojo#1061]
### Issue description

After installing WSL ubuntu and modular, I can't Install Mojo using the command "modular install mojo" and I'm getting this error:
[8603:8603:20231015,180719.211828:ERROR exception_handler_server.cc:361] getsockopt: Invalid argument (22)
[8601:8601:20231015,180719.212223:ERROR socket.cc:153] unhandled cmsg 0, 0
Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: crashpad failed to start handler
# Found release for https://packages.modular.com/mojo @ 0.4.0
# Installing to /home/toka_mohamed/.modular/pkg/packages.modular.com_mojo
# Downloading artifacts. Please wait...
modular: error: failure detected - please run `modular clean` and try again
==========================
Failure Information:
        - http error: failed to reach URL https://cas.modular.com/0/U3Y44CWYG6NwyCPOF_0bP6NVlj_KXJww4gAmn8RH99Q with cURL error Timeout was reached - Looking for U3Y44CWYG6NwyCPOF_0bP6NVlj_KXJww4gAmn8RH99Q
        - Creating symlink for /home/toka_mohamed/.modular/pkg/packages.modular.com_mojo/lib/liblldb.so.18.0.0git -> /home/toka_mohamed/.modular/pkg/packages.modular.com_mojo/lib/liblldb.so failed: File exists
        - Creating symlink for /home/toka_mohamed/.modular/pkg/packages.modular.com_mojo/lib/liblldb.so.18.0.0git -> /home/toka_mohamed/.modular/pkg/packages.modular.com_mojo/lib/liblldb.so.18git failed: File exists
        - Creating symlink for /home/toka_mohamed/.modular/pkg/packages.modular.com_mojo/lib/libMojoLLDB.so.18git -> /home/toka_mohamed/.modular/pkg/packages.modular.com_mojo/lib/libMojoLLDB.so failed: File exists
        - http error: failed to reach URL https://cas.modular.com/0/aSyHtEbKVfuJMM5DmDvACqLgh6zXB8_T1vOZZeFCJw8 with cURL error Timeout was reached - Looking for aSyHtEbKVfuJMM5DmDvACqLgh6zXB8_T1vOZZeFCJw8
        - http error: failed to reach URL https://cas.modular.com/0/XWOPjPQpTXw5rl5d_3iNdw8IWB4hif3ppDS8Efjhqkw with cURL error Timeout was reached - Looking for XWOPjPQpTXw5rl5d_3iNdw8IWB4hif3ppDS8Efjhqkw
==========================

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`  --> modular 0.2.0
- What OS did you install modular CLI on ? Windows
```

**Comment by oskgo** [comment]
You might want to put the CLI output into a code block for readability. Also, a descriptive name for the issue would be appreciated.

**Comment by gryznar** [comment]
This issue may be related to usage of unsupported WSL version. Only version 2 is supported

**Comment by gryznar** [comment]
Also, I have seen at least one bug report related to crashpad

**Comment by TokaMohamed-QC** [comment]
@gryznar actually I used the WSL version that selected in website  and now it keeps displaying error to set the modular_home but I'm not finding the .modular

**Comment by gryznar** [comment]
I assume, that you have installed `modular`?

**Comment by gryznar** [comment]
How about command: `which modular`?

**Comment by ematejska** [comment]
Thank you for trying out Mojo.  The installation experience has significantly changed and we're closing out all the old issues with the old installer.  To try out our new installation experience using "magic", please see: https://docs.modular.com/mojo/manual/get-started.
