### ISSUE TITLE
[BUG]: open/FileHandle (4 bytes)

### ISSUE THREAD

**Issue by rd4com** [modularml/mojo#1062]
### Bug description

Hello, while verifying a reader_writer for a small tuto,
i noticed there was a memory leak of four bytes (1 block) .

It seems that it comes from open, but im not sure:
```python
fn main() raises:
    var f = open("bytes","r")
    var c = f.read()
    f.close()
```
but all the data is fine, it works great!

### Steps to reproduce

mojo build program.mojo

### System information

```shell
- ubuntu 23.04
- mojo v0.4.0
```

**Comment by abduld** [comment]
Thanks @rd4com for reporting this. This has been fixed in the next release
