### ISSUE TITLE
Unable to generate plots in the mandelbrot notebook under examples

### ISSUE THREAD

**Issue by entropich3atdeath** [modularml/mojo#1066]
The notebook runs fine, but I am unable to generate plots. Keep seeing the following issue - "failed to show plot: No module named 'numpy' ". 
I followed the install instructions on the modular website and do have numpy installed as well. I am new to this, so could be something obvious but can definitely use some help. Thanks!!

**Comment by gryznar** [comment]
You have to have numpy installed in your python env locally

**Comment by jackos** [comment]
Easiest way to fix this, is to put this in a cell and run it:
 
```python
%%python
import sys
import subprocess

subprocess.check_call([sys.executable, "-m", "pip", "install", "matplotlib"])
subprocess.check_call([sys.executable, "-m", "pip", "install", "numpy"])
```

**Comment by entropich3atdeath** [comment]
> Easiest way to fix this, is to put this in a cell and run it:
>  
> ```python
> %%python
> import sys
> import subprocess
> 
> subprocess.check_call([sys.executable, "-m", "pip", "install", "matplotlib"])
> subprocess.check_call([sys.executable, "-m", "pip", "install", "numpy"])
> ```

Worked. Thank you!

**Comment by jackos** [comment]
Great thanks @entropich3atdeath closing
