### ISSUE TITLE
[Modular CLI]: Seg fault when trying to update Mojo

### ISSUE THREAD

**Issue by xing216** [modularml/mojo#1067]
### Issue description

I ran 'modular update mojo' in a WSL terminal in VSCode. I came up with the attached errors.
[mojo_wsl_crash.txt](https://github.com/modularml/mojo/files/12974074/mojo_wsl_crash.txt)
[sudo_mojo_wsl_crash.txt](https://github.com/modularml/mojo/files/12974075/sudo_mojo_wsl_crash.txt)

### Steps to reproduce

- Include anything else that might help us debug the issue.
  - The last change I made to anything, I think, relevant was the modular home and path variables.

### Version Info

```shell
- modular 0.2.0 (355ea9c0)
- Windows 10 Pro 22H2
- 5.15.90.1-microsoft-standard-WSL2
  - Ubuntu 22.04.3 LTS
```

**Comment by ShuzhaoFeng** [comment]
@xing216 the issue has been reported at #1057 , which I'm also waiting for a solution.

Since I'm not admin I can't add duplicate tag, so just commenting to let you know 😃 .

**Comment by bzcheeseman** [comment]
Thanks @ShuzhaoFeng - I'll close this as a duplicate.
