### ISSUE TITLE
[Modular CLI]: Installation freezes after pip package installation 

### ISSUE THREAD

**Issue by jwendcheeseburger** [modularml/mojo#1068]
### Issue description

"modlar install mojo" Freezes after pip collected and installed required packages. Running on WLS Ubuntu 22.04.2 LTS. Followed the instructions on the Donwload page. 
I thought it might download something large in the background since a lot of people seemed to have this issue but letting it run over night (approx 9hrs) didn't do anything. Modular process was stuck at ~380MB memory usage and strace didn't yield any results
![mojobug](https://github.com/modularml/mojo/assets/146121263/0962b29f-7b90-4ab5-a549-8eafacb4295c)
### Steps to reproduce

- Run "modular install mojo"

### Version Info

```shell
- modular 0.2.0 (355ea9c0)
- WLS Ubuntu 22.04.2 LTS
```

**Comment by Sharktheone** [comment]
Which WSL version are you using? Currently only version 2 is supported. This also seems simmilar to #970 and #973

**Comment by jwendcheeseburger** [comment]
Yeah that fixed it
