### ISSUE TITLE
[BUG]: M1 Mac - Mojo hello world binary size unreasonably large

### ISSUE THREAD

**Issue by SimplyYummy** [modularml/mojo#1074]
### Bug description

After building the hello.🔥 program, the size of the binary is 327K. This is similar to the x86 linux issue that was fixed in an update and reduced to ~28kb. https://github.com/modularml/mojo/issues/599

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
        `mojo build hello.🔥`
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.
        Issue is on mojo v0.4.0 m1 macos release

### System information

```shell
- What OS did you do install Mojo on ?
M1 Mac via homebrew
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.4.0 (9e33b013)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.2.1 (5144fffe)
```

**Comment by Mogball** [comment]
Thanks for filing! This is a known issue: on Linux, the linker does a better job of stripping unused symbols from the compiled binary, but MacOS does a worse job. We'll look into it!

**Comment by SimplyYummy** [comment]
Closing this, as I believe the major concern regarding the size of the hello.🔥 binary on M1 Macs has been effectively addressed, as noted by @River707 [here](https://github.com/modularml/mojo/issues/1751#issuecomment-2035670339).

On mojo version `2024.4.117 (8f6529b0)`, the binary size is 272K, which can be further reduced to 208K with the `strip` command. While this further reduction is not substantial, there are more pressing issues than achieving complete optimization of the binary size.

Should the need for further size optimization arise, we can consider creating a separate issue tracker for that in the future.

Thanks to the mojo dev team for your efforts!
