### ISSUE TITLE
Manual install instructions for Mac

### ISSUE THREAD

**Issue by HelloFillip** [modularml/mojo#1076]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

It would be good at the very least to have manual instructions for Mac developers that allow a non-Homebrew installation.

### What is your motivation for this change?

Not using Homebrew at all, it’s frustrating to only have that as an option for a package.

**Comment by inspiredlabs** [comment]
I have tried installing `modular CLI` with `brew`, and it threw an error. I'd be interested in other people's experience with similar errors. See: https://github.com/modularml/mojo/issues/1089

**Comment by HelloFillip** [comment]
Specifically my requirement is to be able to install Mojo _without_ Homebrew. A simple manual installation option is what I'm looking for. Even the "manual" instructions depend on Homebrew.

**Comment by pupba** [comment]
I want this too. 
Due to the circumstances, it is impossible to delete and reinstall Brew.
This is essential to secure more 'mojo' users in the future.

**Comment by thatSAMazing** [comment]
Anyone know how to install the CLI without homebrew installed? Really don't want to install it

**Comment by conradwt** [comment]
I was also interested in installing Mojo without having to install another package manager on macOS.

**Comment by ematejska** [comment]
Thank you for trying out Mojo.  The installation experience has significantly changed and we're closing out all the old issues with the old installer.  To try out our new installation experience using "magic", please see: https://docs.modular.com/mojo/manual/get-started.
