### ISSUE TITLE
[Modular CLI]: error: failed to run python: Program could not be executed

### ISSUE THREAD

**Issue by krzyzanowskim** [modularml/mojo#1077]
### Issue description

I use https://asdf-vm.com/ version manager and it seems that modular somehow can't use python installed that way to install mojo

### Steps to reproduce

```
~ ❯ modular install mojo
# Found release for https://packages.modular.com/mojo @ 0.4.0
# Installing to /Users/marcinkrzyzanowski/.modular/pkg/packages.modular.com_mojo
# Downloading artifacts. Please wait...
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
No version is set for command python3
Consider adding one of the following versions in your config file at
python 3.10.4
python 3.11.4
python 3.12.0
modular: error: failed to run python: Program could not be executed
```

### Version Info

```shell
~ ❯ modular -version
modular 0.2.1 (5144fffe)

~ ❯ python --version
Python 3.12.0

~ ❯ python3 --version
Python 3.12.0

~ ❯ which python3
/Users/marcinkrzyzanowski/.asdf/shims/python3

~ ❯ uname -a
Darwin MarcinK.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103 arm64
```

**Comment by gsnyder2007** [comment]
Modular creates a venv where the python version is installed. If you set the venv, e.g.

source ~/.modular/pkg/packages.modular.com_mojo/venv/bin/activate

Then you can find the path the version of python expected using,

which python

In my case I got,

/Users/gsnyder/.modular/pkg/packages.modular.com_mojo/venv/bin/python

Now you can set the version of python Mojo should by setting MOJO_PYTHON_LIBRARY, e.g.

export MOJO_PYTHON_LIBRARY=/Users/gsnyder/.modular/pkg/packages.modular.com_mojo/venv/bin/python

In my case this corrected the issue where mojo could not resolve the correct version of python to use. 

Hope that helps.

Of course, after doing all that I hit a separate issue. In attempting to run matmul.mojo in the examples folder I ran into an error where mojo is attempting to install numpy and cannot do it. But that's a separate issue IMO which I plan to file shortly.

**Comment by krzyzanowskim** [comment]
> Modular creates a venv where the python version is installed. If you set the venv, e.g.
> source ~/.modular/pkg/packages.modular.com_mojo/venv/bin/activate

not finding anything like `venv` here. I tried to set the `MOJO_PYTHON_LIBRARY` like this
`export MOJO_PYTHON_LIBRARY=~/.asdf/installs/python/3.12.0/bin/python` 
or 
`export MOJO_PYTHON_LIBRARY=~/.asdf/installs/python/3.12.0/lib/libpython3.12.dylib`
but it didn't fix the installation for me.

**Comment by jackos** [comment]
@krzyzanowskim can you try this to fix:
```bash
brew install python3
```
And put this in your shell startup file e.g. `~/.zshrc`:
```bash
export MOJO_PYTHON_LIBRARY=/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/lib/libpython3.11.dylib
```

**Comment by gsnyder2007** [comment]
Hmm, I think that @jackos suggestion may work but I think the intent of modular CLI creating its own venv for mojo and python would be to tightly control the version of python used? Begs the quesion (in my mind) of what version(s) mojo (v0.4.0) supports?

I wonder if referencing a version of python outside this venv might lead to aberrant behavior in the _interaction_ between mojo and python (when importing and using python packages)? 

Perhaps someone from the modular team could weigh in here?

**Comment by gsnyder2007** [comment]
Aha @jackos , forgot about the conda recommended install path. makes sense, thanks.

**Comment by krzyzanowskim** [comment]
@jackos 
> And put this in your shell startup file e.g. ~/.zshrc

I tried that with python installed via asdf, and it didn't work out. If I understand it, it should work too, shouldn't it?
`export MOJO_PYTHON_LIBRARY=~/.asdf/installs/python/3.12.0/lib/libpython3.12.dylib`

**Comment by luosheng** [comment]
I don't think setting absolute path works. Modular still doesn't seem to resolve python path. Here're my full steps to reproduce: 

```
~ ❯ echo $MOJO_PYTHON_LIBRARY && ls $MOJO_PYTHON_LIBRARY
/Users/luosheng/.asdf/installs/python/3.12.0/lib/libpython3.12.dylib
/Users/luosheng/.asdf/installs/python/3.12.0/lib/libpython3.12.dylib
~ ❯ which python python3
/Users/luosheng/.asdf/shims/python
/Users/luosheng/.asdf/shims/python3
~ ❯ modular install mojo
# Found release for https://packages.modular.com/mojo @ 0.4.0
# Installing to /Users/luosheng/.modular/pkg/packages.modular.com_mojo
# Downloading artifacts. Please wait...
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
unknown command: python3. Perhaps you have to reshim?
modular: error: failed to run python:
```

**Comment by akaralar** [comment]
I use `asdf` to manage python versions and I have the exact same problem as @luosheng.

**Comment by hofstee** [comment]
You can get closer with [asdf-direnv](https://github.com/asdf-community/asdf-direnv) and running `modular` through that, but I'm still getting stumped on some issues.

```
$ modular clean
$ asdf direnv shell python 3.12.0 -- modular install mojo
...
Installing collected packages: wcwidth, textwrap3, pure-eval, ptyprocess, pickleshare, find_libpython, fastjsonschema, executing, backcall, appnope, urllib3, traitlets, tqdm, tornado, tenacity, six, rpds-py, pyzmq, pyyaml, pygments, psutil, prompt-toolkit, platformdirs, pexpect, parso, packaging, nest-asyncio, idna, entrypoints, decorator, debugpy, click, charset-normalizer, certifi, attrs, ansiwrap, requests, referencing, python-dateutil, matplotlib-inline, jupyter-core, jedi, comm, asttokens, stack-data, jupyter_client, jsonschema-specifications, jsonschema, ipython, nbformat, ipykernel, nbclient, papermill
Successfully installed ansiwrap-0.8.4 appnope-0.1.3 asttokens-2.4.0 attrs-23.1.0 backcall-0.2.0 certifi-2023.7.22 charset-normalizer-3.3.0 click-8.1.7 comm-0.1.4 debugpy-1.8.0 decorator-5.1.1 entrypoints-0.4 executing-2.0.0 fastjsonschema-2.18.1 find_libpython-0.3.0 idna-3.4 ipykernel-6.25.2 ipython-8.16.1 jedi-0.19.1 jsonschema-4.19.1 jsonschema-specifications-2023.7.1 jupyter-core-5.4.0 jupyter_client-8.4.0 matplotlib-inline-0.1.6 nbclient-0.8.0 nbformat-5.9.2 nest-asyncio-1.5.8 packaging-23.2 papermill-2.4.0 parso-0.8.3 pexpect-4.8.0 pickleshare-0.7.5 platformdirs-3.11.0 prompt-toolkit-3.0.39 psutil-5.9.6 ptyprocess-0.7.0 pure-eval-0.2.2 pygments-2.16.1 python-dateutil-2.8.2 pyyaml-6.0.1 pyzmq-25.1.1 referencing-0.30.2 requests-2.31.0 rpds-py-0.10.6 six-1.16.0 stack-data-0.6.3 tenacity-8.2.3 textwrap3-0.9.2 tornado-6.3.3 tqdm-4.66.1 traitlets-5.11.2 urllib3-2.0.7 wcwidth-0.2.8

[notice] A new release of pip is available: 23.2.1 -> 23.3
[notice] To update, run: pip install --upgrade pip
Traceback (most recent call last):
  File "/Users/hofstee/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 29, in <module>
    import papermill as pm
  File "/Users/hofstee/.modular/pkg/packages.modular.com_mojo/venv/lib/python3.12/site-packages/papermill/__init__.py", line 3, in <module>
    from .exceptions import PapermillException, PapermillExecutionError
  File "/Users/hofstee/.modular/pkg/packages.modular.com_mojo/venv/lib/python3.12/site-packages/papermill/exceptions.py", line 3, in <module>
    from ansiwrap import strip_color
  File "/Users/hofstee/.modular/pkg/packages.modular.com_mojo/venv/lib/python3.12/site-packages/ansiwrap/__init__.py", line 1, in <module>
    from .core import *
  File "/Users/hofstee/.modular/pkg/packages.modular.com_mojo/venv/lib/python3.12/site-packages/ansiwrap/core.py", line 6, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
modular: error: failed to run python:
```

**Comment by hofstee** [comment]
I'm realizing that the issue I was having was because Python 3.12 removed the `imp` module, so `asdf-direnv` at least serves as a workaround.

```
$ asdf direnv shell python 3.11.3 -- modular install mojo
...
$ mojo
Welcome to Mojo! 🔥
```

**Comment by jackos** [comment]
Thanks for the workaround @hofstee not familiar with `asdf`, thanks for posting the fix

**Comment by kenshih** [comment]
thanks @hofstee & @jackos for looking at this! 
i ran into this as well. MacBook Pro M1
```
> uname -a
Darwin kenloaner-mbp.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103 arm64
```

another workaround, if you're using asdf but not direnv
```
cd ~/.asdf
# this temporarily disable asdf
touch asdf_updates_disabled

# then do the install
modular clean
modular install mojo

# then re-enable asdf
rm asdf_updates_disabled
```

**Comment by hazulifidastian** [comment]
Workaround for windows wsl Ubuntu 20.04.6

Disable asdf loader inside .bashrc
```
# . $HOME/.asdf/asdf.sh
```

Exit wsl, and return to wsl again

Check python3 location

```
which python3

# make sure it's displayed
/usr/bin/python3
```

Clean and install mojo

```
apt install python3.8-venv

modular clean
modular install mojo
```

Enable asdf loader inside .bashrc
```
. $HOME/.asdf/asdf.sh
```
