### ISSUE TITLE
[Modular CLI]: Attempting to update via 'modular update mojo' segfaults

### ISSUE THREAD

**Issue by MostHated** [modularml/mojo#1087]
### Issue description

I simply attempted to run `modular update mojo` and receive the error below:

```
zsh ❯ modular update mojo
loc("#M.target<triple = \22x86_64-unknown-linux\22, cpu = \22znver4\22, features = \22+64bit,+adx,+aes,+avx,+avx2,+avx512bf16,+avx512bitalg,+avx512bw,+avx512cd,+avx512dq,+avx512f,+avx512ifma,+avx512vbmi,+avx512vbmi2,+avx512vl,+avx512vnni,+avx512vpopcntdq,+bmi,+bmi2,+clflushopt,+clwb,+clzero,+cmov,+crc32,+cx16,+cx8,+f16c,+fma,+fsgsbase,+fxsr,+gfni,+invpcid,+lzcnt,+mmx,+movbe,+mwaitx,+pclmul,+pku,+popcnt,+prfchw,+rdpid,+rdpru,+rdrnd,+rdseed,+sahf,+sha,+shstk,+sse,+sse2,+sse3,+sse4.1,+sse4.2,+sse4a,+ssse3,+vaes,+vpclmulqdq,+wbnoinvd,+x87,+xsave,+xsavec,+xsaveopt,+xsaves\22, data_layout = \22e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128\22, simd_bit_width = 512>":1:50): error: duplicate or unknown struct parameter name: cpu
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.

Stack dump:
0.	Program arguments: modular update mojo
 #0 0x000055d0e69acd47 (/usr/bin/modular+0x4e8d47)
 #1 0x000055d0e69aa9fe (/usr/bin/modular+0x4e69fe)
 #2 0x000055d0e69ad40f (/usr/bin/modular+0x4e940f)
 #3 0x00007f55d9442520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x000055d0e6d6d254 (/usr/bin/modular+0x8a9254)
 #5 0x000055d0e6d6c8df (/usr/bin/modular+0x8a88df)
 #6 0x000055d0e6988884 (/usr/bin/modular+0x4c4884)
 #7 0x000055d0e6987c6a (/usr/bin/modular+0x4c3c6a)
 #8 0x000055d0e696f053 (/usr/bin/modular+0x4ab053)
 #9 0x00007f55d9429d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#10 0x00007f55d9429e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#11 0x000055d0e696e6ee (/usr/bin/modular+0x4aa6ee)
[1]    2485672 segmentation fault (core dumped)  modular update mojo
```

### Steps to reproduce

All I attempted to do was:
- Run `modular update mojo`

### Version Info

- Provide Modular CLI version by pasting the output of `modular -v`: modular 0.2.1 (5144fffe)
- What OS did you install modular CLI on ?
See system info below:

<details>
<summary>System Details</summary>

```shell
OS: Ubuntu 22.04.3 LTS x86_64
Host: X670E Taichi
Kernel: 6.4.12-060412-generic
Uptime: 2 days, 12 hours, 15 mins
Packages: 3219 (dpkg), 71 (flatpak), 27 (snap)
Shell: zsh 5.8.1
Resolution: 2560x1080
DE: GNOME 42.9
WM: Mutter
WM Theme: Adwaita
Theme: Yaru-dark [GTK2/3]
Icons: Yaru [GTK2/3]
Terminal: alacritty
CPU: AMD Ryzen 9 7950X (32) @ 4.500GHz
GPU: AMD ATI 5a:00.0 Device 164e
GPU: AMD ATI Radeon RX 6800/6800 XT / 6900 XT
Memory: 29673MiB / 63398MiB
```

</details>

**Comment by jackos** [comment]
Looks related to: https://github.com/modularml/mojo/issues/1002

**Comment by MostHated** [comment]
Strange. I tried it again, just for giggles, and the output was different this time:

```sh
zsh ❯ modular update mojo
loc("#M.target<triple = \22x86_64-unknown-linux\22, cpu = \22znver4\22, features = \22+64bit,+adx,+aes,+avx,+avx2,+avx512bf16,+avx512bitalg,+avx512bw,+avx512cd,+avx512dq,+avx512f,+avx512ifma,+avx512vbmi,+avx512vbmi2,+avx512vl,+avx512vnni,+avx512vpopcntdq,+bmi,+bmi2,+clflushopt,+clwb,+clzero,+cmov,+crc32,+cx16,+cx8,+f16c,+fma,+fsgsbase,+fxsr,+gfni,+invpcid,+lzcnt,+mmx,+movbe,+mwaitx,+pclmul,+pku,+popcnt,+prfchw,+rdpid,+rdpru,+rdrnd,+rdseed,+sahf,+sha,+shstk,+sse,+sse2,+sse3,+sse4.1,+sse4.2,+sse4a,+ssse3,+vaes,+vpclmulqdq,+wbnoinvd,+x87,+xsave,+xsavec,+xsaveopt,+xsaves\22, data_layout = \22e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128\22, simd_bit_width = 512>":1:50): error: duplicate or unknown struct parameter name: cpu
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.	Program arguments: modular update mojo
[595007:595008:20231019,170038.267715:ERROR directory_reader_posix.cc:42] opendir /home/mosthated/.modular/crashdb/attachments/bbbf88a4-0d5b-457b-a752-70fda13c20be: No such file or directory (2)
 #0 0x00005639fd902d47 (/usr/bin/modular+0x4e8d47)
 #1 0x00005639fd9009fe (/usr/bin/modular+0x4e69fe)
 #2 0x00005639fd90340f (/usr/bin/modular+0x4e940f)
 #3 0x00007f649c242520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00005639fdcc3254 (/usr/bin/modular+0x8a9254)
 #5 0x00005639fdcc28df (/usr/bin/modular+0x8a88df)
 #6 0x00005639fd8de884 (/usr/bin/modular+0x4c4884)
 #7 0x00005639fd8ddc6a (/usr/bin/modular+0x4c3c6a)
 #8 0x00005639fd8c5053 (/usr/bin/modular+0x4ab053)
 #9 0x00007f649c229d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#10 0x00007f649c229e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#11 0x00005639fd8c46ee (/usr/bin/modular+0x4aa6ee)
[595007:595008:20231019,170038.533963:ERROR http_transport_libcurl.cc:483] HTTP status 404
[1]    594995 segmentation fault (core dumped)  modular update mojo
```

**Comment by corvinux** [comment]
Operating System: Kali GNU/Linux Rolling
Kernel: Linux 6.5.0-kali2-amd64
Architecture: x86-64
Hardware Vendor: Lenovo
Hardware Model: ThinkPad T560
`echo` $SHELL
`/usr/bin/bash`
`modular update mojo`
loc("#M.target<triple = \22x86_64-unknown-linux\22, cpu = \22skylake\22, features = \22+64bit,+adx,+aes,+avx,+avx2,+bmi,+bmi2,+clflushopt,+cmov,+crc32,+cx16,+cx8,+f16c,+fma,+fsgsbase,+fxsr,+invpcid,+lzcnt,+mmx,+movbe,+pclmul,+popcnt,+prfchw,+rdrnd,+rdseed,+sahf,+sgx,+sse,+sse2,+sse3,+sse4.1,+sse4.2,+ssse3,+x87,+xsave,+xsavec,+xsaveopt,+xsaves\22, data_layout = \22e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128\22, simd_bit_width = 256>":1:50): error: duplicate or unknown struct parameter name: cpu
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.      Program arguments: modular update mojo
 #0 0x000056071170fbb7 (/usr/bin/modular+0x4eebb7)
 #1 0x000056071170d86e (/usr/bin/modular+0x4ec86e)
 #2 0x000056071171027f (/usr/bin/modular+0x4ef27f)
 #3 0x00007f363025a510 (/lib/x86_64-linux-gnu/libc.so.6+0x3c510)
 #4 0x0000560711acd434 (/usr/bin/modular+0x8ac434)
 #5 0x0000560711accabf (/usr/bin/modular+0x8ababf)
 #6 0x00005607116eb6f4 (/usr/bin/modular+0x4ca6f4)
 #7 0x00005607116eaada (/usr/bin/modular+0x4c9ada)
 #8 0x00005607116d1ec3 (/usr/bin/modular+0x4b0ec3)
 #9 0x00007f36302456ca __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
#10 0x00007f3630245785 call_init ./csu/../csu/libc-start.c:128:20
#11 0x00007f3630245785 __libc_start_main ./csu/../csu/libc-start.c:347:5
#12 0x00005607116d155e (/usr/bin/modular+0x4b055e)
Segmentation fault

**Comment by MostHated** [comment]
I was able to 'resolve' this by clearing out the .modular folder/doing `modular clean`,  and then was able to run `modular install mojo`, which then worked at that point.

**Comment by jackos** [comment]
Great thanks for reporting back @MostHated
