### ISSUE TITLE
[BUG]: Apple Silicon installer throws: `modular: The arm64 architecture is required for this software. Error: modular: An unsatisfied requirement failed this build.`

### ISSUE THREAD

**Issue by inspiredlabs** [modularml/mojo#1089]
### Issue description

modular CLI won't install on Apple Silicon.

### Steps to reproduce

When I run `curl https://get.modular.com | \
  MODULAR_AUTH=mut_<TOKEN> \
  sh -`

it throws:

`Installing/upgrading Modular using Homebrew
modular: The arm64 architecture is required for this software.
Error: modular: An unsatisfied requirement failed this build.`

### Version Info

- Modular CLI isn't installed yet. It returns: `zsh: command not found: modular`
- running: `arch` returns: `arm64`
- running: `brew -v` returns: `Homebrew 4.1.16-11-g3480dda`
- running: `/usr/bin/xcodebuild -version` returns: `Xcode 14.1 / Build version 14B5024i`
- running: `env` returns `TERM_PROGRAM=Apple_Terminal // TERM_PROGRAM_VERSION=446 // SHELL=/bin/zsh // _system_type=Darwin // _system_name=OSX // _system_version=13.0`

**Comment by jackos** [comment]
Related to: https://github.com/modularml/mojo/issues/1078 please try the steps in there thanks
