### ISSUE TITLE
[Modular CLI]: install mojo on M1 Pro results in "invalid manifest: root json is missing or invalid"

### ISSUE THREAD

**Issue by tom-rigelblu** [modularml/mojo#1090]
### Issue description

I'm getting this error on Step 3
```sh
modular install mojo
modular: error: invalid manifest: root json is missing or invalid.
```

Please let me know what other info I can provide

### Steps to reproduce

- Setup brew to install packages in user's home dir
- Follow "Set up Mojo on Mac (Apple silicon)" instructions on https://developer.modular.com/download
- Add to ~/.zprofile
   ```
    # Modular
    MODULAR_HOME=~/.modular
    PATH=$PATH:$MODULAR_HOME
    ```

### Version Info

```shell
- modular 0.2.1 (5144fffe)

- Darwin MacBook-Pro--Tom.local 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000 arm64

- brew info modular
==> modularml/packages/modular: stable 0.2.1-final
Modular developer CLI tool
https://www.modular.com
/Users/tom-rb/homebrew/Cellar/modular/0.2.1-final (6 files, 57.9MB) *
  Built from source on 2023-10-19 at 15:31:19
From: https://github.com/modularml/homebrew-packages/blob/HEAD/Formula/modular.rb
==> Dependencies
Required: python@3.11 ✔
==> Requirements
Required: arm64 architecture ✔, macOS ✔
==> Caveats
The Modular tool expects or will create a MODULAR_HOME directory.
This defaults to `~/.modular`. You can create your own, and if you do,
please add `MODULAR_HOME=/path/to/your/dir` to your environment.
```

**Comment by shacron** [comment]
I get the same issue. This doesn't look right.

```
% modular install mojo
modular: error: invalid manifest: root json is missing or invalid
% rm -rf .modular/pkg/packages.modular.com_mojo 
% modular install mojo
modular: error: unable to bootstrap the TUF repository, missing bootstrap.json
% cat .modular/pkg/packages.modular.com_mojo/root.json
null%
% modular install mojo
modular: error: invalid manifest: root json is missing or invalid.
```

**Comment by bzcheeseman** [comment]
Can y'all try and run `brew --prefix` and post the output?

**Comment by shacron** [comment]
```
% brew --prefix
/Users/shac/local/homebrew
```

**Comment by tom-rigelblu** [comment]
```
brew --prefix
/Users/tom-rb/homebrew
```

**Comment by bzcheeseman** [comment]
Ah I see. We will start working on a permanent solution. For a temporary workaround, try `cp $(brew --prefix)/etc/modular/bootstrap.json $MODULAR_HOME` - we need that file in a place we can find it, and since your homebrew prefix is in a non-standard location, we can just move the file to a standard location :)

**Comment by shacron** [comment]
Additionally required `rm -rf .modular/pkg/packages.modular.com_mojo` to remove the corrupted root.json file in there. Then the install worked.

This fix leaves my system with a symlink `bootstrap.json@ -> ../../Cellar/modular/0.2.1-final/etc/modular/bootstrap.json`, which will be broken the next time mojo is updated. Further, everyone will that installs homebrew to a different path will encounter this and need to find the workaround. The file will be linked in `$(brew --prefix)/etc/modular/`, why not use it from there directly?

**Comment by bzcheeseman** [comment]
You could also copy the file directly, that probably makes more sense :) This is why I explained what we were trying to do, so that our wonderful community can suggest improvements!

**Comment by shacron** [comment]
Copying the file directly would still render it broken/inconsistent the next time the mojo package updates that file. A more stable fix that would require no end-user involvement would be to use the package manager to resolve package paths.

**Comment by bzcheeseman** [comment]
That's also true, but that file doesn't update very often and since this is a temporary fix, we should be able to roll out a permanent fix before it becomes a problem.

**Comment by tom-rigelblu** [comment]
Just an FYI, I did `cp` as you recommended but got the same error. I had to remove root.json as @shacron mentioned too for it to work

All good now. Installed successfully. Thanks for your help!

```sh
% modular install mojo
modular: error: invalid manifest: root json is missing or invalid.

% rm .modular/pkg/packages.modular.com_mojo/root.json
remove .modular/pkg/packages.modular.com_mojo/root.json? y

% modular install mojo
# Found release for https://packages.modular.com/mojo @ 0.4.0
# Installing to /Users/tom-rb/.modular/pkg/packages.modular.com_mojo
# Downloading artifacts. Please wait...
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
...
```

**Comment by ematejska** [comment]
Thank you for trying out Mojo.  The installation experience has significantly changed and we're closing out all the old issues with the old installer.  To try out our new installation experience using "magic", please see: https://docs.modular.com/mojo/manual/get-started.
