### ISSUE TITLE
[BUG]: Parser crashes with this simple code snippet

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1091]
### Bug description

Very simple incomplete code causes the parser to crash.

### Steps to reproduce

The following incomplete code snippet causes a parser crash

```mojo
fn f(a: Int = 1, b):
    ...
```

The language server works fine (shows red squiggly correctly) on the following:

```mojo
fn f(a: Int = 1, b: Int):
    ...
```

and

```mojo
fn f(a: Int, b):
    ...
```

### System information

```shell
- OS: Docker on macOS Intel
- mojo -v: mojo 0.4.0 (9e33b013)
- modular -v: modular 0.2.1 (5144fffe)
```

**Comment by lattner** [comment]
@laszlokindrat argument related?

**Comment by laszlokindrat** [comment]
Thanks for opening the ticket! I was able to reproduce the crash and it will be fixed in the next release. Please open a new issue if you run into something similar again.
