### ISSUE TITLE
[Feature Request] Support for macOS - Intel

### ISSUE THREAD

**Issue by jackos** [modularml/mojo#1092]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Tracking issue for supporting Mojo on macOS with Intel cpu's natively.

Currently, you can install Mojo in a docker container following the instructions here: https://developer.modular.com/download

Please upvote if you want to see macOS support on Intel cpu's so that we can prioritize accordingly.

**Comment by aespeiuk22** [comment]
Is this closed? 
Confusing as the search for Intel MAC's are leading me from one thread to another and then says closed..
When is Intel MAC's going to be supported?
My MAC i9 is very powerful and as it is AI ML time, old school work is extinct and need to use it for AI ML based work and it would be great if MA Intel was supported.

**Comment by wafwoof** [comment]
Please add Intel support.
Macs from pre-2020 would benefit greatly, but the hackintosh community also... x86_64 Macs alike.

**Comment by Moosems** [comment]
Would be very nice.

**Comment by thierrymoudiki** [comment]
> Is this closed? Confusing as the search for Intel MAC's are leading me from one thread to another and then says closed.. When is Intel MAC's going to be supported? My MAC i9 is very powerful and as it is AI ML time, old school work is extinct and need to use it for AI ML based work and it would be great if MA Intel was supported.

+ +1

**Comment by jackos** [comment]
@aespeiuk22 @thierrymoudiki @Moosems no this ticket is not closed:
<img width="716" alt="image" src="https://github.com/modularml/mojo/assets/77730378/2cbb258a-ed83-4ffd-8e83-2703c2b71ff1">

The arm64 one is closed as it's completed:
<img width="863" alt="image" src="https://github.com/modularml/mojo/assets/77730378/977c032c-46a1-4fa1-bb95-a43fd674537f">

**Comment by thierrymoudiki** [comment]
@jackos thanks

**Comment by mikekppp** [comment]
+1

**Comment by rdsaylor-noaa** [comment]
There are still a lot of Intel-based Macs out there - please support!

**Comment by johnwind1001** [comment]
+1

**Comment by aespeiuk22** [comment]
Why no progress on this?

There is no movement.

I have a very powerful intel and without native support I will be stuck with the capabilities of m1 air to test advanced capabilities.

**Comment by Moosems** [comment]
Its not a fast process...

**Comment by wafwoof** [comment]
An update or mention of this issue in any way would be appreciated. I understand porting takes time, but getting the maximum number users interested in Mojo development is key.

**Comment by rdsaylor-noaa** [comment]
@wafwoof Apparently, Modular's product development plan for Mojo (a.k.a. Hype-O) is to release a super-hyped but barely functional language on a handful of platforms in the hope that the community will serve as their extended (but unpaid) development team.  I'm giving up on Mojo for now.  Maybe in a couple of years (or ten) it will live up to its promise.

**Comment by Moosems** [comment]
@rdsaylor-noaa May I ask as to the source of this "information"? Thats a very strong claim with no evidence to back it up.

**Comment by rdsaylor-noaa** [comment]
@Moosems No evidence whatsoever.  Just my opinion based on what I've observed.

**Comment by Moosems** [comment]
@rdsaylor-noaa So you are making an opinion-based claim without any evidence that Modular hopes to make the community do the work for free so they can use us for an extended unpaid development team of what you call a "super-hyped but barely functional language"?

**Comment by thierrymoudiki** [comment]
For now, I'm using mojo on Codespaces (ubuntu linux)...

**Comment by walter-erquinigo** [comment]
Thank you for reporting this. I'm closing this for now. Eventually we'll include other OS - architectures.

**Comment by wafwoof** [comment]
that sucks but it makes sense

**Comment by stringydev** [comment]
Any update on adding Intel Mac support? Dying to get my hands on Mojo.

**Comment by walter-erquinigo** [comment]
Not yet in sight because of our focus on the GPU effort. Hopefully in 2025 we'll focus on it.

**Comment by walter-erquinigo** [comment]
Maybe @jackos knows about that

**Comment by Moosems** [comment]
@stringydev Yes, just make an Ubuntu docker image and ssh in
