### ISSUE TITLE
[Feature Request] Support for Linux arm64 CPU's

### ISSUE THREAD

**Issue by jackos** [modularml/mojo#1093]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Tracking issue for supporting Mojo on Linux with arm64 cpu's natively.

Please upvote if you want to see Linux support on arm64 cpu's so that we can prioritize accordingly.

**Comment by creategui** [comment]
nvidia jetson family support would be nice

**Comment by Saddibek1** [comment]
+1

**Comment by twkun** [comment]
+1

**Comment by mikekppp** [comment]
+1
Related to [[Feature Request] Support for Raspberry Pi #945](https://github.com/modularml/mojo/issues/945).

**Comment by oe5rnl** [comment]
Yes, Support for  Raspberry Pi!

**Comment by hybrid-robotics** [comment]
Please add support for Arm CPUs. Support for NVIDIAs Orin series development kits and Raspberry Pi 4 & 5, would be awesome!

**Comment by morne** [comment]
+1

**Comment by jackos** [comment]
arm64 support for Linux was added in 24.01

**Comment by gryznar** [comment]
@jackos It was added? It is strange, that changelog did not mentioned that! Android like OSes are huge topic

**Comment by LCrossman** [comment]
For Raspberry Pi:  
I have installed modular and mojo
Linux raspberrypi 6.6.20+rpt-rpi-2712 https://github.com/modularml/mojo/pull/1 SMP PREEMPT Debian 1:6.6.20-1+rpt1 (2024-03-07) aarch64 GNU/Linux
for Debian Bookworm aarch64 on Raspberry Pi 5
mojo-aarch64-unknown-linux-gnu-24.2.0-c2427bc5-release-11-0.tar.gz
and can confirm mojo is running hello world
under mojo --version mojo 24.2.0

```
pi@raspberrypi:~ $ mojo hello.mojo
Hello, world!
```

**Comment by yeison** [comment]
I tried to install mojo using the magic-cli on Debian Bookworm, but I just get this strange error:

`bash: /home/yeison/code/mojo/arm.mojo/.magic/envs/default/bin/mojo: cannot execute: required file not found`
