### ISSUE TITLE
[BUG]: Error: expected str, bytes or os.PathLike object, not PosixPath

### ISSUE THREAD

**Issue by dvrshil** [modularml/mojo#1095]
### Bug description

I was running the mandelbrot notebook from the examples, the fifth code cell where matplotlib python module is imported. While loading the matplotlib module the error shows up as mentioned in the issue title.

### Steps to reproduce

plt = Python.import_module("matplotlib.pyplot")

### System information

```shell
- MacOS Sonoma 14.0 [M1 Pro Macbook Pro]
- mojo 0.4.0 (9e33b013)
- modular 0.2.1 (5144fffe)
```

**Comment by jackos** [comment]
Closing in favor of https://github.com/modularml/mojo/issues/1547
