### ISSUE TITLE
[BUG]: VSCode doesn't highlight properties of `PythonObject`s correctly

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1098]
### Bug description

As title. Also, it says `__getattr__`, which doesn't match the name of the property accessed. Maybe `PythonObject` has some magic built in that causes this?

### Steps to reproduce

Consider the following code snippet:
```mojo
from python import Python


def main():
    let o = Python.import_module("math")
    _ = o.sin(1).to_float64()#
```

Notice the blue shade extending beyond `sin` in the screenshot:

<img width="716" alt="Screenshot 2023-10-19 at 23 53 04" src="https://github.com/modularml/mojo/assets/6129707/6c693539-1e79-44ea-a362-7d039640ba10">

### System information

```shell
- OS: Docker on macOS Intel
- mojo -v: mojo 0.4.0 (9e33b013)
- modular -v: modular 0.2.1 (5144fffe)
```

**Comment by River707** [comment]
Thanks for filing! Must be some weird source location handling in the lsp, will take a look!

**Comment by River707** [comment]
This should be fixed in the next release!
