### ISSUE TITLE
[BUG]: M1 Mac new installation: errors on python (matplotlib) code in notebook

### ISSUE THREAD

**Issue by rdickert** [modularml/mojo#1099]
### Bug description

Fresh install of mojo today! 🔥  

Mojo itself seems to work, but the graphs in the Mandelbrot demo all fail to print with different errors in Jupyter and VSCode.

I'm relatively new to Python environments and use `micromamba` to install packages, but I also have used `pip`. I'm not clear which environment is being used by mojo or if it's a new one created by mojo. I don't believe I have ever installed the original `conda` lib or other variants, only `micromamba`. I aliased `conda` to `micromamba` in my .zshrc file

Trying to set `MOJO_PYTHON_LIBRARY` to either `micromamba/bin/python` or something like `micromamba/envs/my-env/bin/python` don't seem to have an effect.

### Steps to reproduce

- Open Mandelbrot.ipynb in Jupyter or VSCode (slightly different outputs, see below)
- Select the Mojo kernel and run each step of the code

**Result:** 

All mojo functions seem to run

Here's the benchmark on my M1 MBP Max
```
Number of threads: 10
Vectorized: 29.883731000000001 ms
Parallelized: 4.7389469999999996 ms
Parallel speedup: 6.3059854858051807
```

**Errors**

On `show_plot(compute_mandelbrot())` (or any `show_plot()` call):

Jupyter notebook: 

```failed to show plot: invalid decimal literal (uuid.py, line 138)```

VSCode notebook: 
```
failed to show plot: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
```

not sure if this is helpful, but running `print(find_spec("matplotlib"))` in the vscode notebook returns
```
ModuleSpec(name='matplotlib', loader=<_frozen_importlib_external.SourceFileLoader object at 0x1052c0650>, origin='/Users/.../micromamba/lib/python3.12/site-packages/matplotlib/__init__.py', submodule_search_locations=['/Users/.../micromamba/lib/python3.12/site-packages/matplotlib'])

```

### System information

```shell
- macos 13.5.2
- mojo 0.4.0 (9e33b013)
- modular 0.2.1 (5144fffe)

- default shell: zsh 5.9 (x86_64-apple-darwin22.0) <- not sure if x86 name indicates a problem? `arch` in the shell is `arm64`

"base" env (was empty, I tried installing numpy and matplotlib)
- python 3.12 
- micromamba 1.5.2
- pip 23.3

Note that without activation, there are no conda packages installed, but `pip list`s numpy and matplotlib and the same python
```

**Comment by jackos** [comment]
Hi @rdickert micromamba doesn't come with libpython I believe, see steps here to install miniconda and fix it: https://github.com/modularml/mojo/issues/1085#issuecomment-1771403719

**Comment by rdickert** [comment]
Thank you, this solved the problem 👍 

For anyone else who is having similar problems, I'll also note that vscode seems to require a full restart to reflect the change.
