### ISSUE TITLE
Python 3.12 is not supported

### ISSUE THREAD

**Issue by mooseyacky** [modularml/mojo#1101]
### Bug description

The ansiwrap module is installed in the install script and seems pretty deprecated at this point given the last push was 5 years back. Not only this, it tries to import `imp` which was deprecated in 3.4 and removed in 3.12.

### Steps to reproduce

According to a user, they received an ansiwrap error in the installation test.

https://discord.com/channels/1087530497313357884/1098713601386233997/1164698877467836517

### System information

```shell
- What OS did you do install Mojo on ?
macOS M1
- Provide version information for Mojo by pasting the output of `mojo -v`
I dunno :(. 0.4.0 I assume
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by smuniraj2018** [comment]
Closing as we are tracking via #1102
