### ISSUE TITLE
[Modular CLI]: 

### ISSUE THREAD

**Issue by krish-shar** [modularml/mojo#1103]
### Issue description

Unable to install Mojo

### Steps to reproduce

Just running 
`modular install mojo`
outputs 
`modular: error: invalid manifest: root json is missing or invalid.`

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.2.1 (5144fffe)
- What OS did you install modular CLI on ?
macOS Sonoma
```

**Comment by tom-rigelblu** [comment]
They posted a temporary workaround in https://github.com/modularml/mojo/issues/1090
