### ISSUE TITLE
[BUG]: Manual install on macOS 13.6 fails

### ISSUE THREAD

**Issue by domesticmouse** [modularml/mojo#1105]
### Bug description

Attempting to manually install mojo fails

```console
$ modular install mojo
modular: error: invalid manifest: root json is missing or invalid.
```

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

- What OS did you do install Mojo on ?

```console
$ uname -m -r -s -v
Darwin 22.6.0 Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000 arm64
```

- Provide version information for Mojo by pasting the output of `mojo -v`

```console
$ mojo -v
zsh: command not found: mojo
```

- Provide Modular CLI version by pasting the output of `modular -v`

```console
$ modular -v
modular 0.2.1 (5144fffe)
```

**Comment by Moosems** [comment]
Have you tried reinstalling the modular package manager?

**Comment by domesticmouse** [comment]
```shell
$ brew reinstall modular
==> Fetching modularml/packages/modular
==> Downloading https://dl.modular.com/public/installer/raw/names/modular-mac-arm64/versions/la
Already downloaded: /Users/brettmorgan/Library/Caches/Homebrew/downloads/1f5b8eb993fdfa0f53ff0275ee0a0f95230623bdf58ae0996fd1fd60e3223783--modular-v0.2.1-macos-arm64.tar.gz
==> Reinstalling modularml/packages/modular
==> Caveats
The Modular tool expects or will create a MODULAR_HOME directory.
This defaults to `~/.modular`. You can create your own, and if you do,
please add `MODULAR_HOME=/path/to/your/dir` to your environment.
==> Summary
🍺  /Users/brettmorgan/homebrew/Cellar/modular/0.2.1-final: 6 files, 57.9MB, built in 2 seconds
==> Running `brew cleanup modular`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
$ modular install mojo
modular: error: invalid manifest: root json is missing or invalid.
```

**Comment by Moosems** [comment]
Very interesting 😄.

**Comment by domesticmouse** [comment]
Might be due to my non-standard homebrew location in my homedir.

**Comment by Moosems** [comment]
Possibly 🙂.

**Comment by smuniraj2018** [comment]
Closing as its tracked via #1102

**Comment by ematejska** [comment]
Thank you for trying out Mojo.  The installation experience has significantly changed and we're closing out all the old issues with the old installer.  To try out our new installation experience using "magic", please see: https://docs.modular.com/mojo/manual/get-started.
