### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by AvinashPrajapati** [modularml/mojo#1106]
### Bug description

**Running this code in vscode in Windows Linux WSL:**
fn main() raises:
    # let random = Python.import_module("random")

    # let a = random.randrange(2,10)
    let np = Python.import_module("numpy")
    # var array = np.array([1, 2, 3])
    let array = np.array([1, 2, 3])
    print(array)

**OUTPUT:** 
Unhandled exception caught during execution: An error occurred in Python.
mojo: error: execution exited with a non-zero result: 1

**ALSO**
Same uses in case of random module works fine.
Also fix **@strict** def as it is not working as mentioned in doc.
thanks.

### Steps to reproduce
- code snippets
fn main() raises:
    # let random = Python.import_module("random")

    # let a = random.randrange(2,10)
    let np = Python.import_module("numpy")
    # var array = np.array([1, 2, 3])
    let array = np.array([1, 2, 3])
    print(array)
- If applicable, add screenshots to help explain the problem.
<img width="1013" alt="Screenshot 2023-10-20 112016" src="https://github.com/modularml/mojo/assets/62180007/7efbd104-5c2a-4512-a937-8e56c64cbb52">

- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
Window - linux substystem
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.3.1 (a3eed7c8)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.2.0 (355ea9c0)
```

**Comment by AvinashPrajapati** [comment]
also please mention me use of @strict def

**Comment by jackos** [comment]
Hi @AvinashPrajapati `random` is a stdlib module, to get `numpy` working try following these steps here: https://github.com/modularml/mojo/issues/1085#issuecomment-1771403719

Please reopen with the error if this doesn't resolve your issue thanks
