### ISSUE TITLE
[BUG]: hello_interop.mojo fails to install numpy

### ISSUE THREAD

**Issue by nicholasbook** [modularml/mojo#1111]
### Bug description

The hello_interop.mojo example fails to install numpy with the following error:

`% mojo hello_interop.mojo
Hello Mojo 🔥!
9
6
3
Numpy not found, installing...
/Users/nicholas/.modular/pkg/packages.modular.com_mojo/bin/mojo: error: unrecognized argument '-m'
Command '['/Users/nicholas/.modular/pkg/packages.modular.com_mojo/bin/mojo', '-m', 'pip', 'install', 'numpy']' returned non-zero exit status 1. could not find module simple_interop`

### Steps to reproduce

1) Clean install of mojo on macOS with brew. 
2) Conda environment activated with python 3.11.4 but no numpy installed.
3) In `examples` directry, call `mojo hello_interop.mojo`.

### System information

```shell
- What OS did you do install Mojo on ?
macOS Ventura 13.6
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.4.0 (9e33b013)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.2.1 (5144fffe)
```

**Comment by seanaguinaga** [comment]
Same issue

**Comment by jackos** [comment]
Thanks @nicholasbook  I'll address this now

**Comment by gmazz** [comment]
![image](https://github.com/modularml/mojo/assets/2866266/a903dd6e-c98c-43ec-83e6-e1c364f73bd5)
I had the same issue, the problem is that Mojo is not using the Numpy in the current Python virtualenv.

**Comment by gmazz** [comment]
After installing Numpy on the python version used by Mojo everything worked fine.
![image](https://github.com/modularml/mojo/assets/2866266/a1d0f537-06f5-4302-8bb3-d75658906712)

**Comment by gmazz** [comment]
You can check what the Python version Mojo is referencing from the REPL as explained in the Mojo documentation (https://www.modular.com/blog/using-mojo-with-python)

![image](https://github.com/modularml/mojo/assets/2866266/126d6fb4-9c27-4b8a-801e-27451776955f)

**Comment by nicholasbook** [comment]
@gmazz makes sense, thank you. I agree that mojo should automatically detect and use the packages from the currently activated venv / conda environment.

**Comment by jackos** [comment]
Thanks @nicholasbook have made the fix, should work now for venv and conda
