### ISSUE TITLE
[Feature Request] Faster and secure access speed: dict [T, U] data type

### ISSUE THREAD

**Issue by 1138886114** [modularml/mojo#1114]
Except for Python's dictionary and C++'s unordered_ Map, I hope there is another and a new hashmap with the following features:

For example:

```python

Foo1 [str, int]={"a": 10, "b": 2, "c": 10, "d": 20, "e": 10, "f": 10}

Foo2 [str, str]={"a": "1", "b": "2", "c": "3", "d": "3", "e": "3", "f": "3"}

```

1. Key-value pairs can be initialized during declaration, and all keys can be obtained during compilation.

2. When using the foo variable, only the values of key value pairs can be modified.

3. You can never delete existing key value pairs or insert new key value pairs.

4. Foo can be reinitialized or cleared as follows:

```python

Foo1 [str, int]={"a": 0, "b": 0, "c": 0, "d": 0, "e": 0, "f": 0}

Foo2 [str, str]={"a": "", "b": "", "c": "", "d": "", "e": "", "f": ""}

```

Explanation: I hope this hashmap can have extremely faster and secure access speed.
At certain times in the project, I need to frequently traverse and access the dictionary (which has many key value pairs) to obtain or modify values, but this process does not require adding or deleting the dictionary key value pairs,
I also need to clear the dictionary and reuse it again without adding a new key.

**Comment by 1138886114** [comment]
3. You can never delete existing key value pairs or insert new key value pairs.

**Comment by gryznar** [comment]
+1
