### ISSUE TITLE
[Dev Console]: (debugConfiguration.env || []) is not iterable

### ISSUE THREAD

**Issue by danny-su** [modularml/mojo#1116]
### Issue description

(debugConfiguration.env || \[\]) is not iterable

### Steps to reproduce

* Add screenshots if possible, to help explain the problem.
* Include anything that might help us debug the issue.

![image](https://uploads.linear.app/2f794fde-0e09-4092-aa52-1ed3e9241f74/9fe2b774-dc56-4919-b264-d70d00f4fc4f/b6dd3a9a-a7a9-41f4-afb5-38a2281c14e9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzJmNzk0ZmRlLTBlMDktNDA5Mi1hYTUyLTFlZDNlOTI0MWY3NC85ZmUyYjc3NC1kYzU2LTQ5MTktYjI2NC1kNzBkMDBmNGZjNGYvYjZkZDNhOWEtYTdhOS00MWY0LWFmYjUtMzhhMjI4MWMxNGU5IiwiaWF0IjoxNzE0NjAyMTU1LCJleHAiOjMzMjg1MTYyMTU1fQ.InVp-4hbp49g8xcRjG4mWfFcmr2h-GRKyb_wDEuUgYE "=1275x")

**Comment by PaulFWatts** [comment]
I'm have the exact same error running the following:
Windows 11
WSL Ubuntu 22.04.03 LTS
Mojo 0.4.0 (9e33b013)
Visual Studio Code 1.83.1
Mojo extension (latest release)

**Comment by guidorice** [comment]
➕ 1

mojo 0.5.0 (6e50a738)
modular 0.2.2 (95d42445)
Darwin macbookair.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:31 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8112 arm64

**Comment by guidorice** [comment]
Summary: it seems the mojo debugger is not currently usable from vscode .

**Comment by carlca** [comment]
I would urge Modular to make fixing this the number one priority for Mojo 0.6.0. It's not just a QoL fix, but, rather, an improvement that would surely accelerate the production of quality code by the community as a whole!
