### ISSUE TITLE
[BUG]: Mac M1 Failed to start the kernel on Jupyter notebooks inside VSCode

### ISSUE THREAD

**Issue by LGTiscar** [modularml/mojo#1121]
### Bug description

# Bug behaviour

Hello! 

Fresh Mac M1 Mojo installation today! It works just fine when working and running mojo files, but when trying to use jupyter notebook inside VScode, the next error message is raised:

```No se pudo iniciar el Kernel. 
OSError: dlopen(/Users/luisgarcia/.modular/pkg/packages.modular.com_mojo/lib/libMojoJupyter.dylib, 0x0006): tried: '/Users/luisgarcia/.modular/pkg/packages.modular.com_mojo/lib/libMojoJupyter.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/luisgarcia/.modular/pkg/packages.modular.com_mojo/lib/libMojoJupyter.dylib' (no such file), '/Users/luisgarcia/.modular/pkg/packages.modular.com_mojo/lib/libMojoJupyter.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')). 
Vea el [registro] de Jupyter (command:jupyter.viewOutput) para obtener más detalles.
```

I have seen other issues where, as Mojo uses Python envs when first installed, if that Python environment does not have ipykernel, it cannot start the kernel. Despite that, I have seen that now it creates a new venv when installed.

This is the Python env that mojo is using right now as when choosing Mojo as Jupyter's Kernel
```
/Users/luisgarcia/.modular/pkg/packages.modular.com_mojo/venv/bin/python
```

Tried to activate that venv and install ipykernel, and checked if it was installed with pip list:

```ipykernel                 6.25.2 ```

But still raises the error...

### Steps to reproduce

1. Install Modular SDK and Mojo as told in the installation guide
2. Add Modular to PATH using ```echo 'export MODULAR_HOME="/Users/luisgarcia/.modular"' >> ~/.zshrc
echo 'export PATH="/Users/luisgarcia/.modular/pkg/packages.modular.com_mojo/bin:$PATH"' >> ~/.zshrc
source ~/.zshrc```
3. Install Mojo VSCode extension
4. Choose Kernel for Jupyter notebook file, choose Jupyter Kernels dropdown list, choose Mojo
5. Try to execute a cell.

### System information

```shell
- What OS did you do install Mojo on ?
MacOs Sonoma
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.4.0 (9e33b013)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.2.1 (5144fffe)
```

**Comment by SimplyYummy** [comment]
## Probable Cause:
The core of the issue lies in the architectural mismatch between the dylib file and your Mac M1 chip. Mac M1 chips are based on the 'arm64' architecture, while most previous Macs run on 'x86_64'. The error message suggests that the libMojoJupyter.dylib was compiled for 'x86_64', which is not compatible with 'arm64'.

## Potential Solutions:

1. **Verify Homebrew Architecture** :
   - Homebrew can have installations specific to 'arm64' and 'x86_64'. Ensure you're using the 'arm64' version for M1 Macs.
   - To check the Homebrew architecture, see https://github.com/modularml/mojo/issues/1078#issuecomment-1771674021

**Comment by River707** [comment]
Yeah, this is often an indication that homebrew and friends are in x86_64 mode, which conflicts with mojo (which is arm64). Please make sure that your environment is using arm64.
