### ISSUE TITLE
[Modular CLI]: Install fails on Mac with M2 Max CPU

### ISSUE THREAD

**Issue by kkrugler** [modularml/mojo#1123]
### Issue description

I'm trying to install Mojo on my Mac, following instructions at https://developer.modular.com/download after I've logged into my account, but the install fails.

### Steps to reproduce

Running `curl https://get.modular.com | sh - && modular auth <auth token>` results in:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3885  100  3885    0     0  20581      0 --:--:-- --:--:-- --:--:-- 20775
Updating Homebrew
Already up-to-date.
Installing/upgrading Modular using Homebrew
modular: The arm64 architecture is required for this software.
Error: modular: An unsatisfied requirement failed this build.
```

### Version Info

```shell
Mac running 13.5, with M2 Max CPU.
```

**Comment by aespeiuk22** [comment]
go to applications folder, select terminal app, under its options, uncheck Rosetta and try. Got the same issue fixed earlier.

**Comment by kkrugler** [comment]
Thanks - but my `Open using Rosetta` option currently isn't checked.

**Comment by aespeiuk22** [comment]
please try the discord. you get more people to look into this.

**Comment by aespeiuk22** [comment]
https://discord.gg/modular

**Comment by kkrugler** [comment]
Thanks @aespeiuk22! I found a discussion on Discord that referenced https://github.com/modularml/mojo/issues/1078, and it looks like the issue is that my homebrew was installed for Intel. So I have to uninstall and re-install it :( That would be really useful information to include on the page about setting up Mojo on a newer Mac...

**Comment by aespeiuk22** [comment]
@jackos Please note.

**Comment by jackos** [comment]
Hi @kkrugler yes has been a common issue, we should include an error message, uninstalling and reinstalling is the way to fix: https://github.com/Homebrew/install#uninstall-homebrew

@bzcheeseman @zbowling fyi lots of users have x86 homebrew installed on their arm64 machine, can we guide them to the above instructions in that scenario or just show the steps to uninstall and reinstall?

**Comment by kkrugler** [comment]
Hi @jackos - thanks, that worked! Though I had to edit the `brew-uninstall.sh` script to get it to work, my (ancient) brew install was located at `/usr/local/homebrew`, and I had to manually remove this directory when the uninstall was finished.
