### ISSUE TITLE
[Modular CLI]: 

### ISSUE THREAD

**Issue by ANEASER** [modularml/mojo#1124]
### Issue description

installing error. stcuk for long time on python package installing on wsl. "modular install mojo"

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
- What OS did you install modular CLI on ?
```

**Comment by smuniraj2018** [comment]
Please check your internet speed and retry again. We also recommend using WSL2 in case if you haven't upgraded still
