### ISSUE TITLE
[BUG]:  Mac M1 can normally run the llama2.mojo, but can't import any library like from DType import DType

### ISSUE THREAD

**Issue by linhduongtuan** [modularml/mojo#1129]
### Bug description

Hi all,

I can install modular and mojo on my Mac M1 and  can successfully run the llama2.mojo
However, I can't import any library such as:
from DType import DType
from Functional import vectorize
from Intrinsics import compressed_store
and among others

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

from DType import DType
from Functional import vectorize
from Intrinsics import compressed_store
from Math import iota, any_true, reduce_bit_count
from Memory import *
from Pointer import DTypePointer
from String import String, ord
from TargetInfo import dtype_simd_width
from Vector import DynamicVector
from python import Python

fn main() raises:
	let torch = Python.import_module("torch")
	let x = torch.linspace(0, 10, 100)
	let y = torch.sin(x)
	plot(x, y)

def plot(x: PythonObject, y: PythonObject) -> None:
	let plt = Python.import_module("matplotlib.pyplot")
	plt.plot(x.numpy(), y.numpy())
	plt.xlabel('x')
	plt.ylabel('y')
	plt.title("Plot of y = sin(x)")
	plt.grid(True)
	plt.show()

<img width="657" alt="Untitled" src="https://github.com/modularml/mojo/assets/22388092/58a25ebe-c1de-48f6-9b7a-8fcadc705537">

### System information

```shell
- What OS did you do install Mojo on ? 
MacOS Sonoma

- Provide version information for Mojo by pasting the output of `mojo -v` 
mojo 0.4.0 (9e33b013)

- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.2.1 (5144fffe)
```

**Comment by abdullahselek** [comment]
Hi @linhduongtuan try importing `DynamicVector` from `utils.vector` using `from utils.vector import DynamicVector`.

**Comment by linhduongtuan** [comment]
Thank @abdullahselek it works for importing DynamicVector from utils.vector. However, it doesn't work while trying to import the other libraries at all.

**Comment by ematejska** [comment]
You will need to import these modules from the Mojo library.  Please take a look at the names of the modules and what's available here: https://docs.modular.com/mojo/
