### ISSUE TITLE
[Modular CLI]: Install fails on Mac using a `rye` managed python

### ISSUE THREAD

**Issue by geoqiao** [modularml/mojo#1131]
### Issue description

I'm trying to install Mojo on my Mac, following instructions at https://developer.modular.com/download after I've logged into my account. `brew install modular ` is successful, but `modular install mojo` is failed.

### Steps to reproduce

`modular install mojo` failed:
When running `modular install mojo` ,  results in:
```
$ modular install mojo
# Found release for https://packages.modular.com/mojo @ 0.4.0
# Installing to /Users/geoqiao/.modular/pkg/packages.modular.com_mojo
# Downloading artifacts. Please wait...
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
error: could not determine home folder
modular: error: failed to run python:
```

### Version Info

```shell
$ modular -v
modular 0.2.1 (5144fffe)
```

os:
```
Apple M1 Pro macOS 14.1
```

Other information:
I'm using `rye` to manage my Python environment. I have tried to uninstall `rye`, but it doesn't work. 
When `brew install modular`, it downloaded a python3.11.
```

**Comment by detrin** [comment]
I am experiencing the same problem with `modular 0.2.2 (95d42445)`

**Comment by jackos** [comment]
Hi @geoqiao `rye` uses a shim to redirect to a path like `~/.rye/py/cpython@3.12.3/bin/python3.12`, the shim is a custom binary that isn't compatible with Mojo (pyenv shim works). You can change `PYTHONHOME` and `MOJO_PYTHON_LIBRARY` to work around this e.g.:
```
export PYTHONHOME="/Users/jack/.rye/py/cpython@3.12.3"
export MOJO_PYTHON_LIBRARY="/Users/jack/.rye/py/cpython@3.12.3/lib/libpython3.12.dylib"
```
Then you can use the rye managed python environment to install Mojo and for interop. I can't think of an obvious way to resolve this without making a contribution to `rye` but I'll leave this open for future tracking.

**Comment by jradxl** [comment]
I'm using Rye, and wanted to try Mojo on Ubuntu 24.04
I did some googling before I tried to see if there was compatibility issues....
Before installing Modular I added PYTHONHOME and MOJO_PYTHON_LIBRARY in advance.
BUT
I noticed that pip list and pip -V were not working
Googling suggests that removing `PYTHONHOME` and indeed that fixed pip.
```
$ pip -V
pip 24.0 from /usr/lib/python3/dist-packages/pip (python 3.12)
```
BUT this pip is from Ubuntu packages, and Rye has built python itself.
A recipe for disaster!

I thought I'd try to continue.
Created a Rye project and entered the .venv
But modular install max failed 
`[mojo][error] Mojo SDK post-install test "`mojo build test_python.mojo`" failed:`

I think I'll give up and create and use a different user account for mojo

**Comment by ematejska** [comment]
Thank you for trying out Mojo.  The installation experience has significantly changed and we're closing out all the old issues with the old installer.  To try out our new installation experience using "magic", please see: https://docs.modular.com/mojo/manual/get-started.
