### ISSUE TITLE
[Feature Request] Add `size` param to FileHandle.read function

### ISSUE THREAD

**Issue by tairov** [modularml/mojo#1135]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Add `size: Int64` param to `FileHandle.read` https://docs.modular.com/mojo/stdlib/builtin/file.html#read

### What is your motivation for this change?

Python `file.read` function supports 1 parameter to set size of bytes to be read from the file opened https://www.tutorialspoint.com/python/file_read.htm

Need parity feature to be implemented in native Mojo `FileHandle.read` function. 
When implementing Mojo solution that reads file it's much safer read files by chunks, rather than loading full file content to end-up with OOM, that could crush the whole system ( see issue & comment from users: https://github.com/tairov/llama2.mojo/issues/51#issuecomment-1770568334 )

I guess `size` param for `read` function & `getsize` functions must be introduced in a single release, just because it's quite tricky to load file by chunks if we don't know what is it's size.

See another feature request : https://github.com/modularml/mojo/issues/1130

**Comment by JoeLoser** [comment]
Thanks for the request! `read()` supports specifying the `size` for number of bytes to read (defaults to EOF).  See https://github.com/modularml/mojo/blob/80f077403c9c55c7f96ad0ed9b4f3470f638c8f8/stdlib/src/builtin/file.mojo#L136 and friends.  This was probably introduced a few releases ago and just catching up some old issues here.
