### ISSUE TITLE
[BUG]: redefinition of symbol named '$< ... >'

### ISSUE THREAD

**Issue by StijnWoestenborghs** [modularml/mojo#1140]
### Bug description

A compiler error that took me a while to figure out how to work around it. 

Error:
```
./dainemo/utils/activations.mojo:0:0: error: redefinition of symbol named '$activations'
./dainemo/utils/activations.mojo:0:0: note: see current operation: 
"lit.file_module"() ({
^bb0:
}) {sym_name = "$activations"} : () -> ()
./dainemo/nn/activations.mojo:0:0: note: see existing symbol definition here
mojo: error: failed to parse the provided Mojo
```

### Steps to reproduce

Caused by empty files in a mojo module 
```
mymodule/
    __init__.mojo
    activations.mojo --> empty file
main.mojo
```
Import module in main.

Even if you delete the activations.mojo file now the compiler gets stuck in the same error. So you have to first clear the compiler cache:
delete `~/.modular/.mojo_cache`

### System information

```shell
Ubuntu 22.04
mojo 0.4.0 (9e33b013)
modular 0.2.1 (5144fffe)
```

**Comment by ematejska** [comment]
Seems like the error could be a bit better.

**Comment by StijnWoestenborghs** [comment]
@ematejska It looks indeed that the error message is incomplete. That here should be something more after 
`./dainemo/nn/activations.mojo:0:0: note: see existing symbol definition here`. But that actually is where the error message stopped.

**Comment by Mogball** [comment]
Closing in favour of https://github.com/modularml/mojo/issues/1248
