### ISSUE TITLE
Following error popped up when working through Modules & Packages examples from documentation

### ISSUE THREAD

**Issue by entropich3atdeath** [modularml/mojo#1148]
![Screenshot 2023-10-23 231330](https://github.com/modularml/mojo/assets/143988590/7de186f7-eabf-4186-94d1-e62fd81e5825)
![Screenshot 2023-10-23 231903](https://github.com/modularml/mojo/assets/143988590/2d95fd13-e4ba-4415-ad3c-0f3609c61cdd)

Hi, I was working through the Modules and Packages examples on this page - https://docs.modular.com/mojo/manual/get-started/packages.html . When I followed the instructions to create a package, I got the above error in the code. I copy pasted the code from the examples, so do not expect any problems there. I am also attaching a screenshot of how I setup the files (following instructions in the webpage).

Help pls!! Thanks.

**Comment by Ivo-Balbaert** [comment]
Hi, probably the same bug as I encountered when trying this example. Already made an issue here: 
[BUG]: Error when trying out the Docs code for Mojo packages #1011

**Comment by ematejska** [comment]
Marked as a dup of https://github.com/modularml/mojo/issues/1011.  If it still reproduces, please let us know.
