### ISSUE TITLE
[BUG] `print` on a floating point value is not printing enough digits

### ISSUE THREAD

**Issue by laviavigdor** [modularml/mojo#115]
## Request

Support printing of more then 6 significant digits for floating point numbers

### Motivation

Currently basic floating point operations cannot be verified to be correct, such as calculating significant digits in PI.
See example:
```
let pi = 3.1415916535897743
print(pi) # 3.141592
let x = (pi - 3.141591)*1e6
print(x) # 0.653590
```

### Description and Requirements

The print function should either print all significant digits for a floating point number, or allow custom choosing of how many are displayed.

**Comment by ksandvik** [comment]
It should be on parity with python 3. With Python 3.11.3:

pi = 3.1415916535897743
print(pi)

3.1415916535897743

**Comment by Nithin1728** [comment]
Hello, can I work on this?
