### ISSUE TITLE
[BUG]: type ascription causes compilation failure

### ISSUE THREAD

**Issue by dchenbecker** [modularml/mojo#1150]
### Bug description

There seems to be n issue with the interaction between type checking and fn/def compatibility. It's unclear from the documentation whether this is invalid code that does not have a proper error message or if there's a bug in the compilation. If I have two functions and I call them with the same `let` variable, I get a compilation failure if the first is a `def`. The following minimal examples fail:

```
def main():
    let z: Int8 = 24
    test(z)
    superfabulous(z)

def test(foo: Int8):
    print(foo)

def superfabulous(z: Int8):
    print(z)
```

```
def main():
    let z: Int8 = 24
    test(z)
    superfabulous(z)

def test(foo: Int8):
    print(foo)

fn superfabulous(z: Int8):
    print(z)
```

They fail with the error:

```
❯ mojo type_bug.mojo
/ssdhome/software/projects/mojo-playground/type_bug.mojo:4:18: error: use of uninitialized value 'z'
    superfabulous(z)
                 ^
/ssdhome/software/projects/mojo-playground/type_bug.mojo:2:5: note: 'z' declared here
    let z: Int8 = 24
    ^
mojo: error: failed to run the pass manager
```

However, if I change the first function to an `fn`, then both of these compile and run properly:

```
def main():
    let z: Int8 = 24
    test(z)
    superfabulous(z)

fn test(foo: Int8):
    print(foo)

def superfabulous(z: Int8):
    print(z)
```

```
def main():
    let z: Int8 = 24
    test(z)
    superfabulous(z)

fn test(foo: Int8):
    print(foo)

fn superfabulous(z: Int8):
    print(z)
```

Also, if I remove the type ascription from the first def, then these compile and run properly:

```
def main():
    let z: Int8 = 24
    test(z)
    superfabulous(z)

def test(foo):
    print(foo)

def superfabulous(z: Int8):
    print(z)
```

```
def main():
    let z: Int8 = 24
    test(z)
    superfabulous(z)

def test(foo):
    print(foo)

fn superfabulous(z: Int8):
    print(z)
```

### Steps to reproduce

Please see the bug description for minimal example code to reproduce the issue

### System information

```shell
- What OS did you do install Mojo on ?
  Ubuntu 22.04.3 LTS

- Provide version information for Mojo by pasting the output of `mojo -v`
  mojo 0.4.0 (9e33b013)

- Provide Modular CLI version by pasting the output of `modular -v`
  modular 0.2.1 (5144fffe)
```

**Comment by Mogball** [comment]
@stumpOS another lifetimes issue for you to look at when you have time

**Comment by lattner** [comment]
I fixed this a week or two ago

**Comment by dchenbecker** [comment]
If you mark as closed, would it be possible to reference the PR that fixes/closes this one?

**Comment by lattner** [comment]
This issue was internally reported as https://github.com/modularml/modular/issues/25419 which has the same issue, the problem was that uninit checker pass treated consume (e.g. when passing to an owned argument, which is default for defs)
of a trivial regpassable type as ending the lifetime of the value.  This shouldn't happen because there is no copy ctor to invoke, so the values are always treated as live after they are initialized

**Comment by lattner** [comment]
PR https://github.com/modularml/modular/pull/25564

**Comment by dchenbecker** [comment]
Thank you!
