### ISSUE TITLE
[Feature Request] Allow mutable `self` argument when overloading operators using dunder methods

### ISSUE THREAD

**Issue by lflash** [modularml/mojo#1152]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Right now mojo can't parse a mutable `self` argument when overloading operators like `__add__` or `__div__`.

This means that you can't make changes to struct values, or call member functions from within these dunder methods like you can in other methods.

```
struct val:
    var data: Float64

    fn __init__(inout self, data: Float64):
        self.data = data
    
    fn _op(inout self, otherVal: val):
        pass #do some operation here

    # this function won't parse
    fn __add__ (inout self, otherVal: val) -> val:
        self._op(otherVal)
        return val(self.data + otherVal.data)
    
    # this function works
    fn add (inout self, otherVal: val) -> val:
        self._op(otherVal)
        return val(self.data + otherValue.data)
```

### What is your motivation for this change?

Python classes can call other methods/change variables from within all dunder methods.

It's inconsistent with how other struct methods are implemented.

I'd love to make the above struct perform automatic differentiation, but right now you can't keep track of operations performed on a class from within overloaded operations.

Plus, more extensibility is always good!

### Any other details?

The `self` method can't be `owned` inside an operator dunder method either. That's inconsistent with how other struct methods are implemented too

**Comment by lattner** [comment]
Hrm, fair point.  This is an arbitrary limitation that we are imposing.  I'll bring it up for discussion thx!

**Comment by lattner** [comment]
Fixed, this will ship in a future update, thanks for raising this!
