### ISSUE TITLE
[BUG]: Missing module causes parser crash in LSP

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1153]
### Bug description

Parser crashes reported in LSP if the module in `import` is not found.

### Steps to reproduce

The following code causes the parser to crash:

```mojo
from a.b.c import d
```

While Mojo produces the correct diagnostics: `unable to locate module 'a'` if it's only nested 2 levels deep:

```mojo
from a.b import c
```

### System information

```shell
- OS: Docker on macOS Intel
- mojo -v: mojo 0.4.0 (9e33b013)
- modular -v: modular 0.2.1 (5144fffe)
```

**Comment by ematejska** [comment]
I'm unable to reproduce this (get an appropriate error in both cases.). Can you attach the full output of the running the compiler on the first case which doesn't produce the error?  Here is what i see:

```
bla2.mojo:1:6: error: unable to locate module 'a'
from a.b.c import d
     ^
mojo: error: failed to parse the provided Mojo
```

**Comment by Mogball** [comment]
This is not reproducible outside of the LSP server. cc @River707

**Comment by River707** [comment]
Thanks for the ping, will take a look.

**Comment by River707** [comment]
Should be fixed in the next release!
