### ISSUE TITLE
[Modular CLI]: Unsupported Windows Platform

### ISSUE THREAD

**Issue by structure-charger** [modularml/mojo#1155]
### Issue description

OS: windows 10
env: msys2
container daemon: podman
some shell error during install modular from official website while install mojo with Dockerfile.

Docker build with podman during execute below commands
RUN curl https://get.modular.com | MODULAR_AUTH=$AUTH_KEY sh - 
it will report error : " sh: 80: [[: not found" after execute " apt install modular (and Dependencies)"   and then cause modular auth failed before  "modular install mojo"

change command to official install format as below will take a work around from " sh: 80: [[: not found"  and complete the mojo install  while " sh: 80: [[: not found"  exists.

RUN curl https://get.modular.com | sh -  && modular auth $AUTH_KEY \
    && modular install mojo

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.
git clone https://github.com/modularml/mojo.git
cd mojo/examples/docker
 bash build-image.sh --use-podman --auth-key mut_***********

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`  modular (0.2.1) (from apt install message) 
- What OS did you install modular CLI on ?  msys2 env on windows 10
```

**Comment by structure-charger** [comment]
if  change Dockerfile is confirmed . I will launch a PR.

**Comment by structure-charger** [comment]
May be some error during web site server  serve shells to windows OS , shell from linux server may changed to dos format after download shell to windows file system. package modular to scoop && msys2 pacman package or winget etc. may  solve the problem.

**Comment by zbowling** [comment]
It looks your MSYS shell doesn't understand modern bash script args but regardless, Modular doesn't support MSYS2 containers on windows since the binaries are not compiled for windows currently. It does work with WSL2 with Ubuntu or Debian images. Instructions can be found on docs.modular.com
