### ISSUE TITLE
[BUG]: The language server doesn't warn about bad return type

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1159]
### Bug description

Consider the following code:
```mojo
fn f() -> Int:
  <body>
```

Mojo language server doesn't produce a type error when body doesn't contain a return. There are cases where this (no error) makes sense, like when <body> contains only `pass` or `...`. However, for the majority of cases, this clearly won't type check. And as the compiler does produce an error, I think it's the LSP that is at fault here.

### Steps to reproduce

```mojo
fn f() -> Int:
  let a = 1
```

### System information

```shell
- OS: Docker on macOS Intel
- mojo -v: mojo 0.4.0 (9e33b013)
- modular -v: modular 0.2.1 (5144fffe)
```

**Comment by River707** [comment]
This should be fixed in the next release!
