### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by CrypticRevenger** [modularml/mojo#1163]
### What can we do better?

Table of Contents: Create a table of contents at the beginning of the README to help users quickly navigate to the sections they're interested in.
More About the Playground: Provide a brief overview of what users can do in the Mojo Playground. Mention if there are any limitations, offer some tips, or include a link to a more detailed guide.

**Comment by CrypticRevenger** [comment]
@modularbot please review the PR #1164.

**Comment by scottamain** [comment]
The Mojo repo is very limited at this point, so I don't think it needs a table of contents yet. The best place to learn more about Mojo is in the Mojo Manual: https://docs.modular.com/mojo/manual/
