### ISSUE TITLE
[BUG]: warning: unreachable code after return statement with context manager

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [modularml/mojo#1166]
### Bug description

When using a context manager to read a file and return a string, I am greeted with this warning which is quite surprising since in python, the `__exit__` of the context manager is called before returning.

### Steps to reproduce

Here is a minimal repro (who doesn't like those?):

```python
# trying_stuff.mojo

from pathlib import Path


fn read_text(self: StringLiteral) raises -> String:
    with open(self, "r") as f:
        return f.read()


def main():
    print(read_text("./trying_stuff.mojo")[:20])
```

```bash
$ mojo trying_stuff.mojo
/projects/open_source/mojo-stdlib-extensions/trying_stuff.mojo:7:5: warning: unreachable code after return statement
    with open(self, "r") as f:
    ^
# trying_stuff.mojo
```

### System information

```shell
- What OS did you do install Mojo on ?
ubuntu 22.04 in docker container in wsl
⚡  /projects/open_source/mojo-stdlib-extensions   master  modular -v
modular 0.2.1 (5144fffe)
 ⚡  /projects/open_source/mojo-stdlib-extensions   master  mojo -v
mojo 0.4.0 (9e33b013)
```

**Comment by Vijay-948** [comment]
can you assign me?

**Comment by lattner** [comment]
Nice, thank you for filing this.  In addition to the warning, this bug could cause the with statement to fail to extend 'f' for the full duration of the body.  Not a problem in this case, but could affect others.  Fixed in next release.

**Comment by gabrieldemarmiesse** [comment]
Thanks to the modular team :)
