### ISSUE TITLE
[Modular CLI]:  Building wheel for pyzmq (PEP 517) ... error

### ISSUE THREAD

**Issue by JoeFirmament** [modularml/mojo#1167]
### Issue description
Building wheel for pyzmq (PEP 517) ... error
The following error occurs during installation.

### Steps to reproduce

- Include relevant code snippet that did not work as expected.

>   Building wheel for pyzmq (PEP 517) ... error
>   ERROR: Command errored out with exit status 1:
>    command: /Users/bquill/.modular/pkg/packages.modular.com_mojo/venv/bin/python /Users/bquill/.modular/pkg/packages.modular.com_mojo/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmprbf8iee_
>        cwd: /private/tmp/pip-install-5642hkh4/pyzmq
>   Complete output (252 lines):
>   /private/tmp/pip-build-env-f8rjs3io/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'cffi_modules'

- Sreenshots to help explain the problem.
<img width="819" alt="Screenshot 2023-10-27 at 11 13 15" src="https://github.com/modularml/mojo/assets/9443895/48823e84-55b5-4480-bb56-77acbe4019ae">
<img width="818" alt="Screenshot 2023-10-27 at 11 14 32" src="https://github.com/modularml/mojo/assets/9443895/a16938b6-8d3a-4f46-a786-907c735d3624">

- Include anything else that might help us debug the issue.
[Terminal Saved Output.txt](https://github.com/modularml/mojo/files/13184618/Terminal.Saved.Output.txt)

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.2.1 (5144fffe)
- What OS did you install modular CLI on ?
Mac OS Sonama14
```

**Comment by smuniraj2018** [comment]
Please check xcode cmd line developer tools installation and retry.

**Comment by ematejska** [comment]
@River707 The dependencies being pulled in are surprising.  Could you take a look if that's what is expected?

**Comment by ihnorton** [comment]
FWIW, pyzmq has arm64 wheels available for python 3.8, so building from source should not be necessary. This looks like it might just be a pip version issue in the host environment - try `pip install --upgrade pip`.

**Comment by gia-guar** [comment]
I am having the same problem. If you upgrade, modular will ask to clean `modular: error: failure detected - please run `modular clean` and try again` which will reset the upgrade and make the original error apear again

**Comment by ematejska** [comment]
Closing out this old issue since so much has changed, please open if this still occurs.
