### ISSUE TITLE
[Docs] when using python,An error occurred assigning a value to the dictionary

### ISSUE THREAD

**Issue by tomfred23** [modularml/mojo#1168]
### Where is the problem?

no

### What can we do better?

from python.python import Python
from python.object import PythonObject

fn main():
    var dictionary = Python.dict()
    dictionary['fruit'] = "apple"
    dictionary['starch'] = "potato"
error: cannot call function that may raise in a context that cannot raise
    dictionary['fruit'] = "apple"

### Anything else?

no

**Comment by scottamain** [comment]
Hi @tomfred23, without a link to the document where you found the problem, we cannot fix this. Please reopen and share a link to the page where you see the problem.
