### ISSUE TITLE
[BUG]: A crash happened in the mojo parser

### ISSUE THREAD

**Issue by NobinKhan** [modularml/mojo#1181]
### Bug description

I got the message from mojo vs-code extension that with current content parser crashed. below is my content.

```
from python import python
import mojo.net.http as http
import mojo.net.tcp as tcp


fn main():
    print("hello world")
    try:
        let datetime = python.Python.import_module("datetime")
        print(datetime.datetime.now())
    except:
        print("error")
```

### Steps to reproduce

* Include relevant code snippet or link to code that did not work as expected.
* If applicable, add screenshots to help explain the problem.
* If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
* Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Ubuntu 23.10 (python 3.11.6)
- Provide version information for Mojo by pasting the output of `mojo -v`
- mojo 0.4.0 (9e33b013)
- Provide Modular CLI version by pasting the output of `modular -v`
- modular 0.2.1 (5144fffe)
```

**Comment by ksandvik** [comment]
What's 
import mojo.net.http as http
import mojo.net.tcp as tcp

? 

Removing those, then it compiled and run:
$ mojo testdate.mojo
hello world
2023-10-28 12:09:29.604958

$  mojo --version
mojo 0.4.0-beta (82bba63c)

**Comment by ksandvik** [comment]
Also add raises after the main call:

`fn main() raises:`

**Comment by ematejska** [comment]
When I try compiling at the commandline I see the error:
error: unable to locate module 'mojo'
import mojo.net.http as http
       ^

Do you get that error anywhere in the VSCode environment that's visible to you?

**Comment by River707** [comment]
Without the `mojo` package imports, this appears to work fine. If you encounter this again, please reopen the issue. If it still happens with your `mojo` package imports, could you include some of the context of those packages for reproduction?
