### ISSUE TITLE
[BUG]:typo error-"Remove Double Quotes for 'Chief Creative Officer' in 'recruitments' Section" 

### ISSUE THREAD

**Issue by chinmay7016** [modularml/mojo#1183]
### Bug description

In the "recruitments" section of the provided JSON configuration, the value for "Chief Creative Officer" is enclosed in double quotes when it should not be. The correct format should be without double quotes
readme file

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.
in readme file typo error

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by ematejska** [comment]
I'm not sure what this bug is referring to.  If you have more details, please re-open and provide to a path of the file with the typo.
