### ISSUE TITLE
[Docs]:

### ISSUE THREAD

**Issue by Kalyanimhala** [modularml/mojo#1184]
### Where is the problem?

No contributors section to the README.md file.

### What can we do better?

There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/modularml/mojo/assets/147402107/e948d846-d8e6-431a-8dcc-c837b48d1034)

**Comment by Kalyanimhala** [comment]
@lattner Kindly assign me this issue, I want to work on it. Thank You!!

**Comment by lattner** [comment]
cool!

**Comment by Kalyanimhala** [comment]
@lattner  if You don't mind can I upgrade the project by adding CONTRIBUTING.md file

-Importance of CONTRIBUTING.md:-
 A "Contributing.md" file is added to a repository to provide guidelines and 
instructions for potential contributors on how to collaborate effectively with the project. 
It typically includes information on coding standards, how to submit changes, reporting issues,
 and other important details to streamline the contribution process and maintain a healthy 
open-source community.
