### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by dalvishruti14** [modularml/mojo#1185]
### Where is the problem?

The problem is that the repository currently does not have a license file.

### What can we do better?

I intend to add an MIT License to the repository to specify the terms under which the code can be used, modified, and distributed by others.

### Anything else?

Can I work on this issue?

**Comment by dalvishruti14** [comment]
Add the LICENSE section in your README to make it more informative, user-friendly, and visually appealing. This helps clarify the licensing terms and intentions of your project for potential users and contributors.

**Comment by iamtimdavis** [comment]
Thanks for the question - the Mojo SDK license is available here - https://www.modular.com/legal/mojo. As @soraros correctly highlights, we are working towards open-sourcing parts of Mojo and will share some exciting updates on this front soon, and licensing as well.
