### ISSUE TITLE
[Request] Implement `__iter__` for `DynamicVector` to allow for use in range-for loops

### ISSUE THREAD

**Issue by bserletfun** [modularml/mojo#1189]
### Bug description

Maybe it's just a newbie issue, but I can't get for to work with dynamic vectors.  I would expect the following code to work:
```
let xx = DynamicVector[Int]()
xx.push_back(1)
xx.push_back(2)
print("xx=", xx[0], xx[1])
for x in xx:
    print("x=", x)

```

### Steps to reproduce

Reproducible.
A workaround is to use an integer index of course.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
Latest mojo on Mac.
```

**Comment by lattner** [comment]
Thanks for filing this Bertrand, this isn't a newbie issue.  The key thing here is that Mojo doesn't have traits/protocols yet (this is actively under implementation though) so every collection needs to manually implement the informal protocol that for loops depend on, and when they don't bad things happen.  In the interim, we can just manually implement these to make sure basic stuff like this works

@JoeLoser fyi

**Comment by gryznar** [comment]
Task was closed, because this was introduced to Mojo and will be available for future release?

**Comment by JoeLoser** [comment]
> Task was closed, because this was introduced to Mojo and will be available for future release?

Yep, functionality has been added and will be available in the Feb release.
