### ISSUE TITLE
[BUG] Cannot redefine in python cell

### ISSUE THREAD

**Issue by ianxek** [modularml/mojo#119]
## Bug Description

Can't reassign in a python cell.

### Steps to Reproduce

%%python

s = 13
s = s/5

error: Expression [12]:27:5: invalid redefinition of 's'
    let s = __lldb_python_module_12.s
    ^

Expression [12]:26:5: previous definition here
    let s = __lldb_python_module_12.s
    ^

**Comment by Mogball** [comment]
Fyi @walter-erquinigo @River707
