### ISSUE TITLE
[Docs] Code doesn't match comment in Mandelbrot.ipynb

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1192]
### Where is the problem?

https://github.com/modularml/mojo/blob/main/examples/notebooks/Mandelbrot.ipynb

### What can we do better?

In the *Benchmarking* section, it's mentioned that size has been increased to 4096 and `MAX_ITERS` 1000, yet it's not done in the code.

**Comment by scottamain** [comment]
@jackos Are you familiar with the changes here?

**Comment by jackos** [comment]
Hi thanks @soraros this will be updated in the next release
