### ISSUE TITLE
[BUG]: String creation from a Pointer or DTypePointer working differently in 0.5.0

### ISSUE THREAD

**Issue by andresnowak** [modularml/mojo#1219]
### Bug description

If you try to create a String from a Pointer or DTypePointer it will not using the complete value for the len, instead it will use len - 1. So let's say if i have a Pointer with a len of 5 values, when we create the string from this pointer passing as len the value 5, it will instead create a String with a size of 4.

### Steps to reproduce

```py
fn main():
    let temp_pointer = Pointer[Int8].alloc(5)
 
    for i in range(5):
        temp_pointer.store(i, ord("a"))
 
    let temp_string = String(temp_pointer, 5)
 
    print(len(temp_string))
    print(temp_string)
```

### System information

```shell
- What OS did you do install Mojo on ? Pop Os
- Provide version information for Mojo by pasting the output of `mojo -v`: mojo 0.5.0 (6e50a738)
- Provide Modular CLI version by pasting the output of `modular -v`: modular 0.2.2 (95d42445)
```

**Comment by mzaks** [comment]
After some playing around I come to a conclusion that this is not a bug, it is a breaking change. Before 0.5.0 the initialiser worked with pointers to non `0` terminated strings, now it works only with pointers to `0` terminated string and the len argument needs to include the `0` byte. Also before the `_buffer` from `String` was also not `0` terminated. The main difference is:
```
let s: String = "Maxim"
print(len(s)) # prints 5
print(len(s._buffer)) # prints 6
```

**Comment by andresnowak** [comment]
Thank you for clarifying this. For now i will leave this open so if other people run into the same problem can find this, because for now at least i didn't find this change written in the changelog

**Comment by scottamain** [comment]
@arthurevans maybe we should retroactively add this to the 0.5 changelog. WDYT?
