### ISSUE TITLE
[object] Fully dynamic features (like `__add__`) are not wired up yet

### ISSUE THREAD

**Issue by ianxek** [modularml/mojo#122]
To understand type inference in Mojo

## Bug Description

In a regular Mojo cell, that works

```
def foo(L, D):
    s = D[0]
    for i in range(1,L):
        s += D[i]
    return s
```

but that fails, why?

```
def bar(L, D):
    s = 0
    for i in range(L):
        s += D[i]
    return s
```

**Comment by nevdelap** [comment]
You should include the failure.

**Comment by ianxek** [comment]
> You should include the failure.

Yes, right:

```
error: Expression [24]:13:11: invalid call to '__iadd__': right side cannot be converted from 'object' to 'Int'
        s += D[i]
        ~~^~~~~~~

/.modular/Kernels/mojo/Builtin/Int.mojo:410:5: function declared here
    fn __iadd__(inout self, rhs: Int):
    ^
```

**Comment by lattner** [comment]
We're currently missing core features (like traits+classes) that are need to make this work really well.  I'd recommend sticking with the static parts of Mojo in the immediate future, this will improve in the next 3-6 months.  Thanks!

**Comment by Mogball** [comment]
Closing in favour of roadmap
