### ISSUE TITLE
[Docs] Pseudo code incomplete

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1221]
### Where is the problem?

https://docs.modular.com/mojo/stdlib/builtin/simd.html#select

### What can we do better?

The list comprehension is incomplete in the `Returns:` section:
```mojo
[true_case[i] if elem else false_case[i] in enumerate(self)]
```
should have been
```
[true_case[i] if elem else false_case[I] for i, elem in enumerate(self)]
```

**Comment by scottamain** [comment]
Thank you! This will be fixed in the next update.
