### ISSUE TITLE
[SYNTAX]: Compile-time keyword parameters intersecting with new type syntax in python 3.12?

### ISSUE THREAD

**Issue by shroominic** [modularml/mojo#1222]
### Bug description

Since Mojo is trying to be a superset of python I think the new python version could crash into the new mojo features.

### Python utilizing brackets for new type syntax:
![Screenshot 2023-11-03 at 12 19 32](https://github.com/modularml/mojo/assets/34897716/ada340ae-b0de-4ec7-bb98-b3f0c0184408)

### Mojo utilizing brackets for new compile-time keyword syntax:
![Screenshot 2023-11-03 at 12 18 51](https://github.com/modularml/mojo/assets/34897716/bc751a7a-e4c8-47ca-88e8-5e72a9dff36b)

I know that mojo is doing it in their own new defined mojo fn and mojo structs but I think this could make the language a bit weird to have 2 different cases with also mojo functions needing a different solution for generics.

### Steps to reproduce

Reading the docs:
- python 3.12: https://docs.python.org/3.12/whatsnew/3.12.html#pep-695-type-parameter-syntax
- mojo 0.5.0: https://docs.modular.com/mojo/changelog.html

### System information

```shell
All
```

**Comment by jackos** [comment]
Hi @shroominic this is the same syntax as Mojo, can you provide any specific examples of where it differs that you're concerned about?

**Comment by shroominic** [comment]
Thanks for the info! I think this is right I was just confused
