### ISSUE TITLE
Encountering problem with the modular install mojo command on windows 10 through ubuntu as shell[Modular CLI]: 

### ISSUE THREAD

**Issue by mohan-676** [modularml/mojo#1226]
### Issue description

As I was setting up mojo on my windows 10 I enounterd problem while runnng the **"modular install mojo"** command in the shell. I've mentioned the error message below 

Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: crashpad failed to start handler

After this I also tried **"modular clean"** command but seems like that also doesn't work out. If someone has an idea about it please let me know !!

### Steps to reproduce

**1st command: modular install mojo
2nd command: modular clean** 

error : [2361:2361:20231104,154155.466475:ERROR exception_handler_server.cc:361] getsockopt: Invalid argument (22)
[2359:2359:20231104,154155.518807:ERROR socket.cc:153] unhandled cmsg 0, 0
Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: crashpad failed to start handler

### Version Info

```shell
modular cli version : modular 0.2.2 (95d42445)
Windows 10
```

**Comment by Sharktheone** [comment]
What WSL version are you using? Only WSL2 is officially supported.

**Comment by Ivo-Balbaert** [comment]
Update to WSL2. That should hopefully resolve the issue: wsl --update or sudo apt install wsl

**Comment by sahill3** [comment]
wsl --set-version Ubuntu-20.04 2
Run this command in your Windows Powershell and you are good to go. Replace the Ubuntu version with the one you have.

**Comment by ematejska** [comment]
Thank you for trying out Mojo.  The installation experience has significantly changed and we're closing out all the old issues with the old installer.  To try out our new installation experience using "magic", please see: https://docs.modular.com/mojo/manual/get-started.
