### ISSUE TITLE
[BUG]: Error when Using `simdwidthof` to Default a Keyword Parameter

### ISSUE THREAD

**Issue by leandrolcampos** [modularml/mojo#1227]
### Bug description

When I have a struct parameterized with `dtype: DType = DType.float32, simd_width: Int = simdwidthof[dtype]()` and I attempt to initialize an instance of it using the default parameter values, I encounter the following error:

> error: Expression [67]:1:1: 'lit.alias.decl' op invalid use of parameter with no declaration "_7x19_dtype"

### Steps to reproduce

Consider the following struct:

```
@value
@register_passable("trivial")
struct Polynomial[dtype: DType = DType.float32, simd_width: Int = simdwidthof[dtype]()]:
    var coefficients: VariadicList[SIMD[dtype, simd_width]]

    @always_inline("nodebug")
    fn __init__(*coefficients: SIMD[dtype, simd_width]) -> Self:
        return Self {coefficients: coefficients}

    @always_inline("nodebug")
    fn __getitem__(self: Self, index: Int) -> SIMD[dtype, simd_width]:
        return self.coefficients[index]

    @always_inline("nodebug")
    fn __len__(self: Self) -> Int:
        return len(self.coefficients)
```

When I try to initialize a polynomial using the default parameter values (e.g., `alias p = Polynomial(1.0, 2.0)`), I receive the following error:
> error: Expression [67]:1:1: 'lit.alias.decl' op invalid use of parameter with no declaration "_7x19_dtype"
alias p = Polynomial(1.0, 2.0)
^
>
> expression failed to parse (no further compiler diagnostics)

**It's worth noting that specifying the data type explicitly, as in `alias p = Polynomial[DType.float32](1.0, 2.0)`, works as expected.**

### System information

```shell
- What OS did you do install Mojo on ? `Ubuntu 22.04.2 LTS (WSL2)`
- Provide version information for Mojo by pasting the output of `mojo -v`: `0.5.0 (6e50a738)`
- Provide Modular CLI version by pasting the output of `modular -v``: `0.2.0 (355ea9c0)`
```

**Comment by lattner** [comment]
@Mogball and @laszlokindrat fyi

**Comment by Mogball** [comment]
I believe this got fixed already. @laszlokindrat do you remember?

**Comment by Mogball** [comment]
I get a different error, but it seems the root issue has not been fixed. Thanks for the report!
