### ISSUE TITLE
[Request][mojo-stdlib]: Inconsistent function naming in `tensor`

### ISSUE THREAD

**Issue by sa-** [modularml/mojo#1229]
### Bug description

The following functions have missing underscores

- `bytecount`
- `fromfile`
- `tofile`

If they have an underscore it would be consistent with snake case naming like so:

- `byte_count`
- `from_file`
- `to_file`

### Steps to reproduce

n/a

### System information

```shell
n/a
```

**Comment by gryznar** [comment]
+1 Keeping names consistent with Python does not mean to have theme the same.  Mojo will do better job with having inner consistency than have some names separated via "_" and some not.

Python: tofile()
Mojo as Python++: to_file()

**Comment by willghatch** [comment]
We are currently working on fleshing out a style guide which we will apply throughout the standard library.  Thanks for raising this.

**Comment by gryznar** [comment]
Please keep in mind, that names separated via "_" are much more readable :)

**Comment by gryznar** [comment]
@willghatch is this fleshing out namings still actual? :)

**Comment by JoeLoser** [comment]
> @willghatch is this fleshing out namings still actual? :)

This hasn't been done yet, but we'll work on a style guide for when we open source the stdlib.  Also, see my comment at https://github.com/modularml/mojo/issues/1528#issuecomment-1957652882.  FYI @rparolin @ConnorGray

**Comment by sa-** [comment]
Tensor will be deprecated
