### ISSUE TITLE
[BUG]: DCE too eager?

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1231]
### Bug description

I would expect the code in repro to NOT pass type checking.

### Steps to reproduce

The following code compiles just fine, even with `@always_inline`:

```mojo
fn main():
    let l = [0, 1.1]
    get(l)

@always_inline
fn get(l: ListLiteral):
    let a = l.get[1, Int]()
```

And if one changes the `l.get` to `rebind`, it's even weirder, where a `value unused` warning is generated, and the code still runs.

```mojo
fn main():
    let l = [0, 1.1]
    get(l)

@always_inline
fn get(l: ListLiteral):
    rebind[Float32](l)
```

While the following does error our:

```mojo
fn main():
    let l = [0, 1.1]
    l.get[1, Int]()
```

### System information

```shell
mojo 0.5.0 on docker, macOS Intel
```

**Comment by Mogball** [comment]
Thanks for the issue! This is something that is known. `rebind` is not really meant to be used widely, and hopefully soon we can get rid of it entirely. Closing this as "will not fix"/"intentional".

**Comment by Mogball** [comment]
`l.get[1, Int]()` actually just calls `rebind`.... lol

But yeah I think your point here is valid. The API is poor. I'll re-open the issue and focus more on the `get` API, since `rebind` is an implementation detail
