### ISSUE TITLE
[BUG]: Doesn't reject empty identifier name

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1232]
### Bug description

I'm not sure if it's a bug or an unintuitive corner case like Banach-Tarski.

### Steps to reproduce

Consider the following code:

```mojo
fn main():
    let `` = 1
    print(``)
```

### System information

```shell
mojo 0.5.0 on docker, macOS Intel
```

**Comment by Mogball** [comment]
I'm tempted to say this is working as intended. @lattner @laszlokindrat thoughts?

**Comment by Mogball** [comment]
We should probably reject this. While this is cool, empty identifiers (and symbol names) could cause all sorts of trouble.

**Comment by lattner** [comment]
Fixed in next release, you'll now get: `error: empty backtick identifier isn't allowed`.  Thanks for filing this!
