### ISSUE TITLE
[BUG]: VSCode doesn't show autocomplete in `if` statements

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1236]
### Bug description

As title.

### Steps to reproduce

VSCode doesn't show symbol completion in `if`/`while`/etc.
```mojo
fn main():
    let a: Float64 = 10
    if a.|
         ^ cursor here
```

### System information

```shell
mojo 0.5.0 on docker, macOS Intel
```

**Comment by River707** [comment]
Thanks for filing, we'll take a look!

**Comment by River707** [comment]
This should be fixed in the next release!
