### ISSUE TITLE
[BUG]: "Unable to locate module" if stem of filename in cwd matches module name

### ISSUE THREAD

**Issue by ihnorton** [modularml/mojo#1238]
### Bug description

I get a module import failure if the module name matches the stem of a filename present in the same directory, for some extensions. I originally noticed this with a `.h` file, and it appears to happen with `.foo`, `.cpp`, `.java`, `.ppc` (Oddly, it doesn't happen with `mymod.bar`)

### Steps to reproduce

Directory contents:
```
==> main.mojo <==
import mymod

def main():
    pass

==> mymod <==

==> mymod/__init__.mojo <==
from .mymod import *

==> mymod/mymod.mojo <==
struct Foo:
    pass
```

1. `mojo run main.mojo` works fine
2. run `touch mymod.foo`
3. then `mojo run main.mojo` gives:
```
/private/tmp/test/main.mojo:1:8: error: unable to locate module 'mymod'
import mymod
       ^
mojo: error: failed to parse the provided Mojo
```

### System information

```shell
- What OS did you do install Mojo on ?
macOS 13.5
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.5.0 (6e50a738)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.2.1 (5144fffe)
```

**Comment by Mogball** [comment]
Closing in favour of #1248

**Comment by Mogball** [comment]
This is actually a different issue. Reopening.
