### ISSUE TITLE
[Modular CLI]: Non supported CPU 

### ISSUE THREAD

**Issue by josexsquared** [modularml/mojo#1239]
### Issue description

modular: error: no packages found for the current target hardware - please run `modular host-info` and file a ticket at https://github.com/modularml/mojo with your hardware information

 Host Information
  ================

  Target Triple: aarch64-unknown-linux
  CPU: cortex-a76
  CPU Features: aes, crc, crypto, dotprod, fp-armv8, fullfp16, lse, neon, ras, rcpc, rdm, sha2, ssbs

### Steps to reproduce

modular install mojo

modular host-info

### Version Info

```shell
- modular 0.2.1 (5144fffe)
- WSL
```

**Comment by Sharktheone** [comment]
Currently arm only MacOS arm CPUs are supported. See #1093

**Comment by ematejska** [comment]
Thank you for trying out Mojo.  The installation experience has significantly changed and we're closing out all the old issues with the old installer.  To try out our new installation experience using "magic", please see: https://docs.modular.com/mojo/manual/get-started.
