### ISSUE TITLE
[Modular CLI]: newline missing on ubuntu 22.04 WSL

### ISSUE THREAD

**Issue by mvillmow-openxpu** [modularml/mojo#1243]
### Issue description

When I run the command:
" modular install mojo
Package https://packages.modular.com/mojo is already installed, did you mean `modular update https://packages.modular.com/mojo`?mvillmow@DESKTOP-RED5QRG:~/modular$
"

The output is missing a final newline, thus causing the bash command line to be appended.

### Steps to reproduce

![image](https://github.com/modularml/mojo/assets/146022025/d8c51194-1e56-40ad-9c1c-346d6438aa33)

### Version Info

```shell
modular -v
modular 0.2.2 (95d42445)

lsb_release  -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

This is on windows 11 WSL
```

**Comment by ematejska** [comment]
Thank you for trying out Mojo.  The installation experience has significantly changed and we're closing out all the old issues with the old installer.  To try out our new installation experience using "magic", please see: https://docs.modular.com/mojo/manual/get-started.
