### ISSUE TITLE
[BUG]: compiler warnings are too transient

### ISSUE THREAD

**Issue by guidorice** [modularml/mojo#1246]
### Bug description

Mojo compiler warnings occur on the first compile, and then disappear, presumably because of the build caching system which is happening behind the scenes. In a larger codebase, this will make warnings more difficult to  discover over time.

cc: to this issue https://github.com/guidorice/mojo-pytest/issues/2 because I think it would be great to surface warnings in a tool like mojo-pytest.

### Steps to reproduce

repro.mojo

```mojo
fn main():
    var x = 42
    print(x)
```

```
$ mojo run repro.mojo 
.../repro.mojo:2:5: warning: 'x' was declared as a 'var' but never mutated, consider switching to a 'let'
    var x = 42
    ^
42
$ mojo run repro.mojo 
42
$ mojo run repro.mojo 
42
```

### System information

```shell
mojo 0.5.0 (6e50a738)
modular 0.2.2 (95d42445)
Darwin macbookair.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:31 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8112 arm64
```

**Comment by lattner** [comment]
@River707 sounds like we're caching the IR but not the diagnostics?

**Comment by River707** [comment]
Yeah, I know where this is happening. We seem to not preserve diagnostics emitted during semantic lowering.

**Comment by gabrieldemarmiesse** [comment]
To detect those kind of compiler issues, would that make sense to create a `--no-cache` option in the mojo CLI? I also stumbled a few time on compiler issues (already filed) where the error was different if the cache was hot or cold.

**Comment by River707** [comment]
> To detect those kind of compiler issues, would that make sense to create a `--no-cache` option in the mojo CLI? I also stumbled a few time on compiler issues (already filed) where the error was different if the cache was hot or cold.

This is something we should consider (even for other reasons beyond diagnostics), but it's a little tricky as we have caching very pervasively used throughout the infra.

**Comment by River707** [comment]
This should be fixed in the next release!

**Comment by guidorice** [comment]
Thanks! I also added a mojo compiler warning capturing mode to mojo-pytest: https://github.com/guidorice/mojo-pytest/issues/2
