### ISSUE TITLE
[BUG][mojo] Issues when importing from a file with the same name as the current file

### ISSUE THREAD

**Issue by Mogball** [modularml/mojo#1248]
### Bug description

There are a variety of issues related to importing from a module with the same name as the current file. This confuses the parser in many different ways, causing various crashes and poor error messages. We should fix the import resolver to handle this properly.

- #1051
- #972 
- #1065 
- #1052 
- #1238

**Comment by ematejska** [comment]
Dup https://github.com/modularml/mojo/issues/1597.

**Comment by Mogball** [comment]
This should be fixed in the next release.
