### ISSUE TITLE
[BUG] Cannot store String in DynamicVector

### ISSUE THREAD

**Issue by czheo** [modularml/mojo#126]
## Bug Description

Storing `Int` works.
```py
var int_vec = DynamicVector[Int]()
int_vec.push_back(123)
print(int_vec[0]) # 123
```

Storing `String` doesn't work.
```py
var str_vec = DynamicVector[String]() # initialization works.
str_vec.push_back("xxx")
# throws error like below

"""
error: Expression [72]:20:22: invalid call to 'push_back': method argument #0 cannot bind generic !mlirtype to memory-only type 'String'
    str_vec.push_back("xxx")
    ~~~~~~~~~~~~~~~~~^~~~~~~

/.modular/Kernels/mojo/Stdlib/Vector.mojo:391:5: function declared here
    fn push_back(inout self, value: type):
    ^
                 ~^
"""
```

Storing `StringRef` works.

```py
var str_vec = DynamicVector[StringRef]()
str_vec.push_back("xxx")
print(str_vec[0]) # xxx
```

### Steps to Reproduce

![image](https://github.com/modularml/mojo/assets/1692400/589abc52-4602-4e57-89aa-6ec53eabafe0)

### Context

11:memory:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-poda6d59870_f09b_4c16_a0a7_5b412ecab651.slice/cri-containerd-527fda7d29c6c0d89606b873d8cd1139d51a6cb5d12a8cd55390ad38be080a61.scope
10:hugetlb:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-poda6d59870_f09b_4c16_a0a7_5b412ecab651.slice/cri-containerd-527fda7d29c6c0d89606b873d8cd1139d51a6cb5d12a8cd55390ad38be080a61.scope
9:perf_event:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-poda6d59870_f09b_4c16_a0a7_5b412ecab651.slice/cri-containerd-527fda7d29c6c0d89606b873d8cd1139d51a6cb5d12a8cd55390ad38be080a61.scope
8:devices:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-poda6d59870_f09b_4c16_a0a7_5b412ecab651.slice/cri-containerd-527fda7d29c6c0d89606b873d8cd1139d51a6cb5d12a8cd55390ad38be080a61.scope
7:freezer:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-poda6d59870_f09b_4c16_a0a7_5b412ecab651.slice/cri-containerd-527fda7d29c6c0d89606b873d8cd1139d51a6cb5d12a8cd55390ad38be080a61.scope
6:cpuset:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-poda6d59870_f09b_4c16_a0a7_5b412ecab651.slice/cri-containerd-527fda7d29c6c0d89606b873d8cd1139d51a6cb5d12a8cd55390ad38be080a61.scope
5:blkio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-poda6d59870_f09b_4c16_a0a7_5b412ecab651.slice/cri-containerd-527fda7d29c6c0d89606b873d8cd1139d51a6cb5d12a8cd55390ad38be080a61.scope
4:pids:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-poda6d59870_f09b_4c16_a0a7_5b412ecab651.slice/cri-containerd-527fda7d29c6c0d89606b873d8cd1139d51a6cb5d12a8cd55390ad38be080a61.scope
3:net_cls,net_prio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-poda6d59870_f09b_4c16_a0a7_5b412ecab651.slice/cri-containerd-527fda7d29c6c0d89606b873d8cd1139d51a6cb5d12a8cd55390ad38be080a61.scope
2:cpu,cpuacct:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-poda6d59870_f09b_4c16_a0a7_5b412ecab651.slice/cri-containerd-527fda7d29c6c0d89606b873d8cd1139d51a6cb5d12a8cd55390ad38be080a61.scope
1:name=systemd:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-poda6d59870_f09b_4c16_a0a7_5b412ecab651.slice/cri-containerd-527fda7d29c6c0d89606b873d8cd1139d51a6cb5d12a8cd55390ad38be080a61.scope
0::/

**Comment by lattner** [comment]
Right.  Until we have #113, we cannot reason about the ctors/dtors/copyctors etc of a type like String.  We're working on this, so please stay tuned.  Until then let's track as #113
