### ISSUE TITLE
[Feature Request] ARM suppor

### ISSUE THREAD

**Issue by jaroslawjanas** [modularml/mojo#1261]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Native ARM support for Linux and Windows

### What is your motivation for this change?

I see native Windows support but no mention of ARM.
I don't see any plans for ARM support on Linux.

### Any other details?

👎

**Comment by Sharktheone** [comment]
Duplicate of #1093
