### ISSUE TITLE
[Modular CLI]: failed to install Mojo with command `modular install mojo`

### ISSUE THREAD

**Issue by zikcheng** [modularml/mojo#1265]
### Issue description

$ modular install mojo
\# Found release for https://packages.modular.com/mojo @ 0.5.0
\# Installing to /Users/mac/.modular/pkg/packages.modular.com_mojo
\# Downloading artifacts. Please wait...
\# Downloads complete, setting configs...
\# Configs complete, running post-install hooks...
Collecting find_libpython==0.3.0
  Using cached find_libpython-0.3.0-py3-none-any.whl (8.5 kB)
Collecting papermill==2.4.0
  Using cached papermill-2.4.0-py3-none-any.whl (38 kB)
Collecting jupyter_client>=8.3.0
  Using cached jupyter_client-8.6.0-py3-none-any.whl (105 kB)
Collecting ipykernel>=6.25.0
  Using cached ipykernel-6.26.0-py3-none-any.whl (114 kB)
Collecting entrypoints
  Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
Collecting tenacity
  Using cached tenacity-8.2.3-py3-none-any.whl (24 kB)
Collecting requests
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting nbformat>=5.1.2
  Using cached nbformat-5.9.2-py3-none-any.whl (77 kB)
Collecting click
  Using cached click-8.1.7-py3-none-any.whl (97 kB)
Collecting tqdm>=4.32.2
  Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)
Collecting nbclient>=0.2.0
  Using cached nbclient-0.9.0-py3-none-any.whl (24 kB)
Collecting ansiwrap
  Using cached ansiwrap-0.8.4-py2.py3-none-any.whl (8.5 kB)
Collecting pyyaml
  Using cached PyYAML-6.0.1-cp39-cp39-macosx_10_9_x86_64.whl (197 kB)
Collecting python-dateutil>=2.8.2
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting jupyter-core!=5.0.*,>=4.12
  Using cached jupyter_core-5.5.0-py3-none-any.whl (28 kB)
Collecting traitlets>=5.3
  Using cached traitlets-5.13.0-py3-none-any.whl (84 kB)
Collecting importlib-metadata>=4.8.3
  Using cached importlib_metadata-6.8.0-py3-none-any.whl (22 kB)
Collecting tornado>=6.2
  Using cached tornado-6.3.3-cp38-abi3-macosx_10_9_x86_64.whl (423 kB)
Collecting pyzmq>=23.0
  Using cached pyzmq-25.1.1-cp39-cp39-macosx_10_15_universal2.whl (1.9 MB)
Collecting appnope
  Using cached appnope-0.1.3-py2.py3-none-any.whl (4.4 kB)
Collecting matplotlib-inline>=0.1
  Using cached matplotlib_inline-0.1.6-py3-none-any.whl (9.4 kB)
Collecting ipython>=7.23.1
  Using cached ipython-8.17.2-py3-none-any.whl (808 kB)
Collecting debugpy>=1.6.5
  Using cached debugpy-1.8.0-py2.py3-none-any.whl (5.0 MB)
Collecting comm>=0.1.1
  Using cached comm-0.2.0-py3-none-any.whl (7.0 kB)
Collecting psutil
  Using cached psutil-5.9.6-cp36-abi3-macosx_10_9_x86_64.whl (246 kB)
Collecting packaging
  Using cached packaging-23.2-py3-none-any.whl (53 kB)
Collecting nest-asyncio
  Using cached nest_asyncio-1.5.8-py3-none-any.whl (5.3 kB)
Collecting zipp>=0.5
  Using cached zipp-3.17.0-py3-none-any.whl (7.4 kB)
Collecting jedi>=0.16
  Using cached jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)
Collecting exceptiongroup
  Using cached exceptiongroup-1.1.3-py3-none-any.whl (14 kB)
Collecting decorator
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Collecting pexpect>4.3
  Using cached pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Collecting stack-data
  Using cached stack_data-0.6.3-py3-none-any.whl (24 kB)
Collecting prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30
  Using cached prompt_toolkit-3.0.39-py3-none-any.whl (385 kB)
Collecting pygments>=2.4.0
  Using cached Pygments-2.16.1-py3-none-any.whl (1.2 MB)
Collecting parso<0.9.0,>=0.8.3
  Using cached parso-0.8.3-py2.py3-none-any.whl (100 kB)
Collecting platformdirs>=2.5
  Using cached platformdirs-3.11.0-py3-none-any.whl (17 kB)
Collecting jsonschema>=2.6
  Using cached jsonschema-4.19.2-py3-none-any.whl (83 kB)
Collecting fastjsonschema
  Using cached fastjsonschema-2.18.1-py3-none-any.whl (23 kB)
Collecting jsonschema-specifications>=2023.03.6
  Using cached jsonschema_specifications-2023.7.1-py3-none-any.whl (17 kB)
Collecting rpds-py>=0.7.1
  Using cached rpds_py-0.12.0-cp39-cp39-macosx_10_7_x86_64.whl (334 kB)
Collecting referencing>=0.28.4
  Using cached referencing-0.30.2-py3-none-any.whl (25 kB)
Collecting attrs>=22.2.0
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting ptyprocess>=0.5
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting wcwidth
  Using cached wcwidth-0.2.9-py2.py3-none-any.whl (102 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting textwrap3>=0.9.2
  Using cached textwrap3-0.9.2-py2.py3-none-any.whl (12 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.0.7-py3-none-any.whl (124 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2023.7.22-py3-none-any.whl (158 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.3.2-cp39-cp39-macosx_10_9_x86_64.whl (122 kB)
Collecting pure-eval
  Using cached pure_eval-0.2.2-py3-none-any.whl (11 kB)
Collecting executing>=1.2.0
  Using cached executing-2.0.1-py2.py3-none-any.whl (24 kB)
Collecting asttokens>=2.1.0
  Using cached asttokens-2.4.1-py2.py3-none-any.whl (27 kB)
Installing collected packages: rpds-py, attrs, referencing, zipp, traitlets, six, platformdirs, jsonschema-specifications, wcwidth, tornado, pyzmq, python-dateutil, pure-eval, ptyprocess, parso, jupyter-core, jsonschema, importlib-metadata, fastjsonschema, executing, asttokens, urllib3, typing-extensions, textwrap3, stack-data, pygments, prompt-toolkit, pexpect, nbformat, matplotlib-inline, jupyter-client, jedi, idna, exceptiongroup, decorator, charset-normalizer, certifi, appnope, tqdm, tenacity, requests, pyyaml, psutil, packaging, nest-asyncio, nbclient, ipython, entrypoints, debugpy, comm, click, ansiwrap, papermill, ipykernel, find-libpython
Successfully installed ansiwrap-0.8.4 appnope-0.1.3 asttokens-2.4.1 attrs-23.1.0 certifi-2023.7.22 charset-normalizer-3.3.2 click-8.1.7 comm-0.2.0 debugpy-1.8.0 decorator-5.1.1 entrypoints-0.4 exceptiongroup-1.1.3 executing-2.0.1 fastjsonschema-2.18.1 find-libpython-0.3.0 idna-3.4 importlib-metadata-6.8.0 ipykernel-6.26.0 ipython-8.17.2 jedi-0.19.1 jsonschema-4.19.2 jsonschema-specifications-2023.7.1 jupyter-client-8.6.0 jupyter-core-5.5.0 matplotlib-inline-0.1.6 nbclient-0.9.0 nbformat-5.9.2 nest-asyncio-1.5.8 packaging-23.2 papermill-2.4.0 parso-0.8.3 pexpect-4.8.0 platformdirs-3.11.0 prompt-toolkit-3.0.39 psutil-5.9.6 ptyprocess-0.7.0 pure-eval-0.2.2 pygments-2.16.1 python-dateutil-2.8.2 pyyaml-6.0.1 pyzmq-25.1.1 referencing-0.30.2 requests-2.31.0 rpds-py-0.12.0 six-1.16.0 stack-data-0.6.3 tenacity-8.2.3 textwrap3-0.9.2 tornado-6.3.3 tqdm-4.66.1 traitlets-5.13.0 typing-extensions-4.8.0 urllib3-2.0.7 wcwidth-0.2.9 zipp-3.17.0
WARNING: You are using pip version 21.1.1; however, version 23.3.1 is available.
You should consider upgrading via the '/Users/mac/.modular/pkg/packages.modular.com_mojo/venv/bin/python -m pip install --upgrade pip' command.
[mojo] Testing: `mojo build test_mandelbrot.mojo` [FAIL]
[mojo] Testing: `mojo build test_python.mojo` [FAIL]
[mojo] Testing: `mojo test_python.mojo` [FAIL]
[mojo] Testing: `mojo repl` [FAIL]
[mojo] Some components may have been installed successfully, but others may not work as expected. Please submit an issue to https://github.com/modularml/mojo and include the full output of the command you just ran.
modular: error: failed to run python:

### Steps to reproduce

I followed steps as https://developer.modular.com/download says with `Set up on Mac` selected.

After the third step `modular install mojo`, the output tells me to submit this issue.

### Version Info

```shell
- Modular CLI version: modular 0.2.2 (95d42445)
- OS: macOS Sonoma
```

**Comment by modocache** [comment]
Thanks for the report! More recent versions of the `modular` tool, as well as the Mojo and MAX packages, include more detailed error reporting. These failures could be similar to some aspects of #1803 or #1933 -- please try updating your `modular` tool and re-running `modular install mojo` or `modular install nightly/mojo` when you have a chance. If errors persist, please file another issue. Thanks again!
