### ISSUE TITLE
[BUG]: variadic list of functions: Please submit a bug report

### ISSUE THREAD

**Issue by rd4com** [modularml/mojo#1284]
### Bug description

Hello,

somebody asked on discord how to make a variadic list of functions,

i prepared an answer but when i tested the code:
> Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.

```python
fn a() -> Int:
    return 1

fn b() -> Int:
    return 2

fn take_functions(*args: fn() ->Int):
    for i in range(len(args)):
        args[i]()

fn main():
    take_functions(a,b)
```

### Steps to reproduce

Nothing special except the code in the bug description section

### System information

```shell
- Ubuntu 23.04
- Mojo 0.5.0
- Modular 0.2.0
```

**Comment by rd4com** [comment]
Yes, sorry in the description there is an additional back tick (typo) i edited it.

    mojo: /__w/modular/modular/KGEN/lib/ObjectCompiler/StandaloneObject.cpp:68: auto sliceDependencies(mlir::Operation *, mlir::SymbolTable &, const mlir::SymbolTable &)::(anonymous class)::operator()(mlir::StringAttr) const: Assertion `symbol && "invalid IR?"' failed.
    Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.

**Comment by jackos** [comment]
Hi thanks for raising @rd4com this is fixed in the next release
