### ISSUE TITLE
[Docs] argument passing: mention about existence of "reference objects"

### ISSUE THREAD

**Issue by paugier** [modularml/mojo#1294]
### Where is the problem?

https://docs.modular.com/mojo/programming-manual.html#argument-passing-control-and-memory-ownership

### What can we do better?

```python
def my_def(a: object):
    # argument given by copy but one can modify the referenced list
    a[0] = 1

fn my_fn(borrowed a: object) raises:
    # argument borrowed but one can modify the referenced list
    a[0] = 2

def main():
    a = object([0])

    print(a)
    my_def(a)
    print(a)
    my_fn(a)
    print(a)
```

gives (like in Python)

```
[0]
[1]
[2]
```

I think it makes sense because `object` acts like a reference towards another object but this is a bit counterintuitive for readers of  https://docs.modular.com/mojo/programming-manual.html#argument-passing-control-and-memory-ownership.

Note that it also works with `PythonObject`

```python
from python import Python


def setitem(obj: PythonObject, key: String, value: Int):
    # obj is copied but we can modified the Python object
    obj.__setitem__(key, value)


def setitem(obj: PythonObject, idx: Int, value: Int):
    # obj is copied but we can modified the Python object
    obj.__setitem__(idx, value)


def main():
    let python_builtins: PythonObject = Python.import_module("builtins")
    let dict: PythonObject = python_builtins.dict
    let d: PythonObject = dict()
    # error: expression must be mutable in assignment (with Mojo 0.5)
    # d["a"] = 0
    # works:
    d.__setitem__("a", 0)
    print(d["a"])

    d.__setitem__("a", 1)
    print(d["a"])

    setitem(d, "a", 2)
    print(d["a"])

    print("With Numpy:")
    np = Python().import_module("numpy")
    let a = np.zeros(2)
    print(a[0])
    setitem(a, 0, 1)
    print(a[0])
```
which gives:
```
0
1
2
With Numpy:
0.0
1.0
```

**Comment by scottamain** [comment]
Thanks for your suggestion! We have some new documentation coming soon that tackles this very issue. Also note that in a `def` function, the default argument type is `object` to match the Python behavior, so it's not necessary to declare the `object` type on your argument—doing so kind of defeats the purpose that you don't need to declare types in a `def`. :)

**Comment by scottamain** [comment]
I think this is resolved by the new page about value semantics that we published last week:
https://docs.modular.com/mojo/manual/values/value-semantics.html
Please reopen and let us know if there's anything else that could be improved.
