### ISSUE TITLE
[Feature Request] Better fallback support for fp16 vectorization on x86

### ISSUE THREAD

**Issue by jon-chuang** [modularml/mojo#1296]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

I believe perf is a priority, and bf16/fp16 are important precisions for CPU inference.

If fp16 AVX is not available, I believe MLIR/LLVM should fallback on f32 AVX.

### What is your motivation for this change?

Bad f16 perf on https://github.com/modularml/mojo/pull/1292

### Any other details?
I have not inspected the generated x86 asm. How might I do so?

**Comment by jon-chuang** [comment]
I was able to get around the poor perf by casting and using a SIMD accumulate buffer. See https://github.com/modularml/mojo/pull/1292.

Casting has overhead. But it should not - we should just be able to load the SIMD f32 registers with f16 via x86 instruction.

**Comment by Mogball** [comment]
I think this is something that needs to be built in the library. The code should inspect the target to determine if f16 is available without emulation and otherwise use something else. cc @abduld
