### ISSUE TITLE
[BUG]: VSCode run fails when path includes a space

### ISSUE THREAD

**Issue by enerrio** [modularml/mojo#1299]
### Bug description

I installed Mojo's VSCode extension v0.5.0 but get an error when trying to run a mojo file with the ▶️ button in the top right corner of a mojo file. The error occurs when the full mojo file path includes a space.

In my case I have a mojo file located at `/Users/enerrio/Machine Learning/mojo/hello.mojo` and when I click the ▶️ button I can see in my terminal the command that tries to get executed and the error: 
```
user@username mojo % /Users/enerrio/.modular/pkg/packages.modular.com_mojo/bin/mojo /Users/enerrio/Machine Learning/mojo
/hello.mojo
/Users/enerrio/.modular/pkg/packages.modular.com_mojo/bin/mojo: error: no such command '/Users/enerrio/Machine'
```

### Steps to reproduce

1. Install Mojo's VSCode extension v0.5.0
2. Create a mojo file in a folder with a space in it. ex: "/Users/myusername/mojo project/hello.mojo"
3. Open the "hello.mojo" file in VSCode
4. Click the ▶️ button

My hello.mojo file simply has:
```
from os import env

fn main():
    print("Hello 🔥!")
```

### System information

```shell
- What OS did you do install Mojo on ?
Darwin MacBook-Pro.local 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:43:05 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6020 arm64

- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.5.0 (6e50a738)

- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.2.2 (95d42445)
```

**Comment by Sharktheone** [comment]
I guess, the simplest fix is to remove the space in the path and replace it with a underscore or a dash. But they maybe should fix this, so spaces can be used in the path because when you have a space in your username, this can be quite difficult to fix. But generally just avoid spaces in a path.
