### ISSUE TITLE
[Feature Request] Add Django and FastAPI compatibility

### ISSUE THREAD

**Issue by marquesdavi** [modularml/mojo#13]
## Request

Add to Mojo, support for Python backend development frameworks like Django and FastAPI

### Motivation

The same reason people use Python for backend development! You don't need to learn another programming language to be able to put your ideas on the internet

### Description and Requirements

Be able to create RestAPIs, manage relational databases...

**Comment by sa-** [comment]
Or providing an alternative webserver implementation (so that you don't have to use python unless you want to/have to) would also work. Happy to contribute here if needed!

**Comment by lattner** [comment]
This is a great idea, but I'm not sure it is super actionable right now.  Mojo can already talk to all the existing python apis, so these should (in principle) already work.  I think the more interesting thing will be to develop mojo native apis for this use-case, which will be pretty epic.  OTOH, this will be true for /tons/ of domains, and I don't think we should track all of them.  We should keep building out the language and as it gets more filled out, we can explore these things.

Thank you for filing this though, super exciting time!

**Comment by Bronya0** [comment]
so nice idea！

**Comment by west-github** [comment]
The man himself so happy about mojo and having great community 👏

**Comment by wasdee** [comment]
today i can run
```
from python import Python
import sys

def main():
    fa = Python.import_module("fastapi")
    app = fa.FastAPI()

    print("FastAPI __version__:", fa.__version__)
```
on my WSL2 latest. 


```
from python import Python
import sys

def main():
    fa = Python.import_module("fastapi")
    app = fa.FastAPI()

    print("FastAPI __version__:", fa.__version__)

    @app.get("/")
    def read_root():
        return {"Hello": "World"}

```
this is not working. Below are errors.

```
'/home/nam/.modular/pkg/packages.modular.com_mojo/bin/mojo' '/home/nam/UnixDev/fastapi-mojo/main.mojo'
/home/nam/UnixDev/fastapi-mojo/main.mojo:2:5: error: unexpected tokens after decorator, each need to be on their own line
    def read_root():
    ^
/home/nam/UnixDev/fastapi-mojo/main.mojo:3:16: error: TODO: cannot emit dictionary literals yet
        return {"Hello": "World"}
               ^~~~~~~~~~~~~~~~~~
/home/nam/UnixDev/fastapi-mojo/main.mojo:1:2: error: use of unknown declaration 'app'
@app.get("/")
 ^~~
/home/nam/.modular/pkg/packages.modular.com_mojo/bin/mojo: error: failed to parse the provided Mojo
```

**Comment by danielegaliffa** [comment]
Why this issue is closed?

**Comment by wasdee** [comment]
> Why this issue is closed?

idk. i should reopen i guess.

**Comment by k00000han** [comment]
It's will be great if we could to use **Mojo** for backend development with **FastAPI/Django** the way people use **Typescript** with **React/Vue/Node/**etc.

**Comment by wasdee** [comment]
> It's will be great if we could to use **Mojo** for backend development with **FastAPI/Django** the way people use **Typescript** with **React/Vue/Node/** etc.

I am expecting similar phenomenal like [Elysia](https://elysiajs.com/) typescript on bun-zig. 

I want to see/make a new pythonic fastest web framework on planet.

**Comment by munjed-ab** [comment]
I am so excited for this 🔥

**Comment by GokuSy** [comment]
Is this issue resolved ?

I'm transitioning from Python to Mojo and would like guidance on setting up an endpoint with Mojo.

**Comment by Pyroseza** [comment]
What's happening here? Why is this closed, does it work with both FastAPI and Django?

**Comment by alew3** [comment]
API Endpoints are very important for ML/AI workflows or any web app for that matter. This should be prioritized IMO.

**Comment by Warrio111** [comment]
This is high prio from my point of view

**Comment by tares003** [comment]
Looking forward to this!!!

**Comment by leejongheon42** [comment]
looking forward to this too

**Comment by ArunJRK** [comment]
Looking forward to this. It could entirely change the way we build backends. At least just FastAPI support will be great.

**Comment by danieljohnmorris** [comment]
Why is this closed?

**Comment by KyoungsueKim** [comment]
Looking forward to this too. The reason have been already enriched by above peoples.

**Comment by JudeDavis1** [comment]
+1!!!

**Comment by imitelis** [comment]
I'm currently planning to migrate my FastAPI servers into Mojo too.

**Comment by h3llf1r33** [comment]
any updates ?

**Comment by abelkm99** [comment]
Commenting cause I also want that to happen.

**Comment by Pyroseza** [comment]
@lattner, can you please consider re-opening this so that when the time is right it can be worked on, instead of being closed an buried?

**Comment by Jacksprojects** [comment]
Also extremely excited for this to happen! Keen to contribute where I can

**Comment by lookevink** [comment]
given the interoperability between mojo & py, this should already work out of the box. has anyone tried it?

I'm spinning up a new service that requires chonky parallel processing. love to hear from anyone who's done this, but I can always try things out myself & share results

**Comment by gpsa** [comment]
Any progress on this?
