### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Netadministrator** [modularml/mojo#1306]
### Bug description

When I try to compile a file with "mojo run" command, it returns with the following error:

0.	Program arguments: mojo Kutuphane.mojo
#0 0x000055bd3256c197 (/home/ahmet/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5c9197)
#1 0x000055bd32569d6e (/home/ahmet/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5c6d6e)
#2 0x000055bd3256c86f (/home/ahmet/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5c986f)
#3 0x00007f2709cc3520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
Parçalama arızası (çekirdek döküldü)

Mojo is running under Linux Mint 21.2 system. I also encounter error when I use the "source ~ .bashrc" command.
Thank you for your interest.

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by ematejska** [comment]
As you are running into this with the "source ~ .bashrc" command, this does not appear to be a mojo SDK bug.  I would recommend debugging your bashrc script and narrowing down to the offending lines.
