### ISSUE TITLE
[BUG]: Parameter of type `fn` doesn't accept function with default argument

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1307]
### Bug description

As title.

### Steps to reproduce

Consider the following code:

```mojo
fn main():
  print(apply[add]())

fn apply[f: fn(Int, Int) -> Int]():
  return None

fn add(a: Int, b: Int = 0) -> Int:
  return a + b
```

raises

```
error: cannot pass 'fn(a = Int, b = Int) -> Int' value, parameter expected 'fn(Int, Int, /) -> Int'
```

### System information

```shell
Mojo 0.5.0 on Docker, Intel Mac
```

**Comment by jackos** [comment]
Try:

```rust
fn main():
  print(apply[add]())

fn apply[f: fn(a: Int, b: Int = 0) -> Int]():
  return None

fn add(a: Int, b: Int = 0) -> Int:
  return a + b
```

**Comment by Mogball** [comment]
@soraros What Jack suggested will work, but I believe the implicit function conversion you're attempting should work. This is still a bug.

**Comment by suahelen** [comment]
I ran into a similar issue while trying to run a gradio app from mojo. I don't know if it would work anyways but the problem still stands. 

here the `fn `is not recognized as a keyword argument. Thus, it does not compile.

```
fn greet():
    print("hello")

fn main():
    try:
        let gr = Python.import_module("gradio")
        demo = gr.Interface(fn=greet, inputs="text", outputs="text")
        demo.launch()   
    except e:
        print(e)

```

**Comment by laszlokindrat** [comment]
Thanks for opening the ticket, a fix is on the way to allow passing function parameters where the expected signatures differ in the default values.
