### ISSUE TITLE
[BUG]: cannot use a dynamic value in type specification

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [modularml/mojo#1308]
### Bug description

I'm trying to use range with the signature that has 3 arguments. Here is my code:

```python
fn iterate(length: Int = 1, reverse: Bool = False):
    var order: range(0, length, 1)
    if reverse:
        order = range(length -1, -1, -1)
    ...


def main():
    iterate()
```
which should be correct if we refer to this page in the docs: https://docs.modular.com/mojo/stdlib/builtin/range.html

But I have the following message:

```bash
$ mojo trying_stuff.mojo
/projects/open_source/mojo-stdlib-extensions/trying_stuff.mojo:2:25: error: cannot use a dynamic value in type specification
    var order: range(0, length, 1)
                        ^~~~~~
mojo: error: failed to parse the provided Mojo
```

### Steps to reproduce

See above

### System information

```shell
- What OS did you do install Mojo on ? 
ubuntu 22.04 under docker under wsl
$ mojo -v
mojo 0.4.0 (9e33b013)
$ modular -v
modular 0.2.1 (5144fffe)
```

**Comment by gabrieldemarmiesse** [comment]
You're right I feel stupid, thanks.

Though maybe the error message could be improved? I mean it's pretty far from the actual problem with my code.

**Comment by ematejska** [comment]
Thanks for reporting this.
