### ISSUE TITLE
[BUG]: Simple code using `parallelize` crashes the parser

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1309]
### Bug description

As title. If the `worker` function is decorated with `parameter`, it runs fine.

### Steps to reproduce

Consider the following code:
```mojo
from algorithm.functional import parallelize

fn f(l: DynamicVector[Int]):
  fn worker(i: Int):
    let a = l[i]
  parallelize[worker](2, 2)
```

### System information

```shell
Mojo 0.5.0 on Docker, Intel Mac
```

**Comment by ematejska** [comment]
Can you paste the crash that you see?

**Comment by laszlokindrat** [comment]
This is definitely a parser issue, as I was able to isolate it from the standard library:
```mojo
alias Int = __mlir_type.index

fn parallelize[func: fn (Int) capturing -> None](): pass

trait Copyable:
    fn __copyinit__(inout self, existing: Self): ...

struct Stuff(Copyable):
    fn __copyinit__(inout self, existing: Self): pass

fn f(s: Stuff):
    fn worker(i: Int):
        var a = s
    parallelize[worker]()
```
@stumpOS Could you please take a look?

**Comment by stumpOS** [comment]
I was unable to reproduce this on the latest release (0.7). It did not crash but produced an error message. You will need to use the `@parameter` decorator moving forward to bind closures to parameter values. i.e. 
```
from algorithm.functional import parallelize

fn f(l: DynamicVector[Int]):
  @parameter
  fn worker(i: Int):
    let a = l[i]
  parallelize[worker](2, 2)
```

**Comment by soraros** [comment]
@stumpOS Great, thanks!
