### ISSUE TITLE
[BUG]: Mojo permits the use of any constructor for implicit conversions

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1310]
### Bug description

As title. Maybe it's working as intended, but I consider it a bug, for Mojo is not JavaScript. Is the behaviour there to circumvent the traitless-ness of `print`?

### Steps to reproduce

I think the following code shouldn't type check.

```mojo
fn main():
  let s: String = 1
```

### System information

```shell
Mojo 0.5.0 on Docker, Intel Mac
```

**Comment by guidorice** [comment]
Not sure it's implicit, I think this is just how the `stdlib` String is implemented. It has a constructor that takes an int, and a dozen of other constructors.

> Constructs a string representing an integer value.
https://docs.modular.com/mojo/stdlib/builtin/string.html#init__

**Comment by guidorice** [comment]
If you try the opposite, you can generate a compiler error:

`let n: Int = "42"`

> cannot implicitly convert 'StringLiteral' value to 'Int' in 'let' initializer

**Comment by guidorice** [comment]
I was thinking that it is simply because String has a constructor that takes an Int value- however , now I am not so sure about how implicit conversions really work, and could not find in the programming manual where this is explained. Good question 👍🏽

**Comment by helehex** [comment]
I like it, but an `@explicit` decorator would be nice

**Comment by helehex** [comment]
also, if you want to control this in the mean time, I've been wrapping the argument in a single tuple and it usually works

**Comment by ivellapillil** [comment]
Implicit conversions are going to be headscratchers in the future. At least marking a constructor as @implicit would document that such a conversation is taking place.

**Comment by helehex** [comment]
@nonmaterializable is even impliciter

**Comment by helehex** [comment]
i wonder if we'll ever get the implicitest conversion

**Comment by lattner** [comment]
Agree, we need to make implicit conversions be opt-in with an `@implicit` sort of decorator or something

**Comment by guidorice** [comment]
@soraros I think that's not so much about implicit conversions. 

"The overload resolution logic filters for candidates according to the following rules, in order of precedence" seems well documented here: https://docs.modular.com/mojo/programming-manual.html#overloading-on-parameters

**Comment by guidorice** [comment]
It does see counter-intuitive,  that the numeric types don't win in that overload. But the docs say the precedence is:

> 1. Candidates with the minimal number of implicit conversions (in both arguments and parameters).

**Comment by JoeLoser** [comment]
One option for moving forward in the short-term would be to have an explicit `to_string` function on the `Int` type and remove the `String` constructor taking in an `Int`.

**Comment by arthurevans** [comment]
@scottamain @JoeLoser did tagging this issue documentation remove the mojo-stdlib label? There is probably more we could do in the docs, but I think this is mostly a stdlib issue (for specific conversions) and/or a Mojo issue (adding a way to separate implicit conversions from other constructor types.

**Comment by scottamain** [comment]
> @scottamain @JoeLoser did tagging this issue documentation remove the mojo-stdlib label? There is probably more we could do in the docs, but I think this is mostly a stdlib issue (for specific conversions) and/or a Mojo issue (adding a way to separate implicit conversions from other constructor types.

No, Will removed the stdlib tag, maybe because this is primarily a language behavior in terms of how implicit conversion happens. Also, this issue was reported before we published [this documentation about implicit conversion](https://docs.modular.com/mojo/manual/variables.html#implicit-type-conversion), which describes the current behavior but without acknowledging this issue. I think we should wait until something changes before updating those docs, but maybe we should add a note with a link to this issue.

**Comment by lattner** [comment]
@bethebunny has a proposal

**Comment by JoeLoser** [comment]
> @bethebunny has a proposal

@bethebunny do you want to push on this some more or want @modularml/mojo-standard-library to run with it?

**Comment by eric-vader** [comment]
Yea, consider this to be a bug too..
Strange case using vectors; I thought its the type checker but found this thread and realised its the implicit cast.

```mojo
from tensor import Tensor
fn print_tensor[dtype: DType](x:Tensor[dtype]):
    print(x)

fn main() raises:

    print_tensor[DType.float64](Int(1))
    print_tensor[DType.float64](1)
    print_tensor[DType.float64](Tensor[DType.float64](1))
```

**Comment by helehex** [comment]
still waiting on the implicitest conversion

**Comment by helehex** [comment]
recursively search for the path of least resistance from one type to another, and automatically follow it :]

**Comment by gabrieldemarmiesse** [comment]
I have a more general question about this issue. Is any implicit conversion needed in the language? Would getting rid of it impact the usability of the language if we have automatic materialization (`IntLiteral` -> `Int`, `StringLiteral` -> `String`, etc...)
