### ISSUE TITLE
[BUG]: benchmark.keep() throws error with SIMD size greater than 1

### ISSUE THREAD

**Issue by helehex** [modularml/mojo#1316]
### Bug description

Moving the SIMD into a `var` fixes the problem.
Happens on any DType, and any size greater than 1.

### Steps to reproduce

```
fn main():
    from benchmark import keep
    keep(SIMD[DType.index,2]())
```

error:
```
error: couldn't allocate input reg for constraint 'r'
```

### System information

```shell
Host Information
  ================

  Target Triple: x86_64-unknown-linux
  CPU: skylake
  CPU Features: 64bit, adx, aes, avx, avx2, bmi, bmi2, clflushopt, cmov, crc32, cx16, cx8, f16c, fma, fsgsbase, fxsr, invpcid, lzcnt, mmx, movbe, pclmul, popcnt, prfchw, rdrnd, rdseed, rtm, sahf, sgx, sse, sse2, sse3, sse4.1, sse4.2, ssse3, x87, xsave, xsavec, xsaveopt, xsaves

mojo 0.5.0 (6e50a738)

modular 0.2.2 (95d42445)
```

**Comment by JoeLoser** [comment]
Repro confirmed, although with latest `mojo`, we hitting an assertion:

```
Assertion failed: (PartVT.getFixedSizeInBits() > ValueSize && "lossy conversion of vector to scalar type"), function getCopyToPartsVector, file SelectionDAGBuilder.cpp, line 720.
```

End result is the still the same: `simd_width` of `1` works, but `2` or higher crashes. FYI: @abduld

**Comment by HJLebbink** [comment]
I have the same issue, but I cannot circumvent the problem. On 0.6.0, any keep (or a var or let) keeps giving me the constraint violation `error: couldn't allocate input reg for constraint 'r'`

**Comment by abduld** [comment]
Thanks for reporting @helehex and @HJLebbink . This issue is fixed in the next release of Mojo
