### ISSUE TITLE
[BUG]: Mojo parser raises invalid errors after backticking unicode identifier

### ISSUE THREAD

**Issue by MonsterAzi** [modularml/mojo#1319]
### Bug description

Attempting to use a unicode character, such as ψ or 🐟, in Mojo results in errors in the parser as expected. The issue is that these errors are persistent and will stick around after the error has been resolved, when they should disappear. The errors can be resolved by closing the file and reopening it.

### Steps to reproduce

```
fn main():
    let 🥺 = 4
```
![image](https://github.com/modularml/mojo/assets/120850865/4a540f01-3d46-448e-95ee-da32b05f143a)
changing `🥺` to `a` still results in errors in the parser.
![image](https://github.com/modularml/mojo/assets/120850865/d42b0af8-c859-480a-8250-e5f59acc9162)
_Weirdly a new error appears afterwards_
![image](https://github.com/modularml/mojo/assets/120850865/bad3f588-6b39-43f5-b17c-a493d646eb98)

### System information

```shell
- Remote VSCode through WSL2 Ubuntu 22.04 on Windows 11 22H2
- mojo 0.5.0 (6e50a738)
- modular 0.2.2 (95d42445)
```

**Comment by River707** [comment]
Thanks for filing! Unfortunately Mojo doesn't yet have full support for unicode identifiers/plumbing, so issues like this are a bit expected for now. We intend to get there, but the timeline isn't fully sketched out yet.
