### ISSUE TITLE
[Modular CLI]: Installation error in Ubuntu in WSL2 on Surface Pro X - SQ2 ARM based processor

### ISSUE THREAD

**Issue by odeame** [modularml/mojo#1320]
### Issue description

Installation error for Ubuntu under WSL2 on Windows 11 Pro on Surface Pro X (ARM based SQ2 processor)

### Steps to reproduce

>modular install mojo
modular: error: no packages found for the current target hardware - please run `modular host-info` and file a ticket at https://github.com/modularml/mojo with your hardware information
> modular host-info
  Host Information
  ================

  Target Triple: aarch64-unknown-linux
  CPU: cortex-a76
  CPU Features: aes, crc, crypto, dotprod, fp-armv8, fullfp16, lse, neon, ras, rcpc, rdm, sha2, ssbs

### Version Info

```shell
> modular -v
modular 0.2.2 (95d42445)
> cat /etc/os-release
PRETTY_NAME="Ubuntu 23.04"
NAME="Ubuntu"
VERSION_ID="23.04"
VERSION="23.04 (Lunar Lobster)"
VERSION_CODENAME=lunar
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=lunar
LOGO=ubuntu-logo
> winver
Windows 11 Pro
Version 23H2 (OS Build 226312715)
```

**Comment by jackos** [comment]
Hi @odeame we don't support ARM on Linux yet which would enable this, there's a ticket to upvote here for that here: https://github.com/modularml/mojo/issues/1093

But we'll likely support native windows before this anyway, which has a ticket here: https://github.com/modularml/mojo/issues/620
