### ISSUE TITLE
[Modular CLI]: Unable to install mojo on RHEL

### ISSUE THREAD

**Issue by sreerajkksd** [modularml/mojo#1324]
### Issue description

I'm trying to use Redhat Enterprise Linux (RHEL) 8.8 to install mojo.

I managed to install modular on the host through the official documentation (which install the yum repositories). 

```
[1]8.8P 01:59 karicher-rh8.toa(nyc) ~$ modular --version
modular 0.2.2 (95d42445)
[0]8.8P 02:01 karicher-rh8.toa(nyc) ~$
```

... and installing mojo fails with:

```
[0]8.8P 01:59 karicher-rh8.toa(nyc) ~$ modular install mojo
modular: error: http error: response code 503 -
[1]8.8P 01:59 karicher-rh8.toa(nyc) ~$
```

I have checked the firewall and confirmed that we are allowing all the IPs requested on the host, so it is unlikely that our firewall is causing this.

I could see a similar issue reported in https://github.com/modularml/mojo/issues/573 and mentioned that you have 0.3.x deployed a couple of months back. However, the latest that I see here is 0.2.2.

I have a couple of questions:

- Is Redhat supported for using mojo ?
- Can we get the latest version of mojo on the RPM repositories ?
- Is this something else ?

### Steps to reproduce

- Use RHEL 8.8
- Install modular cli as per the documentation
- Try running "modular install mojo"

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
[1]8.8P 01:59 karicher-rh8.toa(nyc) ~$ modular --version
modular 0.2.2 (95d42445)
[0]8.8P 02:01 karicher-rh8.toa(nyc) ~$

- What OS did you install modular CLI on ?

Redhat Enterprise Linux 8.8
```

**Comment by sreerajkksd** [comment]
Also, is it possible to mention the endpoint that return 503 in verbose mode ? 

eg:

```
modular: error: http error: xxxxxx.modular/com/yyyyyyyyy/zzzzz response code 503 -
```

**Comment by sreerajkksd** [comment]
I managed to get this working by adding tweaking the firewalls to not restrict the following URLs.

https://dl.modular.com/ 
https://packages.modular.com/
https://cas.modular.com/

So, my only question here is:  Can we tweak the modular error reporting to include the URL that returned non 200 code ?

**Comment by ematejska** [comment]
Thank you for trying out Mojo.  The installation experience has significantly changed and we're closing out all the old issues with the old installer.  To try out our new installation experience using "magic", please see: https://docs.modular.com/mojo/manual/get-started.
