### ISSUE TITLE
How to run a module?

### ISSUE THREAD

**Issue by keisanng** [modularml/mojo#1334]
### Issue description

I've set up a Pythonic module with Mojo as shown:

```
.
|-- README.md
`-- mod
    |-- __init__.mojo
    `-- __main__.mojo
```

And I'd like to run it as you'd run a module with Python, just using Mojo:

```sh
mojo run -m mod
```

A `-p` flag for package instead of `-m` for module seems more Mojo-like to me.

### Steps to reproduce

Simply recreate the file structure.

### Version Info

```shell
- modular 0.2.2 (95d42445)
- Arch Linux (latest)
```

**Comment by River707** [comment]
Thanks for the report! Running a package is not something that is currently supported, you'd need to pull the __main__ out and run that way. It's a bit unfortunate, but something that we haven't had time to look into yet!

**Comment by walter-erquinigo** [comment]
After revisiting this, this feature is not part of the roadmap and we won't work on this in the foreseeable future.
Thanks for the report, anyway!
