### ISSUE TITLE
Progress Bar in Modular CLI

### ISSUE THREAD

**Issue by developer-kush** [modularml/mojo#1336]
### Issue description

Can we please have a Progress Bar in the Modular CLI since it doesn't show if and how many of the required packages and files are being downloaded.
It just seems as if the installation is stuck.

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
> modular install mojo
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v` 
> v0.2.2 (95d42445)
- What OS did you install modular CLI on ?
> Ubuntu 22.04 (Jammy Jellyfish)
```

**Comment by smuniraj2018** [comment]
Thanks for the feedback @developer-kush. We will forward the request to our product team
