### ISSUE TITLE
[BUG][mojo-stdlib] `String.find()` returns wrong value when starting index is non-zero

### ISSUE THREAD

**Issue by L29CtWQQV** [modularml/mojo#1355]
### Bug description

I noticed, that String.find using an start-index, gives the difference between the start-index and the index of the sub-string occurrence.
In Python on the other hand, the index of the occurrence is returned.
So I think the Mojo behavior should match the Python one.

### Steps to reproduce

Python:
```
>>> t = "...a"
>>> t.find("a",0)
3
>>> t.find("a",1)
3
>>> t.find("a",2)
3

```

Mojo REPL :
```
  1> var t : String = "...a"

  8> print(t.find("a",0)) 
3
  9> print(t.find("a",1))
2
 10> print(t.find("a",2))
1

```

### System information

```shell
on Debian GNU/Linux 12 (bookworm)
with mojo version:
mojo 0.5.0 (6e50a738)
python version:
Python 3.11.2
```

**Comment by JoeLoser** [comment]
This is unintuitive and should be fixed - thanks for reporting it.  I agree that the Mojo Standard Library should match the Python implementation here.  Regardless of what `start` offset you pass, the caller should reasonably expect the right offset **from the beginning of the string** should be returned based on the found substring.

**Comment by ConnorGray** [comment]
Thanks for the report! This is fixed now, and will be in the the next Mojo release.
