### ISSUE TITLE
[Feature Request] : Mojo 🔥 version 0.6

### ISSUE THREAD

**Issue by mojo-for-ai** [modularml/mojo#1356]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Issuing an update to the Mojo 🔥 programming language to become 0.6

### What is your motivation for this change?

Mojo 🔥 0.5 is great, but Mojo 🔥 0.6 is even more amazing 🔥🔥🔥

### Any other details?

When will Mojo 🔥 0.6 be released?

**Comment by ivellapillil** [comment]
I don't think we should create features for this. I suggest to close this as it just fills in the backlog with spurious stuff.

**Comment by mojo-for-ai** [comment]
> لا أعتقد أنه يجب علينا إنشاء ميزات لهذا الغرض. أقترح إغلاق هذا لأنه يملأ الأعمال المتراكمة بأشياء زائفة.
> 
> للأسئلة يمكنك الذهاب إلى قسم المناقشات. كثيرًا ما يجيب أعضاء فريق Mojo على الأسئلة هناك.
What's your business?

**Comment by mojo-for-ai** [comment]
> لا أعتقد أنه يجب علينا إنشاء مهارات لهذا الحصاد. أقترح إغلاق هذا لأنه يملأ الأعمال المتراكمة بأشياء زائفة.
> 
> للأسئلة يمكنك الذهاب إلى قسم المناقشات. كثيرًا ما يجيب أعضاء فريق Mojo على الأسئلة هناك.




Whoever you are, you idiot, don't force me to do what I should do

**Comment by lattner** [comment]
Let's be kind, but I agree that we don't need this tracking bug.  You'll know when 0.6 is ready, we're working hard on it!
