### ISSUE TITLE
[BUG]: Error if the file is called `debug.🔥`

### ISSUE THREAD

**Issue by isuckatcs** [modularml/mojo#1361]
### Bug description

If a file is called `debug.mojo` or `debug.🔥`, the interpreter gives unrelated errors.

```
// debug.🔥
fn main():
```
```
> mojo debug.🔥
debug.🔥:1:1: error: recursive reference to declaration
fn main():
^
debug.🔥:1:1: note: previously used here
fn main():
^
debug.🔥:1:1: error: unable to locate module 'lldb'
fn main():
^
mojo: error: failed to parse the provided Mojo
```
It seems like the filename `debug` is reserved.

### Steps to reproduce

- Create a file called `debug.mojo` or `debug.🔥`
- Define `fn main():` in the created file
- Invoked the mojo interpreter with the file

### System information

```shell
- Ubuntu 22.04 (WSL 2)
- mojo 0.5.0 (6e50a738)
- modular 0.2.2 (95d42445)
```

**Comment by JoeLoser** [comment]
This is expected behavior right now.  You cannot have a file called `debug.mojo` or `debug.🔥`.  @walter-erquinigo do you mind adding some docs to improve this for external users?

**Comment by walter-erquinigo** [comment]
@JoeLoser , this is a more general error in which you can't create a file whose name matches one of the stdlib packages, this includes `debug` and `algorithm`, among others.

Look at this:

```
 mojo run algorithm.mojo
/Users/walter/Source/modular/algorithm.mojo:1:1: error: unable to locate module 'functional'
fn main():
^
mojo: error: failed to parse the provided Mojo
```

@Mogball , should this be a thing to fix in the compiler side or we just forbid this?
