### ISSUE TITLE
[Docs] Searching for caret `^` makes the docs webpage OOM

### ISSUE THREAD

**Issue by fnands** [modularml/mojo#1363]
### Where is the problem?

https://docs.modular.com/mojo/changelog.html?q=^#may-2023

### What can we do better?

I was searching for info on the `^` operator, and that crashed my browser. 
Tested on Chrome, Firefox, and Chrome on my phone. 

If you search for `^` and select anything in the dropdown menu the webpage starts gobbling up memory until it crashes the tab. 

Another example: `https://docs.modular.com/mojo/notebooks/Mandelbrot.html?q=^`

**Comment by scottamain** [comment]
Thanks for reporting this. I think it's the same issue as this one: https://github.com/modularml/mojo/issues/265
