### ISSUE TITLE
[BUG]: string.replace() behaves wrong in multiple-character reductions

### ISSUE THREAD

**Issue by p88h** [modularml/mojo#1367]
### Bug description

When replacing two spaces with one (to remove duplicate spaces), the runtime will mis-align some of the replacements,
producing some funny results. A small reproduction is included below. 

```
    var s = String("a   complex  test case  with some  spaces")
    s = s.replace("  "," ")
    print(s)
# prints: 
a  complex test case with some  aces
```

### Steps to reproduce

- Get a string with multiple spaces, like "a   complex  test case  with some  spaces"
- Try to get rid of the multiple spaces with `string.replace("  "," ")`
- Fail hilariously
- Despair
- Debug
- Despair some more
- Rework the code to never use string.replace
- File a bug, just in case others run into it.

### System information

```shell
- What OS did you do install Mojo on ?
Win11 + WSL2 + Ubuntu 23.04
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.5.0 (6e50a738)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.2.2 (95d42445)
```

**Comment by p88h** [comment]
Also broken in mojo 0.6.0 (d55c0025)

**Comment by ConnorGray** [comment]
Thank you for the report @p88h! Apologies for the frustration this caused. I'm happy to report this has been fixed, and should be working in the next Mojo🔥 release (the fix unfortunately did not make it into Mojo 6.1, released yesterday).

Please let us know if you run into any further issues.
