### ISSUE TITLE
[BUG]: memset() doesn't work with initializers other than zero (for Int at least)

### ISSUE THREAD

**Issue by p88h** [modularml/mojo#1368]
### Bug description

Memset seems to behave badly with non-zero initializers:

```
  from memory import memset 
  alias intptr = DTypePointer[DType.int32] 
  var buf = intptr.alloc(1000)  
  memset(buf, 1, 1000) 
  print(buf.load(0))   
# prints:
16843009
```

### Steps to reproduce

- create an integer buffer
- try to set it all to 1
- Fail hilariously
- Despair
- Debug
- Despair some more
- Rework the code to set to 0 and add 1 later
- File a bug, just in case others run into it.

### System information

```shell
- What OS did you do install Mojo on ?
Win11 + WSL2 + Ubuntu 23.04
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.5.0 (6e50a738)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.2.2 (95d42445)
```

**Comment by p88h** [comment]
Also in mojo 0.6.0 (d55c0025)

**Comment by p88h** [comment]
I'm not sure if this is actually fixed ? 
```
from memory import memset
from buffer import Buffer
from memory.unsafe_pointer import UnsafePointer

alias intptr = UnsafePointer[Int]

fn main():
    # Prints junk, not 1
    buf = intptr.alloc(1000)
    memset(buf, 1, 1000)
    print(buf[0], buf[999])
    # This works
    buff = Buffer[DType.int32, 1024].stack_allocation()
    buff.fill(1)
    print(buff[0],buff[1023])    
```
this still breaks with mojo 24.5.0

**Comment by soraros** [comment]
I think `memset` fills *bytes*, not values (in your case, `Int`).

**Comment by p88h** [comment]
Oh ok, got it. So I can initialize to zero in this case, but anything else, memset will not work.

**Comment by soraros** [comment]
It will, for instance, fill your `Int` with eight `0x01` which gives you `72340172838076673` (try `hex(...)`). Depending on the use case, you might categorise that as "not working".
