### ISSUE TITLE
[BUG]: Memory corruption and segfault from global python instance

### ISSUE THREAD

**Issue by isuckatcs** [modularml/mojo#1370]
### Bug description

The following snippets seems to have memory corruption issues and even segfaults sometimes.

```
from python import Python

var py = Python()


fn world() -> String:
    let s = py.__str__("world")
    return s


fn main():
    let s = py.__str__("hello")

    print(s, world())
```
```
$ mojo repro.🔥 
world world
$ mojo repro.🔥 
[17094:17094:20231204,131340.563286:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[17094:17094:20231204,131340.563341:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.      Program arguments: mojo repro.\360\237\224\245
#0 0x000055924fd8d997 (/home/danny/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5c7997)
#1 0x000055924fd8b56e (/home/danny/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5c556e)
#2 0x000055924fd8e06f (/home/danny/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5c806f)
#3 0x00007f0d07af6520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
#4 0x00007f0c70006113 
Segmentation fault
```

As seen from the output, the behavior is completely undefined, if the interpreter doesn't crash, the resulting message is corrupted.

If the snippet is slightly modified, the crash seems to go away, only the corrupted output remains.
```
from python import Python


fn world() -> String:
    var py = Python()
    let s = py.__str__("world")
    return s


fn main():
    var py = Python()
    let s = py.__str__("hello")

    print(s, world())
```
```
$ mojo repro.🔥 
world world
```

### Steps to reproduce

- Invoke mojo with the snippets in the description.

### System information

```shell
- Ubuntu 22.04 (WSL 2)
- mojo 0.5.0 (6e50a738)
- modular 0.2.2 (95d42445)
```

**Comment by rarebreed** [comment]
Hopefully top level code will be supported soon, but currently it is not.  Everything has to reside in either a function or struct right now.  The line `var py = Python()` (outside any fn) in the first example would be "top level" code.

However, the second code example should work.  I tried this code but got a slightly different error running on mojo 0.6.0 (wsl ubuntu with python 3.10.12)

```
➜  mojo git:(main) ✗ mojo run repro.mojo
world world
```

if I change `main` slightly 

```
fn main():
    var py = Python()
    let t = py.__str__("hello")
    print(t)
    print(t, world())
```

It prints `t` correctly

```
➜  mojo git:(main) ✗ mojo run repro.mojo
hello
world world
```

Since I am using mojo 0.6.0, I am not sure if this is a related issue or not.  I have a feeling the new trait system might be causing the repeat "world world" since print now uses traits I noticed, so perhaps the impl for the print trait is getting the wrong value of T for t.

**Comment by isuckatcs** [comment]
I upgraded to `mojo v0.6.0` and played around with this snippet a bit. It seems like the issue comes from `StringRef`.  

If I explicitly set the type of `s` to `String`, the output is correct.

```python
fn main():
    var py = Python()

    # 's' is 'StringRef' by default
    let s: String = py.__str__("hello")

    print(s, world())
```
```
hello world
```

It seems like the second `StringRef` overwrites the pointer in the first one.

```python
fn world() -> StringRef:
    var py = Python()
    let s = py.__str__("world")
    return s


fn main():
    var py = Python()
    let s = py.__str__("hello")

    print(s.data)
    print(world().data)
    print(s.data)
```
```
hello
world
world
```

**Comment by ematejska** [comment]
Global variables are still not fully supported. Starting to collate the dups here: https://github.com/modularml/mojo/issues/1573. Sorry for the reverse dup.
