### ISSUE TITLE
[BUG]: Invalid call ... memory-only type bound to generic result type

### ISSUE THREAD

**Issue by theopomies** [modularml/mojo#1376]
### Bug description

When using a higher order function with a callback, mojo fails to infer/convert the callbacks signature to the argument's expected signature, I believe this bug was introduced by 0.6.0, easy to reproduce with the snippet below.

### Steps to reproduce

Minmal code to reproduce:

```py
fn map_vector[
    T: CollectionElement, O: CollectionElement
](vector: DynamicVector[T], callback: fn (elem: T) -> O) -> DynamicVector[O]:
    var mapped_vector = DynamicVector[O](capacity=len(vector))
 
    for i in range(len(vector)):
        let elem = callback(vector[i])
        mapped_vector.push_back(elem)
 
    return mapped_vector
 
 
fn callback(elem: String) -> Int:
    return 0
 
 
fn main() raises:
    let vec = DynamicVector[String]()
    """
    invalid call to 'map_vector': argument #1 cannot be converted from 'fn(elem = String) -> Int' to 'fn(/, elem = String) -> Int'
    repro.mojo(19, 34): memory-only type bound to generic result type: argument returns 'Int' by reference
    repro.mojo(1, 1): function declared here
    """
    map_vector[String, Int](vec, callback)
```

### System information

```shell
- What OS did you do install Mojo on ?
macOS Sonoma 14.1.2
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.6.0 (d55c0025)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.2.2 (95d42445)
```

**Comment by theopomies** [comment]
The issue seems related to the `Int` result type, as error suggests, with `String` it works.
Also, removing the bodies of the functions or replacing `... fn (elem: T)...` by `...fn (T)...` doesn't change anything

**Comment by theopomies** [comment]
Overloading the function by replacing `O` by `Int` does solve the issue
```py
# ...
fn map_vector[
    T: CollectionElement,
](vector: DynamicVector[T], callback: fn (T) -> Int) -> DynamicVector[Int]:
    var mapped_vector = DynamicVector[Int](capacity=len(vector))

    for i in range(len(vector)):
        let elem = callback(vector[i])
        mapped_vector.push_back(elem)

    return mapped_vector
# ...
```

But I still believe this is unintended behavior

**Comment by theopomies** [comment]
Note: I get this error with various other functions, all related to `memory-only type bound to generic result type: argument returns 'Int' by reference`

**Comment by lattner** [comment]
@laszlokindrat @Mogball any ideas?

**Comment by Mogball** [comment]
It seems we haven't implemented thunk generation for the conversion of function types that change the passing conventions of the argument or result types!

**Comment by laszlokindrat** [comment]
A lot has changed since the ticket was opened, here is and updated and somewhat minimized repro along with the moderately helpful error message it produces:
```mojo
fn map_vector[
    T: CollectionElement, O: CollectionElement
](callback: fn (elem: T) -> O):
    pass

fn callback(elem: String) -> Int:
    return 0

fn pass_callback():
    map_vector[String, Int](callback)
```
yields
```console
error: invalid call to 'map_vector': argument #0 cannot be converted from 'fn(elem: String) -> Int' to 'fn(elem: String) -> Int'
```
