### ISSUE TITLE
[BUG]: 'Bool' does not implement 'CollectionElement'

### ISSUE THREAD

**Issue by theopomies** [modularml/mojo#1379]
### Bug description

Cannot create a `DynamicVector[Bool]` because 'Bool' does not implement 'CollectionElement'. This seems like an oversight.

### Steps to reproduce

```py
fn main():
    let vec = DynamicVector[Bool]()
```

### System information

```shell
- What OS did you do install Mojo on ?
macOS Sonoma 14.1.2
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.6.0 (d55c0025)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.2.2 (95d42445)
```

**Comment by JoeLoser** [comment]
This is an oversight; I'll fix it now.  Thanks for reporting it!

**Comment by frankrap** [comment]
StringLiteral is also

**Comment by JoeLoser** [comment]
> StringLiteral is also

Thanks for pointing it out - I have a PRs open internally that fix this for both `Bool` and `StringLiteral`.  Let me know if you run into any others and I'll make sure they're fixed before the next release.

**Comment by JoeLoser** [comment]
Those PRs landed and they'll be included in the next release.

**Comment by theopomies** [comment]
Thanks for the reactivity!
