### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by RobotChow** [modularml/mojo#1388]
### Where is the problem?

Page does not load

### What can we do better?

The below URL, does not load. Tested on Safari and Firefox:

https://docs.modular.com/mojo/manual/basics/

**Comment by scottamain** [comment]
It appears you found a broken link. It would help if you share the page where you found it. But this looks familiar and might have been fixed already, so I'm closing this. Please reopen with more information.

**Comment by RobotChow** [comment]
It is still down.   You don't see the link in my original report?  Maybe some security system is filtering it.  Here it is again.

https://docs.modular.com/mojo/manual/basics/

And here broken up:

docs[DOT]modularDOTCOM/mojo/manual/basics/

**Comment by RobotChow** [comment]
OK, I see you wanted to see where Beth link came from . It was on Docs page I believe.  I don't see it there anymore.  It was a link that was meant to describe the 'basics' of Mojo, as you can see in the path.  Looks like it was fixed.  Thanks
