### ISSUE TITLE
[BUG]: `algorithm.sum` gives nondeterministic results when called on tensor buffer

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1390]
### Bug description

As title. Returns senseless result every time it's called. This repro is a reduced `exmaples/reduce.mojo`.

### Steps to reproduce

```mojo
from algorithm import sum
from tensor import Tensor
from memory import memset_zero

fn main():
  alias N = 10
  let t = Tensor[DType.float32](N)
  memset_zero(t.data(), N)
  print(sum(t._to_buffer()))
```

### System information

```shell
Mojo 0.6.0 on Docker, Intel Mac
```

**Comment by soraros** [comment]
Come think about it, it looks like an issue caused by ASAP destruction. So maybe it's working as expected.

**Comment by bethebunny** [comment]
Correct, this is a lifetimes issue. Conceptually we could add a lifetime to Buffer, but we need some time to rethink Tensor.
