### ISSUE TITLE
[BUG]: Global values no longer work in Mojo 0.6.

### ISSUE THREAD

**Issue by mortax** [modularml/mojo#1393]
### Bug description

Global values no longer work in Mojo 0.6.

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.

```
#!/usr/bin/env mojo run

let INT = ((2 ** 63) - 1)
var TEXT = 'text'


fn main():
    print('INT =', INT)
    print('TEXT =', TEXT)

    let int = (2 ** 63) - 1
    let text = 'text'

    print('int =', int)
    print('text =', text)
```

Produces:

```
INT = 0
TEXT = 
int = 9223372036854775807
text = text
```

Expected output:

```
INT = 9223372036854775807
TEXT =  text
int = 9223372036854775807
text = text
```

- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

This worked using 0.5 (and 0.5.1).

What am i missing?

### System information

```shell
- What OS did you do install Mojo on?

macOS 14.1.2 (23B92)

- Provide version information for Mojo by pasting the output of `mojo -v`

mojo 0.6.0 (d55c0025)

- Provide Modular CLI version by pasting the output of `modular -v`

modular 0.2.2 (95d42445)
```

**Comment by rarebreed** [comment]
At first I was going to ask if top-level  global values ever worked, because according to the roadmap docs, it still isn't there yet.  But then I tried this expecting it to fail...but it worked :D 

```
from python import Python

let glob = True

fn test() -> Bool:
    return glob

fn main():
    print(test())
```

So, it seems like this is an issue when running just-in-time with `mojo run`.  I built the code with `mojo build global.mojo` and it works

```
➜  mojo git:(main) ✗ mojo build global.mojo
➜  mojo git:(main) ✗ ./global              
INT = 9223372036854775807
TEXT = text
int = 9223372036854775807
text = text
```

**Comment by mortax** [comment]
now that's interesting!

this is what i get:

```
[univac]$ cat global.mojo 
#!/usr/bin/env mojo run

let INT = ((2 ** 63) - 1)
var TEXT = 'text'

fn main():
    print('INT =', INT)
    print('TEXT =', TEXT)

    let int = (2 ** 63) - 1
    let text = 'text'

    print('int =', int)
    print('text =', text)
[univac]$ mojo build global.mojo
[univac]$ ./global 
INT = 0
TEXT = 
int = 9223372036854775807
text = text
```

my system:

```
[univac]$ uname -a
Darwin univac.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020 arm64
[univac]$ mojo -v
mojo 0.6.0 (d55c0025)
[univac]$ modular -v
modular 0.2.2 (95d42445)
```

the good news is that this does work:

```
[univac]$ cat global.mojo 
alias INT = ((2 ** 63) - 1)
alias TEXT = 'text'

fn main():
    print('INT =', INT)
    print('TEXT =', TEXT)

    let int = (2 ** 63) - 1
    let text = 'text'

    print('int =', int)
    print('text =', text)
[univac]$ mojo run global.mojo 
INT = 9223372036854775807
TEXT = text
int = 9223372036854775807
text = text
```

i guess i'll use `alias` for now -- but i'm curious what's going on.

**Comment by soraros** [comment]
@mortax Glad that worked. Mind that `alias` has its own share of problems (#1397).

**Comment by mortax** [comment]
i'm curious why compiling works for you but not for me. strange, no?

**Comment by ematejska** [comment]
Global variables are still not fully supported.  Starting to collate the dups here: https://github.com/modularml/mojo/issues/1573.  Sorry for the reverse dup.

**Comment by mortax** [comment]
@ematejska i agree that it looks like this issue and the other one are getting at the same RC. i'm surprised you duped the older to the newer (and i thought my description was clear - especially given the workaround). the important thing, of course, is that it gets fixed at some point.

**Comment by ematejska** [comment]
Again, sorry for the reverse dup.
