### ISSUE TITLE
[BUG]: Using `Bool` as a alias name causes all kinds of weird behaviour

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1395]
### Bug description

As title.

### Steps to reproduce

1. `recursive reference to declaration`:
```mojo
fn main():
  alias Bool = False
```
2. Parser crash:
```mojo
fn main():
  alias Bool = Int
  let b: Int = False
```
To be continued...

### System information

```shell
Mojo 0.6.0 on Docker, Intel Mac
```

**Comment by laszlokindrat** [comment]
Thanks for filing this issue! Could you please provide the exact crash trace?

**Comment by laszlokindrat** [comment]
I was able to reproduce the crash for this example, and a fix is on its way:
```mojo
fn main():
  alias Bool = Int
  let b: Int = False
```

Regarding the first example in the OP:
```mojo
fn main():
  alias Bool = False
```
The "recursive reference to declaration" error message is technically correct, but we will have improved error messages to point out that you are redeclaring a builtin.

**Comment by soraros** [comment]
@laszlokindrat Thanks a lot for fixing!

**Comment by laszlokindrat** [comment]
@soraros Update: we discussed this internally and decided to retain the current error message for redeclaring the builtins.

Regarding this:

> Does this mean we can't have alias with the same name as builtin ones? That sounds very C like, or very unhygienic.

You can, but as you encountered, it will break the behavior of the builtin being redeclared (e.g. in literals, raised errors, etc.). I agree that this is a sharp edge, so we will discuss some options to mitigate it.
