### ISSUE TITLE
[BUG]: Movable trait not detected on recursive struct implemented with AnyPointer

### ISSUE THREAD

**Issue by theopomies** [modularml/mojo#1402]
### Bug description

When defining a recursive struct (or however you call a struct that has a member of its own Self type) using AnyPointer and implementing the Movable trait on said struct to allow the storage of said struct in AnyPointer, the Movable trait is not detected.

### Steps to reproduce

Minimal reproducible code:
```py
struct S(Movable):
    var s: AnyPointer[Self]

    fn __copyinit__(inout self, other: Self):
        self.s = AnyPointer[Self].alloc(1)
        self.s.emplace_value(other.s)

    fn __moveinit__(inout self: Self, owned other: Self):
        self.s = other.s ^
```

### System information

```shell
- What OS did you do install Mojo on ?
macOS Sonoma 14.1.2
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.6.0 (d55c0025)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.2.2 (95d42445)
```

**Comment by laszlokindrat** [comment]
Thanks for opening the issue! Could you please provide the error message you are seeing?

**Comment by theopomies** [comment]
@laszlokindrat sorry for forgetting to include it, here it is:
```
mojo build repro.mojo             
/path/to/repro.mojo:2:23: error: 'AnyPointer' parameter #0 has 'Movable' type, but value has type 'S'
    var s: AnyPointer[Self]
                      ^~~~
/path/to/repro.mojo:1:1: note: 'AnyPointer' declared here
struct S(Movable):
^
mojo: error: failed to parse the provided Mojo
```

**Comment by laszlokindrat** [comment]
@weiweichen could you please take a look?

**Comment by weiweichen** [comment]
Sure. I was hitting the same issue myself too 😬 .

**Comment by weiweichen** [comment]
Actually this can be fixed by adding ⬇️  to `Struct S`
```
   fn __del__(owned self: Self):
      # anything to do to destroy this struct
```

I agree that the error message is not helpful here. We should figure out how to fix it.

**Comment by weiweichen** [comment]
Ok, we have a fix that won't require 
```
fn __del__
```
to be added for `struct S` explicitly because all structs should have a default destructor (which does nothing). The issue will be close once the fix lands.
