### ISSUE TITLE
[Modular CLI]: modular install mojo should support version pinning

### ISSUE THREAD

**Issue by guidorice** [modularml/mojo#1405]
### Issue description

I cannot figure out how to install a specific version of mojo. This would be useful, essential really, for library maintainers and CI/CD systems.

### Steps to reproduce

```
$ modular install mojo==0.5.0
modular: error: http error: response code 500 - 
```

### Version Info

```shell
modular 0.2.2 (95d42445)

Darwin macbook.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:31 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8112 arm64
```

**Comment by smuniraj2018** [comment]
Thanks for the feedback. We have incorporated this feature in our installer tool and will be released shortly.

**Comment by guidorice** [comment]
`modular install --install-version 0.6.0 mojo`

thanks!
