### ISSUE TITLE
[lifetimes]: misuse of `VariadicList` not caught by the compiler

### ISSUE THREAD

**Issue by mikowals** [modularml/mojo#1428]
### Bug description

Triggering the bug is convoluted and I am sorry I couldn't reduce it further. Calling a function that calls a function that returns a VariadicList gets different values depending on where in the process the contents are checked. The Variadic list contains a `@register_passable("trivial")` struct that holds 2 Ints and is Stringable. Reproducing the issue is very elaborate making me think that it depends on what is in the register and sometimes I can get lucky and the correct values are still available.

By elaborate I mean that even changing print statements inside if branches that are never executed appears to fix the bug. In the project where I discovered this, I fixed it by replacing the VariadicList with a DynamicVector. So given small, seemingly unrelated changes that fixed the bug I am not very confident VariadicList is the source of the problem.

There was also an earlier version of the bug in my project where it was the length of the VariadicList that was changing. It was length 1 inside the callee and length 2 after the return to the caller. I was unable to catch that behaviour in a reproducer but it seems like a symptom of the memory in VaridicList getting screwy.

### Steps to reproduce

The code below is in [this repo](https://github.com/mikowals/mojo_variadic_list_bug/blob/main/reproducer.mojo).

Running the code prints out the VariadicList contents inside the callee, `read_mappings` and after it is returned to the caller, `translate`. The output shows different values with the result in `translate` being incorrect and looking like it is accessing an incorrect or overwritten memory location.

```shell
result in read_mapping: Slice(83, 95)
result in translate: Slice(5123967776, 5123967776)
```

This is the code.  There are a lot of things that seem unrelated but I tried removing them and the bug disappeared so I have put comments on them.

```mojo
import time

from algorithm.sort import partition
from utils.list import Dim
from memory.memory import memcpy


@value
@register_passable("trivial")
struct Slice(CollectionElement, Stringable):
    var start: Int
    var end: Int

    fn __str__(self) -> String:
        return "Slice(" + String(self.start) + ", " + String(self.end) + ")"


@value
@register_passable("trivial")
struct Mapping(CollectionElement, Stringable):
    var destination: Int
    var start: Int
    var end: Int

    fn __init__(destination: Int, start: Int, range: Int) -> Self:
        return Self {destination: destination, start: start, end: start + range}

    fn read_mapping(self, seed: Slice) -> VariadicList[Slice]:
        
        # removing this error check fixes the bug
        if seed.start < self.start or seed.start >= self.end:
            # The print message is not reached during the bug case but
            # making print message shorter or without variables fixes the bug
            print(
                "read mapping slice: Value out of range. slice: "
                + seed.__str__()
                + " start: "
                + self.start
                + " end: "
                + self.end
            )
        let result = VariadicList[Slice](Slice(83, 95))

        # The bug persists without this print but it is useful to see that result is correct here.
        print("result in read_mapping: ", result[0])
        return result

    fn __str__(self) -> String:
        return (
            "Mapping: "
            + String(self.destination)
            + " - "
            + String(self.start)
            + " - "
            + String(self.end)
        )


struct MappingList:
    var mappings: DynamicVector[Mapping]

    fn __init__(inout self):
        self.mappings = DynamicVector[Mapping]()
        self.mappings.push_back(Mapping(52, 50, 48))

    fn add(inout self, mapping: Mapping) raises:
        self.mappings.push_back(mapping)

    fn map_result(inout self, seed: Slice) raises -> VariadicList[Slice]:
        let val = seed.start

        # removing this if fixes the bug
        if val < self[0].start:
            print("unreachable if in map result")
            return VariadicList[Slice](Slice(0, 0))
            # return Mapping(0, 0, self[0].start).read_mapping(seed)

        # removing this print fixes the bug
        print("mid: ", 0, self[0])
        return self[0].read_mapping(seed)

    fn translate(inout self, inout seeds: DynamicVector[Slice]) raises:
        let current = self.map_result(seeds[0])
        
        # removing this print or the len(current) in the print fixes the bug
        # removing this for-loop to just print the current[0] fixes the bug
        for j in range(len(current)):
            print("result in translate: ", current[j])

    fn __getitem__(self, index: Int) raises -> Mapping:
        return self.mappings[index]


fn main() raises:
    var mappings = MappingList()

    # removing this add fixes the bug.  
    # This is creates a second unused element in the DynamicVector so I think the impact is just changing register contents.
    mappings.add(Mapping(50, 98, 2))

    # mappings.translate calls mappings[0].map_result.
    # Calling mappings[0].map_result directly fixes the bug.
    var seeds = DynamicVector[Slice]()
    seeds.push_back(Slice(79, 93))
    mappings.translate(seeds)
```

### System information

```shell
- MacOs Sonoma 14.0 (23A344) on M1 Pro
- mojo 0.6.0 (d55c0025)
- modular 0.2.2 (95d42445)
```

**Comment by laszlokindrat** [comment]
Thanks for opening the ticket! It is difficult to say what is going on here, but using some aggressive bisection, I was able to reduce this to something very short:
```mojo
fn make_list() -> VariadicList[Int]:
    _ = "" + String(1)  # removing this fixes the issue
    return VariadicList[Int](42)

fn main():
    var v = make_list()
    print("non-deterministic:", v[0])
    print("deterministic, but wrong:", v[0])
```

On my computer this yields:
```console
non-deterministic: 4940954880
deterministic, but wrong: 73896
```

I'm not sure what's going on, but this is possibly a miscompile.

**Comment by ematejska** [comment]
AI: Error out on this case.  This is related to lifetimes working.  @JoeLoser Will look at what the docs say here.

**Comment by lattner** [comment]
This is a basic dangling pointer bug in this code:

```
    fn map_result(inout self, seed: Slice) raises -> VariadicList[Slice]:
        let val = seed.start

        # removing this if fixes the bug
        if val < self[0].start:
            print("unreachable if in map result")
            return VariadicList[Slice](Slice(0, 0))
```

What is happening here is that we're forming a reference to the Slice(0,0) on the stack and VariadicList is referring to that, which is reading garbage memory.

As mentioned upthread, the right answer to this is the lifetimes feature that will directly catch this sort of thing - this is coming soon.  That said, VariadicList and VariadicListMem aren't intended for use by users and certainly not intended to be returned.  Please just "don't do this", and stay tuned for lifetimes that will correctly reject this.

**Comment by lattner** [comment]
The root issue here is that the !kgen.variadic is logically a pointer to the stack, so when a frame returns, the "array" dangles.

**Comment by ematejska** [comment]
This was closed as not planned.
