### ISSUE TITLE
[BUG]: Mojo would not install on Mac with M1

### ISSUE THREAD

**Issue by hroitblat** [modularml/mojo#1435]
### Bug description

Mojo would not install on Mac with M1.
If you need any other supported languages, run `brew install tesseract-lang`.
hroitblat~$modular install mojo
# Found release for https://packages.modular.com/mojo @ 0.6.0
# Installing to /Users/hroitblat/.modular/pkg/packages.modular.com_mojo
# Downloading artifacts. Please wait...
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
Collecting find_libpython==0.3.0
  Downloading find_libpython-0.3.0-py3-none-any.whl (8.5 kB)
Collecting jupyter_client>=8.3.0
  Downloading jupyter_client-8.6.0-py3-none-any.whl (105 kB)
     |████████████████████████████████| 105 kB 3.7 MB/s 
Collecting ipykernel>=6.25.0
  Downloading ipykernel-6.27.1-py3-none-any.whl (114 kB)
     |████████████████████████████████| 114 kB 21.4 MB/s 
Collecting jupyter-core!=5.0.*,>=4.12
  Downloading jupyter_core-5.5.0-py3-none-any.whl (28 kB)
Collecting importlib-metadata>=4.8.3
  Downloading importlib_metadata-7.0.0-py3-none-any.whl (23 kB)
Collecting pyzmq>=23.0
  Downloading pyzmq-25.1.2-cp39-cp39-macosx_10_15_universal2.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 19.0 MB/s 
Collecting python-dateutil>=2.8.2
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting traitlets>=5.3
  Downloading traitlets-5.14.0-py3-none-any.whl (85 kB)
     |████████████████████████████████| 85 kB 26.7 MB/s 
Collecting tornado>=6.2
  Downloading tornado-6.4-cp38-abi3-macosx_10_9_x86_64.whl (431 kB)
     |████████████████████████████████| 431 kB 48.1 MB/s 
Collecting debugpy>=1.6.5
  Downloading debugpy-1.8.0-py2.py3-none-any.whl (5.0 MB)
     |████████████████████████████████| 5.0 MB 56.5 MB/s 
Collecting appnope
  Downloading appnope-0.1.3-py2.py3-none-any.whl (4.4 kB)
Collecting packaging
  Using cached packaging-23.2-py3-none-any.whl (53 kB)
Collecting nest-asyncio
  Downloading nest_asyncio-1.5.8-py3-none-any.whl (5.3 kB)
Collecting comm>=0.1.1
  Downloading comm-0.2.0-py3-none-any.whl (7.0 kB)
Collecting ipython>=7.23.1
  Downloading ipython-8.18.1-py3-none-any.whl (808 kB)
     |████████████████████████████████| 808 kB 25.0 MB/s 
Collecting psutil
  Downloading psutil-5.9.6-cp36-abi3-macosx_10_9_x86_64.whl (246 kB)
     |████████████████████████████████| 246 kB 32.0 MB/s 
Collecting matplotlib-inline>=0.1
  Downloading matplotlib_inline-0.1.6-py3-none-any.whl (9.4 kB)
Collecting zipp>=0.5
  Using cached zipp-3.17.0-py3-none-any.whl (7.4 kB)
Collecting exceptiongroup
  Downloading exceptiongroup-1.2.0-py3-none-any.whl (16 kB)
Collecting pygments>=2.4.0
  Downloading pygments-2.17.2-py3-none-any.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 23.7 MB/s 
Collecting decorator
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting pexpect>4.3
  Downloading pexpect-4.9.0-py2.py3-none-any.whl (63 kB)
     |████████████████████████████████| 63 kB 14.0 MB/s 
Collecting typing-extensions
  Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Collecting stack-data
  Downloading stack_data-0.6.3-py3-none-any.whl (24 kB)
Collecting prompt-toolkit<3.1.0,>=3.0.41
  Downloading prompt_toolkit-3.0.41-py3-none-any.whl (385 kB)
     |████████████████████████████████| 385 kB 34.8 MB/s 
Collecting jedi>=0.16
  Downloading jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 66.9 MB/s 
Collecting parso<0.9.0,>=0.8.3
  Downloading parso-0.8.3-py2.py3-none-any.whl (100 kB)
     |████████████████████████████████| 100 kB 26.0 MB/s 
Collecting platformdirs>=2.5
  Downloading platformdirs-4.1.0-py3-none-any.whl (17 kB)
Collecting ptyprocess>=0.5
  Downloading ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting wcwidth
  Downloading wcwidth-0.2.12-py2.py3-none-any.whl (34 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting executing>=1.2.0
  Downloading executing-2.0.1-py2.py3-none-any.whl (24 kB)
Collecting asttokens>=2.1.0
  Downloading asttokens-2.4.1-py2.py3-none-any.whl (27 kB)
Collecting pure-eval
  Downloading pure_eval-0.2.2-py3-none-any.whl (11 kB)
Installing collected packages: six, zipp, wcwidth, traitlets, pure-eval, ptyprocess, platformdirs, parso, executing, asttokens, typing-extensions, tornado, stack-data, pyzmq, python-dateutil, pygments, prompt-toolkit, pexpect, matplotlib-inline, jupyter-core, jedi, importlib-metadata, exceptiongroup, decorator, psutil, packaging, nest-asyncio, jupyter-client, ipython, debugpy, comm, appnope, ipykernel, find-libpython
Successfully installed appnope-0.1.3 asttokens-2.4.1 comm-0.2.0 debugpy-1.8.0 decorator-5.1.1 exceptiongroup-1.2.0 executing-2.0.1 find-libpython-0.3.0 importlib-metadata-7.0.0 ipykernel-6.27.1 ipython-8.18.1 jedi-0.19.1 jupyter-client-8.6.0 jupyter-core-5.5.0 matplotlib-inline-0.1.6 nest-asyncio-1.5.8 packaging-23.2 parso-0.8.3 pexpect-4.9.0 platformdirs-4.1.0 prompt-toolkit-3.0.41 psutil-5.9.6 ptyprocess-0.7.0 pure-eval-0.2.2 pygments-2.17.2 python-dateutil-2.8.2 pyzmq-25.1.2 six-1.16.0 stack-data-0.6.3 tornado-6.4 traitlets-5.14.0 typing-extensions-4.8.0 wcwidth-0.2.12 zipp-3.17.0
WARNING: You are using pip version 21.2.3; however, version 23.3.1 is available.
You should consider upgrading via the '/Users/hroitblat/.modular/pkg/packages.modular.com_mojo/venv/bin/python -m pip install --upgrade pip' command.
[mojo] Testing: `mojo build test_mandelbrot.mojo` [FAIL]
[mojo] Testing: `mojo build test_python.mojo` [FAIL]
[mojo] Testing: `mojo test_python.mojo` [FAIL]
[mojo] Testing: `mojo repl` [FAIL]
[mojo] Some components may have been installed successfully, but others may not work as expected. Please submit an issue to https://github.com/modularml/mojo and include the full output of the command you just ran.
modular: error: failed to run python: 

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
hroitblat~$mojo -v
zsh: command not found: mojo
```

**Comment by felixnext** [comment]
This also seems to be same issue as #1378

**Comment by jackos** [comment]
Hi @hroitblat this has been resolved, please reopen if you're still experiencing the same issue.
