### ISSUE TITLE
mojo self tests failed

### ISSUE THREAD

**Issue by Nipesh25** [modularml/mojo#1441]
### Issue description

I have install homebrew, modular in my mac 11.5.2 then i try to install mojo then there is problem with installation that it says: 
dyld: Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /opt/homebrew/bin/modular (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib

zsh: abort      modular auth mut_8b5ede3fb27d41279c13bb531eea0f57

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.
For Mojo documentation, see https://docs.modular.com/mojo.
To chat on Discord, visit https://discord.gg/modular.
To report issues, go to https://github.com/modularml/mojo/issues.
dyld: Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /opt/homebrew/bin/modular (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib

zsh: abort      modular auth mut_8b5ede3fb27d41279c13bb531eea0f57

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
- What OS did you install modular CLI on ?
```

```[tasklist]
### Tasks
```

**Comment by smuniraj2018** [comment]
Please update your macOS version to the latest and try again

**Comment by Nipesh25** [comment]
i update the mac and try to install..modular has been installed but when i install mojo there is error like some packages are not install. The output is :  Found release for https://packages.modular.com/mojo @ 0.6.0
# Installing to /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo
# Downloading artifacts. Please wait...
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
Collecting find_libpython==0.3.0 (from -r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 1))
  Using cached find_libpython-0.3.0-py3-none-any.whl (8.5 kB)
Collecting jupyter_client>=8.3.0 (from -r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for jupyter_client>=8.3.0 from https://files.pythonhosted.org/packages/43/ae/5f4f72980765e2e5e02b260f9c53bcc706cefa7ac9c8d7240225c55788d4/jupyter_client-8.6.0-py3-none-any.whl.metadata
  Using cached jupyter_client-8.6.0-py3-none-any.whl.metadata (8.3 kB)
Collecting ipykernel>=6.25.0 (from -r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Obtaining dependency information for ipykernel>=6.25.0 from https://files.pythonhosted.org/packages/73/14/ec9a1c42d2c952c848a1ac366718783ab725148faf910bc086601809cefd/ipykernel-6.27.1-py3-none-any.whl.metadata
  Using cached ipykernel-6.27.1-py3-none-any.whl.metadata (6.3 kB)
Collecting jupyter-core!=5.0.*,>=4.12 (from jupyter_client>=8.3.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for jupyter-core!=5.0.*,>=4.12 from https://files.pythonhosted.org/packages/ab/ea/af6508f71d2bcbf4db538940120cc3d3f10287f62105e756bd315aa345b5/jupyter_core-5.5.0-py3-none-any.whl.metadata
  Using cached jupyter_core-5.5.0-py3-none-any.whl.metadata (3.4 kB)
Collecting python-dateutil>=2.8.2 (from jupyter_client>=8.3.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pyzmq>=23.0 (from jupyter_client>=8.3.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for pyzmq>=23.0 from https://files.pythonhosted.org/packages/6e/f0/d71cf69dc039c9adc8b625efc3bad3684f3660a570e47f0f0c64df787b41/pyzmq-25.1.2-cp312-cp312-macosx_10_15_universal2.whl.metadata
  Using cached pyzmq-25.1.2-cp312-cp312-macosx_10_15_universal2.whl.metadata (4.9 kB)
Collecting tornado>=6.2 (from jupyter_client>=8.3.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for tornado>=6.2 from https://files.pythonhosted.org/packages/4a/2e/3ba930e3af171847d610e07ae878e04fcb7e4d7822f1a2d29a27b128ea24/tornado-6.4-cp38-abi3-macosx_10_9_universal2.whl.metadata
  Using cached tornado-6.4-cp38-abi3-macosx_10_9_universal2.whl.metadata (2.5 kB)
Collecting traitlets>=5.3 (from jupyter_client>=8.3.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for traitlets>=5.3 from https://files.pythonhosted.org/packages/a7/1d/7d07e1b152b419a8a9c7f812eeefd408a0610d869489ee2e86973486713f/traitlets-5.14.0-py3-none-any.whl.metadata
  Using cached traitlets-5.14.0-py3-none-any.whl.metadata (10 kB)
Collecting appnope (from ipykernel>=6.25.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Using cached appnope-0.1.3-py2.py3-none-any.whl (4.4 kB)
Collecting comm>=0.1.1 (from ipykernel>=6.25.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Obtaining dependency information for comm>=0.1.1 from https://files.pythonhosted.org/packages/7b/a6/5fd0242e974914b139451eea0a61ed9fd2e47157e33a67939043c50a94dd/comm-0.2.0-py3-none-any.whl.metadata
  Using cached comm-0.2.0-py3-none-any.whl.metadata (3.7 kB)
Collecting debugpy>=1.6.5 (from ipykernel>=6.25.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Obtaining dependency information for debugpy>=1.6.5 from https://files.pythonhosted.org/packages/64/59/b9c5dbe60c3a3e4e4bb12b1968aa75e98b99ff8b65273a5e7de75cceef75/debugpy-1.8.0-py2.py3-none-any.whl.metadata
  Using cached debugpy-1.8.0-py2.py3-none-any.whl.metadata (1.1 kB)
Collecting ipython>=7.23.1 (from ipykernel>=6.25.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Obtaining dependency information for ipython>=7.23.1 from https://files.pythonhosted.org/packages/47/6b/d9fdcdef2eb6a23f391251fde8781c38d42acd82abe84d054cb74f7863b0/ipython-8.18.1-py3-none-any.whl.metadata
  Using cached ipython-8.18.1-py3-none-any.whl.metadata (6.0 kB)
Collecting matplotlib-inline>=0.1 (from ipykernel>=6.25.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Using cached matplotlib_inline-0.1.6-py3-none-any.whl (9.4 kB)
Collecting nest-asyncio (from ipykernel>=6.25.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Obtaining dependency information for nest-asyncio from https://files.pythonhosted.org/packages/ab/d3/48c01d1944e0ee49fdc005bf518a68b0582d3bd201e5401664890b62a647/nest_asyncio-1.5.8-py3-none-any.whl.metadata
  Using cached nest_asyncio-1.5.8-py3-none-any.whl.metadata (2.8 kB)
Collecting packaging (from ipykernel>=6.25.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Obtaining dependency information for packaging from https://files.pythonhosted.org/packages/ec/1a/610693ac4ee14fcdf2d9bf3c493370e4f2ef7ae2e19217d7a237ff42367d/packaging-23.2-py3-none-any.whl.metadata
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting psutil (from ipykernel>=6.25.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Obtaining dependency information for psutil from https://files.pythonhosted.org/packages/9e/cb/e4b83c27eea66bc255effc967053f6fce7c14906dd9b43a348ead9f0cfea/psutil-5.9.6-cp38-abi3-macosx_11_0_arm64.whl.metadata
  Using cached psutil-5.9.6-cp38-abi3-macosx_11_0_arm64.whl.metadata (21 kB)
Collecting decorator (from ipython>=7.23.1->ipykernel>=6.25.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting jedi>=0.16 (from ipython>=7.23.1->ipykernel>=6.25.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Obtaining dependency information for jedi>=0.16 from https://files.pythonhosted.org/packages/20/9f/bc63f0f0737ad7a60800bfd472a4836661adae21f9c2535f3957b1e54ceb/jedi-0.19.1-py2.py3-none-any.whl.metadata
  Using cached jedi-0.19.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting prompt-toolkit<3.1.0,>=3.0.41 (from ipython>=7.23.1->ipykernel>=6.25.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Obtaining dependency information for prompt-toolkit<3.1.0,>=3.0.41 from https://files.pythonhosted.org/packages/1f/9d/be9b01085bbd67a71c4b6aa02518fade8104e7a2224e5de5e947811d7176/prompt_toolkit-3.0.41-py3-none-any.whl.metadata
  Using cached prompt_toolkit-3.0.41-py3-none-any.whl.metadata (6.5 kB)
Collecting pygments>=2.4.0 (from ipython>=7.23.1->ipykernel>=6.25.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Obtaining dependency information for pygments>=2.4.0 from https://files.pythonhosted.org/packages/97/9c/372fef8377a6e340b1704768d20daaded98bf13282b5327beb2e2fe2c7ef/pygments-2.17.2-py3-none-any.whl.metadata
  Using cached pygments-2.17.2-py3-none-any.whl.metadata (2.6 kB)
Collecting stack-data (from ipython>=7.23.1->ipykernel>=6.25.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Obtaining dependency information for stack-data from https://files.pythonhosted.org/packages/f1/7b/ce1eafaf1a76852e2ec9b22edecf1daa58175c090266e9f6c64afcd81d91/stack_data-0.6.3-py3-none-any.whl.metadata
  Using cached stack_data-0.6.3-py3-none-any.whl.metadata (18 kB)
Collecting pexpect>4.3 (from ipython>=7.23.1->ipykernel>=6.25.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Obtaining dependency information for pexpect>4.3 from https://files.pythonhosted.org/packages/9e/c3/059298687310d527a58bb01f3b1965787ee3b40dce76752eda8b44e9a2c5/pexpect-4.9.0-py2.py3-none-any.whl.metadata
  Using cached pexpect-4.9.0-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting platformdirs>=2.5 (from jupyter-core!=5.0.*,>=4.12->jupyter_client>=8.3.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for platformdirs>=2.5 from https://files.pythonhosted.org/packages/be/53/42fe5eab4a09d251a76d0043e018172db324a23fcdac70f77a551c11f618/platformdirs-4.1.0-py3-none-any.whl.metadata
  Using cached platformdirs-4.1.0-py3-none-any.whl.metadata (11 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->jupyter_client>=8.3.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting parso<0.9.0,>=0.8.3 (from jedi>=0.16->ipython>=7.23.1->ipykernel>=6.25.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Using cached parso-0.8.3-py2.py3-none-any.whl (100 kB)
Collecting ptyprocess>=0.5 (from pexpect>4.3->ipython>=7.23.1->ipykernel>=6.25.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting wcwidth (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel>=6.25.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Obtaining dependency information for wcwidth from https://files.pythonhosted.org/packages/31/b1/a59de0ad3aabb17523a39804f4c6df3ae87ead053a4e25362ae03d73d03a/wcwidth-0.2.12-py2.py3-none-any.whl.metadata
  Using cached wcwidth-0.2.12-py2.py3-none-any.whl.metadata (14 kB)
Collecting executing>=1.2.0 (from stack-data->ipython>=7.23.1->ipykernel>=6.25.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Obtaining dependency information for executing>=1.2.0 from https://files.pythonhosted.org/packages/80/03/6ea8b1b2a5ab40a7a60dc464d3daa7aa546e0a74d74a9f8ff551ea7905db/executing-2.0.1-py2.py3-none-any.whl.metadata
  Using cached executing-2.0.1-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting asttokens>=2.1.0 (from stack-data->ipython>=7.23.1->ipykernel>=6.25.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Obtaining dependency information for asttokens>=2.1.0 from https://files.pythonhosted.org/packages/45/86/4736ac618d82a20d87d2f92ae19441ebc7ac9e7a581d7e58bbe79233b24a/asttokens-2.4.1-py2.py3-none-any.whl.metadata
  Using cached asttokens-2.4.1-py2.py3-none-any.whl.metadata (5.2 kB)
Collecting pure-eval (from stack-data->ipython>=7.23.1->ipykernel>=6.25.0->-r /Users/nipeshdulal/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3))
  Using cached pure_eval-0.2.2-py3-none-any.whl (11 kB)
Using cached jupyter_client-8.6.0-py3-none-any.whl (105 kB)
Using cached ipykernel-6.27.1-py3-none-any.whl (114 kB)
Using cached comm-0.2.0-py3-none-any.whl (7.0 kB)
Using cached debugpy-1.8.0-py2.py3-none-any.whl (5.0 MB)
Using cached ipython-8.18.1-py3-none-any.whl (808 kB)
Using cached jupyter_core-5.5.0-py3-none-any.whl (28 kB)
Using cached pyzmq-25.1.2-cp312-cp312-macosx_10_15_universal2.whl (1.9 MB)
Using cached tornado-6.4-cp38-abi3-macosx_10_9_universal2.whl (433 kB)
Using cached traitlets-5.14.0-py3-none-any.whl (85 kB)
Using cached nest_asyncio-1.5.8-py3-none-any.whl (5.3 kB)
Using cached packaging-23.2-py3-none-any.whl (53 kB)
Using cached psutil-5.9.6-cp38-abi3-macosx_11_0_arm64.whl (246 kB)
Using cached jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)
Using cached pexpect-4.9.0-py2.py3-none-any.whl (63 kB)
Using cached platformdirs-4.1.0-py3-none-any.whl (17 kB)
Using cached prompt_toolkit-3.0.41-py3-none-any.whl (385 kB)
Using cached pygments-2.17.2-py3-none-any.whl (1.2 MB)
Using cached stack_data-0.6.3-py3-none-any.whl (24 kB)
Using cached asttokens-2.4.1-py2.py3-none-any.whl (27 kB)
Using cached executing-2.0.1-py2.py3-none-any.whl (24 kB)
Using cached wcwidth-0.2.12-py2.py3-none-any.whl (34 kB)
Installing collected packages: wcwidth, pure-eval, ptyprocess, find_libpython, appnope, traitlets, tornado, six, pyzmq, pygments, psutil, prompt-toolkit, platformdirs, pexpect, parso, packaging, nest-asyncio, executing, decorator, debugpy, python-dateutil, matplotlib-inline, jupyter-core, jedi, comm, asttokens, stack-data, jupyter_client, ipython, ipykernel
Successfully installed appnope-0.1.3 asttokens-2.4.1 comm-0.2.0 debugpy-1.8.0 decorator-5.1.1 executing-2.0.1 find_libpython-0.3.0 ipykernel-6.27.1 ipython-8.18.1 jedi-0.19.1 jupyter-core-5.5.0 jupyter_client-8.6.0 matplotlib-inline-0.1.6 nest-asyncio-1.5.8 packaging-23.2 parso-0.8.3 pexpect-4.9.0 platformdirs-4.1.0 prompt-toolkit-3.0.41 psutil-5.9.6 ptyprocess-0.7.0 pure-eval-0.2.2 pygments-2.17.2 python-dateutil-2.8.2 pyzmq-25.1.2 six-1.16.0 stack-data-0.6.3 tornado-6.4 traitlets-5.14.0 wcwidth-0.2.12
WARNING: There was an error checking the latest version of pip.
[mojo] Testing: `mojo build test_mandelbrot.mojo` [FAIL]
[mojo] Testing: `mojo build test_python.mojo` [FAIL]
[mojo] Testing: `mojo repl` [FAIL]
[mojo] Some components may have been installed successfully, but others may not work as expected. Please submit an issue to https://github.com/modularml/mojo and i
/nclude the full output of the command you just ran.
Duplicate of #

**Comment by jackos** [comment]
Hi @Nipesh25 this issue should be resolved, please try again and reopen if it's still failing
