### ISSUE TITLE
[Typo] First sentence description in jupyter notebook

### ISSUE THREAD

**Issue by histonemark** [modularml/mojo#145]
"Mojo is designed as a superset of Python, so a lot of language features you are familiar with and the concepts that you know in Python translate **directory** to Mojo. For instance, a "Hello World" program in Mojo looks exactly as it does in Python:"

Change to directly.

**Comment by lattner** [comment]
@scottamain @ZolotukhinM

**Comment by scottamain** [comment]
Thanks. This has been fixed and will be included in the next website update.
