### ISSUE TITLE
[Feature Request] Allow downloading binaries directly via an endpoint

### ISSUE THREAD

**Issue by lsh** [modularml/mojo#1457]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

It would be beneficial for build pipelines if users could download the Mojo binary directly via an endpoint with, e.g., the auth being a query parameter in the URL.

### What is your motivation for this change?

In some build systems, such as Nix, trying to first install the `modular` cli and then the Mojo binary from there can be a little tricky to maintain. It would be nice to be able to get the binary directly if you're just writing a CI pipelines or the like.

**Comment by zbowling** [comment]
Thanks for the suggestion. Unfortunately this won't be possible given full roadmap of how all the products will interact across modular.
