### ISSUE TITLE
[BUG] + button located in top-left in https://playground.modular.com/  has no effect

### ISSUE THREAD

**Issue by mytechnotalent** [modularml/mojo#146]
## Bug Description
The + button located in top-left in https://playground.modular.com/  has no effect.  When pressing it it has no functionality.  As this was tested on Chrome in a Windows 11 env.

What is the current, unexpected behavior?
nothing

Please also include the expected behavior in your description.
A new notebook prompt or modal generates in the browser.

### Steps to Reproduce
Explain how to reproduce the issue in steps:
for example,
1. login to https://playground.modular.com
2. press blue + in upper left hand corner
3. observe nothing happens

**Comment by ahmadkammonah** [comment]
It opens a new launcher tab for me. I tested on Chrome in Ubuntu 22.04 (Jammy).

**Comment by Mogball** [comment]
Also works for me. @mytechnotalent please check again if it works for you. Might've been fixed in the newest release

**Comment by mytechnotalent** [comment]
works now thanks @Mogball
