### ISSUE TITLE
[Feature Request] support DTypePointer.simd_gather similar to existing DTypePointer.simd_load

### ISSUE THREAD

**Issue by HJLebbink** [modularml/mojo#1462]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Similar to `DTypePointer.simd_load[width: Int](self: Self, offset: Int) -> SIMD[type, width]`, provide support for masked gathers; eg:
`DTypePointer.simd_masked_gather[width: Int](self: Self, offsets: SIMD[DType.uint32, width], mask: SIMD[DType.bool, width]) -> SIMD[DType.uint32, width]`

### What is your motivation for this change?

I'm aware that this is not a trivial addition, but the [LLVM dialect](https://mlir.llvm.org/docs/Dialects/LLVM/#llvmintrmaskedgather-llvmmasked_gather) has the needed code to generate efficient instructions. 

Currently (Mojo v0.60), we need to trust the LLVM backend to optimize a loop with loads into a gather, E.g.: 

```mojo
fn gather[width: Int = 16](
    ptr: DTypePointer[DType.uint32],
    offset: SIMD[DType.uint32, width],
) -> SIMD[DType.uint32, width]:
    var result = SIMD[DType.uint32, width]()
    @unroll
    for i in range(width):
        result[i] = ptr.load(offset[i].to_int())
    return result
```

Will give us the following instructions (for a Sapphire Rapids) :
    
```
    # 37d9: 62 f2 7d 48 35 c1       vpmovzxdq zmm0,ymm1
    # 37df: 62 f3 fd 48 3b c9 01    vextracti64x4 ymm1,zmm1,0x1
    # 37e6: 62 f2 7d 48 35 c9       vpmovzxdq zmm1,ymm1
    # 37ec: c5 fc 46 c8             kxnorw k1,k0,k0
    # 37f0: c5 fc 46 d0             kxnorw k2,k0,k0
    # 37f4: c5 e9 ef d2             vpxor  xmm2,xmm2,xmm2
    # 37f8: 62 f2 7d 4a 91 14 8b    vpgatherqd ymm2{k2},DWORD PTR [rbx+zmm1*4]
    # 37ff: c5 f1 ef c9             vpxor  xmm1,xmm1,xmm1
    # 3803: 62 f2 7d 49 91 0c 83    vpgatherqd ymm1{k1},DWORD PTR [rbx+zmm0*4]
    # 380a: 62 f3 f5 48 3a c2 01    vinserti64x4 zmm0,zmm1,ymm2,0x1
```
We could argue about the efficiency of the above code; nevertheless, for a masked gather, no such reasonable code is generated.

```mojo
fn masked_gather[width: Int = 16](
    ptr: DTypePointer[DType.uint32],
    offset: SIMD[DType.uint32, width],
    mask: SIMD[DType.bool, width],
) -> SIMD[DType.uint32, width]:
    var result = SIMD[DType.uint32, width]()
    #unroll
    for i in range(width):
        result[i] = ptr.load(offset[i].to_int()) if mask[i] else 0
    return result
 ```
    
Thus, if the intention of the code (in Mojo) is to gather data, Mojo could best lower this into the gather instruction in MLIR (or the LLVM dialect)
    

### Any other details?

Once the source code of the Mojo compiler is available I would love to see if I can make a PR to add this.

**Comment by JoeLoser** [comment]
Thanks for the request.  I see the value-add and would definitely welcome a PR for this once we open source the standard library in Q1 2024 if we don't get to it before then.

**Comment by JoeLoser** [comment]
`DTypePointer` has gather and scatter methods now, so closing this issue.  If there's something else you'd like to see, feel free to comment back 😄
