### ISSUE TITLE
[BUG]: Could not debug code

### ISSUE THREAD

**Issue by AlaDeli7** [modularml/mojo#1466]
### Issue description

I tried to debug the following example provided by the Mojo documentaion, but i got this error:

`

Running initCommands:
(lldb) settings set target.show-hex-variable-values-with-leading-zeroes false
(lldb) plugin load '/home/deli/.modular/pkg/packages.modular.com_mojo/lib/libMojoLLDB.so.18git'
(lldb) command script import /home/deli/.modular/pkg/packages.modular.com_mojo/lib/lldb-visualizers/lldbDataFormatters.py
error: module importing failed: This script interpreter does not support importing modules.
(lldb) command script import /home/deli/.modular/pkg/packages.modular.com_mojo/lib/lldb-visualizers/mlirDataFormatters.py
error: module importing failed: This script interpreter does not support importing modules.
End!
`

### Steps to reproduce

- Add screenshots if possible, to help explain the problem.
vscode on winbdows 10 pro wsl 
mojo 0.6.0 (d55c0025)
modular 0.2.2 (95d42445)
`
trait DefaultConstructible:
    fn __init__(inout self): ...

trait Movable:
    fn __moveinit__(inout self, owned existing: Self): ...

trait MassProducible(DefaultConstructible, Movable):
    pass

fn factory[T: MassProducible]() -> T:
    return T()

struct Thing(MassProducible):
    var id: Int

    fn __init__(inout self):
        self.id = 0

    fn __moveinit__(inout self, owned existing: Self):
        self.id = existing.id

fn main():
   
    let thing = factory[Thing]()  # Break point goes here
    print("End!")
`
- Include anything that might help us debug the issue.
The break point is not activated and "End!" is printed at the console

**Comment by River707** [comment]
Thanks for the report! We haven't yet fully released the Mojo debugger, so some configurations aren't yet setup correctly (issue here is that we aren't shipping the debugger with scripting support, so some visualizers fail to load, FYI; @walter-erquinigo). Closing this for now, but the fully experience we'll be released somewhere in the next few releases!

**Comment by walter-erquinigo** [comment]
> issue here is that we aren't shipping the debugger with scripting support, so some visualizers fail to load

I'll removing these lines if lldb doesn't have scripting support.

**Comment by walter-erquinigo** [comment]
The next version of the SDK will only enable these visualizers if python scripting support is enabled. Eventually we'll ship LLDB with such support, but no timeline is defined yet.
