### ISSUE TITLE
[Modular CLI]: Could not install Mojo properly

### ISSUE THREAD

**Issue by drwho495** [modularml/mojo#1467]
### Issue description

I get this error when trying to install mojo on Ubuntu 20.04.6 LTS:

# Found release for https://packages.modular.com/mojo @ 0.6.0
# Installing to /root/.modular/pkg/packages.modular.com_mojo
# Downloading artifacts. Please wait...
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
Error: Command '['/root/.modular/pkg/packages.modular.com_mojo/venv/bin/python3', '-m', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
modular: error: failed to run python: 

### Steps to reproduce

Run curl https://get.modular.com | sh - && \\
modular auth <your id> && modular install mojo

### Version Info

```shell
modular 0.2.2 (95d42445)
Ubuntu 20.04.6 LTS
```

**Comment by smuniraj2018** [comment]
Are you running inside a docker container?
Can you send us more details on the python version that you have ?

**Comment by drwho495** [comment]
no i am not using a docker container

**Comment by jackos** [comment]
Hi @drwho495 the required package was added as a dependency, please reopen if you're still experiencing issues
