### ISSUE TITLE
[BUG]: [bikeshedding, very sorry] The keyword `alias` does not convey its meaning.

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [modularml/mojo#1468]
I usually don't like bikeshedding, I'm very sorry. But I do care about beginners because I'm often in a position where I have to teach stuff.

### What is surprising about `alias`?

Using the word `alias` to define a compile time constant is very surprising, because none of the meanings of the word `alias` has anything to do with a compilation step. At least from a Mojo user's perspective.

Let's try to read some code from the perspective of a (let's say Python, but it can be something else) programmer who has never read any Mojo code and didn't read the documentation yet:
```
alias x = 4
```
Alias in english means "a second name". Which implies that 4 had already a first name in the program. It's very confusing.

From [Wikipedia](https://en.wikipedia.org/wiki/Aliasing_(computing)):
> In computing, aliasing describes a situation in which a data location in memory can be accessed through different symbolic names in the program. Thus, modifying the data through one name implicitly modifies the values associated with all aliased names, which may not be expected by the programmer. As a result, aliasing makes it particularly difficult to understand, analyze and optimize programs. Aliasing analysers  intend to make and compute useful information for understanding aliasing in programs.

With this definition of alias in mind, a Mojo beginner might do:

```python
var x = 1
alias y = x  # I just want a second name for x without any runtime cost
```
Which is completely invalid Mojo code.

I'm not even sure why the keyword is named  `alias` in the first place because I can't find which of its english meaning is used (maybe let's add it to the docs? I don't think I'm the only one who doesn't know). I guess it's a second name because you can do `alias int8 = DType(2)` so it's a second name for DType(2), but It's a very little percentage of all alias usage. Most of them are for small constants or more complicated function calls `alias fixed_vector = compute_fibionaci_vector(20)`.

### How to improve it?

I propose that we change the `alias` keyword to something that really convey its meaning, being from the Mojo documentation:
>It is very common to want to name compile-time values. Whereas var defines a runtime value, and let defines a runtime constant, we need a way to define a compile-time temporary value. For this, Mojo uses an alias declaration.

So alias is the name of a compile time value. It makes sure the value is computed at compile time if it's the result of a fonction. That is a very simple concept for beginners to understand. As such I propose that the new name convey this notion by using "compilation" in the keyword. I propose possible keywords, but of course I would be satisfied with anything else as long as the compilation step is implied:

```python
compile x: Int = 4
compile int8 = DType(2)
compile fixed_vector = compute_fibionaci_vector(20)`
```
or 
```python
comptime x: Int = 4
comptime int8 = DType(2)
comptime fixed_vector = compute_fibionaci_vector(20)`
```
or 
```python
comp x: Int = 4
comp int8 = DType(2)
comp fixed_vector = compute_fibionaci_vector(20)`
```
It is more verbose than `alias` but `alias` is used way less often than `var` or `let` so I believe it's fine. It has a strong emphasis on compilation which I believe is much easier for beginners to understand, whatever situation the keyword is used for.

From a compiler perspective, maybe `alias` makes sense, but not really from a beginner perspective, where `compile time` is an easier notion to understand.

### A note about Zig:
Zig, known for its compile-time programming, uses `comptime`, which is much better to convey its meaning. Again, I'm not pushing for `comptime` specifically, I would just like a name that has something to do with compilation.

**Comment by gryznar** [comment]
+1 For me it also seems to be quite confusing, especially for newcomers.

**Comment by gryznar** [comment]
Maybe `compvar`? If only `var` will exist, then `compvar` will be comptime variable :)

**Comment by melodyogonna** [comment]
I've mentioned already in other places, alias should not be used for compile-time values, it's confusing. Also, Mojo can use Python's existing type alias syntax, with some extensions to better fit Mojo. 

I do not think it's necessary to indicate a value is compile-time value at the point where it's used, literals are already known at compile time, I don't think an extra identifier is necessary if Mojo knows the values are not changed at runtime. For more complex types it should be possible to define a value as a compile time value with a decorator:
```python
@comptime
fn compile_time_function() -> Int:
    return 10 * 10

fn main():
   var x = compile_time_function()
```

**Comment by gabrieldemarmiesse** [comment]
@melodyogonna I think that a keyword to mark compile time values is necessary to achieve Mojo's goals. The programmer must have full control over the compiler. And it's not because all inputs are known at compile time that it should be run at compile time. Here is an example:

```
from pathlib import Path
import json
def main():
     var some_json = json.loads(Path("./my_file.json").read_text())  # this filed is on the final user's machine
     alias some_json = json.loads(Path("./my_file.json").read_text())  # this file is present when compiling the program
```
Here both json.loads and read_text() can be used at compile time and runtime and they are both used for different things. So a decorator cannot be used to indicate what the programmer wants.

**Comment by melodyogonna** [comment]
@gabrieldemarmiesse This can be achieved by loading the file in a compile-time function. The point of this thread is that `alias` is a terrible label for the example you just showed because the name doesn't match the functionality.

**Comment by paper-sahil** [comment]
As a noob, alias makes sense to me, especially reading it backwards. The logic:

There is some constant (for example, `4`) and I'm alias-ing that to a name I want to use throughout the program.

**Comment by Ryul0rd** [comment]
To add another suggestion for a keyword, how about `aot` for "ahead of time"? Don't really have a strong opinion on this myself but thought I'd throw it out there.

**Comment by ParadaCarleton** [comment]
Related to #1255 in general. Mojo has a lot of difficult-to-understand keywords/names/syntax (and in some cases, even the semantics are unintuitive, e.g. Mojo is weakly typed unlike Python, as seen in #1310). Hopefully these can be cleaned up before launch.

**Comment by soraros** [comment]
I'd argue that syntax shouldn't be too surprise to new users, but being "immediately obvious" should be a non-goal, as it's not achievable because people have different background and perspectives. I don't think people can argue `def` is a good name for *only* functions declaration, for instance, but it's not too bad, and people live with it. In the case of Mojo, an `alias` is simply defined as "a compile time value". I would even say alien looking keywords are less noisy, and less misleading (because you have to look for the definition). `alias` and `var` differs in more than their phase distinction (which `comp` etc. indicates): `alias` don't have lifetime; they can be late bind; and from a semantic point of view, they really feel like "the other name" in the call-by-name sense.

**Comment by laszlokindrat** [comment]
Thank you for opening this ticket! We have discussed with the team the replacement of `alias` with some other keyword, but we were not convinced that any of the current suggestions (`compvar`, `aot`, etc.) would provide a meaningful improvement over `alias`. In particular, `compvar` doesn't seem much more meaningful on its own (`comp` could stand for many things, "compile time" is immediately implied). The semantics of `alias` are that of a "named parameter expression", and we cannot currently see a better name for this. For now, we would like to focus on defining and implementing a few major features for Mojo, and once those are in the language and fully baked, we will consider improving upon the `alias` keyword.

**Comment by bernaferrari** [comment]
Why not `const` or `static const`?

**Comment by mzaks** [comment]
It’s compile time evaluation of a value. How about:

ceval

It is short, novel and IMHO spells out nicely.
In my talk about Mojo alias keyword is the first thing I explain to the audience and it’s also one of the most confusing things, as people are familiar with type aliases, but in Mojo it goes beyond that. 
Hence I think a new keyword with a nice ring to it is actually helpful. When you look at the expression itself, it is easy to understand what’s going on, but the keyword alias is rather a mental stumbling block.

**Comment by gryznar** [comment]
> It’s compile time evaluation of a value. How about:
> 
> ceval
> 
> It is short, novel and IMHO spells out nicely.
> In my talk about Mojo alias keyword is the first thing I explain to the audience and it’s also one of the most confusing things, as people are familiar with type aliases, but in Mojo it goes beyond that. 
> Hence I think a new keyword with a nice ring to it is actually helpful. When you look at the expression itself, it is easy to understand what’s going on, but the keyword alias is rather a mental stumbling block.

Or `cevar` to connotate with `var`?

**Comment by marcom** [comment]
Maybe `@comptime` could replace `alias` and the `@parameter` `if` construct ?

**Comment by gryznar** [comment]
If parameters in Mojo are compile-time values, so why not to use related keyword? e.g. `param`

**Comment by LiamSwayne** [comment]
Perhaps `inline` could serve as a replacement for `alias`. The `@inline` decorator inlines a function, and an alias inlines an expression. Using `inline` instead of `alias` would make the syntax consistent for inlining functions and expressions.

**Comment by gryznar** [comment]
I like `inline`! It is much better suited than `comp*` and a lot more than `alias`. It could be also use for conditional if as a decorator, instead of `parameter`

**Comment by HelloWorld-n** [comment]
I think either `const` or `inline` would convey meaning better but `alias` doing good job as well.  
As for `compile`, `comptime`, `comp`, `aot`; honestly each of those seems more confusing than `alias`.

**Comment by gabrieldemarmiesse** [comment]
Closing as renaming things is not a priority right now. The focus is more on the language fundamentals.

**Comment by gabrieldemarmiesse** [comment]
For people following this thread, alias was renamed to comptime. See https://forum.modular.com/t/mojo-change-renaming-alias-to-comptime/2430/26
