### ISSUE TITLE
[Docs] rows and columns mixed up

### ISSUE THREAD

**Issue by jesper-olsen** [modularml/mojo#1471]
### Where is the problem?

[https://docs.modular.com/mojo/notebooks/Mandelbrot.html](https://docs.modular.com/mojo/notebooks/Mandelbrot.html)

### What can we do better?

This example only works because width and height are the same
alias width = 960
alias height = 960
if you change them to be different, e.g.
alias width = 1000
alias height = 750

you will have an indexing error

### Anything else?

*No response*

```[tasklist]
### Tasks
```

**Comment by jesper-olsen** [comment]
You can fix the index error by updating show_plot() like this:

```
    for row in range(height):
        for col in range(width):
            #numpy_array.itemset((col, row), tensor[col, row])
            numpy_array.itemset((row,col), tensor[row,col])
```

**Comment by jesper-olsen** [comment]
Also see
https://github.com/modularml/mojo/issues/1545

**Comment by jackos** [comment]
Thanks @jesper-olsen resolved
