### ISSUE TITLE
[Modular CLI]: Illegal instruction

### ISSUE THREAD

**Issue by ErrorLoadingUsername** [modularml/mojo#1480]
### Issue description

root@localhost:~# modular install mojo                       
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.      Program arguments: modular install mojo                   
 #0 0x0000003000514dac (/usr/bin/modular+0x514dac)
 #1 0x0000003000512c7c (/usr/bin/modular+0x512c7c)
 #2 0x000000300051552c (/usr/bin/modular+0x51552c)
 #3 0x0000007ae06d27f0 (linux-vdso.so.1+0x7f0)
 #4 0x00000030013261b0 (/usr/bin/modular+0x13261b0)
 #5 0x00000030004db3e8 (/usr/bin/modular+0x4db3e8)
 #6 0x00000030004da994 (/usr/bin/modular+0x4da994)
 #7 0x0000007ae01673fc (/lib/aarch64-linux-gnu/libc.so.6+0x273fc)
 #8 0x0000007ae01674cc __libc_start_main (/lib/aarch64-linux-gnu/libc.so.6+0x274cc)
 #9 0x00000030004d9d74 (/usr/bin/modular+0x4d9d74)
Illegal instruction

### Steps to reproduce

Modular install mojo
 

### Version Info

```shell
modular 0.2.2 (95d42445)

Ubuntu 22.04 on termux
```

**Comment by Sharktheone** [comment]
might be related to #583 Can you maybe run `lscpu`?
