### ISSUE TITLE
[Docs] Misspelling on the Modules and Packages page

### ISSUE THREAD

**Issue by atholcomb** [modularml/mojo#1483]
### Where is the problem?

https://docs.modular.com/mojo/manual/packages.html

### What can we do better?

There is a type-o on the first line of the Modules and Packages page. See italicized word below.
Mojo provides a packaging system that allows you to organize and compile code libraries into _importables_ files.

**Comment by atholcomb** [comment]
@scottamain Is this closed because it's been fixed and will be updated in the next release?

**Comment by scottamain** [comment]
Yep, thanks for reporting it!

**Comment by atholcomb** [comment]
You're welcome! Thanks @scottamain!
