### ISSUE TITLE
Failing Target Hardware acquisition for WSL2 [Modular CLI]: 

### ISSUE THREAD

**Issue by crnex** [modularml/mojo#1485]
### Issue description

modular: error: no packages found for the current target hardware - please run `modular host-info` and file a ticket at https://github.com/modularml/mojo with your hardware information

 modular host-info
  Host Information
  ================

  Target Triple: x86_64-unknown-linux
  CPU: znver3
  CPU Features: adx, aes, avx, avx2, bmi, bmi2, clflushopt, clwb, clzero, crc32, cx16, cx8, f16c, fma, fsgsbase, fxsr, invpcid, lzcnt, mmx, movbe, mwaitx, pclmul, pku, popcnt, prfchw, rdpid, rdpru, rdrnd, rdseed, sahf, sha, sse, sse2, sse3, sse4.1, sse4.2, sse4a, ssse3, vaes, vpclmulqdq, wbnoinvd, x87, xsave, xsavec, xsaveopt, xsaves

### Steps to reproduce

- WSL2 - Debian / Ubuntu 22.04.2 LTS
- modular mojo install

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.3.0 (8afa5600)

- What OS did you install modular CLI on ?

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
Secondary WSL tested with 
Description:    Ubuntu 22.04.2 LTS

**Comment by crnex** [comment]
temporary fix via modular=0.2.2

**Comment by Sharktheone** [comment]
See #1492 for updates

**Comment by zbowling** [comment]
I just pushed a new patch release for the modular CLI (version 0.3.1) that should hopefully resolve this issue on AMD CPUs.

If you have already installed the modular CLI from the [modular.com](http://modular.com/) site you can update modular on Ubuntu with:
```
> apt-get update && apt-get upgrade modular
```

After that you can test you have the latest version of modular with:
```
> modular --version
modular 0.3.1 (589ce200)
```

Both `modular install mojo` and `modular upgrade mojo` commands should work. 

Let me know if you run into any more trouble on #1492!
