### ISSUE TITLE
[Modular CLI]: mojo won't install on WSL

### ISSUE THREAD

**Issue by taweili** [modularml/mojo#1486]
### Issue description

david@MORTAR-WIN10:~$ modular -v
modular 0.3.0 (8afa5600)
david@MORTAR-WIN10:~$ modular install mojo
modular: error: no packages found for the current target hardware - please run `modular host-info` and file a ticket at https://github.com/modularml/mojo with your hardware information
david@MORTAR-WIN10:~$ modular host-info
  Host Information
  ================

  Target Triple: x86_64-unknown-linux
  CPU: znver3
  CPU Features: adx, aes, avx, avx2, bmi, bmi2, clflushopt, clwb, clzero, crc32, cx16, cx8, f16c, fma, fsgsbase, fxsr, invpcid, lzcnt, mmx, movbe, mwaitx, pclmul, pku, popcnt, prfchw, rdpid, rdpru, rdrnd, rdseed, sahf, sha, sse, sse2, sse3, sse4.1, sse4.2, sse4a, ssse3, vaes, vpclmulqdq, wbnoinvd, x87, xsave, xsavec, xsaveopt, xsaves

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
- What OS did you install modular CLI on ?
david@MORTAR-WIN10:~$ modular -v
modular 0.3.0 (8afa5600)
david@MORTAR-WIN10:~$ modular install mojo
modular: error: no packages found for the current target hardware - please run `modular host-info` and file a ticket at https://github.com/modularml/mojo with your hardware information
david@MORTAR-WIN10:~$ modular host-info
  Host Information
  ================

  Target Triple: x86_64-unknown-linux
  CPU: znver3
  CPU Features: adx, aes, avx, avx2, bmi, bmi2, clflushopt, clwb, clzero, crc32, cx16, cx8, f16c, fma, fsgsbase, fxsr, invpcid, lzcnt, mmx, movbe, mwaitx, pclmul, pku, popcnt, prfchw, rdpid, rdpru, rdrnd, rdseed, sahf, sha, sse, sse2, sse3, sse4.1, sse4.2, sse4a, ssse3, vaes, vpclmulqdq, wbnoinvd, x87, xsave, xsavec, xsaveopt, xsaves
```

**Comment by zbowling** [comment]
Ther is a new modular CLI (version 0.3.1) release that should hopefully resolve this issue on AMD CPUs.

If you have already installed the modular CLI from the [modular.com](http://modular.com/) site you can update modular on Ubuntu with:
```
> apt-get update && apt-get upgrade modular
```

After that you can test you have the latest version of modular with:
```
> modular --version
modular 0.3.1 (589ce200)
```

Both `modular install mojo` and `modular upgrade mojo` commands should work. 

Let me know if you run into any more trouble on #1492!

**Comment by taweili** [comment]
Thanks. It now install perfectly on WSL on AMD.
