### ISSUE TITLE
[Modular CLI]: install error - no packages found for current hardware (ubuntu, znver1 arch)

### ISSUE THREAD

**Issue by marcom** [modularml/mojo#1487]
### Issue description

Installing mojo on Ubuntu 22.04 on CPU arch `znver1` now fails.

Previously, I was using `mojo-0.6.0` on this machine without any problems (compilation etc all working).

After updating `modular`, running `modular clean && modular install mojo` now fails and I cannot use mojo anymore.

### Steps to reproduce

After running

```
sudo apt update
sudo apt upgrade modular
modular clean
modular install mojo
```

The install command `modular install mojo` fails with:

```
modular: error: no packages found for the current target hardware - please run `modular host-info` and file a ticket at https://github.com/modularml/mojo with your hardware information
```

Running the `modular auth [...]` command as found here https://developer.modular.com/download before installation didn't change anything.

The output of `modular host-info`:
```
  Host Information
  ================

  Target Triple: x86_64-unknown-linux
  CPU: znver1
  CPU Features: adx, aes, avx, avx2, bmi, bmi2, clflushopt, clzero, crc32, cx16, cx8, f16c, fma, fsgsbase, fxsr, lzcnt, mmx, movbe, mwaitx, pclmul, popcnt, prfchw, rdrnd, rdseed, sahf, sha, sse, sse2, sse3, sse4.1, sse4.2, sse4a, ssse3, x87, xsave, xsavec, xsaveopt, xsaves
```

### Version Info

```shell
`modular --version`:

modular 0.3.0 (8afa5600)
```

`cat /etc/os-release | grep PRETTY_NAME`
```
PRETTY_NAME="Ubuntu 22.04.3 LTS"
```
```

**Comment by zbowling** [comment]
Are you by chance using WSL on Windows? Or is this a native Linux install?

**Comment by zbowling** [comment]
Same as #1492. We are having an issue specific to AMD CPUs. For now you can rollback to the modular 0.2.2 CLI and see if that resolves your issue with:
`sudo apt-get install modular=0.2.2`

**Comment by marcom** [comment]
This is a native Linux install, that's why I opened a new issue.

Modular 0.2.2 works as it was before.

Why 'not planned'?

**Comment by zbowling** [comment]
> Why 'not planned'?

Sorry that is just the status GH uses for duplicates too. 

I just pushed a new patch release for the modular CLI (version 0.3.1) that should hopefully resolve this issue on AMD CPUs.

If you have already installed the modular CLI from the [modular.com](http://modular.com/) site you can update modular on Ubuntu with:
```
> apt-get update && apt-get upgrade modular
```

After that you can test you have the latest version of modular with:
```
> modular --version
modular 0.3.1 (589ce200)
```

Both `modular install mojo` and `modular upgrade mojo` commands should work. 

Let me know if you run into any more trouble on #1492!

**Comment by marcom** [comment]
Thanks for the explanation and the quick fix.

Everything works again with modular 0.3.1.
