### ISSUE TITLE
[Modular CLI]: Unable to install Mojo in Ubuntu WSL for AMD Ryzen znver2

### ISSUE THREAD

**Issue by faustinoaq** [modularml/mojo#1492]
### Issue description

```
user@DESKTOP-UTSVN6V:~$ modular host-info
  Host Information
  ================

  Target Triple: x86_64-unknown-linux
  CPU: znver2
  CPU Features: adx, aes, avx, avx2, bmi, bmi2, clflushopt, clwb, clzero, crc32, cx16, cx8, f16c, fma, fsgsbase, fxsr, lzcnt, mmx, movbe, mwaitx, pclmul, popcnt, prfchw, rdpid, rdpru, rdrnd, rdseed, sahf, sha, sse, sse2, sse3, sse4.1, sse4.2, sse4a, ssse3, wbnoinvd, x87, xsave, xsavec, xsaveopt, xsaves
user@DESKTOP-UTSVN6V:~$ modular install mojo
modular: error: no packages found for the current target hardware - please run `modular host-info` and file a ticket at https://github.com/modularml/mojo with your hardware information
```

### Steps to reproduce

- modular install mojo
- get  error: no packages found for the current target hardware - please run `modular host-info` and file a ticket at https://github.com/modularml/mojo with your hardware information
- My CPU AMD Ryzen 5 3600 already includes SSE4.2 support please see https://www.techpowerup.com/cpu-specs/ryzen-5-3600.c2132

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`: modular 0.3.0 (8afa5600)
- What OS did you install modular CLI on ?: Ubuntu WSL in Windows 11


user@DESKTOP-UTSVN6V:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```
```

**Comment by zbowling** [comment]
Can you check which version of WSL you are using? We only support WSL2. 

https://learn.microsoft.com/en-us/windows/wsl/install#check-which-version-of-wsl-you-are-running

**Comment by faustinoaq** [comment]
@zbowling I'm already using WSL2

```
PS C:\Users\user> wsl -l -v
  NAME      STATE           VERSION
* Ubuntu    Running         2
PS C:\Users\user> wsl --version
WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.2861
```

**Comment by rezanour** [comment]
I am seeing the same issue on an AMD Ryzen Threadripper 3970X:

$ modular install mojo
modular: error: no packages found for the current target hardware - please run `modular host-info` and file a ticket at https://github.com/modularml/mojo with your hardware information

$ modular host-info
  Host Information
  ================

  Target Triple: x86_64-unknown-linux
  CPU: znver2
  CPU Features: adx, aes, avx, avx2, bmi, bmi2, clflushopt, clwb, clzero, crc32, cx16, cx8, f16c, fma, fsgsbase, fxsr, lzcnt, mmx, movbe, mwaitx, pclmul, popcnt, prfchw, rdpid, rdpru, rdrnd, rdseed, sahf, sha, sse, sse2, sse3, sse4.1, sse4.2, sse4a, ssse3, wbnoinvd, x87, xsave, xsavec, xsaveopt, xsaves
  
  PS > wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu-22.04           Running         2

**Comment by zbowling** [comment]
Thanks for that. Investigating if this is an AMD specific issue or an AMD + WSL2 issue. 

For now you can rollback to the modular 0.2.2 CLI and see if that resolves your issue with:
`sudo apt-get install modular=0.2.2`

**Comment by guidorice** [comment]
+1 here, I have a Github Action which shows this regression bug with installing on ubuntu-latest x86. here is the workflow recipe if that's helpful:
https://github.com/guidorice/geo-features/blob/9c25f0880fdc80d112e7f0d7a8cb8f5b50cf5167/.github/workflows/tests.yaml

**Comment by zbowling** [comment]
I just pushed a new patch release for the modular CLI (version 0.3.1) that should hopefully resolve this issue AMD CPUs.

If you have already installed the modular CLI from the [modular.com](http://modular.com/) site you can update modular on Ubuntu with:
```
> apt-get update && apt-get upgrade modular
```

After that you can test you have the latest version of modular with:
```
> modular --version
modular 0.3.1 (589ce200)
```

Let me know if this works!

**Comment by faustinoaq** [comment]
Thank u @zbowling it is working like a charm!!!

```
user@DESKTOP-UTSVN6V:~$ modular --version
modular 0.3.1 (589ce200)
user@DESKTOP-UTSVN6V:~$ mojo --version
mojo 0.6.0 (d55c0025)
```

You can close the issue now ✨

**Comment by zbowling** [comment]
Fantastic!

**Comment by hhstore** [comment]
# unable to install Mojo in Ubuntu 22.04


- CPU: `AMD R7 5800U`
- PVE



```ruby

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy


 $ modular -v
modular 0.3.1 (589ce200)


$ modular host-info
  Host Information
  ================

  Target Triple: x86_64-unknown-linux
  CPU: k8-sse3
  CPU Features: 3dnow, 3dnowa, cx8, fxsr, mmx, sse, sse2, sse3, x87



```

**Comment by zbowling** [comment]
@hhstore You running under QEMU, not with WSL2 or another supported hypervisor. That QEMU emulates an ancient Athlon64 CPU from 15-20 years ago.

**Comment by rezanour** [comment]
Thanks, I'll give it a try tomorrow!


-------- Original message --------
From: Zac Bowling ***@***.***>
Date: 12/16/23 3:26 PM (GMT-08:00)
To: modularml/mojo ***@***.***>
Cc: Reza Nourai ***@***.***>, Comment ***@***.***>
Subject: Re: [modularml/mojo] [Modular CLI]: Unable to install Mojo in Ubuntu WSL for AMD Ryzen znver2 (Issue #1492)


@hhstore<https://github.com/hhstore> You running under QEMU, not with WSL2 or another supported hypervisor. That QEMU emulates an ancient Athlon64 CPU from 15-20 years ago.

**Comment by rezanour** [comment]
Works great, thanks for the fast turnaround!
________________________________
From: Reza Nourai ***@***.***>
Sent: Saturday, December 16, 2023 7:08 PM
To: modularml/mojo ***@***.***>; modularml/mojo ***@***.***>
Cc: Comment ***@***.***>
Subject: RE: [modularml/mojo] [Modular CLI]: Unable to install Mojo in Ubuntu WSL for AMD Ryzen znver2 (Issue #1492)

Thanks, I'll give it a try tomorrow!


-------- Original message --------
From: Zac Bowling ***@***.***>
Date: 12/16/23 3:26 PM (GMT-08:00)
To: modularml/mojo ***@***.***>
Cc: Reza Nourai ***@***.***>, Comment ***@***.***>
Subject: Re: [modularml/mojo] [Modular CLI]: Unable to install Mojo in Ubuntu WSL for AMD Ryzen znver2 (Issue #1492)


@hhstore<https://github.com/hhstore> You running under QEMU, not with WSL2 or another supported hypervisor. That QEMU emulates an ancient Athlon64 CPU from 15-20 years ago.

**Comment by hhstore** [comment]
> @hhstore You are running Debian under QEMU, not with WSL2 or another supported hypervisor. That QEMU based KVM emulates an ancient Athlon64 CPU from 15-20 years ago. There are certain CPU features needed by more modern processors to run mojo that are not reported in that VM.

- Thanks for the explanation. 
- Then I'd better use a physical machine to install Mojo. 😄

**Comment by spaceyjx** [comment]
root@DESKTOP-GTB1ENA:/usr/local/cmake-3.28.1# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
root@DESKTOP-GTB1ENA:/usr/local/cmake-3.28.1# modular host-info
modular: error: failed to create target info: unknown target triple 'generic-unknown-linux'
root@DESKTOP-GTB1ENA:/usr/local/cmake-3.28.1#


cpu instrucitions MMX(+),SSE,SSE2,SSE4A,x86_64   ,no have SSE4.2  ,  Is it possible to install mojo

**Comment by spaceyjx** [comment]
"modular: error: failed to create target info: unknown target triple 'generic-unknown-linux'"
How to deal with this

**Comment by freeclb** [comment]
> "modular: error: failed to create target info: unknown target triple 'generic-unknown-linux'" How to deal with this

did you fix it? The same problem to me.

**Comment by freeclb** [comment]
> "modular: error: failed to create target info: unknown target triple 'generic-unknown-linux'" How to deal with this

@spaceyjx  did you fix it? The same problem to me.
