### ISSUE TITLE
[Modular CLI]: Failed to install mojo on AMD znver3 ubuntu

### ISSUE THREAD

**Issue by PumeTu** [modularml/mojo#1494]
### Issue description

Failed to install mojo on ubuntu 22.04 on znver3

```
  Host Information
  ================

  Target Triple: x86_64-unknown-linux
  CPU: znver3
  CPU Features: adx, aes, avx, avx2, bmi, bmi2, clflushopt, clwb, clzero, crc32, cx16, cx8, f16c, fma, fsgsbase, fxsr, invpcid, lzcnt, mmx, movbe, mwaitx, pclmul, pku, popcnt, prfchw, rdpid, rdpru, rdrnd, rdseed, sahf, sha, sse, sse2, sse3, sse4.1, sse4.2, sse4a, ssse3, vaes, vpclmulqdq, wbnoinvd, x87, xsave, xsavec, xsaveopt, xsaves
 ```

### Steps to reproduce

`modular install mojo`
error : `modular: error: no packages found for the current target hardware - please run modular host-info and file a ticket at https://github.com/modularml/mojo with your hardware information`
`modular host-info`
output:
 ```
  Host Information
  ================

  Target Triple: x86_64-unknown-linux
  CPU: znver3
  CPU Features: adx, aes, avx, avx2, bmi, bmi2, clflushopt, clwb, clzero, crc32, cx16, cx8, f16c, fma, fsgsbase, fxsr, invpcid, lzcnt, mmx, movbe, mwaitx, pclmul, pku, popcnt, prfchw, rdpid, rdpru, rdrnd, rdseed, sahf, sha, sse, sse2, sse3, sse4.1, sse4.2, sse4a, ssse3, vaes, vpclmulqdq, wbnoinvd, x87, xsave, xsavec, xsaveopt, xsaves
 ``` 

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`: modular 0.3.0 (8afa5600)
- What OS did you install modular CLI on ?: Ubuntu Desktop 22.04


OS: Ubuntu 22.04.3 LTS x86_64
Kernel: 6.2.0-39-generic
```
```

**Comment by zbowling** [comment]
Same as #1492 

We are having an issue specific to AMD CPUs. For now you can rollback to the modular 0.2.2 CLI and see if that resolves your issue with:
sudo apt-get install modular=0.2.2

**Comment by zbowling** [comment]
I just pushed a new patch release for the modular CLI (version 0.3.1) that should hopefully resolve this issue on AMD CPUs.

If you have already installed the modular CLI from the [modular.com](http://modular.com/) site you can update modular on Ubuntu with:
```
> apt-get update && apt-get upgrade modular
```

After that you can test you have the latest version of modular with:
```
> modular --version
modular 0.3.1 (589ce200)
```

Both `modular install mojo` and `modular upgrade mojo` commands should work. 

Let me know if you run into any more trouble on #1492!
