### ISSUE TITLE
[BUG]: Type inference does not propagate in dependent type

### ISSUE THREAD

**Issue by YichengDWu** [modularml/mojo#1496]
### Bug description

It is natural to generalize the following definition
```python
@value
struct S[V: Int]:
    fn test(self) -> String:
        return String(V)
```
to 
```python
@value
struct S2[T: Stringable, V: T]:
    fn test(self) -> String:
        return String(V)  # Error: cannot construct 'String' from 'T' value in return value
```
But `test` cannot be defined since the compiler doesn't know `T` is a `Stringable`. This should be a bug in the traits system.

### Steps to reproduce

See above.

### System information

```shell
- What OS did you do install Mojo on ?

ethan@LAPTOP-PHBTR3GS:~$ mojo -v
mojo 0.6.0 (d55c0025)
ethan@LAPTOP-PHBTR3GS:~$ modular -v
modular 0.2.2 (95d42445)
```

**Comment by Mogball** [comment]
@JoeLoser does `String` not have a constructor from `Stringable`? Will this trigger the recursive resolution error?

**Comment by JoeLoser** [comment]
This got fixed right after v0.6.1 was cut in https://github.com/modularml/modular/commit/0301fd342d03a6d65e694080e61d1a15ebf1a2a8 specifically.  I just tried with top-of-tree and the original code compiles fine.  That commit mentioned added a constructor to the `String` type which accepts any argument that conforms to the `Stringable` trait.

**Comment by YichengDWu** [comment]
我不认为问题得到了解决，即类型推断不会传播，请看下面代码：
```python
@value
struct S3[T: Intable, V: T]:
    fn test(self) -> Stringable:
        return String(V)  #error: Expression [6]:4:22: cannot construct 'String' from 'T' value in return value
    return String(V)
```

Since `T<Intable<Stringable`, the compiler should know that it is valid to call `String` on `T`.

**Comment by soraros** [comment]
@YichengDWu That's not how the trait system works. In particular, this is not true: `T < Intable < Stringable`.

**Comment by YichengDWu** [comment]
@soraros You are correct, I did not consider the issue of multiple inheritance.
