### ISSUE TITLE
[Typo] Matrix multiplication in Mojo notebook typo

### ISSUE THREAD

**Issue by elinx** [modularml/mojo#150]
[Searching for the tile_factor](https://docs.modular.com/mojo/notebooks/Matmul.html#searching-for-the-tile_factor), should delete the first `write`:
> We want ~write~ to write portable code without having to know everything about the hardware, so we can ask Mojo to automatically select the best tile factor using autotuning.

**Comment by lattner** [comment]
@scottamain @ZolotukhinM
