### ISSUE TITLE
[BUG]: No compiler error after using  the ^ transfer operator 

### ISSUE THREAD

**Issue by AlaDeli7** [modularml/mojo#1500]
### Bug description

I tried this example from the mojo [documentaion](https://docs.modular.com/mojo/manual/values/ownership.html#:~:text=However%2C%20if%20you%20add%20the%20%5E%20transfer%20operator%20when%20calling%20take_text()%2C%20the%20compiler%20complains%20about%20print(message)%2C%20because%20at%20that%20point%2C%20the%20message%20variable%20is%20no%20longer%20initialized.%20That%20is%2C%20this%20version%20does%20not%20compile%3A)

Expected result : ERROR: The `message` variable is uninitialized
Actual Result : Compilation passes with a warning

> warning: transfer from a trivial register value has no effect and can be removed
>     take_text(message^)  
>                      ^
>                      
> Hello!
> Hello

### Steps to reproduce

```
fn take_text(owned text: String):
    text += "!"
    print(text)

fn my_function():
    let message = "Hello"
    take_text(message^)  
    print(message)

fn main():
    my_function()
```

### System information

```shell
- What OS did you do install Mojo on ?
wsl on windows 10 pro
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.6.0 (d55c0025)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.2.2 (95d42445)
```

**Comment by scottamain** [comment]
Thanks for the report. This is discussed further here: https://github.com/modularml/mojo/issues/1407

**Comment by AlaDeli7** [comment]
string literal will be autopromoted to String
I guess  the ^ transfer operator works only for the struct String and not string literal
