### ISSUE TITLE
[BUG]: mojo installs its own special lldb with the same name as the ordinary lldb. Confusing.

### ISSUE THREAD

**Issue by jbulow** [modularml/mojo#1503]
### Bug description

 mojo installs its own special lldb with the same name as the ordinary lldb. Confusing when you try to use lldb and you get mojo's version of lldb.

### Steps to reproduce

Install mojo

### System information

```shell
- What OS did you do install Mojo on ?
ubuntu 22.04
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.6.0 (d55c0025)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.3.1 (589ce200)
```

**Comment by River707** [comment]
@walter-erquinigo We've talked about this before, can you take a look at this?

**Comment by walter-erquinigo** [comment]
Sure, I can handle this.

**Comment by walter-erquinigo** [comment]
This will be fixed in the next SDK release.

**Comment by jbulow** [comment]
Still broken in 0.7.0 release.

**Comment by walter-erquinigo** [comment]
@jbulow , I've just confirmed on my end that the 0.7 SDK doesn't contain the any binaries with the plain name `lldb`. Could you double check what's the real path of the `lldb` you have in your PATH? I'm afraid that, maybe, the `lldb` binary from the previous SDK still appears in your PATH.

**Comment by jbulow** [comment]
It still installs liblldb with the same name as lldb built from source:
```
find ~/.modular -name liblldb.so.18.0.0git  -ls
 20513628 126676 -rwxr-xr-x   1 jonasbu  jonasbu  129709848 Jan 26 17:29 /home/jonasbu/.modular/pkg/packages.modular.com_mojo/lib/liblldb.so.18.0.0git```

lldb build from source and installed in `/big/local`

```
find /big/local -name liblldb.so.18.0.0git -ls
 15863138 127620 -rw-r--r--   1 jonasbu  jonasbu  130677088 Jan 19 11:04 /big/local/lib/liblldb.so.18.0.0git
```

If I dont clear LD_LIBARY_PATH before starting mojo it will fail to start.

It seems mojo dynamically load liblldb when starting and does not refer to it from its own install directory.

**Comment by walter-erquinigo** [comment]
What you mention is very unexpected.
Could you run the following command and share the output?
```
readelf -d /path/to/modular/mojo-lldb
```

I want to make sure that we have set the rpath correctly for the mojo-lldb being distributed. Btw, do you have a preset value for LD_LIBARY_PATH?

**Comment by jbulow** [comment]
The output of readelf is:

```
readelf -d ~/.modular/pkg/packages.modular.com_mojo/bin/mojo-lldb

Dynamic section at offset 0x6cd08 contains 37 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [liblldb.so.18git]
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libtinfo.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../lib:/__w/modular/modular/.derived/third-party/llvm-project/build-release/lib:]
 0x000000000000000c (INIT)               0xd000
 0x000000000000000d (FINI)               0x48f34
 0x0000000000000019 (INIT_ARRAY)         0x69db0
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x69db8
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x340
 0x0000000000000005 (STRTAB)             0x1990
 0x0000000000000006 (SYMTAB)             0x388
 0x000000000000000a (STRSZ)              6643 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000015 (DEBUG)              0x0
 0x0000000000000003 (PLTGOT)             0x6e000
 0x0000000000000002 (PLTRELSZ)           4992 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0xad48
 0x0000000000000007 (RELA)               0x3740
 0x0000000000000008 (RELASZ)             30216 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffb (FLAGS_1)            Flags: PIE
 0x000000006ffffffe (VERNEED)            0x3560
 0x000000006fffffff (VERNEEDNUM)         9
 0x000000006ffffff0 (VERSYM)             0x3384
 0x000000006ffffff9 (RELACOUNT)          1229
 0x0000000000000000 (NULL)               0x0
```

My LD_LIBRARY_PATH includes the lib install path for my local llvm project build `/big/local/lib`.

**Comment by walter-erquinigo** [comment]
> My LD_LIBRARY_PATH includes the lib install path for my local llvm project build.

I'm pretty sure this is the actual issue. It seems that mojo-lldb picks your build of liblldb because LD_LIBRARY_PATH supersedes any other search path. If you see the RUNPATH of mojo-lldb, it is doing what it should do.

My only recommendation is to restrict that LD_LIBRARY_PATH to only when you invoke your own LLDB (via a wrapper script maybe?) or to try not to use it at all.

**Comment by jbulow** [comment]
Wouldn't it make sense that mojo documented this behavior of having conflicting libraries in its installation instructions? I.e add a note about prepend LD_LIBRARY_PATH with the .modular lib path?

Using RPATH instead of RUNPATH will also solve the problem: (LD_LIBRARY_PATH overrides RUNPATH but not RPATH)

patchelf --force-rpath --set-rpath ~/.modular/pkg/packages.modular.com_mojo/lib ~/.modular/pkg/packages.modular.com_mojo/bin/mojo-lldb

**Comment by walter-erquinigo** [comment]
I'll make sure to add a mention to this in the debugger documentation.
