### ISSUE TITLE
[Feature Request] please support a `__debugbreak` intrinsic

### ISSUE THREAD

**Issue by HJLebbink** [modularml/mojo#1516]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Please support a method to put a explicit debug break (byte CC on x86) into the compiled code.

### What is your motivation for this change?

Even if all libraries are bug free, and all features are meticulously documented, there will always be some need to inspect code and step through instructions.

 

### Any other details?

If there is no official support for such a feature, please share, (possibly in secret), how you guys/gals have been debugging compiled mojo code the past year.

**Comment by Mogball** [comment]
print debugging

In all seriousness, a fully featured Mojo debugger was demo'd at Modcon on Dec 4, and it's officially on the roadmap for one of the next releases!

**Comment by HJLebbink** [comment]
Hi @Mogball,

Im not requesting this as an alternative for print debugging.

Im aware of the nice debugger integration with IDEs (I assume you mean that), but I need to inspect optimized code, eg. to debug when a `vzeroupper` is issued before a [RDTSC](https://github.com/HJLebbink/asm-dude/wiki/RDTSC), in the below code sniped after the call. This for example makes timing code very difficult. The people at Modular must have been using a mechanism to inject such debug bytes.

```asm
    3b77:	c5 f8 77             	vzeroupper 
    3b7a:	41 ff 14 04          	call   QWORD PTR [r12+rax*1]
 ```

**Comment by HJLebbink** [comment]
This may be very foreign for some people. Assume you don't have an IceLake but you like to convince your collegues that Mojo compiles to mature and good code. You ssh into an IceLake at AWS and you do the following experiments:

And you want to know the difference between: Code A:
```python
let a = gen_random_SIMD[DType.uint32, 16]()
var b: UInt32 = 0
let start_time_ms = now()
b = a.reduce_add()
let elapsed_time_ms = now() - start_time_ms
keep(b)
```
and Code B:
```python
let a = gen_random_SIMD[DType.uint32, 16]()
var b: UInt32 = 0
let start_time_ms = now()
b = a.reduce_add()
keep(b)
let elapsed_time_ms = now() - start_time_ms
```

I explicitly do not use the `time_function` because then I cannot control the placement of the `keep`. (It generates the same assembly as Code B)
```python
@parameter
fn runner():
    b = a.reduce_add()
    keep(b)
let elapsed_time_ms = time_function[runner]()
```


The `reduce_add` generates a well known sequence of instructions that some people like to talk about at the coffee machine. When you don't know where in the code this sequence will be, you need to set a breakpoint (in the source code). Setting such a breakpoint also allows you to identify where your code snippet starts and ends. If you do not have a GUI on your machine that can be somewhat annoying if there is no intrinsic to do the same thing manually.

If I could have placed an __debugbreak() before and after the `keep` : I might have found out more easily what the keep contributed.

Code B:
```asm
vzeroupper
call   0x555555557230 <clock_gettime@plt>
; next the reduce_add
vmovdqu64 zmm1,ZMMWORD PTR [rsp+0x30]
vextracti64x4 ymm0,zmm1,0x1
vpaddd ymm0,ymm1,ymm0
vextracti128 xmm1,ymm0,0x1
vpaddd xmm0,xmm0,xmm1
vpshufd xmm1,xmm0,0xee
vpaddd xmm0,xmm0,xmm1
vpshufd xmm1,xmm0,0x55
vpaddd xmm0,xmm0,xmm1

vmovd  eax,xmm0 ; dead: I assume part of the keep		

vmovd  DWORD PTR [rsp+0x4],xmm0 ; save reduce_add result on the stack
vmovaps xmm0,XMMWORD PTR [rsp+0x10] ; load stuff from the previous clock_gettime
vmovaps XMMWORD PTR [rsp+0x30],xmm0 ; save stuff from the previous clock_gettime
lea    rcx,[rsp+0x4] ; retrieve reduce_add result from the stack
mov    QWORD PTR [rsp+0x8],rcx ; save result again back to another place on the stack

vxorps xmm0,xmm0,xmm0   
vmovaps XMMWORD PTR [rsp+0x20],xmm0  ; cleaning the for the next clock_time

lea    rsi,[rsp+0x20]
mov    edi,0x1
vzeroupper
call   0x555555557230 <clock_gettime@plt>
```

**Conclusion**, a lot of redundancy inside the runner function. Something you should absolutely know when timing stuff. To find all this I had to dig through a lot of code, which would have been much simpler with an int3.

Side note: Code A gives a lot better picture, but still not ideal. 

```asm
vzeroupper
call   0x555555557230 <clock_gettime@plt>

vmovdqu64 zmm1,ZMMWORD PTR [rsp+0x40]
vextracti64x4 ymm0,zmm1,0x1
vpaddd ymm0,ymm1,ymm0
vextracti128 xmm1,ymm0,0x1
vpaddd xmm0,xmm0,xmm1
vpshufd xmm1,xmm0,0xee
vpaddd xmm0,xmm0,xmm1
vpshufd xmm1,xmm0,0x55
vpaddd xmm0,xmm0,xmm1

vmovdqa XMMWORD PTR [rsp+0x40],xmm0
vmovd  ebx,xmm0
vpxor  xmm0,xmm0,xmm0
vmovdqa XMMWORD PTR [rsp+0x20],xmm0
vmovaps xmm0,XMMWORD PTR [rsp+0x10]
vmovaps XMMWORD PTR [rsp+0x30],xmm0
		
lea    rsi,[rsp+0x20]
mov    edi,0x1
vzeroupper
call   0x555555557230 <clock_gettime@plt>

**Comment by River707** [comment]
Thanks for this request! We're going to be pushing a lot on the debuggability of mojo soon, and this is something on the radar. (FYI: @walter-erquinigo we've talked about this before as well).

**Comment by walter-erquinigo** [comment]
Thanks for the suggestion! I'll make sure this is added relatively soon.

**Comment by walter-erquinigo** [comment]
The next version of the SDK will have the method `debug.trap()` that implements what you request.
Cheers
