### ISSUE TITLE
[Feature Request] [mojo-stdlib] Reorder type arguments in `StaticTuple`

### ISSUE THREAD

**Issue by JoeLoser** [modularml/mojo#1521]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

For consistency with other vocabulary types in the library, `StaticTuple[size, type]` should be `StaticTuple[type, size]` to match that of `SIMD`, `InlineFixedVector`, and friends.  Suggested from https://github.com/modularml/mojo/issues/899#issue-1909380029.

### What is your motivation for this change?

Consistency

**Comment by bgreni** [comment]
I went to do this and I see it was already done in e02bd47 so this issue should be closed?

**Comment by JoeLoser** [comment]
> I went to do this and I see it was already done in [e02bd47](https://github.com/modularml/mojo/commit/e02bd476221fa721dc08cf9df820914d23dde95a) so this issue should be closed?

Yes, thank you for flagging this. Someone internally did this recently a few weeks ago and didn't know there was a public GitHub issue for this it looks like. I just closed this issue.
