### ISSUE TITLE
[BUG]: Installing mojo facing exception in CLI (modular install mojo)

### ISSUE THREAD

**Issue by NarasimmanSaravana1994** [modularml/mojo#1525]
### Bug description

# Found release for https://packages.modular.com/mojo @ 0.6.1
# Installing to /home/narasimman/.modular/pkg/packages.modular.com_mojo
# Downloading artifacts. Please wait...
modular: error: failure detected - please run `modular clean` and try again
==========================
Failure Information:
        - Creating symlink for /home/narasimman/.modular/pkg/packages.modular.com_mojo/lib/liblldb.so -> /home/narasimman/.modular/pkg/packages.modular.com_mojo/lib/liblldb.so.18.0.0git failed: File exists
        - Creating symlink for /home/narasimman/.modular/pkg/packages.modular.com_mojo/lib/libMojoJupyter.so -> /home/narasimman/.modular/pkg/packages.modular.com_mojo/lib/libMojoJupyter.so.18git failed: File exists
        - Creating symlink for /home/narasimman/.modular/pkg/packages.modular.com_mojo/lib/liblldb.so.18git -> /home/narasimman/.modular/pkg/packages.modular.com_mojo/lib/liblldb.so.18.0.0git failed: File exists
        - Creating symlink for /home/narasimman/.modular/pkg/packages.modular.com_mojo/lib/libKGENCompilerRTShared.so -> /home/narasimman/.modular/pkg/packages.modular.com_mojo/lib/libKGENCompilerRTShared.so.18git failed: File exists
        - Creating symlink for /home/narasimman/.modular/pkg/packages.modular.com_mojo/lib/libMojoLLDB.so -> /home/narasimman/.modular/pkg/packages.modular.com_mojo/lib/libMojoLLDB.so.18git failed: File exists
        - Creating symlink for /home/narasimman/.modular/pkg/packages.modular.com_mojo/lib/libLLCLRuntimeGlobals.so -> /home/narasimman/.modular/pkg/packages.modular.com_mojo/lib/libLLCLRuntimeGlobals.so.18git failed: File exists
        - Creating symlink for /home/narasimman/.modular/pkg/packages.modular.com_mojo/lib/libMSupportGlobals.so -> /home/narasimman/.modular/pkg/packages.modular.com_mojo/lib/libMSupportGlobals.so.18git failed: File exists
==========================

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by gryznar** [comment]
As errors points out, please execute:
`modular clean` 
and try again

**Comment by smuniraj2018** [comment]
Looks like some files existed from previous installation. Did `modular clean` and trying again help?

**Comment by jackos** [comment]
`modular clean` should resolve this issue, please reopen if you still have issues
