### ISSUE TITLE
[Feature Request] Add comparison operators to CollectionElement, or create ComparableCollectionElement

### ISSUE THREAD

**Issue by Benny-Nottonson** [modularml/mojo#1526]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

The trait CollectionElement should be modified to support __eq__, __ne__, __lt__, and __gt__, etc, in order to enhance the potentially functionality of extended data structures. Alternatively, a new trait: ComparableCollectionElement should be added, specifically in a way that it can interface with DynamicVector[ComparableCollectionElement], in order to allow further extendability.

### What is your motivation for this change?

For enhanced data structures, such as a BinaryHeap, it is necessary to use some form of resizing backing array (Most chose to go with DynamicVector in mojo) in order to store data. Unfortunately, a BinaryHeap requires comparison of data in order to determine how to form and shape the heap, making this currently impossible in Mojo without hacky code or strange syntax.

**Comment by rparolin** [comment]
ComparableCollectionElement has already been added to the stdlib. The implementation can be found in `builtin/value.mojo`.  Hope this helps.
