### ISSUE TITLE
[Feature Request] Optional Types in Structs

### ISSUE THREAD

**Issue by Benny-Nottonson** [modularml/mojo#1527]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Allow for optional / nullable types in Structs and type hints, this is useful for something like LinkedLists, where Nodes can either point to another Node, or a Null object / space. Pointers can do this currently with get_null, but there are cases where a Pointer is not the correct type.

### What is your motivation for this change?

This would help implement data structures like LinkedList, Graph, etc. where objects have attributes that can be None or some value.

**Comment by rarebreed** [comment]
They should be planning for this already once they get Abstract Data Types working.  

https://docs.modular.com/mojo/roadmap.html#small-independent-features

What I am curious about, is how they will design out the std lib.  Will they go for an exception approach (I hope not), or Option/Maybe, and Result/Either types?

**Comment by Benny-Nottonson** [comment]
It might not be the best approach but since the raises keyword is required for fn functions, the return type potentially being an error object could be implied with this

**Comment by soraros** [comment]
I `raises` are already implemented as results.

**Comment by JoeLoser** [comment]
We already have a `Optional` type - see the [docs](https://docs.modular.com/mojo/stdlib/collections/optional.html).  You can use these as data members in a struct.
