### ISSUE TITLE
[BUG] Time.now() returns incorrect result

### ISSUE THREAD

**Issue by czheo** [modularml/mojo#153]
## Bug Description
The result of `Time.now()` (wrong) is way off from `os.system("date +%s")` (correct).

```python
from Time import now
print(now())

from PythonInterface import Python
os = Python.import_module("os")
os.system("date +%s")
```

### Steps to Reproduce
![image](https://github.com/modularml/mojo/assets/1692400/281b97d0-a44e-411a-82cf-9761df3c2cd0)

### Context

11:devices:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podae678bb1_6c52_4b1d_8328_97f035fe9952.slice/cri-containerd-4d2fe0bbffbef2a0eae4c852da290d07ff6f42db06efde0a6972690a940d5e09.scope
10:perf_event:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podae678bb1_6c52_4b1d_8328_97f035fe9952.slice/cri-containerd-4d2fe0bbffbef2a0eae4c852da290d07ff6f42db06efde0a6972690a940d5e09.scope
9:cpuset:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podae678bb1_6c52_4b1d_8328_97f035fe9952.slice/cri-containerd-4d2fe0bbffbef2a0eae4c852da290d07ff6f42db06efde0a6972690a940d5e09.scope
8:freezer:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podae678bb1_6c52_4b1d_8328_97f035fe9952.slice/cri-containerd-4d2fe0bbffbef2a0eae4c852da290d07ff6f42db06efde0a6972690a940d5e09.scope
7:net_cls,net_prio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podae678bb1_6c52_4b1d_8328_97f035fe9952.slice/cri-containerd-4d2fe0bbffbef2a0eae4c852da290d07ff6f42db06efde0a6972690a940d5e09.scope
6:pids:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podae678bb1_6c52_4b1d_8328_97f035fe9952.slice/cri-containerd-4d2fe0bbffbef2a0eae4c852da290d07ff6f42db06efde0a6972690a940d5e09.scope
5:hugetlb:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podae678bb1_6c52_4b1d_8328_97f035fe9952.slice/cri-containerd-4d2fe0bbffbef2a0eae4c852da290d07ff6f42db06efde0a6972690a940d5e09.scope
4:cpu,cpuacct:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podae678bb1_6c52_4b1d_8328_97f035fe9952.slice/cri-containerd-4d2fe0bbffbef2a0eae4c852da290d07ff6f42db06efde0a6972690a940d5e09.scope
3:blkio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podae678bb1_6c52_4b1d_8328_97f035fe9952.slice/cri-containerd-4d2fe0bbffbef2a0eae4c852da290d07ff6f42db06efde0a6972690a940d5e09.scope
2:memory:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podae678bb1_6c52_4b1d_8328_97f035fe9952.slice/cri-containerd-4d2fe0bbffbef2a0eae4c852da290d07ff6f42db06efde0a6972690a940d5e09.scope
1:name=systemd:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podae678bb1_6c52_4b1d_8328_97f035fe9952.slice/cri-containerd-4d2fe0bbffbef2a0eae4c852da290d07ff6f42db06efde0a6972690a940d5e09.scope
0::/

**Comment by jayant-01** [comment]
@czheo 

The first code i.e

 from Time import now
print(now())

will  give an error in python , but in case of mojo it prints certain value 
so as per @sa- it can be correct that it prints in monotonic nanoseconds

but the python code

import time
print(time.monotonic_ns())

doesnot give the same output as that in now().  

where as the second code 

"from PythonInterface import Python
os = Python.import_module("os")
os.system("date +%s")"

this  prints the number of seconds since Jan 1 1970

**Comment by Mogball** [comment]
We can change the implementation of `Time.now`, but it also seems like we can document the differences and expected behaviour of the function @abduld

**Comment by jayant-01** [comment]
@Mogball    how can we change the implementation of time.now()
