### ISSUE TITLE
[Feature Request] StopIteration, Enhanced Errors

### ISSUE THREAD

**Issue by Benny-Nottonson** [modularml/mojo#1533]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Add a new builtin for StopIteration, as well as other needed builtin Error types, such as IndexError, TypeError, etc. Currently the best way to extend errors is alias IndexError = Error("Index Error"), but this is ambiguous and feels less than ideal. Furthermore, to implement __iter__ methods, StopIteration is normally used, yet does not exist yet in mojo.

### What is your motivation for this change?

For __iter__ methods, and other related iteration methods, having StopIteration makes the code much more readable and reusable to code, rather than having to chain try statements to determine when an iterator has reached an end.

**Comment by JoeLoser** [comment]
Let's decouple the ideas of named/distinct error types (such as `TypeError`) from how we want to approach iterators.  It's very likely we will drift from Python here in iterator design and instead go for `Optional[T]` return type approach instead of raising `StopIteration` error for example.
