### ISSUE TITLE
[BUG]: `print(len("🔥"))` gives 4 in Mojo and 1 in Python 

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [modularml/mojo#1539]
### Bug description

As the title says, it seems that `String.__len__()` gives the number of bytes and not the number of characters. In Python it gives the number of characters

### Steps to reproduce

`print(len("🔥"))`

### System information

```shell
Ubuntu 22.04
modular 0.2.1 (5144fffe)
mojo 0.6.1 (876ded2e)
```

**Comment by lattner** [comment]
Definitely a bug.  We need to build out unicode support in string, and move to support characters as grapheme clusters.

**Comment by JoeLoser** [comment]
Thanks for filing this issue. Support for unicode as a top-level issue can be found https://github.com/modularml/mojo/issues/1616. We're not actively working on this, but it's something we'll want to do in the future for sure.

**Comment by JoeLoser** [comment]
> Should we close this issue in favor of #1616 ?

Yep, thanks for flagging it.  It helps me keep track of everything both internally and externally.  Supporting non-ASCII things isn't on our Q1 roadmap, but it's definitely known that we want to support this in the future.
