### ISSUE TITLE
[BUG]: @unroll does not accept alias as unroll factor

### ISSUE THREAD

**Issue by mikowals** [modularml/mojo#1542]
### Bug description

From the documentation:

> The loop’s lower bound, upper bound, and induction step size are compile-time constants (they do not vary at runtime).

So a compile time constant defined with alias should work as the unroll factor passed to `@unroll`.

### Steps to reproduce

Place the following code in a file called `unroll.mojo`:

```
alias count = 5


fn main():
    @unroll(count)
    for i in range(count):
        print(i)
```

Running `mojo unroll.mojo` will produce the error:
```
error: unsupported decorator on 'for' statement
    @unroll(count)
     ~~~~~~^~~~~~~
mojo: error: failed to parse the provided Mojo
```

writing `@unroll(5)` works so it is something about getting the compile time constant from the `alias` causing the problem.

### System information

```shell
- What OS did you do install Mojo on ?  
MacOS 14.0 (23A344)
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.6.1 (876ded2e)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.3.1 (589ce200)
```

**Comment by Mogball** [comment]
cc @weiweichen I believe we should support this?

**Comment by weiweichen** [comment]
> cc @weiweichen I believe we should support this?

Not yet, but yes, we should!
