### ISSUE TITLE
[Feature Request] Support String.toupper and .tolower for non ASCII chars which have upper lower cases

### ISSUE THREAD

**Issue by mzaks** [modularml/mojo#1543]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Current implementation of toupper and tolower methods on String support only ASCII characters. In order to have parity with Python str the methods should work for all characters which have upper/lower case semantics

### What is your motivation for this change?

Support for non ASCII string characters which have upper lower case semantics

**Comment by mzaks** [comment]
Example:
```
print(String("hello 🔥 однажды, Küste").toupper()) # HELLO 🔥 однажды, KüSTE
```

Compared to Python:
```
"hello 🔥 однажды, Küste".upper() # 'HELLO 🔥 ОДНАЖДЫ, KÜSTE'
```

**Comment by gryznar** [comment]
`lower()` and `upper()` at least do not have 2 mangled words together without any separator

**Comment by JoeLoser** [comment]
Thanks for filing this issue.  Support for unicode as a top-level issue can be found [here](https://github.com/modularml/mojo/issues/1616).  We're not actively working on this, but it's something we'll want to do in the future for sure.

The docs for `String` should be clear we only support ASCII right now, but please do file an issue if you have clear points which can be improved to avoid confusion.

**Comment by mzaks** [comment]
This PR https://github.com/modularml/mojo/pull/3496 will resolve this issue.
