### ISSUE TITLE
[BUG]: matplotlib does not work in example notebooks on VS Code (e.g. Mandelbrot.ipynb)

### ISSUE THREAD

**Issue by billbliss** [modularml/mojo#1547]
### Bug description

All of the notebook examples work fine except for the ones that use matplotlib. Upon first starting VS Code and opening the Mandelbrot.ipynb notebook (i.e., first run), all the cells up until the one starting with `def show_plot()` work just fine. When trying to run that cell, this is the error output:
```
error: [0;1;31m[1mExpression [4]:1:30: [0m[1muse of unknown declaration 'float_type'
[0mdef show_plot(tensor: Tensor[float_type]):
[0;1;32m                             ^~~~~~~~~~
[0m[0m
error: [0;1;31m[1mExpression [4]:11:29: [0m[1munexpected token in expression
[0m    for row in range(height):
[0;1;32m                            ^
[0m[0m
error: [0;1;31m[1mExpression [4]:11:29: [0m[1mstatements must start at the beginning of a line
[0m    for row in range(height):
[0;1;32m                            ^
[0m[0m
error: [0;1;31m[1mExpression [4]:2:19: [0m[1mcould not find builtin 'IntLiteral' type
[0m    alias scale = 10
[0;1;32m                  ^
[0m[0m
error: [0;1;31m[1mExpression [4]:3:17: [0m[1mcould not find builtin 'IntLiteral' type
[0m    alias dpi = 64
[0;1;32m                ^
[0m[0m
expression failed to parse (no further compiler diagnostics)
```

It doesn't matter how many times I re-run that cell, that same error occurs. _If_, however, I re-run all the cells above that one, then a different error message appears:

`Error: partially initialized module 'matplotlib.pyplot' has no attribute 'figure' (most likely due to a circular import)`

I can't get that to go away and see the Mandelbrot plot no matter how many times I re-run that cell or the ones above it.

I can't see how this could be a circular import problem; it's behaving like a race condition or async/await type issue, but what do I know...

I did verify that matplotlib functions on my machine by using it on more of a matplotlib "hello world" type example: https://github.com/derekbanas/matplotlib. 

### Steps to reproduce

1. Open Mandelbrot.ipynb notebook in VS Code.
2. Go to the `def show_plot()` cell.
3. Execute all the cells above that cell. (I used the "Execute Above Cells" command.)
4. Run the cell.
5. A bunch of errors will appear (see bug description).
6. Re-execute all the cells above the cell as described above.
7. Re-run the cell. 
8. This error message appears: `Error: partially initialized module 'matplotlib.pyplot' has no attribute 'figure' (most likely due to a circular import)`

Expect: a Mandelbrot chart to appear. 

### System information

```shell
- What OS did you do install Mojo on ?

Mac OS Sonoma 14.1.2 MacBook Pro M2 Max
Python 3.11.7
VS Code

- Provide version information for Mojo by pasting the output of `mojo -v`

mojo 0.6.1 (876ded2e)

- Provide Modular CLI version by pasting the output of `modular -v`

modular 0.3.1 (589ce200)
```

**Comment by ematejska** [comment]
Reproduces for me as well.

**Comment by jackos** [comment]
I can't reproduce in current build, if this is still a problem for you @billbliss or @ematejska please reopen.
