### ISSUE TITLE
[BUG]: A local `StringLiteral` and a global `StringLiteral` are recognized to be the same

### ISSUE THREAD

**Issue by isuckatcs** [modularml/mojo#1555]
### Bug description

Mojo confuses a global `StringLiteral` with a local one and gives a redefenition error. I guess, in any case, implicit(?) `StringLiteral`s should never be the same, and for me this error message does not make sense.

```python
let foo: String = "global"


fn main():
    print("local ", "dummy, to trigger error")
```

```
error: redeclaration of parameter "`anonymous*0"
    print("local ", "dummy, to trigger error")
          ^
note: previous declaration here
let foo: String = "global"
                  ^
```

### Steps to reproduce

- run the snippet in the description with mojo

### System information

```shell
- Ubuntu 22.04.3 LTS (WSL 2)
- mojo 0.6.1 (876ded2e)
- modular 0.3.1 (589ce200)
```

**Comment by ematejska** [comment]
Global variables are still not fully supported. Starting to collate the dups here: https://github.com/modularml/mojo/issues/1573. Sorry for the reverse dup.
