### ISSUE TITLE
[BUG]: Variable is still accessible when lifetime ends in Mojo Jupyter notebook

### ISSUE THREAD

**Issue by omarelb** [modularml/mojo#1563]
### Bug description

When Following [the documentation](https://docs.modular.com/mojo/manual/lifecycle/life.html#consuming-move-constructor) for `__moveinit__` in a Mojo notebook, it seems that a variable whose lifetime is ended is still accessible, while it shouldn't be.

### Steps to reproduce

Here's the specific code snippet:
```mojo
struct HeapArray:
    var data: Pointer[Int]
    var size: Int

    fn __init__(inout self, size: Int, val: Int):
        self.size = size
        self.data = Pointer[Int].alloc(self.size)
        for i in range(self.size):
            self.data.store(i, val)

    fn __copyinit__(inout self, existing: Self):
        print("copy")
        # Deep-copy the existing value
        self.size = existing.size
        self.data = Pointer[Int].alloc(self.size)
        for i in range(self.size):
            self.data.store(i, existing.data.load(i))

    fn __moveinit__(inout self, owned existing: Self):
        print("move")
        # Shallow copy the existing value
        self.size = existing.size
        self.data = existing.data
        # Then the lifetime of `existing` ends here, but
        # Mojo does NOT call its destructor

    fn __del__(owned self):
        self.data.free()

    fn dump(self):
        print_no_newline("[")
        for i in range(self.size):
            if i > 0:
                print_no_newline(", ")
            print_no_newline(self.data.load(i))
        print("]")


let ha1 = HeapArray(3, 1)
let ha2 = ha1^
# At this point, `ha1` shouldn't be accessible anymore, but this prints "[1, 1, 1]"
ha1.dump()
```

When the code above is run in the notebook, `[1, 1, 1]` is printed. When the code is run in a normal `mojo` file, the code doesn't compile.

### System information

```shell
- What OS did you do install Mojo on: MacBook Pro M2 -- Ventura 13.0
- Provide version information for Mojo by pasting the output of `mojo -v`:
mojo 0.6.1 (876ded2e)
- Provide Modular CLI version by pasting the output of `modular -v`:
modular 0.3.1 (589ce200)
```

**Comment by ematejska** [comment]
The build error has to do with global variables so it's probably covering up the lifetime issue when compiling as well.
```
error: TODO: expressions are not yet supported at the file scope level
ha1.dump()
```

**Comment by River707** [comment]
Thanks for the report! The variables at the top-scope of a notebook or REPL expression are treated a bit specially right now, and don't fall nicely into the lifetime support that is being built out. It's a bit of a known issue (and not a nice one), but one we likely won't fix in the short term (as we build out lifetimes, proper support for top-level code, global variables, etc.).
