### ISSUE TITLE
[Docs]: Implicitly declared local variables (in `def` functions) may not be function-scoped

### ISSUE THREAD

**Issue by duckki** [modularml/mojo#1574]
### Bug description

Implicitly declared local variables are supposed to have the function-level scope (as stated in [the doc](https://docs.modular.com/mojo/manual/variables.html)). But, it appears to be restricted to the scope they were assigned.

### Steps to reproduce

```python
def example( nondet ):
    # Exepcted that `v` is declared function-wide.
    # Thus, the implicit declaration of `var v` should've been hoisted to the top of the function.
    if nondet:
        v = 1 # assignment here, implicitly declaring a local variable `v`
    else:
        v = 2
    print( v ) # error: "use of unknown declaration 'v'"
```

### System information

```shell
- macOS Sonoma
- mojo 0.6.1 (876ded2e)
- modular 0.3.0 (8afa5600)
```

**Comment by duckki** [comment]
It seems related to [the intentional scoping deviation from Python mentioned in the roadmap](https://docs.modular.com/mojo/roadmap.html#scoping-and-mutability-of-statement-variables).

**Comment by ematejska** [comment]
Yes, exactly but the documentation could be improved here.
