### ISSUE TITLE
[Docs] Decorator of `@export` is missing in the doc

### ISSUE THREAD

**Issue by felixf4xu** [modularml/mojo#1588]
### Where is the problem?

https://docs.modular.com/mojo/manual/decorators/

### What can we do better?

`@export` is mentioned in the change log https://docs.modular.com/mojo/changelog.html (2023-07-20), but I can't find the document under the `Mojo decorators` chapter https://docs.modular.com/mojo/manual/decorators/

**Comment by arthurevans** [comment]
We don't intend to document this decorator, which is not really designed for public use. We hope to add something more usable.
