### ISSUE TITLE
[BUG]: Cannot install modular on Apple Silicon - Getting error that Intel is not supported

### ISSUE THREAD

**Issue by naveensoman** [modularml/mojo#1592]
### Bug description

Getting the below error on my M1 Macbook Air.

curl https://get.modular.com | sh - && \
modular auth mut_token
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3885  100  3885    0     0  15369      0 --:--:-- --:--:-- --:--:-- 15602
Sorry, modular is not currently supported on Intel based Macs. Please visit https://www.modular.com/mojo to learn about supported platforms. You can also build and run a Mojo container by following instructions at https://github.com/modularml/mojo.

### Steps to reproduce

Run curl https://get.modular.com | sh - && \
modular auth mut_db291fdcc429413c940022a98b8e607a in Terminal on M1 Macbook Air.

### System information

```shell
- What OS did you do install Mojo on ? Version 13.6.1 (22G313)
- Provide version information for Mojo by pasting the output of `mojo -v` - N/A
- Provide Modular CLI version by pasting the output of `modular -v` - N/A
```

**Comment by realnihal** [comment]
I am facing the same issue

**Comment by Sharktheone** [comment]
probably that's because your Terminal runs via rosetta. 
Looks very similar to #1078, so check that one out for more information and a potential fix.

**Comment by thphuc** [comment]
I got that issue. What I fixed was disabling `Open using Rosetta`

<img width="320" alt="image" src="https://github.com/modularml/mojo/assets/4323410/5f972d34-67aa-45dd-8c10-72c5f5decf29">

Then

<img width="394" alt="image" src="https://github.com/modularml/mojo/assets/4323410/5ed3a1fc-6449-4f23-88e8-731b4a5d7137">

**Comment by ematejska** [comment]
Please follow the suggestions above and report if there are any more problems.
