### ISSUE TITLE
[BUG]: `IntLiteral`'s `__iadd__` etc. methods doesn't work in (dynamic) loops, needs better error message

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1595]
### Bug description

As title. Maybe it's the intended semantics (`IntLiteral` needs to be materialised at compile time), the error message could still use some improvements.

### Steps to reproduce

Consider the following code:

```mojo
fn main():
    var n: IntLiteral = 0
    for i in range(10):
        n += 1
```

### System information

```shell
Mojo 0.6.0 on Docker, Intel Mac
```

**Comment by gryznar** [comment]
Should `IntLiteral` be writable (probably not)? If Mojo will automatically cast to `Int` declared signature of `n` would be wrong

**Comment by lattner** [comment]
IntLiteral isn't a "materializable" type.  @willghatch shouldn't we reject this?

**Comment by willghatch** [comment]
Erroring out is correct, but it should have a better message.

**Comment by Mogball** [comment]
This is tricky, because the loop would work when being interpreted!

**Comment by soraros** [comment]
@Mogball So, introduce `@parameter` loops and make the compiler happy?
