### ISSUE TITLE
[BUG]: Error if the file is called math.🔥 / math.mojo

### ISSUE THREAD

**Issue by zeelsheladiya** [modularml/mojo#1597]
### Bug description

If a file is called math.mojo or math.🔥, the interpreter gives unrelated errors.

```
// math.🔥
from python import Python

fn main():
    ......
```

```
mojo math.mojo
/Users/zeel/Programming_Practice/mojo/math.mojo:1:6: error: unable to locate module 'Python'
from Python import Python
     ^
/Users/zeel/Programming_Practice/mojo/math.mojo:1:1: error: recursive reference to declaration
from Python import Python
^
/Users/zeel/Programming_Practice/mojo/math.mojo:1:1: note: previously used here
from Python import Python
^
/Users/zeel/Programming_Practice/mojo/math.mojo:1:1: error: module 'math' does not contain 'min'
from Python import Python
^
/Users/zeel/Programming_Practice/mojo/math.mojo:1:1: error: module 'math' does not contain 'min'
from Python import Python
^
/Users/zeel/Programming_Practice/mojo/math.mojo1:1: error: unable to locate module 'bit'
from Python import Python
^
mojo: error: failed to parse the provided Mojo
```

It seems like the filename debug is reserved.

### Steps to reproduce

Create a file called math.mojo or math.🔥
Define fn main(): in the created file
Invoked the mojo interpreter with the file

### System information

```shell
- Apple silicon (M2 processor)
- mojo 0.6.1 (876ded2e)
- modular 0.2.2 (95d42445)
```

**Comment by guidorice** [comment]
Same problem exists in Python FWIW, ex: https://stackoverflow.com/questions/54602023/import-module-with-name-same-as-built-in-module-in-python-3
After being bitten a few times by this, I just learned to be careful about naming source files.
cc @Mogball

**Comment by ematejska** [comment]
Closing this in favor of https://github.com/modularml/mojo/issues/1248
