### ISSUE TITLE
[BUG]: Owned convention does not destroy variable after transferring ownership

### ISSUE THREAD

**Issue by VMois** [modularml/mojo#1604]
### Bug description

Hello everybody! I am working on a project that has small exercises to learn Mojo. I am currently working on the value ownership section and playing with the code below. My issue is that Snippet 1 compiles, but to my understanding of owned and ownership operators, it shouldn't. 

If you take equivalent code for a string in Snippet 2, it has an error "a is not initialized":
For equivalent integer code in Snippet 3, it throws no error, and the value of x is 1.

Can someone please explain if this behavior is correct, or am I missing something? Thank you.

### Steps to reproduce

Snippet 1:
```python
fn take_ptr(owned array: Pointer[Int]):
    array.store(2, 23)


fn main():
    # this line just allocates pointer for 3 integers
    var array = Pointer[Int].alloc(3)

    array.store(0, 1)
    array.store(1, 2)

    # this function call does not need any changes
    take_ptr(array^)

    array.store(2, 2)
    print(array[2])
```

Snippet 2:
```python
fn take_text(owned text: String):
    text += "🔥"
    return text


fn main():
    var a: String = "mojo"

    take_text(a^)
    print(a)
```

Snippet 3:
```python
fn take_value(owned x: Int):
    x += 2


fn main():
    var x: Int = 1
    take_value(x^)
    print(x)
```

### System information

```shell
- What OS did you do install Mojo on ? **MacOS Monterey (M1)**
- Provide version information for Mojo by pasting the output of `mojo -v`? **mojo 0.6.1 (876ded2e)**
- Provide Modular CLI version by pasting the output of `modular -v` - **modular 0.2.2 (95d42445)**
```

**Comment by laszlokindrat** [comment]
@lattner can you please take a look?

**Comment by VMois** [comment]
I just saw that he provided an answer to my Discord question that I asked a few weeks ago (link - https://discord.com/channels/1087530497313357884/1190784717998538903/1196704091041185843).

As soon as new version of Mojo will be released I will check if this bug got fixed or not.

Thank you for your work.

**Comment by lattner** [comment]
yes, there is a bug here.  We are doing the right thing non-trivial types, but trivial types like pointer are not handled correctly.  This should be a compile time error:

```
fn main():
    var array = Pointer[Int]()
    _ = array^          ## Consumes the array variable
    _ = array[2]       ## Should be invalid to use "array" because it is consumed (would also crash at runtime in this case)
```

**Comment by lattner** [comment]
Ah, actually not.  The real issue is that the transfer operation on a value of trivial type (like a pointer or integer) is actually a noop.  It doesn't destroy the input value, because these things don't have copy constructors, move operators or the other stuff to track.

Thank you for filing this, this is pretty confusing.  I filed the compiler to generate a warning to make this more clear:

```
x.mojo:4:14: warning: transfer from a value of trivial register type 'Pointer[Int, 0]' has no effect and can be removed
takePtr(array^)
                      ^
```
