### ISSUE TITLE
Mojo: Opaque Error Message

### ISSUE THREAD

**Issue by suciokhan** [modularml/mojo#1610]
### Issue description

Apologies if this is sub-optimal categorization- none of the options seemed like a good fit for error message rewordings to me. I'd like to offer a recommendation for what to change it to, but unfortunately I don't understand what the problem is or what it's trying to tell me.

The error message is:

`cannot call function that may raise in a context that cannot raise`

I don't know what is meant by raise and "may raise" and "cannot raise" is confusing. Perhaps it comes down to me just needing to be smarter, but in case I'm not the only one who has trouble figuring this out, perhaps it's worth considering.

### Steps to reproduce

* Add screenshots if possible, to help explain the problem.
* Include anything that might help us debug the issue.

```
fn add(x: Int, y: Int) -> Int: 
    return x + y

def addPy(x,y):
    return x + y
```

```
fn main():

    let a:Int = 1
    let b:Int = 2

    print("SUM:", add(a,b)) 
    print("PY SUM", addPy(a,b))
```

**Comment by suciokhan** [comment]
Is the problem that you can't pass strongly-typed variables to a function that uses dynamically typed variables?

**Comment by soraros** [comment]
The error message is actually not wrong, however, maybe you could suggest some improvements on the wording. A `def` is a function that can raise (can throw an exception), and you can't call raising functions from non-raising functions without wrapping the call in `try`/`except`. If you move your cursor onto the function name in VSCode, you will see its type:

```mojo
def addPy(owned x: object, owned y: object) raises -> object
```

As of why your code didn't work, there are several problems:

```mojo
fn add(x: Int, y: Int) -> Int:
  return x + y

def addPy(x, y):  # -> object
  return x + y

def main():  # changed to a def so you may call addPy without try/except
  let a: Int = 1
  let b: Int = 2

  print("SUM:", add(a, b))
  let res: object = addPy(a, b)  # res is an object
  print(res)                     # variadic print currently doesn't support mixing object with other printable types
```

**Comment by suciokhan** [comment]
Hmmm...maybe:

`cannot call a def inside an fn unless the def is inside a try/except loop`

**Comment by soraros** [comment]
Actually, `fn` can raise too, if marked with `raises`, like `fn add(a: Int, b: Int) raises -> Int`.
