### ISSUE TITLE
[BUG]: Wrong type name in error message

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1613]
### Bug description

As title.

### Steps to reproduce

```mojo
trait S:
  fn add(self: Int):
    ...
```

The error message mentions nonexistent type `T`:

```
error: 'self' argument must have type 'T' but actually has type 'Int'
  fn add(self: Int):
         ^     ~~~
```

### System information

```shell
Mojo 0.6.1 on Docker, Intel Mac
```

**Comment by laszlokindrat** [comment]
Thanks for opening the ticket! The error message for this will be improved in the next release, so that it would say something like `'self' argument must have type 'Self' in trait method declaration, but actually has type 'Int'`.
