### ISSUE TITLE
llvm error when installing Mojo on Ubuntu Latest on Lenovo G550 laptop

### ISSUE THREAD

**Issue by dwhire** [modularml/mojo#1615]
### Bug description

I tried to log this with llvm but they closed it with the following message:
This is the issue tracker for the upstream llvm-project, but it looks like the crash is Modular/Mojo related, which is not part of upstream llvm-project. Please raise the issue directly with Modular/Mojo.
----------
Here is the error:
0.	Program arguments: modular install mojo
 #0 0x0000559bafd10867 (/usr/bin/modular+0x53e867)
 #1 0x0000559bafd0e51e (/usr/bin/modular+0x53c51e)
 #2 0x0000559bafd10f2f (/usr/bin/modular+0x53ef2f)
 #3 0x00007f1e5d842910 (/lib/x86_64-linux-gnu/libc.so.6+0x42910)
 #4 0x0000559bb0f6c970 (/usr/bin/modular+0x179a970)
 #5 0x0000559bb0f6ccbb (/usr/bin/modular+0x179acbb)
 #6 0x0000559bb0157ce4 (/usr/bin/modular+0x985ce4)
 #7 0x0000559bafcd1d9a (/usr/bin/modular+0x4ffd9a)
 #8 0x00007f1e5d8280d0 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
 #9 0x00007f1e5d828189 call_init ./csu/../csu/libc-start.c:128:20
#10 0x00007f1e5d828189 __libc_start_main ./csu/../csu/libc-start.c:347:5
#11 0x0000559bafcd16be (/usr/bin/modular+0x4ff6be)
Illegal instruction (core dumped)

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by ematejska** [comment]
Please provide the system information requested.

**Comment by ematejska** [comment]
Does it repeatedly fail or were you sucessfull in installing at some point?

**Comment by dwhire** [comment]
On the 1st attempt it said that the path to llvm symbolizer was not defined. Not knowing if or where that path would be I did an apt-get install Clang. Since then I have not successfully installed Mojo. The error message is consistent even after reboot.

Sent from Yahoo Mail on Android 
 
  On Thu, 11 Jan 2024 at 19:49, ***@***.***> wrote:   


Does it repeatedly fail or were you sucessfull in installing at some point?

**Comment by dwhire** [comment]
This machine has a Pentium Dual-Core T4500.  The SSE4 instruction set is not supported
