### ISSUE TITLE
[BUG]: VSCode deosn't highlight 'fn' keyword in specific contexts 

### ISSUE THREAD

**Issue by kishmakov** [modularml/mojo#1617]
### Bug description

In functional type expression, when function type is parameterized, `fn` keyword is not highlighted.
Looks like it is because Mojo highlighting rules are represented as an increment for Python ones, and in Python `def` is not supposed to be followed by `[`.

![Screenshot from 2024-01-12 10-20-57](https://github.com/modularml/mojo/assets/1360111/df8881ee-5562-44fb-b5e1-604fe5aca009)

### Steps to reproduce

Reproducer is as follows:

```
alias type1 = fn [Bool](Int) -> None # fails
alias type2 = fn (Int) -> None # works
```

### System information

```shell
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
$ mojo --version
mojo 0.6.1 (876ded2e)
$ modular -v
modular 0.2.2 (95d42445)
```

**Comment by River707** [comment]
This should be fixed in the next release!
