### ISSUE TITLE
[BUG]: `String.replace` behaves wrong when replacing multiple characters

### ISSUE THREAD

**Issue by mbelak-dtml** [modularml/mojo#1618]
### Bug description

`String.replace` behaves wrong when replacing multiple characters

### Steps to reproduce

```mojo
let x = String("axxxbc")
print(x.replace("xx", "y"))
```
The result is `"ayyc"`, even though the correct result is `"ayxbc"`.

### System information

```shell
- OS: Manjaro Linux
- mojo -v: mojo 0.6.1 (876ded2e)
- modular -v: modular 0.3.1 (589ce200)
```

**Comment by JoeLoser** [comment]
Duplicate of https://github.com/modularml/mojo/issues/1367 which has already been fixed and will be included in the upcoming release.  I confirmed the provided test case passes as expected with top-of-tree today.
