### ISSUE TITLE
[BUG]: VSCode deosn't highlight 'raises' and 'capturing' keywords when used in functional type expression

### ISSUE THREAD

**Issue by kishmakov** [modularml/mojo#1621]
### Bug description

![Screenshot from 2024-01-13 18-51-31](https://github.com/modularml/mojo/assets/1360111/862ffcec-9c32-4369-9c19-00e05f9f4077)

Keywords 'raises' and 'capturing' are not highlighted when used within functional type expression, while they are highlighted in function definition.

### Steps to reproduce

Open this code fragment:

```
alias callback1 = fn (String) capturing -> None
alias callback2 = fn (String) raises -> None
alias callback3 = fn (String) raises capturing -> None
alias callback4 = fn (String) capturing raises -> None

```

### System information

```shell
VSCode extension v0.6.1

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
$ mojo --version
mojo 0.6.1 (876ded2e)
$ modular -v
modular 0.2.2 (95d42445)
```

**Comment by River707** [comment]
Thank you for filing this! We'll take a look
