### ISSUE TITLE
[Feature Request] Enable SIMD vector of indices in `DTypePointer.simd_load`

### ISSUE THREAD

**Issue by leandrolcampos** [modularml/mojo#1626]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Add an overload to the `DTypePointer.simd_load` method that takes a SIMD vector containing `width` indices as an argument.

This overload should have a semantically equivalent implementation to the following sequence of scalar loads:

```python
for i in range(width):
    result[i] = self[int(indices[i])]
```

Whenever possible, this overload should use SIMD intrinsics, such as the AVX2 intrinsic function `_mm256_i32gather_ps`.

### What is your motivation for this change?

This change aims to enable the efficient implementation of mathematical functions that utilize table lookup algorithms (table-based numerical methods).

**Comment by leandrolcampos** [comment]
Hi, @abduld.

Here are the [`gather` and `scatter` methods](https://github.com/leandrolcampos/mojo/blob/17a6eadf0c31fb4c90f5c29abae84ccb9704b9e7/stdlib/src/memory/unsafe.mojo#L1490-L1673) that I would add to `DTypePointer` along with their [respective unit tests](https://github.com/leandrolcampos/mojo/blob/17a6eadf0c31fb4c90f5c29abae84ccb9704b9e7/stdlib/test/memory/test_memory.mojo#L302-L417).

I would also update the [docstring of the `scatter` function](https://github.com/leandrolcampos/mojo/blob/17a6eadf0c31fb4c90f5c29abae84ccb9704b9e7/stdlib/src/sys/intrinsics.mojo#L677-L680) in `sys.intrinsics` to align it with the [documentation of the `llvm.masked.scatter.*` intrinsics](https://llvm.org/docs/LangRef.html#llvm-masked-scatter-intrinsics) regarding overlapping addresses.

All the best,

**Comment by JoeLoser** [comment]
Fixed with https://github.com/modularml/mojo/commit/1a14a1e6f8ad9273db2c2bf67fcaef3011011195
