### ISSUE TITLE
[Feature Request] Mojo 🔥 0.7

### ISSUE THREAD

**Issue by Eprahim-taha** [modularml/mojo#1629]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Mojo 🔥 0.7

### What is your motivation for this change?

Just curious I'm excited to see what's new in Mojo 

### Any other details?

Thanks

**Comment by Mogball** [comment]
Lifetimes and references

**Comment by Eprahim-taha** [comment]
What is the time frame for Mojo 0.7 release?
