### ISSUE TITLE
[BUG]: `fn` using generic type doesn't type check.

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1631]
### Bug description

As title.

### Steps to reproduce

```mojo
fn g[T: AnyType, f: fn(x: T) -> None]():
    ...
 
fn f(x: Int):
    ...
 
fn main():
    g[Int, f]()
```

Above produces the error:

```
error: cannot pass 'fn(x = Int) -> None' value, parameter expected 'fn(x = Int) -> None'
    g[Int, f]()
```

### System information

```shell
Mojo 0.6.1 on Docker, Intel Mac
```

**Comment by lattner** [comment]
I looked into this, the problem is that the argument conventions mismatch: "g" takes a function pointer where (because of the trait bound) the argument is passed in memory, but "f" is taking the argument in a register:

```
from: !kgen.signature<!lit.signature<("x": !lit.declref<@stdlib::@builtin::@int::@Int> borrow) -> !kgen.none>>
to: !kgen.signature<!lit.signature<[1]("x": !lit.ref<@stdlib::@builtin::@int::@Int, imm *[0,0]> borrow_in_mem) -> !kgen.none>>
```

we'll need to generate a thunk in this case.  @Mogball fyi

**Comment by soraros** [comment]
@lattner So, re-abstraction thunk like in Swift?
