### ISSUE TITLE
[BUG]: Mojo produces weird error when `inout` function is used in non mutating function

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1632]
### Bug description

As title.

### Steps to reproduce

```mojo
struct S[T: CollectionElement]:
  var data: T
 
fn f(inout v: S):
  ...
 
fn g(v: S):
  f(v)
```

Above produces:

```
/workspaces/ubuntu/issues/1632.mojo:8:4: error: invalid call to 'f': callee expects 1 input parameter, but 0 were specified
  f(v)
  ~^~~
/workspaces/ubuntu/issues/1632.mojo:4:1: note: function declared here
fn f(inout v: S):
^
/home/vscode/.modular/pkg/packages.modular.com_mojo/bin/mojo: error: failed to parse the provided Mojo
```

### System information

```shell
Mojo 0.6.1 on Docker, Intel Mac.
```

**Comment by arthurevans** [comment]
I'm not sure the error is entirely wrong here. By declaring a function that takes a partially-bound type (`S`), you're adding an implicit parameter to the function. So writing:

`fn f(inout v: S):`

Is approximately the same as writing:

`fn f[T: CollectionElement](inout v: S[T]):`

But you're never specifying the `T` parameter. Hence the error.

The fact that you get different errors based on whether the outer function has an `inout` argument is odd, and seems like a bug to me.

**Comment by soraros** [comment]
@arthurevans I don't think not specifying the `T` parameter is the problem here, since if we remove or add both `inout`, parameter inference works, and the error goes away.

**Comment by lattner** [comment]
Thanks for filing this, with the fix we now produce:
```
invalid call to 'f': argument #0 must be mutable in order to pass to a mutating argument
```
