### ISSUE TITLE
[Modular CLI]: Docker container: modular: error: invalid manifest: expiration has passed

### ISSUE THREAD

**Issue by benjamin-pieczynski** [modularml/mojo#1637]
### Issue description

When building the Docker container using the Dockerfile.mojosdk file I get the following error.

Step 12/18 : RUN modular install mojo
modular: error: invalid manifest: expiration has passed

I added the authentication token from my account into the file before building the container.

### Steps to reproduce

1.)  curl https://get.modular.com | sh - && \
modular auth $AUTH_TOKEN

2.) modular install mojo

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
Latest version. v0.3.1
- What OS did you install modular CLI on ?
Building Docker container on an Ubuntu 18.04 system. Container is running Ubuntu 20.04.
```

**Comment by zbowling** [comment]
Thie issue has been resolved now. Go ahead and give it another try. Sorry about that!
