### ISSUE TITLE
[Modular CLI]: modular: error: invalid manifest: expiration has passed

### ISSUE THREAD

**Issue by donutloop** [modularml/mojo#1640]
### Issue description

While attempting to install the Mojo SDK on Ubuntu 22.04 using the command "modular install mojo," an error occurred, stating "modular: error: invalid manifest: expiration has passed."

### Steps to reproduce

Command steps 

* curl https://get.modular.com | sh - && \
modular auth mut_583247e22c7349cd9d43f655b880897b
* modular install mojo

![Screenshot from 2024-01-19 07-14-27](https://github.com/modularml/mojo/assets/9432921/b60e6589-f71c-4418-b23d-deef04d3b97c)

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`

modular 0.3.1 (589ce200)

- What OS did you install modular CLI on ?

Ubuntu 22.04, Kernel 6.5.0-14-generic
```

**Comment by zbowling** [comment]
These issue has been resolved now. Go ahead and give it another try. Sorry about that!
