### ISSUE TITLE
[Modular CLI]: Issue updating mojo with modular CLI 0.3.1

### ISSUE THREAD

**Issue by Patrikios** [modularml/mojo#1646]
### Issue description

root@DESKTOP-M2105EE:~# modular --version
modular 0.3.1 (589ce200)
root@DESKTOP-M2105EE:~# modular update mojo
loc("#M.target<triple = \22x86_64-unknown-linux\22, cpu = \22skylake\22, features = \22+64bit,+adx,+aes,+avx,+avx2,+bmi,+bmi2,+clflushopt,+cmov,+crc32,+cx16,+cx8,+f16c,+fma,+fsgsbase,+fxsr,+invpcid,+lzcnt,+mmx,+movbe,+pclmul,+popcnt,+prfchw,+rdrnd,+rdseed,+rtm,+sahf,+sgx,+sse,+sse2,+sse3,+sse4.1,+sse4.2,+ssse3,+x87,+xsave,+xsavec,+xsaveopt,+xsaves\22, data_layout = \22e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128\22, simd_bit_width = 256>":1:50): error: duplicate or unknown struct parameter name: cpu
[833:833:20240121,215216.011419:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[833:833:20240121,215216.011498:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.      Program arguments: modular update mojo
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  modular   0x000055f25d9c0867
1  modular   0x000055f25d9be51e
2  modular   0x000055f25d9c0f2f
3  libc.so.6 0x00007fe31fc73520
4  modular   0x000055f25dde6ba4
5  modular   0x000055f25dde622f
6  modular   0x000055f25d99c354
7  modular   0x000055f25d99b73a
8  modular   0x000055f25d9824b3
9  libc.so.6 0x00007fe31fc5ad90
10 libc.so.6 0x00007fe31fc5ae40 __libc_start_main + 128
11 modular   0x000055f25d9816be
Segmentation fault

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
- What OS did you install modular CLI on ? Windows 11 via WSL
```

**Comment by gryznar** [comment]
1. Which WSL are you using? (WSL 1 is not supported)
2. Have you performed `modular clean` with retrying?
