### ISSUE TITLE
[Modular CLI]: make installation-Shell-Script compatible to the POSIX standard and do not use [[ in the script - or adapt instructions to use bash

### ISSUE THREAD

**Issue by elasticjava** [modularml/mojo#1647]
### Issue description

in line 80 of the installation script got by `curl https://get.modular.com` you use following code:
```bash
if [[ -n "${MODULAR_AUTH-}" ]]; then
  modular auth "$MODULAR_AUTH"
fi
```
this is valid for bash shell scripting but not for shell scripting compatible to the POSIX standard. 
you have to write:
```sh
if [ -n "${MODULAR_AUTH-}" ]; then
  modular auth "$MODULAR_AUTH"
fi
```

### Steps to reproduce

follow the instruction No.2 on https://developer.modular.com/download

### Version Info

```shell
modular (0.3.1)
```

**Comment by vctrstrm** [comment]
Just ran into this. This is actually not even a standard issue but a complete breaking bug. All current instructions say to run script through "/bin/sh" (including Windows WSL instructions), even the shebang line at top of the script from `get.modular.com` is "#!/bin/sh". The syntax used at line 80 of that script (referenced in OP) is simply not compatible with /bin/sh and breaks during install so nothing there ever runs anyway

**Comment by ematejska** [comment]
Thank you for trying out Mojo.  The installation experience has significantly changed and we're closing out all the old issues with the old installer.  To try out our new installation experience using "magic", please see: https://docs.modular.com/mojo/manual/get-started.
