### ISSUE TITLE
[Modular CLI]: cURL error SSL connect error - on Ubuntu 20.04 on WSL 2

### ISSUE THREAD

**Issue by petermweeks** [modularml/mojo#1658]
### Issue description

Following the instructions to install mojo via the modular cli and `modular install mojo` fails with:
`modular: error: http error: failed to reach URL https://packages.modular.com/mojo/1.root.json with cURL error SSL connect error -`

I'm 95% sure the issue is a certificate issue, as I'm in an environment which uses SSL inspection. Is there a way to configure the modular cli to look in a different place for certificates? 

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
`modular install mojo`

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.4.0 (01374fa3)
- What OS did you install modular CLI on ?
Ubuntu 20.04.6 LTS on WSL2
```

**Comment by bzcheeseman** [comment]
Hi @petermweeks - I suggest trying the `CURL_CA_BUNDLE` env variable and point it at your certificate bundle. Alternatively, you could copy the certificates into the standard system location, which the `curl` command line tool should be able to help with.

**Comment by petermweeks** [comment]
Tried this and got the same error :S Don't sweat it, I'll just play around with mojo on a different box. I thought maybe `curl `had special behavior like `node`, for which we have to export `NODE_EXTRA_CA_CERTS` in order to get it to work, despite the special certs being present in `/etc/ssl/certs/ca-certificates.crt`

**Comment by petermweeks** [comment]
Closing because it's a very niche problem and unlikely to be solved without more than trivial effort.
