### ISSUE TITLE
[BUG]: Wrong highlighting then defining self referential function in function

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1659]
### Bug description

As title. Likely a LSP bug. Notice the `f` in `fn`; shows tooltip when mouse is hovered over `f`.
<img width="254" alt="Screenshot 2024-01-24 at 22 41 22" src="https://github.com/modularml/mojo/assets/6129707/37865f35-b145-4982-8f4e-9925c756a1c4">

### Steps to reproduce

```mojo
fn main():
  fn g():
    g()
```

### System information

```shell
Mojo 0.6.1 on Docker, Intel Mac
```

**Comment by River707** [comment]
Thanks for the report! It looks like this issue has been resolved, I'm no longer able to reproduce it. Can you verify?

**Comment by soraros** [comment]
@River707 Indeed it's working on both `mojo 24.2.0` and `mojo 2024.4.117`. Closing. Thank you for the fix!
