### ISSUE TITLE
error while installation process.

### ISSUE THREAD

**Issue by Swag-With-Jal** [modularml/mojo#1662]
Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: while locating crashpad handler: unable to locate crashpad handler executable

**Comment by gryznar** [comment]
Duplicate. If you are using WSL 1, you have to update it to WSL 2. Look at: https://github.com/modularml/mojo/issues/984

**Comment by Swag-With-Jal** [comment]
There are few things like giving path which we missed.....while installing mojo you have to give this(export MODULAR_HOME="$HOME/.modular"
export PATH="$MODULAR_HOME/pkg/packages.modular.com_mojo/bin:$PATH") path and while using jupyter lab use this (export PATH="$HOME/.local/bin:$PATH") path in vscode teminal...without it jupter lab will not work.

**Comment by rcghpge** [comment]
hey group, I am running into this toolchain issue as well. I have WSL2 on Windows verified 

![Image](https://github.com/user-attachments/assets/77c300a8-ba9a-45c7-8c27-52f8c6746d53)
![Image](https://github.com/user-attachments/assets/bcbf234b-0379-4a80-8066-bd7f3338dc8c)
