### ISSUE TITLE
[Feature Request] Add check to `modular install mojo` if WSL 1 is used

### ISSUE THREAD

**Issue by gryznar** [modularml/mojo#1663]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

People using WSL 1 often come with problem that installation is broken. Adding check to `modular` CLI tool if WSL 1 is used and stopping installation with instruction how to update WSL could be very helpful

### What is your motivation for this change?

It would greatly help to solve common problem with installation

**Comment by Mechanick13** [comment]
1.Open windows cmd with administrator rights
2.To change versions, use the command: wsl --set-version <distro name> 2 
replacing <distro name> with the name of the Linux distribution that you want to update. For example, 
wsl --set-version Ubuntu-20.04 2 
will set your Ubuntu 20.04 distribution to use WSL 2
p.s.
Check if virtualization is enabled in "Turn Windows features on or off" :)

**Comment by gryznar** [comment]
Bumping up. Implementing this check would prevent cases like this: https://github.com/modularml/mojo/issues/3292 to occur

**Comment by ematejska** [comment]
Thank you for trying out Mojo.  The installation experience has significantly changed and we're closing out all the old issues with the old installer.  To try out our new installation experience using "magic", please see: https://docs.modular.com/mojo/manual/get-started.
