### ISSUE TITLE
[BUG]: modular install mojo

### ISSUE THREAD

**Issue by betapro** [modularml/mojo#1680]
### Bug description

Error message from: $ modular install mojo
loc("#M.target<triple = \22x86_64-unknown-linux\22, cpu = \22znver2\22, features = \22+64bit,+adx,+aes,+avx,+avx2,+bmi,+bmi2,+clflushopt,+clwb,+clzero,+cmov,+crc32,+cx16,+cx8,+f16c,+fma,+fsgsbase,+fxsr,+lzcnt,+mmx,+movbe,+mwaitx,+pclmul,+popcnt,+prfchw,+rdpid,+rdpru,+rdrnd,+rdseed,+sahf,+sha,+sse,+sse2,+sse3,+sse4.1,+sse4.2,+sse4a,+ssse3,+wbnoinvd,+x87,+xsave,+xsavec,+xsaveopt,+xsaves\22, data_layout = \22e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128\22, simd_bit_width = 256>":1:50): error: duplicate or unknown struct parameter name: cpu
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.	Program arguments: modular install mojo
 #0 0x000056216c0e3ce7 (/usr/bin/modular+0x556ce7)
 #1 0x000056216c0e199e (/usr/bin/modular+0x55499e)
 #2 0x000056216c0e43af (/usr/bin/modular+0x5573af)
 #3 0x00007fea89842520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x000056216c50f194 (/usr/bin/modular+0x982194)
 #5 0x000056216c50e79f (/usr/bin/modular+0x98179f)
 #6 0x000056216c0a81f3 (/usr/bin/modular+0x51b1f3)
 #7 0x000056216c0a71f9 (/usr/bin/modular+0x51a1f9)
 #8 0x000056216c0a50b3 (/usr/bin/modular+0x5180b3)
 #9 0x00007fea89829d90 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
#10 0x00007fea89829e40 call_init ./csu/../csu/libc-start.c:128:20
#11 0x00007fea89829e40 __libc_start_main ./csu/../csu/libc-start.c:379:5
#12 0x000056216c0a478e (/usr/bin/modular+0x51778e)
Segmentation fault (core dumped)

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ? Linux Mint 21.2 (Victoria)
- Provide version information for Mojo by pasting the output of `mojo -v` mojo 0.2.1 (64d14e85)
- Provide Modular CLI version by pasting the output of `modular -v` modular 0.4.1 (2d8afe15)
```

**Comment by gryznar** [comment]
Try:
```
modular clean
modular install mojo
```

**Comment by betapro** [comment]
$ modular clean
$ modular install mojo
This sorted out the issue! Tx.
