### ISSUE TITLE
[Modular CLI]: Broken progress bar if terminal window is not maximized

### ISSUE THREAD

**Issue by gryznar** [modularml/mojo#1686]
### Issue description

If terminal is open in full-sized mode progress bar works as expected. As soon as size of window is changed to smaller, sth like this happen:
![image](https://github.com/modularml/mojo/assets/90425096/4f453dac-57d1-4976-b2b0-0abab69db461)

### Steps to reproduce

Try to install Mojo in not full-sized terminal window.

### Version Info

```shell
modular 0.4.1 (2d8afe15)
Ubuntu 23.04
```

**Comment by zbowling** [comment]
If you update to modular CLI 0.5.1, the progress bar now dynamically sizes itself to the width of your terminal. Let me know you run into anymore issues.

**Comment by gryznar** [comment]
@zbowling it does not work if you change size few times from normal to maximized

**Comment by zbowling** [comment]
Can you post a screenshot of what you are seeing now?

**Comment by gryznar** [comment]
![image](https://github.com/modularml/mojo/assets/90425096/dee609d6-7d36-437b-8e39-b2fc4493878b)
To repro: enter and exit full screen few times
