### ISSUE TITLE
[BUG]: Tuple unpacking doesn't support generic type?

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1693]
### Bug description

As title. Not sure it's the correct title though.

### Steps to reproduce

```mojo
fn swap(inout v: DynamicVector):
  v[0], v[1] = v[1], v[0]
```

Code crashes with:

```
<unknown>:0: error: variadic sequence element #0 has type
  '!lit.trait<@"$stdlib"::@"$collections"::@"$vector"::@CollectionElement>'
but expected
  '!kgen.type'
```

### System information

```shell
Mojo 0.7.0 on Docker, Intel Mac
```

**Comment by laszlokindrat** [comment]
I was able to repro this, and I'm even seeing a crash after the error. @stumpOS could you please take a look?
