### ISSUE TITLE
[BUG]: Crash when attempting to assign a value to a type ("illegal hardware instruction")

### ISSUE THREAD

**Issue by nmsmith** [modularml/mojo#1695]
The crash happens both in the Mojo playground and in my local installation.

### Steps to reproduce

Put the following code in the Mojo REPL, a Mojo file, or on the Mojo playground:
```
fn crash():
    var a = Int
    var b = Int()
    a = b
```

The function doesn't need to be executed. The following error will occur:
> [78426:4192641:20240128,125322.632736:WARNING crash_report_exception_handler.cc:257] UniversalExceptionRaise: (os/kern) failure (5)
zsh: illegal hardware instruction  mojo

### System information

```shell
- MacOS Ventura (M1)
- mojo 0.7.0 (af002202)
- modular 0.2.1 (5144fffe)
```

**Comment by laszlokindrat** [comment]
Thanks for opening the ticket! Variables of a type values (e.g. `var a = Int` in the OP) have been disabled, so this crash no longer reproduces, and just yields the following error instead:
```console
error: dynamic type values not permitted yet; try creating an `alias` instead of a `var`
    var a = Int
```
Please open another ticket if you run into other problems!
