### ISSUE TITLE
[BUG]: VSCode syntax highlighting seems to have regressed a bit for `0.7`

### ISSUE THREAD

**Issue by tristanbiesecker** [modularml/mojo#1696]
### Bug description

Syntax highlighting seems to be a bit flakey for version `0.7`. When I first open a file, everything looks good. However, once I start coding, I often find that the new code a write isn't highlighted properly. Further, the act of writing that new code sometimes results in already-written code losing its highlighting.

### Steps to reproduce

**When open the file for the first time:**
<img width="801" alt="Screenshot 2024-01-27 at 8 11 05 PM" src="https://github.com/modularml/mojo/assets/12146879/52cb8f6c-ddcf-4065-ad3a-bd03b16fd0a5">

**After changing `value` to `Optional[String]`:**
<img width="904" alt="Screenshot 2024-01-27 at 8 14 18 PM" src="https://github.com/modularml/mojo/assets/12146879/7ff8cf15-b529-435d-bc26-acd901d1bb71">

Note that optional syntax is not highlighted properly. I also sometimes have seen the rest of the statements within the `__init__` function lose highlighting. If I close the file and re-open it, everything is highlighted properly.

Another example of inconsistent highlighting with comments (the top line is correctly grayed out, but the button one is not):
<img width="202" alt="Screenshot 2024-01-27 at 8 23 27 PM" src="https://github.com/modularml/mojo/assets/12146879/bd351561-528e-45aa-913f-3ea9fa40efb6">

### System information

```shell
- What OS did you do install Mojo on ?
macOS 14.2.1
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.7.0 (af002202)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.4.1 (2d8afe15)
```

**Comment by River707** [comment]
Thanks for filing this! Turns out that a change snuck in that misconfigured our runtime, causing a bunch of LSP requests (like semantic tokens) to get dropped. This should be fixed in the next release!
