### ISSUE TITLE
[BUG] Typo in HelloMojo.ipynb - Second paragraph uses the word "directory" where "directly" should be.

### ISSUE THREAD

**Issue by drylwlsn** [modularml/mojo#170]
## Bug Description
Second paragraph uses the word "directory" where "directly" should be used.

### Steps to Reproduce

1. Simple typo; text uses "directory" where it should say "directly".

**Comment by lattner** [comment]
@scottamain

**Comment by scottamain** [comment]
Thank you. We just pushed a fix for this.
