### ISSUE TITLE
[BUG]: @value doesn't delete the default constructor if an `__init__()` is provided

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [modularml/mojo#1705]
### Bug description

From the documentation about `@value`: 
> Mojo synthesizes each lifecycle method only when it doesn’t exist, so you can use @value and still define your own versions to override the default behavior.

Which seems to be wrong. Here is an example showing that the default `__init__` exists even if redeclared:
```python
@value
struct SomeStruct:
    var a :  Int
    var b : Int

    fn __init__(inout self, b : Int):
        self.a = b - 5
        self.b = b


fn main():
    var x = SomeStruct(10, 20)
    print(x.a, x.b) # prints 10 20, __init__ is not called
```

So the next question is "Should be change the docs of should we change the way `@value` works? I believe we should change the way `@value` works because it prevents the user to write some code. The compiler has a hard time with this:

```python
@value
struct SomeStruct:
    var a :  Int

    fn __init__(inout self, a : Int, add_10: Bool = False):
        self.a = a
        if add_10:
            self.a += 10


fn main():
    var x: Int = 10
    var y = SomeStruct(x)
    # here we get "error: cannot construct 'SomeStruct' from 'Int' value in 'var' initializer"

    var z = SomeStruct(a=x)
    # here we get "error: ambiguous call to '__init__', each candidate requires 0 implicit conversions, disambiguate with an explicit cast"
```
So users are locked out of `@value` if they want to add optional arguments to the constructor, which is a very common use case. I wonder is the issue is similar with `__copyinit__` and `__moveinit__`.

### Steps to reproduce

See above.

### System information

```shell
- What OS did you do install Mojo on ?
ubuntu 22.04
mojo -v
mojo 0.7.0 (af002202)
modular -v
modular 0.4.0 (01374fa3)
```

**Comment by arthurevans** [comment]
Will leave this open in case the eng team has comments here but at the minimum we should clarify the docs around `@value` and constructor overrides.

**Comment by gabrieldemarmiesse** [comment]
That's indded the issue here. We can't with `@value` define a new constructor that has additional default arguments. They overlap with each other. If I want to add optional arguments, I have to give up on `@value` completely, but that means I have to implement the two other methods `__moveinit__` and `__clopyinit__` myself. That hurts the UX quite a bit.

**Comment by arthurevans** [comment]
In answer to another part of the original question. The copy constructor and move constructors are different: they always have the same signature. If you define a copy constructor, it will suppress the generated copy constructor. 

But it's very common to overload the constructor, so `@value` doesn't suppress the member-wise constructor if you define _any_ constructor, only if you define a constructor with the same arguments. If you have 10 fields, `@value` will synthesize the constructor with 10 fields, and you can write overloads for shortcuts that default the field values.

If there's a good case for suppressing the default member-wise constructor, it's possible that could be added to the decorator.

**Comment by gabrieldemarmiesse** [comment]
I propose the following behavior as a way to respect the existing behavior, and remove the behavior that produces an error, let me know if it's technically feasable or not.

When the compiler reads the stuct, if there is at least one `__init__` defined by the user:
     * The compiler tries to call the `__init__` defined by `@value`, what we call here the default constructor. If there is no issue, then the existing behavior is applied. If we get an error `error: ambiguous call to '__init__'`, then it means that the default constructor made by `@value` is unusable (meaning it will never be chosen by the compilator in any call possible), and thus can be removed.

With this behavior, we are backward compatible, the behavior will just change if the user was previously getting an `ambiguous call` error, by using the user-defined `__init__` instead of the default one, because the default one is unusable.

**Comment by arthurevans** [comment]
OK. The next version of the docs we publish will include a clarification of the current behavior. I'm going to convert this into a feature request.

**Comment by laszlokindrat** [comment]
Thank you for opening the ticket! We discussed the issues that arise when explicit overloads of `__init__` exist on a `@value` struct, and acknowledge that this area could use some quality of life improvement. Our goal with the `@value` decorator is to provide a simple and predictable model for generating magic methods for structs with value-like semantics, leading to better readability and less boilerplate. We think that modifying overload resolution rules to treat methods synthesized by `@value` differently would make the model more complicated. Instead, we will allow customization of `@value` and what methods it synthesizes, so that one can opt in/out of generating some of them. We will also consider implementing some basic checks in the parser that could catch and warn about common ambiguities like those in the OP. We will start to flesh out the details of this soon.

**Comment by gryznar** [comment]
Everything related to creation in one place? Looks promising!
