### ISSUE TITLE
[Modular CLI]: Providing support for manual install

### ISSUE THREAD

**Issue by kobzar** [modularml/mojo#1706]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

There many users use differents version linux on their desktop, like arch, void, gentoo, slack, e.t.c or BSD systems.
So, it was be perfect if you will add the variant to manual installation of Modular for Power Users.

Its make your product more popularity and get more feedback. 
This is look worse now that user must migrate to ubuntu to chek how to mojo work.
The same for tests on VM.

I dont think that put the few files from prebuild archive is hard or check the required libs for linux power users.
Thanks.

### What is your motivation for this change?

Poetry, rust - the good examples for it

**Comment by ematejska** [comment]
Thank you for trying out Mojo.  The installation experience has significantly changed and we're closing out all the old issues with the old installer.  To try out our new installation experience using "magic", please see: https://docs.modular.com/mojo/manual/get-started.
