### ISSUE TITLE
[Docs] Add entries about `Variant` and `Optional` to Mojo manual

### ISSUE THREAD

**Issue by gryznar** [modularml/mojo#1717]
### Where is the problem?

https://docs.modular.com/mojo/manual/

### What can we do better?

Manual is missing mention about `Variant` and `Optional` from collection. This features are very powerful and useful, but badly exposed. For most users manual is main entry point and they are missing them, because they are placed somewhere deeper in documentation

**Comment by Brian-M-J** [comment]
Small correction. It's [`Variant`](https://docs.modular.com/mojo/stdlib/utils/variant.html#variant), not `Variance`.

**Comment by gryznar** [comment]
@Brian-M-J thanks! Fixed

**Comment by arthurevans** [comment]
This (or at least Optional) probably belongs in a section on stdlib collection types.
