### ISSUE TITLE
[BUG]: can't install mojo on mac m1 pro

### ISSUE THREAD

**Issue by eamag** [modularml/mojo#1719]
### Bug description

Can't install, 
```      bundled/zeromq/src/curve_client_tools.hpp:189:40: error: type 'std::vector<uint8_t, secure_allocator_t<uint8_t>>' (aka 'vector<unsigned char, secure_allocator_t<unsigned char>>') does not provide a subscript operator
                  memcpy (&initiate_plaintext[crypto_box_ZEROBYTES + 48 + 80],
                           ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      fatal error: too many errors emitted, stopping now [-ferror-limit=]
      20 errors generated.
      ************************************************
      ************************************************
      error: command '/usr/bin/clang++' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyzmq
ERROR: Could not build wheels for pyzmq, which is required to install pyproject.toml-based projects
```

Probably at ``` clang++ -std=c++11 -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -DZMQ_HAVE_CURVE=1 -DZMQ_USE_TWEETNACL=1 -DZMQ_USE_KQUEUE=1 -DZMQ_IOTHREADS_USE_KQUEUE=1 -DZMQ_POLL_BASED_ON_POLL=1 -Ibundled/zeromq/include -Ibundled -I/Users/...``` 

### Steps to reproduce

```
conda create --name pet
conda activate pet
modular install mojo
```

### System information

```shell
- MacOS 14.3 
- modular 0.4.1 (2d8afe15)
```

**Comment by smuniraj2018** [comment]
Can you please do try
```
brew update
brew upgrade modular
```
and let us know if you still see this issue using our modular-cli 0.5.1?

**Comment by ematejska** [comment]
Thank you for trying out Mojo.  The installation experience has significantly changed and we're closing out all the old issues with the old installer.  To try out our new installation experience using "magic", please see: https://docs.modular.com/mojo/manual/get-started.
