### ISSUE TITLE
Can't run Modular either Mojo on a Mac M2

### ISSUE THREAD

**Issue by ceha80** [modularml/mojo#1720]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

I have installed Modular and Mojo on MacOs M2 as the installation instructions said, but I only get error messages. For example with "modualr --version" I get following error message: "Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: /home/saket/.modular could not be created: Operation not supported
modular 0.4.1 (2d8afe15)" or when I run a program "mojo test.mojo" I get "Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: while creating crashpad database: Operation not supported
/Users/ceha/mojo/test.mojo:1:1: error: unable to locate module 'builtin'
fn main()
^
/Users/ceha/mojo/test.mojo:2:1: error: TODO: expressions are not yet supported at the file scope level
print("Hello World")
^
/Users/ceha/mojo/test.mojo:2:1: error: use of unknown declaration 'print'
print("Hello World")
^~~~~
/Users/ceha/mojo/test.mojo:2:1: error: unknown function effect 'print', expected 'raises' or 'capturing'
print("Hello World")
^
/Users/ceha/mojo/test.mojo:2:6: error: expected ':' in function definition
print("Hello World")
     ^
/Users/ceha/mojo/test.mojo:2:7: error: could not find builtin 'StringLiteral' type
print("Hello World")
      ^
mojo: error: failed to parse the provided Mojo"

But I've found nozhing about these issues. Please help!

### What is your motivation for this change?

I can't work with mojo

**Comment by Sharktheone** [comment]
It looks like you have tried to run code without a function.
Currently you need a function in order to use mojo.

So, you need to do this:
```python
fn main():
    print("Hello, world!")
```

**Comment by jackos** [comment]
It says it can't create `/home/saket/.modular` but your user is `/Users/ceha/mojo/`

Can you try starting from scratch.

First, remove the PATH and MODULAR_HOME you added for Mojo in your `~/.zshrc` and then run:

```
rm -r ~/.modular
brew uninstall modular
curl https://get.modular.com | sh -
modular auth <your-token>
modular install mojo
```

And add the new PATH and MODULAR_HOME it prompts in your `~/.zshrc`

**Comment by ceha80** [comment]
> It says it can't create `/home/saket/.modular` but your user is `/Users/ceha/mojo/`
> 
> Can you try starting from scratch.
> 
> First, remove the PATH and MODULAR_HOME you added for Mojo in your `~/.zshrc` and then run:
> 
> ```
> rm -r ~/.modular
> brew uninstall modular
> curl https://get.modular.com | sh -
> modular auth <your-token>
> modular install mojo
> ```
> 
> And add the new PATH and MODULAR_HOME it prompts in your `~/.zshrc`

Hello jackos,
thanks for your advice. I did it like you said but when I type "modular install mojo", I get now following error message: "Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: /home/saket/.modular could not be created: Operation not supported
modular: error: please run `modular auth` before attempting to install a package" BUT I runned my modular auth!

**Comment by jackos** [comment]
@ceha80 It's strange that it's using the path: `/home/saket/.modular` because that's a Linux path, macOS looks like `/Users/saket/.modular`

Make sure that `MODULAR_HOME` is not set, running this should return nothing:

```bash
echo $MODULAR_HOME
```

If that's returning `/home/saket/.modular` remove it from your `~/.bashrc` or `~/.zshrc`, restart the terminal, and run the steps above again.

The only other thing I can think of is to make sure you're using arm64 homebrew. [You can follow the steps here to check and fix that](https://github.com/modularml/mojo/issues/1078#issuecomment-1771674021)

**Comment by ceha80** [comment]
> @ceha80 It's strange that it's using the path: `/home/saket/.modular` because that's a Linux path, macOS looks like `/Users/saket/.modular`
> 
> Make sure that `MODULAR_HOME` is not set, running this should return nothing:
> 
> ```shell
> echo $MODULAR_HOME
> ```
> 
> If that's returning `/home/saket/.modular` remove it from your `~/.bashrc` or `~/.zshrc`, restart the terminal, and run the steps above again.
> 
> The only other thing I can think of is to make sure you're using arm64 homebrew. [You can follow the steps here to check and fix that](https://github.com/modularml/mojo/issues/1078#issuecomment-1771674021)


Unfortunately, nothing works. I only recently bought this MacBook Air because I'm tired of screwing around with Linux for ages until something works properly. Unfortunately, I have to say that it's at least the same with Mac. 

Can someone explain to me why this simply doesn't work with a new Mac?
