### ISSUE TITLE
Unstablity of Tensor.data()

### ISSUE THREAD

**Issue by Rick0827** [modularml/mojo#1733]
### Discussed in https://github.com/modularml/mojo/discussions/1732

<div type='discussions-op-text'>

<sup>Originally posted by **Rick0827** February  5, 2024</sup>
Codes with problem:
<img width="328" alt="image" src="https://github.com/modularml/mojo/assets/137137852/1c185c79-3c16-4442-85ca-05802edeed26">
Env: WSL Ubuntu22.04 || mojo 0.7.0
For the output of the loop, expected "1.0 2.0 3.0 4.0", got
<img width="200" alt="image" src="https://github.com/modularml/mojo/assets/137137852/eff57f86-d1b2-46d9-bc3c-175b7f5b10ac">
which is unstable.
But everything seems to be correct in REPL or add "print(sample[i])" to the loop.</div>

**Comment by Elshararomeus** [comment]
tanks you

Le lun. 5 févr. 2024 à 11:18 AM, Rick0827 ***@***.***> a
écrit :
