### ISSUE TITLE
[Feature Request] import .mojo file in playground

### ISSUE THREAD

**Issue by czheo** [modularml/mojo#174]
## Request

Allow user to save `.mojo` files in playground and import them in notebook.

### Motivation

User defined common libraries can be saved in those files without copying around among notebooks.

### Description and Requirements

Save a file `MyTest.mojo` like below in the same dir as the notebook.
```py
fn myTest():
    print(42)
```

Run from notebook
```py
from MyTest import myTest
myTest()
```
Optional consideration: How import paths should be specified? via `sys.path`, environment variable or etc?

**Comment by Mogball** [comment]
Hey, thanks for filing this issue. The ability to import Mojo files in notebooks is not something that is intended to be supported and is not something we intend to add at the moment.
