### ISSUE TITLE
[BUG]: LSP showing unrelated(?) info when cursor points to `struct`

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1740]
### Bug description

As title. It's not really *unrelated* to be fair.

<img width="391" alt="Screenshot 2024-02-09 at 17 16 00" src="https://github.com/modularml/mojo/assets/6129707/69dd8008-2267-48f9-8070-e5d886770b4e">

### Steps to reproduce

```mojo
struct S:
  ...
```

### System information

```shell
Mojo 0.7.0 on Docker, Intel Mac
```

**Comment by River707** [comment]
Yep, thanks for filing this! We need some better filtering of synthetic functions that get generated, we'll take a look at this!
