### ISSUE TITLE
[BUG]: LSP doesn't show `inout`, `owned` etc. keywords for variadic arguments

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1741]
### Bug description

As title.
<img width="271" alt="Screenshot 2024-02-10 at 05 06 58" src="https://github.com/modularml/mojo/assets/6129707/96f11601-1542-454f-b701-5d1361e730f3">

### Steps to reproduce

```mojo
fn f(inout *x: Int):
  ...
```

### System information

```shell
Mojo 0.7.0 on Docker, Intel Mac
```

**Comment by River707** [comment]
Thanks for reporting this! Looks like some missed updates in documentation generation, we'll take a look!

**Comment by River707** [comment]
This should be fixed in the next release!
