### ISSUE TITLE
[BUG]: Parser crash when constructor of `DTypePointer` called on value with wrong type

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1743]
### Bug description

As title. The code is *invalid*, it should fail gracefully though.

### Steps to reproduce

```mojo
fn f():
  let n = 0
  let p = DTypePointer[DType.uint8](n.__add__)
```

### System information

```shell
Mojo 0.7.0 on Docker, Intel Mac
```

**Comment by laszlokindrat** [comment]
Thanks for opening the ticket! This must have been fixed recently, as I can no longer reproduce it on head of main:
```mojo
fn f():
  var n = 0
  var p = DTypePointer[DType.uint8](n.__add__)
```
Please open a new ticket if you run into similar issues!
