### ISSUE TITLE
[Feature Request] Is it possible to bring Mojo to the IOT community

### ISSUE THREAD

**Issue by kanstantsin-bucha** [modularml/mojo#175]
## Request

Hi! Is there a possibility to make mojo the language of IOT devices too? I got the idea that it could be used instead of C++. And the primary pain of IOT development is that C++ is too overcomplicated, and Python is too slow on IOT devices. As Mojo is a subset of Python, bringing it to the IOT world might be easy too. But I might need to be corrected here.

Please tell me if that idea is possible based on your information.

If someone has an idea where I can discuss that on the specialized forums, please let me know.

### Motivation

There is only C/C++ that we can use in the modern IOT, RUST will join later (but I found it pretty repetitive regarding the error handling). There is no modern language that everybody can use.

### Description and Requirements

No requirements need more info about the topic.

**Comment by lattner** [comment]
yes, definitely, we want Mojo to go everywhere, and deploying to small devices is part of our design.  One step at a time though :-)

**Comment by Neon22** [comment]
I use micropython extensively in my IOT work (works really well) so there is an existing route which can only be improved moving forward.

**Comment by Mogball** [comment]
Mojo will run on any IOT device that has an LLVM backend. For those that don't, it will prove much more challenging, but it is our ambition that Mojo will run anywhere. Closing this issue for now
