### ISSUE TITLE
[Feature] extraterrestrial languages

### ISSUE THREAD

**Issue by euclas** [modularml/mojo#1764]
They're talking about making it easier for new users...
Well!!!
The original Python had signaling for the beginning and end of program blocks, which were eliminated by something lame like ":" an "identation" system (whose name I disagree with, as it is the old tab, used by old and archaic languages : COBOL, FORTRAN, etc...).
How about at least making it optional between the current model (Using ":" and tab) and "{" and "}" with indentation (you can put the beginning of the sentence in any column without ruining the execution)???
This would bring thousands of programmers of these (evolved) languages ​​to MOJO (including me, who just didn't migrate to Python because I was disgusted by its block notation).
Give us this affection... please.

**Comment by soraros** [comment]
This idea has been brought up, and rejected several times. See rational for rejection in #41 and #438.

And now, for the fun of it:
> ... used by old and archaic languages ...

You can say the same about braces: they are used by old and archaic languages like C and VB. Please also notice the following facts:
- Cobol and Fortran are IS (indentation sensitive) in ways very different from Python; Fortran for instance, does require keyword to delimit the end of control flow.
- There are many fancy or new languages that supports IS, and for good reason, like Haskell, Agda, and F#. Scala add support for indentation sensitivity in V3, and made most braces optional.

All this is to say that the view where braces are always "superior", and language that uses them are somehow more "evolved" is not factual, and possibly biased. Of course, this is not criticism to your personal preference. However, maybe you could give IS languages like Mojo a chance.

**Comment by ematejska** [comment]
Per the comment above, this has discussed in the issues mentioned and closing this one.
