### ISSUE TITLE
[BUG]: Parser crashes when a trait extends Copyable and or Movable and is used as the type of a field in a struct with @value.

### ISSUE THREAD

**Issue by Juicestus** [modularml/mojo#1765]
### Bug description

![Screenshot 2024-02-17 at 8 00 27 AM](https://github.com/modularml/mojo/assets/49132972/0bb39ecf-8382-4380-96ca-0cb6454f0cc3)

I wanted to make a trait `Shape`, which defines an `area` method so my shapes can get their area. 

I also wanted to make a `ShapeContainer`, which is a `@value` struct with one field `shape` of type `Shape`, used for holding the shape. I want this to be a `@value` struct so that I could use it in a `DynamicVector` or such.

In order for `@value` to work on `StructContainer` I must make `Shape` movable and copyable, as the linter told me to do so correctly. So I made my `Shape` trait extend `Copyable` and `Moveable`, which should make the code work.

However the parser crashed and gave the following error.
![Screenshot 2024-02-17 at 7 54 43 AM](https://github.com/modularml/mojo/assets/49132972/f6df4595-58cc-4658-bd8d-e551516d62b2)

### Steps to reproduce

Reproduce with the following code. You must be desperately wanting to find the area of a shape /j.

![Screenshot 2024-02-17 at 7 55 53 AM](https://github.com/modularml/mojo/assets/49132972/7d8e696b-d283-4ed7-ac70-4b28dfd33c6f)

```python
trait Shape(Copyable, Movable):
    fn area(self) -> Float64:
        ...

@value
struct ShapeContainer:
    var shape: Shape
```

### System information

```shell
- What OS did you do install Mojo on ?
Mac OS Sonoma 14.1 (23B2073)

- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.7.0 (af002202)
(upgraded this morning w/ `modular update mojo`)

- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.4.1 (2d8afe15)
(upgraded this morning w/ `brew upgrade modular`)
```

**Comment by Mogball** [comment]
@stumpOS PTAL
