### ISSUE TITLE
[mojo-tooling]: `mojo format` cannot parse multiple lines

### ISSUE THREAD

**Issue by NoEdgeAtLife** [modularml/mojo#1782]
### Issue description

In this section (https://docs.modular.com/mojo/manual/basics.html#blocks-and-statements), there is an example of long string spanning two lines. mojo format fails to format that function.

### Steps to reproduce

test.mojo
```
def print_line():
    long_text = "This is a long line of text that is a lot easier to read if"
                " it is broken up across two lines instead of one long line."
    print(long_text)
```

`mojo format test.mojo`
error: cannot format test.mojo: Cannot parse: 3:0:                 " it is broken up across two lines instead of one long line."

Oh no! 💥 💔 💥

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.4.1
- What OS did you install modular CLI on ?
macOS 13.4.1
```

**Comment by AmaranthineCodices** [comment]
Unfortunately, fixing this requires substantial rework of the formatter's parser. A workaround is to wrap the string in parentheses – this will format correctly.
