### ISSUE TITLE
[Feature Request] docs.modular.com should have REST API for searches

### ISSUE THREAD

**Issue by ksandvik** [modularml/mojo#179]
## Request

Just now the docs.modular.com including the Mojo documentation does not have a direct REST API for searches/queries

### Motivation

This makes it possible for various tools to do direct lookups without first going to the web site, for example using Alfred and similar hot key solutions.

### Description and Requirements

Provide a REST API to the modular docs web site, similar to ex: https://doc.rust-lang.org/std/fs/?search={query} where {query} is the query string.

**Comment by albertocavalcante** [comment]
Is this being looked at?

**Comment by scottamain** [comment]
Sorry for the silence @albertocavalcante. This has not been on our radar, but we're building a new website with Docusaurus, and I believe it provides the functionality you want. For example: https://docusaurus.io/search?q=foo
So, stay tuned. :)

**Comment by scottamain** [comment]
@albertocavalcante I believe this works now with the new website we launched a few months ago. Please reopen if it's not working as expected.
