### ISSUE TITLE
[BUG]: Mojo Repl crashes after two tab presses

### ISSUE THREAD

**Issue by TrevorMassey** [modularml/mojo#1796]
### Bug description

Mojo Repl fails after pressing any whitespace followed by a tab

### Steps to reproduce

Sample:

```
Welcome to Mojo! 🔥

Expressions are delimited by a blank line.
Type `:quit` to exit the REPL and `:mojo help` for further assistance.

  1>  /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_vector.h:1060: std::vector::const_reference std::vector<lldb_private::Args::ArgEntry>::operator[](std::vector::size_type) const [_Tp = lldb_private::Args::ArgEntry, _Alloc = std::allocator<lldb_private::Args::ArgEntry>]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
[19001:19001:20240222,232147.505565:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[19001:19001:20240222,232147.505721:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
Aborted
```

I pressed spacebar, then tab, then it crashed.

Same issue occurs regardless of typing two tabs, or space then a tab, or 10 spaces then a tab, or if I write a function definition, which causes an auto-indent, then pressing tab.

Does NOT occur if the line contains any character other than whitespace. In this case, pressing tab causes autocomplete options to pop up, and does not crash.

Does NOT occur regardless of how many spaces I type.  Only tabs cause the crash.

I suspect its a bug in autocomplete. 

### System information

```shell
- What OS did you do install Mojo on ?
WSL2 with Ubuntu 22.04.2 LTS
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.7.0 (af002202)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.5.0 (47924ae4)
```

**Comment by Sharktheone** [comment]
Can confirm, but I get a different error, it fails to read a directory.

```
  1>  /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_vector.h:1060: std::vector::const_reference std::vector<lldb_private::Args::ArgEntry>::operator[](std::vector::size_type) const [_Tp = lldb_private::Args::ArgEntry, _Alloc = std::allocator<lldb_private::Args::ArgEntry>]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
[263032:263033:20240223,083737.339241:ERROR directory_reader_posix.cc:42] opendir /home/shark/.modular/crashdb/attachments/8b064724-175d-4793-a8d9-037585255ccd: No such file or directory (2)
[1]    263019 IOT instruction (core dumped)  mojo
```

**Comment by River707** [comment]
Thanks for reporting!

@walter-erquinigo This looks like a bug in LLDB, it crashes before we even get to our REPL code AFAICT, wonder if it just isn't prepared to handle empty lines?

**Comment by walter-erquinigo** [comment]
Thanks for the report!
I was able to repro this on Linux. It works on MAC though. I'll try to get a fix soon.

**Comment by walter-erquinigo** [comment]
The fix has landed in upstream LLDB and will be available in a future release of our SDK.
Cheers

**Comment by coderNODEZ** [comment]
this was supposed to be fun on a Saturday. Mojo is junk
I tried installing on Debian 12 and Ubuntu. When did it become OK for software installtions to be horrible? I get that good projects require debugging but this is junk!
