### ISSUE TITLE
[BUG]: `register_passable` generates phantom trait bound overload

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1805]
### Bug description

As title. If either `register_passable` or the `Hashable` conformance is removed, the error goes away.

### Steps to reproduce

```mojo
@register_passable
struct S(Hashable):
  fn __hash__(self) -> Int:
    return 0

fn main():
  S.__hash__  # error: cannot form a reference to overloaded declaration of '__hash__'
```

### System information

```shell
Mojo 0.7.1 on Docker, Intel Mac.
```

**Comment by RtyLiu** [comment]
I do not understand, what are you trying here.  @register_passable needs __init__ and you need instance:
```mojo
@register_passable
struct S(Hashable):
    fn __init__() -> Self:
        return Self{}    
    fn __hash__(self) -> Int:
        return 0

fn main():
    print(S().__hash__())
```

**Comment by soraros** [comment]
@RtyLiu This is clearly a reduced repro, and regardless of what I was trying to do, my code should work.
Let's say we generate our constructor etc. with `@value`, and add another function `fn f(self) -> Int`. The compiler has no problem with `S.f` (which can be passed to a higher order function), so how and why is `S.__hash__` any different?

**Comment by RtyLiu** [comment]
@soraros S.__hash__  is like you triyng to call static function. You need instance.  __hash__(self)  has self as parameter.

**Comment by soraros** [comment]
@RtyLiu You are just explaining things people know (`S.__hash__` is of type `fn(S) -> Int`, rather irrelevant), but doesn't explain what I see. Needing an instance is just irrelevant. 
I will write the **exact** code I indicated in my last response:
```mojo
@value
@register_passable
struct S(Hashable):
  fn __hash__(self) -> Int: return 0
  fn f(self) -> Int: return 0

fn main():
  S.__hash__  # error
  S.f         # works just fine
```
If you even bothered to try the code snippet I provided, you will see something strange: the two overloads, according to LSP, has the exact same signature.

**Comment by RtyLiu** [comment]
Sorry. You are right here.

**Comment by soraros** [comment]
@RtyLiu Yea, no problem! Thank you for trying to help. I'm sorry my tune wasn't the best.

**Comment by RtyLiu** [comment]
Hi @soraros, I think the compiler sees two definitions, one from Hashable and one for S. If we say which definition we will, it should work:
`    var q: fn(S) -> Int =  S.__hash__`

**Comment by soraros** [comment]
If that makes sense, `@register_passable` shouldn't play a role here. However, if you leave only the `@value`, the overload is somehow not generated.
Even given the explicit type annotation we sill couldn't tell which overload is picked for they have the same signature (which itself contradicts all sorts of rules).

**Comment by RtyLiu** [comment]
@soraros Yep, again right :) I would like to see the code behind `@register_passable`
