### ISSUE TITLE
[Modular CLI]: Cannot auth - it just hangs

### ISSUE THREAD

**Issue by andreif** [modularml/mojo#1806]
### Issue description

I cannot complete modular auth after installing CLI on Ubuntu 20.04.

### Steps to reproduce

I am using M1 MBP with Docker and the following Dockerfile:
```dockerfile
FROM ubuntu:20.04

RUN apt update && apt install -y \
    build-essential \
    curl

ENV DEFAULT_TZ=Europe/Stockholm

RUN curl -1sLf "https://dl.modular.com/public/installer/gpg.0E4925737A3895AD.key" | \
    gpg --dearmor     >> /usr/share/keyrings/modular-installer-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/modular-installer-archive-keyring.gpg] https://dl.modular.com/public/installer/deb/ubuntu focal main" >> /etc/apt/sources.list && \
    apt update && DEBIAN_FRONTEND=noninteractive apt install -y modular
```
I then build and run the container:
```sh
docker build --platform=linux/amd64 --tag=mojo .
docker run   --platform=linux/amd64 -it --rm mojo
```
and in the shell I try to either provide token from my account,
```sh
$ modular auth mut_abc....
```
or use sign-in URL and authorising via my Modular account
```sh
$ modular auth 
# Please visit this URL in your browser: https://developer.modular.com/device?userCode=ABCD-1234
# Waiting for confirmation...
```
both hanging without any message. 

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`

> modular 0.5.0 (47924ae4)

- What OS did you install modular CLI on ?

> macOS Sonoma 14.3 (23D56)
> Docker Desktop 4.27.2 (137060)
```

**Comment by andreif** [comment]
I am not using Homebrew -- just trying to make a Docker image. 
It still hangs after installing modular cli via `apt install modular` and running `modular auth`.

**Comment by ematejska** [comment]
Thank you for trying out Mojo.  The installation experience has significantly changed and we're closing out all the old issues with the old installer.  To try out our new installation experience using "magic", please see: https://docs.modular.com/mojo/manual/get-started.
