### ISSUE TITLE
[Feature Request] CollectionElement Buffer Type

### ISSUE THREAD

**Issue by lsh** [modularml/mojo#1809]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

A struct defined similar to the following would be useful:
```
struct Buffer[inferred is_mutable: __mlir_type.i1, lifetime: AnyLifetime[T].lifetime, T: CollectionElement]:
    var _ptr: Reference[T, is_mutable, lifetime.type]
    var len: Int
```

### What is your motivation for this change?

Right now there is no way to have a non owning buffer of a `CollectionElement` type. Now that lifetimes are starting to come into place, being able to call, eg, `__refitem__(slice: Slice)` on a `DynamicVector` or a `StaticTuple` to return a non owning buffer type is important for rounding out general APIs.

### Any other details?

The name `Buffer` is already taken, however I think the current `Buffer` struct should be renamed to `DTypeBuffer`. Day to day users are more likely to want a non owning buffer than the low level `DType` based struct most of the time.

**Comment by JoeLoser** [comment]
@lsh safe to close this now in favor of your recent Span work?

**Comment by lsh** [comment]
Yep!
