### ISSUE TITLE
[BUG]: SIGABRT when trying to print tensor data

### ISSUE THREAD

**Issue by pumetu** [modularml/mojo#1810]
### Bug description

I tried to print the data of a tensor after initializing it, not sure if this is the intended behavior

mojo: /\__w/modular/modular/KGEN/lib/MojoParser/OverloadFitness.cpp:768: static std::pair M::KGEN::LIT::OverloadFitness::checkOneOperand(ASTExprAnd, M::KGEN::ValueInputConvention, M::KGEN::LIT::ASTType, size_t &, size_t &, bool &, bool, llvm::SMLoc, M::KGEN::LIT::ASTDecl &, M::KGEN::LIT::SharedState &): Assertion \`argVal && "we handled ORValue above"' failed.
Please submit a bug report to [https://github.com/modularml/mojo/issues](https://github.com/modularml/mojo/issues) and include the crash backtrace along with all the relevant source codes.
Stack dump:
0. Program arguments: mojo hanabi/graph.mojo

1. Crash resolving decl body at loc("/home/pumetu/hanabi/hanabi/graph.mojo":21:1)

   > > fn main():
   > >        ^.........
   > > let spec = TensorSpec(DType.float32, 4, 4)
   > > let t1 = Tensor[DType.float32](spec)
   > > print(t1.data)
   > >        ..................<
2. Crash parsing statement at loc("/home/pumetu/hanabi/hanabi/graph.mojo":24:5)

   > > print(t1.data)
   > >            ^.............<
   > > Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
   > > 0 mojo 0x000055c52c7ab337
   > > 1 mojo 0x000055c52c7a8f0e
   > > 2 mojo 0x000055c52c7aba0f
   > > 3 libc.so.6 0x00007f93ce042520
   > > 4 libc.so.6 0x00007f93ce0969fc pthread_kill + 300
   > > 5 libc.so.6 0x00007f93ce042476 raise + 22
   > > 6 libc.so.6 0x00007f93ce0287f3 abort + 211
   > > 7 libc.so.6 0x00007f93ce02871b
   > > 8 libc.so.6 0x00007f93ce039e96
   > > 9 mojo 0x000055c52cca73c2
   > > 10 mojo 0x000055c52ccaa241
   > > 11 mojo 0x000055c52cca917a
   > > 12 mojo 0x000055c52cc9e105
   > > 13 mojo 0x000055c52cc456bd
   > > 14 mojo 0x000055c52cca769d
   > > 15 mojo 0x000055c52ccaa241
   > > 16 mojo 0x000055c52cca917a
   > > 17 mojo 0x000055c52cc9e105
   > > 18 mojo 0x000055c52cca1a37
   > > 19 mojo 0x000055c52cc55eef
   > > 20 mojo 0x000055c52cc486a9
   > > 21 mojo 0x000055c52cc7ebba
   > > 22 mojo 0x000055c52cc7bfa8
   > > 23 mojo 0x000055c52cc7be46
   > > 24 mojo 0x000055c52cc1d43c
   > > 25 mojo 0x000055c52cc35c06
   > > 26 mojo 0x000055c52cc362c8
   > > 27 mojo 0x000055c52cbdd614
   > > 28 mojo 0x000055c52cbdd980
   > > 29 mojo 0x000055c52c773b1f
   > > 30 mojo 0x000055c52c760f1b
   > > 31 mojo 0x000055c52c772f60
   > > 32 mojo 0x000055c52c75a6c2
   > > 33 libc.so.6 0x00007f93ce029d90
   > > 34 libc.so.6 0x00007f93ce029e40 \__libc_start_main + 128
   > > 35 mojo 0x000055c52c759c9e
   > > fish: Job 1, 'mojo hanabi/graph.mojo' terminated by signal SIGABRT (Abort)

### Steps to reproduce

```
 fn main():
     let spec = TensorSpec(DType.float32, 4, 4)
     let t1 = Tensor[DType.float32](spec)
     print(t1.data)
```

### System information

```shell
- What OS did you do install Mojo on ? Ubuntu 22.04
- Provide version information for Mojo by pasting the output of `mojo -v` mojo 0.7.1 (af002202)
- Provide Modular CLI version by pasting the output of `modular -v` modular 0.4.1 (2d8afe15)
```

**Comment by RtyLiu** [comment]
It crashes the parser in VS Code too.
If you want to print it use print(t1) or use the index: t1[Index(x,y)]

**Comment by gryznar** [comment]
Crash in not unsafe code is not intended behavior, no matter what it is referring to :)
