### ISSUE TITLE
[Feature Request] Implement `Int8` and unsigned versions of `Int` (`UInt8`, `UInt16`, `UInt32` and `UInt64`)

### ISSUE THREAD

**Issue by gryznar** [modularml/mojo#1815]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

This looks like an oversight, but there is no implementation for `Int8` and for unsigned versions of `Int` like. For a sake of completeness, I would like to support them.

### What is your motivation for this change?

Greater control over memory taken and simplicity

**Comment by gabrieldemarmiesse** [comment]
Can you provide a code example of what you would like? I can run 
```python
def main() -> None:    
    var a: Int8 = 1
    var b: UInt8 = 2
    var c: Int16 = 3
    var d: UInt16 = 4
    var e: Int32 = 5
    var f: UInt32 = 6
    var g: Int64 = 7
    var h: UInt64 = 8
    var i: Int = 9
    print(a)
    print(b)
    print(c)
    print(d)
    print(e)
    print(f)
    print(g)
    print(h)
    print(i)
```
So i'm not sure what additional type is needed here

**Comment by gryznar** [comment]
Oh, I've looked at the docs. There are incomplete!
