### ISSUE TITLE
[BUG]: Can't create a function that returns two strings

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [modularml/mojo#1817]
### Bug description

As the title says. This is quite limiting.

### Steps to reproduce

```python
fn return_two_strings() -> Tuple[String, String]:
    return String("hello"), String("world")

def main():
    var a: String
    var b: String
    a, b = return_two_strings()
```

```
$ mojo trying_stuff.mojo
/projects/open_source/mojo-stdlib-extensions/trying_stuff.mojo:7:6: error: invalid call to 'get': result cannot bind AnyRegType type to memory-only type 'String'
    a, b = return_two_strings()
    ~^~~
/projects/open_source/mojo-stdlib-extensions/trying_stuff.mojo:1:1: note: function declared here
fn return_two_strings() -> Tuple[String, String]:
^
mojo: error: failed to parse the provided Mojo
```

### System information

```shell
ubuntu 22.04
modular -v
modular 0.4.1 (2d8afe15)
mojo -v
mojo 0.7.1 (af002202)
```

Edit: I tried it with Mojo 2024.1.0 and the bug is still there.

**Comment by RtyLiu** [comment]
Only comment :)
I thought, that the reason here is the get method of Tuple (String is not AnyRegType):
fn get[i: Int, T: AnyRegType](self: Self) -> T

But it is workung with StringLiteral, which also have not AnyRegType (Or at least is not in docs)

**Comment by laszlokindrat** [comment]
@stumpOS Could you PTAL?

**Comment by laszlokindrat** [comment]
Thanks for opening the ticket! There have been several improvements to related areas recently, and the problem in the OP no longer reproduces on head of main. Please continue to open issues if you run into problems!

**Comment by lattner** [comment]
Yep, this is fixed in the next release
