### ISSUE TITLE
[Modular CLI]: Ubuntu 22.04 apt repository problem

### ISSUE THREAD

**Issue by emccreigh** [modularml/mojo#1822]
### Issue description

A month ago I followed the instructions to install the modular CLI on my Ubuntu 22.04 workstation, and the install seemed to work correctly. Then a few days ago when doing an "apt update" on that system, I began seeing the error message "Skipping architecture of configured file 'main/binary-i386/Packages' as repository 'https//dl.modular.com/public/installer/deb/ubuntu jammy InRelease' doesn't support architecture 'i386'". During the "apt update" apparently apt downloaded 2971 bytes from that repository, and the problem was noticed after that. Can somebody explain what's changed, why, and how to recover?

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### Version Info

```shell
- modular 0.5.0 (47924ae4)
- Ubuntu Linux 22.04 (64-bit architecture)
```

**Comment by emccreigh** [comment]
For what it's worth, if I do an "apt policy modular", I don't see the i386 architecture mentioned; I only see the amd64 architecture, for all dozen or so entries in the modular version table.

**Comment by smuniraj2018** [comment]
Can you update to our latest client 0.7.1 and let us know if you still see this issue?

**Comment by ematejska** [comment]
Thank you for trying out Mojo.  The installation experience has significantly changed and we're closing out all the old issues with the old installer.  To try out our new installation experience using "magic", please see: https://docs.modular.com/mojo/manual/get-started.
