### ISSUE TITLE
[BUG]: reduce_min/max don't respect the size fully

### ISSUE THREAD

**Issue by ehsanmok** [modularml/mojo#1826]
### Bug description

```
var b = SIMD[DType.float32, 8](1,2,3,4,3,2,1,0)

print(b.reduce_max[1]()) 
print(b.reduce_max[2]()) 
print(b.reduce_max[4]())
print(b.reduce_max[8]())
print(b.reduce_max[16]())
```

outputs

```
4.0
[3.0, 4.0]
[3.0, 2.0, 3.0, 4.0]
[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0]
[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0]
```

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by ehsanmok** [comment]
Also #1247

**Comment by elhigu** [comment]
Thanks for making issue for this! I would not expect that this actually matters in this case, but the environment was:

Ubuntu 22.04 ssh shell running in docker container
Installed with: curl https://get.modular.com | sh - && modular auth mut_3689ad8dd2fe4fd8ac11563272f111 && modular install mojo
bigbox:~# mojo --version
mojo 0.7.1 (af002202)
bigbox:~# modular -v
modular 0.5.0 (47924ae4)

Same kind of  unexpected behavior was also observed for `.reduce_min`.

**Comment by ehsanmok** [comment]
This is fixed in the next release!

**Comment by RtyLiu** [comment]
I am not an AI man and do not know what is expected as result, but with mojo 24.1.0 (c176f84d) the result is the same:

```
4.0
[3.0, 4.0]
[3.0, 2.0, 3.0, 4.0]
[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0]
[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0]
```

Nothing changed. Why is the ticket closed?
