### ISSUE TITLE
[Feature Request] Improvements on print() function

### ISSUE THREAD

**Issue by locnnil** [modularml/mojo#185]
## Request

It would be nice if `print()` function have the same formaters as Python version does.

Like:  
- The hability to chose the terminator instead of jump a line:

```python
# Print without a newline
print('Hello', end='')
print('World') 
```

- Print multiple variables *and* specify the separator:
```python
print("Hello", "how are you?", sep="---")
```

- Write to a file instead of the standard output:

```python
import sys

print('This message will be displayed on the screen.')

original_stdout = sys.stdout # Save a reference to the original standard output

with open('filename.txt', 'w') as f:
    sys.stdout = f # Change the standard output to the file we created.
    print('This message will be written to a file.')
    sys.stdout = original_stdout # Reset the standard output to its original value
```

-  specifying if the output is flushed or buffered.

```python
# A countdown example using flushed output instead of buffered 
from time import sleep

for second in range(3, 0, -1):
    print(second, end=" ", flush=True)
    sleep(1)
print("Go!")
```

### Motivation

As a "Superset of Python" it's interesting to implement the basic functionality of the basic components of Python language. Specially one of the most used function "print()"

### Description and Requirements

Parameter input that `print()` function should accept:

<html>
<body>

Parameter | Description
-- | --
object(s) | Any object, and as many as you like. Will be converted to string before printed
sep='separator' | Optional. Specify how to separate the objects, if there is more than one. Default is ' '
end='end' | Optional. Specify what to print at the end. Default is '\n' (line feed)
file | Optional. An object with a write method. Default is sys.stdout
flush | Optional. A Boolean, specifying if the output is flushed (True) or buffered (False). Default is False

</body>
</html>

**Comment by Mogball** [comment]
We will have to wait until keyword arguments are wired up... but thanks for the suggestionS!
