### ISSUE TITLE
[BUG]: cannot construct 'DynamicVector[Int]' from 'IntLiteral' value in 'var' initializer

### ISSUE THREAD

**Issue by friedrixk** [modularml/mojo#1869]
### Bug description

When trying to construct a DynamicVector like this

```
from collections.vector import DynamicVector

fn main() raises: 
    var vec = DynamicVector[Int](8)
```

the Mojo Language Extension gives me this error: cannot construct 'DynamicVector[Int]' from 'IntLiteral' value in 'var' initializer.

This is the example from [mojodojo](https://mojodojo.dev/guides/std/Vector/DynamicVector.html) and therefore I expected it to work.

### Steps to reproduce

Just run the above code.

### System information

```shell
I am using

- VSCode Dev Container with Ubuntu 22.04.3 LTS

- mojo 24.1.0 (55ec12d6)

- modular 0.5.1 (1b608e3d)
```

**Comment by gujuriu** [comment]
Hi @friedrixk,
try `var vec = DynamicVector[Int](capacity=8)`
mojodojo last update seems to be ~[7 months ago](https://github.com/mojodojodev/mojodojo.dev/commits/main/)
also, I don't think you need to `from collections.vector import DynamicVector` anymore

**Comment by friedrixk** [comment]
> Hi @friedrixk, try `var vec = DynamicVector[Int](capacity=8)` mojodojo last update seems to be ~[7 months ago](https://github.com/mojodojodev/mojodojo.dev/commits/main/) also, I don't think you need to `from collections.vector import DynamicVector` anymore

Great, this is working! Thanks @gujuriu!
