### ISSUE TITLE
AMD CPU utilisation with parallelize not using 50% of CPU usage up to 16 cores out of 32 cores available

### ISSUE THREAD

**Issue by iwoogy** [modularml/mojo#1877]
Hello,

I've been experiencing an issue with CPU utilization on an AMD 7950X, which has 32 threads. Despite the system's capabilities, I'm only able to utilize up to 16 cores, resulting in a maximum of 50% CPU usage. This limitation is significantly impacting the performance of my applications, and I am curious if this behavior is expected or if there might be a configuration issue on my end.

## Environment:

CPU: AMD 7950X
Operating System: Ubuntu 22.04.4 LTS

## Steps to Reproduce:
Run the matrix multiplication notebook with parallelize.

## Expected Behavior:
I would expect to be able to utilize all 32 threads available on the AMD 7950X, allowing for up to 100% CPU usage for optimized performance.

## Actual Behavior:
The system is only utilizing up to 16 cores, restricting CPU usage to a maximum of 50%.

## Questions:

Is this limitation expected due to the pricing plan or product tier I am currently on?
If it's a configuration issue, could you provide guidance or documentation on how to enable full utilization of all 32 threads?
Are there any workarounds or settings adjustments that you recommend to overcome this limitation?

I appreciate your time and assistance in addressing this issue. Please let me know if you need any more information or specific logs to help diagnose the problem.

Thank you.

**Comment by Sharktheone** [comment]
Looks like an issue with Hyperthreading, can you maybe post some code to test this?

**Comment by iwoogy** [comment]
I used the code from the notebook in the documentation.

```mojo
from memory import memset_zero
from random import rand
from sys import argv
from time import now
from algorithm import vectorize
from algorithm import parallelize

alias type = DType.float32
alias nelts = simdwidthof[DType.float32]()

struct Matrix:
    var data: DTypePointer[type]
    var rows: Int
    var cols: Int

    # Initialize zeroeing all values
    fn __init__(inout self, rows: Int, cols: Int):
        self.data = DTypePointer[type].alloc(rows * cols)
        memset_zero(self.data, rows * cols)
        self.rows = rows
        self.cols = cols

    # Initialize taking a pointer, don't set any elements
    fn __init__(inout self, rows: Int, cols: Int, data: DTypePointer[DType.float32]):
        self.data = data
        self.rows = rows
        self.cols = cols

    ## Initialize with random values
    @staticmethod
    fn rand(rows: Int, cols: Int) -> Self:
        let data = DTypePointer[type].alloc(rows * cols)
        rand(data, rows * cols)
        return Self(rows, cols, data)

    fn __getitem__(self, y: Int, x: Int) -> Float32:
        return self.load[1](y, x)

    fn __setitem__(inout self, y: Int, x: Int, val: Float32):
        return self.store[1](y, x, val)

    fn load[nelts: Int](self, y: Int, x: Int) -> SIMD[DType.float32, nelts]:
        return self.data.simd_load[nelts](y * self.cols + x)

    fn store[nelts: Int](self, y: Int, x: Int, val: SIMD[DType.float32, nelts]):
        return self.data.simd_store[nelts](y * self.cols + x, val)


fn matmul_parallelized(inout C: Matrix, A: Matrix, B: Matrix):
    @parameter
    fn calc_row(m: Int):
        for k in range(A.cols):
            @parameter
            fn dot[nelts : Int](n : Int):
                C.store[nelts](m,n, C.load[nelts](m,n) + A[m,k] * B.load[nelts](k,n))
            vectorize[nelts, dot](C.cols)
    parallelize[calc_row](C.rows, C.rows)


fn main() raises:
    print("Start execution")
    let execution_type = argv()[1]
    let time_start_at = now()

    let dimensions = 16*1024
    let A: Matrix = Matrix(dimensions, dimensions, Matrix.rand(dimensions, dimensions).data)
    let B: Matrix = Matrix(dimensions, dimensions, Matrix.rand(dimensions, dimensions).data)
    var C: Matrix = Matrix(dimensions, dimensions)

    matmul_parallelized(C, A, B)

    let time_end_at = now()
    let execution_duration = (time_end_at-time_start_at)/1e9
    print("execution_duration", execution_duration)    
```

**Comment by keithrbennett** [comment]
Are you sure that full capacity of your CPU would be reported by `top` as 3200% and not 1600%? I just asked a few AI tools to tell me whether `top` reporting 1600% means all or half of the CPU is being used, and got conflicting answers. I've done a little research on cores and threads and while I don't understand it completely, I think threads are virtual and the real computing capacity of the CPU is measured as 100% * core count. As another data point, https://unix.stackexchange.com/questions/29310/why-does-top-report-the-incorrect-cpu-usage/29352#29352 says "Try running a process with 4 threads that can eat up 4 CPU cores, you will find it using 400% CPU." The following comment also might be helpful: "If you want to obtain a percentage of the total CPU capabilities (i.e. when the sum of the possible CPU usage adds up to 100% and not cpu_cores_number * 100%), just toggle the 'Irix' mode by pressing I.

**Comment by keithrbennett** [comment]
I also got this advice from someone else:

----

`cat /proc/cpu` and see how many it thinks it has. (also that's why I prefer htop :)

----

`htop` will show the CPU's and their workloads, e.g. this on my Mac:

<img width="1702" alt="image" src="https://github.com/modularml/mojo/assets/28410/bfb96481-98fe-4100-80e3-0889952162f5">

**Comment by iwoogy** [comment]
I've taken the guidance from a StackExchange discussion and disabled Irix mode, which has allowed me to observe CPU usage percentages. However, this adjustment has revealed a more pronounced issue. When running a more complex Mojo application, CPU utilization remains around 30% across approximately 10 threads. With Irix mode enabled, this figure would appear as 1000%.

To manage concurrent execution, I'm employing Go coroutines, limiting operation to two Mojo programs simultaneously.

![CleanShot 2567-03-05 at 15 25 01@2x](https://github.com/modularml/mojo/assets/479162/1255d0c0-7a67-4342-b003-6a8a994aa38b)



Contrastingly, on my Mac equipped with an M2 Pro chip and 10 cores, the same application fully utilizes the CPU, reaching 100% global CPU usage.


![CleanShot 2567-03-05 at 15 31 49@2x](https://github.com/modularml/mojo/assets/479162/9f5cf057-9c93-45ba-96ef-795d7f487726)

**Comment by yeison** [comment]
I encountered the same issue running the same code on my AMD Ryzen 7900X.   Mojo is not utilizing the hyper-threading on the CPU.

```mojo
# Use the above tile function to perform tiled matmul.
fn matmul_tiled_parallelized(C: Matrix, A: Matrix, B: Matrix):
    @parameter
    fn calc_row(m: Int):
        @parameter
        fn calc_tile[tile_x: Int, tile_y: Int](x: Int, y: Int):
            for k in range(y, y + tile_y):
                @parameter
                fn dot[nelts: Int](n: Int):
                    C.store(m, n + x, C.load[nelts](m, n + x) + A[m, k] * B.load[nelts](k, n + x))
                vectorize[dot, nelts, size = tile_x]()

        # We hardcode the tile factor to be 4.
        alias tile_size = 4
        tile[calc_tile, nelts * tile_size, tile_size](A.cols, C.cols)

    parallelize[calc_row](C.rows, C.rows)
```

<img width="1512" alt="Screenshot 2024-03-18 at 6 19 32 AM" src="https://github.com/modularml/mojo/assets/106876/6b39e08d-f1e4-4f2f-9e80-283b8560cc8c">

**Comment by yeison** [comment]
I'm encountering the same issue running the same code on my AMD Ryzen 7800X.

```mojo
# Use the above tile function to perform tiled matmul.
fn matmul_tiled_parallelized(C: Matrix, A: Matrix, B: Matrix):
    @parameter
    fn calc_row(m: Int):
        @parameter
        fn calc_tile[tile_x: Int, tile_y: Int](x: Int, y: Int):
            for k in range(y, y + tile_y):
                @parameter
                fn dot[nelts: Int](n: Int):
                    C.store(m, n + x, C.load[nelts](m, n + x) + A[m, k] * B.load[nelts](k, n + x))
                vectorize[dot, nelts, size = tile_x]()

        # We hardcode the tile factor to be 4.
        alias tile_size = 4
        tile[calc_tile, nelts * tile_size, tile_size](A.cols, C.cols)

    parallelize[calc_row](C.rows, C.rows)
```

<img width="1512" alt="Screenshot 2024-03-18 at 6 19 32 AM" src="https://github.com/modularml/mojo/assets/106876/bd264f07-ff94-4b2c-a532-f330042c92f1">

**Comment by yeison** [comment]
Test

**Comment by yeison** [comment]
There is a possibility that this is not a bug.   The reason I say that is because hyper-threading is an optimization to utilize what would otherwise be an idle core that is waiting for its instructions from the decode phase.    Is it possible that by defining the simwidth mojo is actually efficiently using the 12 cores to where we don't require hyper-threading?

```code
alias nelts = simdwidthof[DType.float32]() * 2
```
