### ISSUE TITLE
no version information available (required by modular)

### ISSUE THREAD

**Issue by wswsmao** [modularml/mojo#1878]
Hi, I want to install Mojo SDK in distro. I get a error report:
```
modular install mojo
modular: /lib64/libtinfo.so.6: no version information available (required by modular)
modular: error: please run `modular auth` before attempting to install or update a package

# I can find this so in our repo
dnf prov "*libtinfo.so.6*"
ncurses-libs-6.4-2.ocs23.x86_64 : Ncurses libraries
Repo        : BaseOS
Matched from:
Provide    : libtinfo.so.6()(64bit)

ncurses-libs-6.4-3.ocs23.x86_64 : Ncurses libraries
Repo        : @System
Matched from:
Provide    : libtinfo.so.6()(64bit)

ncurses-libs-6.4-3.ocs23.x86_64 : Ncurses libraries
Repo        : BaseOS
Matched from:
Provide    : libtinfo.so.6()(64bit)

# this so has been installed
ll /lib64/libtinfo.so.6
lrwxrwxrwx. 1 root root 15 Sep 19 21:18 /lib64/libtinfo.so.6 -> libtinfo.so.6.4

rpm -qf /lib64/libtinfo.so.6
ncurses-libs-6.4-3.ocs23.x86_64
```

**Comment by junweizeng** [comment]
Hi @wswsmao,

What OS did you install modular CLI/mojo on?

Here's an issue https://github.com/modularml/mojo/issues/564 that maybe related.

**Comment by newnativeabq** [comment]
Same with Fedora release 39 (Thirty Nine)

```bash
dnf whatprovides */libc.so.6
modular-installer                                                                          1.0 kB/s | 659  B     00:00    
modular-installer                                                                          5.9 kB/s | 1.3 kB     00:00    
Importing GPG key 0x7A3895AD:
 Userid     : "Cloudsmith Package (modular/installer) <support@cloudsmith.io>"
 Fingerprint: 0BAB A1B0 518C 87CF F4CC 3740 0E49 2573 7A38 95AD
 From       : https://dl.modular.com/public/installer/gpg.0E4925737A3895AD.key
```

modular: /lib64/libtinfo.so.6: no version information available (required by modular)

**Comment by junweizeng** [comment]
> Same with Fedora release 39 (Thirty Nine)
> 
> ```shell
> dnf whatprovides */libc.so.6
> modular-installer                                                                          1.0 kB/s | 659  B     00:00    
> modular-installer                                                                          5.9 kB/s | 1.3 kB     00:00    
> Importing GPG key 0x7A3895AD:
>  Userid     : "Cloudsmith Package (modular/installer) <support@cloudsmith.io>"
>  Fingerprint: 0BAB A1B0 518C 87CF F4CC 3740 0E49 2573 7A38 95AD
>  From       : https://dl.modular.com/public/installer/gpg.0E4925737A3895AD.key
> ```
> 
> modular: /lib64/libtinfo.so.6: no version information available (required by modular)

This seems a dup of https://github.com/modularml/mojo/issues/564#issuecomment-1710589396

**Comment by hidara2000** [comment]
This worked for me on Fedora 40

https://github.com/modularml/mojo/issues/855#issuecomment-2116834443

**Comment by jackos** [comment]
Thanks @hidara2000 there is also a workaround here: https://github.com/makism/mojo-on-fedora40

Closing in favor of the feature request: https://github.com/modularml/mojo/issues/2267
