### ISSUE TITLE
[BUG]: Can't transfer ownership of a value if using operators like `+`

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [modularml/mojo#1883]
### Bug description

When implementing `__add__` I can use `owned self` to gain some speed and not have to copy some values. The issue is that I can't make use of the transer operator `^` when using `+`, I can only use the transfer operator when calling `__add__` explicitely, which isn't very idiomatic.

Ownership is quite new to me, so I could be wrong, take this bug report with a grain of salt.

Possibly related, but I'm not sure: https://github.com/modularml/mojo/issues/1279

### Steps to reproduce

```python
@value
struct bytes:
    var _vector: DynamicVector[UInt8]

    fn __init__(inout self, size: Int):
        self._vector = DynamicVector[UInt8]()
        for i in range(size):
            self._vector.append(0)
    
    fn __add__(owned self, other: bytes) -> bytes:
        self._vector.extend(other._vector)
        return self


def main():
    a = bytes(5)
    b = bytes(10)
    c = a.__add__(b)   # works, uses a copy of a
    c = a + b          # works, uses a copy of a
    c = a^.__add__(b)  # works, reuse a, it's faster
    c = a^ + b         # doesn't work, the syntax isn't accepted :(
```

```
/projects/open_source/mojo-stdlib-extensions/trying_stuff2.mojo:21:12: error: 'bytes' does not implement the '__pos__' method
    c = a^ + b 
           ^ ~
mojo: error: failed to parse the provided Mojo
```

### System information

```shell
ubuntu 22.04 in WSL2
modular 0.5.0 (47924ae4)
mojo 24.1.0 (55ec12d6)
```

**Comment by soraros** [comment]
The problem seems to be that `a^ + b` is parsed as `a ^ (+b)` hence the error "`__pos__` not implemented". The fix would be to write `(a^) + b`.

**Comment by gabrieldemarmiesse** [comment]
Well I don't think I would have found the parenthesis solution by myself, thanks!

**Comment by gabrieldemarmiesse** [comment]
Closing as there is not much here to fix. We could always rename the operator but that's not the purpose of this issue.
