### ISSUE TITLE
[BUG]: Slowdown in Mojo REPL

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1891]
### Bug description

I'm experiencing random slowdown while running very simple code in the REPL.

### Steps to reproduce

It doesn't reproduce every time, but alternating the input `var a = 1`, `var a = 2 / 1` and `var a = 2 // 1` tend to trigger the slowdown.

### System information

```shell
Mojo 24.1 on Docker, Intel Mac
```

**Comment by walter-erquinigo** [comment]
Thanks for the report!
We're aware that there might be some slowdowns on Intel HW and we are actively working on them.
