### ISSUE TITLE
[Feature Request]: Do not crash if an imported module isn't installed as long as it's unused

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [modularml/mojo#1895]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

```python
import module_which_does_not_exist

def do():
    module_which_does_not_exist.something()

def main():
    print("hello world")
```
```
$ mojo trying_stuff3.mojo
trying_stuff3.mojo:1:8: error: unable to locate module 'module_which_does_not_exist'
import module_which_does_not_exist
       ^
mojo: error: failed to parse the provided Mojo
```

I believe the above code should not throw any error, unless a flag was used, like `mojo --compile-all`.

### What is your motivation for this change?

It often happens in library development that a module is optional. As such it should be possible to compile a module even if some imported modules are not present as long as the said module is not used and reachable from `main()`.

I don't feel strongly about this as it may not be possible from a technical point of view, but it's a very common use case (optional dependencies are common in python, and the way it's handled isn't always graceful).
With this behavior, we could have a no fail if the optional module isn't used and a fast-fail if it's used (will fail at compile time). In python, the `try-except ImportError:` mean that the failure will happen at runtime and not at compile time.

**Comment by laszlokindrat** [comment]
The team discussed allowing imports to silently fail if the imported module is missing but never used. We think the current behavior is correct: the compiler should fail if an imported module is missing. Users should be explicit about conditional imports just like they are in Python. As the language and our Python interop story evolves, we will continue to re-evaluate the semantics of `import`, but for now, we want to keep it strict.

**Comment by gabrieldemarmiesse** [comment]
Thanks, that makes sense! 

Just for the reccord, currently, if I'm importing a alias that doesn't exist from a file that exists, then the compiler doesn't complain at all if the said alias is unused. This behavior can be observed with `mojo run` and `mojo build`. With `mojo package`, it will fail even if the variable is unused.

**Comment by laszlokindrat** [comment]
> Just for the reccord, currently, if I'm importing a alias that doesn't exist from a file that exists, then the compiler doesn't complain at all if the said alias is unused. This behavior can be observed with `mojo run` and `mojo build`. With `mojo package`, it will fail even if the variable is unused.

Thanks for raising this @gabrieldemarmiesse!  If you haven't done so yet, could you please open a separate ticket for that, with a small repro if possible?

**Comment by gabrieldemarmiesse** [comment]
Will do this :)

**Comment by gabrieldemarmiesse** [comment]
@laszlokindrat done in https://github.com/modularml/mojo/issues/2240
