### ISSUE TITLE
[BUG]: `Int` not have a constructor from Intable

### ISSUE THREAD

**Issue by YichengDWu** [modularml/mojo#1896]
### Bug description

Same in #1496 but for `Intable`

### Steps to reproduce

```python
@value
struct S3[T: Intable, V: T]:
    fn test(self) -> Int:
        return Int(V) 
```

### System information

```shell
ethan@LAPTOP-PHBTR3GS:~/moye$ mojo -v
mojo 24.1.0 (c176f84d)
ethan@LAPTOP-PHBTR3GS:~/moye$ modular -v
modular 0.5.1 (1b608e3d)
```
```

**Comment by soraros** [comment]
You can, and probably should use `int` for this purpose.

I think having a constructor from `Intable` is just wrong. Currently, `Int` doesn't need to know the existence of the `Intable` trait, but with the said constructor, they become coupled.

It's easier to see the problem considering an example. Suppose we have a trait `HasBinaryFormat` which essentially implements `bin` from Python. Does `String` need to know the existence of this trait? Or some other trait that happens to return a `String`? I think the answer is trivially "no".

**Comment by YichengDWu** [comment]
> Does String need to know the existence of this trait?

No it does not **need** to know it but I don't think there is an obvious reason not to know it if you explicitly write `String(HasBinaryFormat)`.
