### ISSUE TITLE
[Feature Request] WASM and WASI

### ISSUE THREAD

**Issue by kyrvlasiuk** [modularml/mojo#19]
## Request

Add wasm and wasi compile targets

### Motivation

Same reason why everyone is doing it. I am on mobile, I might elaborate further, if no one else has. Or you can nuke this one. 

### Description and Requirements

TBD

**Comment by SaiNithinNartuo** [comment]
hello mojo team
i have almost 7 years of experience in python and machine learning can i work on this issue

**Comment by Mogball** [comment]
Closing this because it's not in our immediate roadmap and isn't very useful to keep in our issue tracker.

**Comment by huntc** [comment]
Using Python sans WASI in the context of the web browser is compelling to me. The current strategy of running a Python interpreter under WASM is underwhelming. Therefore, having a Python-like-native-wasm offering may be interesting in general terms. It could help drive Mojo adoption perhaps. Just sharing some hopefully useful thoughts.

(For comparison, consider TypeScript vs AssemblyScript.)

**Comment by johnoscott** [comment]
WASM is already a heterogenous target given that it can target WebGPU and both of them can sit on top of exotic hardware. That very much sounds like a job for Mojo ! +1 for adding this.
