### ISSUE TITLE
[BUG]: code runs with 'mojo run' but compiled binary crashes

### ISSUE THREAD

**Issue by niels-ketelaars** [modularml/mojo#1902]
### Bug description

Some code using global variables works when ran using 'mojo \<file\>.mojo', but when compiled with 'mojo build \<file\>.mojo', the binary crashes instantly when ran.

### Steps to reproduce

```python
var testing = DynamicVector[Int]()


fn main() -> None:
    testing.append(5)
    print(testing[0])
```
Using 'mojo' or 'mojo run' on this file works and prints 5 as expected. However, when compiled using 'mojo build', the compiled binary crashes when trying to run it, with the message
```
/__w/modular/modular/LLCL/include/LLCL/Runtime/Runtime.h:105: static M::LLCL::Allocator *M::LLCL::Runtime::getCurrentAllocator(): Assertion `rt && "a global runtime must be set before getting the current allocator"' failed.
Aborted
```

### System information

```shell
System: Ubuntu 22.04.3 LTS (GNU/Linux 5.15.133.1-microsoft-standard-WSL2 x86_64)
Mojo version: mojo 24.1.0 (55ec12d6)
Modular CLI: modular 0.5.1 (1b608e3d)
```

**Comment by ematejska** [comment]
Sorry, global variables have rough edges right now.  Duping this out: https://github.com/modularml/mojo/issues/1573
