### ISSUE TITLE
[BUG][LSP]: LSP can't track PythonObject usage

### ISSUE THREAD

**Issue by ehsanmok** [modularml/mojo#1907]
### Bug description

vscode LSP complains that `PythonObject value is unused`

```
from python.object import PythonObject

fn main() raises:
    var py_lst: PythonObject = []
    py_lst.append(1)
    print(py_lst)
```

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ? Ubuntu 22.04
- Provide version information for Mojo by pasting the output of `mojo -v`: mojo 24.1.0 (c176f84d)
- Provide Modular CLI version by pasting the output of `modular -v`: modular 0.5.1 (1b608e3d)
```

**Comment by River707** [comment]
This was a general Mojo parser issue, but should be fixed in the next release!
