### ISSUE TITLE
[BUG] Does not run locally and and not open source

### ISSUE THREAD

**Issue by johann-petrak** [modularml/mojo#191]
Got an email from you that you want to hear feedback, so here it is:

I am not considering looking at a new language which cannot be run locally and is not open source. Why you insist on having access lists and only let people run the software on your own servers is utterly weird and I have not heard any justification for that (though I heard the bad justificaton you have given for that).  So I will have a look once the software is properly released as proper open source software if it ever will be. Until then I am going to unsubscribe from your mailing list.

**Comment by lattner** [comment]
SG, we're not trying to growth hack things, we're trying ot build the best possible system.  Please check back when it's more mature, thanks.
