### ISSUE TITLE
[BUG]: len(汉) returns 3 instead of 1 like in Python

### ISSUE THREAD

**Issue by ivellapillil** [modularml/mojo#1910]
### Bug description

I am assuming that the intention for String in Mojo would be to abstract over sequence of Unicode grapheme clusters instead of bytes. If that is the case, then this is a defect that len of a chinese character returns the number of bytes instead of the count of characters.

If String is intended to be just an array of bytes, then we would need something that represents Text as used in the real world.

Since String is the default string type in Mojo, it would be great if it does the right thing by default (String handling is super complex, so having a very good default implementation is a must IMHO). For more efficient string representations, may be it is better to create something else that is named explicitly on its intention (e.g. ByteArray).

### Steps to reproduce

In the Mojo REPL:

```
print(len(String("汉"))) 
```

Results in `3`

Whereas in Python REPL:

```
len(str("汉"))
```

Returns 1

**Comment by soraros** [comment]
This is a known issue tracked in #1616.

**Comment by arthurevans** [comment]
This is a known issue--Mojo's string doesn't support Unicode yet. I'm going to close this since there's already a tracking issue for this here: https://github.com/modularml/mojo/issues/1616
