### ISSUE TITLE
[BUG]: Implicit conversion from `FloatLiteral` to simd vector with integer dtypes should be disallowed

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1911]
### Bug description

As title. Otherwise, it will lead to surprising behaviour that's difficult to debug.

### Steps to reproduce

```mojo
fn main():
  print(Int64(0) < 0.5)  # prints False
```

I think what happens is `0.5` got implicitly converted to `Int64` first. It's also inconsistent because `Int(0.5)` doesn't work.

### System information

```shell
Mojo 24.1 on Docker, Intel Mac.
```

**Comment by bgreni** [comment]
Should be noted that this also works specifically with `Float64` due to the 
`fn __init__(inout self, value: SIMD[DType.float64, 1])` constructor.

```mojo
fn main():
    print(Int32(0) < 0.5)  # prints False
    print(Int64(0) < Float64(0.5))  # prints False
    print(Int32(0) < Float32(0.5))  # doesn't compile
```

**Comment by soraros** [comment]
Fixed in the latest nightly.
