### ISSUE TITLE
[Modular CLI]:  M2 Mac air , fail to install new mojo even afeter clean modular/old mojo. Encounter modular: error: Error extracting /: Can't remove already-existing dir

### ISSUE THREAD

**Issue by ChesterHsieh** [modularml/mojo#1912]
### Issue description

As ttile, While I try to update mojo to 24.1 from 0.7.0. It works fine with older version. 

### Steps to reproduce

1) Clean env. I've check both zsh and modular and mojo. None of them could be found. 

<img width="1053" alt="Screen Shot 2024-03-08 at 5 52 37 PM" src="https://github.com/modularml/mojo/assets/22862274/a7a3b29d-2753-46e3-b0b0-47590fc8b0d7">

2) Install mojo
<img width="1207" alt="image" src="https://github.com/modularml/mojo/assets/22862274/f8fb9408-5389-47ab-b315-51c5dc66d052">

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
-> 0.5.1 
- What OS did you install modular CLI on ?
-> macOS Monterey 12.5
```

**Comment by zbowling** [comment]
Can you run `modular clean` and the run `modular install mojo` again?

**Comment by ChesterHsieh** [comment]
same here. re run both still encounter same error.

**Comment by zbowling** [comment]
can you tell me what version of modular you are running with `modular --version`?

**Comment by zbowling** [comment]
Also one thing we can try if you are willing to do an experiment for me is to run this and see if that works? 

```
modular clean
modular install mojo --force-cas
```

That forces a deprecated package download method that is still used on older packages and is going away soon. 

We are not seeing this error with high frequency but I'm still curious if that method works for you.

**Comment by ChesterHsieh** [comment]
@zbowling . Add flag works! However, I still use modular 0.5.1 to test it first.  Many thanks! Let's close the issue.

**Comment by hhstore** [comment]
@zbowling 

## Could it be because mojo doesn't support rye? 

- not works for me. 
- This may be caused by me using [rye](https://github.com/astral-sh/rye) (Python package management tool) to manage Python version numbers.   
- I seem to have encountered similar errors before.   
- Last time I switched to `pyenv` (not `rye`) to switch the `Python` version number, and then fixed the problem.   
- However, I think mojo needs to fix this error in order to support `rye`, which is also a popular Python package management tool lately.


## Env:

- [python rye](https://github.com/astral-sh/rye)

```ruby
❯ which python
/Users/dev/.rye/shims/python


❯ python -V
Python 3.12.2

```

## Error logs:





```ruby

modular clean && modular install mojo --force-cas

# Found release for https://packages.modular.com/mojo @ 24.1.1-0ab415f7-release
# Collecting necessary files...
[files    124/124][bytes    118MiB/118MiB @  10.5MiB/s][██████████████████████████████] 💯%
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
Traceback (most recent call last):
  File "/Users/dev/.modular/pkg/packages.modular.com_mojo/scripts/post-install/pick_python.py", line 67, in <module>
    main()
  File "/Users/dev/.modular/pkg/packages.modular.com_mojo/scripts/post-install/pick_python.py", line 50, in main
    raise Exception(
Exception: Could not find libpython. Check your Python installation and ensure that $LD_LIBRARY_PATH includes the location to the installed Python library (e.g. /usr/lib/x86_64-linux-gnu).
modular: error: failed to run script
==========================
Failure Information:
	- Script: `PATH=/Users/dev/.pyenv/bin:/opt/homebrew/opt/llvm/bin:/Users/dev/.rye/shims:/Users/dev/google-cloud-sdk/bin:/Users/dev/Library/pnpm:/Users/dev/.cargo/bin:/Users/dev/Library/Caches/fnm_multishells/70445_1710899384616/bin:/Users/dev/.pyenv/shims:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/opt/llvm/bin:/usr/local/bin:/Library/Apple/usr/bin:/opt/homebrew/sbin:/opt/homebrew/bin:/Users/dev/bin:/Users/dev/.local/bin:/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/bin:/Applications/Little Snitch.app/Contents/Components:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:~/.fig/bin:~/.fnm:~/.cargo/bin:~/.local/bin:~/.yarn/bin:~/.pulumi/bin:/Users/dev/go/bin:~/sdk/android/emulator:~/sdk/android/tools:~/sdk/android/tools/bin:~/sdk/android/platform-tools:/Users/dev/Library/Android/sdk/emulator:/Users/dev/Library/Android/sdk/tools:/Users/dev/Library/Android/sdk/tools/bin:/Users/dev/Library/Android/sdk/platform-tools:/Users/dev/.gem/bin:/Users/dev/.modular/pkg/packages.modular.com_mojo/bin:~/.pyenv/bin:~/.pyenv/shims:~/.pyenv/plugins/pyenv-virtualenv/shims:/usr/local/share/dotnet/:/usr/local/share/dotnet//tools:/Users/dev/.pub-cache/bin:/Users/dev/.fvm/default/bin:/Users/dev/.fvm/default/bin/cache/dart-sdk/bin HOME=/Users/dev MODULAR_HOME=/Users/dev/.modular PYTHONPATH=/Users/dev/.modular/pkg/packages.modular.com_mojo/venv/lib/Users/dev/.modular/pkg/packages.modular.com_mojo/venv/bin/python /Users/dev/.modular/pkg/packages.modular.com_mojo/scripts/post-install/pick_python.py -installer-outfile /var/folders/pc/78th99qs10zfzdx_r683t23w0000gn/T/modular-tool-script-redirect-7e8791.tmp`
	- Result: 1
	- Stderr:
Traceback (most recent call last):
  File "/Users/dev/.modular/pkg/packages.modular.com_mojo/scripts/post-install/pick_python.py", line 67, in <module>
    main()
  File "/Users/dev/.modular/pkg/packages.modular.com_mojo/scripts/post-install/pick_python.py", line 50, in main
    raise Exception(
Exception: Could not find libpython. Check your Python installation and ensure that $LD_LIBRARY_PATH includes the location to the installed Python library (e.g. /usr/lib/x86_64-linux-gnu).


==========================

```

**Comment by hhstore** [comment]
## related: 


- https://github.com/modularml/mojo/issues/706

**Comment by zbowling** [comment]
@hhstore I don't think I've tested with Rye. Can you copy your comments to a different bug and open it? It's a different issue than this one and then I can add it to the right team's triage queue.

**Comment by hhstore** [comment]
> @hhstore I don't think I've tested with Rye. Can you copy your comments to a different bug and open it? It's a different issue than this one and then I can add it to the right team's triage queue.

sure. I'll open another issue.
