### ISSUE TITLE
[BUG]: `[]` notation of `Dictionary` doesn't pick the right overload

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1915]
### Bug description

There are two overloads:

```mojo
fn __setitem__(self: Self, key: PythonObject, value: PythonObject): ...
# and
fn __setitem__(self: Self, key: PythonObject, value: Self): ...
```

and the compiler is not able to pick the second one when `[]` notation is used.

### Steps to reproduce

```mojo
from python import Python as py

fn main() raises:
  var d = py.dict()
  d["test"] = d             # error: cannot implicitly convert 'Dictionary' value to 'PythonObject' in assignment
  d.__setitem__("test", d)  # works fine
```

### System information

```shell
Mojo 24.1 on Docker, Intel Mac
```

**Comment by dimitrilw** [comment]
Seems to work fine with Nightly, as of 2024.6.2115 (c0b36f30), possibly before.

<img width="1335" alt="image" src="https://github.com/modularml/mojo/assets/5898931/f5fbd0b5-6e91-4d2c-b6a2-75eaf16653d6">

**Comment by lattner** [comment]
Yep, this got fixed along the way, thanks!
