### ISSUE TITLE
[BUG]: Parser crashes   binding Reference to lvalue with subtype lifetime

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1921]
### Bug description

As title. @lattner

### Steps to reproduce

```mojo
from memory.anypointer import AnyPointer

alias i1 = __mlir_attr.`1: i1`

@value
struct List[T: CollectionElement]:
  var data: AnyPointer[T]

  fn __refitem__(inout self, index: Int) -> Reference[T, i1, __lifetime_of(self)]:
    # return self.data.__refitem__(index)
    return self.data[index]
```

### System information

```shell
Mojo 24.1 on Docker, Intel Mac
```

**Comment by lattner** [comment]
Verified, still crashes on ToT. Will investigate when I get a chance, thanks!

**Comment by Ibrahim758** [comment]
When will Mojo be released for Windows?

**Comment by lattner** [comment]
The issue here is that we weren't handling the conversion from "immortal" lifetime the pointer has to "self" lifetime the result  value has.  Fixed in next release, thank you again for reporting this!
