### ISSUE TITLE
[Feature Request] Make AnyRegType EqualityComparable

### ISSUE THREAD

**Issue by mwytock0812** [modularml/mojo#1923]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

It would be useful for [`AnyRegType`](https://docs.modular.com/mojo/stdlib/builtin/type_aliases) to be [`EqualityComparable`](https://docs.modular.com/mojo/stdlib/builtin/equality_comparable).

### What is your motivation for this change?

With generic containers, it is currently not possible to check for equality based on the value of a struct field whose type is the `AnyRegType` metatype. For example, the following code...

```mojo
@register_passable("trivial")
struct Node[T: AnyRegType]:
    var key: T

    fn __eq__(self: Self, other: Self) -> Bool:
        return self.key == other.key
```

returns the following compiler error

```
error: 'T' does not implement the '__eq__' method
        return self.key == other.key
               ~~~~~~~~ ^
```

In a generic linked list of nodes with `AnyRegType` keys, I believe this makes search for a node with a particular key impossible.

**Comment by JoeLoser** [comment]
I don't think we want to do this. We're moving away from AnyRegType except when calling MLIR ops that require SSA values. Many things will use AnyType or some trait refined type.
