### ISSUE TITLE
[BUG]: `math.copysign` doesn't restrict it's dtype to float

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1940]
### Bug description

As title. Type error should be raised higher up, I think.

### Steps to reproduce

```mojo
import math

fn main():
  var n = Int32(2)
  _ = math.copysign(n, n)
```
Error:
```
/__w/modular/modular/Kernels/mojo/stdlib/math/math.mojo:1397:6: error: call intrinsic signature i32 (i32, i32) to overloaded intrinsic "llvm.copysign" does not match any of the overloads
/__w/modular/modular/Kernels/mojo/stdlib/math/math.mojo:1397:6: error: LLVM Translation failed for operation: llvm.call_intrinsic
/__w/modular/modular/Kernels/mojo/stdlib/math/math.mojo:1397:6: note: see current operation: %15 = "llvm.call_intrinsic"(%3, %3) <{fastmathFlags = #llvm.fastmath<none>, intrin = "llvm.copysign"}> : (i32, i32) -> i32
/home/vscode/.modular/pkg/packages.modular.com_mojo/bin/mojo: error: Failed to materialize symbols: { (exec, { main, KGEN_EE_JIT_GlobalDestructor, KGEN_EE_JIT_GlobalConstructor }) } (from the layer: failed to lower module to LLVM IR for archive compilation)
```

### System information

```shell
Mojo 24.1 on Docker, Intel Mac
```

**Comment by soraros** [comment]
@JoeLoser come think about it, `copysign`does seem to have well defined meaning for integer types, and are quite convenient in generic code. Maybe we should have implementation for them as well, just not lowered into a single LLVM intrinsic.

**Comment by JoeLoser** [comment]
> @JoeLoser come think about it, `copysign`does seem to have well defined meaning for integer types, and are quite convenient in generic code. Maybe we should have implementation for them as well, just not lowered into a single LLVM intrinsic.

Ha, funny that you mention that. I just reworked the PR a few more ago to define it for integral types too with the same rationale. :)

**Comment by soraros** [comment]
@JoeLoser Lol! For signed types only or both? What about booleans? How was zero treated? Maybe having to answer these questions is why they are not generally available (not in NumPy or PyTorch even). I feel very conflicted right now.

**Comment by gryznar** [comment]
btw, why not `copy_sign` to align naming?
