### ISSUE TITLE
[Feature Request] `Optional[T].or_else()` should return `T` instead of `Optional[T]`

### ISSUE THREAD

**Issue by toiletsandpaper** [modularml/mojo#1945]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

As for now, Mojo's `or_else` function returns another `Optional` with new value - [docs](https://docs.modular.com/mojo/stdlib/collections/optional#or_else)
But this is not making any sense for me. 
For example:

```mojo
from collections.optional import Optional

fn default_name() -> String:
    return 'UnknownUser'

fn main():
    var name: Optional[String] = None
    print(
        'Hello', name.or_else(default_name()).value()
    )
```

I've forced to call `.value()` even if I'm SURE that it will return `String`. Even docs (`or_else(self: Self, default: T) -> Self`) says that I need to pass same `T` as `Optional[T]`. And I also can't pass None as default value. So why it returns another Optional if `or_else` is created to fill `None` with not-`None` value?

### What is your motivation for this change?

Rust have somewhat the same function for their `Option` type - [Rust docs](https://doc.rust-lang.org/std/option/enum.Option.html#method.unwrap_or_else)

And `unwrap_or_esle` also returns value, not `Option`
> Returns the contained [Some](https://doc.rust-lang.org/std/option/enum.Option.html#variant.Some) value or computes it from a closure.

So, I'm asking to change `Optional.or_else()` behavior, so it will return `T` instead of `Optional[T]`.

### Any other details?

Thank you for your work, guys. Mojo is the language I was looking for. Mixing Python's flexibility and simplicity with Rust's static typing and borrow checking, salted with SIMD is great combo. You are great!

**Comment by soraros** [comment]
The Rust equivalent is [`unwrap_or`](https://doc.rust-lang.org/std/option/enum.Option.html#method.unwrap_or).

**Comment by JoeLoser** [comment]
+1.  This looks to be an oversight when it was initially designed.  I just opened a PR internally to fix this and it'll be included in the next release.
