### ISSUE TITLE
[Feature Request]  Native Windows support

### ISSUE THREAD

**Issue by Ibrahim758** [modularml/mojo#1948]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

native support for windows.

when will it be available?

### What is your motivation for this change?

I use Windows

**Comment by soraros** [comment]
Duplicate of #620.

**Comment by akirchhoff-modular** [comment]
Thanks @soraros. Yes, this looks like a duplicate of #620. @Ibrahim758, please leave a reaction on #620 to indicate your interest.
