### ISSUE TITLE
[BUG] Type using associated alias of mutually recursive other type isn't recognised as `CollectionElement`

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1967]
### Bug description

As title.

### Steps to reproduce

```mojo
from collections import Optional

@value
struct A(CollectionElement):
  var val: B.T

struct B:
  alias T = Int
  var val: Optional[A]  # error: 'Optional' parameter #0 has 'CollectionElement' type, but value has type 'A'
```

Replacing `B.T` with Int solves the problem.

### System information

```shell
Mojo 24.1 on Docker, Intel Mac
```

**Comment by siitron** [comment]
You can temporarily fix this by adding the `__moveinit__()` and `__copyinit__()` methods to `A`: https://docs.modular.com/mojo/roadmap#value-is-limited-with-trait-conformance-check

**Comment by soraros** [comment]
Fixed in the latest nightly.
