### ISSUE TITLE
[Feature Request] Can Mojo make CPython code AOT-compiled, not JIT'd or interpreted?

### ISSUE THREAD

**Issue by Foxchandaisuki** [modularml/mojo#1968]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

On this page, https://docs.modular.com/mojo/manual/python/ It is said that "It runs Python code using a standard Python interpreter (CPython)"

Does that mean CPython code cannot be AOT-compiled and always be interpreted?

### What is your motivation for this change?

I hope existing CPython code could be AOT-compiled too, as it can be JIT'd, or interpreted in Mojo.

**Comment by River707** [comment]
Thanks for filing! We don't have any current plans for expanding into more advanced CPython handling, but we're constantly evaluating how we can best integrate with the python ecosystem. There are a lot of different avenues we can venture down, but nothing of note to report here yet.

**Comment by Foxchandaisuki** [comment]
Do you mean that CPython code included in Mojo code will always be
interpreted by the inner interpreter with no Ahead-Of-Time compilation to
native code?

2024년 4월 4일 (목) 오전 3:40, River Riddle ***@***.***>님이 작성:

**Comment by walter-erquinigo** [comment]
We are currently revisiting our python integration, so we'll evaluate this request after that.

**Comment by Mogball** [comment]
An explicit goal of the Mojo project is to NOT be a Python compiler. Python is a language that by definition, when compiled, becomes a different language. Mojo is the best way to extend Python, but itself is not a Python compiler.
