### ISSUE TITLE
[BUG] The default value for F32 seems to be random when I initialize it with let, this does not happen with F64

### ISSUE THREAD

**Issue by arfan** [modularml/mojo#197]
## Bug Description

The default value for F32 seems to be random when I initialize it with let, this does not happen with F64. Sample code
```
let a: F64
let b: F32
print(a, b)
```

result 
```
0.000000 1157577169698816.000000
```
![Screen Shot 2023-05-19 at 02 54 49](https://github.com/modularml/mojo/assets/29197/6543697e-9d83-47a1-8912-14d79a89c067)

### Steps to Reproduce

1. Run this code in mojo jupyter lab
```
let a: F64
let b: F32
print(a, b)
```

### Context

**Comment by lattner** [comment]
Right, this is actually because top level code isn't checking for unitialized variables in the notebook.  Let's track this under this bug: https://github.com/modularml/mojo/issues/15

Thank you for filing this!

**Comment by lattner** [comment]
You can resolve this by putting code in a function, it will generate the correct error.
