### ISSUE TITLE
[BUG] Unrolled Iterators treated as Dynamic

### ISSUE THREAD

**Issue by Benny-Nottonson** [modularml/mojo#1978]
### Bug description

When a loop is unrolled, the length must be known at compile time. Because of this, the way it is represented in time, the code block for each iteration should also know the value of its index at compile time, meaning it shouldn't be treated as a dynamic value.

### Steps to reproduce

```mojo
fn example():
    @unroll
    for IDX in range(10):
        alias test = IDX * 2
        print(test)

### System information

```shell
WSL2 Ubunutu
```

**Comment by mikowals** [comment]
I think this is similar to `@parameter` decorated for loops.  See [discussion](https://github.com/modularml/mojo/discussions/1422).

**Comment by Mogball** [comment]
This is no longer relevant because the feature was removed
