### ISSUE TITLE
[BUG] importing `.mojopkg` runs its `main()` instead of only importing

### ISSUE THREAD

**Issue by toiletsandpaper** [modularml/mojo#1987]
### Bug description

When importing and calling something from `.mojopkg` - mojo runs only package's main, and not real main.

### Steps to reproduce

I've written a minimal repro:
```
.
├── birds_package.mojopkg
├── main.mojo
└── simple_package
    ├── __init__.mojo
    └── birds.mojo
```

Where `simple_package/birds.mojo` is:
```mojo
struct Bird:
    var name: String

    fn __init__(inout self, name: String):
        self.name = name

    fn fly(self):
        print("The bird " + self.name + " is flying")

fn main():
    var bird = Bird(name="Package")
    bird.fly()
```

and `main.mojo`:
```mojo
from birds_package.birds import Bird

fn main():
    print('before pigeon')
    var b = Bird('pigeon')
    b.fly()
    print('after pigeon')
```

</hr>

When I'm trying to import `birds_package.mojopkg` in `main.mojo` — my output is:
```
The bird Package is flying
```

And when `simple_package` as folder:
```
before pigeon
The bird pigeon is flying
after pigeon
```

</hr>

Mojo package was created with
```sh
mojo package simple_package -o birds_package.mojopkg
```

and `__init__.mojo` is empty file

### System information

```shell
❯ mojo -v
mojo 24.1.1 (0ab415f7)
❯ modular -v
modular 0.5.2 (6b3a04fd)
❯ modular host-info
  Host Information
  ================

  Target Triple: aarch64-unknown-macosx
  CPU: apple-m1
  CPU Features: aes, complxnum, crc, dotprod, fp-armv8, fp16fml, fullfp16, jsconv, lse, neon, pauth, ras, rcpc, rdm, sha2, sha3
```

**Comment by River707** [comment]
Thanks for the report. Mojo doesn't really have well defined support for defining a `main` inside of a package. We'll add an error an a follow-up release to just prevent this for now until we work through the ramifications of it.
