### ISSUE TITLE
[BUG] Dictionary copy constructor shallow copies the _index.data pointer resulting in a crash

### ISSUE THREAD

**Issue by mgrotkowski** [modularml/mojo#1990]
### Bug description

Stdlib implementation of dictionary copy constructor copies the _index.data pointer instead of making a deep copy of the underlying index data. This results in a crash when accessing the copied dictionary.

### Steps to reproduce

```
from collections.dict import Dict

def main():
    var dict_1 = Dict[String, String]()
    var dict_2 = dict_1

    dict_1["a"] = "b"
    dict_2["a"] = "c"
```
Running this code results in:
```
LLVM ERROR: out of memory
Allocation failed
```

While this confirms that _index.data pointers are the same:

```
from collections.dict import Dict

def main():
    var dict_1 = Dict[String, String]()
    var dict_2 = dict_1

    print(dict_1._index.data)
    print(dict_2._index.data)
```
Output:
```
0x59b27b950000
0x59b27b950000
```

### System information

```shell
- What OS did you do install Mojo on ?
Arch Linux
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 24.1.1 (0ab415f7)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.5.1 (1b608e3d)
```

**Comment by JoeLoser** [comment]
This is already fixed in the upcoming release — thanks for the bug report.  Note to self: fixed in https://github.com/modularml/modular/commit/2596a25af2d639ff12fb670f50a61ac2e661dffd.
