### ISSUE TITLE
[Enhancement] Warnings in playground look l like errors and the rest of the output is not shown

### ISSUE THREAD

**Issue by pharaoh0101** [modularml/mojo#1994]
### Bug description

`def` `lexical_scopes():`
    ` var` `num` = `10`
    ` var` `dig` = `1`
    ` if` `True:`
        ` print("num:", num) # Reads the outer-scope "num"`
        ` var num = 20 # Creates new inner-scope "num"`
        ` print("num:", num) # Reads the inner-scope "num"`
        ` dig = 2 # Edits the outer-scope "dig"`
    ` print("num:", num) # Reads the outer-scope "num"`
    ` print("dig:", dig) # Reads the outer-scope "dig"`

`def main():`
`lexical_scopes()`

Compile error:

/source/prog.mojo:4:8: warning: if statement with constant condition 'if True'
    if True:
       ^

### Steps to reproduce

* Include relevant code snippet or link to code that did not work as expected.
* If applicable, add screenshots to help explain the problem.
* If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
* Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by pharaoh0101** [comment]
Location of the code

https://docs.modular.com/mojo/manual/variables#variable-scopes

The code has been executed on me

https://docs.modular.com/mojo/playground

**Comment by soraros** [comment]
Not a bug.
Missing parentheses: `def main:`, should have been `def main():`.

**Comment by ematejska** [comment]
The warning is appropriate but I can see how in the playground GUI it's being treated as an error and the rest of the output is now show.

@robert-j-webb I think we need to enhance the playground to handle warnings better.

**Comment by ematejska** [comment]
The full output is as follows if run at the command-line
warning: if statement with constant condition 'if True'
  if True:
     ^
num: 10
num: 20
num: 10
dig: 2

**Comment by robert-j-webb** [comment]
@grosskur - can we support some kind of ignoring of warnings?

**Comment by ematejska** [comment]
I like warnings :). Can we somehow display both?  Output pane instead of error pane?
