### ISSUE TITLE
[Modular CLI]

### ISSUE THREAD

**Issue by MikiVanousek** [modularml/mojo#1996]
### Issue description

After running `mojo auth` I get
```
modular: error: could not find the client certificate
```

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`

modular 0.5.2 (6b3a04fd)
```
- What OS did you install modular CLI on?
I use Distrobox with `Ubuntu 22.04.4 LTS x86_64` container.
```

**Comment by smuniraj2018** [comment]
We had a known issue earlier. This should be resolved in 0.7.1 version of the client. Please update and try again
