### ISSUE TITLE
[BUG] [mojo-tooling] Simple code crashes LSP

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1997]
### Bug description

As title. If the closure is marked as `@parameter`, the problem goes away.

### Steps to reproduce

```mojo
fn main():
  var l = DynamicVector[Int]()
  fn inner(i: Int):
    l.append(0)
```

### System information

```shell
Mojo 24.1.1 on Docker, Intel Mac
```

**Comment by River707** [comment]
Thanks for reporting this, we'll take a look!

**Comment by River707** [comment]
This should be fixed in the next release!
