### ISSUE TITLE
[BUG] [mojo-tooling] LSP doesn't show tooltip for capturing closure

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#1998]
### Bug description

As title. Jump to definition also doesn't work.

### Steps to reproduce

```mojo
fn outer(b: Bool):
  fn closure(): # doesn't show anything when cursor is on `closure`
    print(b)
```

### System information

```shell
Mojo 24.1.1 on Docker, Intel Mac
```

**Comment by River707** [comment]
Thanks for reporting this! We're missing some support for nested functions, but we'll look into plugging those gaps.

**Comment by AmaranthineCodices** [comment]
No longer reproduces.

**Comment by soraros** [comment]
It's still not showing the right information:

```mojo
fn outer(b: Bool):
  @parameter
  fn f():  # good
    ...
  fn g():  # no type info etc.
    print(b)
```
