### ISSUE TITLE
[Docs] `.github/ISSUE_TEMPLATE/mojo_bug_report.yaml` has typos

### ISSUE THREAD

**Issue by hamirmahal** [modularml/mojo#2008]
### Where is the problem?

https://github.com/modularml/mojo/blob/main/.github/ISSUE_TEMPLATE/mojo_bug_report.yaml

### What can we do better?

https://github.com/modularml/mojo/blob/main/.github/ISSUE_TEMPLATE/mojo_bug_report.yaml should have correct grammar and spelling.

**Comment by soraros** [comment]
I think it's fixed by #2009.
