### ISSUE TITLE
[Feature Request] comptime check if implement trait

### ISSUE THREAD

**Issue by alex-s168** [modularml/mojo#2012]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Add a compile-time function to check if a type implements a trait for use in template structs and functions

### What is your motivation for this change?

I wanted to make a pretty printer for something that displays the return value of `__str__()` if present, and `<obj>` otherwise.

I believe this has many other applications too, like specializations for parts of algorithms dependent on the data type

**Comment by gabrieldemarmiesse** [comment]
This can be a dupe of https://github.com/modularml/mojo/issues/1876. I'm unsure though

**Comment by alex-s168** [comment]
Didn't notice that
Yes it is exactly that
