### ISSUE TITLE
[mojo-stdlib] Add `list.pop(index)` API

### ISSUE THREAD

**Issue by JoeLoser** [modularml/mojo#2017]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Currently, our `List` type only supports `pop_back` to remove and return the last element in the list.  However, we support `__setitem__` for inserting a value at an arbitrary index.  Naturally, we should be allowed to remove elements at an arbitrary position that is in range.

Note the Python `list` datatype supports `pop(index)` too as seen [here](https://docs.python.org/3/tutorial/datastructures.html).  If no index is specified, it removes the last element and returns it.  I think preserving that behavior is desirable.

### What is your motivation for this change?

Parity with Python `List` API and to allow for specific-index removal.

**Comment by whym1here** [comment]
Could you point to the current `pop_back` implementation?

**Comment by JoeLoser** [comment]
> Could you point to the current `pop_back` implementation?

Of course.  [This](https://github.com/modularml/mojo/blob/76d05839487905d6c7459c7135fdb5bb9f23f336/stdlib/src/collections/list.mojo#L229) is the current implementation.  I recommend we add a new function: `pop(index: Int)` and preserve the `pop_back` for now.  We can deprecate it and remove it in a normal migration manner after we have the `pop` function.

**Comment by sazid** [comment]
Does this look like a valid implementation of the `pop(index)` behavior?

```mojo
@always_inline
fn pop(inout self, index: Int) -> T:
    """Pops the value at the given index and returns it.

    Returns:
        The popped value.
    """
    debug_assert(-self.size <= index < self.size, "index must be within bounds")

    current_len = len(self)

    var normalized_idx = index
    if index < 0:
        normalized_idx += len(self)

    var ret_val = (self.data + normalized_idx).take_value()
    self.size -= 1

    # Move all elements to the left by one index.
    for i in range(normalized_idx, current_len-1):
        self[i] = self[i+1]

    if self.size * 4 < self.capacity:
        if self.capacity > 1:
            self._realloc(self.capacity // 2)

    return ret_val^
```

Chalked it up on my windows machine, if this looks good I'll open and submit a PR after building and testing it on linux/mac.

**Comment by whym1here** [comment]
I could be wrong here but I see an issue in this implementation.
- currently `fn __getitem__(self, i: Int) -> T:` returns a copy of element at `i` 
- and `fn __setitem__(inout self, i: Int, owned value: T):` takes the ownership of the element
- in the current implementation we create the copy for each element `self[i] = self[i+1]`

I would suggest something more efficient like this:
```mojo
    @always_inline
    fn pop(inout self, index: Int = -1) -> T:
        """Pops the value at the given index and returns it.

        Returns:
            The popped value.
        """
        debug_assert(-self.size <= index < self.size, "index must be within bounds")
        
        var current_len = len(self)
        var normalized_idx = index
        
        if index < 0:
            normalized_idx += len(self)

        var ret_val = (self.data + normalized_idx).take_value()

        # Move all elements to the left by one index.
        for i in range(normalized_idx, current_len - 1): 
            self[i] = (self.data + i + 1).take_value() 

        self.size -= 1
        
        if self.size * 4 < self.capacity:
            if self.capacity > 1:
                self._realloc(self.capacity // 2)

        return ret_val^
```

@JoeLoser @sazid I would like to take this issue up if you both don't mind and if the above statement is correct? 
@JoeLoser should we use  `fn __getitem__(self, i: Int) -> T:` in `fn pop(inout self, index: Int = -1) -> T:` as its behavior might change in future?

**Comment by sazid** [comment]
> I could be wrong here but I see an issue in this implementation.
> - currently `fn __getitem__(self, i: Int) -> T:` returns a copy of element at `i` 
> - and `fn __setitem__(inout self, i: Int, owned value: T):` takes the ownership of the element
> - in the current implementation we create the copy for each element `self[i] = self[i+1]`
> 
> I would suggest something more efficient like this:
> ```mojo
>     @always_inline
>     fn pop(inout self, index: Int = -1) -> T:
>         """Pops the value at the given index and returns it.
> 
>         Returns:
>             The popped value.
>         """
>         debug_assert(-self.size <= index < self.size, "index must be within bounds")
>         
>         var current_len = len(self)
>         var normalized_idx = index
>         
>         if index < 0:
>             normalized_idx += len(self)
> 
>         var ret_val = (self.data + normalized_idx).take_value()
> 
>         # Move all elements to the left by one index.
>         for i in range(normalized_idx, current_len - 1): 
>             self[i] = (self.data + i + 1).take_value() 
> 
>         self.size -= 1
>         
>         if self.size * 4 < self.capacity:
>             if self.capacity > 1:
>                 self._realloc(self.capacity // 2)
> 
>         return ret_val^
> ```
> 
> @JoeLoser @sazid I would like to take this issue up if you both don't mind and if the above statement is correct? 
> @JoeLoser should we use  `fn __getitem__(self, i: Int) -> T:` in `fn pop(inout self, index: Int = -1) -> T:` as its behavior might change in future?

I don't mind, go ahead!

**Comment by LJ-9801** [comment]
Hi I think #2041  is ready for review and I am very sorry for submitting a pr before realizing there are already people wanting to work on it at the same time. However if there is any suggestion on this pr please feel free to comment on it.

**Comment by JoeLoser** [comment]
Fixed by https://github.com/modularml/mojo/commit/0e94191609a286eecddafe6e149240c50f07c8dd
