### ISSUE TITLE
[mojo-stdlib] Add tempdir / tempfile functionality to os/Pathlib

### ISSUE THREAD

**Issue by JoeLoser** [modularml/mojo#2018]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Add `tempdir` and `tempfile` functions to the `pathlib` module.

### What is your motivation for this change?

These are generally useful functions that exist in the Python ecosystem that we should have in our `pathlib` module.

**Comment by kiran-4444** [comment]
Can I work on this?

**Comment by JoeLoser** [comment]
> Can I work on this?

Of course, go ahead! Feel free to assign the issue to yourself so other contributors know.

**Comment by artemiogr97** [comment]
@kiran-4444 are you still working on this?, I would like to work on it if you did not continue

**Comment by kiran-4444** [comment]
> @kiran-4444 are you still working on this?, I would like to work on it if you did not continue

Hey, yeah please go ahead.

**Comment by FarhanAliRaza** [comment]
Hello, @kiran-4444  are you working on this?

**Comment by FarhanAliRaza** [comment]
I saw the code of CPython to check how they implement this feature in Python they do create a fileWrappper which has its own close function that deletes the file. 
I tried implementing that like this 

```
struct FileWrapper:
 fn __init__(
        inout self,
        file: FileHandle,


    ):

        self.file = file
```
I am getting an error Filehandle can not be copied because it does not implement the copy function.

**Comment by FarhanAliRaza** [comment]
Another easier method could be to override the __del__ function of Filehandle struct or some other way extending that struct 

```
    @always_inline
    fn __del__(owned self):
        """Closes the file handle."""
        try:
            self.close()
        except:
            pass
```

would become 
```
    @always_inline
    fn __del__(owned self):
        """Closes the file handle."""
        try:
            self.close()
           # delete the file from the file system here
        except:
            pass
```

**Comment by artemiogr97** [comment]
> Hello, @kiran-4444  are you working on this? 

Hello, I'm working on this, but the functions to delete files were not implemented yet, so I opened the issue #2306 and created a pull request for it

**Comment by artemiogr97** [comment]
@JoeLoser maybe you can assign the issue to me? I don't think I can do it myself

**Comment by JoeLoser** [comment]
This is done now, closing this out!  Thanks everyone!
