### ISSUE TITLE
[mojo-stdlib] Replace tests using `FileCheck` with `testing` module where possible

### ISSUE THREAD

**Issue by JoeLoser** [modularml/mojo#2024]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Many tests use `FileCheck` still which isn't great for many reasons for a standard library. We should move these over to use functions like `assert_equal`, `assert_true`, and friends from the `testing` module where possible.

### What is your motivation for this change?

Moving things over to use our `testing` module helps "eat our own cooking" as we build out the test framework.  Additionally, often, the code is much shorter — while still achieving the same intent as the original code.

### Any other details?

There are several test files still using `FileCheck` as can be identified with:

```
git grep -l '| FileCheck'
```

I wouldn't worry too much about the examples to start with; in fact, I recommend we fix those _last_ only after we've changed as many of the standard library tests as we can.

Note: if multiple people plan on working on this, please coordinate to avoid two people working in porting the tests over for the same file.

**Comment by fowlerlee** [comment]
@JoeLoser: is this issue still open for working on (if so I wish to contribute and fix it) ? @shenyihOng has committed to a different ticket (https://github.com/modularml/mojo/pull/2069) but there are still files that use the FileCheck error handling. I can help by fixing the remaining files work.

**Comment by gabrieldemarmiesse** [comment]
#2451 is the last PR we can do in this direction. The only FileCheck left are:
* The tests for `debug_assert`
* The tests for `print`
* The tests for `trap`
* The tests for the docs and examples
Which have all effects that are impossible to grab and inspect from inside the Mojo process. So maybe let's close this issue then? No other improvement can be added from the community's side I believe

**Comment by JoeLoser** [comment]
Sounds good, thank you for all of your hard work in this area, @gabrieldemarmiesse!  Getting the remaining tests off of `FileCheck` is a bit trickier/requires some library work.  I have some initial ideas for inspecting stdout and such using `dup`, but we may want to do that sort of "stdout" inspection at the unit testing frameworking level when we build that out in the coming months.
