### ISSUE TITLE
[mojo-stdlib] Add move constructor to `Atomic`

### ISSUE THREAD

**Issue by JoeLoser** [modularml/mojo#2026]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Add a `moveinit` function to the `Atomic` type.  Currently, people do workarounds such as calling `atomic.fetch_add(0)` in a user-defined type's `moveinit` when trying to move a data member that is an `Atomic` type.

### What is your motivation for this change?

This will help simplify/clarify intent for code trying to move from an atomic, such as a class trying to define a `moveinit` function that has a data member that is an `Atomic` type.

### Any other details?

Please explicitly conform to the `Movable` trait once `moveinit` is implemented for `Atomic`.

**Comment by vladdy** [comment]
I'd like to take this one.

**Comment by JoeLoser** [comment]
> I'd like to take this one.

Great!  Feel free to assign yourself so others know not to start working on it.  Appreciate it! 😄

**Comment by StandinKP** [comment]
I took this up as there was no update since 2 days. Let me know if any suggestions on the PR. Thanks.

Also @JoeLoser I tried to assign the issue to me but I am unable to assign the issue to me. The PR can be assigned. Lmk Thanks

**Comment by vladdy** [comment]
@StandinKP I'm looking into this. Could you take some other issue please?

**Comment by vladdy** [comment]
Sorry, I missed you did a PR already. I you can take
this issue other.

**Comment by StandinKP** [comment]
Thanks @vladdy 
@JoeLoser can you take a look at the assigning issues issue? So that we can avoid this kind of confusions in the future.

**Comment by vladdy** [comment]
@StandinKP I wanted to respectfully point that there was no confusion here. You just went ahead and submitted a PR even without asking. Assigning an issue would not solve that problem.

**Comment by jayzhan211** [comment]
> @StandinKP I wanted to respectfully point that there was no confusion here. You just went ahead and submitted a PR even without asking. Assigning an issue would not solve that problem.

Agree.

**Comment by StandinKP** [comment]
> @StandinKP I wanted to respectfully point that there was no confusion here. You just went ahead and submitted a PR even without asking. Assigning an issue would not solve that problem.

My bad. There was no update on it so I thought it was free to take up. Do you want me to close this PR and you can take it up?

**Comment by vladdy** [comment]
@StandinKP not a big deal. Please complete what you started.
