### ISSUE TITLE
[mojo-stdlib] Remove uses of `__get_lvalue_as_address`

### ISSUE THREAD

**Issue by JoeLoser** [modularml/mojo#2027]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Replace uses of `__get_lvalue_as_address` so we can remove the builtin from the compiler itself.  Everything using `__get_lvalue_as_address(expr)` can move to using `Reference(expr)` and `Reference(expr).get_unsafe_pointer()` should theoretically be a mechanical replacement.

### What is your motivation for this change?

Doing this will allow us to remove the builtin from the compiler itself.

**Comment by Shaikh-Ubaid** [comment]
What should be used here `Reference` or `Reference(expr).get_unsafe_pointer() ` to replace `__get_lvalue_as_address`?

When do we use `Reference` and when do we use `Reference(expr).get_unsafe_pointer() `?

**Comment by JoeLoser** [comment]
Fixed with https://github.com/modularml/mojo/commit/3eb0f64b4fb9a4b4ba8a09029db80f05ee40778a, thank you!
