### ISSUE TITLE
[mojo-stdlib] Make use of variadic initializer for `List` where applicable

### ISSUE THREAD

**Issue by JoeLoser** [modularml/mojo#2045]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

For example, replace things like 

```mojo
var l = List[String]()
l.append("one")
l.append("two")
l.append("three")
```

with 

```mojo
var l = List[String]("one", "two", "three")
```

This is a bit shorter and easier to read.  One such example is [here](https://github.com/modularml/mojo/blob/4feb92e8106072a7d9929cba9eee220422afb227/stdlib/test/collections/test_list.mojo#L133C5-L136C25)

### What is your motivation for this change?

Using new standard library constructor for `List` to simplify/shorten existing code.

**Comment by VMois** [comment]
Isn't this part already done? Below is reference in the code:

https://github.com/modularml/mojo/blob/6d2a7b552769358ec68a94b8fd1f6c2126d59ad9/stdlib/src/collections/list.mojo#L115-L125

In addition, I can do this for example:

```mojo
var test = List[String]("one", "two", "three")
```

Unless the proposed change should also eliminate copying and use "owned" as well?

**Comment by JoeLoser** [comment]
This issue was just meant to be applying that constructor you pointed out, where possible, such as at https://github.com/modularml/mojo/blob/4feb92e8106072a7d9929cba9eee220422afb227/stdlib/test/collections/test_list.mojo#L133C5-L136C25 for example.  There doesn't appear to be many other places right now that would immediately benefit from this constructor yet.  One other spot is `stdlib/test/utils/issue_13632.mojo`.  This is just a small starter task for someone who's getting used to contributing to the repo primarily. 😄 

The part about avoiding copying the variadic arguments can't be done yet as we need some more work done in the compiler to support that still I believe (I just recently added this constructor a few weeks ago).

**Comment by VMois** [comment]
Oh, I see. Sorry for the confusion.

**Comment by kevinmingtarja** [comment]
Hi, I'd like to contribute to this issue!

**Comment by JoeLoser** [comment]
Fixed with https://github.com/modularml/mojo/commit/cbcb4b015b922df3dc56c1144d70d24518cf1521
