### ISSUE TITLE
[stdlib] Do not copy elements when using `FileHandle.read_bytes()`

### ISSUE THREAD

**Issue by VMois** [modularml/mojo#2051]
I was doing a one-billion row challenge with Mojo and tried reading 1 billion rows (around 13GB file) using `read_bytes()` and quickly ran out of memory. It does not happen with `read()`.

```mojo
alias input_file = "../1brc/measurements.txt"
alias chunk_size = 1024

fn main() raises:
    with open(input_file, "rb") as f:
        while len(f.read_bytes(chunk_size)):
            pass
```

After checking recently open-sourced `stdlib` (hooray), I found that while `read` passes buffer to String, `read_bytes` copies memory.

https://github.com/modularml/mojo/blob/6d2a7b552769358ec68a94b8fd1f6c2126d59ad9/stdlib/src/builtin/file.mojo#L187-L195

I am not a novice in Mojo, but I am far away from being good. I am not sure why it is a problem. I modified the read_bytes method and replaced the built stdlib in `.modular/pkg/packages.modular.com_mojo/lib/mojo`:

```mojo
var list = List[Int8](capacity=int(size_copy))
list.data = rebind[AnyPointer[Int8]](buf)
list.size = int(size_copy)
```
I am still unsure how `buf` becomes owned by a list here (similarly in the `read` method), but my modification does not run out of memory.

I would appreciate an explanation of why, and if my approach makes sense, I can open PR. Thank you

**Comment by MoSafi2** [comment]
As #2182  is now merged, we can fix this issue.
@JoeLoser can you assign this to me?

**Comment by JoeLoser** [comment]
> As #2182 is now merged, we can fix this issue. @JoeLoser can you assign this to me?

All yours, just assigned!  I think @jackos is working in this area for something else though.  @jackos do you mind chiming in here?

**Comment by jackos** [comment]
Hey good catch @VMois yep it's an unnecessary memcpy and memory leak. The external function returns a pointer with the memory already allocated, so doing the memcpy to a different address means that the original pointer is never freed.

This would be a great PR to raise yeah! What you have there looks correct.

**Comment by JoeLoser** [comment]
Fixed with https://github.com/modularml/mojo/commit/0b344fbd14fa80a33a3c07bfccba3dce661262de, thank you @MoSafi2 for the fix!
