### ISSUE TITLE
[BUG] __del__ crashes the compiler

### ISSUE THREAD

**Issue by andrew-suprun** [modularml/mojo#2054]
### Bug description

Compiler v24.2 crashes when compiling code below.

### Steps to reproduce

```mojo
struct S:
    var name: String

    fn __init__(inout self, name: String):
        self.name = name

    fn __del__(owned self):
        # print("del", str(self))  # works
        print("del", self)  # crashes the compiler

    fn __str__(self) -> String:
        return self.name


fn main():
    _ = S("")
```

### System information

```shell
- What OS did you do install Mojo on ?
  Mac Book Pro (M1) Sonoma 14.2.1

- Provide version information for Mojo by pasting the output of `mojo -v`
  mojo 24.2.0 (c2427bc5)

- Provide Modular CLI version by pasting the output of `modular -v`
  modular 0.6.0 (04c05243)
```

**Comment by a62690705** [comment]
Output

Compile error:

mojo: /__w/modular/modular/third-party/llvm-project/llvm/include/llvm/Support/Casting.h:566: decltype(auto) llvm::cast(const From &) [To = M::KGEN::LIT::RefType, From = mlir::Type]: Assertion `isa<To>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  mojo           0x000055d921ce5157
1  mojo           0x000055d921ce2d2e
2  mojo           0x000055d921ce57ef
3  libc.so.6      0x00007f3da0140520
4  libc.so.6      0x00007f3da01949fc pthread_kill + 300
5  libc.so.6      0x00007f3da0140476 raise + 22
6  libc.so.6      0x00007f3da01267f3 abort + 211
7  libc.so.6      0x00007f3da012671b
8  libc.so.6      0x00007f3da0137e96
9  mojo           0x000055d923346ebe
10 mojo           0x000055d9233466e4
11 mojo           0x000055d923345096
12 mojo           0x000055d923344d8c
13 mojo           0x000055d923343688
14 mojo           0x000055d923342e6c
15 mojo           0x000055d923339ee3
16 mojo           0x000055d9247e58d6
17 mojo           0x000055d9247e5f61
18 mojo           0x000055d9247e8542
19 mojo           0x000055d92339f016
20 mojo           0x000055d92222f4b5
21 mojo           0x000055d92339e670
22 mojo           0x000055d92339e170
23 mojo           0x000055d923abd309
24 mojo           0x000055d923abd141
25 libstdc++.so.6 0x00007f3da0425253
26 libc.so.6      0x00007f3da0192ac3
27 libc.so.6      0x00007f3da0224850

**Comment by ematejska** [comment]
Thank you for the fully formed testcase!

**Comment by lattner** [comment]
this is fixed in the next release, thank you!
