### ISSUE TITLE
[stdlib] Open source tensor module

### ISSUE THREAD

**Issue by a62690705** [modularml/mojo#2063]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Open source tensor module

### What is your motivation for this change?

When I use the tensor type, some strange errors appear. I am curious to know the components of the tensor for better, smoother, and easier use. If you mind, that's fine.

**Comment by soraros** [comment]
Quote @jackos `@benny` on Discord ([link](https://discord.com/channels/1087530497313357884/1223149631597182986/1223155440490250311)):

> I’ve asked staff about this and they feel that it is best to only open source parts of the stdlib with concrete APIs, although more is coming in the future

So, things that are going to change significantly are held off for now. But stay tuned!
