### ISSUE TITLE
[BUG] Get item with slice syntax on `StaticTuple` crashes the parser

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#2086]
### Bug description

As title. Calling `__getitem__` throws the type error correctly.

### Steps to reproduce

```mojo
fn main():
  var t = StaticTuple[Int, 10]()
  t[:]
```

### System information

```shell
Mojo 24.2 on Docker, Intel Mac
```

**Comment by ematejska** [comment]
Crash I see is:
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.	Program arguments: mojo bla4.mojo
1.	Crash resolving decl body at loc("/Users/ewa/tmp/bla4.mojo":1:4)
    >> fn main():
          ^......
    >>   var t = StaticTuple[Int, 10]()
    >>   t[:]
       ......<
2.	Crash parsing statement at loc("/Users/ewa/tmp/bla4.mojo":3:3)
    >>   t[:]
         ^...<
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  mojo                     0x0000000100f53cd0 llvm_strlcpy + 54448
1  mojo                     0x0000000100f51e30 llvm_strlcpy + 46608
2  mojo                     0x0000000100f54370 llvm_strlcpy + 56144
3  libsystem_platform.dylib 0x0000000190a7ea24 _sigtramp + 56
4  mojo                     0x0000000101227a50 llvm_strlcpy + 3019312
5  mojo                     0x0000000101227a50 llvm_strlcpy + 3019312
6  mojo                     0x000000010125d098 llvm_strlcpy + 3238008
7  mojo                     0x000000010128c634 llvm_strlcpy + 3431956
8  mojo                     0x000000010128c078 llvm_strlcpy + 3430488
9  mojo                     0x0000000101224f00 llvm_strlcpy + 3008224
10 mojo                     0x0000000101223f40 llvm_strlcpy + 3004192
11 mojo                     0x0000000101225590 llvm_strlcpy + 3009904
12 mojo                     0x00000001012879e8 llvm_strlcpy + 3412424
13 mojo                     0x0000000101226184 llvm_strlcpy + 3012964
14 mojo                     0x0000000101226048 llvm_strlcpy + 3012648
15 mojo                     0x0000000101269f04 llvm_strlcpy + 3290852
16 mojo                     0x000000010126d9f4 llvm_strlcpy + 3305940
17 mojo                     0x0000000101260608 llvm_strlcpy + 3251688
18 mojo                     0x000000010129792c llvm_strlcpy + 3477772
19 mojo                     0x0000000101293a98 llvm_strlcpy + 3461752
20 mojo                     0x0000000101293934 llvm_strlcpy + 3461396
21 mojo                     0x000000010123b570 llvm_strlcpy + 3099984
22 mojo                     0x0000000101248484 llvm_strlcpy + 3152996
23 mojo                     0x0000000101248b24 llvm_strlcpy + 3154692
24 mojo                     0x0000000101251de8 llvm_strlcpy + 3192264
25 mojo                     0x0000000101252138 llvm_strlcpy + 3193112
26 mojo                     0x0000000100e8dab4
27 mojo                     0x0000000100ea445c
28 mojo                     0x0000000100e888a8
29 dyld                     0x00000001906f7f28 start + 2236
0x1048b1300 crashed!
Please file a bug report.
[44321:11275926:20240402,102747.735186:WARNING in_range_cast.h:38] value -634136515 out of range
[44321:11275926:20240402,102747.738962:WARNING crash_report_exception_handler.cc:257] UniversalExceptionRaise: (os/kern) failure (5)
zsh: segmentation fault  mojo bla4.mojo

**Comment by soraros** [comment]
Fixed in the latest nightly.
