### ISSUE TITLE
Partial installation issue for Mojo SDK on Fedora

### ISSUE THREAD

**Issue by Shreyan1** [modularml/mojo#2101]
For - `modular install max`

Please refer to the following .txt file for the error output.
[MojoSDK_Error.txt](https://github.com/modularml/mojo/files/14815228/MojoSDK.Error.txt)

**Comment by jackos** [comment]
Hi @Shreyan1 what operating system was this? It's missing some dynamic libraries that are in ubuntu 20.04 and 22.04

**Comment by Shreyan1** [comment]
> Hi @Shreyan1 what operating system was this? It's missing some dynamic libraries that are in ubuntu 20.04 and 22.04

Hi Jackos, I've used Fedora 39 for this. Are the missing library issues for Ubuntu applied to this as well ?

**Comment by jackos** [comment]
Hi @Shreyan1 yeah you can try this workaround to install Mojo on Fedora here: https://github.com/makism/mojo-on-fedora40

Closing in favor of the feature request: https://github.com/modularml/mojo/issues/2267
