### ISSUE TITLE
[Docs]The link in README to write your first Mojo program is valid.

### ISSUE THREAD

**Issue by workingloong** [modularml/mojo#2107]
### Where is the problem?

https://github.com/modularml/mojo/blob/main/README.md

### What can we do better?

There are two prefixed of `https://` in the link of "write your first Mojo program".
`[write your first Mojo program](https://https//docs.modular.com/mojo/manual/get-started/hello-world).`

**Comment by agardnerIT** [comment]
Title should be changed to `is invalid`. But I just hit this too

**Comment by renxida** [comment]
PR in.
