### ISSUE TITLE
[Feature Request] Remove `offset` method from `Reference`

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#2115]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

As title.

### What is your motivation for this change?

Safe reference shouldn't provide this unsafe capability.

### Any other details?

N/A.

**Comment by JoeLoser** [comment]
Thanks for filing this.  I still have a long backlog of internal GitHub issues to move to the public repo, and this is one of them!  Internally, in the original GitHub issue, we said:

> The `Reference` struct gained an offset method along the way, which is really bad:

It cannot ever be implemented safely, but `Reference` is a safe type.
It breaks the model for a reference - references are not pointers that can be moved around like a pointer. Use UnsafePointer for that just like "int*" vs "int&" in C++.

I don't think we should even make this an "unsafe_offset" method - it completely breaks the model for reference. IF we need it for internal implementation purposes, then please make it a global function like:

```
fn _unsafe_reference_offset(Reference) -> Reference
```

**Comment by StandinKP** [comment]
I would like to take this up. I just have a doubt. In cases where we are currently using the offset (used in utils/variant.mojo), what will be the alternative to replace this usage?

**Comment by StandinKP** [comment]
I am actually unable to test this due to #2144 @JoeLoser can you take a look once? Thanks

**Comment by JoeLoser** [comment]
`Reference` no longer has an offset method, closing this.
