### ISSUE TITLE
[mojo-stdlib] Rename `List.pop_back` to `List.pop`

### ISSUE THREAD

**Issue by lattner** [modularml/mojo#2117]
### Bug description

`pop_back` is the name of the std::vector thing in C++, but the Python list method calls this method `pop`.  I think we should rename it to align with Python

### Steps to reproduce

n/a

### System information

```shell
n/a
```

**Comment by JoeLoser** [comment]
@lattner see https://github.com/modularml/mojo/issues/2017 which I filed and there's already a [PR](https://github.com/modularml/mojo/pull/2041) for.  We'll remove `pop_back` once we have `pop` with a particular index in place.

**Comment by Benny-Nottonson** [comment]
Unlucky, just finished this and was about to PR
