### ISSUE TITLE
[Feature Request] Register Passable Variant

### ISSUE THREAD

**Issue by Benny-Nottonson** [modularml/mojo#2119]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

With the introduction of OptionalReg and the Open Sourcing of stdlib, Variant is trivially easy to make @register_passable (You can just add that decorator and make no other changes, all tests passing). 

### What is your motivation for this change?

As with OptionalReg, register passable structs give more flexibility, in this case for other register passable structures. In multiple of my projects, I have had to use Tuple with 'fake' values to create this same effect.

### Any other details?

N/A

**Comment by lattner** [comment]
This isn't the direction we want to take Mojo - we want to eliminate the need for types to be register passable.  The next update will include Tuple that allows arbitrary element types, a significantly upgraded pointer etc.
