### ISSUE TITLE
[Modular CLI] Can not install mojo via `modular install mojo`

### ISSUE THREAD

**Issue by thwzjx** [modularml/mojo#2120]
### Issue description

$ modular install mojo
# Found release for https://packages.modular.com/mojo @ 24.2.0-c2427bc5-release
# Downloading archive: packages/24.2.0-c2427bc5-release/mojo-arm64-apple-darwin22.6.0-24.2.0-c2427bc5-release-11-0.tar.gz
Done         [ ██████████████████████████████████████████████████████████████████████████████████████████████████████ ] 100%     167MiB/167MiB @  3.49MiB/s
# Extracting downloaded archives. 
# Extraction complete, setting configs...
# Configs complete, running post-install hooks...
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/private/var/folders/6g/n11_y75j2qb4ybfj9c780gy80000gn/T/modular/.modular_home/pkg/packages.modular.com_mojo/scripts/post-install/install-dependencies.py': [Errno 2] No such file or directory
modular: error: failed to run script
==========================
Failure Information:
        - Script: `PATH=/opt/homebrew/opt/python@3.11/libexec/bin:.package_path/bin:/Users/thw/.modular/pkg/packages.modular.com_mojo/bin:/Users/thw/.modular/pkg/packages.modular.com_mojo/bin:/Users/thw/.local/bin:/opt/homebrew/bin:/Users/thw/bin:/usr/local/bin:/opt/homebrew/opt/pyqt@6/bin:/opt/homebrew/opt/qt@6/bin:/opt/homebrew/Cellar/ruby/3.2.2/bin:/Users/thw/.gem/bin:/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia:/Users/thw/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/go/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Applications/quarto/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:.package_path/bin:/Users/thw/.modular/pkg/packages.modular.com_mojo/bin:/Users/thw/.local/bin:/opt/homebrew/bin:/Users/thw/bin:/opt/homebrew/opt/pyqt@6/bin:/opt/homebrew/opt/qt@6/bin:/opt/homebrew/Cellar/ruby/3.2.2/bin:/Users/thw/.gem/bin:/Users/thw/opt/anaconda3/bin:/Users/thw/opt/anaconda3/condabin:/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia:/Users/thw/.cargo/bin://flutter/bin:/Users/thw/Software/ruby/bin:/Users/thw/development/flutter/bin:/Users/thw/opt/anaconda3/bin/caj2pdf:/Users/thw/Documents/code/mojo/flutter/bin:/Users/thw/Software/ruby/bin:/Users/thw/development/flutter/bin:/Users/thw/opt/anaconda3/bin/caj2pdf HOME=/Users/thw MODULAR_HOME=.modular_home/usr/bin/python3 .modular_home/pkg/packages.modular.com_mojo/scripts/post-install/install-dependencies.py .modular_home/pkg/packages.modular.com_mojo .modular_home/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt`
        - Result: 2
        - Stderr:
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/private/var/folders/6g/n11_y75j2qb4ybfj9c780gy80000gn/T/modular/.modular_home/pkg/packages.modular.com_mojo/scripts/post-install/install-dependencies.py': [Errno 2] No such file or directory

==========================

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.6.0 (04c05243)
- What OS did you install modular CLI on ?
macos12 m1
```

**Comment by gautam-e** [comment]
I have an Apple MacbookPro M1 and appear to have a similar problem while I was trying to update mojo.

```
(base) gautam@GMacPro ~ % modular update mojo
# Found release for https://packages.modular.com/mojo @ 24.3.0
# Downloading archive: packages/24.3.0/mojo-arm64-apple-darwin22.6.0-24.3.0-13-0.tar.zst
Downloaded           [ █████████████████ ] 100% 86.9MiB/86.9MiB
# Running pre-uninstall hooks for the old version...
Error running pre-uninstall script:/Users/gautam/.modular/pkg/packages.modular.com_mojo/jupyter/manage_kernel.py
failed to run script: Executable "/Users/gautam/.modular/pkg/packages.modular.com_mojo/venv/bin/python" doesn't exist!
==========================
Failure Information:
	- Script: `PATH=/opt/homebrew/opt/python@3.11/libexec/bin:/Users/gautam/miniconda3/bin:/Users/gautam/miniconda3/condabin:/Users/gautam/.modular/pkg/packages.modular.com_mojo/bin:/opt/homebrew/opt/ruby/bin:/usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems/3.1.0/bin:/opt/homebrew/lib/ruby/gems/3.1.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Library/TeX/texbin:/Applications/quarto/bin HOME=/Users/gautam MODULAR_HOME=/Users/gautam/.modular PYTHONPATH=/Users/gautam/.modular/pkg/packages.modular.com_mojo/venv/lib/Users/gautam/.modular/pkg/packages.modular.com_mojo/venv/bin/python /Users/gautam/.modular/pkg/packages.modular.com_mojo/jupyter/manage_kernel.py uninstall --mojo-install-channel stable`
	- Result: -1

==========================

# Extracting downloaded archives.
Extracted            [ █████████████████ ] 100% 86.9MiB/86.9MiB
# Running post-install scripts...
Install Python Deps  [ ░░                ]   0%                               An error occurred when creating a virtual environment:
stdout:

stderr:
Error: [Errno 2] No such file or directory: '/Users/gautam/.modular/pkg/packages.modular.com_mojo/venv/bin/python3'

Traceback (most recent call last):
  File "/Users/gautam/.modular/pkg/packages.modular.com_mojo/scripts/post-install/install-dependencies.py", line 75, in <module>
    main()
  File "/Users/gautam/.modular/pkg/packages.modular.com_mojo/scripts/post-install/install-dependencies.py", line 56, in main
    _check_call(
  File "/Users/gautam/.modular/pkg/packages.modular.com_mojo/scripts/post-install/install-dependencies.py", line 22, in _check_call
    subprocess.run(
  File "/Users/gautam/miniconda3/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/Users/gautam/miniconda3/bin/python3', '-m', 'venv', '/Users/gautam/.modular/pkg/packages.modular.com_mojo/venv')' returned non-zero exit status 1.
Install Python Deps  [ ░░                ]   0%
modular: error: failed to run script

==========================
Failure Information:
	- Script: `PATH=/opt/homebrew/opt/python@3.11/libexec/bin:/Users/gautam/miniconda3/bin:/Users/gautam/miniconda3/condabin:/Users/gautam/.modular/pkg/packages.modular.com_mojo/bin:/opt/homebrew/opt/ruby/bin:/usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems/3.1.0/bin:/opt/homebrew/lib/ruby/gems/3.1.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Library/TeX/texbin:/Applications/quarto/bin HOME=/Users/gautam MODULAR_HOME=/Users/gautam/.modular/Users/gautam/miniconda3/bin/python3 /Users/gautam/.modular/pkg/packages.modular.com_mojo/scripts/post-install/install-dependencies.py /Users/gautam/.modular/pkg/packages.modular.com_mojo /Users/gautam/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt`
	- Result: 1
	- Stderr:
An error occurred when creating a virtual environment:
stdout:

stderr:
Error: [Errno 2] No such file or directory: '/Users/gautam/.modular/pkg/packages.modular.com_mojo/venv/bin/python3'

Traceback (most recent call last):
  File "/Users/gautam/.modular/pkg/packages.modular.com_mojo/scripts/post-install/install-dependencies.py", line 75, in <module>
    main()
  File "/Users/gautam/.modular/pkg/packages.modular.com_mojo/scripts/post-install/install-dependencies.py", line 56, in main
    _check_call(
  File "/Users/gautam/.modular/pkg/packages.modular.com_mojo/scripts/post-install/install-dependencies.py", line 22, in _check_call
    subprocess.run(
  File "/Users/gautam/miniconda3/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/Users/gautam/miniconda3/bin/python3', '-m', 'venv', '/Users/gautam/.modular/pkg/packages.modular.com_mojo/venv')' returned non-zero exit status 1.


==========================
```

**Comment by gautam-e** [comment]
Running `modular clean` and then re-running `modular install mojo` seems to rectify this issue for me.
