### ISSUE TITLE
[BUG] I can't figure out how to return multiple values in a function and use them

### ISSUE THREAD

**Issue by bserletfun** [modularml/mojo#2125]
### Bug description

I would expect something like this to work:
fn two_ints() -> (Int, Int) :
        return 3, 4
fn call_two_ints() :
        var a, b = two_ints()
        print("a:", a, "b:", b)

But I get:
expected name for 'var' declaration
        var (a, b) = two_ints()

What should the caller side look like? 

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
Latest mojo as of 2 days ago
```

**Comment by soraros** [comment]
Please consider using the forum for questions like this. Currently, the support for tuple unpacking is not complete, you will have to do this:

```mojo
fn f(...) -> Tuple[A, B]:
  ...

fn main():
  var a: A
  var b: B
  a, b = f(...)
```

**Comment by ematejska** [comment]
Closing and please use support forums as noted.

**Comment by bserletfun** [comment]
I think there's still a bug here: it should be easier, and more similar to python.

**Comment by soraros** [comment]
I agree, and it's already tracked in #2105.
If you find this feature important, please go upvote in the issue to help the team prioritise.
