### ISSUE TITLE
[BUG] Can't easily convert a PythonObject to a Float32

### ISSUE THREAD

**Issue by bserletfun** [modularml/mojo#2127]
### Bug description

The following code works:
```
fn py_to_f32(x: PythonObject) -> Float32:
    """ Convert a Python object to a Float32."""
    var f64: Float64 = x.to_float64()
    return Float32(f64)

```
but not:
```
fn py_to_f32(x: PythonObject) -> Float32:
    """ Convert a Python object to a Float32."""
    return x.to_float32(x)

```

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
Latest mojo
```

**Comment by soraros** [comment]
You can use `cast` on `SIMD`.

**Comment by bserletfun** [comment]
Can you give me the snippet of code to do that?

Also, isn't it a bug still that there is to_float64 but no to_float32?

**Comment by soraros** [comment]
```mojo
a.as_float64().cast[DType.float32]()
```

> Also, isn't it a bug still that there is to_float64 but no to_float32?

I guess it would be convenient to have one, however, Mojo supports a dozen of dtypes, do we simply add them all? I think having only `as_float64` on the Mojo-Python boundary strikes a fairly nice balance.

**Comment by bserletfun** [comment]
The snippet worked.
Your rationale makes sense.  Closing.
