### ISSUE TITLE
[BUG] Unclear how to make a function float-generic

### ISSUE THREAD

**Issue by bserletfun** [modularml/mojo#2129]
### Bug description

I'd like the following function to be generic and work for Float32 as well as Float64.
fn cap(x: Float32) -> Float32:
    """ Cap a value between -1. and 1."""
    if x < -1.0:
        return -1.0
    if x > 1.0:
        return 1.0
    return x

I dont know how to do that.

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
Latest mojo
```

**Comment by soraros** [comment]
This is not a bug, please use the discussions forum next time.

You could write such a function as:
```mojo
fn f[dt: DType, width: Int](arg: SIMD[dt, width]) -> SIMD[dt, width]:
  constrained[dt.is_floating_point()]()
  ...
```

**Comment by bserletfun** [comment]
Thank you that works.
