### ISSUE TITLE
[BUG] Unclear how to make function generic for any numeric type

### ISSUE THREAD

**Issue by bserletfun** [modularml/mojo#2130]
### Bug description

fn dist_arrays(x: List[Float32], y: List[Float32]) -> Float32:
    """ Cartesian Distance between two arrays."""
    if len(x) != len(y):
        abort("*** Arrays have different lengths")
    var dist: Float32 = 0.0
    for i in range(len(x)):
        var d: Float32 = x[i] - y[i]
        dist += d * d
    return math.sqrt(dist)

Also, is there a faster way to compute the norm of the difference between two vectors?

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
latest mojo
```

**Comment by soraros** [comment]
I believe your question is answered in #2129. Also, please ask such questions in the discussion forum.

**Comment by ematejska** [comment]
Closing because looks like a dup of https://github.com/modularml/mojo/issues/2129.

**Comment by bserletfun** [comment]
Thank you.  It works.
