### ISSUE TITLE
[BUG] Functions that work on SIMD vectors applied to a single value

### ISSUE THREAD

**Issue by bserletfun** [modularml/mojo#2131]
### Bug description

I wanted to count the number of bit sets in an integer (population count).
I found an SIMD API that I made to work with:
```
fn int_bit_count(x: UInt64) -> Int:
    """ Count the number of bits set to 1 in x."""
    var count = bit.ctpop[DType.uint64, 1](x)
    return Int(count.to_int())

```
Is that a good way - seems a bit contorted?
Is that the most efficient way?

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
latest mojo
```

**Comment by soraros** [comment]
It lowers to LLVM intrinsics, so yes, it's the most efficient way. There is no need to supply the parameters by hand, though. You could write the following or don't use the wrapper altogether.

```mojo
fn int_bit_count(x: UInt64) -> Int:
    return bit.ctpop(x).to_int()
```
