### ISSUE TITLE
[BUG] Missing a close paren in the middle of a file creates a parse error in a very different place

### ISSUE THREAD

**Issue by bserletfun** [modularml/mojo#2132]
### Bug description

It's a pain to debug (especially the first time when you dont know about this).

To reproduce, take a working project, and remove a ) in the middle of a file.
The error you get is not obvious...

### Steps to reproduce

* Include relevant code snippet or link to code that did not work as expected.
* If applicable, add screenshots to help explain the problem.
* If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
* Include anything else that might help us debug the issue.

### System information

```shell
latest mojo
```

**Comment by ematejska** [comment]
Is this in VSCode or on the commandline?

**Comment by bserletfun** [comment]
This is in VSCode.

**Comment by AmaranthineCodices** [comment]
I can't reproduce this anymore; parse errors due to missing parens always appear very close to the missing paren in my testing.
