### ISSUE TITLE
[Enhancement] List.resize takes a T even when you are shrinking the list

### ISSUE THREAD

**Issue by bserletfun** [modularml/mojo#2133]
### Bug description

I think it would be cleaner to have List.grow that takes a T and List.shrink that does not.

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
Latest mojo
```

**Comment by soraros** [comment]
Not a bug. Please write a feature request, and fill in all the fields.

**Comment by bserletfun** [comment]
I think there's a bug: I can't provide a T when I'm shrinking the list...

**Comment by mikowals** [comment]
This is added in nightly branch. See #2140.

**Comment by ConnorGray** [comment]
Closing as fixed by #2140, thanks!
