### ISSUE TITLE
[stdlib] Add `List.insert` method that inserts an item at a given index

### ISSUE THREAD

**Issue by bserletfun** [modularml/mojo#2134]
### Bug description

(with documentation that the performance is O(N))

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
latest mojo
```

**Comment by StandinKP** [comment]
Can I take this up and submit a PR?

**Comment by whym1here** [comment]
@StandinKP I have been working on some data structures in mojo (in private) for few days and I had already implemented it so I raised the pr my bad for not commenting it here. If you have any other suggestions or find any issue in my pr do let me know.

**Comment by StandinKP** [comment]
No problem @whym1here

**Comment by JoeLoser** [comment]
Fixed with https://github.com/modularml/mojo/commit/98e062dc1b70eaea349f6561ca14987d91d569a1
