### ISSUE TITLE
[Enhancemet] Add math.pi

### ISSUE THREAD

**Issue by bserletfun** [modularml/mojo#2135]
### Bug description

It's a useful number...

### Steps to reproduce

* Include relevant code snippet or link to code that did not work as expected.
* If applicable, add screenshots to help explain the problem.
* If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
* Include anything else that might help us debug the issue.

### System information

```shell
latest mojo
```

**Comment by StandinKP** [comment]
This shouldn't be a bug but a Feature Request
