### ISSUE TITLE
[BUG] [Refactor] `Slice.end` should not be default to `_int_max_value()`

### ISSUE THREAD

**Issue by LJ-9801** [modularml/mojo#2142]
### Proposal
defaulting `Slice.end` to -1 has several benefit. First of all, it avoids unsafe memory access in case it is used in the wrong way. Secondly, I saw most of the struct implements a `_adjust_span(self, span: Slice) -> Slice` method to round the slice. This refactor could simplify a lot of these method throughout the stdlib

```mojo
fn _adjust_span(self, span: Slice) -> Slice:
        """Adjusts the span based on the list length."""
        var adjusted_span = span

        if adjusted_span.start < 0:
            adjusted_span.start = len(self) + adjusted_span.start
        

        if not adjusted_span._has_end(): # <--- this if statement can be removed
            adjusted_span.end = len(self)
        elif adjusted_span.end < 0:
            adjusted_span.end = len(self) + adjusted_span.end

        if span.step < 0:
            var tmp = adjusted_span.end
            adjusted_span.end = adjusted_span.start - 1
            adjusted_span.start = tmp - 1

        return adjusted_span
```

### Steps to reproduce

see #1944 and #2046

**Comment by mikowals** [comment]
At the point where the Slice is created the length or size of the thing being sliced is not known.  So there is no way to use the last index to keep the slice in bounds.  `-1` as the end value can mean the last element when counting up or in the case of `step=-1` it may mean the first index to be excluded.  

So I think having a general Slice that works for all cases without having access to the length of the slicee, `Slice.start` and `Slice.end` need to be able to hold a `None` to reflect the programmers intent.

**Comment by mikowals** [comment]
I think this behaviour was changed by #2495 so this issue could close.
