### ISSUE TITLE
[BUG]     sep="       "  do not work

### ISSUE THREAD

**Issue by a62690705** [modularml/mojo#2161]
### Bug description

```mojo
struct GenericArray[T: AnyRegType]:
    var data: Pointer[T]
    var size: Int

    fn __init__(inout self, *elements: T):
        self.size = len(elements)
        self.data = Pointer[T].alloc(self.size)
        for i in range(self.size):
            self.data[i] = elements[i]

    fn __del__(owned self):
        self.data.free()

    fn __getitem__(self, i: Int) raises -> T:
        if i < self.size:
            return self.data[i]
        else:
            raise Error("Out of bounds")


def main():
    var array = GenericArray[Int](1, 2, 3, 4)
    for i in range(array.size):
      print(array[i], sep="		", end="")


Output

1234
``` 

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?   https://docs.modular.com/mojo/playground
- Provide version information for Mojo by pasting the output of `mojo -v`  24.2
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by HelloWorld-n** [comment]
It seems to me that since `array[i]` is only single element `sep` is not supposed to do anything.  

If `main` would look like
```
def main():
    var array = GenericArray[Int](1, 2, 3, 4)
    for i in range(array.size):
      print(array[i], sep="		", end="+")
    print("(")
    print(array[0], array[1], array[2], array[3], sep=", ", end="")
    print(")")
```

program prints 
```
1+2+3+4+(
1, 2, 3, 4)
```

Notably; in line above it prints `+` from `end` 4 times because it runs 4 times and doesn't use `sep` because there is only one argument.   
In line bellow there are 4 arguments so it prints `, ` from `sep` 3 times.

**Comment by soraros** [comment]
Indeed, `sep` only make sense when you use the variadic overload of the function. Python behaves the same way, and it's not a bug.

**Comment by JoeLoser** [comment]
As others said, this is working as intended.  The `sep` keyword only has meaning for printing a variadic number of things; it has no meaning when printing a single value.
