### ISSUE TITLE
[stdlib] [Feature Request] Allow List initalization from a raw pointer

### ISSUE THREAD

**Issue by MoSafi2** [modularml/mojo#2170]
### Review Mojo's priorities

- [x] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

As per title, add an initalizer to list to allow initlization from a Pointer gived the length of the data similair to Rust's [from_raw_parts](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.from_raw_parts).
Suggested signature: `(inout self: Self, owned ptr: AnyPointer,  length: Int, capacity: Int)`
This will allow fixing #2051 by eliminating unnecessary copying from the IO pointer and an empty list pointer

### What is your motivation for this change?

Currently, `FileHandle.read_bytes()` is **2x** slower than 24.1 implementation due to unnecessary copying of data which causes regression in many IO related tasks.

**Comment by JoeLoser** [comment]
This makes sense to me.  Are you interested in working on this?  I just added "good first issue" label in case you or others want to take it up.

**Comment by StandinKP** [comment]
I would like to take this up. @MoSafi2 if you aren't working on this @JoeLoser can you assign this to me?

**Comment by StandinKP** [comment]
@JoeLoser I created a PR but it doesn't link to this issue.
![image](https://github.com/modularml/mojo/assets/60636741/b7683684-c610-4eb3-a127-1d505866120d)
It doesn't show up here. Any suggestions?

**Comment by JoeLoser** [comment]
> @JoeLoser I created a PR but it doesn't link to this issue. ![image](https://private-user-images.githubusercontent.com/60636741/319437188-b7683684-c610-4eb3-a127-1d505866120d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMDUyNDIsIm5iZiI6MTcxMjIwNDk0MiwicGF0aCI6Ii82MDYzNjc0MS8zMTk0MzcxODgtYjc2ODM2ODQtYzYxMC00ZWIzLWExMjctMWQ1MDU4NjYxMjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA0MjkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMDQzOTkwYzEyZmU3NDBjMTY0OGNmNWNkYzdlZjg3M2MzM2U1YmVhYTY5MzNhMTJmYTU1MWU4YTcwYjQ2YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VT1o_JBx-EjvEN_w-Yx76Q5Uwsl2wDU7B04MGEHPcX4) It doesn't show up here. Any suggestions?

Hmm, that's weird.  It shows up fine on my end.  Do you not see this on this GitHub issue from your perspective?  Perhaps it's a setting I need to change at the repository level or something for contributors.  Please let me know.

<img width="1295" alt="Screenshot 2024-04-03 at 10 29 40 PM" src="https://github.com/modularml/mojo/assets/6462525/be6f2475-3415-4fa9-aad7-35af6f0fcc25">

**Comment by JoeLoser** [comment]
It doesn't link show the normal "pull request linked" from the view at https://github.com/modularml/mojo/issues/ I notice though.  So that's consistent for both of us it seems.  Any ideas why @ConnorGray?

**Comment by StandinKP** [comment]
It shows up in the Issue. Just not in the "pull request linked"

> Hmm, that's weird. It shows up fine on my end. Do you not see this on this GitHub issue from your perspective? Perhaps it's a setting I need to change at the repository level or something for contributors. Please let me know.

**Comment by StandinKP** [comment]
I can see it linked for this issue
https://github.com/modularml/mojo/issues/2045

**Comment by MoSafi2** [comment]
@StandinKP sure, happy that it can be added.

**Comment by JoeLoser** [comment]
Fixed with https://github.com/modularml/mojo/commit/c3361e8580cded34e488a42f5bdb1df516906c51
