### ISSUE TITLE
[stdlib] Optional.value should return a Reference

### ISSUE THREAD

**Issue by lsh** [modularml/mojo#2179]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

The Optional docs for `value()` state that it should return a `Reference` when that is possible. Since the underlying `Variant` already returns a reference which is then dereferenced, this should be possible now.

### What is your motivation for this change?

This is a planned feature per the comment on the method.

**Comment by StandinKP** [comment]
I will take this task up. Thanks

**Comment by StandinKP** [comment]
In this what should be passed into the lifetime component and the mutability component of the Reference?

**Comment by StandinKP** [comment]
@lsh I was working on this

**Comment by lsh** [comment]
@StandinKP didn't mean to step on any toes. This is a feature I wanted for a project, and I knew roughly how to wire up all the lifetimes and mutability in `Reference`, but am happy to close out in favor of whatever you have.

**Comment by StandinKP** [comment]
> @StandinKP didn't mean to step on any toes. This is a feature I wanted for a project, and I knew roughly how to wire up all the lifetimes and mutability in `Reference`, but am happy to close out in favor of whatever you have.

Nah man don't worry. Don't close it. I'll review the PR and let you know if any comments. Next time it would be good to ask so we won't be repeating efforts and we can grow this faster🤟🏻🤩
