### ISSUE TITLE
[Feature Request] Swift-style use of `?` in null handling

### ISSUE THREAD

**Issue by sa-** [modularml/mojo#221]
## Request

- Use `?` as a shorthand for `Optional[T]` like `Int?`
- This syntax: `object?.value ?? default_val`

### Motivation

Everyone who uses this feature in Kotlin/Zig/Swift describes it as pleasant. It's a good example of conciseness and clarity going hand in hand.

**Comment by lattner** [comment]
I'm familiar, I added that to swift and the rust folks adopted it from there.  Right now, we don't have optional types though, so we dont' need to track polish on top of the basic feature.  (Just trying to keep the bug tracker focused on actionable-in-the-near-term issues)
