### ISSUE TITLE
Problem installing on Sonomo

### ISSUE THREAD

**Issue by jonnyraync** [modularml/mojo#2210]
### Bug description

Mojo does not install.

### Steps to reproduce

curl -s https://get.modular.com | sh -
[modular install mojo.txt](https://github.com/modularml/mojo/files/14890613/modular.install.mojo.txt)
modular install mojo

### System information

```shell
- What OS did you do install Mojo on ?
Sonoma
- Provide version information for Mojo by pasting the output of `mojo -v`
Mojo did not install.
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.6.0 (04c05243)
```

**Comment by zbowling** [comment]
Hi! did you run `modular auth` first?

**Comment by jonnyraync** [comment]
YesSent from my iPhoneOn Apr 5, 2024, at 5:50 PM, Zac Bowling ***@***.***> wrote:﻿
Hi! did you run modular auth first?

**Comment by StandinKP** [comment]
I had no problems installing mojo as well as mojo nightly on Mac OS Sonoma 14.4.1. Can you provide more input on what exactly error are you facing?

**Comment by jonnyraync** [comment]
i posted a file in the bug report with the full set of messages as mojo tries to install. It appears that several artefacts are not built and/or cannot link.


________________________________
