### ISSUE TITLE
[BUG] `object` does not implement `__truediv__` or `__floordiv__`

### ISSUE THREAD

**Issue by Brian-M-J** [modularml/mojo#2224]
### Bug description

When running the code snippets linked below in the [Mojo Playground](https://docs.modular.com/mojo/playground), I get the following errors:

`__floordiv__` code:
```
/source/prog.mojo:2:20: error: 'object' does not implement the '__floordiv__' method
    return (x + y) // 2
           ~~~~~~~ ^
mojo: error: failed to parse the provided Mojo
```
It is supposed to print `1`

`__truediv__` code:
```
/source/prog.mojo:2:20: error: 'object' does not implement the '__truediv__' method
    return (x + y) / 2
           ~~~~~~~ ^
mojo: error: failed to parse the provided Mojo
```
It is supposed to print `1.5`

I consider this to be a bug as the exact same code works perfectly fine in Python.

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.

[`__truediv__` code](https://gist.github.com/modularbot/4aef64f85bccd1ad0fb1294a7a487e9f)

[`__floordiv__` code](https://gist.github.com/modularbot/64ca9ee9ce38d14552d79aa18ebeade2)

Just run the above snippets in the Playground.

### System information

```shell
I ran this on the Mojo Playground as of 06-04-2024.
```

**Comment by LJ-9801** [comment]
this seems to be in the TODO list of the object struct implementation 
https://github.com/modularml/mojo/blob/738901dec1058612d8f01fd13e13a3e09103944f/stdlib/src/builtin/object.mojo#L1326
https://github.com/modularml/mojo/blob/738901dec1058612d8f01fd13e13a3e09103944f/stdlib/src/builtin/object.mojo#L1327

There are other dunder methods such as mod, lshiift and rshift that has not been implemented yet. I can open a PR for now for the truediv and div?

**Comment by JoeLoser** [comment]
@LJ-9801 - these look like they all need to be implemented still for the builtin object type.  I'd definitely welcome a contributor for any/all that you're up for with this type.  Thank you for looking into this!

**Comment by JoeLoser** [comment]
Fixed in https://github.com/modularml/mojo/commit/dbe3deed799b032b5243de291f4a2f316029bb31
