### ISSUE TITLE
[Docs] Explain the different types of pointers and how to use them

### ISSUE THREAD

**Issue by a62690705** [modularml/mojo#2232]
### Where is the problem?

There is no explanation for pointer

### What can we do better?

 Explain the different types of pointers and how to use them

**Comment by AzizAlqasem** [comment]
The following thread on X might be helpful for the documentation:
https://x.com/Modular/status/1769823792527028471

The code can be found here:
https://github.com/modularml/devrel-extras/blob/main/tweetorials/pointers/pointers.mojo
