### ISSUE TITLE
[BUG] Incorrect Values When Accessing `StaticTuple` Elements via `as_ptr` Method

### ISSUE THREAD

**Issue by leandrolcampos** [modularml/mojo#2248]
### Bug description

When attempting to access elements of a `StaticTuple` using its `as_ptr` method, which returns a `Pointer` instance, and then applying the Pointer's `offset` and `load` methods, I encounter unexpected behavior.

### Steps to reproduce

Create a file `main.mojo` with the following code:

```mojo
from utils.static_tuple import StaticTuple


fn main() raises:
    var array = StaticTuple[Int, 4](1, 2, 4, 8)
    var base_ptr = array.as_ptr()

    for i in range(len(array)):
        var ptr = base_ptr.offset(i)
        print(
            "offset:",
            i,
            "address:",
            int(ptr),
            "value:",
            ptr.load(),
            "expected:",
            array[i],
        )

```

Then execute `mojo run ./main.mojo` in the terminal. You'll get an output similar to:

```bash
$ mojo run ./main.mojo
offset: 0 address: 140722544459608 value: 1 expected: 1
offset: 1 address: 140722544459616 value: 1 expected: 2
offset: 2 address: 140722544459624 value: 1 expected: 4
offset: 3 address: 140722544459632 value: 1 expected: 8
```

### System information

```shell
Ubuntu 22.04.3 LTS
modular 0.7.0 (487c2f88)
mojo 2024.4.818 (34399306)
```

**Comment by bgreni** [comment]
To make things even more fun I've noticed that running the above example with `-debug-level full` actually produces the correct results.

**Comment by leandrolcampos** [comment]
> To make things even more fun I've noticed that running the above example with -debug-level full actually produces the correct results.

Interesting. Maybe this is the reason the `test_tuple_pointer` unit test isn't failing.

**Comment by JoeLoser** [comment]
FYI @ConnorGray as I know you dug into this recently with the gep stuff. Mind chiming in here?

**Comment by JoeLoser** [comment]
Thanks for filing this GitHub issue!  I think @lattner fixed this internally the other day (xref internal commit https://github.com/modularml/modular/commit/e81cf8dd2e48bcd74bc6e86923fa8b0b5d536009).  It should get fixed in the next `nightly/mojo`.  Note: that commit removes the `as_ptr()` method completely from `StaticTuple`, but you can still use `address_of()` and friends and it should work fine now once the new `nightly/mojo` is available that contains this fix.

**Comment by leandrolcampos** [comment]
Thanks for the update!
