### ISSUE TITLE
[BUG] Memory leakage while accessing `data` pointer of a List

### ISSUE THREAD

**Issue by arvindavoudi** [modularml/mojo#2253]
### Bug description

When accessing the nth element (e.g., second) of a `List` in Mojo using its `data` pointer, the operations perform as expected until the final attempt. The last operation unexpectedly results in an incorrect, large integer value, possibly showing a memory leakage.

### Steps to reproduce

First let's see output of this code:
```mojo
from collections.list import List

def main():
    var x = List[Int](1,2,3)
    print(
      (x.data + 1).bitcast[Int]()[]
    )
```

- The Output:
```bash
8582818015747831309
```

Secondly, we try with this code below:
```mojo
from collections.list import List

def main():
    var x = List[Int](1,2,3)
    print(
      (x.data + 1).bitcast[Int]()[]
    )
    print(
      (x.data + 1).bitcast[Int]()[]
    )
```

- The Output:

```bash
2
3754896513848559274
```

Upon execution, the second print statement produces an unexpected value.

If we add another print statement to our code, we can easily identify that the issue always occurs when executing the last print statement.

```mojo
from collections.list import List

def main():
    var x = List[Int](1,2,3)
    print(
      (x.data + 1).bitcast[Int]()[]
    )
    print(
      (x.data + 1).bitcast[Int]()[]
    )
    print(
      (x.data + 1).bitcast[Int]()[]
    )
```

- The Output:

```bash
2
2
-105709693747326497
```

### System information

```shell
Issue persists on Playground and MacOS both running Mojo V24.2
```

### Note:
When running these codes on MacOS, 0 is always printed out instead of those big integers that we encounter in Mojo Playground.

**Comment by past-moon** [comment]
I believe your list is getting `__del__` as soon after you access the access `x.data`. The `List.data` value is an AnyPointer which won't keep the owned x alive, so the compiler `__del__`s it, as there are no more references to `x` after that point.

If you use the x after that point it should work. You can use the `keep` function as a no-op use of the variable.
```
from collections.list import List
from benchmark import keep

def main():
    var x = List[Int](1,2,3)
    var y = x.data + 1
    print(
      (x.data + 1).bitcast[Int]()[]
    )
    keep(x)
```

This just comes with the territory of using unsafe pointers, the compiler loses the ability to track ownership.

**Comment by arvindavoudi** [comment]
Thanks!

**Comment by soraros** [comment]
You could also use `_ = x` to keep `x` alive.
Here's some [ref](https://docs.modular.com/mojo/manual/lifecycle/death#benefits-of-asap-destruction).
