### ISSUE TITLE
[BUG] VSCode Language Server Crashes when capturing Variables on inner functions.

### ISSUE THREAD

**Issue by sibarras** [modularml/mojo#2266]
### Bug description

When a function is trying to capture a variable from the outside, the server crashes if the function signature doesn't contain the `capturing` keyword.

### Steps to reproduce

```mojo
fn main():
    var num = 4

    fn capture(v: Int) capturing -> Int:
        return num + v
```

This code works fine in both compiler and Language Server:

This one crashes the Language Server (5 times in 2 seconds) in Visual Studio Code. Still compiles an run.
```mojo
fn main():
    var num = 4

    fn capture(v: Int) -> Int:
        return num + v
```

This one works fine again, if the function has no arguments.
```mojo
fn main():
    var num = 4

    fn capture() -> Int:
        return num
```

### System information

```shell
- What OS did you do install Mojo on ? MacBook Pro M1 2020 14.4.1 (23E224)
- Provide version information for Mojo by pasting the output of `mojo -v` mojo 24.2.0 (c2427bc5)
- Provide Modular CLI version by pasting the output of `modular -v` modular 0.7.0 (487c2f88)
```

**Comment by River707** [comment]
Thanks for filing! This should be fixed in the next release!
