### ISSUE TITLE
[Feature Request] Fedora/RHEL Support

### ISSUE THREAD

**Issue by dmeaux** [modularml/mojo#2267]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

I would like official Fedora/RHEL support. I understand that some people have gotten it working, but I'm adding this issue as I would like it officially supported and don't see a submitted feature request for it.

### What is your motivation for this change?

Most of our clients use private clouds and development computers running on various Red Hat flavors of Linux.

**Comment by ematejska** [comment]
Thanks for filing.  For folks that would like to see this, please add your vote.

**Comment by jackos** [comment]
Workaround you can try to install Mojo on Fedora here: https://github.com/makism/mojo-on-fedora40

**Comment by jackos** [comment]
Workaround you can try to install Mojo on Fedora here: https://github.com/makism/mojo-on-fedora40

**Comment by walter-erquinigo** [comment]
We have just moved to a distribution based on conda/magic, so, even though we are actively not working on Fedora, it might just work now. Feel free to reopen if you have remaining issues.

**Comment by dmeaux** [comment]
:1st_place_medal: :1st_place_medal: :1st_place_medal: I just want to say, "THANK YOU!" :magic_wand: :fire: :racing_car: 

Magic, Mojo, and MAX are all working for me so far in Fedora 39, by simply following the steps to install Magic with curl and then setup Python and Mojo projects, even with rootless privileges. 

It was a simple, easy, and very smooth process to get it going.

Thank you, thank you, thank you!
