### ISSUE TITLE
[stdlib] String to Int conversion with specified base

### ISSUE THREAD

**Issue by artemiogr97** [modularml/mojo#2274]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

`int` function should be able to convert String to Int with bases from 2 to 36 included

### What is your motivation for this change?

python parity 😊

**Comment by ConnorGray** [comment]
Closing as this is fixed by #2273.
