### ISSUE TITLE
Is it possible to use numpy made to use in python without going through python in mojo?

### ISSUE THREAD

**Issue by SilmaliTech** [modularml/mojo#2278]
Numpy is a Python library used in Python.
If I want to use numpy in mojo, I have to go through python to use it. When I use numpy, can I use it directly in mojo without going through python?

**Comment by ematejska** [comment]
No, since numpy is in Python, it needs to use the Python interop if using from Mojo.  Please see: https://docs.modular.com/mojo/manual/python/
