### ISSUE TITLE
[Feature Request] Convert the stdlib bytes from `List[Int8]` to `List[UInt8]`

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [modularml/mojo#2317]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

This issue is a follow up to track the progress on the implementation of the proposal #2099 . @JoeLoser mentioned that Modular doesn't have the bandwidth internally to make the change in the stdlib, it's up to the community to do it. See [https://github.com/modularml/mojo/pull/2099#issuecomment-2060170092](https://github.com/modularml/mojo/pull/2099#issuecomment-2060170092)

We should convert all bytes usage from Int8 to UInt8. Here is some reference:

```
git grep 'List\[Int8\]' | cat - 
stdlib/src/base64/base64.mojo:    var out = List[Int8](capacity=length + 1)
stdlib/src/builtin/file.mojo:    fn read_bytes(self, size: Int64 = -1) raises -> List[Int8]:
stdlib/src/builtin/file.mojo:        var list = List[Int8](capacity=int(size_copy))
stdlib/src/builtin/hex.mojo:    var buf = List[Int8]()
stdlib/src/builtin/hex.mojo:    inout fmt: List[Int8],
stdlib/src/builtin/string.mojo:    alias _buffer_type = List[Int8]
stdlib/src/builtin/string.mojo:        var buf = List[Int8]()
stdlib/src/builtin/string.mojo:    fn as_bytes(self) -> List[Int8]:
stdlib/src/builtin/string.mojo:        var res = List[Int8]()
stdlib/src/builtin/string.mojo:        var res = List[Int8]()
stdlib/src/pathlib/path.mojo:    fn read_bytes(self) raises -> List[Int8]:
stdlib/src/utils/inlined_string.mojo:            var buffer = List[Int8](capacity=total_len)
stdlib/test/collections/test_list.mojo:    var some_list = List[Int8](new_pointer, size=3, capacity=5)
stdlib/test/collections/test_list.mojo:    initial_list = List[Int8](0, 1, 2)
stdlib/test/collections/test_list.mojo:    var some_list = List[Int8](
stdlib/test/utils/issue_13632.mojo:fn sum_items(data: List[Int8]) -> Int:
stdlib/test/utils/issue_13632.mojo:fn make_abcd_vector() -> List[Int8]:
stdlib/test/utils/issue_13632.mojo:    return List[Int8](97, 98, 99, 100)
```

It's possible that some of those usages don't need to be converted or that there are more, but it gives an overview of what to do. Don't hesitate to add unit tests if you're scared of breaking something.

### What is your motivation for this change?

The proposal was accepted.

### Any other details?

*No response*

**Comment by StandinKP** [comment]
Can we close this if this is merged?

**Comment by gabrieldemarmiesse** [comment]
I only did a small part of the work listed here, so I don't think we can close this issue yet

**Comment by pcc-phulgk** [comment]
Oh please let me know if I can help or any subtask I can pick up

**Comment by StandinKP** [comment]
Oh please let me know if I can help or any subtask I can pick up

**Comment by gabrieldemarmiesse** [comment]
There are a few things to do, but we might want to wait a few days that the number of PRs opened go down a bit. With so many PRs opened, that might lead to git conflicts later on. It would be a pain for all the contributors and maintainers to fix those conflicts

**Comment by JoeLoser** [comment]
Changing https://github.com/modularml/mojo/blob/4cbb4c81b787470286949386898d722483ab4ad3/stdlib/src/builtin/file.mojo#L275 `read_bytes` to return `List[UInt8]` seems like a nice thing to pick off next in the list towards this goal.

**Comment by StandinKP** [comment]
Sounds good. I'll pick this up @JoeLoser
