### ISSUE TITLE
[stdlib] Reverse iterator for Set and Dict

### ISSUE THREAD

**Issue by jayzhan211** [modularml/mojo#2325]
As a follow-up, we can go implement reverse iterator support for `Set` and `Dict`, right?  I'm happy to create some GitHub issues for that if anyone is interested in working on that.

_Originally posted by @JoeLoser in https://github.com/modularml/mojo/pull/2215#pullrequestreview-2001824680_
            
```[tasklist]
### Tasks
- [ ] Set
- [ ] Dict
```

I would like to work on this

**Comment by JoeLoser** [comment]
Thanks for filing this.  Should we make a `set` reverse-iterable?  Of note, Python's `set` isn't reversible, which surprised me.  However, there is a `dict_reversekeyiterator` in Python for example so that

```
ys = {"hello": 42, "bar" : 100}
for y in reversed(ys):
   print(y)
```

is well-formed for example.
