### ISSUE TITLE
[tools] [stdlib] API doc string validation

### ISSUE THREAD

**Issue by JoeLoser** [modularml/mojo#2331]
Now that other `mojo` tools understand the package name in the open-source standard library directory structure as of the recently `nightly/mojo` release, we can revive a fixed-up variant of the API doc string scripts removed in https://github.com/modularml/mojo/pull/2118.  I haven't checked, but `mojo doc` and friends should work.

I recommend we write it in Python probably for maintainability sake.  The high-level is we need to run API doc string validation script that runs on each module (directory) in `stdlib/src` and also `stdlib/test` (such as `test_utils`).  So we'll need to walk over those directories, find all the subdirectories (modules), and run `mojo doc -warn-missing-doc-strings` on each module.  The original PR had some bugs in that script with the arguments, but the ideas presented in this GitHub issue point in the right direction.

It's desirable to have this check externally in our CI since we have this check internally in a different shape/form tied in at our build system and CI level.  When we import PRs, we don't want things to pass external CI and then fail internal CI for things like this; it's not an effective use of maintainer's time.

FYI @ConnorGray (but external contributors also may be interested in this).  I can do this too if nobody else gets to it soon.

Note:
- I think the current top of tree in the `nightly` branch may fail some API doc string validation that we may need to fix up.

**Comment by sarfarazsiddiquii** [comment]
hi @JoeLoser i can take this issue.
can you assign me?

**Comment by JoeLoser** [comment]
> hi @JoeLoser i can take this issue. can you assign me?

Assigned! Feel free to ping if you want any help or run into issues, and I'm happy to help out here.

**Comment by sarfarazsiddiquii** [comment]
Thanks, @JoeLoser, I'm considering developing a Python script to automate the validation of documentation strings. The script will be placed in the root directory and utilize the `subprocess` module to execute the `mojo doc -warn-missing-doc-strings` command on every module within the `stdlib/src and stdlib/test` directories.

It will iterate through these directories, run the command for each module, capture the output, and identify any warnings about missing documentation strings.

Please let me know if this proposed solution sounds appropriate, or if you have any other suggestions before I proceed with implementing the script

**Comment by JoeLoser** [comment]
> Thanks, @JoeLoser, I'm considering developing a Python script to automate the validation of documentation strings. The script will be placed in the root directory and utilize the `subprocess` module to execute the `mojo doc -warn-missing-doc-strings` command on every module within the `stdlib/src and stdlib/test` directories.
> 
> It will iterate through these directories, run the command for each module, capture the output, and identify any warnings about missing documentation strings.
> 
> Please let me know if this proposed solution sounds appropriate, or if you have any other suggestions before I proceed with implementing the script

Seems reasonable, but I think we can keep it even simpler after playing around with it a bit.  I think we can get a lot of mileage just with:

```
mojo doc -warn-missing-doc-strings -o /dev/null stdlib/src/
```

for example (and **don't run this on the test directory**).

Of note, the current `nightly` branch has a few doc string things to fix as seen from the command above:

```
mojo doc -warn-missing-doc-strings -o /dev/null stdlib/src/
Included from /Users/joe/dev/mojo/stdlib/src/builtin/__init__.mojo:1:
/Users/joe/dev/mojo/stdlib/src/builtin/reversed.mojo:77:4: warning: function takes parameters, but no 'Parameters' in doc string
fn reversed[
   ^
Included from /Users/joe/dev/mojo/stdlib/src/testing/__init__.mojo:1:
/Users/joe/dev/mojo/stdlib/src/testing/testing.mojo:115:4: warning: function takes parameters, but no 'Parameters' in doc string
fn assert_equal[T: Testable](lhs: T, rhs: T, msg: String = "") raises:
   ^
Included from /Users/joe/dev/mojo/stdlib/src/testing/__init__.mojo:1:
/Users/joe/dev/mojo/stdlib/src/testing/testing.mojo:175:4: warning: function takes parameters, but no 'Parameters' in doc string
fn assert_not_equal[T: Testable](lhs: T, rhs: T, msg: String = "") raises:
   ^
Included from /Users/joe/dev/mojo/stdlib/src/collections/__init__.mojo:1:
/Users/joe/dev/mojo/stdlib/src/collections/optional.mojo:103:8: warning: function takes parameters, but no 'Parameters' in doc string
    fn value[
```

We fixed these internally when importing all the PRs recently, but I think setting up the tooling/scripting to automate this to prevent future issues here in the public repo would be helpful.  We'd want this to hook into CI stuff in https://github.com/modularml/mojo/blob/e2dc80e68466e754a5f8e21e92a46e48beb3d663/.github/workflows/standard_library_tests_and_examples.yml.

**Comment by sarfarazsiddiquii** [comment]
Thank you, @JoeLoser, for providing a straightforward solution. 
The warnings from stdlib/src/ have been resolved and integrated into CI.

![Screenshot 2024-04-20 033443](https://github.com/modularml/mojo/assets/102226735/24e55406-ab20-42f7-8226-2766738c2b24)

**Comment by sarfarazsiddiquii** [comment]
I am having trouble making a pull request, but before that i think we must look into warnings from `stdlib/test` too.
I would like some assistance since we cant run `mojo doc -warn-missing-doc-strings ` in test module.

**Comment by JoeLoser** [comment]
> I am having trouble making a pull request, but before that i think we must look into warnings from `stdlib/test` too. I would like some assistance since we cant run `mojo doc -warn-missing-doc-strings ` in test module.

I think there's nothing to do actually for now in running the `mojo doc -warn-missing-doc-strings` on anything in the `stdlib/test` directory.  We don't do that internally in our test file (or even `test_utils`).  So it's safe to skip that for now — sorry if that caused you some confusion.

**Comment by sarfarazsiddiquii** [comment]
That's fine, Thank you for your help.
I will make a new pr now that closes the issue.

**Comment by sarfarazsiddiquii** [comment]
@JoeLoser Thank you for the help.
I have made a PR that closes the issue. Please review it and ping me if any changes are required.
