### ISSUE TITLE
So far I love what I see.  but variable declarations are weird

### ISSUE THREAD

**Issue by flyingwolf1701** [modularml/mojo#2333]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

I don't understand why you chose to use the key word "let" for your immutable variables. as near as I can tell Swift is the only language that does that. And that's probably cause apple likes to flip all the standards. 

Almost all other C based languages have const as immutable and let or var be mutable. 

### What is your motivation for this change?

Considering that the goal of this language is to make it so that Python dev's can onboard with it really fast I would suggest staying with the standards of C based languages. 

Also, I know that I am a bit biased as JavaScript is my primary language, but I would imagine that you will be getting a lot of JavaScript users as well, And since it is the most used language, I would suggest if you have a choice of a pattern to follow it would help adoption if you followed patterns that more dev's are familiar with. Especially because I doubt you are going to be getting Rust or Swift dev's to switch languages. But Dev's who are newer are going to gravitate towards things that have patterns they are familiar with. 

Honestly, I know it is too late for that observation. So feel free to mark this as resolved.

**Comment by arthurevans** [comment]
I think you may be looking at some older content. A [proposal to remove `let`](https://github.com/modularml/mojo/blob/main/proposals/remove-let-decls.md) was circulated in December, and the `let` keyword was removed entirely in the 24.2 release. Mojo currently only supports `var` variables (and undeclared variables a la Python inside `def` functions or in top-level code in the REPL).

**Comment by arthurevans** [comment]
I also spent a lot of time working in JavaScript, and the immutable `let` messed with my head, too. But since we've already removed `let`, I'm going to close this as resolved. If you see any reference to `let` in the current docs or examples, please open a PR or file a bug!
