### ISSUE TITLE
[stdlib] Add `divmod` for `SIMD` and `Int` types

### ISSUE THREAD

**Issue by JoeLoser** [modularml/mojo#2335]

**Comment by gabrieldemarmiesse** [comment]
Maybe we could elaborate about how it differs from https://github.com/modularml/mojo/pull/2097 ? Do you mean to move `math.divmod`?

**Comment by JoeLoser** [comment]
> Maybe we could elaborate about how it differs from #2097 ? Do you mean to move `math.divmod`?

For the `Int` case, we already have `_divmod`; I think we should just make it public for starters. WDYT?

**Comment by gabrieldemarmiesse** [comment]
Mmmhhh maybe I should reopen #2097 then? I'm not sure I understand what's different between what is asked and my previous PR
