### ISSUE TITLE
Cannot install Modular in my M1

### ISSUE THREAD

**Issue by staruhub** [modularml/mojo#2338]
### Bug description

When I try to install modular on my M1, I hit below issue.
I put this command in my shell:
- brew install modularml/packages/modular

It returns:
- modular:The arm64 architecture is required for this software.
- Error: modular: An unsatisfied requirement failed this build.

I tried to use brew info like below:
- brew info modularml/packages/modular`

It returns:

> Modular developer CLI tool
> https://www.modular.com
> Not installed
> From: https://github.com/modularml/homebrew-packages/blob/HEAD/Formula/modular.rb
> ==> Dependencies
> Required: python@3.11 ✔
> ==> Requirements
> Required: arm64 architecture ✘, macOS ✔
> ==> Caveats
> The Modular tool expects or will create a MODULAR_HOME directory.
> This defaults to `~/.modular`. You can create your own, and if you do,
> please add `MODULAR_HOME=/path/to/your/dir` to your environment.

I am using M1, how do I solve this?

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
M1
- Provide version information for Mojo by pasting the output of `mojo -v`
zsh: command not found: mojo
- Provide Modular CLI version by pasting the output of `modular -v`
zsh: command not found: modular
```

**Comment by ematejska** [comment]
Since, this is at the modular tool install level, adding modular CLI label.

**Comment by bwiedmann** [comment]
Did you check #1592?

**Comment by jackos** [comment]
Hi @staruhub following the comment in https://github.com/modularml/mojo/issues/1592#issuecomment-1876677473 should resolve your issue. Please reopen if it's still not working
