### ISSUE TITLE
Allow usage of `nightly` on the online playground

### ISSUE THREAD

**Issue by Moosems** [modularml/mojo#2345]
### Discussed in https://github.com/modularml/mojo/discussions/2321

<div type='discussions-op-text'>

<sup>Originally posted by **Moosems** April 17, 2024</sup>
I don't have enough RAM for a VM or to run docker and keep open the docs and rely on the online playground to run my Mojo code. If there was a small dropdown that would allow me to swap from the main to nightly compiler, that would be really awesome.</div>

**Comment by JoeLoser** [comment]
FYI @amscanne for routing this request to the appropriate team.

**Comment by Moosems** [comment]
So there an appropriate repo to leave playground requests on?
