### ISSUE TITLE
[BUG] `__getitem__` / `__refitem__` on the same type.

### ISSUE THREAD

**Issue by lsh** [modularml/mojo#2372]
### Bug description

Filing to follow up on #2294. Defining `__getitem__` as:

```mojo
fn __getitem__(self, idx: Int) -> Self.ElementType:
    return self.__refitem__(idx)
```

(apparently) fails on top of tree.

### Steps to reproduce

See above

### System information

```shell
N/A
```

**Comment by JoeLoser** [comment]
FYI @lattner - see my comment [on the `InlineArray` PR](https://github.com/modularml/mojo/pull/2294#issuecomment-2068056757).
