### ISSUE TITLE
[BUG] The `and` and `or` operators produce incorrect results with SIMD inputs

### ISSUE THREAD

**Issue by leandrolcampos** [modularml/mojo#2374]
### Bug description

The `and`  and `or` operators produce incorrect results when they are applied to SIMD inputs.

### Steps to reproduce

Run the following program:

```mojo
fn main():
    var a = SIMD[DType.bool, 4](True, True, False, False)
    var b = SIMD[DType.bool, 4](True, False, False, False)

    print("and:", a and b)
    print("  &:", a & b)

    print("")
    print(" or:", a or b)
    print("  |:", a | b)
```

The program prints:

```
and: [True, True, False, False]
  &: [True, False, False, False]

 or: [True, False, False, False]
  |: [True, True, False, False]
```

The outputs of `&` and `|` are correct.

### System information

```shell
Ubuntu 22.04.3 LTS
mojo 2024.4.1618 (37a3e965)
modular 0.7.0 (487c2f88)
```

**Comment by VMois** [comment]
I can reproduce.

**Comment by soraros** [comment]
`a and b` is really `a if bool(a) else b`, which can be confusing. We are moving away from `Boolable` `SIMD` when `size > 1`.

**Comment by leandrolcampos** [comment]
I'm closing this issue because the same subject was discussed in #252 and #275.
