### ISSUE TITLE
[Feature Request] More precise assertation failure information need to be provided

### ISSUE THREAD

**Issue by zhoujingya** [modularml/mojo#2379]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

when I worked on #2378, I wrote some test cases, but the assertation failure only told me i failed my test, but I didn't know the error line and column
```
Unhandled exception caught during execution: AssertionError: condition was unexpectedly False
mojo: error: execution exited with a non-zero result: 1
```
when we added too many test cases later, I think it was not friendly for our developers to find the precise source code information

### What is your motivation for this change?

More precise assertation failure information

**Comment by gabrieldemarmiesse** [comment]
Stacktraces :heart:

**Comment by mikowals** [comment]
testing.assert_... function now print the file and line number when there is a failure.  See this [commit](https://github.com/modularml/mojo/commit/52ceff7b986d6022fd8c82a49702729b176de0d3).  

So I think this issue can be closed.

**Comment by JoeLoser** [comment]
Yep, I'm going to close this issue as have the source location now plumbed through in the assert functions. Thanks @laszlokindrat for making this happen! Stack traces from Mojo programs are a whole separate beast. Feel free to a separate GitHub issue for that, but it's well known internally that users would like that.
