### ISSUE TITLE
[Feature Request] Support Intel GPU

### ISSUE THREAD

**Issue by a62690705** [modularml/mojo#2393]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Support Intel GPU

### What is your motivation for this change?

Support Intel GPU

**Comment by martinvuyk** [comment]
As long as the hardware vendors add MLIR interfaces it will be compatible in the future [(Mojo FAQ)](https://docs.modular.com/mojo/faq#who-writes-the-software-to-add-more-hardware-support-for-mojo). Of course it still needs work. You can directly [import and call C/C++ methods](https://docs.modular.com/mojo/faq#who-writes-the-software-to-add-more-hardware-support-for-mojo) if you want

**Comment by martinvuyk** [comment]
[yes](https://github.com/intel/mlir-extensions)

**Comment by martinvuyk** [comment]
It most probably is in their plans to add GPU access. But I don't know what you mean by soon.. It's a 1 year old language after all

**Comment by a62690705** [comment]
Chris said that support for graphics processing units is coming this summer, that is, the second quarter. Almost a month has passed in the second quarter, and I do not know whether this will happen or not.

**Comment by lattner** [comment]
We've announced support for nvidia gpus is coming this summer, we haven't discussed any other hardware.  I'd recommend contacting Intel about this.  Thank you!

**Comment by a62690705** [comment]
Does this mean that Mojo will not support Intel GPU never

**Comment by a62690705** [comment]
Most artificial intelligence developers in Egypt use the Windows operating system, and I am one of them. I have confidence in your ability to support Windows this year, perhaps in the third quarter of the current year, I think, isn’t it, perhaps? 🥺

**Comment by martinvuyk** [comment]
use the [docker image](https://github.com/modularml/mojo/tree/main/examples/docker)
