### ISSUE TITLE
[stdlib] Add unit tests for the SIMD __rfloordiv__() method and constraint check on the element types

### ISSUE THREAD

**Issue by peymanbr** [modularml/mojo#2415]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

The Int and Object types support __rfloordiv__. I added this method to the SIMD type in this PR:
https://github.com/modularml/mojo/pull/2414

### What is your motivation for this change?

Extending the SIMD type to support more math operations.

**Comment by peymanbr** [comment]
Since the SIMD type already includes mod() and rmod(), I have added rfloordiv() for greater comprehensiveness in built-in types. Additionally, the Int and Object types also support this method.
@JoeLoser I would appreciate it if you could assign this issue to me and review the PR.

**Comment by gryznar** [comment]
This issue is missing title :)

**Comment by StandinKP** [comment]
I will take this up if noone is working on this.

**Comment by peymanbr** [comment]
It's already assigned to me and there is a PR for the issue.

**Comment by StandinKP** [comment]
Oh. Np I couldn't see any PR in this thread. Didn't see it was already assigned🤟🏻

**Comment by gabrieldemarmiesse** [comment]
Maybe we can close this PR as this has already been implemented in https://github.com/modularml/mojo/commit/f5aee408379ae336d5f877694ddc7128d9bd9bb1 ?

**Comment by peymanbr** [comment]
In https://github.com/modularml/mojo/pull/2414 I added unit tests and the constraint check for `__rfloordiv_` method that was added in https://github.com/modularml/mojo/commit/f5aee408379ae336d5f877694ddc7128d9bd9bb1
and changed the issue's title.
