### ISSUE TITLE
[BUG] Eager copying of `struct` even though no mutation occurs

### ISSUE THREAD

**Issue by Brian-M-J** [modularml/mojo#2416]
### Bug description

Mojo aims to provide copy-on-write semantics, so programmers do not have to pay a price to reassign data if no mutation occurs. However, in the snippet linked below, even though no mutation is performed, the value of `demo_obj_1` is copied eagerly as demonstrated by the output:
```
Called constructor for DemoStruct(List(1, 2, 3, 4, 5))
Called copy constructor for DemoStruct(List(1, 2, 3, 4, 5))
DemoStruct(List(1, 2, 3, 4, 5))
Calling destructor for DemoStruct(List(1, 2, 3, 4, 5))
DemoStruct(List(1, 2, 3, 4, 5))
Calling destructor for DemoStruct(List(1, 2, 3, 4, 5))
```
This introduces unnecessary run-time costs into the program.

### Steps to reproduce

Run this snippet in the playground: https://gist.github.com/modularbot/6aed759930420cd70f38795dbcb874fe

### System information

```shell
The Mojo playground as of 26-04-2024
```

**Comment by Brian-M-J** [comment]
> This is working as intended per @jpamer

I don't fully understand what you mean. It's [mentioned](https://www.modular.com/blog/mojo-vs-rust-is-mojo-faster-than-rust) that:
> Because `String` implements a copy constructor, it's able to be moved into `bar` and leave behind a copy. Under the hood this is still passing by reference for maximum efficiency, it'll only create a copy if `foo` is mutated.

...but as demonstrated [here](https://gist.github.com/modularbot/2be7ca18bd18cb20ec08538b38515aaf), a copy is in fact created as demonstrated by the output (even though no mutation occurs):
```
Called __init__ for DemoStruct(String("foo"))
Called __copyinit__ for DemoStruct(String("foo"))
Called __del__ for DemoStruct(String("foo"))
Called bar with argument: DemoStruct(String("foo"))
DemoStruct(String("foo"))
Called __del__ for DemoStruct(String("foo"))
```
`__copyinit__` is in fact called, and `__del__` is called twice. This seems to contradict the statement in the blog post that Mojo enforces copy-on-write semantics.

I say "Mojo enforces COW" and not "`String` enforces COW" because it's not like `String` has some special magic code to enforce COW. Its `__copyinit__` just calls  `List`'s `__copyinit__`, which is [nothing special](https://github.com/modularml/mojo/blob/nightly/stdlib/src/collections/list.mojo#L169). So I can only assume it's the compiler that reasons about mutation and eliminates copies as necessary. Type authors don't have to worry about it.

**Comment by soraros** [comment]
> Mojo enforces COW

Citation needed.

**Comment by Brian-M-J** [comment]
> Citation needed.

I already gave it:

> it'll only create a copy if `foo` is mutated

> it's not like String has some special magic code to enforce COW. Its `__copyinit__` just calls List's `__copyinit__`, which is [nothing special](https://github.com/modularml/mojo/blob/nightly/stdlib/src/collections/list.mojo#L169)

**Comment by soraros** [comment]
I think you misunderstood what Jack wrote in the blog, he was talking about owned argument and move. `String` doesn't have COW semantics, and it is certainly not enforced by the language. I guess we could expect the compiler to eliminate more unnecessary copy, but I don't think that optimisation is/can be guaranteed (consider when `__copyinit__` has other side effect).

```mojo
fn main():
  var a: String = "a"
  var b = a  # a copy is created here

  ...
```
