### ISSUE TITLE
[BUG] Excessive memory usage during compilation of large StaticIntTuble

### ISSUE THREAD

**Issue by MoSafi2** [modularml/mojo#2424]
### Bug description

As per title, compilation of code requiring initilizatio of large StaticIntTuble is associated with excessive memory consumption. 
```mojo
var x = StaticIntTuple[30_000]()
print(x[0])
```
When running `mojo build <file_name.mojo>` mojo would allocate 28 GB during compilation but the resulting binary would consume trivial resources. 
The resouce consumption during compilation is also proprotional to the `StaticIntTuple` size with size 50_000 not compiling on my system and size 20_000 associated with only 10GB memory usage.

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ? Ubuntu 24.04 LTS, also reproducible on Ubuntu 22.04 LTS running in a VM
- Provide version information for Mojo by pasting the output of `mojo -v`  Mojo nightly mojo 2024.4.2621 (6dff3016)
- Provide Modular CLI version by pasting the output of `modular -v` modular 0.7.2 (d0adc668)
```

**Comment by VMois** [comment]
I can reproduce with mojo 24.2.1 (2f0dcf11). I can see a spike to 22GB and it will probably go even more.

**Comment by VMois** [comment]
The size of the binary for size 20k on MacOS was 577KB.
