### ISSUE TITLE
[stdlib] Add `__refitem__` to `List`

### ISSUE THREAD

**Issue by JoeLoser** [modularml/mojo#2432]
As the [TODO](https://github.com/modularml/mojo/blob/d344d178aec2b80c5772261b8a6e441202a752de/stdlib/src/collections/list.mojo#L516) suggests, rename `__get_ref` to be `__refitem__`.  Then, we can remove `List.__getitem__`.  This will require fixing up a bunch of callers that previously were using `List.__getitem__` to now dereferenced the returned `Reference` from `List.__refitem__`, e.g. `my_list[some_index][]`.

**Comment by StandinKP** [comment]
I can take this up @JoeLoser

**Comment by JoeLoser** [comment]
> I can take this up @JoeLoser

I appreciate the enthusiasm, but unfortunately this one may be blocked on https://github.com/modularml/mojo/issues/2441 as @mikowals started taking a look at this I think.

**Comment by JoeLoser** [comment]
Blocked by https://github.com/modularml/mojo/issues/2441

**Comment by StandinKP** [comment]
No problem. LMK if I should take up anything on priority or I can browse through some of the older issues and pick sth up @JoeLoser

**Comment by JoeLoser** [comment]
> No problem. LMK if I should take up anything on priority or I can browse through some of the older issues and pick sth up @JoeLoser

Will certainly do! I'm planning on adding several GitHub issues to the public repo this week, so stay tuned 😄

**Comment by StandinKP** [comment]
Perfect🔥

**Comment by JoeLoser** [comment]
Removed blocked label since it appears to have been a user error. See my comment at https://github.com/modularml/mojo/issues/2441#issuecomment-2082732920
