### ISSUE TITLE
[Feature Request]  Provide an option to make `mojo doc` fail if any warnings are triggered

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [modularml/mojo#2447]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

We would like to use this option in the CI to ensure every docstring has the appropriate fields. We can do this by checking the stderr manually, but this does not seem very future-proof if something else than warnings are one day written to stderr.

### What is your motivation for this change?

See @JoeLoser 's comment here also: https://github.com/modularml/mojo/pull/2344#discussion_r1573831595

### Any other details?
See this PR: https://github.com/modularml/mojo/pull/2444 where we have to manually parse stderr

**Comment by JoeLoser** [comment]
FYI @modocache @River707
