### ISSUE TITLE
[Feature Request] Add a way for `print` to print to stderr

### ISSUE THREAD

**Issue by modocache** [modularml/mojo#2453]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

In Python, we can print to stderr like so:

```python
import sys
print("hi", file=sys.stderr)
```

I'd like to accomplish the same thing in Mojo, but I believe the Mojo print function (as documented [here](https://docs.modular.com/mojo/stdlib/builtin/io#print)) can only print to `stdout` right now.

### What is your motivation for this change?

I'm developing a command-line tool written in Mojo, and I wish to print error messages. These are typically printed to `stderr`.

### Any other details?

This is a good first issue for new contributors, since it just requires some light plumbing to specify `_fdopen.STDOUT` or `_fdopen.STDERR` (defined [here](https://github.com/modularml/mojo/blob/432b2c1c966b8f2d9866d0b5257ab603aacd62d1/stdlib/src/builtin/io.mojo#L52-L54)) when calling `print`. Mojo supports keyword arguments, so one option would be to add a `file=` keyword argument similar to the one supported by Python's `print` function.

Tests also ought to be added to ensure that what's bring printed is actually being written to stderr.

**Comment by JoeLoser** [comment]
Thanks for migrating this issue to the public repo!  I agree this would get a good first issue for new contributors.
