### ISSUE TITLE
[Feature Request] Implement `__repr__` for all the major types in the stdlib

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [modularml/mojo#2458]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

This issue is a follow up on https://github.com/modularml/mojo/issues/2207 and https://github.com/modularml/mojo/pull/2361 .

We now have a `Representable` trait and more of our types in the mojo stdlib should have this trait. For some types like `List` or `Dict` it's not possible to add the trait but it's still possible to have a `__repr__` static method. You can take a look at how `__str__` is implemented there.

If you are unsure about what the representation of a struct should look like, you can use these two guidelines:
* Take a look at what `repr()` does in Python for a similar object
* Take a look at [the python docs](https://docs.python.org/3/reference/datamodel.html#object.__repr__) explaining the difference with `__str__`. Long story short, the output of `__repr__` should be an unambiguous string that is a valid Mojo expression (you should be able to copy-paste it into a Mojo file to re-create the object).

### What is your motivation for this change?

`__repr__` is useful for many things. One is debugging, the other is to be able to implement `__str__` for containers. Long term, the debugger will call `repr(my_object_to_inspect)` and `assert_equal()` will call the `repr()` function when creating the error message.

**Comment by whym1here** [comment]
Can I work on this issue?

**Comment by gabrieldemarmiesse** [comment]
Sure thing, you don't need to ask :)

**Comment by jayzhan211** [comment]
@whym1here What types had you worked on already? I would like to help on this issue since it is really helpful for debugging

**Comment by JoeLoser** [comment]
I think this issue is mostly done at this point, but feel free to open a new issue for any other core types missing `repr` dunder method.
