### ISSUE TITLE
[Feature Request] Jetbrains Pycharm Integration at Language Launch

### ISSUE THREAD

**Issue by NickW3101** [modularml/mojo#246]
## Request
Work with the Jetbrains/Pycharm team early and often to have their IDE tool ready for Mojo developers at launch.  

 Pycharm is the most powerful Python IDE and their tutorial feature could help speed up the adoption of Mojo when you guys release the language.  

### Motivation
Jetbrains could help simplify adoption of Mojo for Python developers.   

  Tooling will make or break the language.  Working with Jetbrains could help Mojo support world class tooling at launch.  

### Description and Requirements
Similar integration for Mojo to what Python has with Pycharm.

**Comment by Mogball** [comment]
Thanks for filing! I agree that this would be nice to have on launch, but it's a bit of a stretch given the our goal of focusing on building out the core language at the moment, so I am closing this issue for now.

**Comment by Vivraan** [comment]
Hey! Now that a year has passed, maybe it'd be a nice idea to reconsider this feature request?
