### ISSUE TITLE
[Feature Request] Introduce Ordering trait

### ISSUE THREAD

**Issue by jayzhan211** [modularml/mojo#2462]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

We have `EqualityComparable` trait for `eq` and `ne`.

But, that is not enough to implement comparison function, like sorting

I think we need to introduce trait like
```mojo
trait OrderingComparable:
  fn __lt__():  1 < 2
  fn __gt__(): 2 > 1
  fn __le__():  1 <= 2
  fn __ge__(): 2 >= 1
```

There might be a better name for `OrderingComparable`.

### What is your motivation for this change?

Having trait for comparison function

**Comment by JoeLoser** [comment]
I agree we want this; I haven't thought much about the naming yet.  This will enable us to write a generic sorting function and start on algorithms and the like.  Did you have a specific use case in mind in applying this in the library or is this just a "known nice to have/something that is needed" from your perspective?

**Comment by jayzhan211** [comment]
I think it is what we need for List sorting. 

https://github.com/modularml/mojo/issues/2390

**Comment by JoeLoser** [comment]
We have a `Comparable` trait now that serves this purpose.  We may rename it to `PartialOrd` or something, but it's functionally fine for now.
