### ISSUE TITLE
[BUG] Compiler error when `print`ing `self` in destructors

### ISSUE THREAD

**Issue by Brian-M-J** [modularml/mojo#2464]
### Bug description

When running the code snippets linked below, I got compile errors along with stack traces. They all looked similar to this:

```
mojo: /__w/modular/modular/third-party/llvm-project/llvm/include/llvm/Support/Casting.h:566: decltype(auto) llvm::cast(const From &) [To = M::KGEN::LIT::RefType, From = mlir::Type]: Assertion `isa<To>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.	Program arguments: mojo build -o /build/prog /source/prog.mojo
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  mojo      0x00005602d10bc217
1  mojo      0x00005602d10b9dee
2  mojo      0x00005602d10bc8af
3  libc.so.6 0x00007faf42260520
4  libc.so.6 0x00007faf422b49fc pthread_kill + 300
5  libc.so.6 0x00007faf42260476 raise + 22
6  libc.so.6 0x00007faf422467f3 abort + 211
7  libc.so.6 0x00007faf4224671b
8  libc.so.6 0x00007faf42257e96
9  mojo      0x00005602d271e04e
10 mojo      0x00005602d271d874
11 mojo      0x00005602d271c226
12 mojo      0x00005602d271bf1c
13 mojo      0x00005602d271a818
14 mojo      0x00005602d2719ffc
15 mojo      0x00005602d2711073
16 mojo      0x00005602d3bbca76
17 mojo      0x00005602d3bbd101
18 mojo      0x00005602d3bbf6e2
19 mojo      0x00005602d27761a6
20 mojo      0x00005602d1606575
21 mojo      0x00005602d2775800
22 mojo      0x00005602d2775300
23 mojo      0x00005602d2e95789
24 mojo      0x00005602d34d69ff
25 mojo      0x00005602d34d6c79
26 mojo      0x00005602d2ead9a4
27 mojo      0x00005602d2e93e25
28 mojo      0x00005602d15fe508
29 mojo      0x00005602d0fd19f4
30 mojo      0x00005602d0fcfd9e
31 libc.so.6 0x00007faf42247d90
32 libc.so.6 0x00007faf42247e40 __libc_start_main + 128
33 mojo      0x00005602d0fcf6ee
```

### Steps to reproduce

Snippets that reproduce the errors:

1. The original: [https://gist.github.com/modularbot/d827349fa3124c4b7e1d8754884db580](https://gist.github.com/modularbot/d827349fa3124c4b7e1d8754884db580)
2. This also happens with `String`s: [https://gist.github.com/modularbot/2b9b76bfaa87baf04ea02cc929856e77](https://gist.github.com/modularbot/2b9b76bfaa87baf04ea02cc929856e77)
3. I thought the implicit conversions from `StringLiteral` to `String` were causing the crashes, but that's not it: [https://gist.github.com/modularbot/a0431d09677f205daae6e5c1ca177bfe](https://gist.github.com/modularbot/a0431d09677f205daae6e5c1ca177bfe)

More interesting are the snippets that don't crash:

1. No crash when dealing with `Int`s: [https://gist.github.com/modularbot/20f92958dabfdbd701fc44599bbc09d9](https://gist.github.com/modularbot/20f92958dabfdbd701fc44599bbc09d9)
2. Explicitly calling `str` in `print` doesn't crash, for both `String`s and `List`s: [https://gist.github.com/modularbot/4853fcbd73659f121479f37c884d58d6](https://gist.github.com/modularbot/4853fcbd73659f121479f37c884d58d6)
3. `print`ing `self` doesn't crash in member functions: [https://gist.github.com/modularbot/9b6fbc786c472afd419d221fbe1d2afe](https://gist.github.com/modularbot/9b6fbc786c472afd419d221fbe1d2afe)

### System information

```shell
The Mojo playground as of 2nd May, 2024
```

**Comment by ematejska** [comment]
Reproduces in the playground but not with compiled Mojo 24.3.0

**Comment by ematejska** [comment]
The playground has been updated with the latest version of Mojo and this now works.  Thank you for filing.
