### ISSUE TITLE
[BUG] Server does not start after uploading lots of CSV files

### ISSUE THREAD

**Issue by syone9** [modularml/mojo#247]
## Bug Description

I just started to use Mojo playground last week, and yesterday it stopped working.
When I logged in playground, server tries to start, but it does not redirect to JupyterHub even it takes 1 hour.
(It stops loading after the progress bar color turns into red)

Is this error? Anyone have been in the same situation?

The server has been working perfectly before I tested my python code and I uploaded 1,000 - 2,000 csv files.

**Comment by syone9** [comment]
It looks like this

![Screenshot 2023-05-24 at 12 52 33](https://github.com/modularml/mojo/assets/36655202/8f802396-b841-470b-b337-93dd3e66b08d)

**Comment by Mogball** [comment]
@liamstewart can you have a look and triage this issue?

@syone9 is it possible for you to share more details?

**Comment by Mogball** [comment]
Thanks @liamstewart. What can be done to alleviate the issue? Can the instance be reset and a limit be placed so that people don't bork their instances?

**Comment by liamstewart** [comment]
We can remove the volume to reset storage if need be, but I'd like to see what's going on first- just speculating on a limit being hit.

**Comment by syone9** [comment]
I checked the details and found that the total uploaded file size was around 250MB consists of approx. 2000 csv files.
Using those files, the code wrote 2,800 csv files whose size may be around 300MB.
The total size should be <1GB but the number of file is quite many.

My issue occured because Yahoo! Finance API cannot be used for analysis, so can you remove the storage so that I can try again? If only python library `yfinance` is enabled on Mojo playground, no csv outputs are necessary.

**Comment by liamstewart** [comment]
@syone9 thanks! Can you send your playground login over to playground@modular.com so we can take a deeper look and get things going again? We have a survey running for packages to use with Mojo here https://docs.google.com/forms/d/e/1FAIpQLSflZgf5N5M8Rp0xa8PUCVKm1eQXPY2fupoGUTNU7hDsrlsAlQ/viewform

**Comment by Mogball** [comment]
@liamstewart Did this get resolved?

**Comment by liamstewart** [comment]
No. I have seen rare issues with servers failing to start with attachment issues but those are transient and things generally work on a second attempt to spin up a server. For this one in particular I can't debug more without additional info from @syone9.

**Comment by Mogball** [comment]
Thanks. Will close for now then
