### ISSUE TITLE
[Feature Request] add # type: ignore to ignore compiler warnings in that line

### ISSUE THREAD

**Issue by martinvuyk** [modularml/mojo#2474]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

add `# type: ignore` to ignore compiler warnings in that line

### What is your motivation for this change?

Being able to leave project structure and compatibility with python's mypy
```
if some_condition():
    pass
elif False:  # type: ignore
    # TODO: something
    pass
```

**Comment by walter-erquinigo** [comment]
Hi, thank you for reporting this. We'll see what we can do here, but this will happen much later in our roadmap.

**Comment by walter-erquinigo** [comment]
After a second examination, we won't be doing this. Unlike python were many warnings are spurious, mojo warnings don't have that nature, so for the time being we prefer to always display to the user all warnings.
