### ISSUE TITLE
[BUG] math.logb is just log base 2 and it rounds to whole numbers

### ISSUE THREAD

**Issue by MadAlex1997** [modularml/mojo#2477]
### Bug description

math.logb does not actually implement log base b. It does not have an arg for the base and it calculates log base 2 rounded to whole numbers.

### Steps to reproduce

* Read the docs for logb note it only has one argument
* import math.logb
* print(logb[DType.float32,1](2))
* returns 1.0
* print(logb[DType.float32,1](4))
* returns 2.0
* print(logb[DType.float32,1](10))
* returns 3.0

### System information

```shell
- Mojo Version 24.3
```

**Comment by leandrolcampos** [comment]
I think `math.logb` behaves like `logb` in C. For example, in the following code

```mojo
var x = Float32(-125)
var y = math.logb(x)
```

the value of `y` equals the floor of the logarithm of `math.abs(x)`, using the radix of `DType.float32` as base for the logarithm. If I'm right, as radix of `DType.float32` is 2, in this case `math.logb(x)` gives the same result as `math.floor(math.log2(math.abs(x)))`.

**Comment by MadAlex1997** [comment]
> I think `math.logb` behaves like `logb` in C. For example, in the following code
> 
> ```mojo
> var x = Float32(-125)
> var y = math.logb(x)
> ```
> 
> the value of `y` equals the floor of the logarithm of `math.abs(x)`, using the radix of `DType.float32` as the base for the logarithm. If I'm right, since the radix of `DType.float32` is 2, in this case, `math.logb(x)` would yield the same result as `math.floor(math.log2(math.abs(x)))`.

Interesting if true. Not what I would have expected.

I am working on making versions of the standard math functions for tensors, and many more math functions for tensors. As a mathematician and someone who has only dabbled in C++, it would never have occurred to me that there would be another function called logb. Perhaps the name should be changed or the documentation should say what it actually does.
