### ISSUE TITLE
[Feature] Enable `__setitem__` to take variadic arguments

### ISSUE THREAD

**Issue by diyessi** [modularml/mojo#248]
## Request

Either:
 - Allow a fixed number of arguments after a variadic argument
 - Change the arguments of `__setitem__` to have the value immediately follow `self`

### Motivation

Implementing a tensor struct with a rank not known at compile-time needs a variadic index and a value to assign. With the value as the last argument, there is not an easy way to have a variadic index.

### Description and Requirements

It is probably simplest to move the argument, i.e. `(inout self, value : F32, index* : Int)` but that would not be Pythonic, whereas `(inout self, index* : Int, value : F32)` compatibly extends existing behavior.

If `RANK` were a parameter another option would be something like `(inout self, index*RANK : Int, value:F32)`.

**Comment by Mogball** [comment]
@laszlokindrat FYI something to think about.

**Comment by lattner** [comment]
Update, you can now use keyword arguments in setitem index list, but that doesn't help with this bug.  For this, we'd have to support the lookup logic realize it needs to pass the "item value" as a keyword argument.  That would allow a type author to specify the item value with a required keyword, which would allow it to be after a variadic list.

**Comment by lattner** [comment]
This is fixed in the next update, sorry for the delay!
