### ISSUE TITLE
[Feature Request] Make the `msg` argument of `assert_true/false/...` keyword only

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#2487]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

As title.

### What is your motivation for this change?

To prevent #2475 from happening again.

### Any other details?

I think it's a good first issue.

**Comment by softmaxer** [comment]
I'm currently on this and as I'm looking through it, most of the assert functions already had `msg: String = ""` in place. Except for maybe 2 functions. So I added that. Is that the issue or am I completely missing something here?

**Comment by soraros** [comment]
We removed the problematic constructor, so this is no longer needed.
