### ISSUE TITLE
[BUG] Support for negative index in the List._reverse() method

### ISSUE THREAD

**Issue by msaelices** [modularml/mojo#2496]
### Bug description

Reviewing the `collections.List` struct, I've found that the `_reverse(start)` private method is not supporting negative indexes

### Steps to reproduce

This piece of code will not work as expected:

```mojo
    vec = List[Int]()
    vec.append(1)
    vec.append(2)
    vec.append(3)
 
    vec._reverse(start=-2)
```

### System information

```shell
- What OS did you do install Mojo on ?

Ubuntu 22.04.4 LTS
```

* Provide version information for Mojo by pasting the output of `mojo -v`

```
mojo 2024.5.303 (0b4c4e9b)
```

* Provide Modular CLI version by pasting the output of `modular -v`

```
modular 0.7.4 (df7a9e8b)
```

```
```

**Comment by vidur2** [comment]
Can I take a stab at this?

**Comment by JoeLoser** [comment]
> Can I take a stab at this?

Of course, go for it! Happy to review a PR.

**Comment by soraros** [comment]
@vidur2 I think @msaelices already opened #2497 for this.

**Comment by vidur2** [comment]
Oh ok thank you
