### ISSUE TITLE
[Docs] Incomplete code example for StringLiterals

### ISSUE THREAD

**Issue by hroemer** [modularml/mojo#2521]
### Where is the problem?

https://docs.modular.com/mojo/manual/types#string-literals

### What can we do better?

The last code example in [String literals](https://docs.modular.com/mojo/manual/types#string-literals) seems incomplete:

```mojo
var a = 5
var b: String = "String literals may not concatenate "
```

Shouldn't it contain something like this:

```mojo
var a = 5
var b: String = "String literals may not concatenate " + str(a)
print(b)
```

**Comment by ematejska** [comment]
@arthur FYI
