### ISSUE TITLE
[BUG] check-license failing sometimes

### ISSUE THREAD

**Issue by artemiogr97** [modularml/mojo#2528]
### Bug description

The pre-commit hook for license checking is failing sometimes.
I had not been able to understand when it happens, from the log it seems like my stdlib.mojopkg is not found but running an script in the same terminal by doing `mojo path/to/my/script` works (and the stdlib in my build directory is used).

### Steps to reproduce

just do `git commit`, I get the following log:

```
[INFO] Stashing unstaged files to /home/temo/.cache/pre-commit/patch1714911965-57965.
mojo-format..............................................................Passed
check-docstrings.........................................................Passed
check-license............................................................Failed
- hook id: check-license
- exit code: 1

/home/temo/repos/mojo/build/stdlib.mojopkg:0:0: error: attempting to skip 4 bytes when only 0 remain
/home/temo/repos/mojo/stdlib/scripts/check-licenses.mojo:14:1: error: unable to load package '/home/temo/repos/mojo/build/stdlib.mojopkg'
import sys
^
/home/temo/repos/mojo/stdlib/scripts/check-licenses.mojo:14:8: error: unable to locate module 'sys'
import sys
       ^
/home/temo/repos/mojo/stdlib/scripts/check-licenses.mojo:15:6: error: unable to locate module 'pathlib'
from pathlib import Path
     ^
/home/temo/repos/mojo/stdlib/scripts/check-licenses.mojo:19:17: error: use of unknown declaration 'String'
alias LICENSE = String(
                ^~~~~~
/home/temo/repos/mojo/stdlib/scripts/check-licenses.mojo:27:11: error: could not find an 'object' type
def main():
          ^
/home/temo/repos/mojo/stdlib/scripts/check-licenses.mojo:27:11: error: could not find an 'Error' type
def main():
          ^
/home/temo/repos/mojo/stdlib/scripts/check-licenses.mojo:27:5: error: could not find an 'object' type
def main():
    ^
/home/temo/repos/mojo/stdlib/scripts/check-licenses.mojo:27:5: error: unable to locate module 'builtin'
def main():
    ^
/home/temo/repos/mojo/stdlib/scripts/check-licenses.mojo:28:1: error: 
    target_paths = sys.argv()
^
/home/temo/.modular/pkg/packages.modular.com_nightly_mojo/bin/mojo: error: failed to parse the provided Mojo source module
```

### System information

```shell
- What OS did you do install Mojo on ?
WSL ubuntu 22.04.4 in windows 11
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 2024.5.323 (1d9276ea)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.7.2 (d0adc668)
```

**Comment by artemiogr97** [comment]
@gabrieldemarmiesse any ideas? maybe using a python hook would be a workaround for now?

**Comment by gabrieldemarmiesse** [comment]
Mhhh indeed that's hard to know what was going on. My guess is that at that time, either the stdlib.mojopkg wasn't build yet, or the environment variable setting the path to the stdlib.mojopkg wasn't set correctly. I must admit it's hard to find out what exactly happened without being able to reproduce

**Comment by artemiogr97** [comment]
yep that was my guess too, but I ran both commands in the same terminal one after the other (I tried `git commit` and then `mojo path/to/my/script` and also `mojo path/to/my/script` and then `git commit`, in both cases git commit failed but the other command succeeded), it's really weird

**Comment by artemiogr97** [comment]
I found the issue, I did what is mentioned in [development.md](https://github.com/modularml/mojo/blob/main/stdlib/docs/development.md): https://github.com/modularml/mojo/blob/00528f4c44f799966b3da0a866a00e24370c4b59/stdlib/docs/development.md?plain=1#L249-L262
Every time I commit `entr` tries to compile so the pre-commit is ran while compiling stdlib, so maybe it is worth adding a comment in the doc @gabrieldemarmiesse ?

**Comment by gabrieldemarmiesse** [comment]
Nice one! Indeed, that makes sense that it didn't work. Yes feel free to open a PR with a comment in the guide

**Comment by ematejska** [comment]
Thanks for this issue!
