### ISSUE TITLE
[Feature Request] Support for errno in external_call to Improve Error Handling

### ISSUE THREAD

**Issue by dayeondev** [modularml/mojo#2532]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Please add the ability to access errno after using external_call in Mojo. This enhancement will allow for more detailed error handling and reporting after system function calls.

### What is your motivation for this change?

Currently, while Mojo's external_call facilitates the invocation of system library functions, it lacks the capability to access error codes (errno) after a call fails. This limitation significantly restricts error management. For instance, operations such as file deletion or library closure provide only the status of failure without any information on the cause of the error. This lack of detailed error information is a major hindrance for developers in diagnosing issues and providing useful feedback to users.

**Examples:**
* In stdlib/src/builtin/io.mojo:
``` mojo
_ = external_call["fclose", Int32](self.handle)
_ = external_call["fflush", Int32](fd)
_ = external_call["vprintf", Int32](x.data, arg_ptr.bitcast[UnsafePointer[NoneType]]())
```
* In stdlib/src/os/os.mojo:
``` mojo
_ = external_call["closedir", Int32](self._handle)
var error = external_call["unlink", Int](path._as_ptr())
```
* In stdlib/src/sys/ffi.mojo:
``` mojo
_ = external_call["dlclose", Int](self.handle)
```
* In stdlib/src/time/time.mojo:
``` mojo
_ = external_call["clock_gettime", Int32](Int32(clockid), UnsafePointer.address_of(ts))
_ = external_call["nanosleep", Int32](req, rem)
```

### Any other details?

**The implementation should include the following minimum functional attributes:**

* Direct access to errno or through a standardized error handling interface.
* A mechanism to capture and return error states in a consistent manner across platforms.
* The ability to return detailed error messages based on error codes, similar to the strerror function in C, either supported directly by Mojo or implemented internally.

**Other considerations:**
* Enhancing error handling capabilities will contribute to strengthening Mojo's flexibility and reliability as a systems programming language.
* Improving error management will help developers build more robust and stable applications and improve the end-user experience.

**Comment by JoeLoser** [comment]
@Mogball what's the priority of global variable support?

**Comment by Mogball** [comment]
@jopamer
