### ISSUE TITLE
[Feature Request] DX: Change the default branch of modularml/mojo from `main` to `nightly`

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [modularml/mojo#2556]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

I would like a modularml admin to go to the settings of this repo and change the default branch to nightly, see https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch

### What is your motivation for this change?

* Many (mostly new) contributors make the mistake of targeting main instead of nightly. This happens so many times that we even had to make a github action to check it in the CI. 
* Also when reading contributing guides and such from the github UI, it makes sense that future contributors read the latest version (from nightly) than the latest stable version.
* The mojo repo in the github UI is not supposed to be accessed by non-contributors (except the readme maybe), as such, it doesn't matter which version of the code/docs appears first in the github UI

To conclude: There is very little value in keeping `main` as the default branch, we could switch it to nightly.

This should lower the number of quirks to remember/learn when contributing to this repo.

**Comment by ematejska** [comment]
Thanks for filing this.  Would love the community to +1 if this is important to other folks.  The reason that the main branch is is the default right now is to support the users that download the released versions of Mojo and want to run the examples.

**Comment by gabrieldemarmiesse** [comment]
While this is in no way the exact list of all the PRs that have wrongfully targeted main, here is the list of PRs that target main: https://github.com/modularml/mojo/pulls?q=is%3Apr+base%3Amain+is%3Aopen . That can be used as a data point to understand the problem I'm talking about.

If I may add, new contributors aren't necessarily the ones that will +1 this, because it's a mistake that contributors make once and will never make again. So it might not seem important when the contributor has learned that nightly is the right target.

Maybe there is something we can work out about the examples to still keep this workflow while still changing the main branch? If someone from the community has an idea there it would be great :)

**Comment by jayzhan211** [comment]
+1 for this.

I would even prefer if the `main` branch is the current nightly branch for daily development. And, the `stable` branch is the current `main` branch for cutting release.

**Comment by ksandvik** [comment]
Would it help if there was a cross-platform bash script or something similar with the right git instructions that did the right thing to set up a PR pull?

**Comment by gabrieldemarmiesse** [comment]
> Would it help if there was a cross-platform bash script or something similar with the right git instructions that did the right thing to set up fix branch locally?

I don't think the issue is here. The issue is in the github UI as mentionned in the issue description and a bash script won't change the UI.

**Comment by gabrieldemarmiesse** [comment]
One another minor annoyance of not having the nightly branch as the default branch is that the issue template and pull request templates used are the ones of the default branch, meaning any change to those will only be seen at the next release

**Comment by siitron** [comment]
+1

**Comment by Brian-M-J** [comment]
For motivating examples, I'm re-listing the PRs I mentioned on [Discord](https://discord.com/channels/1087530497313357884/1224434323193594059/1240983667111886898):

1. 2697
2. 2665
3. 2490
4. 2478
5. 2343
6. 2309
7. 2301
8. 2272
9. 2221
10. 2178
11. 2039
12. 2029
13. 2028
14. 2662
15. 2656
16. 2732
17. 2881

(I'm not providing links because GitHub)

**Comment by Brian-M-J** [comment]
For more motivating examples, here are all the PRs (and one issue) till now (which I could find) that suggested documentation fixes which were already applied in the `nightly` branch:

1. 2890
2. 2881
3. 2750
4. 2732
5. 2512
6. 2516
7. 2508

Since the docs site syncs with `main` and not `nightly`, users see a lot of outdated information and errors. They then look at the repo and see that the repo's default branch (`main`) also has these errors, not realizing that they need to check `nightly` instead.
