### ISSUE TITLE
[Feature Request] Support `__add__` and `__mul__` operators for `List`

### ISSUE THREAD

**Issue by bgreni** [modularml/mojo#2589]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

We should support the `__add__` and `__mul__` operators for the standard `List` container. Where `__add__` is used to concatenate two lists, and `__mul__` is used to concat a list with itself 1 or more times.

### What is your motivation for this change?

This behaviour is present in Python, and therefore, should also be present in Mojo.

**Comment by soraros** [comment]
What's the desired semantics for move only types?

**Comment by bgreni** [comment]
> What's the desired semantics for move only types?

@soraros Since the `CollectionElement` trait is a composition of `Movable` and `Copyable that's not an issue correct?

**Comment by soraros** [comment]
@bgreni Indeed, silly me.
