### ISSUE TITLE
[BUG] Passing functions which have arguments to other functions fails without type hints

### ISSUE THREAD

**Issue by jackmott** [modularml/mojo#2601]
### Bug description

Within `def` functions I expect to be able to pass function pointers around without type hints just as I would in python. If the functions have no arguments, this works fine. But passing a function that has arguments to another function currently fails, unless you add type hints.

### Steps to reproduce

Here is a minimal reproducing example, the call to `bar` within `main` errors with: `invalid call to 'bar': argument #0 cannot be converted from 'fn(owned s: object) raises -> object' to 'object'mojo`

```py
def foo(s):
    print(s)
     
def bar(foo):
    foo("foo")
    print("bar")
 
def main():
    bar(foo)
```

### System information

```shell
- Windows with Ubuntu linux subsystem
- Mojo 24.3.0
- Modular 0.7.4
```

**Comment by ematejska** [comment]
This now works with the latest nightly and should be fixed in the next release.  Please give it a try.
