### ISSUE TITLE
[Feature Request] Add more `List` methods to the `InlineList` struct

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [modularml/mojo#2610]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

The `InlineList` struct has been added to the stdlib recently: https://github.com/modularml/mojo/pull/2587 .
We would like to have more methods available in `InlineList`, and those methods should mirror the ones available in `List`.

We would like to avoid code duplication as much as possible, so, when adding new methods, please try to group the code together when it's relevant to do so. 

### What is your motivation for this change?

We'll use `InlineList` for SSO, so we'll likely need more methods, like `resize`, `__getitem__(slice)`, `pop`, etc... There is no need to have multiple APIs for different sorts of list, so let's copy the API of the list. It will allow `InlineList` to be a somewhat drop-in replacement for `List` when the capacity is known at compile time (and small enough).

### Any other details?

This is the kind of task where it makes sense to do one pull request per method added, and is very beginner friendly. If you're looking for an issue to do your first PR in Mojo, this one is pretty easy :)

**Comment by JoeLoser** [comment]
Makes sense. +1 for this!

**Comment by JoeLoser** [comment]
As discussed in today's team meeting, going to close this.  If specific methods need to be to `InlineList` that is driven by some feature (such as the original SSO work), please create a PR and the feature work it builds towards.
