### ISSUE TITLE
Numpy import error (in CLI, Jupyter and REPL)

### ISSUE THREAD

**Issue by CalmScout** [modularml/mojo#2636]
### Bug description

Dear members of Mojo community,

When I run the following code:

```mojo
from python import Python
 
def main():
    var np = Python.import_module("numpy")
    var array = np.array([1, 2, 3])
    print(array)
```

The following error appears:

```bash
Unhandled exception caught during execution: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there
```

The behaviour persist if I run the script via Terminal or in Jupyter Notebook or enter the code in Mojo REPL.
The only version of Mojo on the system is one with MAX Engine. The only python environment that has mojo has installed numpy:

```bash
❯ mamba list | grep numpy
numpy 1.26.4 pypi_0 pypi
```

This is a conde env inside pyenv env. Hello world examples, that requires only Mojo (no Python imports) work correctly.

I appreciate any help on the issue.

Best regards,
Anton.

### Steps to reproduce

Code snippet is provided in the description above.

### System information

```bash
❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble
```

```bash
❯ mojo -v
mojo 24.3.0 (9882e19d)
```

```bash
❯ modular -v
modular 0.8.0 (39a426b5)
```

**Comment by jackos** [comment]
Hi @CalmScout try this after activating your conda environment to link Mojo to it:

```bash
export MOJO_PYTHON_LIBRARY="$(find $CONDA_PREFIX/lib -iname 'libpython*.[s,d]*' | sort -r | head -n 1)"
echo "export MOJO_PYTHON_LIBRARY=$MOJO_PYTHON_LIBRARY" >> ~/.zshrc
echo "export MOJO_PYTHON_LIBRARY=$MOJO_PYTHON_LIBRARY" >> ~/.bashrc
```

Then restart your shell and try running mojo again

**Comment by CalmScout** [comment]
Hi @jackos ,

Thank you for such a prompt reply. I followed your instructions and this solved the issue! Thank you for providing instructions for both `bash` and `zsh`.

Best regards,
Anton.
