### ISSUE TITLE
[BUG]: Memory leak on Mojo docs website

### ISSUE THREAD

**Issue by elisbyberi** [modularml/mojo#265]
### Bug description

```shell
A memory leak occurs when visiting the Mojo Docs website.
It's not aggressive; it occurs slowly but steadily.
Tested in both Chrome and Firefox.
```

### Steps to reproduce

```shell
Visit: https://docs.modular.com/mojo/MojoStdlib/StaticTuple.html?q=&
```

### System information

```shell
Ubuntu 22.04, Intel
Chrome 113.0.5672.126 (Official Build) (64-bit)
Firefox 113.0.2 (64-bit)
```

**Comment by scottamain** [comment]
Thank you for reporting this! This was a bug in Quarto that's [now fixed](https://github.com/quarto-dev/quarto-cli/commit/5d340ef1a5077485124307df910d3cebf2474fc1). I'll keep this bug open so we remember to update our Quarto to v1.4 when it's a stable release.

**Comment by scottamain** [comment]
Still waiting for Quarto to release version 1.4 as the stable build: https://quarto.org/docs/download/

**Comment by Mogball** [comment]
Is our Quarto version pinned or is it bumped automatically?

**Comment by scottamain** [comment]
Our version is pinned.
- Scott

**Comment by scottamain** [comment]
Fixed when we switch our website to Docusaurus
