### ISSUE TITLE
[stdlib] Improve tests for `abs`, `divmod`, `round` free functions

### ISSUE THREAD

**Issue by laszlokindrat** [modularml/mojo#2679]
These delegate to dunder methods, which should be tested separately for each structs that implement them. However, we do need a few basic tests to ensure that the free functions do work (e.g. so we don't accidentally rename them).

See comment: https://github.com/modularml/mojo/commit/65f0e5b8b8a11e29e7b5c9aab50030f0a2322ee9#diff-2812447c50533870693b58783ccb2c24de6d8d3083372eb17084dbe369eb87a6R43-R45

**Comment by msaelices** [comment]
@laszlokindrat can I work on this?

**Comment by laszlokindrat** [comment]
@msaelices it's yours, thank you!

**Comment by msaelices** [comment]
PR ready for review: https://github.com/modularml/mojo/pull/2724

**Comment by msaelices** [comment]
Should we close this?

**Comment by laszlokindrat** [comment]
Yes, thanks for fixing it!
