### ISSUE TITLE
[stdlib] Improve tests for `utils.numerics`

### ISSUE THREAD

**Issue by laszlokindrat** [modularml/mojo#2680]
Most functionality in this module is either poorly or not at all tested (and it's possible that some tests are misplaced somewhere else, e.g. `test_simd.mojo`). We should improve the coverage on this module and organize the test cases better.

See comment: https://github.com/modularml/mojo/commit/a2b9d3b8148e5d4bb747e326961665e33fa75383#diff-
f25d998fb073a68a1aaa3cabd5203651034b0e2b55d67be3ecfce89ef99139faR20

**Comment by msaelices** [comment]
@laszlokindrat can I work on it?

**Comment by msaelices** [comment]
PR ready for review: https://github.com/modularml/mojo/pull/2727

**Comment by msaelices** [comment]
I think we can close it, right?

**Comment by laszlokindrat** [comment]
> I think we can close it, right?

Yes, thank you for fixing it!
