### ISSUE TITLE
[stdlib] Implement missing functions in the `bit` module

### ISSUE THREAD

**Issue by laszlokindrat** [modularml/mojo#2682]
For example: `bit_ceil`, `bit_floor`, `has_single_bit`, and others. The immediate goal is to achieve (or get pretty close to) parity with [Cpp's `<bit>`](https://en.cppreference.com/w/cpp/header/bit). We shouldn't blindly follow the naming, and we can deviate from or extend some of these APIs slightly if we have a good reason to. Many of these functions might be simple wrappers around intrinsics.

See comment: https://github.com/modularml/mojo/commit/3f9fa057a9587f26e217344e663cc77513c0002a#diff-20568bce7de07632ece5bf3e933c7e2eec19706a949dcae48ddd4299309ddd10R249

**Comment by LJ-9801** [comment]
Can I take a look into this? May use this issue to track all the PRs.

**Comment by laszlokindrat** [comment]
> Can I take a look into this? May use this issue to track all the PRs.

It's yours now, thank you for working on this! 🎉 Feel free to ping me once you have PRs.

**Comment by LJ-9801** [comment]
@laszlokindrat some of the originally implemented bit functions such as `countl_zero`, `bit_reverse`, `countl_zero` and etc do not seem to be tested. Are test cases necessary for them? I can open an other PR to add all the test cases for these function if needed.

**Comment by laszlokindrat** [comment]
> @laszlokindrat some of the originally implemented bit functions such as `countl_zero`, `bit_reverse`, `countl_zero` and etc do not seem to be tested. Are test cases necessary for them?

Yes, they are necessary, but indeed missing.

> I can open an other PR to add all the test cases for these function if needed.

That would be highly appreciated, thank you!


I can open an other PR to add all the test cases for these function if needed.

Tha
