### ISSUE TITLE
[stdlib] [Feature Request] Refactor `String` to not have so many raises and use Optional

### ISSUE THREAD

**Issue by martinvuyk** [modularml/mojo#2686]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

As title.

### What is your motivation for this change?

Could have a `fn () raising -> Int` and an `fn () -> Optional[Int]`
```mojo
fn atol(str: String, base: Int = 10) raises -> Int:
    return _atol(str._strref_dangerous(), base)

fn atol_safe(str: String, base: Int = 10) -> Optional[Int]:
    try:
      return _atol(str._strref_dangerous(), base)(str, base)
    except:
      return None
```

This could just return a list with one item, it being the whole String. `if not delimiter: return List[String](self)`
```mojo
    fn split(self, delimiter: String) raises -> List[String]:
        """Split the string by a delimiter.

        Args:
          delimiter: The string to split on.

        Returns:
          A List of Strings containing the input split by the delimiter.

        Raises:
          Error if an empty delimiter is specified.
        """
        if not delimiter:
            raise Error("empty delimiter not allowed to be passed to split.")
```

This will most certainly always be checked against anyway with `if index == -1: ...` so it could also be made an Optional[Int]
```mojo
fn find(self, substr: String, start: Int = 0) -> Int:
        """Finds the offset of the first occurrence of `substr` starting at
        `start`. If not found, returns -1.

        Args:
          substr: The substring to find.
          start: The offset from which to find.

        Returns:
          The offset of `substr` relative to the beginning of the string.
        """

        return self._strref_dangerous().find(
            substr._strref_dangerous(), start=start
        )
```

**Comment by siitron** [comment]
For Python interop `split` should default to split on any whitespace, and `find` should return -1 if the substring isn't found.

**Comment by martinvuyk** [comment]
> For Python interop `split` should default to split on any whitespace, and `find` should return -1 if the substring isn't found.

understood. how does this look ?
```mojo
    fn split(self, owned delimiter: String = " ") -> List[String]:
        """Split the string by a delimiter.

        Args:
          delimiter: The string to split on.

        Returns:
          A List of Strings containing the input split by the delimiter.

        """
        if not delimiter:
            delimiter = " "
        ...
```

**Comment by siitron** [comment]
Whitespace could be more than just spaces. I think all of these count as whitespace:
* Spaces: `' '`
* Tabs: `'\t'`
* Newlines: `'\n'`
* Carriage returns: `'\r'`
* Vertical tabs: `'\v'`
* Form feeds: `'\f'`


Also, note that, for example, `"a\n\na".split()` isn't the same as `"a\n\na".split("\n")` in Python. The default split will treat continuous whitespace as one separator.

**Comment by martinvuyk** [comment]
> Whitespace could be more than just spaces. I think all of these count as whitespace:

wow I had no idea. The current implementation doesn't take that into account, will try to imitate python. But this will absolutely kill performance lol.

**Comment by bgreni** [comment]
@martinvuyk Sorry I didn't notice you already had a PR making changes to the `String.split`. 

I've tried to address these differences and added a missing `maxsplit` arg in #2713

**Comment by martinvuyk** [comment]
> @martinvuyk Sorry I didn't notice you already had a PR making changes to the `String.split`.
> 
> I've tried to address these differences and added a missing `maxsplit` arg in #2713

please close that PR I'm currently working on that

also there are some characters missing still in String.WHITESPACE to have Python's behaviour which I'm also adressing. And I'm also trying to document this thoroughly and add more tests. 

Also what do you think of putting the maxsplit in params? at least that way the compiled code wont have so many branches. Iit'll be less pythonic but I think python devs will manage (?). 
```mojo
    fn split[
        maxsplit: Int = -1
    ](self, owned delimiter: String = "") -> List[String]:
    ...
```
