### ISSUE TITLE
[BUG] struct with multiple SIMD fields rounds `sizeof` up to nearest power of 2

### ISSUE THREAD

**Issue by mikowals** [modularml/mojo#2693]
### Bug description

I expected a struct's `sizeof` to be the total of the `sizeof` each of its fields individually. This usually is true but does not seem to be the case for SIMD fields when the sizes don't total to a power of 2. I am not sure if this is really a bug or just something that needs better documentation. But it was unexpected and can be a lot of extra memory use.

### Steps to reproduce

[Gist from playground](https://gist.github.com/modularbot/1dbd9f434e114d43a0a80cc5a3ca3e87) or code below:

```mojo
from sys import sizeof
struct Foo:
  var a: SIMD[DType.uint8, 8]
  var b: SIMD[DType.uint8, 4]
 
def main():
    print("sizeof[Foo](): ", sizeof[Foo]())
    print("sizeof[SIMD[DType.uint8, 8]]():", sizeof[SIMD[DType.uint8, 8]]())
    print("sizeof[SIMD[DType.uint8, 4]]():", sizeof[SIMD[DType.uint8, 4]]())
```

output:

```console
sizeof[Foo]():  16
sizeof[SIMD[DType.uint8, 8]](): 8
sizeof[SIMD[DType.uint8, 4]](): 4
```

### System information

```shell
In playground on 17-May-2024 and locally on:
- macOS Sonoma 14.4.1 (23E224)
- mojo 2024.5.1607 (bd1f55d0)
- modular 0.7.2 (d0adc668)
```

**Comment by bgreni** [comment]
This doesn't seem to be exclusive to `SIMD` so there could be a reason for this behaviour?

```mojo
struct Bar:
    var d: Int
    var e: Bool
    

fn main():
    print(sizeof[Int]()) # 8
    print(sizeof[Bool]()) # 1
    print(sizeof[Bar]()) # 16
``

**Comment by mikowals** [comment]
@JoeLoser , this appears to have been closed in error.  Using the latest nightly (mojo 2024.6.2614 (366c690a)),  `sizeof[Foo]()` in the example  still equals 16 rather than the expected 12.

**Comment by JoeLoser** [comment]
> @JoeLoser , this appears to have been closed in error. Using the latest nightly (mojo 2024.6.2614 (366c690a)), `sizeof[Foo]()` in the example still equals 16 rather than the expected 12.

@Mogball can you comment on why this was closed?

**Comment by Mogball** [comment]
This is expected behaviour
