### ISSUE TITLE
[BUG] While loop logic causes seg fault.

### ISSUE THREAD

**Issue by johnsoez4** [modularml/mojo#2696]
### Bug description

**This issue started a few days ago with Mojo nightly version 2024.5.1002.**
**Edit 2024-05-28:**

* mojo 2024.5.822 (2cfed0ad) = OK
* mojo 2024.5.1002 (83c7e1be) = KO (issues started)

In the code shown below, function `app_run` causes a seg fault, but `app_close` alone compiles and works properly. The logic to exit each while loop is essentially identical but inverted. I presume that both functions should compile and work properly.
**Important:** I just confirmed that this issue does NOT exist with Mojo stable version 24.3.0 (9882e19d).
[stack_dump.txt](https://github.com/modularml/mojo/files/15343523/stack_dump.txt)

### Steps to reproduce

```
fn main() raises:
    app_close()
    app_run()


fn app_close():
    # This compiles and works.
    var app_close = False
    var loops = 10
    while not app_close:
        loops -= 1
        if loops == 0:
            app_close = True
    print("app_close: Success!")


fn app_run():
    # This does not compile (seg fault).
    var app_run = True
    var loops = 10
    while app_run:
        loops -= 1
        if loops == 0:
            app_run = False
    print("app_run: Success!")
    ```
 
### System information
 
```shell
Ubuntu: 24.04 LTS
Python: 3.12.3
Mojo Nightly: 2024.5.1619 (bd52708e)
Modular: 0.7.4 (df7a9e8b)
```

**Comment by johnsoez4** [comment]
**Problem remains:**
mojo 2024.5.1805 (341542be)
mojo 2024.5.1905 (46b7e7ee)

**Comment by JoeLoser** [comment]
@ematejska @jopamer also asked on discord at https://discord.com/channels/1087530497313357884/1224434323193594059/1242260289060077589

**Comment by ematejska** [comment]
Thanks for filing!  We'll take a look.

**Comment by ematejska** [comment]
Duplicate filed here: https://github.com/modularml/mojo/issues/2821

Reduced use-case from there:
```
fn main():
    var loop = True
    while loop:
        loop=False
```
