### ISSUE TITLE
[CI] Run `markdownlint.sh` on all markdown files in the repo

### ISSUE THREAD

**Issue by JoeLoser** [modularml/mojo#2716]
In https://github.com/modularml/mojo/commit/f5e7231c3427cc58d62dd3a60d83dc9e225af12b, I added the scripts for `markdownlint.sh` and the config we use internally for linting our markdown docs.  It would be nice to set up some `pre-commit` rules and/or run `markdownlint.sh` on all the markdown files in the repo.  This has the benefit of saving stdlib maintainers time when importing changes that make markdown edits (which is quite often now that folks write their own changelog entries) and/or make doc changes like in https://github.com/modularml/mojo/pull/2663 for example.

CC: @gabrieldemarmiesse

**Comment by gabrieldemarmiesse** [comment]
@JoeLoser #2717 will run it in the CI
