### ISSUE TITLE
[Docs] Blog page with broken link / missing source code

### ISSUE THREAD

**Issue by lbartworks** [modularml/mojo#2734]
### Where is the problem?

https://www.modular.com/blog/mojo-python-calculating-and-plotting-a-valentines-day-using-mojo-and-python

### What can we do better?

the broken link is:
https://github.com/modularml/mojo/blob/main/examples/blogs-videos/valentine.mojo

i think you need to add the file to github and link it properly in the blog entry

**Comment by hogepodge** [comment]
Republished an updated example to https://github.com/modularml/devrel-extras/tree/main/blogs/mojo-calculating-and-plotting-a-valentines-day-heart
