### ISSUE TITLE
[Feature Request] Remove `__bool__` on `SIMD` types with size > 1

### ISSUE THREAD

**Issue by DayDun** [modularml/mojo#275]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Remove the `__bool__` method on `SIMD` types when its `size` is larger than one.

### What is your motivation for this change?

I don't think it is very clear what the expected behavior should be when trying to convert a SIMD type to Bool. Today `__bool__` uses `.reduce_and()`, which only becomes truthy if all elements are truthy. This sort of clashes with my intuition on integers where if a single bit is on, the value becomes truthy.

Removing `__bool__` (or making it cause some kind of assertion) is also consistent with how numpy treats `__bool__` on arrays:
```
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

Also I'm pretty sure `__bool__` has a typo for non-boolean SIMD types currently. The equality should be inverted: `(self == 0).reduce_and()`.

### Any other details?

Original issue: https://github.com/modularml/mojo/issues/252

Don't really know when it's appropriate to change an issue as opposed to creating a new one.

**Comment by DayDun** [comment]
Ok lol this issue template thing sucks.

**Comment by Mogball** [comment]
@abduld What are your thoughts?

**Comment by abduld** [comment]
We want to have `__bool__` method since it allows one to write code such as 

```
if my_simd_type:
     something()
```

Also, the scalar types (Uint8, Float32, ...) are aliases to single-element simd types, so it is useful to write

```
if Float32(3) == Float32(4):
     return "three is not a four"
```

There is no ambiguity if you consistenly follow the same convention, and we will clarify this in the documentation.

**Comment by DayDun** [comment]
The issue does not concern `SIMD` types where the `size == 1`, those can be left as they are. But when using `SIMD` types with a `size` greater than 1, I don't think it is apparent at all what the expected behavior should be, and it can easily cause footguns as seen in https://github.com/modularml/mojo/issues/252.

The following code is not ambiguous:
```py
from DType import DType

if SIMD[DType.bool, 1](True):
    print("hello")
```
but this is:
```py
from DType import DType

if SIMD[DType.bool, 4](True, False, True, False):
    print("hello")
```
---
Numpy has already solved this issue, and I think they have a very reasonable solution:
```py
import numpy as np

if np.array([True]):
    print("hello")
```
works just as expected, and
```py
import numpy as np

if np.array([True, False, True, False]):
    print("hello")
```
causes the exception
```py
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
---
You could implement a fix for this today like this:
```py
from DType import DType
from Assert import assert_param_msg

struct SIMD[type: DType, size: Int]:
    fn __bool__(self) -> Bool:
        assert_param_msg[size == 1, "The truth value of a SIMD type with more than one element is ambiguous. Use a.reduce_and() or a.reduce_or()"]()
        
        @parameter
        if type == DType.bool:
            return self.cast[DType.bool]()[0].value
        # Fixed from `self == 0`
        return (self != 0)[0].value
```
or potentially some better way in the future with traits.
