### ISSUE TITLE
[Feature Request] [mojo-lang] [proposal] Make fstring formatting a priority and define what features will be available

### ISSUE THREAD

**Issue by martinvuyk** [modularml/mojo#2761]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Fstring formatting i.e. `f"my text with an embedded value: {some_var}, it's so simple"` is one of the best features of Python IMO, it helps really simplify dealing with strings. What I don't like, is how complicated the `"".format()` PEP specification is...

What I would propose is that we simplify things and let the programmer decide how to represent their types. Make it so that f strings are syntax sugar for string concatenation.

If someone wants to represent, say, an int's hex value, then they should just do f"some hex_value: {hex(10)}", instead of the `StringLiteral.format()` method needing to have a bunch of edge cases and different handcoded support for each stdlib type...

We can also simplify things even more by saying that  `f"my text with an embedded value: {some_var}, it's so simple"` generates code that looks like `("my text with an embedded value: " + (some_var) + ", it's so simple")` that way chained f strings would be simpler to implement.
```mojo
var a  = f"Just imagining that {f"I can chain {f"my text with an embedded value: {some_var}, it's so simple"} that I can almost taste"} the absolute joy of writing in this language"
```
Would codegen into
```mojo
var a = "Just imagining that" + ("I can chain  " + ("my text with an embedded value: " + (some_var) + ", it's so simple") + "that I can almost taste") + "the absolute joy of writing in this language"
```

### What is your motivation for this change?

Adding support for Python fstrings is important. But I think we shouldn't implement it exactly the same. We could do a `StringLiteral.format()` equal to Python's, but I don't think fstrings should have templating capabilities since that just overcomplicates things and we can leave those cases to `StringLiteral.format()` anyway

**Comment by bgreni** [comment]
The ubiquitous use and utility of `format` is precisely why we cannot intentionally shortcut the implementation for Mojo. It needs to work the same as Python programmers expect it to eventually. However as you mentioned the standard is quite complex and given it doesn't quite align with the short term priorities for Mojo it's unlikely to be prioritized anytime soon I would bet.

I agree having trivial stand in support for now would be nice though!

**Comment by laszlokindrat** [comment]
Thanks for opening this ticket! I agree that f-strings are one of the most useful features in Python. `StringLiteral` is eventually going to become non-materializable with `String` as the materialization target, so I wouldn't worry too much about it in this context.

At the same time, I strongly agree with @bgreni here: eventually we _must_ comply with the f-string semantics dictated by Python. This doesn't mean, however, that we couldn't hill climb this. I would suggest that we start with something simple, like `String.format(*args: Stringable)` without any ability for format specification, then extend to `String.format(*args: Stringable, **kwargs: Stringable)`. This would already enable some useful functionality.

Then I would start looking at implementing the builtin `format` function, along with a related trait along these lines:
```mojo
trait StringFormattable:  # name to be bike shedded
    fn __format__(self, format_spec: StringSlice) -> String: ...
    fn __format__(self) -> String: ...   # overload to work around some current issues with default stringslice values
```

Note that we already have a `Formattable` trait, but it requires a slightly lower level API. We need to think about how these could compose. @ConnorGray you have been doing some work in this area, WDYT?

**Comment by rd4com** [comment]
@laszlokindrat excellent, looks like a nice plan ! 

@bgreni :+1:

**Comment by rd4com** [comment]
Hello @laszlokindrat , i pushed a change in https://github.com/modularml/mojo/pull/2771 for the simple `{0}` + `*args` :+1: 

i feel that if anybody have a better understanding on how it works with python, they could do the implementations.

This is challenging and need to be done the right way !

I observed that if we could assign to a slice, it would be easier: `res[13:16] = args[i]`

**Comment by arthurevans** [comment]
In case people land here looking for it: a limited subset of `String.format()` is now supported. It's documented here: https://docs.modular.com/mojo/stdlib/collections/string/format/ and this API doc page will be updated as new support is added.
