### ISSUE TITLE
[stdlib] Support custom prefix for `hex` function

### ISSUE THREAD

**Issue by JoeLoser** [modularml/mojo#2778]
Ideally the `hex` function would support a custom prefix which defaults to `0x` (as in Python and in Mojo today). Right now, internal users have the following code escaping control characters during URL construction: `"%" + hex(v)[2:]` which can be cleaned up with this functionality.

**Comment by bgreni** [comment]
The current implementation does support this no? https://github.com/modularml/mojo/blob/nightly/stdlib/src/builtin/hex.mojo#L26

**Comment by JoeLoser** [comment]
> The current implementation does support this no? https://github.com/modularml/mojo/blob/nightly/stdlib/src/builtin/hex.mojo#L26

Oops, you're right.  Sorry I missed that when porting this internally issue to the public repo.  We have this functionality now, thanks!
