### ISSUE TITLE
[BUG] Mojo crashes when attempting run `str()` during compilation.

### ISSUE THREAD

**Issue by thatstoasty** [modularml/mojo#2779]
### Bug description

Running `str()` within in an alias causes the compiler to crash. I think we should be able to convert Stringables to String during compilation unless I'm missing something. Thanks!

### Steps to reproduce

* Include relevant code snippet or link to code that did not work as expected.
* If applicable, add screenshots to help explain the problem.
* If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
* Include anything else that might help us debug the issue.

Minimal example to reproduce the error:

```mojo
fn main() -> None:
    alias s = str(1)
```

### System information

```shell
- What OS did you do install Mojo on ? MacOS 14.4.1
- Provide version information for Mojo by pasting the output of `mojo -v` mojo 2024.5.2012 (fb60fe4f)
- Provide Modular CLI version by pasting the output of `modular -v` modular 0.7.1 (28ddab26)
```

**Comment by JoeLoser** [comment]
FYI @laszlokindrat as we were talking about this last week if I recall correctly.

**Comment by laszlokindrat** [comment]
@thatstoasty Thanks for opening the ticket! Can you please provide the error message or trace you are getting?

**Comment by laszlokindrat** [comment]
@Mogball is this a potential issue with variadic packs in the compiler?

**Comment by zyx-billy** [comment]
After fixing the issue with packs, evaluation still fails due to a dependency on an external call to snprintf in stdlib for formatting ints. So unfortunately this is not something that can be supported at compile-time unless the implementation no longer depends on the external call. Thanks for filing the issue though, it helped plug a hole with interpreting packs.

**Comment by thatstoasty** [comment]
No problem, my use case will be covered once https://github.com/modularml/mojo/issues/1573 is resolved!
