### ISSUE TITLE
[Feature Request] Add playsound module

### ISSUE THREAD

**Issue by osag1e** [modularml/mojo#2799]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Add playsound module 

### What is your motivation for this change?

I simply want to use it to add sound alerts for my pomodoro timer, for when the work and break durations end.

### Any other details?

It needs to be able to play both WAV and MP3 audio files.

**Comment by MadAlex1997** [comment]
I feel like this doesn't belong in the standard library.

**Comment by osag1e** [comment]
> I feel like this doesn't belong in the standard library.

You are probably right, but it will be a nice feature to have regardless. Thank you, Alex.

**Comment by helehex** [comment]
*~beep*

**Comment by ematejska** [comment]
Thank you for filing.  Right now this is not in scope in the current roadmap but seems like a nice addition that the community could build.
