### ISSUE TITLE
Add `function` keyword as an alternative way to define functions in mojo

### ISSUE THREAD

**Issue by slf188** [modularml/mojo#28]
## Request
I noticed that the current syntax for declaring functions is `fn` as well as `def`, but I believe it would be helpful to provide an alternative syntax using the keyword function.-->

## Motivation

I would like to request that you consider adding the `function` keyword as an alternative way to define functions, in addition to the existing `fn` and `def` syntax. 

**What is the value to the product/user of doing this?**
This would allow developers to choose the syntax that they are most comfortable with, and would also make the language more accessible to those who are used to other programming languages that use the `function` keyword. Per se I'm a swift programmer.

I understand that this may require some changes to the codebase, but I believe it would ultimately make the language more flexible and easier to use for a wider range of developers.

Thank you for your consideration, and please let me know if there is any way I can help adding this feature or any concerns about this request.

**Comment by lattner** [comment]
Thank you for your interest.  Right now we're focused on building out the core model of the language (the type system, major missing features etc) as defined in the roadmap.  We can come back and apply a new set of paint when the system is up and running - that's when we'll know how all the features "look" when sitting next to each other.  Until then, we're making reasonable starting decisions and avoiding syntactic sugar.

This is a long way to say "let's come back to this later".  One guiding principle is that we dont' want many synonyms, so we should pick one thing or other other, not have fn and function.

**Comment by lattner** [comment]
Also, I'm not sure if you were involved then, but this is what we did with Swift: Swift 1/2 bring in the basic functionality and we repainted everything in Swift 3.  I don't expect things to take that long for Mojo, but can give you an mental framework to work with.

**Comment by slf188** [comment]
Sounds good to me, we'll get back to it later then!

If there's anything I can help with (including the type system, translating documentation) please let me know!

I can sense there is a bright future ahead for Mojo. Kudos! @lattner
