### ISSUE TITLE
[BUG]: 'let' fields in structs are not supported yet

### ISSUE THREAD

**Issue by bsyedumar** [modularml/mojo#280]
### Bug description

```shell
The documentation suggests : "Syntactically, the biggest difference compared to a Python class is that all instance properties in a struct must be explicitly declared with a var or let declaration."

But the structs still need to support the let keyword. Do you have any updates on when that might be implemented and if it is in the works?
```

### Steps to reproduce

```shell
from String import String
@value
struct Employee:
    var name: String
    var age: Int
    var department: String
    var salary: F64
    let country: String


There is an error due to let. I have tried other examples too but it doesn't work.
```

**Comment by lattner** [comment]
Thank you for filing this.  This is known (to me) to not be supported.  We have the infrastructure to do this now, but we need to decide whether we want it.  There are various folks (incl on this forum) that are proposing that we eliminate 'let' declarations to simplify things, and I'd rather resolve that direction before investing more time into let declarations.

Incidentally, this discussion will come up "real soon now" as it is all tangled into the lifetime proposal.  This should be coming to the community for discussion in the next two weeks.

**Comment by yakupc55** [comment]
if you need changeable values in struct
I have an example for you:
[https://github.com/yakupc55/mojo-example/blob/main/changeable%20data%20for%20struct.md](https://github.com/yakupc55/mojo-example/blob/main/changeable%20data%20for%20struct.md)

**Comment by bsyedumar** [comment]
> Thank you for filing this. This is known (to me) to not be supported. We have the infrastructure to do this now, but we need to decide whether we want it. There are various folks (incl on this forum) that are proposing that we eliminate 'let' declarations to simplify things, and I'd rather resolve that direction before investing more time into let declarations.
> 
> Incidentally, this discussion will come up "real soon now" as it is all tangled into the lifetime proposal. This should be coming to the community for discussion in the next two weeks.

That makes sense. Personally, I like the addition of let but I can understand how it can confuse some people. Thanks and good luck! :)
