### ISSUE TITLE
[BUG] `DTypePointer[bool]` packs bits inconsistently

### ISSUE THREAD

**Issue by helehex** [modularml/mojo#2813]
### Bug description

When using `DTypePointer[bool]` `store()`/`load()` with different widths, you get inconsistent results.

### Steps to reproduce

```mojo
var ptr = DTypePointer[DType.bool].alloc(4)
ptr.store(0, True)
ptr.store(1, True)
ptr.store(2, True)
ptr.store(3, True)
print(ptr.load[width=4](0))
```

prints: `[True, False, False, False]`

### System information

```shell
Host Information
  ================

  Target Triple: x86_64-unknown-linux
  CPU: skylake
  CPU Features: adx, aes, avx, avx2, bmi, bmi2, clflushopt, cmov, crc32, cx16, cx8, f16c, fma, fsgsbase, fxsr, invpcid, lzcnt, mmx, movbe, pclmul, popcnt, prfchw, rdrnd, rdseed, sahf, sgx, sse, sse2, sse3, sse4.1, sse4.2, ssse3, x87, xsave, xsavec, xsaveopt, xsaves

mojo 2024.5.2405 (fc1ed0a3)

modular 0.8.0 (39a426b5)
```

**Comment by MadAlex1997** [comment]
Probably Related to [2492](https://github.com/modularml/mojo/issues/2492), I am pretty sure there are issues at the DType pointer level with the i1 representation of `SIMD[DType.bool,1]` and the 8 Bit C style bool used in the pointers.

**Comment by bgreni** [comment]
Seems as though this has been fixed with recent changes?

```mojo
var ptr = DTypePointer[DType.bool].alloc(4)
SIMD[size=4].store(ptr, SIMD[DType.bool, 4](True, False, True, True))
print(SIMD[size=4].load(ptr)) # prints [True, False, True, True]
```

**Comment by rparolin** [comment]
Looks like the patch mentioned above by @bgreni resolved the issue.  I'll close it but we can definitely reopen it if knock-ons are discovered.  Thank you!

**Comment by helehex** [comment]
looks like when `store`/`load` moved to `SIMD`, the fix wasn't

**Comment by helehex** [comment]
```mojo
var ptr = DTypePointer[DType.bool].alloc(4)
SIMD[DType.bool, 1].store(ptr, 0, True)
SIMD[DType.bool, 1].store(ptr, 1, True)
SIMD[DType.bool, 1].store(ptr, 2, True)
SIMD[DType.bool, 1].store(ptr, 3, True)
print(SIMD[DType.bool, 4].load(ptr, 0))
```
still prints `[True, False, False, False]`

**Comment by helehex** [comment]
The inconsistency is that width packs bits, but the offset is in bytes.
This means everything gets weird when using different widths on the same pointer.
```mojo
SIMD[DType.bool, 1].store(ptr, 0, True)
SIMD[DType.bool, 1].store(ptr, 1, True)
# b00000001
# b00000001
```
vs:
```mojo
SIMD[DType.bool, 2].store(ptr, 0, True)
# b00000011
```

**Comment by bgreni** [comment]
@helehex hmm yeah I see your point, loading the entire thing in/out works better now, but trying to do piecemeal operations still doesn't work.

**Comment by MarkOWiesemann** [comment]
Is this supposed to work now? I am on mojo 24.4.0 (2cb57382)

**Comment by MadAlex1997** [comment]
> Is this supposed to work now? I am on mojo 24.4.0 (2cb57382)

They fixed it in nightly but it did not make it into 24.4. And I don't know if it got reverted in nightly.

```python
def main():
    var boolpointer = DTypePointer[DType.bool]().alloc(32)
    boolpointer.store[width=64](0,SIMD[DType.bool,1](True))
    print(boolpointer)
    for i in range(32):
        print(boolpointer[i])
```
```python
True
True
True
True
True
True
True
True
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False```
