### ISSUE TITLE
[Feature Request] support curly braces or some other block symbo

### ISSUE THREAD

**Issue by qq105677765** [modularml/mojo#284]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

```shell
Use support curly braces or some other symbol to partition code
```

### What is your motivation for this change?

```shell
Adjusting the code logic by tab is verbose after pasting code which is from another place. I think that's the most uncomfortable thing about Python.
```

**Comment by s0undt3ch** [comment]
I'm not affiliated with the project, currently just watching progress, but the project clearly states that it's a superset of Python.
Python uses spaces(or tabs) to indent code blocks, and curly braces clearly goes against that.

**Comment by lattner** [comment]
Indeed, our goal is to add system features to python and be a superset, not to be a first-principles new language
