### ISSUE TITLE
[Docs] Typo in K-Means Clustering Guide Posted May 20, 2024

### ISSUE THREAD

**Issue by kasmith11** [modularml/mojo#2840]
### Where is the problem?

[Location of Typo](https://www.modular.com/blog/fast-k-means-clustering-in-mojo-guide-to-porting-python-to-mojo-for-accelerated-k-means-clustering)

### What can we do better?

 In the section `Calculating squared Euclidean distance Python+NumPy and Mojo` there is a reference to k-means plus plus when I believe it should make reference to squared Euclidean distance:

"Below is Python and Mojo implementation of k-means plus plus algorithm (click to zoom, best viewed when browser is full screen). The red boxes show what changes we needed to make to port code over to Mojo."

**Comment by hogepodge** [comment]
Looking at the code and the algorithm, I don't think that there's anything incorrect about what was written. The code as written looks in line with the k-means++ algorithm.
