### ISSUE TITLE
[BUG] [stdlib] String's `UnsafePointer` does not give correct UInt8 values

### ISSUE THREAD

**Issue by martinvuyk** [modularml/mojo#2844]
### Bug description

Both of these should print true yet the one with the pointer doesn't. I'm guessing this has to do with the whole transition from si8 to ui8. And I think this might also explain other weird bugs I encountered.
```mojo
fn main():
    alias spaces = SIMD[DType.uint8, 8](
        ord(" "),
        ord("\t"),
        ord("\n"),
        ord("\r"),
        ord("\f"),
        ord("\v"),
        ord("\v"),
        ord("\v"),
    )
    var item1: UInt8 = String("\v").as_bytes()[0]
    var item2: UInt8 = String("\v").unsafe_uint8_ptr()[0]
    print((spaces & item1).cast[DType.bool]().reduce_or())
    print((spaces & item2).cast[DType.bool]().reduce_or())
```

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
`mojo 2024.5.2605`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by mikowals** [comment]
The pointer will always be empty by design when you call `String("\v").unsafe_uint8_ptr()[0]`.  That is both the first and last use of the String being created so the pointer will immediately be freed.  

You need to keep the String in use until after you read the pointer.  Like this:

```mojo
fn main():
    alias spaces = SIMD[DType.uint8, 8](
        ord(" "),
        ord("\t"),
        ord("\n"),
        ord("\r"),
        ord("\f"),
        ord("\v"),
        ord("\v"),
        ord("\v"),
    )
    var item1: UInt8 = String("\v").as_bytes()[0]
    var v = String("\v")
    var item2: UInt8 = v.unsafe_uint8_ptr()[0]
    print((spaces & item1).cast[DType.bool]().reduce_or())
    print((spaces & item2).cast[DType.bool]().reduce_or())
    _ = len(v)
```
returns True twice.
