### ISSUE TITLE
[Feature Request] [stdlib] Add support for `SIMD[DType.bool, _].reduce_add()`

### ISSUE THREAD

**Issue by martinvuyk** [modularml/mojo#2858]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

As title.

### What is your motivation for this change?

Being able to count how many items in the vector contain the value
```mojo
_ = (~(vec ^ value).cast[DType.bool]()).reduce_add()
```
constraint failed: the SIMD type must be numeric

my current workaround:
```mojo
var different = (vec ^ value).cast[DType.bool]().cast[DType.uint8]()
return int(vec.size - different.reduce_add())
```

**Comment by soraros** [comment]
You can write `(v == 1.0).cast[DType.uint8]().reduce_add()`, which is not that bad.

**Comment by martinvuyk** [comment]
> You can write `(v == val).cast[DType.uint8]().reduce_add()`, which is not that bad.

that's simple enough, thanks
