### ISSUE TITLE
[BUG] Undefined behaviour when indexing into `VariadicList`

### ISSUE THREAD

**Issue by YichengDWu** [modularml/mojo#2864]
### Bug description

`VariadicList` doesn't check bounds. And surprisingly it doesn't support negative indexing neither.

### Steps to reproduce

```mojo
fn f(*values: Int) -> Int:
  return values[3]
 
fn g(*values: Int) -> Int:
  return values[-1]
   
fn main():
  var a = f(1,2)
  print(a)
  var b = f(3,4)
  print(b)
 
  var c = g(3,4)
  print(c)
  var d = g(5,6)
  print(d)
 
```

```shell
94795649406992
7
7
7
```

### System information

```shell
The playground.
```

**Comment by JoeLoser** [comment]
[https://github.com/modularml/mojo/pull/2886](https://github.com/modularml/mojo/pull/2886) is an approach, but comes with some runtime costs due to the bounds checking.  We're deciding not to pursue that right now, but may reconsider in the future.  For now, I'm going to mark this as "won't fix".
