### ISSUE TITLE
[BUG] ```.modular/crashdb/pending``` error in mojo docker.

### ISSUE THREAD

**Issue by Av1nag** [modularml/mojo#2876]
### Bug description

I'm using nightly release of mojo docker. After the modifications, it installed as expected but having this error while trying to run the mojo file. Hope you can find the attachment below for the reference

**Attachment**

![ Screenshot from 2024-05-29 09-32-41](https://uploads.linear.app/2f794fde-0e09-4092-aa52-1ed3e9241f74/c0896512-59de-424e-a4fa-679a589846bb/461f05c3-32a7-4ecb-b200-b5c548f7502e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzJmNzk0ZmRlLTBlMDktNDA5Mi1hYTUyLTFlZDNlOTI0MWY3NC9jMDg5NjUxMi01OWRlLTQyNGUtYTRmYS02NzlhNTg5ODQ2YmIvNDYxZjA1YzMtMzJhNy00ZWNiLWIyMDAtYjVjNTQ4Zjc1MDJlIiwiaWF0IjoxNzE2OTk5MTIxLCJleHAiOjMzMjg3NTU5MTIxfQ.n5ZH0dEQKaUbVU9dXxaXCtxh1dwrA_oeqSa7L2au4Zw)

### Steps to reproduce

* Install mojo using docker from [modularml/mojo:nightly](https://github.com/modularml/mojo/tree/nightly)
* Create and run the container in bash using `docker run -it -v $PWD:/workspace --network=host --name=mojo modular/mojo-v bash`
* Create a mojo file and run it using `mojo file-name.mojo` command in the mojo CLI
* The you might get the error

### System information

```shell
- What OS did you do install Mojo on ?
  Docker Ubuntu
- Provide version information for Mojo by pasting the output of `mojo -v`
  mojo 24.3.0 (9882e19d)
- Provide Modular CLI version by pasting the output of `modular -v`
  modular 0.8.0 (39a426b5)
```

**Comment by Av1nag** [comment]
Hi @JoeLoser, Don't know whether this error is related to ```mojo``` or ```docker```, could you give a clarification about this issue. 
Thank you.

**Comment by ematejska** [comment]
@shashankprasanna I know you wrote the docker bog post.  Any ideas here?

**Comment by Av1nag** [comment]
> @shashankprasanna I know you wrote the docker bog post. Any ideas here?

Hey, I think it's not related to docker, although it's related to mojo itself. Also I request @shashankprasanna to update the Docker blog aligned to the latest mojo version. The updated docker is released in the nightly version, hope you can look into it.
