### ISSUE TITLE
[Feature Request] [stdlib] Make `String`'s `split` method accept `None` as the separator

### ISSUE THREAD

**Issue by siitron** [modularml/mojo#2880]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Currently, `String`'s `split` method does not support `None` as the separator to split on. In Python it's fully possible to perform splits such as `some_string.split(None)` and `some_string.split(None, maxsplit=1)` and `some_string.split(None, 2)`. This is the same as not providing any `sep` at all.

### What is your motivation for this change?

Python interoperability

**Comment by laszlokindrat** [comment]
Thanks for filing this! Should be a simple fix, but I would request that whoever does this also investigates if we could have an overload taking a `StringSlice` for sep as a general improvement.

**Comment by martinvuyk** [comment]
I think this can be solved similarly to Optional's constructor `fn __init__(inout self, value: NoneType):`

I would like to take this on once PR #2868 is merged, since I also wanna refactor that same split overload to take all separators into account.

**Comment by martinvuyk** [comment]
Hi @siitron could you close this issue? It's fixed
