### ISSUE TITLE
[BUG] bug for `SIMD[int64]` when initializing alias

### ISSUE THREAD

**Issue by LJ-9801** [modularml/mojo#2882]
### Bug description

When initializing an alias for `SIMD[Dtype.int64]`, any value bigger than 2\*\*30 will cause a compiler crash. If the value is typed in, it will be ok.

### Steps to reproduce

This was found when implementing tests cases for the bit module.

```mojo
alias var1 = SIMD[Dtype.int64, 4](1, 2, 3, 2**30) # good
alias var2 = SIMD[Dtype.int64, 4](1, 2, 3, 2**31) # not good
alias var3 = SIMD[Dtype.int64, 4](1, 2, 3, 2147483648) # good (this equals 2**31)
alias var4 = SIMD[Dtype.int64, 4](1, 2, 3, 2**32) # not good
alias var5 = SIMD[Dtype.int64, 4](1, 2, 3, 4294967296) # good (this equals 2**32)
```

Error Message

```
failed to fold operation pop.cast(#pop : !pop.scalar)
```

### System information

```shell
- What OS did you do install Mojo on ? MacOS Sonoma 14.5
- Provide version information for Mojo by pasting the output of `mojo -v` mojo 2024.5.2912
- Provide Modular CLI version by pasting the output of `modular -v` modular 0.8.0
```

**Comment by JoeLoser** [comment]
Thanks for filing the issue.  This doesn't seem to repro anymore with latest nightly, likely due to some @laszlo's recent work in the SIMD area?  Can you please take a look and reply here if it's still an issue for you?
