### ISSUE TITLE
[Feature Request] High level ML layers

### ISSUE THREAD

**Issue by timmermansjoy** [modularml/mojo#29]
## Request

The ability to have high level layers kinda like in the [`keras.layers`](https://keras.io/api/layers/) api to kinda do something like `layers.Dense(32, activation='relu')` or [`pytorch.nn`](https://pytorch.org/docs/stable/nn.html) with `torch.nn.Linear(5, 32)`

### Motivation

this will even reduce the barrier to entry and already have optimised functions for these basic building blocks of nn's. although there will probably be arguments about this if the community should creates libraries like these 

### Description and Requirements

have all the building blocks of a NN in high level functions to make it easier for users to use

**Comment by lattner** [comment]
This will be really cool, but we need to build out a bunch of things before tackling this; and this is probably best built by the community.  Right now we're focused on issues tracking mojo compiler/language bugs, so I'm going to close this (even though I want it badly ;-)
