### ISSUE TITLE
[Feature Request] [stdlib] [proposal] Add linalg package

### ISSUE THREAD

**Issue by martinvuyk** [modularml/mojo#2907]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

I think a linalg package similar to [numpy's](https://numpy.org/doc/stable/reference/routines.linalg.html) or better yet like [scipy's](https://docs.scipy.org/doc/scipy/reference/linalg.html#module-scipy.linalg) that is built from the ground up with SIMD will be very good for Mojo. Not depending on Fortran or C libraries (BLAS, LAPACK, etc.) and platform-specific optimizations and building them with Mojo would be epic.

### What is your motivation for this change?

- Having an stdlib made linalg package will make the Mojo ecosystem less fragmented.
- Things like Matrix should be standardized and not need to be reimplemented for each project. 
- Centralizing such algorithms allows for some very clever optimizations that we know Mojo is capable of. 

### Any other details?

This slides very close to what the MAX engine is supposed to be, but the main interest is to have standardized and powerful linear algebra on 1 and 2 D arrays.

**Comment by rparolin** [comment]
Hey @martinvuyk!  Thanks for submitting this proposal.  I discussed this with the Mojo stdlib team and determined (as you pointed out in the proposal) that this is outside the current scope of the Mojo stdlib as we ship equivalent functionality in our MAX product.  Therefore, I recommend we don't integrate it at this time.  As we share more about our package management strategy, I could see this be a community supported library that we re-evaluate in the future if its popular amongst the community.

Many thanks again for taking the time to submit this proposal and being an active part of the Mojo community!

CC: @JoeLoser
