### ISSUE TITLE
[stdlib] Add safe, non-allocating `FileHandle.write(..)` overload

### ISSUE THREAD

**Issue by ConnorGray** [modularml/mojo#2909]
We should add a `FileHandle.write(Span[UInt8, _, _])` overload for safely writing a borrowed sequence of bytes.

Currently, the `FileHandle` type used to read and write data to an opened file descriptor currently provides three `write(..)` method overloads:

* `FileHandle.write(String)` — requires allocating a `String`
* `FileHandle.write(StringRef)` — use of the unsafe and easy-to-misuse `StringRef` type
* `FileHandle.write(UnsafePointer[UInt8], Int)` — requires use of `UnsafePointer`

This means that all currently existing ways to write to a file are either non-optimal or requires dipping down into low-level unsafe code.

**Comment by keshavvinayak01** [comment]
Can I take this up?
