### ISSUE TITLE
[BUG] Structs cannot be recursive even through indirection

### ISSUE THREAD

**Issue by sa-** [modularml/mojo#291]
### Bug description

"Steps to reproduce" contains a simplified example. I would like to use this in my `Tensor` struct so that I can implement back propagation

### Steps to reproduce

Follow up, the pointer version seems to throw an error

```python
@value
struct Node:
    var left: Pointer[Self]
    var right: Pointer[Self]

let n = Node(Pointer[Node].get_null(), Pointer[Node].get_null())
```

Error:
```
error: Expression [2]:16:5: 'pop.store' op failed to verify that pointer element type
    let n = Node(Pointer[Node].get_null(), Pointer[Node].get_null())
    ^
```

### Context
It would of course be nice to just be able to use null values eventually, using pointers is a stopgap
```python
@value
struct Node:
    var left: Self?
    var right: Self?

let n = Node(None, None)
```

**Comment by lattner** [comment]
@Mogball can you take a look at this?

**Comment by Mogball** [comment]
This is a known issue. Structs cannot be recursive at all at the moment.

**Comment by Mogball** [comment]
closing as dupe of #74
