### ISSUE TITLE
[Feature Request] Add default path . to mojo test

### ISSUE THREAD

**Issue by eric-vader** [modularml/mojo#2916]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Add path `.` as part of the default list of directories to search for imported Mojo files.

### What is your motivation for this change?

Given a std folder structure, 
```
mypkg/
test/
main.mojo
README.md
```

One would need to run `mojo test -I .` to execute the tests even though one is following the standard structure.

There is no need to specify the path for the common use case.
In more esoteric use-cases, it would make sense to specify, but not for the default/std structure.

**Comment by ematejska** [comment]
This should be working now in nightlies.
