### ISSUE TITLE
[stdlib] Avoid using various lit-specific substitution in tests

### ISSUE THREAD

**Issue by JoeLoser** [modularml/mojo#2918]
Several tests use various lit substitution syntax (https://llvm.org/docs/CommandGuide/lit.html#substitutions) that will only work with the lit test runner.  Since we want these tests to work with other test runners (such as the one with `mojo test`), we need to rework these parts.  Thankfully, a lot of them (all?) should be able to be achieved with various `Path` functions that we have in the `pathlib` module now in the standard library — which we didn't have at the time of writing these tests.

**Comment by StandinKP** [comment]
@Dan13llljws are you going to work on this? If not I would be happy to take it up

**Comment by JoeLoser** [comment]
> @Dan13llljws are you going to work on this? If not I would be happy to take it up

He has a PR up internally for this right now.

**Comment by StandinKP** [comment]
cool. Thanks @JoeLoser 
@Dan13llljws let me know if you need any help
