### ISSUE TITLE
[Feature Request] Split `dict.pop` into two overloads like `get`.

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#2921]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

As title.

### What is your motivation for this change?

There is no reason to have a raising `pop` when `default` is provided.

### Any other details?

Should be a good first issue.

**Comment by JoeLoser** [comment]
I agree.  Thanks for filing this issue.  I added the appropriate GitHub labels too in case anyone wants to work on this.

**Comment by keshavvinayak01** [comment]
Hey, I can take this up. @soraros @JoeLoser Could you provide a bit more detail?

**Comment by soraros** [comment]
@keshavvinayak01 you don't have to ask! If you are interested, please go ahead.
