### ISSUE TITLE
[BUG] Early destruction of DTypePointer

### ISSUE THREAD

**Issue by dreycenfoiles** [modularml/mojo#2928]
### Bug description

I have found a case where a destructor is called too early on one of my types. In the attached code sample, I have a type that, when initialized, allocates a DTypePointer. I assign a value to that pointer and print the newly changed value. If the discard line at the end of the code sample is commented out, the change in the pointer will not appear, which to me indicates that it has been too eagerly freed. If the last line is present in the code, the pointer's change is visible.

### Steps to reproduce

```
struct Array[rank: Int, dtype: DType = DType.float64]:
    var data: DTypePointer[dtype]

    var size: Int
    var shape: VariadicList[Int]

    alias simd_width: Int = simdwidthof[dtype]()

    fn __init__(inout self, *dims: Int):
        self.shape = dims
        self.size = 1
        for i in dims:
            self.size *= i

        self.data = DTypePointer[dtype].alloc(self.size)
        memset_zero(self.data, self.size)

    fn __del__(owned self):
        self.data.free()


fn main():

    var vec = Array[1, DType.float64](10)

    print(vec.data[0])
    vec.data[0] = 1
    print(vec.data[0])
    _ = vec.data
```

### System information

```shell
- Ubuntu 24.04
- mojo 2024.6.205 (2ccfbc94)
- modular 0.8.0 (39a426b5)
```

**Comment by ehsanmok** [comment]
Confirming the issue!

```mojo
fn main():
    var vec = Array[DType.float64](2)
    vec.data[0] = 1
    print(vec.data[0])
```
prints `0.0` but

```mojo
fn main():
    var vec = Array[DType.float64](2)
    vec.data[0] = 1
    print(vec.data[0], print.data[1])
```
prints `1.0 0.0`

**Comment by ehsanmok** [comment]
@jeff this is a strange behaviour and checked with `mojo 24.4.0 (267bbe2e)`

**Comment by lattner** [comment]
This actually behaves correctly.  The code is equivalent to:

```
fn main():
    var vec = Array[1, DType.float64](2)
    vec.data[0] = 1
    var tmp_ptr = vec.data[0]
    # Array.__del__(vec)   <= vec destroyed here because the access above is the last use of vec.
    print(tmp_ptr) # Dereference a dangling pointer.
```

The issue here is that the pointer doesn't keep the interior object alive.  For this, you need to get into the world of lifetimes - so the compiler knows the reference returned needs the Array object to be alive.  This is being built out now in the nightlies, e.g. look at how InlineArray.getitem works

**Comment by ehsanmok** [comment]
Why isn't `print(vec.data[0])`considered use of `vec` and avoiding dtor to happen earlier?

```
vec.data[0] = 1
print(vec.data[0]) <-- prints 0
```
