### ISSUE TITLE
[Feature Request] a new lint rule to require that each block must end with #. (HashtagDot) or # or a new line.

### ISSUE THREAD

**Issue by EdSaleh** [modularml/mojo#2929]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Hello,

Please create a new lint rule to require that each block must end with # or #. or a new line.
This would work as a curly braces blocks found in C style languages.
Also, this could also be used to reformat python code by code editor to fix any indentation issues.

Users can also use a different word symbol or use a new line for this purpose. (#., #, #/, newline, etc). The user has the option to select the keyword they would like to have for the project. The difference between this proposal (:\n code_block \n#.) and curly braces ({}) in C languages is that curly braces are also indentation insensitive while this proposal is indentation sensitive just like indentation style languages.

There could also be a configurable threshold limit for block lines for which the `code_block_ending_marker` rule is activated and would apply (example: block_lines > 1 lines by default). 
Users can also use new line instead of # or #. by configuring `code_block_ending_marker_word` if it fits their project development.

Example:

```python
import string
def atbash(sequence: str) -> str:
    """
    Example
    """
    output = ""
    for i in sequence:
        extract = ord(i)
        if 65 <= extract <= 90:
            output += chr(155 - extract)
        #.
        elif 97 <= extract <= 122:
            output += chr(219 - extract)
        #.
        else:
            output += i
        #.
    #.
    return output
#.
```

There are cases where strict block guarantees is required. Also, when copying python code sometimes spacing is not aligned correctly and having code with this style with editor support, editor would fix incorrect spacing easily.

```python
if(True):
print(True)
print(True)
#
if(True):
print(True)
print(True)
#
```

OR

```python
if(True):
print(True)
print(True)
#.
if(True):
print(True)
print(True)
#.
```
would be aligned correctly by the editor to:

```python
if(True):
 print(True)
 print(True)
#
if(True):
 print(True)
 print(True)
#
```
OR
```python
if(True):
 print(True)
 print(True)
#.
if(True):
 print(True)
 print(True)
#.
```

Thank you,

### What is your motivation for this change?

[Feature Request] new lint rule to require a comment #. at end each python block.

**Comment by ksandvik** [comment]
The goal of Python is to be pythonic in syntax, and this syntax is not Python-based. Most modern code editors assist with block alignments today.

**Comment by EdSaleh** [comment]
> The goal of Python is to be pythonic in syntax, and this syntax is not Python-based. Most modern code editors assist with block alignments today.

There are cases where strict block guarantees is required. Also, when copying python code sometimes spacing is not aligned correctly and having code with this style with editor support, editor would fix incorrect spacing easily.

```python
if(True):
print(True)
Print(True)
#
if(True):
print(True)
Print(True)
#
```
would be aligned correctly by the editor to:

```python
if(True):
 print(True)
 Print(True)
#
if(True):
 print(True)
 Print(True)
#
```

**Comment by EdSaleh** [comment]
> The point made [here](https://github.com/pylint-dev/pylint/issues/9684) applies to Mojo as well. There is little chance Mojo is going to adopt something that's against a fundamental property of Python syntax.

the issues reference an issue outside mojo are not related. this request is just for creating a lint rule and the language stays the same.

**Comment by EdSaleh** [comment]
I have also contributed to rust lint previously and my proposal was completed and merged.
https://github.com/rust-lang/rust-clippy/issues/2685

**Comment by walter-erquinigo** [comment]
Sadly this doesn't align with the pythonic syntax we try to follow, so we won't be able to work on this.
However, I recommend you implementing a VSCode extension that adds visual modifiers at the end of every section.
