### ISSUE TITLE
[Docs] VS Code Extension Config | Getting Started Broken

### ISSUE THREAD

**Issue by VinLucero** [modularml/mojo#2943]
### Where is the problem?

VS Code Extension Config

### What can we do better?

![image](https://github.com/modularml/mojo/assets/3068574/de5d4232-6042-4cdb-a263-746945f29dbd)

<img width="773" alt="image" src="https://github.com/modularml/mojo/assets/3068574/ad46848b-54c1-4392-a7fa-6812bab62bc0">

![image](https://github.com/modularml/mojo/assets/3068574/16d2f39a-1b17-466d-804f-734243833c42)

Am I alone in not having VS Code detect the SDK when I pass it correctly?

**Comment by VinLucero** [comment]
<img width="769" alt="image" src="https://github.com/modularml/mojo/assets/3068574/6d4e29f9-a933-43e9-ab91-16a2fbd97756">

**Comment by VinLucero** [comment]
<img width="1535" alt="image" src="https://github.com/modularml/mojo/assets/3068574/3a55d595-5884-43c8-af1f-42e17c32e4bc">

**Comment by walter-erquinigo** [comment]
Oof, this is tricky. Have you tried changing the permissions to that file? I wonder if the user assigned to VSCode can't access the modular config file.

**Comment by walter-erquinigo** [comment]
This issue might be gone now that we have a different distribution model for the SDK.
