### ISSUE TITLE
[BUG] Mojo/Python interoperability error: Unable to locate a suitable libpython, please set `MOJO_PYTHON_LIBRARY`

### ISSUE THREAD

**Issue by VinLucero** [modularml/mojo#2944]
### Bug description

![image](https://uploads.linear.app/2f794fde-0e09-4092-aa52-1ed3e9241f74/ac327736-aafb-4b2a-b2b1-0fe7752b3e0f/13173db9-ed32-475a-b5e6-9afe3bbe4a3d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzJmNzk0ZmRlLTBlMDktNDA5Mi1hYTUyLTFlZDNlOTI0MWY3NC9hYzMyNzczNi1hYWZiLTRiMmEtYjJiMS0wZmU3NzUyYjNlMGYvMTMxNzNkYjktZWQzMi00NzVhLWI1ZTYtOWFmZTNiYmU0YTNkIiwiaWF0IjoxNzE3NTE4MzAxLCJleHAiOjMzMjg4MDc4MzAxfQ.hhh-DkGi7oGAGCtJUijBPVy2WE7-llj6IxYUyntkloE "=1514x")

### Steps to reproduce

Attempted to use reduce.mojo from Playground locally after building it and it failed with Python interaction.

Mojo/Python interoperability error: Unable to locate a suitable libpython, please set `MOJO_PYTHON_LIBRARY`
zsh: segmentation fault ./device_test

### System information

```shell
- What OS did you do install Mojo on ?
MAC M3
 
(mojo-venv) vince@Vincents-MacBook-M3 scripts % mojo -v
mojo 24.3.0 (9882e19d)
(mojo-venv) vince@Vincents-MacBook-M3 scripts % modular -v
modular 0.8.0 (39a426b5)
(mojo-venv) vince@Vincents-MacBook-M3 scripts %
```

**Comment by VinLucero** [comment]
Could this be related to me not having the underlying dependencies as seen here?

https://github.com/modularml/mojo/issues/1085#issuecomment-1771403719

**Comment by jackos** [comment]
Hi try running this script, it will find a libpython on your system if it exists and give you a command to link to it. If not let me know:

```
import os
import subprocess

FIND_LIBPYTHON = """
import os
import sys
from pathlib import Path
from sysconfig import get_config_var
ext = "dll" if os.name == "nt" else "dylib" if sys.platform == "darwin" else "so"
binary = f"libpython{get_config_var('py_version_short')}.{ext}"
for folder in [Path(get_config_var(p)) for p in ["LIBPL", "LIBDIR"]]:
    libpython_path = folder / binary
    if libpython_path.is_file():
        print(libpython_path.resolve())
        exit(0)
exit(1)
"""
FIND_PYTHON_VER = "import sysconfig; print(sysconfig.get_python_version())"

exe_names = ["python3", "python"] + [f"python3.{i}" for i in range(8, 13)]
seen = []
executables = []

print("Mojo will attempt to use the first python executable from the top:\n")
print("vers | compat | path")
for path in os.environ["PATH"].split(":"):
    for exe in exe_names:
        full_path = os.path.join(path, exe)
        if os.path.exists(full_path):
            pyver = subprocess.check_output([full_path, "-c", FIND_PYTHON_VER], text=True).strip()
            res = subprocess.run([full_path, "-c", FIND_LIBPYTHON], text=True, capture_output=True)
            libpython = res.stdout.strip()
            if res.returncode != 0:
                print(f"{pyver:<7} no      {full_path}")
            elif libpython not in seen:
                print(f"{pyver:<7} yes     {full_path}")
                seen.append(libpython)
                executables.append(full_path)

if not executables:
    print("no compatible Python environments found")
else:
    print("\nChoose a version of libpython that matches the version of python you have on top of PATH:")
    print(f'    MOJO_PYTHON_LIBRARY="{seen[0]}"')
```

**Comment by jackos** [comment]
This is fixed in next release btw, it will soon automatically find the associated libpython

**Comment by jackos** [comment]
You can test now with `modular install nightly/mojo` please reopen if this doesn't resolve your issue

**Comment by VinLucero** [comment]
Updated to the modular nightly and still got this error:

<img width="775" alt="image" src="https://github.com/modularml/mojo/assets/3068574/ced6a2aa-8c53-42d3-a4d5-b4278dfcfe7c">


Here is my ZSHRC file:

<img width="609" alt="image" src="https://github.com/modularml/mojo/assets/3068574/14ca216f-ec74-48c5-8137-b2a3fa45f1ff">


Here is the output of your script:

<img width="670" alt="image" src="https://github.com/modularml/mojo/assets/3068574/5718b5c5-c460-4cb8-9a95-7b8b1570a086">

**Comment by VinLucero** [comment]
@jackos I don't see the option to re-open with comment on this repo. Let me know what you would prefer as next step.

**Comment by jackos** [comment]
Hi @VinLucero that error is from the older version before the change, it's fixed in stable now. Please try removing your modular folder and installing again:
```bash
rm -rf ~/.modular
curl -s https://get.modular.com | sh -
modular install mojo
```
If it doesn't work please try activating a venv with 3.11 first and trying again:
```
python3.11 -m venv ~/venv
source ~/venv
modular install mojo
```
