### ISSUE TITLE
mojo crashed!

### ISSUE THREAD

**Issue by ghassenTn** [modularml/mojo#2958]
### Issue description

[38691:38691:20240605,083724.595583:ERROR elf_dynamic_array_reader.h:64] tag not found

### Steps to reproduce

- Add screenshots if possible, to help explain the problem.
- Include anything that might help us debug the issue.

**Comment by ematejska** [comment]
Dup of: [https://github.com/modularml/mojo/issues/1601](https://github.com/modularml/mojo/issues/1601)
