### ISSUE TITLE
[Docs] No reference to Cython in the documentation

### ISSUE THREAD

**Issue by matrach** [modularml/mojo#297]
### Where is the problem?

https://docs.modular.com/mojo/why-mojo.html#related-work

### What can we do better?

[Cython](https://cython.org/), the actual competition and closely related work is not mentioned anywhere in the docs. Neither is its predecessor: [Pyrex](https://wiki.python.org/moin/Pyrex).

Cython is [widely used](https://github.com/search?q=language%3ACython&type=code&l=Cython) in the scientific Python community. For instance:
- [scikit-learn](https://github.com/search?q=repo%3Ascikit-learn%2Fscikit-learn%20path%3A**%2F*.pyx&type=code)
- some parts of [numpy](https://github.com/search?q=repo%3Anumpy%2Fnumpy+path%3A**%2F*.pyx&type=code)
- [scipy](https://github.com/search?q=repo%3Ascipy%2Fscipy+language%3ACython&type=code&l=Cython)

Since the utilities are so similar, the omission of Cython from the docs is very uncanny.

### Anything else?

Is Mojo a fork of Cython? Essentially, the next step of Pyrex -> Cython -> X evolution?

**Comment by lattner** [comment]
@scottamain do you think it is worth adding a mention that Mojo has no relation to these previous projects?  You could frame it positively as "a first principles rethink unrelated to existing python acceleration projects" and add unladen swallow, pypy and many other to the list.

**Comment by scottamain** [comment]
Yes, I suppose this Cython is a category of projects that we haven't addressed here. However, I think it's more important that we address the root of the confusion. Even after reading this whole document, if @matrach and others think that Cython is similar and can do what Mojo does, then we've missed something important.

**Comment by scottamain** [comment]
Thanks for the feedback! We've added some more information here: https://docs.modular.com/mojo/why-mojo.html#python-supersets-with-c-compatibility
