### ISSUE TITLE
[BUG] DType inside a `fn` function results in error

### ISSUE THREAD

**Issue by ivellapillil** [modularml/mojo#2983]
### Bug description

When we execute the following code:

```mojo
def main():
    fn introspect(type: DType):
        print("Bit width:", type.bitwidth())
        print("Is signed:", type.is_signed())
     
    introspect(DType.float16)
```

It results in the following error:

```
/Users/ec2-user/actions-runner/_work/modular/modular/Kernels/mojo/stdlib/builtin/dtype.mojo:468:44: error: failed to legalize operation 'pop.dtype.sizeof' that was explicitly marked illegal
/Users/ec2-user/actions-runner/_work/modular/modular/Kernels/mojo/stdlib/builtin/dtype.mojo:468:44: note: see current operation: %37 = "pop.dtype.sizeof"(%0) : (!kgen.dtype) -> index
mojo: error: Failed to materialize symbols: { (exec, { _main, _KGEN_EE_JIT_GlobalConstructor, _KGEN_EE_JIT_GlobalDestructor }) } (from the layer: failed to lower module to LLVM IR for archive compilation)
```

The above code used to work in at least one earlier version of Mojo compiler.

### Steps to reproduce

Please execute the above code

### System information

```shell
System Version: macOS 14.1 (23B74)
Kernel Version: Darwin 23.1.0
Model Name: MacBook Pro
Model Identifier: MacBookPro18,3
Model Number: MKGP3SM/A
Chip: Apple M1 Pro
Total Number of Cores: 8 (6 performance and 2 efficiency)
Memory: 16 GB
 
 
mojo 24.4.0 (2cb57382)
 
modular 0.7.4 (df7a9e8b)
```

**Comment by guna-sd** [comment]
The issue you're encountering is from the way Mojo handles function parameters, particularly when dealing with types like DType. In your initial implementation, the type is passed as a function argument, which causes issues with Mojo's type system. Instead, you need to use a parametric function where the type is specified as a parameter like below

def main():
    fn introspect[type: DType]():
        print("Bit width:", type.bitwidth())
        print("Is signed:", type.is_signed())

    introspect[DType.float16]()


this would work correctly

**Comment by ivellapillil** [comment]
> The issue you're encountering is from the way Mojo handles function parameters, particularly when dealing with types like DType. In your initial implementation, the type is passed as a function argument, which causes issues with Mojo's type system. Instead, you need to use a parametric function where the type is specified as a parameter like below

The bug is actually a regression. The same code used to work before, I am not sure in which version this regression appeared though. Moreover, limitations are usually the other way round. Not all runtime constructs can be instantiated at compile-time, but compile-time constructs should be possible to be instantiated at runtime. 

If it is really a constraint from Mojo, then we need a more clear compiler error message.

The following code actually works.

```mojo
def main():
    fn introspect(type: DType):
        print("Bit width:", type.bitwidth())
    
    introspect(DType.float16)
```

**Comment by JakeEBrooks** [comment]
This seems to be connected to an issue I posted some time ago: #2194. Both involve something going on with `sizeof()`.

**Comment by tatianashp** [comment]
Thanks for reporting the issue! This is now fixed at the top-of-the-tree.
