### ISSUE TITLE
[Feature Request] Allow the use of ` -D MOJO_ENABLE_ASSERTIONS` with `mojo test`

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [modularml/mojo#2992]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

I'd like to set options when using `mojo test`.

### What is your motivation for this change?

We run the tests in the stdlib with assertions enabled. We can't start using `mojo test` unless this feature is available

**Comment by AmaranthineCodices** [comment]
This will be fixed in the 24.5 release.
