### ISSUE TITLE
Unhandled exception caught during execution: No module named 'numpy'

### ISSUE THREAD

**Issue by vishcodex** [modularml/mojo#3002]
### Issue description

![image](https://uploads.linear.app/2f794fde-0e09-4092-aa52-1ed3e9241f74/5921ee4d-0d8c-42c6-9d44-4a66d090f058/bb756220-b915-40d9-8a9e-7c587e79ac4c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzJmNzk0ZmRlLTBlMDktNDA5Mi1hYTUyLTFlZDNlOTI0MWY3NC81OTIxZWU0ZC0wZDhjLTQyYzYtOWQ0NC00YTY2ZDA5MGYwNTgvYmI3NTYyMjAtYjkxNS00MGQ5LThhOWUtN2M1ODdlNzlhYzRjIiwiaWF0IjoxNzE4MDQ0MTU5LCJleHAiOjMzMjg4NjA0MTU5fQ.nin3ZvNMgPAekwhSQoi7-NBKhad7LH22pIZJZ4RD284 "=939x")

Error:

Unhandled exception caught during execution: No module named 'numpy'
mojo: error: execution exited with a non-zero result: 1

### Steps to reproduce

* Include relevant code snippet that did not work as expected.
* If applicable, add screenshots to help explain the problem.
* Include anything else that might help us debug the issue.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v` : mojo 24.4.0 (2cb57382)
- What OS did you install modular CLI on ? : MacOS M1
```

**Comment by vishcodex** [comment]
As shown on the screenshot, I see the modules installed, Still I am facing the issue. Thank You!

**Comment by jackos** [comment]
Hi @vishcodex can you please show me the output of running this with Mojo:

```mojo
from python import Python
from os.env import getenv


def main():
    var pre_init_lib = getenv("MOJO_PYTHON_LIBRARY")
    if pre_init_lib:
        print("\npython_lib:", pre_init_lib, end="\n\n")
    sys = Python.import_module("sys")
    print("----module-paths----")
    for p in sys.path:
        print(p)
    print("\npython_lib:", getenv("MOJO_PYTHON_LIBRARY"))
    print("python_exe:", getenv("PYTHONEXECUTABLE"))
```

**Comment by jackos** [comment]
And also the output of this command: `mojo --version`

**Comment by vishcodex** [comment]
Hi @jackos , Please find the output :-)

<img width="952" alt="image" src="https://github.com/modularml/mojo/assets/108595774/b93f48f8-d713-49a1-90ea-098ecf653db4">

**Comment by jackos** [comment]
It looks like the conda environment isn't active, can you do:

```bash
/Users/AF82152/anaconda3/bin/conda init --all
```
Then restart your shell and do:

```bash
conda activate mojo
```

And try running again?

**Comment by jackos** [comment]
What is the output when you run the command:

```
which -a python3
```

**Comment by vishcodex** [comment]
Please find below 

<img width="920" alt="image" src="https://github.com/modularml/mojo/assets/108595774/bfb00edb-a3ea-4734-926b-b79f499ff635">

**Comment by jackos** [comment]
Yes your conda environment should go to the top of `PATH` when you activate it, but here you have `/opt/homebrew/bin/python3` twice ahead of it. Try these until one of them fixes it:

* Restart your shell and activate again with `conda activate mojo`
* Check your `~/.zshrc` or `~/.bashrc` (whichever shell you're using) and make sure the conda activation script is at the end
* Remove `anaconda3` with `rm -r ~/anaconda3` (and delete the script out of your shell activation script) and install `miniconda3` instead: [https://docs.anaconda.com/free/miniconda/#quick-command-line-install](https://docs.anaconda.com/free/miniconda/#quick-command-line-install)<br><br>One of those should fix it, if nothing works you can explicitly add it to the top of your `PATH`
* Explicitly add the path at the end of your startup script:<br>\`\`\`bash<br>export PATH="\~/anaconda3/envs/mojo/bin:$PATH"<br>\`\`\`

**Comment by vishcodex** [comment]
thanks a lot @jackos for your prompt response in resolving this issue. 

<img width="920" alt="image" src="https://github.com/modularml/mojo/assets/108595774/0e07ec44-27e2-4d04-8c4e-f5d36cbddbbe">
