### ISSUE TITLE
[BUG] VsCode Nightly Extension: `install_id` gets dumped in every cwd when opening VsCode

### ISSUE THREAD

**Issue by martinvuyk** [modularml/mojo#3017]
### Bug description

As title. Happens on any directory. I've already pushed install_id on python and SQL projects at work as well...

At the beginning I was getting an error on the CLI that a db dump file already existed. Went and deleted it and it now still dumps just with no error.

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
`Ubuntu 22.04.4 LTS` 
- Provide version information for Mojo by pasting the output of `mojo -v`
`mojo 2024.6.1105`
- Provide Modular CLI version by pasting the output of `modular -v`

Mojo 🔥 (nightly)
v2024.6.1105
```

**Comment by jackos** [comment]
Thanks @martinvuyk there's an internal PR to remove this, hopefully be in next nightly release

**Comment by jackos** [comment]
Merged for next nightly thanks
