### ISSUE TITLE
[BUG] Crash when declaring a nested struct with a variable of the same type

### ISSUE THREAD

**Issue by guna-sd** [modularml/mojo#3025]
### Bug description

**When declaring a struct that contains a variable of its own type, the code crashes**. This issue is not limited to any specific struct but occurs with any struct that includes a variable of the same struct type. The expected behavior is for the code to compile without errors, but it results in a crash instead.

This issue appears to be related to the recursive nature of the struct declaration, where a struct contains a variable of its own type. **This problem is critical as it affects the ability to define common data structures like linked lists, trees, and others that require self-referential types.**

#### issue code

```mojo
@value
struct Node:
    var data: Int
    var next: Optional[Node]
```

**Crash log**

\[34229:34229:20240612,222743.659602:WARNING process_reader_linux.cc:144\] no stack mapping
Please submit a bug report to [https://github.com/modularml/mojo/issues](https://github.com/modularml/mojo/issues) and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.      Program arguments: /home/guna/.modular/pkg/packages.modular.com_mojo/bin/mojo /home/guna/Projects/new/test.mojo
\[34229:34230:20240612,222743.692664:ERROR directory_reader_posix.cc:42\] opendir /home/guna/.modular/crashdb/attachments/542b6caf-68ed-4ad1-9bf0-6a0f03aa4c0d: No such file or directory (2)
  #0 0x000059c6b1289438 (/home/guna/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x12a1438)
  #1 0x000059c6b128725e (/home/guna/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x129f25e)
  #2 0x000059c6b1289acd (/home/guna/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x12a1acd)
  ...
  #255 0x000059c6b17c1950 (/home/guna/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x17d9950)
  mojo crashed!
  Please file a bug report.
  Segmentation fault (core dumped)

### System information

```shell
Ubuntu 24.04 LTS
mojo 24.4.0 (2cb57382)
modular 0.8.0 (39a426b5)
```

**Comment by ematejska** [comment]
Looks similar to [https://github.com/modularml/mojo/issues/2208](https://github.com/modularml/mojo/issues/2208).

**Comment by ematejska** [comment]
Should this also error out?  In the latest nightly build (mojo 2024.6.1405 (ceceb171), it compiles.  @jeff @tatiana

**Comment by suahelen** [comment]
> Should this also error out? In the latest nightly build (mojo 2024.6.1405 (ceceb171), it compiles. @jeff @tatiana

The struct definition seems to compile but as soon as I try to instantiate it in main the error is there again.

**Comment by msaelices** [comment]
This is happening again in 25.4.0.dev2025053005:
```
@value
struct BinTree:
    var value: Int

    var left: Optional[BinTree]
    var right: Optional[BinTree]

fn main():
    var tree = BinTree(10, None, None)
``` 
```
$ mojo intbintree.mojo
[854329:854329:20250531,104919.101645:WARNING process_reader_linux.cc:144] no stack mapping
Please submit a bug report to https://github.com/modular/modular/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.      Program arguments: mojo inttree.mojo
  #0 0x0000638e782bed8b llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) Signals.cpp:0:0
  #1 0x0000638e782bcb29 llvm::sys::RunSignalHandlers() Signals.cpp:0:0
  #2 0x0000638e782bf43a SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
  #3 0x00007fb56aa45330 (/lib/x86_64-linux-gnu/libc.so.6+0x45330)
  #4 0x00007fb56aa9eb2c __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
  #5 0x00007fb56aa9eb2c __pthread_kill_internal ./nptl/pthread_kill.c:78:10
  #6 0x00007fb56aa9eb2c pthread_kill ./nptl/pthread_kill.c:89:10
  #7 0x00007fb56aa4527e raise ./signal/../sysdeps/posix/raise.c:27:6
  #8 0x00007fb56cdb1542 SignalHandler(int, siginfo_t*, void*) Signals.cpp:0:0
  #9 0x00007fb56aa45330 (/lib/x86_64-linux-gnu/libc.so.6+0x45330)
...
Segmentation fault (core dumped)
```
