### ISSUE TITLE
[Feature Request] Merge `init_pointee_move` and `move_pointee_into`.

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#3038]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

As title.

### What is your motivation for this change?

If I understand correctly, we don't need both.

### Any other details?

N/A

**Comment by bethebunny** [comment]
`init_pointee_move` treats the input as "uninit", which means it won't call the destructor on whatever data is in the pointer already, whereas `move_pointee_into` will call the destructor of the old data before the move.

**Comment by soraros** [comment]
@bethebunny So `s.move_pointee_into(t)` is `t.init_pointee_move(s.take_pointee())`?

**Comment by bethebunny** [comment]
`s.move_pointee_into(t)` should be equivalent to

```mojo
_ = t.take_pointee()
t.init_pointee_move(s.take_pointee())
```

**Comment by soraros** [comment]
But `move_pointee_into` assumes that `dst` is uninitialized.

**Comment by soraros** [comment]
The really difference seems to be that `t.init_pointee_move(s.take_pointee())` calls `moveinit` twice.

```mojo
struct S:
  var data: Float64

  fn __init__(inout self, data: Float64):
    self.data = data

  fn __copyinit__(inout self, other: S):
    print("  copyinit", other.data)
    self.data = other.data

  fn __moveinit__(inout self, owned other: S):
    print("  moveinit", other.data)
    self.data = other.data

  fn __del__(owned self):
    print("  del", self.data)

fn move_pointee_into():
  print("move_pointee_into:")
  var v = S(10)
  var t = UnsafePointer[S].alloc(1)
  var s = UnsafePointer.address_of(v)
  s.move_pointee_into(t)
  print()
  _ = v

fn init_pointee_move():
  print("init_pointee_move:")
  var v = S(20)
  var t = UnsafePointer[S].alloc(1)
  var s = UnsafePointer.address_of(v)
  t.init_pointee_move(s.take_pointee())
  print()
  _ = v

fn main():
  move_pointee_into()
  print()
  init_pointee_move()
```

Result:

```
move_pointee_into:
  moveinit 10.0

  del 10.0

init_pointee_move:
  moveinit 20.0
  moveinit 20.0

  del 20.0
```
