### ISSUE TITLE
[BUG] Possible SIMD[DType.bool, n] tested for truth in the stdlib where n > 1

### ISSUE THREAD

**Issue by thk686** [modularml/mojo#3096]
### Bug description

It appears that some of my code, right or wrong, is triggering a bug where a `SIMD` with `length > 1` is getting passed to `constrained`. That triggers this error message:

/Users/ec2-user/actions-runner/_work/modular/modular/open-source/mojo/stdlib/stdlib/builtin/constrained.mojo:34:6: note:                       constraint failed: The truth value of a SIMD vector with more than one element is ambiguous. Use the builtin `any()` or `all()` functions instead.

### Steps to reproduce

```mojo

trait TestTrait:
    fn test[n: Int](self) -> SIMD[DType.uint64, n]:
        pass


struct TestStruct[m: Int](TestTrait):
    var mem: SIMD[DType.uint64, m]

    fn __init__(inout self):
        self.mem = SIMD[DType.uint64, m](0)

    fn test[n: Int](self) -> SIMD[DType.uint64, n]:
        return self.mem


fn main():
    var x = TestStruct[2]()
    print(x.test[2]())

```

### System information

```shell
Darwin 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:19:05 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8112 arm64
modular 0.8.0 (39a426b5)
mojo 2024.6.2005 (6f19fd07)
```

**Comment by soraros** [comment]
@laszlokindrat Another problem related to #2860.

In this function, Mojo is trying construct a `SIMD[DType.uint64, n]` from a `Boolable` value `self.mem`.
```mojo
    fn test[n: Int](self) -> SIMD[DType.uint64, n]:
        return self.mem
```

You should write it as
```mojo
    fn test[n: Int](self) -> SIMD[DType.uint64, n]:
        return rebind[SIMD[DType.uint64, n]](self.mem)
```

That said, if `n != m`, it won't compile anyway.

**Comment by lbartworks** [comment]
I think this shows as well the same issue:

```
def main():

    var mask=SIMD[DType.bool,8](True, False, False, True, True, True, True, True)
    var mask2=SIMD[DType.bool,8](False, False, False, True, True, True, True, True)

    #works
    print (mask.__and__( mask2))
    
    #does not work
    #print (mask and mask2)
```

**Comment by soraros** [comment]
It's intentional that `m1 and m2` won't work if their size are larger than 1. Should have written
```mojo
print(all(mask) an all(mask2))
```

**Comment by lbartworks** [comment]
No if you want a vectorized AND. In fact, this works vectorized (ie size > 1):

print (mask.__and__( mask2))

**Comment by soraros** [comment]
Exactly, the vectorized and is a different thing from `and`, the operator form is `mask & mask2`.

**Comment by thk686** [comment]
> @laszlokindrat Another problem related to #2860.
> 
> 
> 
> In this function, Mojo is trying construct a `SIMD[DType.uint64, n]` from a `Boolable` value `self.mem`.
> 
> ```mojo
> 
>     fn test[n: Int](self) -> SIMD[DType.uint64, n]:
> 
>         return self.mem
> 
> ```
> 
> 
> 
> You should write it as
> 
> ```mojo
> 
>     fn test[n: Int](self) -> SIMD[DType.uint64, n]:
> 
>         return rebind[SIMD[DType.uint64, n]](self.mem)
> 
> ```
> 
> 
> 
> That said, if `n != m`, it won't compile anyway.

Thanks for the rebind tip. That did indeed solve the problem.
