### ISSUE TITLE
Question, will strings be Unicode?

### ISSUE THREAD

**Issue by nevdelap** [modularml/mojo#31]
I see strings are defined as mutable dynamic vectors of si8 and null terminated for C compatibility. Is that the plan, or temporary? Is it planned that strings be immutable Unicode like Python 3? Thank you.

**Comment by sirinath** [comment]
As Unicode is evolving and there are legacy and custom encodings, I think it is best left open with basic string being Python compatible.

**Comment by lattner** [comment]
+1 we'll follow Python3's approach here.  Thanks!

**Comment by lattner** [comment]
(and to confirm, you're right that the current string is very "toy" implementation :)

**Comment by nevdelap** [comment]
Thanks!
