### ISSUE TITLE
Can we SWAP values in Mojo

### ISSUE THREAD

**Issue by Sai-Vignesh** [modularml/mojo#310]
Unlike Python we can't swap the values of variables in a single statement.

**Comment by abhinav-upadhyay** [comment]
You should use the [Discussions](https://github.com/modularml/mojo/discussions/categories/q-a) for asking questions.

**Comment by Sai-Vignesh** [comment]
Can you tell me how to delete this thread?

**Comment by abhinav-upadhyay** [comment]
You can just close the issue.
