### ISSUE TITLE
[BUG] Functions cannot be parsed during debugging.

### ISSUE THREAD

**Issue by RichardCoppin** [modularml/mojo#3115]
### Bug description

I seem to be unable to evaluate functions while in debug mode in VS Code.

I tried running a simple `print()` statement which failed to parse. I got the following error:
`expression failed to parse (no further compiler diagnostics)`

I could not even evaluate functions in the watch window - same error message.

If you just type the variable name into the debugger - it evaluates as expected, and if I step through the code which would execute the same instruction - that too works without issue.

### Steps to reproduce

Sample code:

```mojo
fn no_op(x: Int) -> Int:
    return x

fn main():
    var x: Int = 1
    var y: Int = no_op(x)
    print(y)  # place breakpoint here.
```
In debug console execute:
`print(x)`

### Expected result:
42

### Actual result:
`expression failed to parse (no further compiler diagnostics)`

### Screenshot:
![image](https://github.com/modularml/mojo/assets/59029926/03cbc309-018b-475d-ad15-b45de3995b16)

### Additional Info:
In fact I cannot evaluate other functions in the Watch window either:
![image](https://github.com/modularml/mojo/assets/59029926/6ddccee4-d4ba-4a9a-8266-34c83957ea1d)

### System information

```shell
- What OS did you do install Mojo on ? 
WSL Ubuntu 22.04.3 LTS 
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 2024.6.2305 (1753b945)
Observed the same issue in the official release 2024.4.4.
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.8.0 (39a426b5)
- VS Code Version
Version: 1.90.2 (user setup)
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:34:26.404Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631
```

**Comment by walter-erquinigo** [comment]
Thanks for the report, but as of now, the debugger doesn't support evaluating expressions. It can only print variables. Expression evaluation is part of the roadmap, so I'll be closing this.
