### ISSUE TITLE
[Docs] Vectorize docs are outdated

### ISSUE THREAD

**Issue by martinvuyk** [modularml/mojo#3116]
### Where is the problem?

algorithm

### What can we do better?

Docs are outdated in relation to the new DTypePointer API.

Trying to get this to work by following the docs and adapting. (does not work)
```mojo
    fn __contains__(self, value: Self._scalar_type) -> Bool:

        var length = len(self)
        alias simd_width = simdwidthof[DType.bool]()
        var p = DTypePointer[DType.bool].alloc(Self._vec_type.size)

        @parameter
        fn closure[simd_width: Int](i: Int):
            p.simd_strided_store[width=simd_width](i, i < length)

        vectorize[closure, simd_width](Self._vec_type.size)
        var size_mask = p.simd_strided_load[width = Self._vec_type.size](
            simd_width
        )
        return ((self.vec == value) & size_mask).reduce_or()
```
It works if I just use a SIMD vec from the beginning:
```mojo
    fn __contains__(self, value: Self._scalar_type) -> Bool:
        var size_mask = SIMD[DType.bool, Self._vec_type.size](False)

        @parameter
        fn closure[simd_width: Int](i: Int):
            size_mask[i] = True

        vectorize[closure, simdwidthof[DType.bool]()](len(self))
        return ((self.vec == value) & size_mask).reduce_or()
```
No idea if there is even a performance difference between these two

**Comment by soraros** [comment]
Actually, if the `self.vec` is already a `SIMD` type, there is no benefit to even use `vectorize` (which is just loops), a [unrolled]loop is better.

**Comment by ematejska** [comment]
What is the link to the docs?  Is it: [https://docs.modular.com/mojo/stdlib/algorithm/functional/vectorize](https://docs.modular.com/mojo/stdlib/algorithm/functional/vectorize)?
