### ISSUE TITLE
return type is not working for a function

### ISSUE THREAD

**Issue by vishcodex** [modularml/mojo#3129]
### Bug description

**Summary**: return statement is not working on a function

Description. While going through the documentation i was testing the functionalities of mojo, when a function with return statement is called in the main function its giving ` error: cannot implicitly convert 'Int' value to 'None' in return value` error. Updating return to print statement is working well.

Environment details: `Mac M1 `
Mojo Compiler Version: `mojo 24.4.0`
Operating System version: `MacOS Sonoma Version 14.5`
Hardware Specifications: `32 GB RAM`
Severity/frequency: `Low`

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- return statement
``` 
fn sum_values(*values: Int):
    var sum: Int = 0
    for value in values:
        sum += value
   return sum

fn main() raises:
    var result = sum_values(3,5)
``` 
- print statement
```
fn sum_values(*values: Int):
    var sum: Int = 0
    for value in values:
        sum += value
    print(sum)

fn main() raises:
    var result = sum_values(3,5)
```
- If applicable, add screenshots to help explain the problem.

with return type :

<img width="1660" alt="image" src="https://github.com/modularml/mojo/assets/108595774/89b119c9-71fd-4944-9de3-c94cb47b856e">

with print statement: 

<img width="1660" alt="image" src="https://github.com/modularml/mojo/assets/108595774/8db81182-d828-4bc5-8aa6-41dba5d39ed7">

- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on? 
MacOS Sonoma Version 14.5
- Provide version information for Mojo by pasting the output of `mojo -v` 
mojo 24.4.0
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.8.0
```

**Comment by soraros** [comment]
It's not a bug. If you add return type to `sum_value` it works:

```mojo
fn sum_values(*values: Int) -> Int:  # <<<
    var sum: Int = 0
    for value in values:
        sum += value
   return sum

fn main() raises:
    var result = sum_values(3,5)
```

`print` works in the other example because `fn f(...): ...` is the same as `fn f(...) -> None: ...`.

**Comment by vishcodex** [comment]
thank you very much!
