### ISSUE TITLE
HelloMojo.ipynb in Jupyter notebook

### ISSUE THREAD

**Issue by m-pedro** [modularml/mojo#314]
### Where is the problem?

Grammatical error in description 

### What can we do better?

The sentence "This notebook assumes you're already familiar Python and some systems programming concepts so we can focus on what's special about Mojo" should read, "This notebook assumes you're already familiar _**with**_ Python and some systems programming concepts so we can focus on what's special about Mojo."

This sentence can be found in the HelloMojo.ipynb file in the Jupyter notebook:
https://playground.modular.com/user/pmorgan@deeplp.com/lab/tree/HelloMojo.ipynb?

### Anything else?

Should be easy to fix.

**Comment by scottamain** [comment]
Thank you. Fixed for the next update.
