### ISSUE TITLE
[stdlib] Add missing comparison operator tests

### ISSUE THREAD

**Issue by laszlokindrat** [modularml/mojo#3145]
The following types are missing tests for the operators required by the `Comparable` trait (`__le__`, `__ge__`, etc.): 

- [x] `Int`: done in https://github.com/modularml/mojo/pull/3161
- [x] `IntLiteral`: done in https://github.com/modularml/mojo/pull/3214
- [x] `FloatLiteral`: done in https://github.com/modularml/mojo/pull/3216
- [x] `SIMD`: done in https://github.com/modularml/mojo/pull/3221

We should also ensure they have tests for `__eq__` and `__ne__`. Keep in mind that dunder methods should be tested directly (i.e. not through operator syntax sugar) for these basic numeric types to avoid unintended implicit conversions.:

**Comment by vguerra** [comment]
hello @laszlokindrat , just wanted to let you know that I pushed a couple of PRs to address the tasks in this issue: #3214 , #3216 and #3221

**Comment by laszlokindrat** [comment]
This is now complete thanks to @MatveyF, @vguerra, and @martinvuyk! 🎉

**Comment by martinvuyk** [comment]
I actually had nothing to do with this lol, just pushed a commit that referenced this during a rebase. Anyhow great work :D
