### ISSUE TITLE
[mojo-stdlib] Implicit conversions between SIMD values can lose data

### ISSUE THREAD

**Issue by lattner** [modularml/mojo#3149]
### Bug description

[Santiago](https://x.com/svpino) (@svpino) points out [on twitter](https://x.com/svpino/status/1807141992222363897)  that Mojo accepts code like this: `var b : Int64 = 1.67` even though we don't like implicit conversions that lose data.

I assume this is because we haven't adopted conditional conformances for the right initializers, is this possible to do now?

**Comment by msaelices** [comment]
Could I work on this?

**Comment by soraros** [comment]
Duplicate of #3065?
