### ISSUE TITLE
[Feature Request] Rename `countl_zero` / `countr_zero` to `count_leading_zeros` / `count_trailing_zeros`

### ISSUE THREAD

**Issue by Julian-J-S** [modularml/mojo#3158]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Not sure if you are open for Feedback/PRs on this (yet) but according to the contributing guide this might fall under "Code readability improvement" or "Conformity to style improvement"

### Suggestion
Rename
- `countl_zero` -> `count_leading_zeros`
- `countr_zero`-> `count_trailing_zeros`

### What is your motivation for this change?

Good, concise naming in a programming language can really benefit all developers in terms of efficiency/productivity and overall experience and should not be underestimated.

### Current "Problem" of `countl_zero` / `countr_zero`
- hard to read; not easy to understand; unclear;
- why change leading/trailing (as in the doctoring) to l/r? Those can be different things based on the direction 
- Why "zero" (singular) instead of "zeros" (plural) which is in `bit.rotate_bits_left`
- not aligned with other, clear, good(!) naming like `is_power_of_two` 👍  `rotate_bits_left` 👍

**Comment by JoeLoser** [comment]
Thanks for filing this!  Originally, we chose these names as inspired from C++ when we were splitting things internally when forming the `bit` module which is new.  We discussed these new names in our team's design meeting today and are +1 for the more verbose method names.

**Comment by gryznar** [comment]
@JoeLoser As of renaming, how about: https://github.com/modularml/mojo/issues/457? Separate word would greatly increase readability there
