### ISSUE TITLE
[BUG] [stdlib] [SIMD] Inconsistent int casting

### ISSUE THREAD

**Issue by martinvuyk** [modularml/mojo#3167]
### Bug description

```mojo
fn main() raises:
    var n1: Int = 255
    var n2: UInt8 = 255
    print(n1 - n2)
    print(int(n1 - n2))
    print(n1 - int(n2))
```
output:
```mojo
0
0
256
```

### Steps to reproduce

I think it makes more sense to assume `int(UIntX)` means positive value, and also when doing `UIntX.cast[DType.intX]()`. Since for example:
```mojo
fn main() raises:
    var n: UInt8 = 255
    print(int(n))
    print(n.cast[DType.int64]())
    print(n.cast[DType.int32]())
    print(n.cast[DType.int16]())
    print(n.cast[DType.int8]())
```
output:
```mojo
-1
255
255
255
-1
```
only in the case of `UInt8 -> Int8` does it really make sense to say it has to be negative since it overflows

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by DWSimmons** [comment]
https://github.com/modularml/mojo/issues/3065
https://github.com/modularml/mojo/issues/3146

Not sure why in 3146 there is a cast at all - which is the real bug for that - but the bug presents itself there too

**Comment by martinvuyk** [comment]
thanks a lot for pointing me to the issue #3065 seems like this is a dup of that

> Not sure why in 3146 there is a cast at all - which is the real bug for that - but the bug presents itself there too

yeah there are several things going on with SIMD atm. that are weirdly implicit and unexpected
