### ISSUE TITLE
[BUG] `atol` fails to parse strings with leading underscores in prefixed integers

### ISSUE THREAD

**Issue by jjvraw** [modularml/mojo#3182]
### Bug description

Actually picked up by @martinvuyk during review for #3178.

`atol` fails to parse prefixed integer literals with leading underscores. This should not be the expected behaviour, see below, taken from Python's docs on [Integer Literals](https://docs.python.org/3/reference/lexical_analysis.html#integers)

```
integer      ::=  decinteger | bininteger | octinteger | hexinteger
decinteger   ::=  nonzerodigit (["_"] digit)* | "0"+ (["_"] "0")*
bininteger   ::=  "0" ("b" | "B") (["_"] bindigit)+
octinteger   ::=  "0" ("o" | "O") (["_"] octdigit)+
hexinteger   ::=  "0" ("x" | "X") (["_"] hexdigit)+
nonzerodigit ::=  "1"..."9"
digit        ::=  "0"..."9"
bindigit     ::=  "0" | "1"
octdigit     ::=  "0"..."7"
hexdigit     ::=  digit | "a"..."f" | "A"..."F"
```

This issue is resolved in #3180.

### Steps to reproduce

```mojo
1> print(atol('0x_ff', 0))
  2.
Error: String is not convertible to integer with base 0: '0x_ff'
[User] Unhandled exception caught during execution
```

### System information

```shell
- MacOS Sonoma
- mojo 2024.7.505 
- mmodular 0.8.0
```

**Comment by bgreni** [comment]
While it's reasonable that `atol` should be tolerant to that format, this actually isn't a deviation from the behaviour in Python when converting a string to an int.

```
>>> int("0x_ff")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '0x_ff'
```

**Comment by jjvraw** [comment]
Hi! I should edit the issue description for clarify.

While it's true that Python's `int()` function doesn't accept "0x_ff" with the default base (10), it does handle prefixed integer literals with leading underscores when the appropriate base is specified or inferred (base 0). Here are some examples:

```python
>>> int("0x_16", base=0)  # Base 0 allows prefix detection
22
>>> int("0x_16", base=16)  # Explicit base 16
22
>>> int("0b_1010", base=0)  # Binary with base 0
10
>>> int("0o_17", base=0)  # Octal with base 0
15
