### ISSUE TITLE
[Docs] Declare positive and negative convention in Round docs args

### ISSUE THREAD

**Issue by DWSimmons** [modularml/mojo#3183]
### Where is the problem?

https://github.com/modularml/mojo/blob/47ff10b3077e1b70ee9f83444bd7f5a34e96c6f0/stdlib/src/builtin/math.mojo#L423

### What can we do better?

Positive ndigits arg are  rounded two digits to the right of the decimal (as in convention in other Python libraries) as the code suggests and performs...
round(1.2345, 2) # returns 1.23

Additionally, 
Negative ndigits arg are counted from the decimal to the left
round(12345, -2) # returns 12000

I suggest adding a simple line that makes that explicit.
[Current] "ndigits: The number of digits to round to."
[ADD] Positive to the right of the decimal, negative to the left.

**Comment by JoeLoser** [comment]
Clarifying this in the API docs would be great.  Thanks for filing the issue.  Feel free to submit a PR!

**Comment by pythoncrazy** [comment]
Given that this was solved in [this pull request](https://github.com/modularml/mojo/pull/3352), I think that this issue should be closed as completed.
