### ISSUE TITLE
[Feature Request] Constructor from `IntLiteral` and `FloatLiteral` -> `StringLiteral` for better `constrained[]()` error messages

### ISSUE THREAD

**Issue by martinvuyk** [modularml/mojo#3209]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

As title. I tried but this needs some MLIR black magic.

### What is your motivation for this change?

Many functions can have better error messages in their constrained failure

**Comment by JoeLoser** [comment]
Are you asking for the `msg` argument to `constrained` allowed to be specified an `IntLiteral` or `FloatLiteral` instead of just `StringLiteral`?

**Comment by martinvuyk** [comment]
Nope, rather to be able to concatenate compile time values to `StringLiteral` for better messages. A start would be `IntLiteral` and `FloatLiteral`, but since many constraints also take in `Int` for the condition for example, it would be cool if it's possible to concatenate that to a `StringLiteral` for a more explicit error message e.g. `constrained[num < 255, "This method can only be used for numbers bellow 255, given value was: " + num]`. If we could make compile time `String` fold into `StringLiteral` it would also fix this by `...given value was: " + str(num)` or if we could make constrained take in `String`.
