### ISSUE TITLE
[BUG] Can't form alias to `Int`'s dunder methods

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#3213]
### Bug description

As title. It's odd since most other types work.

### Steps to reproduce

```mojo
fn main():
	alias le = Int.__le__  # error: cannot form a reference to overloaded declaration of '__le__'
```

### System information

```shell
Mojo 2024.7.1022 (1e94b6a0)
```

**Comment by Mogball** [comment]
> ```
> cannot form a reference to overloaded declaration of '__le__'
> ```

This is intended behaviour. The real question is whether this method should be overloaded.

**Comment by Mogball** [comment]
Will defer to @joe

**Comment by soraros** [comment]
> This is intended behaviour. The real question is whether this method should be overloaded.

That's the thing: it's not overloaded.

**Comment by Mogball** [comment]
Ah, then this is indeed a bug

**Comment by soraros** [comment]
It also happens to `Bool`, but for instance not to `SIMD`.

**Comment by soraros** [comment]
The problem seems to be that `@register_passable` doesn't work well with trait explicit bound (`EqualityComparable` in this case). If either is removed, the problem goes away.
```mojo
fn main():
    Int.__eq__


@register_passable
struct Int(EqualityComparable):
    fn __eq__(self, rhs: Self) -> Bool:
        return False

    fn __ne__(self, rhs: Self) -> Bool:
        return False
```

**Comment by soraros** [comment]
Doesn't reproduce on `mojo 24.6.0.dev2024113005`.
