### ISSUE TITLE
[BUG] UnsafePointer inside function gets freed too early depending on branch (lifetime issue, eager destruction)

### ISSUE THREAD

**Issue by martinvuyk** [modularml/mojo#3226]
### Bug description

This seems like it has something to do with branching and the compiler not seeing a discard which is impossible to signal on a function return other than storing in a variable and then discarding before returning the variable. Couldn't this be fixed with codegen if the pointer is passed as an argument to another function to at least wait for the end of the scope of that function by adding the variable declaration and discard? This is super unintuitive behavior
```mojo
from memory import memcmp


fn func(n2: UnsafePointer[UInt8]) -> (Bool, Int):
    var n1 = List[UInt8](0x30, 0x30)
    return memcmp(n1.unsafe_ptr(), n2, 2) == 0, 1


fn main() raises:
    var asd = List[UInt8](0x30, 0x30)
    var res = func(asd.unsafe_ptr())
    print(res[0], res[1])
    _ = asd
```
output:
```text
False 1
```
this doesn't work either (outputs `False 0`)
```mojo
fn func(n2: UnsafePointer[UInt8]) -> (Bool, Int):
    var n1 = List[UInt8](0x30, 0x30)
    if memcmp(n1.unsafe_ptr(), n2, 2) == 0:
        return True, 1
    return False, 0
```
only works with explicit discard  (outputs `True 1`)
```mojo
fn func(n2: UnsafePointer[UInt8], other_condition: Bool = True) -> (Bool, Int):
    var n1 = List[UInt8](0x30, 0x30)
    if memcmp(n1.unsafe_ptr(), n2, 2) == 0 and other_condition:
        return True, 1
    _ = n1
    return False, 0
```
but if i bring the memcmp inside the if it doesn't (outputs `False 1`)
```mojo
fn func(n2: UnsafePointer[UInt8], other_condition: Bool = True) -> (Bool, Int):
    var n1 = List[UInt8](0x30, 0x30)
    if other_condition:
        return memcmp(n1.unsafe_ptr(), n2, 2) == 0, 1
    _ = n1
    return False, 0
```

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
`mojo 2024.7.1114`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by Mogball** [comment]
```mojo
fn func(n2: UnsafePointer[UInt8]) -> (Bool, Int):
    var n1 = List[UInt8](0x30, 0x30)
    return memcmp(n1.unsafe_ptr(), n2, 2) == 0, 1
```

This is the same as writing


```mojo
fn func(n2: UnsafePointer[UInt8]) -> (Bool, Int):
    var n1 = List[UInt8](0x30, 0x30)
    var ptr = n1.unsafe_ptr() # last use of `n1`
    # `n1` is destructed
    return memcmp(ptr, n2, 2) == 0, 1 # use of dangling pointer
```

**Comment by Mogball** [comment]
We should stop exposing unsafe pointers so easily in these APIs. It's a massive footgun. cc @JoeLoser

**Comment by martinvuyk** [comment]
> We should stop exposing unsafe pointers so easily in these APIs

This code was for the stdlib internals (specifically in PR #3223) and it took me quite some time to find the bug.

>```mojo
>fn func(n2: UnsafePointer[UInt8]) -> (Bool, Int):
>    var n1 = List[UInt8](0x30, 0x30)
>    return memcmp(n1.unsafe_ptr(), n2, 2) == 0, 1
>```
>This is the same as writing
>
>```mojo
>fn func(n2: UnsafePointer[UInt8]) -> (Bool, Int):
>    var n1 = List[UInt8](0x30, 0x30)
>    var ptr = n1.unsafe_ptr() # last use of `n1`
>    # `n1` is destructed
>    return memcmp(ptr, n2, 2) == 0, 1 # use of dangling pointer
>```

To me that is the problem, the "last use" when something is passed as an argument to a function is the scope of that other function, it shouldn't be destroyed that eagerly IMO. That is what i meant by solving it by first storing the result of the function call in an intermediate variable before explicitly discarding the owner and sending back the result. Or at least explain this thoroughly when talking about lifetimes and eager destruction.

The second problem that wasn't addressed is the thing with the branching not seeing the explicit discard:

but if i bring the memcmp inside the if it doesn't (outputs `False 1`)
```mojo
fn func(n2: UnsafePointer[UInt8], other_condition: Bool = True) -> (Bool, Int):
    var n1 = List[UInt8](0x30, 0x30)
    if other_condition:
        return memcmp(n1.unsafe_ptr(), n2, 2) == 0, 1
    _ = n1
    return False, 0
```
To me this seems like a potential footgun since it is very unique about this language.

**Comment by Mogball** [comment]
The actual problem is with the `unsafe_ptr` function. That function is the footgun

**Comment by martinvuyk** [comment]
> The actual problem is with the unsafe_ptr function. That function is the footgun

yes you're right it's dangerous, but unsafe operations will always be needed at some point. And eager destruction of a variable seems like a potential footgun when doing said unsafe ops.

Is there no way to make the return of a function extend the lifetime of the object ? That would solve this problem entirely. 

Another way is to introduce a mechanism to "keepalive" (`del` keyword ?) some variables until that line (make them not eagerly destroyable) regardless of branch. Or potentially until the end of the scope of the entire function.

Python has the `del` keyword which manual discard is analogous to, my problem here with the branching for example is that if I signal that something be destroyed at line x in my code, I don't expect the compiler to get clever on me because in that branch the owner was not destroyed after pointer usage.

I'm being a bit insistent because I think any C or C++ dev that gets to use these eagerly freed pointers will also be confused.

**Comment by Mogball** [comment]
It's easy. We remove the `unsafe_ptr` function and instead add a `data()` function that returns a reference to the inner data, properly tracked with lifetimes. `UnsafePointer` doesn't have a lifetime 🤷
