### ISSUE TITLE
[Modular CLI] modular update mojo ends up in a segmentation fault

### ISSUE THREAD

**Issue by tamas-viola** [modularml/mojo#3245]
### Issue description

loc("#M.target<triple = \22x86_64-unknown-linux\22, cpu = \22westmere\22, features = \22+64bit,+aes,+cmov,+crc32,+cx16,+cx8,+fxsr,+mmx,+pclmul,+popcnt,+sahf,+sse,+sse2,+sse3,+sse4.1,+sse4.2,+ssse3,+x87\22, data_layout = \22e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128\22, simd_bit_width = 128>":1:50): error: duplicate or unknown struct parameter name: cpu
Please submit a bug report to https://github.com/modularml/max/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.      Program arguments: modular update mojo
[143141:143142:20240714,151752.952538:ERROR directory_reader_posix.cc:42] opendir /home/tviola/.modular/crashdb/attachments/2dbdcc47-62f3-45ce-bc33-cf4a70967cb7: No such file or directory (2)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  modular   0x000055aeb14a8327
1  modular   0x000055aeb14a5fde
2  modular   0x000055aeb14a89af
3  libc.so.6 0x00007f83d7058580
4  modular   0x000055aeb18cadd4
5  modular   0x000055aeb18ca54c
6  modular   0x000055aeb18bad8f
7  modular   0x000055aeb18b9c78
8  modular   0x000055aeb13fe038
9  modular   0x000055aeb13f36ba
10 libc.so.6 0x00007f83d7042c8a
11 libc.so.6 0x00007f83d7042d45 __libc_start_main + 133
12 modular   0x000055aeb13f2e2e
installer crashed!
Please file a bug report.
zsh: segmentation fault  modular update mojo

### Steps to reproduce

modular update mojo

### Version Info

```shell
modular 0.8.0 (39a426b5)

Linux vtpad 6.6.9-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.6.9-1kali1 (2024-01-08) x86_64 GNU/Linux
```

**Comment by Sharktheone** [comment]
Does your CPU have AVX2 support? I don't know if that is the problem here, but Mojo needs support for it.
