### ISSUE TITLE
[Docs] Update Tensor docs

### ISSUE THREAD

**Issue by FireBirdJZ** [modularml/mojo#3255]
### Where is the problem?

https://docs.modular.com/mojo/stdlib/tensor/tensor/

### What can we do better?

In the example code for RGB to grayscale:
`var image = Tensor.rand[DType.float32](TensorShape(height, width, channels))` 

should become: `var image = Tensor[DType.float32].rand((TensorShape(height, width, channels)))`

Or you will get an error such as: _invalid call to 'rand': could not deduce parameter 'type' of parent struct 'Tensor'_

**Comment by arthurevans** [comment]
Tensor is now under MAX. This error has been corrected. https://docs.modular.com/max/api/mojo/tensor/tensor/Tensor
