### ISSUE TITLE
[stdlib] Allow `!r` in `String.format`

### ISSUE THREAD

**Issue by JoeLoser** [modularml/mojo#3267]
Allow "{!r}".format(x), which is equivalent to `repr(x)` rather than `str(x)`.  See https://dev.to/behainguyen/python-the-r-string-format-and-the-repr-and-str-methods-29i7 for more info.

**Comment by jjvraw** [comment]
Hi :) Had a quick look into this. 

Unsure of how we can allow both `{!s}` (inferred by `{}`) and `{!r}` without tightening the restrictions on the parameters of `format`, unless this is okay?

A potential solution could be to introduce a new trait, `StringRepresentable`, that inherits from both `Stringable` and `Representable`?

It would be neat to insert, where appropriate, the following into `format`:
```mojo
if i == e[].field[Int]:
    if e[].format_specifier == "r":
        res += repr(args[i])
    else:
        res += str(args[i])
```

It follows we would need to introduce this new field, `format_specifier`, to  `_FormatCurlyEntry` and adjust the logic in `_FormatCurlyEntry.make_entries`. 

In comparison to the [`Formatter`](https://github.com/modularml/mojo/blob/8bd1dbdf26c70c634768bfd4c014537f6fdb0fb2/stdlib/src/utils/_format.mojo#L24) trait this would approach would still align more closely with Python's use of dunder methods? 

If this seems like the right direction, I'm happy to continue working on a PR. If not, also happy to consider a different approach.

On another note, if we look at the [Format String Syntax](https://docs.python.org/3/library/string.html#format-string-syntax) from the Python docs,
```
replacement_field ::=  "{" [field_name] ["!" conversion] [":" format_spec] "}"
field_name        ::=  arg_name ("." attribute_name | "[" element_index "]")*
arg_name          ::=  [identifier | digit+]
attribute_name    ::=  identifier
element_index     ::=  digit+ | index_string
index_string      ::=  <any source character except "]"> +
conversion        ::=  "r" | "s" | "a"
format_spec       ::=  <see Python docs for details>
```

, it's worth mentioning that the current `format` implementation also omits the `!a` conversion.

**Comment by JoeLoser** [comment]
Fixed in https://github.com/modularml/mojo/pull/3279, thank you for the contribution!
