### ISSUE TITLE
[Feature Request] FreeBSD ports collection

### ISSUE THREAD

**Issue by syleishere** [modularml/mojo#3288]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Add ports package to FreeBSD for users wanting to play with mojo.

### What is your motivation for this change?

Many people have switched from Linux/kvm to FreeBSD/bhyve for host OS ever since demise of Centos. Would be nice to have support here.

### Any other details?

For TCP sockets FreeBSD uses kqueue instead of epoll, perhaps a 3rd party library using libev or libevent may be able to combine the two, or just separate implementations.

**Comment by martinvuyk** [comment]
Hi, sorry to be a bummer but realistically FreeBSD is not on the priority list. Currently very many efforts are going into adding support for Windows and better Python and eventually (nex year) C interop. 

> For TCP sockets FreeBSD uses kqueue instead of epoll

I'm currently trying to implement sync  TCP (others have already done it, I'm just adapting code), but trying to setup an async API to eventually implement kqueue for freeBSD and other BSD family (+ Apple) and maybe io_uring for linux ([there is someone implementing it in Mojo](https://github.com/dmitry-salin/io_uring)), and IOCP for windows. 

If you are interested, here is the [link to the discussion I opened](https://github.com/modularml/mojo/discussions/2746) and [where I'm trying to get the thing to work](https://github.com/martinvuyk/forge-tools/tree/main/src/forge_tools/socket). If you're only interested in building your own FFI you still might be interested in looking at [this file](https://github.com/martinvuyk/forge-tools/blob/main/src/forge_tools/ffi/c.mojo) where I adapted some old code to work (w/ latest nightly) for calling some libc funcs.

You can also use the online notebooks, though I've never used them. Ask around in the discord server if you need any help :)

**Comment by haikyuu** [comment]
Since macos has been shipped, any news on this?
