### ISSUE TITLE
[BUG]Mojo doesnt recognise main function

### ISSUE THREAD

**Issue by BenChanlLOL** [modularml/mojo#3292]
### Bug description

I have simple code:
```
fn main():
    var A: Int8 = 5
    print(A)

```
but when I try to compile or run I get:  "mojo: error: module does not define a main function"

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`

1> Ubuntu-WSL on windows
2> mojo 24.4.0 (59977802)
3> modular 0.8.0 (39a426b5
```

**Comment by gryznar** [comment]
Could you please provide block of code in \`\`\`?
````text
```mojo
# code block goes here
```
````
Current formatting is messed up

**Comment by gryznar** [comment]
Which version of WSL do you have? May be unrelated, but Mojo supports only WSL2. I have tried this code in playground and it works fine:
![image](https://github.com/user-attachments/assets/cca73170-0681-4773-b1b1-50f5a144052f)

Other possible debugging steps:
- provide commands used to compile / run and name of the file
- is content of file saved?

**Comment by gryznar** [comment]
You are welcome :) Task may be closed
