### ISSUE TITLE
[Docs] Mojo URL leads to 404

### ISSUE THREAD

**Issue by brandondrew** [modularml/mojo#3308]
### Where is the problem?

https://github.com/modularml/mojo

### What can we do better?

The URL displayed on GitHub for Mojo in the upper right is no longer valid.  Please replace this link with something better:

- https://docs.modular.com/mojo

**Comment by brandondrew** [comment]
Since I wasn't able to find an anchor, here's a screenshot to show what URL I'm referring to.

![location of the url](https://github.com/user-attachments/assets/074db440-dee2-4a80-8d41-801d795bb7b8)

**Comment by DWSimmons** [comment]
I suspect that this was part of the site refresh and that it hasn't made it to GitHub yet https://docs.modular.com/mojo/manual/

**Comment by jackos** [comment]
Fixed thanks for raising

**Comment by brandondrew** [comment]
> I suspect that this was part of the website refresh and that it hasn't made it to GitHub yet https://docs.modular.com/mojo/manual/

I suspect that most every web site "refresh" breaks links like this.
