### ISSUE TITLE
[BUG] Top level `var` segfaults when used from package

### ISSUE THREAD

**Issue by helehex** [modularml/mojo#3316]
### Bug description

There is a bug when using top-level `var: DLHandle` to link to a library from a packaged binary.
I've also reproduced a similar bug with just an `UnsafePointer` (see discussion)

Everything works fine when using the source code

But, if you use the packaged code, it segfaults.

The alternative approach would be to carry the library around in the code and keep track of it's lifetime. Doing that seems to work even with packaged code, but it's not very nice todo.

The example below uses sdl, because that's what I was trying to get working

### Steps to reproduce

[Link to repo showing an example with sdl](https://github.com/helehex/mojo-test/tree/main/top_level_var_bug)

### System information

```shell
Host Information
  ================

  Target Triple: x86_64-unknown-linux
  CPU: skylake
  CPU Features: adx, aes, avx, avx2, bmi, bmi2, clflushopt, cmov, crc32, cx16, cx8, f16c, fma, fsgsbase, fxsr, invpcid, lzcnt, mmx, movbe, pclmul, popcnt, prfchw, rdrnd, rdseed, sahf, sgx, sse, sse2, sse3, sse4.1, sse4.2, ssse3, x87, xsave, xsavec, xsaveopt, xsaves

mojo 2024.7.2605 (7b940338)

modular 0.8.0 (39a426b5)
```

**Comment by helehex** [comment]
I also tried using just a top level `String`, but I cant seem to get the same disparity between source and package.
I tried making sure it wasn't being optimized as a constant, but still not certain.

**Comment by helehex** [comment]
So for context, this will also break when used from a package, but works fine when used from source:

`/src/__init__.mojo`
```mojo
var _6 = 6
var top_level = UnsafePointer.address_of(_6)
```

`.../test_{src, pkg}.mojo`
```mojo
import src

def main():
    print(src.top_level[])
```

**Comment by Ryul0rd** [comment]
Found the issue. Functions need to be marked as `capturing` to use top level vars e.g.
```
var foo = 0

fn bar() capturing:
    foo += 1
    print(foo)
```
It's nothing `DLHandle` related. I still find it rather odd that this works fine when you run things as a script or when compiled but not when you package them. It's also problematic that you get a segfault upon trying to import a .mojopkg rather than upon trying to build the package.

**Comment by Ryul0rd** [comment]
Never mind, looks like `DLHandle` is part of the problem. That other part just makes things extra confusing.

**Comment by jackos** [comment]
Hi having a global `var` results in undefined behavior and is being removed, you have to pass around the DLHandle through arguments at the moment.
