### ISSUE TITLE
[Feature Request] Support for the equivalent csv package

### ISSUE THREAD

**Issue by msaelices** [modularml/mojo#3330]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Implement the Mojo equivalent to Python's [csv](https://docs.python.org/3/library/csv.html) module

### What is your motivation for this change?

I want Mojo's stdlib to match Python's one to attract Python programmers and ease migration.

**Comment by msaelices** [comment]
I would like to work on this.

**Comment by JoeLoser** [comment]
Thanks for the issue and excitement to work on this!  Before getting too far, I think we should have a discussion of whether we'd like the csv library to be part of the standard [library](https://docs.python.org/3/library/csv.html) (like it is in Python) or a stand-alone, separate library like in [Rust](https://docs.rs/csv/latest/csv/#).

In general, I see there's a lot of interest in leaning into building Mojo-equivalent of popular Python packages.  I think this is great, but we also want to be mindful that we're starting to lean in more with Python bindings to not *require* this sort of wholesale approach of using Mojo.  We'll share more details on that soon, but this will help posit the standard library's positioning on module evolution compared to the Python ecosystem.
