### ISSUE TITLE
[BUG]  [Mojo][error] Mojo SDK post-install test "`mojo repl`" failed

### ISSUE THREAD

**Issue by Tanya032002** [modularml/mojo#3332]
### Bug description

Hii , 

I am facing this issue while installing Mojo on my windows system, I was following the modular docs and have already installed WSL , i was installing this on ubuntu .

![image](https://github.com/user-attachments/assets/49113473-1915-43c3-ad4b-0e89f1b3c1e1)

Although the mojo is being installed there are some broken dependencies which is causing the issue. I am getting an issue.

![image](https://github.com/user-attachments/assets/13fe2cff-4920-480b-9e26-9ab8b69da4ff)

### Steps to reproduce

- modular install mojo

### System information

```shell
- What OS did you do install Mojo on ?  : Windows 11 on WSL ubuntu 22.04
- `mojo version` = mojo 24.4.0 (2cb57382)
- `modular -v`  = modular 0.9.1 (3460d12e)
```

**Comment by smuniraj2018** [comment]
Are you using WSL 1 or 2? We have seen issues with WSL1 in the past.
