### ISSUE TITLE
[Feature Request] no-mangle decorator

### ISSUE THREAD

**Issue by david-ragazzi** [modularml/mojo#3339]
### Review Mojo's priorities

- [x] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

A decorator to disable the obfuscation of a function name (@no-mangle, or another name), so that a boot binary written in assembly calls the main kernel function (k_main, for example) by the original name that was written.

### What is your motivation for this change?

Create a tiny operating system in Mojo as described [here](https://github.com/modularml/mojo/discussions/3334).

**Comment by Mogball** [comment]
`@export` does what you want

**Comment by david-ragazzi** [comment]
No matter the name. The important is the function name doesn't change in order to linked objets call by the unchanged original name. Do you understand?

**Comment by Mogball** [comment]
I do understand. `@export` does exactly what you want here!

**Comment by david-ragazzi** [comment]
> I do understand. `@export` does exactly what you want here!

Ok. Are you working on this? Where I can follow?

**Comment by Mogball** [comment]
It exists already
