### ISSUE TITLE
[Modular CLI] cannot create account with gmail ?

### ISSUE THREAD

**Issue by liuzhishan** [modularml/mojo#3346]
### Issue description

I cannot create account or run `modular auth` with gmail. Is gmail not supported ? Which email should I use ?

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### Version Info

- Provide Modular CLI version by pasting the output of `modular -v`
```
modular 0.9.1 (3460d12e)
```
 
- What OS did you install modular CLI on ? The os is ubuntu, `modular host-info` result is as follows:

```Host Information
  ================

  Target Triple: x86_64-unknown-linux
  CPU: cascadelake
  CPU Features: adx, aes, avx, avx2, avx512bw, avx512cd, avx512dq, avx512f, avx512vl, avx512vnni, bmi, bmi2, clflushopt, clwb, cmov, crc32, cx16, cx8, evex512, f16c, fma, fsgsbase, fxsr, invpcid, lzcnt, mmx, movbe, pclmul, pku, popcnt, prfchw, rdrnd, rdseed, sahf, sse, sse2, sse3, sse4.1, sse4.2, ssse3, x87, xsave, xsavec, xsaveopt, xsaves
```

**Comment by liuzhishan** [comment]
It worked now. I forgot that I registered before, so create account reported error. I click sign in and it login successfully.
Thanks for help!

**Comment by inzk** [comment]
يتم الاصلاح

**Comment by ematejska** [comment]
Thanks.  Closing this out.
