### ISSUE TITLE
[Feature Request] Align Mojo `alias` with `type`

### ISSUE THREAD

**Issue by redradist** [modularml/mojo#3367]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

In Python 3.12, there is a new use of `type` keyword, [Type Aliases](https://docs.python.org/3/library/typing.html#type-aliases).
I suggest to align `alias` keyword with `type` in favor of `type` in Python

### What is your motivation for this change?

Make better interchangeable between Python and Mojo code

**Comment by martinvuyk** [comment]
The problem is that this would conflict with `alias` being used to setup compile time constants as well, not just types.

**Comment by Mogball** [comment]
`alias` is the more general names of the two. It could be confusing, for example, to write `type g = 123` (even though Python allows using ints as types, linters aside)
