### ISSUE TITLE
[BUG] mojo test: couldn't build the test executable in current nightlies

### ISSUE THREAD

**Issue by sbrunk** [modularml/mojo#3371]
### Bug description

The test runner seems broken as of at least `2024.8.705`

```shell
mojo test test_quickstart.mojo
/var/folders/51/qlrdpg3d5l57rtmtk6qmvg9w0000gn/T/test-7e076b.mojo:6:24: error: use of unknown declaration 'test_inc_one()'
    `test_quickstart`.`test_inc_one()`()
                       ^~~~~~~~~~~~
/Users/brunksn/.modular/pkg/packages.modular.com_nightly_mojo/bin/mojo: error: failed to parse the provided Mojo source module
mojo: error: couldn't build the test executable. Exit code 1
```

### Steps to reproduce

Run `mojo test` with a recent nighly version like `2024.8.705` or newer.

Error from this test code but it seems to error on any test.

```mojo
from testing import assert_equal

def inc(n: Int) -> Int:
    return n + 1

def test_inc_one():
    assert_equal(inc(1), 2)
```

### System information

`macOS 14.5`
`mojo 2024.8.905 (c7900bf8)`
`modular 0.9.1 (3460d12e)`

**Comment by ematejska** [comment]
This should be fixed now in the nightlies.

**Comment by sbrunk** [comment]
Yes I can confirm it's working again with the current nightly. Thanks!

**Comment by walter-erquinigo** [comment]
Awesome!
