### ISSUE TITLE
[Modular CLI] Running `modular auth` fails with the error message: http error: response code 404

### ISSUE THREAD

**Issue by peymanbr** [modularml/mojo#3380]
### Issue description

I'm following the steps described in https://github.com/peymanbr/mojo/blob/main/CONTRIBUTING.md to build the nightly Mojo compiler after cloning my Mojo fork. Running `modular auth` fails in the below step:
```
curl https://get.modular.com | sh -
modular auth
modular install nightly/mojo
```
The error is: `modular: error: http error: response code 404`

The `.modular` dir was created in `$HOME`, and it contains the private and public keys, but it lacks the `modular.cfg` file.

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.9.1 (3460d12e)
- What OS did you install modular CLI on ?
Ubuntu 2022.04 running on x86_64 CPU
```

**Comment by jackos** [comment]
Hi @peymanbr this should be working now, please let me know if not and we'll reopen
