### ISSUE TITLE
[Feature Request] Inline assembly support

### ISSUE THREAD

**Issue by david-ragazzi** [modularml/mojo#3385]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities. 

### What is your request?

A built function for write inline assembly similar to `asm` in C/Rust. To write device drivers, for example, it's necessary read/write hardware ports, thus inline assembly is essential in a system language.

In C we have:

```
unsigned char port_byte_in(uint16_t port) {
    unsigned char result;
    asm("in %%dx, %%al" : "=a" (result) : "d" (port));
    return result;
}
```

And in Rust we have:

```
fn port_byte_in(port: u16) -> u8 {
    let result: u8;
    unsafe {
        asm!("in al, dx", out("al") result, in("dx") port);
    }
    result
}
```

```
fn cpu_id() {
  asm!(
      "cpuid",
      out("eax") eax,
      out("ebx") ebx,
      out("ecx") ecx,
      out("edx") edx,
      options(nomem, nostack)
  );
  ...
}
```

In mojo, to be more pythonic, it could be:

```
fn port_byte_in(port: UInt16) -> UInt8:
    var result: UInt8
    asm("in al, dx", input={"dx": port}, output={"al": result})
    return result
```

```
fn port_byte_out(port: UInt16, value: UInt8):
    asm("out dx, al", input={"dx": port, "al": value})
```

```
fn cpu_id():
  asm("cpuid",
      output={"eax": eax, "ebx": ebx, "ecx": ecx, "edx": edx},
      options=["nomem", "nostack"])
  ...
```

### What is your motivation for this change?

Create a tiny operating system in Mojo as described https://github.com/modularml/mojo/discussions/3334.
But developers that write other embbeded systems also will need if want code them in mojo.

**Comment by jjvraw** [comment]
Just to clarify, I believe inline assembly is already supported, despite the lack of documentation. Is your request regarding the calling convention?

**Comment by david-ragazzi** [comment]
My request is for the suport itself and the convention (as I think is pythonic, ie. easier to read).

So how I can call inline assembly in Mojo?

**Comment by soraros** [comment]
You can use `inlined_assembly` from the `sys.intrinsics` module, with examples in the stdlib.

**Comment by Mogball** [comment]
This already exists

**Comment by david-ragazzi** [comment]
Ok, thanks.

I find this:

https://github.com/modularml/mojo/blob/main/stdlib%2Fsrc%2Fsys%2F_assembly.mojo

And only this example:

https://github.com/modularml/mojo/blob/main/stdlib%2Fsrc%2Futils%2Fnumerics.mojo

It would be great this documented with more examples.. :-/

**Comment by david-ragazzi** [comment]
Well.. While it is not documented, I will post some examples that I tested in order to help anyone who arrives here with the same questions about how to use `inlined_assembly`. I hope I helped!

Here we go:

```
from sys._assembly import inlined_assembly


fn main():

    # To understand constraints:
    #
    # Look this:
    #    constraints="=l,l,l",
    #
    # This means:
    #    =l: outputs a integer
    #    l: arg0 must be a integer
    #    l: arg1 must be a integer
    #
    # Beyond 'l' we have:
    #    f: float32
    #    h: float16
    #    r: register
    #
    # From I understood, 'r' assumes the type of result type. Thus if the result type of the operation
    # is Int16, then 'r' will be interpreted as 'l'


    # Example with NO operand and NO result: Put the CPU in a wait state until an interrupt occurs

    inlined_assembly[
        "hlt",  # Put the CPU in a wait state
        NoneType,  # No result will be returned
        constraints="",
        has_side_effect=False,
    ]()


    # Example with ONE operand: Increment a integer of 16 bits

    var num: Int16 = 10
    var ret = inlined_assembly[
        "inc $0",  # Increment 10 at 1
        Int16,  # The result will be a integer of 16 bits
        constraints="=r,r",
        has_side_effect=False,
    ](num)
    print(ret)  # Outputs 11


    # Example #2 with TWO operands: Sum two integers of 32 bits

    var num1: Int32 = 4
    var num2: Int32 = 15
    var ret2 = inlined_assembly[
        "add $2, $1",  # Sum 11 + 4
        Int32,  # The result will be a integer of 32 bits
        constraints="=l,l,l",  # Or just: =r, r, r
        has_side_effect=False,
    ](num1, num2)
    print(ret2)  # Outputs 19
```

PS: Please correct me if I made a mistake. Thanks!
