### ISSUE TITLE
pi constant is not available in from module math as docs claim

### ISSUE THREAD

**Issue by antonl321** [modularml/mojo#3399]
### Bug description

I cannot get the constant pi from math module with
from math import pi 
although the docs claim that it should work
https://docs.modular.com/mojo/stdlib/math/constants/

### Steps to reproduce

syla@syla-laptop:~/Apps/mojo/tests$ mojo --version
mojo 24.4.0 (59977802)
syla@syla-laptop:~/Apps/mojo/tests$ cat consts.mojo
from math import atan,pi

fn main():
    #alias pi=3.14159
    print("pi is ",pi, 4.0*atan(1.0))
syla@syla-laptop:~/Apps/mojo/tests$ mojo consts.mojo
/home/syla/Apps/mojo/tests/consts.mojo:1:23: error: package 'math' does not contain 'pi'
from math import atan,pi

### System information

```shell
- What OS did you do install Mojo on ?
wsl
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 24.4.0 (59977802)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.9.1 (3460d12e)
```

**Comment by DWSimmons** [comment]
I can verify that main (24.4) does not have pi import available.  I have no idea why it shows up in mojo standard lib docs.

I know this doesn't help you right now though it was introduced into the nightly stream Jun. 20th. [068e9dd6e4bc755f9c9e800d35b85fa13941f646]

```python
  1> from math import atan, pi 
  2. print(pi) 
  3.  
3.1415926535897931
  3> print("pi is ",pi, 4.0*atan(1.0)) 
  4.  
pi is  3.1415926535897931 3.1415926535897931
  4> :quit
Process 24799 exited with status = 9 (0x00000009) killed
darin@home:~$ mojo -v
mojo 2024.8.105 (1fa11138)
```
