### ISSUE TITLE
Unable to Spawn Server

### ISSUE THREAD

**Issue by PeronGH** [modularml/mojo#34]
## Bug Description

I got the access to Mojo playground today, but when I logged in the playground and start my server, it says "Spawn failed
The latest attempt to start your server has failed. Would you like to retry starting it?". Clicking the "Relaunch Server" does not work.

### Steps to Reproduce

1.  Got access
2.  Log in playground
3. Got error

![image](https://user-images.githubusercontent.com/18367871/236594361-e8d15c7f-90eb-47d5-aea9-faea9d661988.png)

**Comment by cniessigma** [comment]
Hello! 

I'm going to take a look, while I investigate, by any chance does your email begin with a special character? There is a known issue with servers hitching on users with email addresses like that

**Comment by cniessigma** [comment]
Looking in the logs it seems like this is the case, assuming that this is you anyways.

Do you have a different email address I can use, by chance? This is a known issue but it's unlikely to have a timely fix, at the very least until our next release.

If you have an alternate email, please contact an Admin on Discord, like @goldiegadde, and we'll get that email swapped out for you :)

**Comment by cniessigma** [comment]
Alright I actually pushed the fix, you could try again with the same email if you'd like

**Comment by PeronGH** [comment]
This issue is resolved. Thanks.
