### ISSUE TITLE
[Feature Request] CURLY BRACES

### ISSUE THREAD

**Issue by AmeerArsala** [modularml/mojo#3402]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Please please please please pleaaaaaseeee let me use curly braces. It doesnt have to be baked in. Just an optional thing that I would love from the language. just some syntactic sugar

### What is your motivation for this change?

need it. this is my reason for living

### Any other details?

i am expecting a child soon (it's a boy). I will name it 'mojo' if you make this happen.

**Comment by Mogball** [comment]
Sorry
