### ISSUE TITLE
[BUG] Can't use SIMD data types as keys for Dicts

### ISSUE THREAD

**Issue by schtschenok** [modularml/mojo#3455]
### Bug description

Can't use SIMD data types (UInt8, Int16, etc.) as Dict keys despite that SIMD seems to fit KeyElement requirements.

### Steps to reproduce

```mojo
from collections import Dict

var map1 = Dict[Int, UInt8]()  # Works
var map2 = Dict[UInt8, UInt8]()  # Doesn't work
```

### System information

```shell
Ubuntu 22.04.4 LTS running in WSL on Windows 11 24H2
mojo 24.4.0 (59977802)
modular 0.9.2 (b3079bd5)
```

**Comment by jjvraw** [comment]
`SIMD`'s `__eq__`/`__ne__` methods returns a bool `SIMD` vector, which differs to the conformance of `EqualityComparable`, of which `KeyElement` inherits

**Comment by JoeLoser** [comment]
Yep, this is working as intended right now, even though it's unfortunate.  There's other tracking issues for making SIMD regular (so that its `eq` and `ne` would return a `Bool` and thus compose nicely).
