### ISSUE TITLE
[Modular CLI] 'No available targets are compatible with triple "aarch64-unknown-linux" on x86_64 system with Ryzen 9000

### ISSUE THREAD

**Issue by chriselrod** [modularml/mojo#3459]
### Issue description

On Arch Linux with a Ryzen 9000 CPU:
```
$ cat /proc/cpuinfo | head -n5
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 26
model		: 68
model name	: AMD Ryzen 9 9950X 16-Core Processor
```
I installed using `paru -Syu mojo-git`.

However, the modular cli failed to install mojo, with an error message relating to aarch64-unknown-linux.

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
```
$ modular install mojo
modular: error: could not construct host target info: No available targets are compatible with triple "aarch64-unknown-linux"

$ modular host-info
modular: error: could not construct host target info: No available targets are compatible with triple "aarch64-unknown-linux"
```
These look like they're misidentifying the host as aarch64 instead of x86_64.

I don't believe modular currently supports aarch64-unknown-linux, but if it did, perhaps it would have tried to install an incompatible aarch64 binary?

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`

$ modular -v
modular 0.9.2 (b3079bd5)
```

- What OS did you install modular CLI on ?
```
$ uname -a
Linux cachy9950xz5 6.10.8-2-cachyos #1 SMP PREEMPT_DYNAMIC Wed, 04 Sep 2024 13:59:35 +0000 x86_64 GNU/Linux
```
This is an Arch derivative. I was told to file a new issue here: https://github.com/modularml/mojo/issues/572#issuecomment-2336836320

Please let me know if there is any other information I can provide.

**Comment by chriselrod** [comment]
On another system with the same OS, I get roughly the expected result
```
$ modular host-info
  Host Information
  ================

  Target Triple: x86_64-unknown-linux
  CPU: tigerlake
  CPU Features: adx, aes, avx, avx2, avx512bitalg, avx512bw, avx512cd, avx512dq, avx512f, avx512ifma, avx512vbmi, avx512vbmi2, avx512vl, avx512vnni, avx512vp2intersect, avx512vpopcntdq, bmi, bmi2, clflushopt, clwb, cmov, crc32, cx16, cx8, evex512, f16c, fma, fsgsbase, fxsr, gfni, invpcid, kl, lzcnt, mmx, movbe, movdir64b, movdiri, pclmul, pku, popcnt, prfchw, rdpid, rdrnd, rdseed, sahf, sgx, sha, shstk, sse, sse2, sse3, sse4.1, sse4.2, ssse3, vaes, vpclmulqdq, widekl, x87, xsave, xsavec, xsaveopt, xsaves
```
CPU and target features are of course expected to differ.

**Comment by JoeLoser** [comment]
Given that the `modular` tool is deprecated in favor of `magic` tool now, I'm going to mark this as "Won't fix".
