### ISSUE TITLE
[BUG] Mojo is ~7000x slower than python to run `(str("hello world\n") * 10_000).split("\n")`

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [modularml/mojo#3460]
### Bug description

As the title says.

This performance bug is making it prohibitly expensive to benchmark the new `atof` on the common `canada.txt` ,see [comment](https://github.com/modularml/mojo/pull/3434#issuecomment-2325252746) because loading the text file and splitting it by lines takes more than 5 minutes on mojo while this is instant in Python. 

So it's blocking for some benchmarking work.

### Steps to reproduce

Here is the python script:

```python
from time import time_ns

def main():
    t1 = time_ns()
    lines = (str("hello world\n") * 10_000).split("\n")
    t2 = time_ns()

    print(len(lines))
    print("Time:", t2 - t1, "ns")

main()
```

The mojo script:

```mojo
from time import perf_counter_ns

def main():
    t1 = perf_counter_ns()
    lines = (str("hello world\n") * 10_000).split("\n")
    t2 = perf_counter_ns()

    print(len(lines))
    print("Time:", t2 - t1, "ns")
```

On my system, wsl2 windows 11, 

Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz

Base speed:	3,80 GHz
Sockets:	1
Cores:	8
Logical processors:	16
Virtualization:	Enabled
L1 cache:	512 KB
L2 cache:	2,0 MB
L3 cache:	16,0 MB

I get 326600ns for python and 2277131800 ns for Mojo.

### System information

```shell
ubuntu 22.04
max/mojo 24.6.0.dev2024090905
Pixi version: 0.27.1
```

**Comment by jjvraw** [comment]
Hi, seems like we ran into the same issue, as you pointed out. Noticed this when parsing a CSV, and the runtime between `splitlines` and `split` earlier this semester.  With the implementation in #3461, reading in and separating a dataset (13612 observations per 21 features)  delimited with `','` takes `0.012406`s compared to Python's  `0.022226`s, extracting `272,241` fields. Without exhaustive testing, this is actually a 1.7x speedup. The scripts shown below.

```python
def main():
    start_time = time.time_ns()
    with open("DataSet.csv", "r") as f:
        lines = f.read()
    
    temp = lines.split(',')
    
    end_time = time.time_ns()
    elapsed = (end_time - start_time) / 1e9
    
    print("Time:", elapsed, "seconds")
    print("Number of lines:", len(temp))
```

```mojo
fn main() raises:
    
    start_time = now()
    var lines: String
    with open("DataSet.csv", "r") as f:
        lines = f.read()

    var temp = lines.split(',')
    end_time = now()
    var elapsed = (end_time - start_time) / 1e9

    print("Time:", elapsed, "seconds")
    print("Number of lines:", len(temp))
```

The new implementation avoids frequent `StringSlice`-`String` conversions and excessive substring copies. By dealing directly with pointers in a single pass, it evidently improves the performance.

**Comment by JoeLoser** [comment]
Is this still the case after https://github.com/modularml/mojo/commit/5b026f4e946fba3e6af02383bd2a112ed49cbaa5?

**Comment by jjvraw** [comment]
I had tested `split` on a dataset, comma separated, with near 300k fields, of which runtime was around 1.7-2x that of Python's, if I remember correctly. 

Separating such, prior to `5b026f4` was not possible.

**Comment by JoeLoser** [comment]
Yeah, in the simple repro test, locally after https://github.com/modularml/mojo/commit/5b026f4e946fba3e6af02383bd2a112ed49cbaa5, I'm seeing Mojo be about 2.65x slower.   Not great, but plenty of room for improvement.   Given how small the string used is, adding `hint_is_trivial_type` to the `List` in the `split` function actually makes things slower for this case.

**Comment by gabrieldemarmiesse** [comment]
Indeed now parsing a huge text file and splitting by lines is around as fast as python. Obviously not great, I'm sure we can do better, but it's not a huge pain point anymore. Closing this issue as this now falls into the "make everything in the stdlib faster" issue.
