### ISSUE TITLE
[Feature Request] Tuples shouldn't require parens

### ISSUE THREAD

**Issue by ayaan-momin** [modularml/mojo#347]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

```shell
Many Values to Multiple Variables
allows you to assign values to multiple variables in one line
```

### What is your motivation for this change?

```shell
x, y, z = "Orange", "Banana", "Cherry"
print(x)
print(y)
print(z)
```

### Any other details?

```shell
x,y = y,x
print(x,y,z)

fruits = ["apple", "banana", "cherry"]
x, y, z = fruits
print(x)
print(y)
print(z)
```

**Comment by lattner** [comment]
Mojo's recent update supports this, we just require parens around tuples for now.  This is tracked on the roadmap

**Comment by lattner** [comment]
Fixed in the next update, thanks!
