### ISSUE TITLE
[BUG] segfault with parallelize

### ISSUE THREAD

**Issue by f-saez** [modularml/mojo#3470]
### Bug description

Hi,

I've run into something that looks like a bug with parallelize. Works well with Mojo stable but not with nightly.

Let's try this code.
```
from algorithm import parallelize

alias BPP = 4
alias NUM_THREADS = 16

fn main():
    var width = 512
    var height = 512
    var stride = width*BPP

    var src = UnsafePointer[UInt8, alignment=32].alloc(height*stride)
    var dst = UnsafePointer[UInt8, alignment=32].alloc(height*stride)

    @parameter
    fn process_line1(y : Int):    
        var idx = y*stride            
        var x = SIMD[DType.uint8,4](42)
        for _ in range(width):
            src.store[width=4](idx, x)
            idx += BPP

    @parameter
    fn process_line2(y : Int):    
        var idx = y*stride            
        for _ in range(width):
            var rgb = src.load[width=4](idx)
            src.store[width=4](idx, rgb)
            idx += BPP

    @parameter
    fn process_line3(y : Int):    
        var idx = y*stride            
        for _ in range(width):
            var rgb = src.load[width=4](idx)
            dst.store[width=4](idx, rgb)
            idx += BPP

    parallelize[process_line1](height, NUM_THREADS)    
    parallelize[process_line2](height, NUM_THREADS)
    parallelize[process_line3](height, NUM_THREADS)

    src.free()
    dst.free()
 ```

process_line1  alone runs fine.
process_line2  alone runs fine.
process_line1 and process_line2 run fine.
process_line3 alone runs fine.

any other combination segfault.

### Steps to reproduce

run the small code provided as an example.

### System information

```shell
Fedora 40 x86_64
mojo 2024.9.905 (ae516e17)
modular 0.9.2 (b3079bd5)
```

**Comment by ehein6** [comment]
This has been fixed in the nightly by https://github.com/modularml/mojo/commit/91bc81e1655a01442832ba1ecfbc6772b4ddaa7c . 

The `width` parameter can no longer be specified in `UnsafePointer::store`, it is inferred from the input type along with the alignment. The alignment for the store was unspecified in the original example, which was probably leading to the segfault.
