### ISSUE TITLE
[Docs] Missing `load_tr` in `struct Matrix`

### ISSUE THREAD

**Issue by gautam-e** [modularml/mojo#349]
### Where is the problem?

https://docs.modular.com/mojo/notebooks/Matmul.html#adding-types-to-the-python-implementation

### What can we do better?

Problem:
> We are also defining a `load_tr`, which loads a vector from the columns specified at the offset.

... but I don't see a `load_tr` anywhere on that page.

Suggestion:
Define a `load_tr` or modify th quoted line accordingly.

**Comment by Mogball** [comment]
@abduld
