### ISSUE TITLE
[Docs] Confusing Matrix implementation

### ISSUE THREAD

**Issue by gautam-e** [modularml/mojo#350]
### Where is the problem?

https://docs.modular.com/mojo/notebooks/Mandelbrot.html

### What can we do better?

The Matrix struct implementation "reverses" rows and columns (e.g. compared to the Matmul notebook).  
Would be great to make a note why (probably because of convention followed in images, for plotting etc.?) or at least mention that it is "reversed".

**Comment by Mogball** [comment]
@abduld
