### ISSUE TITLE
[BUG] Unable to use formatter in Mojo Playground

### ISSUE THREAD

**Issue by Brian-M-J** [modularml/mojo#3518]
Attempting to use the formatter in the [Mojo Playground](https://docs.modular.com/mojo/playground) results in the following error:

```
Format error:

mojo: error: unable to resolve Mojo formatter in PATH
```

A screenshot is attached below:

**Comment by walter-erquinigo** [comment]
Oof, it seems we didn't test this thoroughly in the last release. Thank you for reporting.
