### ISSUE TITLE
[Feature Request] Add an option to keep the focus on editor after "Run Mojo File"

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#3532]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

As title.

### What is your motivation for this change?

Moving the focus back from the terminal can be tedious.

### Any other details?

N/A

**Comment by walter-erquinigo** [comment]
This is a pretty nice ask. I'll do something about it.

**Comment by walter-erquinigo** [comment]
This will be available in the next nightly release. Maybe tomorrow. The changelog entry is:

- The VS Code extension now has the `mojo.run.focusOnTerminalAfterLaunch`
  setting, which controls whether to focus on the terminal used by the
  `Mojo: Run Mojo File` command or on the editor after launch.
  [Issue #3532](https://github.com/modularml/mojo/issues/3532).
