### ISSUE TITLE
[BUG] Latest VSCode nightly extension fails to install Mojo globally

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#3533]
### Bug description

As title.

Produce the following error:

```
Error: Command failed: /home/vscode/.vscode-server-insiders/data/User/globalStorage/modular-mojotools.vscode-mojo-nightly/magic global install -c https://conda.modular.com/max-nightly -c conda-forge max==2.4...6.6 python>=3.11,<3.12
```

### Steps to reproduce

Update extension to v2024.9.2305 and run "Mojo: Reinstall the MAX SDK for VS Code".

### System information

```shell
- OS: Ubuntu on Docker
```

**Comment by Julian-J-S** [comment]
Same here. OS: Fedora (worked before)

**Comment by walter-erquinigo** [comment]
This has been fixed with the latest vscode nightly extension 2024.9.2306.
