### ISSUE TITLE
[Modular CLI] Failed to install magic

### ISSUE THREAD

**Issue by xguo-prestolabs** [modularml/mojo#3550]
### Issue description

I'm not sure here is the right place to post my magic installer issue.

The following command does not work
```bash
curl -ssL https://magic.modular.com | bash
```
here is the error messsage:
```
Installing the latest version of Magic...
#=#=-#  #                                                                     
error: 'https://dl.modular.com/public/magic/raw/versions/latest/magic-x86_64-unknown-linux-musl' not found.
Sorry, Magic is not available for your OS and CPU architecture.  See https://modul.ar/requirements.
```
I checked the installing bash script and found these lines:

```bash
if [[ $PLATFORM == "Darwin" ]]; then
  PLATFORM="apple-darwin"
elif [[ $PLATFORM == "Linux" ]]; then
  PLATFORM="unknown-linux-musl"
elif [[ $(uname -o) == "Msys" ]]; then
  PLATFORM="pc-windows-msvc"
fi
```
Where means all x84-64 + Linux systems choose download from this url: https://dl.modular.com/public/magic/raw/versions/latest/magic-x86_64-unknown-linux-musl
and the resource is not there.

Any suggestions how to fix the installing issue? Thanks.

my system info:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU E5-2643 v3 @ 3.40GHz
stepping	: 2
microcode	: 0x49
cpu MHz		: 1781.965
cache size	: 20480 KB
physical id	: 0
```

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
- What OS did you install modular CLI on ?
```

**Comment by OlehChyhyryn** [comment]
I was going to create the same issue.

I cannot install Magic on any of the OS I have, Mac OS, Ubuntu 24.04, and 22.04 WSL (don't ask why I have all three of them =)

This is a specification of macOS I have

ProductName:		macOS
ProductVersion:		14.6.1
BuildVersion:		23G93

Message from installation:

```
Installing the latest version of Magic...
#=#=#                                                                          
error: 'https://dl.modular.com/public/magic/raw/versions/latest/magic-aarch64-apple-darwin' not found.
Sorry, Magic is not available for your OS and CPU architecture.  See https://modul.ar/requirements.
```

**Comment by zbowling** [comment]
Are you still having this issue today?

**Comment by stringydev** [comment]
I am having this exact issue on MacOS.
