### ISSUE TITLE
[BUG] `UnsafePointer` doesn't expend lifetime long enough

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#3559]
### Bug description

As title. CC @lattner.

There's a separate but related issue, the `lifetime` field is not passed to the return type of `address_of`, so manually specifying lifetime won't work.

### Steps to reproduce

```mojo
fn main():
  s = String("test")
  p = UnsafePointer.address_of(s)
  print(p[])  # crash
```

### System information

```shell
Mojo 2024.9.2705 (bf2938d0) on Docker, Intel Mac
```

**Comment by lattner** [comment]
This is actually two issues: not noticing the lifetime in the parameter list, but also VariadicListMem not propagating it to print call.

**Comment by soraros** [comment]
@lattner So maybe related to #3473?

**Comment by lattner** [comment]
Entirely possible, the fix is straightforward. Testing it now, thank you again for finding this!

**Comment by soraros** [comment]
@lattner This still fails on Mojo 2024.9.2905 (the one with your pack fix):

```mojo
from memory import UnsafePointer

fn print_str(x: String):
  print(x)

@export
fn main():
  s = String("test")
  p = UnsafePointer.address_of(s)
  print_str(p[])  # prints nothing
```

I checked the IR, and it seems that `@llvm.lifetime.end` is still emitted before the `print_str` call.
