### ISSUE TITLE
[Feature Request] LLDB Mojo Plugin

### ISSUE THREAD

**Issue by taylorpool** [modularml/mojo#3562]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

It looks like we need an LLDB language plugin for mojo.

### What is your motivation for this change?

When running mojo-lldb over an executable created with Mojo, it states that:

This version of lldb has no plugin for the language "mojo". Inspection of frame variables will be limited.

I cannot see any variables in the frame. This appears to be consistent with [lldb language plugins documentation](https://lldb.llvm.org/resources/addinglanguagesupport.html#language-and-languageruntime-plugins).

**Comment by walter-erquinigo** [comment]
Don't use the binary `mojo-lldb`. You have to use the command `mojo debug` which defers to `mojo-lldb` with the language plugin initialized :)
