### ISSUE TITLE
[BUG] `UnsafePointer` doesn't extend lifetime for long enough

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#3580]
### Bug description

As title. CC @lattner. Originally reported [here](https://github.com/modularml/mojo/issues/3559#issuecomment-2381194721).

A variant of #3559. The problem persists if `print` is non-variadic.

### Steps to reproduce

```mojo
from memory import UnsafePointer

fn print_str(x: String):
  print(x)

@export
fn main():
  s = String("test")
  p = UnsafePointer.address_of(s)
  print_str(p[])  # prints nothing
```

I checked the IR, and it seems that `@llvm.lifetime.end` is still emitted before the `print_str` call.

### System information

```shell
Mojo 2024.9.3005 (882b4490) on Docker, Intel Mac
```

**Comment by lattner** [comment]
This works now
