### ISSUE TITLE
[Magic CLI]: Unable to install packages with magic

### ISSUE THREAD

**Issue by suahelen** [modularml/mojo#3590]
### Issue description

I am running in to issues with magic after a fresh install on wsl2. 
All command that would install the max package seem to fail. e.g.
```
magic install
magic shell
magic run mojo
```
all these commands result in something along the lines of:

  ⠤ validate cache       [00:00:03] [━━━━━━━━━━━━━━━━━───] max-python (+1)
  ⠤ download & extract   [00:00:03] [━━──────────────────] 21.10 MiB @ 2.34 MiB/s max-core
  ⠴ installing packages  [00:00:03] [━━━━━━━━╾───────────]     5/12 numpy (+3)                                            × failed to link ncurses-6.5-he02047a_1.conda
  ├─▶ failed to link 'share/terminfo/2/2621a'
  ├─▶ unexpected io operation while removing clobbered file
  ╰─▶ No such file or directory (os error 2)

if i remove the max package the magic commands run again, but obviously mojo is not available anymore.

Thanks for any ideas.

### Steps to reproduce

install magic with:
curl -ssL https://magic.modular.com/3c7b6166-badc-49be-bb0f-0bd100dcb8b2 | bash
source /home/fam/.bashrc

init project:
magic init my-mojo-project --format mojoproject

run any of the commands mentioned before

### Version Info

```shell
- magic --version => magic 0.3.0
- os = wsl2 (ubuntu 2204) on windows 
- mojoproject.toml:

[project]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "my-mojo-project
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
```
```

**Comment by zbowling** [comment]
This can happen if you have a case sensitive filesystem mounted on a case-insenstative system. The ncruses packages has two files in it's package with the same name but different cases. See https://github.com/prefix-dev/pixi/issues/1362

**Comment by zbowling** [comment]
Also see: https://github.com/prefix-dev/pixi/issues/234

**Comment by suahelen** [comment]
thanks for the heads-up. 
Just for completenes sake and to wrap up, here how I worked around it. 
That way you can keep project files on the windows file system if necessary.

select a package dir on the wsl file system
`export MAGIC_HOME=/home/yourusername/.magic_packages`

create a project dir within that that package dir
`mkdir -p $MAGIC_HOME/projects/<your_project>`

create a symlink from your project dir to the package dir
`ln -s $MAGIC_HOME/projects/<your_project>/mnt/c/projects/<your_project>/.magic`

**Comment by liuzhishan** [comment]
Hi, how to fix this problem? I encountered the same problem in ubuntu using docker on mac. And I follow the above link, https://github.com/prefix-dev/pixi/issues/1362 and didn't find a solution.

**Comment by suahelen** [comment]
In my case the problem occurred cause I was using a project folder on a windows pc from WSL.

To solve it, I directly cloned the repo of my code to the wsl-filesystem.

**Comment by rcghpge** [comment]
Yo! Running into this as well. WSL2. I actually just installed the new Python 3.13.0 release.

**Comment by ruben-arts** [comment]
@liuzhishan, it could also happen if the cache directory is on a different filesystem, with `magic info` you should be able to find the cache location that is used.

**Comment by liuzhishan** [comment]
> that

thanks, I will have a try with `magic info`.
