### ISSUE TITLE
[Feature Request] Relaxing inline doc by allowing ending with "backtick example"

### ISSUE THREAD

**Issue by rd4com** [modularml/mojo#3603]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Hello, while creating examples for features (PR),
@JoeLoser noted a possible improvement.

For example:

```mojo
fn create_list_int() - >List[Int]:
 """Creates a new list of int.
  
 Returns:
  An empty list of `Int`.
 
 Example:
 ```mojo
 def main():
  x = create_list_int()
	```
	Note: can only finish with a dot and not the triple backticks example above.
	"""
 return List[Int]()	
```

Link to suggestion of @joeloser in PR [https://github.com/modularml/mojo/pull/3593](https://github.com/modularml/mojo/pull/3593)

### What is your motivation for this change?

Examples are usually placed after arguments, parameters and return 👍

### Any other details?

*No response*

**Comment by jackos** [comment]
Thanks @rd4com this is fixed as of the latest build
