### ISSUE TITLE
[Feature Request] Use 2-space indentation and/or increase default line length in the *stdlib* coding style

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#3637]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

As title.

### What is your motivation for this change?

Notice: 

- This request is driven by practical considerations, not aesthetics or personal preference.
- I am *not* suggesting that we should recommend writing typical Mojo code with, for example, 2-space indentation.
- Unlike e.g. naming convention, this change is transparent to ordinary Mojo users and should only matter to stdlib developers.

The Mojo standard library code tends to contain more magic (e.g., `__mlir_op`) and is often more deeply nested (due to constructs like `@parameter if is_some_arch():`). Common measures like breaking into multiple statements often don't work because of these two characteristics of stdlib. Using 4-space indentation, along with an 80-character line length limit, makes logically cohesive code harder to read when it is forced onto multiple lines. Furthermore, with a smaller "buffer" for line lengths, even minor changes can cause significant shifts in formatting, resulting in larger diffs (particularly when improving error messages, such as in `constrained`). Review experience on GH can be horrible because of this.

We have too many cases like the following:

```mojo
    b = long_name_due_to_the_use_of_uncommon_unsafe_method(a)

# after some trivial 2 character change

    b = long_name_due_to_the_use_of_uncommon_unsafe_method(
        a
    )
```

### Any other details?

Can we afford such a big and trivial but disruptive change?

I think the answer is yes.
- The stdlib is still relatively small, and I'd rather going this sooner rather than later.
- We probably need to go through something similar like removing most `var`s anyways, they can happen together.

Cons:
- Use 2-space indentation (like the Swift stdlib, 2-space, 80char): more disruptive, not Pythonic (stdlib code is inherently non-Pythonic though). We don't have support for 2-space indentation in `mblack`.
- Increase line length limit (like the Rust stdlib, 4-space, 100char): (if increased by too much) ruins experience in environments that don't gracefully handle long lines, including GH review.

**Comment by gryznar** [comment]
Personally I'd prefer to increase line length. This will be more readable than 2-space indentation. Deeply nested code is rarely spotted, thus switching to this will spare no more than 6 characters in most cases. Moreover, `black` on which Mojo formatter is based on, allow to change line length

**Comment by soraros** [comment]
> Deeply nested code is rarely encountered, so switching to that will save no more than 6 characters in most cases.

This may be true in typical scenarios, but our standard library code can easily reach 6 or 7 levels of indentation (you can find several examples in `simd.mojo` alone). And let me remind you, these are largely non-refactorable because they are nested for very trivial reasons, as I mentioned above.

I think, in this particular case, the argument about readability for an ordinary Mojo user hardly applies. Of course, increasing the line length limit alone can be a significant improvement. But also be aware of the "still need to review code on GH" dilemma (which is why Swift took their choice).

**Comment by gryznar** [comment]
As far as I understand 80 chars is set by Github itself or this limit is bigger?

**Comment by soraros** [comment]
It's not a hard limit imposed by GitHub. However, if you want to view an entire line in the side-by-side diff view while maintaining *some* level of accessibility, you're effectively limited to around 90 characters per line, 95 at most.

**Comment by gryznar** [comment]
So, here is the answer. We can increase limit from 80 to 90 chars per line

**Comment by soraros** [comment]
> We can increase limit from 80 to 90 chars per line

Yea, *I think* we should at least do that, preferably both. But of course, it's not my decision to make, and my personal preferences do not matter.

**Comment by owenhilyard** [comment]
From the popular [black](https://github.com/psf/black) formatter for python: 
> You probably noticed the peculiar default line length. Black defaults to 88 characters per line, which happens to be 10% over 80. This number was found to produce significantly shorter files than sticking with 80 (the most popular), or even 79 (used by the standard library). In general, [90-ish seems like the wise choice](https://youtu.be/wf-BqAjZb8M?t=260).
>
> If you're paid by the line of code you write, you can pass --line-length with a lower number. Black will try to respect that. However, sometimes it won't be able to without breaking other rules. In those rare cases, auto-formatted code will exceed your allotted limit.
>
> You can also increase it, but remember that people with sight disabilities find it harder to work with line lengths exceeding 100 characters. It also adversely affects side-by-side diff review on typical screen resolutions. Long lines also make it harder to present code neatly in documentation or talk slides.

Given the popularity of Black in the python ecosystem, and that the Mojo formatter already takes inspiration from them it might be best to align with them.

I can comfortably do a 3-way diff on a 1920x1080p monitor with 88 columns and did so with some frequency when I was maintaining a large python codebase, but much more than that forces me to decrease the font size. 90 is probably the limit to enable that kind of workflow.

**Comment by nmsmith** [comment]
At the font size I use (which is higher than most people), 88/90 characters also happens to be the perfect line width for having two editors open, plus a sidebar.

I've found the 80 character limit to be a big nuisance in Mojo code, so I'm strongly in favour of increasing it. Both in the stdlib, and in Mojo's official formatter.

The amount of lines that need wrapping decays ~exponentially with the line width, so an 8 character bump has a large impact. @owenhilyard, I think you did an A/B test on one of your codebases? We should probably do that for the stdlib as well, and see how the line count changes.

**Comment by soraros** [comment]
I don't think the claims that "2-space indentation hurts readability" are actually backed by any empirical evidence.

One unique aspect of Mojo is that we use constructions (syntactic forms) where two levels of indentation represent only one layer of logical scoping or nesting.

- Nested `fn body` and `@parameter for` constructs to represent vectorized or parallelized loops, as seen in [`matmul.mojo`](https://github.com/modularml/mojo/blob/nightly/examples/matmul.mojo). The linked `matmul` implementation becomes highly unreadable when the indentation level is high. And that's just the toy `matmul`; imagine the horrors of the real thing. Furthermore, we can expect to see more code written in this style once the `algorithm` module is open-sourced.

- Python's `match` statement wastes one level of indentation, and we also have to deal with that. Python folks can play fast and loose and just pretend `match` doesn't exist, but in Mojo, pattern matching is our type-safe best friend for dealing with sum types.

- Wrapping raising code in non-raising contexts is a subtle quirk unique to Mojo. In Python, every function can raise exceptions, and `try .. except` isn't simply used as a wrapper that often; people don't have to *always* explicitly wrap raising code in `noexcept` contexts in C++, and they use 2-space indentation already. Swift has `try` expressions which are inline; Rust uses alternative measures for error handling.

To give a concrete data point for how a codebase with the above characteristics might look in the Python world, let's consider [JAX](https://github.com/jax-ml/jax/blob/main/jax/_src), a project that uses 80-character lines and 2-space indentation. Here are the commonalities it shares with the Mojo standard library (again, with *the Mojo stdlib*, I have no interest debating how people could/should format *their* own code):

- Code is heavily type-annotated, so more information needs to fit on a single line. `NamedTuple`, etc., is used everywhere, similar to the static Mojo code we write today.

- Due to how the tracing mechanism is implemented, they need to use more indentation levels than ordinary Python programs and have to deal with the "2 indents for one" problem I mentioned above.

- It contains a lot of mathematical code with deeply nested loops.

- JAX (like Mojo) is basically a front end to XLA (MLIR), meaning much of the code is dispatching calls to StableHLO intrinsics (LLVM and MLIR intrinsics).

- Uses functional patterns from time to time, with inlined function definitions (not lambdas). This is close to the `vectorise[body](...)` pattern we mentioned above.

It's a large and well-maintained Python codebase with many, many contributors (who are all Python programmers). They even share backgrounds (academics and AI practitioners) with Mojo's target audience. I've never heard contributors complain about the styling choices the JAX team makes. Two-space indentation might look unfamiliar to Python programmers at first, but it's really not that big of a deal at the end of the day. Let's not forget that even though we focus a lot on Python programmers when talking about style, most of the standard library is likely being maintained by seasoned C++ programmers (like things in the Python community already), so let's not alienate them.

Let's focus on the immediate practical benefits (and cons) instead of going into philosophical or aesthetics arguments.

**Comment by nmsmith** [comment]
@soraros A picture speaks a thousand words. Looking at these two function definitions, how easily can you identify the block that each statement belongs to?

I don't think we need to do any empirical studies. I think we can just look at the picture and use our common sense.

<img width="322" alt="Screenshot 2024-10-15 at 6 41 27 PM" src="https://github.com/user-attachments/assets/1520c10c-b816-4805-9f01-ab74e9757c35">

**Comment by soraros** [comment]
You are only proving that *you* are incapable of identifying which block each statement belongs to. Kudos for disabling indentation guide btw. *Your opinion*, which might well align with common *feelings*, is not the same as accepted common knowledge. I find them perfectly readable, which also doesn't matter much.

The main problem is that your code is not representative of the code we see in the stdlib, which can go to 7 levels of indentation of more, with the first a few levels purely boilerplate (`@parameter if arch()`, everything is a method so 8 spaces gone already).

> I don't think we need to do any empirical studies

*You* don't have empirical evidence, while I gave an example of how such a thing, contrary to common misconceptions, *can* work. Right from the Python AI community no less.

This may sound a bit harsh, but why should we tailor the very private part (unlike naming conventions) of stdlib coding style to people (most Python people using Mojo) *not* maintaining and reading said code?

**Comment by nmsmith** [comment]
Sora, I've found your responses incredibly rude, so I'm going to stop engaging now. I'll let others decide what they think about the formatting.

**Comment by owenhilyard** [comment]
> The amount of lines that need wrapping decays ~exponentially with the line width, so an 8 character bump has a large impact. @owenhilyard, I think you did an A/B test on one of your codebases? We should probably do that for the stdlib as well, and see how the line count changes.

@nmsmith Yes, I was responsible for writing the python style guide for python inside of DPDK (C) after the [test harness](https://git.dpdk.org/tools/dts/) (Python) had grown to ~250 kloc. Before that there were no line limits, so I got a chance to test a large organic codebase. 80 characters produced a lot of line breaks in annoying places, but 88 characters cut the line count by ~5k vs 80 characters, with many of those being odd line breaks that weren't present at 88 characters. 90 characters was a marginal improvement and started to have issues on github when people were using dyslexia-friendly non-monospace fonts. 92 characters was around when 3-way diff stopped fitting nicely on my 1080p monitor (it being a linux foundation project, 3-way diffs are more common for maintainers because of the git patch workflow). 

One other point of discussion which is related to this (since I'm now looking through my old commits and notes), is whether the Mojo formatter should offer functionality like [isort](https://pycqa.github.io/isort/) to keep imports in std in some order we decide.

**Comment by soraros** [comment]
Talked with Joe privately who indicated that the team prefers `black`'s default setting: 80-char + 4-space. So it's settled, closing.

**Comment by JoeLoser** [comment]
To clarify: `black`defaults to `88` chars per line which we're +1 for as a team, but there's not wide consensus on that internally, so we're not actively pushing for it at the moment internally (since a lot of things that we do in the standard library get more widely adopted internally for all Mojo code when it comes to guidelines/coding style).<br><br>We were weak -1 on the change to two space indentation.

**Comment by nmsmith** [comment]
> Note that our fork of black, `mblack`, which `mojo format` calls into, has a fixed default of 80 chars per line currently.

FWIW this is why I expressed an interest in an 88-char default. Whatever line width `mojo format` defaults to is likely to become the standard (or most popular choice) in the Mojo community / package ecosystem, just out of happenstance. It would be good if the Mojo community could come to a rough agreement on what the best default is for Mojo.

**Comment by JoeLoser** [comment]
I agree.  Personally, I think we should change `mojo format` to default back to `88` (it was prior to early April from reading the code), but that's a bit stalled internally at the moment.

**Comment by soraros** [comment]
@JoeLoser I think it's still important to make it clear that the stdlib style is distinct from any "standard Mojo style." One notable example is the recommended use of `var` in the stdlib.
