### ISSUE TITLE
[BUG] OOM compiling 24 line program. 

### ISSUE THREAD

**Issue by owenhilyard** [modularml/mojo#3642]
### Bug description

The attached program causes an OOM on my 32 GB of memory laptop, consuming well over 16 GB of memory. It shouldn't consume anywhere near that much memory, given that it only allocates about 0.5 GB. The issues don't happen if I remove the initialization loop, but from memory usage it looks like that version decides that `l[0].inner[0]` is a zero and puts that into the binary since it does not use enough memory to allocate the array.

### Steps to reproduce

```mojo
from collections.inline_array import InlineArray
from memory import UnsafePointer
from random import randint

struct HugeThing:
  alias length: UInt = 1 << 29
  # 512 MiB array
  var inner: InlineArray[UInt8, Self.length]

  fn __init__(inout self):
    self.inner = InlineArray[UInt8, Self.length](unsafe_uninitialized=True)

    for i in range(self.length):
      randint[DType.uint8](self.inner.unsafe_ptr(), Self.length, 0, 255)

  fn __moveinit__(inout self, owned other: Self):
    self.inner = other.inner^

fn main():
  var l = UnsafePointer[HugeThing].alloc(1)

  l[0] = HugeThing()

  print(l[0].inner[0])
```

### System information

```shell
Mojo version: mojo 2024.10.1105 (e911bf68) (Latest nightly at time of writing)
Magic version: magic 0.2.3
```

**Comment by soraros** [comment]
I'm confused.

Do you mean that compiling or running the program is causing the OOM? If it's the former, how much the program itself allocates shouldn't matter (still could be a bug for using that much memory). If it's the latter, doesn't the title seem wrong?

**Comment by owenhilyard** [comment]
@soraros Compiling causes an OOM. The reason I mentioned runtime allocation was because even if Mojo was interpreting the program it should be vastly lower memory than this.

**Comment by martinvuyk** [comment]
Using `mojo 2024.10.1905` it compiles for any size (IMO it should be constrained for too big stack allocs), when trying to run it it gets one core stuck at 100%. I can get up to `length: UInt = 50 * 2**10` and it runs fine which surprised me because AFAIK stack alloc limit should be around 8 MiB. Anyway, no idea what you are trying to do but if you need such a big array just use `UnsafePointer[UInt8]`/`Span[Byte]` and use load and store according to host simd width. You can see an example [here](https://github.com/modularml/mojo/blob/fcd3d4aac153f1e388b3249e3f4f4fd7a9b6aea1/stdlib/src/utils/string_slice.mojo#L35)

**Comment by ematejska** [comment]
@joe Should InlineArray be constrained by a maximum size instead of just 0?  If not, I think we should close this out.

**Comment by owenhilyard** [comment]
> @joe Should InlineArray be constrained by a maximum size instead of just 0? If not, I think we should close this out.

The issue is stale and appears to be fixed, so we can close this issue, but I've written the C and Rust equivalents of this code many times. I don't want an upper bound on the size because there are legitimate reasons to create a 50 GB array (checkpoint recovery from another node in distributed databases, especially using RDMA). A warning if a multi-MB object is placed on the stack might make sense.

**Comment by owenhilyard** [comment]
Fixed on current nightly
