### ISSUE TITLE
[BUG] Incorrect Variant type from ternary expression 

### ISSUE THREAD

**Issue by bgreni** [modularml/mojo#3645]
### Bug description

Returning an `Int` from a ternary expression in a function that returns `Variant[Int, Float64]` will convert the value to a `Float64`.

### Steps to reproduce

```mojo
from utils import Variant

fn foo(b: Bool) -> Variant[Int, Float64]:
    return Int(4) if b else Float64(7)

fn main():
    var v = foo(True)
    print(v.isa[Int]()) # prints False
    print(v.isa[Float64]()) # prints True
    print(v[Float64]) # prints 4.0
```

Formatting the code like so produces the expected result
```mojo
fn foo(b: Bool) -> Variant[Int, Float64]:
    if b:
        return Int(4)
    return Float64(7)
```

### System information

```shell
- MacOS 14.5
- mojo 2024.9.905 (ae516e17)
- magic 0.3.1 - (based on pixi 0.29.0)
```

**Comment by soraros** [comment]
Actually, it has nothing to do with `Variant`. A implicit conversion happened in the ternary expression, since both branches must have the same type.

```mojo
fn main():
  res = Int(4) if b else Float64(7)  # has type Float64
```
