### ISSUE TITLE
[Issue Template]  Mojo bug report

### ISSUE THREAD

**Issue by DWSimmons** [modularml/mojo#3647]
On
https://github.com/modularml/mojo/issues/new/choose

when you choose [Mojo bug report](https://github.com/modularml/mojo/issues/new?assignees=&labels=bug%2Cmojo-repo&projects=&template=mojo_bug_report.yaml&title=%5BBUG%5D)

the [issue template](https://github.com/modularml/mojo/blob/main/.github/ISSUE_TEMPLATE/mojo_bug_report.yaml) still asks for `modular -v`[link to offending line](https://github.com/modularml/mojo/blob/ced1ecb1ed102917467a8b099986fe6a7204d6b6/.github/ISSUE_TEMPLATE/mojo_bug_report.yaml?plain=1#L43)

**Comment by steventr** [comment]
Thanks! https://github.com/modularml/mojo/pull/3646
