### ISSUE TITLE
[Feature Request] Hash the username/email in the Mojo playground notebook server URLs

### ISSUE THREAD

**Issue by suvash** [modularml/mojo#37]
## Request

Hash the username/email that's used on the Mojo playground notebook server URLs, instead of parsing it as it.

### Motivation

As of now, the Mojo playground service URLs have the username/email directly embedded in them. For eg. `https://playground.modular.com/user/myawesomeemail@gmail.com/lab/tree/HelloMojo.ipynb` has the account email `myawesomeemail@gmail.com` in the URL itself.

Instead, this issue proposes to use the hash of the account email/username, or perhaps even the hash of an internal account id etc. for 3 fold benefits, that I can think of now:
- non ascii characters in the username would not have url encoding/decoding issues - Remove possible bugs
- email addresses would not be leaked if the urls were to be shared in the future - Remove possible email leakage in urls 
- if using hash of an internal id instead of username/email, additional benefit would be that the URLs won't change if the username/email changes over time, this is really a business design choice though. - Permanent URLs

### Description and Requirements

- Maintain a hash of the user identity, whethere it be username, email or some internal id
- Use that in the URL route instead of the email address as it now.

**Comment by iamtimdavis** [comment]
Thanks for the feedback @suvash. 

It's something we're considering and we'll note this down as a feature request ✅

**Comment by ematejska** [comment]
This playground has been deprecated, closing this issue.  See the new playground here: https://docs.modular.com/mojo/playground
