### ISSUE TITLE
[BUG] Unify the constructor signature for pointer-based initialization across multiple types

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#3704]
> That said, the unsafe constructors from pointers are really a mess, and I find myself having to look up the keyword names every time. Could we adopt a convention like `fn __init__(inout self, *, ptr: UnsafePointer, len: Int)`?
> 
> * `String`: `fn __init__(inout self, ptr: UnsafePointer[UInt8], len: Int):`
> * `StringRef`: `fn __init__(inout self, ptr: UnsafePointer[c_char], len: Int):`
> * `StringSlice`: ` fn __init__(inout self, *, unsafe_from_utf8_ptr: UnsafePointer[UInt8], len: Int):`
> * `Span`: `fn __init__(inout self, *, unsafe_ptr: UnsafePointer[T], len: Int):`
> * `List`: `fn __init__(inout self, *, unsafe_pointer: UnsafePointer[T], size: Int, capacity: Int):`

Agreed, they're wildly inconsistent.  +1 to your proposed convention - feel free to open a PR.  I'm also +1 for making them all (including `String` kw-only for the ptr + len constructor until we fix implicit constructor issue you linked).

_Originally posted by @JoeLoser in https://github.com/modularml/mojo/issues/3698#issuecomment-2429942505_

**Comment by martinvuyk** [comment]
I agree that it's necessary, but I'll be a bit nit-picky and very subjective: since we are defining a new standard, I wanted to say that I strongly dislike using `len` as argument since it is the name of a builtin function. I personally prefer going for `length`.

**Comment by JoeLoser** [comment]
> I agree that it's necessary, but I'll be a bit nit-picky and very subjective: since we are defining a new standard, I wanted to say that I strongly dislike using `len` as argument since it is the name of a builtin function. I personally prefer going for `length`.

Agreed given that argument.  I'd be fine with `length`.

**Comment by JoeLoser** [comment]
I think this work is done now, closing this out.  Most of these constructors use `ptr` and `len` are their kw args.
