### ISSUE TITLE
[BUG] Mojo frees memory while reference to it is still in use

### ISSUE THREAD

**Issue by avitkauskas** [modularml/mojo#3710]
### Bug description

You cannot take the address of a List `data` into a variable and use it as a reference later, because Mojo frees the memory allocated to `data` by destructuring the List as it reckons it's not being used beyond the point of the last syntactic mention of the List variable.

### Steps to reproduce

```mojo
fn main():
    a = List(1, 2, 3)
    b = List[Int](capacity=3)

    p = a.data
    for i in range(len(a)):
        (p + i).move_pointee_into(b.data + i)
    b.size = 3

    # if you uncomment the line below, everything works fine
    # _ = a.size

    print(b.__str__())
    # => [4462641216, 2, 3]
```

### System information

```shell
macOS 15.0.1
mojo 2024.10.2406 (54f70ee8)
magic 0.3.1 - (based on pixi 0.29.0)
```

**Comment by soraros** [comment]
This is the expected behaviour [ref](https://docs.modular.com/mojo/manual/lifecycle/death#default-destruction-behavior).

`a.data` returns a `UnsafePointer` that doesn't keep `a` alive.

**Comment by avitkauskas** [comment]
So maybe ASAP destruction is not such a great idea? Maybe scope-based destruction makes better sense? Because cases like this are quite surprising IMHO.

10 days ago I was wondering about another case on Discord. And Chris Lattner noticed that and fixed the case immediatelly. Thanks to him! But I can just show you what the case was:
```mojo
from memory import UnsafePointer

struct A:
    var data: UnsafePointer[Int]

    fn __init__(inout self):
        self.data = UnsafePointer[Int].alloc(1)
        self.data.init_pointee_copy(1)

    fn __del__(owned self):
        self.data.free()
```
Create a file `test_struct.mojo`
```
from testing import assert_equal
from destruct import A

fn test_destruct() raises:
    a = A()
    assert_equal(a.data[0], 1)
    # _ = a.data
```
And test was failing unless you uncommented the last line.

The case of the current issue is a bit different, and I understand it when you say it's expected. But still, I find it surprising and inconvenient.

**Comment by avitkauskas** [comment]
In this case, we could solve the problem just using `a.data` directly:
```mojo
for i in range(len(a)):
    (a.data + i).move_pointee_into(b.data + i)
```

But let's say I want to move elements from the end of `a` to the front of `b`. Then:
```mojo
scr = a.data + len(a) - 1
for i in range(len(a)):
    (src - i).move_pointee_into(b.data + i)
```
is much more natural (and can be a bit more efficient) than:
```mojo
for i in range(len(a)):
    (a.data + len(a) - 1 - i).move_pointee_into(b.data + i)
```

**Comment by soraros** [comment]
There’s solid reasoning (like enabling copy-to-move optimisations) behind Mojo’s ASAP destruction [ref](https://youtu.be/9ag0fPMmYPQ). But finding this behavior surprising likely comes down to habit. After all, `UnsafePointer` is called "unsafe" for a reason; the real fix is to keep the buffer alive with `_ = a`. That said, `UnsafePointer` does have an `origin` field, so `List.unsafe_ptr` could return `UnsafePointer[T, __origin_of(self)]`. It’s just a matter of wiring things up.

**Comment by rd4com** [comment]
Hello, it is possible to use the `origin` parameter of `UnsafePointer`:
```mojo
from memory import UnsafePointer
fn main():
    a = List(1, 2, 3)
    b = List[Int](capacity=3)
    p = a.data.bitcast[origin=__origin_of(a)]() 
    for i in range(len(a)):
        (p + i).move_pointee_into(b.data + i)
    b.size = 3
    print(b.__str__())
```

**Comment by avitkauskas** [comment]
Thank you both for comments and explanations. I like the `bitcast[origin=__origin_of(a)]()` aproach as it clearly expresses the intent. I'm closing the issue then.

**Comment by soraros** [comment]
Actually, given that `UnsafePointer` does carry `origin=MutableAnyOrigin` (thus keeping everything in scope live), what I said above could be entirely wrong and this might be a case of #3580. See also: https://github.com/modularml/mojo/commit/016b6f728a8a54d22d294759cfe1112b95816c1d.

**Comment by rd4com** [comment]
Yep @avitkauskas , glad the bitcast is useful,
maybe the issue could stay open until modular see your issue first ?
(as @soraros commented, the `UnsafePointer` have `MutableAnyOrigin`)

**Comment by lattner** [comment]
Just catching up now.  hrm, this looks really weird. We're not handling the control flow effect well here. I'll take a look

**Comment by lattner** [comment]
reduced testcase that still has the problem (frees the list after the call to len but before the loop):

```
fn test(owned a: List[Int], inout b: List[Int]):
    p = a.data
    for i in range(len(a)):
        p .move_pointee_into(b.data)
```
