### ISSUE TITLE
[Feature not working] compile time @parameter function not working

### ISSUE THREAD

**Issue by osag1e** [modularml/mojo#3731]
error: unsupported decorator on 'for' statement
    @parameter
     ^~~~~~~~~
mojo: error: failed to parse the provided Mojo source module

**Comment by soraros** [comment]
Could you please provide the full snippet?

**Comment by osag1e** [comment]
<img width="647" alt="Screenshot 2024-11-02 at 12 35 07" src="https://github.com/user-attachments/assets/96a960a0-51e4-47f1-a6c2-855e8598211d">

**Comment by osag1e** [comment]
<img width="602" alt="Screenshot 2024-11-02 at 12 44 48" src="https://github.com/user-attachments/assets/2bc23f32-9790-4f83-a4b8-583c80d87284">

**Comment by soraros** [comment]
Which version of Mojo are you using?

**Comment by osag1e** [comment]
![IMG_6072](https://github.com/user-attachments/assets/f21dd1ad-2c5c-4f1c-b159-70f4c5bd7dd7)
The latest one ☝️

**Comment by osag1e** [comment]
> Which version of Mojo are you using?

mojo 24.3.0

**Comment by soraros** [comment]
This unrolling was supported by `@unroll`, which was renamed to `@parameter` in version 24.4. Update Mojo, and the problem will be resolved.

Please use the issue template next time and ideally fill in all the details. Also, please share the repro in a code block.

**Comment by osag1e** [comment]
My apologies! I found the solution to my problem. The issue occurred because I continued working in the old repository I had created before the introduction of magic shell and virtual environments. 
<img width="731" alt="Screenshot 2024-11-03 at 01 06 52" src="https://github.com/user-attachments/assets/3b8cea3b-9237-458d-b105-ff7795674fa8">

**Comment by osag1e** [comment]
> This unrolling was supported by `@unroll`, which was renamed to `@parameter` in version 24.4. Update Mojo, and the problem will be resolved.
> 
> Please use the issue template next time and ideally fill in all the details. Also, please share the repro in a code block.

Understood. Thanks Soraros.
