### ISSUE TITLE
[Dev Console] VSCode nightly extension adds run args incorrectly.

### ISSUE THREAD

**Issue by josiahls** [modularml/mojo#3732]
### Issue description

I'm trying to add ` -I .` to vscode run args, but when I run the debugger, it adds the args at the end instead of after the `run` command. This isn't allowing me to debug a package via a separate test dir.

```bash
...globalStorage/modular-mojotools.vscode-mojo-nightly/magic-data-home/envs/max/bin/mojo \
run \
--no-optimization \
--debug-level full /home/fastrl_mojo_user/fastrl_mojo/c_binder_mojo/tests/test_clang.mojo -I .
```
should be
```bash
...globalStorage/modular-mojotools.vscode-mojo-nightly/magic-data-home/envs/max/bin/mojo \
run  -I . \
--no-optimization \
--debug-level full /home/fastrl_mojo_user/fastrl_mojo/c_binder_mojo/tests/test_clang.mojo
```

### Steps to reproduce

`mojo 2024.11.118 (a366db40)`

![Screenshot from 2024-11-01 22-19-06](https://github.com/user-attachments/assets/9f215cbe-344f-4dc9-b2df-744ee122b706)

**Comment by walter-erquinigo** [comment]
@josiahls , I think you need to pass those arguments as the build arguments, not run arguments :) 

`-I .` are arguments for the compiler and not for the executable

**Comment by josiahls** [comment]
@walter-erquinigo You're right, that works. I just got confused because both are added after the mojo run line
