### ISSUE TITLE
[BUG] `math.ceildiv` gives incorrect results for unsigned simd types

### ISSUE THREAD

**Issue by soraros** [modularml/mojo#3733]
### Bug description

As title.

```mojo
fn ceildiv[T: CeilDivable, //](num: T, denom: T) -> T:
  return -(nun // -denom)  # shouldn't use __neg__ on unsigned types
```

### Steps to reproduce

```mojo
import math

fn main():
  res = math.ceildiv(UInt8(8), 2)
  print(res)  # prints 0
```

### System information

```shell
Mojo 2024.11.305 (a9c84705) on Docker, Intel Mac
```

**Comment by corrosive4354** [comment]
In the implementation of the ceildiv function, the negative value operation (__neg__) of the unsigned type is used, which is incorrect for unsigned types. This leads to errors in the calculation results.

Seeing that you are using Docker, I would like to recommend [Servbay](https://servbay.com) to you, which is more professional and easy to use than Docker on Mac.
