### ISSUE TITLE
[Docs] Tuple limitations: multiple return values are supported even without parens

### ISSUE THREAD

**Issue by armgabrielyan** [modularml/mojo#379]
### Where is the problem?

https://docs.modular.com/mojo/roadmap.html#tuple-limitations

### What can we do better?

The documentation says that multiple return values without parens are not supported:

```mojo
fn multiple_returns() -> (Int, Int):
    return 0, 1
```

However, the above code works correctly in the Mojo Playground.

**Comment by lattner** [comment]
Thanks for pointing this out, we have partial support for missing parens (notably they work in returns, but not as general expressions).  We'll finish this off before declaring success.

**Comment by lattner** [comment]
Fixed and will be in the next build, tuples don't require parens anymore!
