### ISSUE TITLE
[Feature Request] Libray to support apache arrow

### ISSUE THREAD

**Issue by sa-** [modularml/mojo#38]
## Request

Add support for Apache Arrow to enable usage of all the tools that come with it, potentially via arrow2

### Motivation

Apache Arrow and pyarrow are big parts of the python data community, support for arrow datasets would enable interop with all the python libraries that use it. 

It would also enable mojo users to use existing parquet libraries with little to no overhead costs since parquet readers will often deeserialize to the arrow format

### Description and Requirements
The spec is described here: https://arrow.apache.org/docs/format/Columnar.html

**Comment by lattner** [comment]
This would be super awesome.  Mojo has a "problem" that it is applicable to all of compute... but it doesn't make sense to track all the possible applications in the issue tracker.  Let's talk about this on discord over the coming months as the language matures, thanks!

**Comment by sa-** [comment]
Fair enough!
