### ISSUE TITLE
[Docs] Exceptions in the standard library

### ISSUE THREAD

**Issue by armgabrielyan** [modularml/mojo#381]
### Where is the problem?

https://docs.modular.com/mojo/roadmap.html#the-standard-library-has-limited-exceptions-use

### What can we do better?

The documentation mentions that in the following code `DynamicVector` will not raise an out-of-bounds error, but it will crash, and `Int` does not throw on divide by zero.

```mojo
let v = DynamicVector[Int](0)
print(v[1]) # crash 💥

print(1/0) # does not raise and could print just about anything
```

However, `DynamicVector` does not crash, but returns unpredictable values, and `Int` raises an error that "'Int' does not implement the '__truediv__' method".

**Comment by care1es5** [comment]
Just to add another example that does raise an error `print (-1**(1/2))` (square rooting -1 numbers) due to not having '**truediv**' method.
