### ISSUE TITLE
[BUG] Can't use returned reference from function

### ISSUE THREAD

**Issue by seanbaxter** [modularml/mojo#3813]
### Bug description

```python
struct Foo:
  var a: Int32

  fn __del__(owned elf):
    print("Destroyed Foo")

  fn __init__(inout self):
    self.a = 1
    print("Created Foo")

fn min(ref [_] a: Foo, ref [_] b: Foo) -> ref [__origin_of(a, b)] Foo:
    return a

fn main():

  var f1 = Foo()
  var f2 = Foo()
  var r = Pointer.address_of(min(f1, f2))

  # error: expression must be mutable in assignment
  r[].a = 101

  print(f1.a)
  print(f2.a)
  ```

I've been trying to implement a `min` function that takes and returns references. A common origin doesn't compile. Using `__origin_of` compiles, but the returned reference is not usable. If I catch it in a `var` it appears to copy the value out. If I catch it in a `Pointer` then it's immutable.

### Steps to reproduce

mojo build

### System information

```shell
mojo 24.6.0.dev2024112222 (0f8a2020)
```

**Comment by guna-sd** [comment]
The issue arises because the original function uses immutable references by default (ref [_]), which prevents mutation when you try to modify the returned reference.

Changing the function to:
```mojo
fn min(ref [MutableAnyOrigin] a: Foo, ref [MutableAnyOrigin] b: Foo) -> ref [__origin_of(a, b)] Foo:
    return a
```
works fine and resolves the issue.

**Comment by nmsmith** [comment]
`ref[_]` doesn't mean "immutable reference". It's meant to be parametric over mutability.

Also, using `MutableAnyOrigin` doesn't give you a function that is parametric over mutability. It gives you one where the arguments are treated as potentially aliasing _anything_. As far as I'm aware, it's primarily meant to be used for `UnsafePointer`, i.e. C-style pointers that provide no aliasing guarantees.
