### ISSUE TITLE
[BUG] Mutability not preserved when taking the union of two origins.

### ISSUE THREAD

**Issue by nmsmith** [modularml/mojo#3815]
### Bug description

When taking the union of two origins using the syntax `__origin_of(a, b)`, it appears the mutability of the origins is not preserved. The following program demonstrates the problem:
```mojo
# This function preserves mutability as expected. (Notice we aren't taking the union of origins.)
fn id(ref [_] x: Int) -> ref [__origin_of(x)] Int:
    return x

# This function doesn't preserve mutability.
fn min(ref [_] a: Int, ref [_] b: Int) -> ref [__origin_of(a, b)] Int:
    return a

# Writing out the parameters explicitly doesn't help.
fn min2[
    m1: Bool, m2: Bool, o1: Origin[m1].type, o2: Origin[m2].type
](ref [o1] a: Int, ref [o2] b: Int) -> ref [__origin_of(a, b)] Int:
    return a

fn main():
    var x: Int = 0
    var y: Int = 0
    id(x) += 1        # OK
    min(x, y) += 1    # ERROR
    min2(x, y) += 1   # ERROR
```

### System information

```shell
mojo 24.6.0.dev2024112505 (a2441ec7)
```

**Comment by lattner** [comment]
I fixed several problems with origin unions and error messages, e.g before and after:

```
error: cannot return reference with incompatible origin: 'c' vs '{#lit.struct.extract<:@stdlib::@builtin::@stubs::@Origin<:@stdlib::@builtin::@stubs::@Bool {:i1 1}> ao, "_mlir_origin">, b}'
error: cannot return reference with incompatible origin: 'c' vs '{ao._mlir_origin, b}'
```

but this one i'm not sure is a problem.  The issue here is that there are two uncorrelated mutabilities.  Mojo handles it correctly if you do this:

```
fn min3[m: Bool, o1: Origin[m].type, o2: Origin[m].type](ref [o1] a: Int, ref [o2] b: Int) -> ref [__origin_of(a, b)] Int:
    return a
```

**Comment by lattner** [comment]
Well, Mojo sees that these are different when forming the union and knows their mutability might be different, but isn't propagating it as an and constraint.  It is just giving up, which prevents the caller from seeing it.  Lemme see about this, it already knows logical equivalence... bwahaha.
