### ISSUE TITLE
Mojo Language Server reports crash on empty file.

### ISSUE THREAD

**Issue by RichardCoppin** [modularml/mojo#3826]
## Issue Description
It would seem that the Language Server is unable to deal with empty .mojo files. This is particularly an issue with `__init__.mojo` files which are often meant to be empty. 

This creates a false positive as the packages are highlighted as containing errors, which in fact do not:
![image](https://github.com/user-attachments/assets/2c35648b-af8c-40c3-a3d1-dba0d9fb5818)

This is the error message received when opening an empty .mojo file:
> A crash happened in the Mojo Language Server when processing this document. The Language Server will try to reprocess this document once it is edited again. Please report this issue in https://github.com/modularml/mojo/issues along with all the relevant source codes with their current contents.

## Steps to reproduce:
Create an empty `__init__.mojo` file. Open said mojo file.
Observe error:
![image](https://github.com/user-attachments/assets/3e27a485-a612-4e3b-8ddf-52b1cee58bd8)

## Request:
The LSP should be able to deal with empty .mojo files and not report a crash.

## Workaround:
Adding a comment  or a blank line to the top of the __init__ file removes the error.

**Comment by walter-erquinigo** [comment]
Thank you for reporting this! I'll look into it soon.

**Comment by RichardCoppin** [comment]
Just loaded the latest Nightly build. It looks likes it's fixed.

Thanks
