### ISSUE TITLE
[BUG] Poor error message when invoking a function pointer upon an argument of the wrong origin

### ISSUE THREAD

**Issue by nmsmith** [modularml/mojo#3829]
### Bug description

The following function is meant to apply `f` to `x`. It's erroneous, because `x` doesn't have the origin that `f` requires.

```mojo
fn apply_f[o: MutableOrigin](f: fn(ref[o] x: Int) -> None, x: Int):
    f(x)
```

The error message is poor:
> argument #0 cannot be converted from 'Int' to 'Reference['Int', ...]. note: cannot bind an RValue to a reference.

I'd expect the error message to say something like:
> argument #0 does not have the required origin

The error messages are slightly better when you declare x as `mut` or `ref`, but they're still not great.

### System information

```shell
mojo 24.6.0.dev2024120105 (78dab9b8)
```

**Comment by lattner** [comment]
Thank you for filing this, this is indeed horrible and out of date, I'll fix it when I get a chance!
