### ISSUE TITLE
[BUG] Duplicates of large dylibs in `.magic/envs` folder

### ISSUE THREAD

**Issue by azarovalex** [modularml/mojo#3831]
### Bug description

Setting up a new project with `magic init` creates duplicates of some large dylibs (libmonnx, libmtorch, libmof) in `.magic/env`. This results in an empty project taking 1GB+ of disk space. Around 400-500MB of this space are copies that should be possible to replace with symbolic links to save considerable amount of space.

### Steps to reproduce

– Create a new hello-world project with `magic init hello-world --format mojoproject`.
– Observe that there some dylibs are duplicated in `.maginc/envs` folder, they are not symbolic links, but full copies

```bash
sha1sum .magic/envs/default/lib/python3.12/site-packages/max/lib/libmonnx.dylib
5e701eae6ff45f5c1966d5307366c4da99218d08  .magic/envs/default/lib/python3.12/site-packages/max/lib/libmonnx.dylib
➜  hello-world sha1sum .magic/envs/default/lib/libmonnx.dylib
5e701eae6ff45f5c1966d5307366c4da99218d08  .magic/envs/default/lib/libmonnx.dylib
```

### System information

```shell
- What OS did you do install Mojo on? 
macOS

- Provide Magic CLI version by pasting the output of `magic -V` or `magic --version`
magic 0.4.0 - (based on pixi 0.33.0)
```

**Comment by zbowling** [comment]
Thanks for the bug! 

So for many files every environment in magic is isolated but reuses files that are hard-linked from a central cache directory on your system. The files in your env are actually hardlinks most of the time. Sometimes symlinks and rarely full copies.

This all happens in rattler which is the backing library for magic. It goes through certian fallback logic for creating the best link type when installing a magic into the env from the cache directory (in cases it may fully copy the file but it's pretty rare unless it needs to patch it) https://github.com/conda/rattler/blob/main/crates/rattler/src/install/link.rs#L137 

Unfortunately it's really hard to look up other places on your system a hardlink is shared across folders but you can your rattler cache directory with `magic info` under cache folder to see the global system package cache. The inodes of files in that folder should match match the ones in the local env folder. 

Specifically for the python-x.y/site-packages/ folder and certian dylibs there that are also in the lib/ in your env, it's true that these are fully duplicated currently and don't get properly de-duplicated in the hardlink. This is a known issue that should get resolved in a future update.
