### ISSUE TITLE
[BUG]: Error 'Struct has no testable member' when trying to assign Testable trait.

### ISSUE THREAD

**Issue by RichardCoppin** [modularml/mojo#3841]
### Bug description

Creating the following structure gives an error `Testable_Struct has no testable member`
```mojo
struct Testable_Struct(Stringable, EqualityComparable, Testable):
    var value: Int

    fn __init__(inout self, value: Int):
        self.value = value

    fn __str__(self) -> String:
        return str(self.value)

    fn __eq__(self, other: Self) -> Bool:
        return (self.value == other.value)

    fn __ne__(self, other: Self) -> Bool:
        return (self.value != other.value)
```

From what I can see this struct conforms to the Testable Trait
```mojo
trait Testable(EqualityComparable, Stringable):
    """A trait that a struct should conform to if we do equality testing on it.
    """
    pass
```

### Steps to reproduce
Implement the structure as above:
![image](https://github.com/user-attachments/assets/39b3c944-b1f4-459a-bfa3-fce5a59a011f)
Observe the error as described.

#### Workaround:
If we take out the explicit `Testable` trait, it seems that the structure conforms to the trait:
So, for instance, if I created this very simple test case:
```mojo
from testing import assert_equal

fn test_equality() raises:
    var x: Testable_Struct = Testable_Struct(1)
    var y: Testable_Struct = Testable_Struct(1)
    assert_equal(x, y)

fn main() raises:
    test_equality()
    print('\nAll tests completed.')
```
It works as expected. This suggests that the struct does implicitly conform to `Testable`.

#### Motivation:
Although it kind-of works in this contrived case, I'm getting an error when trying to use `assert_equality(...)` on a more involved structure.
I would like to be able to explicitly conform my structs to `Testable` in order to troubleshoot any issue with those.

### System information

```shell
- What OS did you do install Mojo on ? 
5.15.167.4-microsoft-standard-WSL2
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 24.6.0.dev2024120705 (405d1f52)
- Provide Magic CLI version by pasting the output of `magic -V` or `magic --version` 
magic 0.4.0 - (based on pixi 0.33.0)
```

**Comment by soraros** [comment]
`Testable` is a private trait in the `testing` module. You could copy and paste its definition into your own code.  

That said, the error message was very unhelpful. I would have expected something like "use of unknown trait definition".

**Comment by RichardCoppin** [comment]
> `Testable` is a private trait in the `testing` module. You could copy and paste its definition into your own code.
> 
> That said, the error message was very unhelpful. I would have expected something like "use of unknown trait definition".

@soraros: Thankyou for the reply. 

Just a quick question: I couldn't find anything in the repo which designated `Testable` as a private trait. 

What defines `Testable` as private?

**Comment by soraros** [comment]
It's the other way around, it's not exposed in [`stdlib/src/testing/__init__.mojo `](https://github.com/modularml/mojo/blob/nightly/stdlib/src/testing/__init__.mojo), so, "private".

**Comment by RichardCoppin** [comment]
Thanks that answers my question.
