### ISSUE TITLE
[Feature Request] piping

### ISSUE THREAD

**Issue by OmarAshkar** [modularml/mojo#386]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

```shell
Piping is very useful to chain multiple transformations without nesting. This keeps code readable. In R, there is a native pipe, also there is support for infix functions so developers can make there own a pipes.
```

### What is your motivation for this change?

```shell
Piping is very convenient for scientific computing. There is a native support for piping in R and Julia.
```

**Comment by lattner** [comment]
Hi Omar, at this point we're resisting the urge to add syntactic sugar.  That said, Python and Mojo already allow you to overload operators with dunder methods.
