### ISSUE TITLE
[Feature Request] [proposal] Move everything string-related to a sub-package `/stdlib/collections/string/`

### ISSUE THREAD

**Issue by martinvuyk** [modularml/mojo#3871]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Create a sub-package `/collections/string/` that will contain:
- `string.mojo`
- `string_slice.mojo`
- `format.mojo`
- `_unicode*.mojo`
- `_utf8_validation.mojo`
- `inline_string.mojo`

And eventually we can also add other files taking related functionality out to their own file to un-bloat `string.mojo` and `string_slice.mojo`

### What is your motivation for this change?

More things in `/utils/` are string-related than not

### Any other details?

...

**Comment by JoeLoser** [comment]
The team is all +1 for this, feel free to open a PR if you'd like.  +1 to Owen's comment about ensuring to re-export the public parts.
