### ISSUE TITLE
[Docs] No `parallelForEachN` function found

### ISSUE THREAD

**Issue by armgabrielyan** [modularml/mojo#390]
### Where is the problem?

https://docs.modular.com/mojo/programming-manual.html#mojo-types-are-just-parameter-expressions

### What can we do better?

The section "Mojo types are just parameter expressions" explains parameters in the example of parallel processing by providing the following example.

> For example, the parallel processing library defines the `parallelForEachN` algorithm, which executes a closure N times in parallel, feeding in a value from the context. That value can be of any type:
> 
> ```mojo
> fn parallelize[
>     arg_type: AnyType,
>     func: fn(Int, arg_type) -> None,
> ](rt: Runtime, num_work_items: Int, arg: arg_type):
>     # Not actually parallel: see Functional.mojo for real impl.
>     for i in range(num_work_items):
>         func(i, arg)
> ```

The text tells about a `parallelForEachN` algorithm, yet the code snippet defines a function named `parallelize`. Indeed, the `Functional` module defines the `parallelize` function and there is no `parallelForEachN` function defined in the standard library.

**Comment by lattner** [comment]
Good catch, fixed in next update, thank you!

**Comment by armgabrielyan** [comment]
Thank you!
