### ISSUE TITLE
[Feature Request] support rustlike error unwrapping

### ISSUE THREAD

**Issue by happyearthbytes** [modularml/mojo#395]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

```shell
In order to support early Error returns without requiring the overhead of try/catch or additional if Error, return Error statements by the caller, It would be amazing to have a lightweight syntax similar to rust to get the value out, or return the Error.

https://doc.rust-lang.org/rust-by-example/error/result/enter_question_mark.html#%E2%80%A0
```

### What is your motivation for this change?

```shell
Reduce unnecessary code blocks for a common design paradigm.
```

**Comment by Mogball** [comment]
Mojo already supports automatic error propagation when calling functions that can throw. In fact, Mojo's error representation under the hood is an `ErrorOr<T>` type. This means that just calling at throwing function will automatically try to unwrap the value or return the error up the callstack.
