### ISSUE TITLE
[Feature Request] Variadic `print` has no overload for `object` arguments

### ISSUE THREAD

**Issue by amqndin** [modularml/mojo#397]
### Bug description

```shell
https://i.imgur.com/enmeyKM.png
what does that even supposed to mean, i cant even use print function 
```

### Steps to reproduce

```shell
- write same thing i wrote on screenshot
```

### System information

```shell
%%python
import subprocess
subprocess.Popen(["cat", "/proc/self/cgroup"])
```

**Comment by Mogball** [comment]
Hey, thanks for filing this issue. Next time, please just post the code that doesn't work in the issue itself.

The specific issue here is that `print` with multiple arguments doesn't have an overload when one of the arguments is an `object`.
