### ISSUE TITLE
[BUG]: camelCase instead of snake_case in Mojo documentation

### ISSUE THREAD

**Issue by gryznar** [modularml/mojo#404]
### Bug description

In various places in Mojo documentation, there are names named improperly. As a superset of Python and Python family member, camelCase is discouraged. In various places it is divergency, for example:
`pairTest`, `useStrings` etc.

### Expected
All camelCase names should be replaced with snake_case ones

**Comment by gryznar** [comment]
Sorry, wrong label and I cannot change it. Should be `Documentation`

**Comment by gryznar** [comment]
@abduld There are still some names to fix:
https://docs.modular.com/mojo/programming-manual.html:
-  `usePointer` 
- `parameterOverloads`
- `funWithSIMD`

**Comment by abduld** [comment]
Thanks @gryznar, will fix. We use camelCase as the convention for C++ code at Modular and some folks do not make the context switch when writing Mojo code :)

**Comment by gryznar** [comment]
Yep, I have supposed, that the C++ is the reason 😁

**Comment by gryznar** [comment]
I don't know if it was noticed, but also here: https://docs.modular.com/mojo/notebooks/BoolMLIR.html (`lhsIndex` and `rhsIndex`) are to fix
