### ISSUE TITLE
[Feature Request] Use unsigned bytes for String's buffer

### ISSUE THREAD

**Issue by lsh** [modularml/mojo#420]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Right now, String's data is stored as `DynamicVector[Int8]`, but it should likely be `DynamicVector[UInt8]`.

### What is your motivation for this change?

Signed bytes tend to make users think semantically that they are working with numbers rather than raw data. It's also become increasingly popular to describe raw bytes as just a Vector of unsigned bytes (such as Uint8Array in JavaScript or []const u8 in Zig).

**Comment by abduld** [comment]
Makes sense, although users should not be working directly with the bytes within a string :)

**Comment by lattner** [comment]
+1, the current implementation needs to be improved a bunch.
