### ISSUE TITLE
[BUG]: failed to legalize operation 'pop.string.concat' that was explicitly marked illegal

### ISSUE THREAD

**Issue by mzaks** [modularml/mojo#425]
### Bug description
Following usage of the `__add__` function on `StringLiteral` does not work:

```mojo
fn _print(indentation: StringLiteral):
    print(indentation)
    if len(indentation) < 10:
        _print(indentation + " ")

_print("a")
```

What is curious, if the `_print` function is defined without usage, the compiler does not complain.

**Comment by Mogball** [comment]
Thanks for filing this issue! This is a known problem and is a current limitation being addressed. In the meantime, please use a `String`. Closing in favour of https://github.com/modularml/mojo/issues/100
