### ISSUE TITLE
[Feature Request] Implement `fn to_int(self) -> Int` on `FloatLiteral`

### ISSUE THREAD

**Issue by mojodojodev** [modularml/mojo#428]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

On `FloatLiteral` implement `fn to_int(self) -> Int` the same way it is in `SIMD`, at the moment the only way to do this without MLIR is quite verbose:

```rust
from DType import DType
let x = 5.5
let y = Float64(x).cast[DType.int64]().to_int()
print(z)
```
```
5
```
In the next release I believe [this ticket was resolved](https://github.com/modularml/mojo/issues/402) so will be shorter:

```rust
let y = Float64(x).to_int()
```
But would be even better to be able to do:
```rust
let y = x.to_int()
```
So users don't get frustrated trying to figure out how to do it

### What is your motivation for this change?

There was a user on discord getting frustrated by the inability to do this in an obvious way: https://discord.com/channels/1087530497313357884/1098713601386233997/1125987008045666365

**Comment by gryznar** [comment]
Or maybe just to allow construct Int from FloatLiteral?
Pythonic way to cast type is like:
```python
x: float = 5.5
y: int = int(x)
```
Above works, but with `Int64` / `UInt32` etc. and not with `Int`

**Comment by abduld** [comment]
The pythonic way is to implement the `__index__` dunder method. We should have an index dunder and have to_int support conversion to int. 

btw. one of the reasons why you cannot just write `Int(Float32(4.0))` is because the Int lives in the builtin module while simd (of which Float32 is just an alias) lives in the standard library.

**Comment by gryznar** [comment]
Thanks for the explaination! Is it going to change in the future?

śr., 5 lip 2023, 18:24 użytkownik abdul dakkak ***@***.***>
napisał:

**Comment by abduld** [comment]
@gryznar , yes it will.
