### ISSUE TITLE
[Feature Request] Implicit Conversion of `SIMD[1, bool]` to `Bool`

### ISSUE THREAD

**Issue by mzaks** [modularml/mojo#429]
### Bug description

```shell
I expect function `f1` to compile. Instead the compiler reports:
... cannot implicitly convert 'SIMD[bool, 1]' value to 'Bool' in return value
```

### Steps to reproduce

```shell
from Vector import DynamicVector

fn f1() -> Bool:
    var v1 = DynamicVector[UInt16]()
    let i1: UInt16 = 2
    v1.push_back(i1)
    return i1 == v1[0]
```

**Comment by mzaks** [comment]
I had another issue with a return type coercion, which probably has the same root cause:

```
error: Expression [2]:278:14: cannot implicitly convert 'Tuple[Int, Bool]' value to 'Tuple[SIMD[ui16, 1], Bool]' in return value
    return (0, False)
```

**Comment by Mogball** [comment]
Thanks for filing this issue! This is not specific to return statements. `SIMD[1, bool]` does not have an implicit conversion to `Bool`. Likewise, element-wise implicit conversions are not supported for Tuple at the moment.

**Comment by mzaks** [comment]
Actually `SIMD[1, bool]` does have an implicit conversion to Bool, as following code works:

```
fn f2() -> Bool:
    var v1 = DynamicVector[UInt16]()
    let i1: UInt16 = 2
    v1.push_back(i1)
    if i1 == v1[0]:
        return True
    return False
```

It seems like the conversions in an `if` predicate part applies.

**Comment by Mogball** [comment]
That conversion context is special because it invokes the `__bool__` dunder method. In all other contexts, like `let x: Bool = simdBool`, the conversion will fail as well.

**Comment by acinnes** [comment]
I've encountered the same issue without even explicitly using arrays. The following code (taken from a Programming Manual example but just changing one of the Int variables to Float64) triggers the same compiler error.

```
struct MyPair:
    var first: Int
    var second: Float64

    # We use 'fn' instead of 'def' here - we'll explain that soon
    fn __init__(inout self, first: Int, second: Float64):
        self.first = first
        self.second = second

    fn __lt__(self, rhs: MyPair) -> Bool:
        return self.first < rhs.first or
              (self.first == rhs.first and
               self.second < rhs.second)
```
