### ISSUE TITLE
[Feature Request] Braces as an optional way for indentation

### ISSUE THREAD

**Issue by southerndevz** [modularml/mojo#438]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

```shell
Please add an optional syntax to have braces instead of indentation, if possible.
```

### What is your motivation for this change?

```shell
They enhance readability and help in things like nested loops.
```

**Comment by gryznar** [comment]
Chris explained that very well in Lex Fridman podcast. Code with braces is also intendent by the formatter, so why keep both braces and indentation?

In my opinion code without braces is cleaner and prettier.

**Comment by lattner** [comment]
We're building a superset of python, not a different language.  Python style indentation is core to what we're building here :)

**Comment by southerndevz** [comment]
The justification for not building a new language holds no ground since isn’t working since we now have `fn`, `let`, and `var` 😅😂
Anyway, I thought it was going to be a simple thing as “semicolon or no semicolon.” Indents without braces can get tricky when dealing with elaborate decision trees. Sometimes you wouldn’t know if the operation is from a nested else-if or from the one previous to it, it comes a nightmare! Braces allow us to hover over the closing brace and see which branch it comes from. Indentation only doesn’t do that properly.

**Comment by mojodojodev** [comment]
Hi @southerndevz those are all really good points, it's just a question of tradeoffs, Chris gives a really [good detailed justification here](https://youtu.be/pdJQ8iVTwj8?t=770) to their decision if you haven't seen it.

**Comment by southerndevz** [comment]
I love when he said, its polarizing. I sometimes believe in writing code from notepad or Notepad++ as an alternative to VS Code “bloatware”. Braces can decouple a programmer from being dependent on IDE formatters. Chris didn’t give a convincing statistically based answer, he said he believes that not many have made errors because of indents. Try running a quick Python script in the Terminal. You’ll pull your hair out wondering what you did wrong. 😅😂 But the primary motivating factor are ambiguous descion-trees, loops, continues and try-catches.
