### ISSUE TITLE
[Docs] Minor typo in BuiltinSlice

### ISSUE THREAD

**Issue by daviddorf2023** [modularml/mojo#440]
### Where is the problem?

https://docs.modular.com/mojo/MojoBuiltin/BuiltinSlice.html

### What can we do better?

In the definition of __len__ : "Return the lenght of the slice.", change to "length"

**Comment by akirchhoff-modular** [comment]
Thanks for the report. I am fixing this and a couple of other typos I found. I expect the typos to be fixed at the next Playground release.
