### ISSUE TITLE
[Docs] Intro notebook suggests variable name typos are handled

### ISSUE THREAD

**Issue by joshtriplett** [modularml/mojo#442]
### Where is the problem?

https://playground.modular.com/user/josh@joshtriplett.org/lab/tree/HelloMojo.ipynb

### What can we do better?

> Exactly like Python you can assign values to a name and it implicitly creates a
function-scope variable within a function. This provides a very dynamic and
easy way to write code, but it also creates a challenge for two reasons:
>
> 1) Systems programmers often want to declare that a value that is immutable.
> 2) Systems programmers want to get an error if they mistype a variable name in an assignment.
>
> To support this, Mojo supports `let` and `var` declarations, which introduce a
new scoped runtime value: `let` is immutable and `var` is mutable. These
values use lexical scoping and support name shadowing:

However, this doesn't make it clear *how* `let` and `var` do anything to catch typos in variable names.

For instance, this code compiles and runs with no errors or warnings:

```
var myvarname = 42
myvarnome = 43
myvarname += 100
print(myvarname)
```

If there's something that mojo does to catch typos, this seems like a good place to either mention or link to it. If mojo *isn't* actually doing something to catch typos (because of the tradeoff with Python compatibility), then it shouldn't mention that as a selling point of `let`/`var` here.

**Comment by lattner** [comment]
Agreed, we should clarify this to talk about within an 'fn'.  In a 'def', you get implicit variable definition.
