### ISSUE TITLE
Ability to use on Google cola 

### ISSUE THREAD

**Issue by sr5434** [modularml/mojo#45]
## Request

The ability to use mojo in Google Colab once Mojo reaches general availability.

### Motivation

Many ML enthusiasts use Google Colab to train their models. They can benefit from the code speedups that come with using Mojo.

### Description and Requirements

Users should be able to download Mojo in Colab and use it without issue.

**Comment by lattner** [comment]
Cool, it would be great to see this as mojo matures!  Right now we are using this bug tracker for language and compiler bugs, so I’m going to close this for now.  Thank you!

**Comment by sr5434** [comment]
Oh, ok

**Comment by OtwellResearch** [comment]
Not only would developers benefit from a Mojo Colab - Google would benefit because the training wouldn't take as long. ;) Or is that true? Would Mojo improve GPU performance?

**Comment by sr5434** [comment]
I’m not completely sure, but things like function autotuning might help improve performance.

**Comment by BrunoArsioli** [comment]
I am looking forward a way to test Mojo in Colab, but I guess this will come when Mojo becomes Open Source. For now, it seems the Modular playground is the only way to test Mojo (but it seems that the Python libraries we can import there, are limited). Does anyone has a timeline for Mojo being open source? 

maybe we need to report the issue as  "

!pip install mojo       

is not working in Gogle Colab  " : )  See the error report: 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting mojo
  Using cached mojo-0.1-py3-none-any.whl (9.8 kB)
Requirement already satisfied: appdirs in /usr/local/lib/python3.10/dist-packages (from mojo) (1.4.4)
Collecting docopt (from mojo)
  Using cached docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from mojo) (1.22.4)
INFO: pip is looking at multiple versions of mojo to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement os (from mojo) (from versions: none)
ERROR: No matching distribution found for os

**Comment by sr5434** [comment]
Lol. It looks like the package was a hackathon project from a few years back. Maybe the pip package(if one is ever released) should be called mojo-lang.
