### ISSUE TITLE
[BUG]: Inconsistent behavior in terms of using variable after passing ownership 

### ISSUE THREAD

**Issue by gryznar** [modularml/mojo#450]
### Bug description

According to HelloMojo.ipynb this code:
```mojo
from String import String

fn set_fire(owned text: String) -> String:
    text += "🔥"
    return text

fn mojo():
    let a: String = "mojo"
    let b = set_fire(a^)
    print(a)
    print(b)

mojo()
```

should produce an error:
```bash
error: Expression [2]:12:23: value 'a' cannot be consumed, because it is used later
    let b = set_fire(a^)
                      ^
```

but in reality, error is:
```bash
error: Expression [6]:13:10: use of uninitialized value 'a'
    print(a)
         ^

Expression [6]:11:5: 'a' declared here
    let a: String = "mojo"
    ^
```

I am not sure if it intendent change and documentation is outdated or it is a classical bug

### Steps to reproduce

1. Follow advice in HelloMojo.ipynb and pass ownership of `a` to `let b = set_fire(a)` via `a^`
```mojo
from String import String

fn set_fire(owned text: String) -> String:
    text += "🔥"
    return text

fn mojo():
    let a: String = "mojo"
    let b = set_fire(a)
    print(a)
    print(b)

mojo()
```
2. Execute

**Comment by gryznar** [comment]
P.s. allowing markdown via this pr for example: https://github.com/modularml/mojo/pull/296 would be very helpful!

**Comment by lattner** [comment]
@scottamain seems like a doc issue, because the compiler behavior changed.  Maybe we should make the doc be less concrete about the specific error message and more about the problem?

**Comment by scottamain** [comment]
I also noticed that this changed and was thinking the same thing.

**Comment by scottamain** [comment]
Thanks for reporting this, it will be fixed in our next release.
