### ISSUE TITLE
[Feature Request] In `struct` and `fn` use only Mojo syntax

### ISSUE THREAD

**Issue by redradist** [modularml/mojo#452]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?
I suggest to use Mojo syntax with all static types only in Mojo context ...
What I mean by that ?!

Use in `fn` only variables with `let`, `var` (other static syntax) and in `struct` functions with `fn`.
If user want more dynamic behavior, it could mix and match it in `class`

### What is your motivation for this change?
For example:
```python
struct Notebook2:
    def login(self, name): # SHOULD BE COMPILER ERROR, DYNAMIC PYTHON FUNCTION IS NOT ALLOWED IN MOJO STRUCT
        pass

    fn password(self, password): # It is Okay
        pass

class Notebook:
    def login(self, name): # It is Okay
        pass

    fn password(self, password): # It is Okay
        pass
```

Currently in Mojo, `def` could be extended with `let` variables and `fn` cannot be extended with variable not declared using `let`.

This mean that going from dynamic to static is allowed, but from static to dynamic is allowed only for `struct` with dynamic functions like `def`. Such behavior make language inconsistent.

I suggest do not allow dynamic behavior for `fn` (already working) and `struct` (not working because `struct` allow to define dynamic function with dynamic behavior `def`)

**Comment by gryznar** [comment]
I am against for this feature because of at least few reasons:
1. Global scope. If that will be accepted also global scope will be affected. If I am not wrong this is bad because of:
- performance - If I am understanding correctly strict types, control over data etc may be very profitabable for the compiler which may perform most advanced optimizations and thus increase speed of execution
-stability and control - specifying types and controlling mutability etc. could make a compiler a helper which will catch bugs related to passing wrong types / mutating variable which should be immutated etc.
2. At least for me - lack of real and significant benefits in this 2-way migration

Mojo is much faster than CPython and allows for a much more fancy stuff.  So natural way of migration is Python -> Mojo. What are the benefits from the opposite one?

**Comment by gryznar** [comment]
One more point to add here, because that was not pointed. Global scope in my opinion should be  be still a mix of that. It has to be dynamic (because of Python compatibility), but disallowing here `fn`, `let` and `var` looks for me like a regression comparing to current behavior

**Comment by redradist** [comment]
@gryznar 
> One more point to add here, because that was not pointed. Global scope in my opinion should be be still a mix of that. It has to be dynamic (because of Python compatibility), but disallowing here `fn`, `let` and `var` looks for me like a regression comparing to current behavior in terms of control and possible optimizations by the compiler

I just request to not allow dynamic behavior in static context, but allow static behavior in dynamic context

**Comment by gryznar** [comment]
Title is in wrong form after changes. I would like to see it like:
"In struct and fn allow only Mojo syntax"
🙃

**Comment by gryznar** [comment]
> Use in `fn` only variables with `let` 

I am not sure if you are proposing via this statement disallowing `var`? It could be a hell for loop which mutates variable by each iteration.

**Comment by redradist** [comment]
@gryznar 
> > Use in `fn` only variables with `let`
> 
> I am not sure if you are proposing via this statement disallowing mutation of argument via `var`? It could be a hell for loop which mutates variable by each iteration.

No, I mean to use in `fn` any new static syntax like (`let`, `var` and etc.)

**Comment by gryznar** [comment]
> @gryznar 
> > > Use in `fn` only variables with `let`
> > 
> > I am not sure if you are proposing via this statement disallowing mutation of argument via `var`? It could be a hell for loop which mutates variable by each iteration.
> 
> No, I mean to use in `fn` any new static syntax like (`let`, `var` and etc.)

So it has to be precised. Mentioning only `let` leads to another confusion

**Comment by lattner** [comment]
I can see how this might avoid some accidental use of dynamic behavior, but I'm not sure why that is something we're worried about.  Further, there are other issues - we need to support top level code and other things that aren't tied to an fn keyword. Furthermore, we want constrained dynamic classes as well (Jeff will share a doc hopefully ~this week about this) in Mojo that aren't as dynamic as Python's

At the end of the day, we also want fn and def to be friends and get along and allow intermixing.  This is a pretty important design principle - we don't want "fn to be mojo" and "def to be legacy python code", so I see this approach working...
