### ISSUE TITLE
Why is this not open source?

### ISSUE THREAD

**Issue by tibrezus** [modularml/mojo#470]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Why is this not open source?

### What is your motivation for this change?

Why is this not open source?

### Any other details?

Why is this not open source?

**Comment by gryznar** [comment]
There is a FAQ or Discussion for such question

**Comment by lattner** [comment]
This is in the faq:
https://docs.modular.com/mojo/faq.html#distribution
