### ISSUE TITLE
Rename/Alias `fn` to `sdef`

### ISSUE THREAD

**Issue by phacic** [modularml/mojo#477]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

strict function definition keyword, `fn` could be renamed or aliased as `sdef` since by definition it is just a `strict def`

### What is your motivation for this change?

Readability

**Comment by lattner** [comment]
Let's track this under https://github.com/modularml/mojo/issues/453 thanks!
