### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by GH05T-HUNTER5** [modularml/mojo#491]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Are you doing more work for this community?

### What is your motivation for this change?

Only if you work more for this community your program will reach more people.Many of my friends don't even know that there is language in a program like this.

### Any other details?

Today you can do more for your community by creating various types of documentation, publishing videos, and creating PDF files.

**Comment by gryznar** [comment]
This is topic to discussion. Feature request is only fo request certain features, not for asking general questions.
