### ISSUE TITLE
[Feature Request] Add int rotation methods

### ISSUE THREAD

**Issue by lsh** [modularml/mojo#499]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

I would like the following methods added to `SIMD[T, N]`:
```
fn rotate_bits_left(self, by: Int) -> Self
fn rotate_bits_right(self, by: Int) -> Self
fn rotate_left(self, by: Int) -> Self
fn rotate_right(self, by: Int) -> Self
```

It would behave as:
```
(0x10000b3).rotate_bits_left(8) # => 0xb301
SIMD[DType.uint8, 4](1, 0, 1, 1).rotate_left(1) # => [0, 1, 1, 1]
```

### What is your motivation for this change?

Left rotation is a pretty common low level feature and used in several cryptographic algorithms.
[Rust example](https://doc.rust-lang.org/std/primitive.u32.html#method.rotate_left)
[Zig example](https://github.com/ziglang/zig/blob/014d88ef657e1736a36e92b0a5b0c650db9e5091/lib/std/math.zig#L634)

**Comment by abduld** [comment]
Thanks @lsh for the suggestion. We have incorporated that into the stdlib and it will be available in the next rollout.
