### ISSUE TITLE
[BUG] Int to String conversion is incorrect and can crash

### ISSUE THREAD

**Issue by mojodojodev** [modularml/mojo#50]
## Bug Description
When casting a value to a different type that alters its representation, if the original identifier is used again, the value of the new identifier will be as expected when printed alone. However, when printing it alongside another value, it will display the modified value from the initial cast.

### Steps to Reproduce
On the playground:
```mojo
from DType import DType

let a: UI64 = 999999999999
let b = a.cast[DType.ui32]()
let c = a.to_int()

print(c)
print("c:", c)
print(a, c)
```
### Returns
```
999999999999
c: -727379969
999999999999 -727379969
```

**Comment by mojodojodev** [comment]
Also to add to this when testing the `Time` module it has similar behavior:

```mojo
from Time import now
let x = now()
print(x)
print("x nanoseconds:", x)
```
Results in:
```
99660240219786
x nanoseconds: -180916598
```
But wrapping in UI64 fixes it:
```
let x = now()
print(x)
print("x nanoseconds:", x)
```
100303272372197
x nanoseconds: 100303272372197

Also what epoch is now() nanoseconds referring to? If I convert it to hours it's 27.683400061051668

**Comment by hoxha-saber** [comment]
Note that if you try to fit `99660240219786` into a 32 bit signed integer you will get `-180916598`. Likewise fitting 999999999999 into a 32 bit signed int gives -727379969.  So then I guess what is happening is that somewhere there is a narrowing cast from unsigned 64bit to signed 32 bit leading to the bug.

My guess is that the correct type isn't being propagated.  As a side question, is there any way in Mojo to print the exact type of an identifier? For example, can we do something like:
```
print(typeof(c)) // would print "Int" or something
```
Of course, the vscode extension would have this information for us so it wouldn't really be needed but I think in this particular case it is interesting to know what the compiler actually thinks the type of `c` is here.

**Comment by Mogball** [comment]
```python
let b = a.cast[DType.ui32]()
```

This is a narrowing cast. `Int` is platform pointer width, so 64 bits in this case. This is intended behaviour.

However, the Int to String conversion backing variadic print is incorrect. Also, the following code crashes


```python
print(9223372036854775806, 1)
```

This is not just a playground problem FYI @abduld

**Comment by deveusss** [comment]
typeof not working in mojo @hoxha-saber
