### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by MistrzHieroglif** [modularml/mojo#505]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

What about operator defining that we using reference, object or copy?
in ex (python)

def some_function(something):
     print(something)
     
some_function(&variable) -> passes always value
some_function(#variable) -> passes always reference
some_function(^variable) -> passes always copy

It would be useful and readable to let user explicity define type of parametr pasing

### What is your motivation for this change?

Python issues

**Comment by drunkwcodes** [comment]
What's that?

Why &variable -> passes always value, not reference?

Are you kidding?

**Comment by tsvel** [comment]
How I understand this error

**Comment by gryznar** [comment]
1. Probably newest entry in changelog will address your request: https://docs.modular.com/mojo/changelog.html#section
2. In this area is missing title of this request:
![image](https://github.com/modularml/mojo/assets/90425096/d578cdd5-9ffc-4200-835e-df3a45d17072)

Should be: "[Feature Request] Title of request"

**Comment by gryznar** [comment]
> How I understand this error
> 
> error: Expression [1]:17:5: use of unknown declaration 'App' App TextEditorApp { ^~~
> 
> error: Expression [1]:17:9: statements must start at the beginning of a line App TextEditorApp { ^
> 
> expression failed to parse (no further compiler diagnostics)

This question is not related to this issue. Please create separate ticket in discussion

**Comment by tsvel** [comment]
How I understand this error 

OK, sir thanks
