### ISSUE TITLE
[Feature Request] DType info methods

### ISSUE THREAD

**Issue by lsh** [modularml/mojo#51]
A few DType methods would be nice such as:
* `min_number[T: DType]() -> Int`
* `max_number[T: DType]() -> Int`
* `bits[T: DType]() -> Int`
* `infinity[T: DType]() -> SIMD[T, 1]` for floating point types
* `nan[T: DType]() -> SIMD[T, 1]` for floating point types

**Comment by jayant-01** [comment]
hello, @lsh what we have to do here?

**Comment by lsh** [comment]
@jayant-01 What I'm asking for amounts to just defining a few constants, kind of like [the C numeric limits](https://en.cppreference.com/w/cpp/types/climits) or the (associated constants on Rust types)]https://doc.rust-lang.org/std/primitive.i32.html#associatedconstant.MIN]. Ideally it would also work for `Int` and `FloatLiteral`. One point to hash out is the actual API, since I think something like `min_number[T: DType]() -> SIMD[T, 1]`, which would in that case return the lowest possible value for the given `DType`.

**Comment by jayant-01** [comment]
ook @lsh i understand it,

so basically we have a creat like a function which will return the lowest value in a list or any other dataset

**Comment by jayant-01** [comment]
Am i right??

**Comment by jayant-01** [comment]
hello @lsh did i get it wrong please rectify ?

**Comment by lattner** [comment]
I think the request here is pretty straight-forward and logical.  @abduld can you route this appropriately?

**Comment by jayant-01** [comment]
@lsh currently I don't have the access to Mojo playground so  first let me  have the permission then I can work on this.

Is that will be okay?

**Comment by abduld** [comment]
This makes perfect sense. One thing is that there are function like inf, nan, and neg_inf that are in the stdlib. Thanks for the suggestion to complete adding the numeric traits functions

**Comment by Mogball** [comment]
Fixed in latest release
