### ISSUE TITLE
[Feature Request] Support for macOS

### ISSUE THREAD

**Issue by goldiegadde** [modularml/mojo#510]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Tracking issue for supporting Mojo on macOS. 
Please upvote if you want to see macOS support so that we can prioritize accordingly. 

### What is your motivation for this change?

support additional hardware/OS.

**Comment by jeremyforan** [comment]
Would it help the process if I bought the team a round of coffee/Cocoa? Cocoa has been known to help with Mac development.

**Comment by annemarietannengrund** [comment]
you mean the goat blood didn't work?

**Comment by wafwoof** [comment]
Can't use mojo in any meaningful way currently because of lack of OS support. Would love to see more attention to this issue. 😒

**Comment by ematejska** [comment]
This is in progress :)

**Comment by lattner** [comment]
Can confirm: this is a top priority :)

**Comment by coolcoder613eb** [comment]
Status?

**Comment by gryznar** [comment]
Modular mentioned on its Tweeter, that it will be shipped till the end of October

**Comment by annemarietannengrund** [comment]
![grafik](https://github.com/modularml/mojo/assets/84636352/cac77ef1-7368-4279-ab35-9a5652cff1a4)

**Comment by jeremyforan** [comment]
Where do I send the thank you coffees?

**Comment by annemarietannengrund** [comment]
🔥 Mojo installed! 🔥

Thank you guys!

**Comment by andrewssobral** [comment]
Thank you guys, working like a charm on my M1 🔥

**Comment by jeremyforan** [comment]
Thanks team!

**Comment by Moosems** [comment]
Is it safe to assume Mac Intel support is also around the corner?

**Comment by jackcooperusesvim** [comment]
It looks like they just added intel too. For some reason my M1 won't run the "modular install mojo" command due to some auth thing but others seem to be able to get that working.

**Comment by andrewssobral** [comment]
@jackcooperusesvim I had the same issue, you will find the auth token on the Manual installation steps, screenshot below

![image](https://github.com/modularml/mojo/assets/483114/ec272ffb-b0b4-4756-b7fa-761ae9260113)

**Comment by jackcooperusesvim** [comment]
I might open another issue on this. I put the auth command above the modular install mojo commnand and it still didn't work. I might just set up another account to try again.
<img width="641" alt="Screen Shot 2023-10-19 at 10 40 07 AM" src="https://github.com/modularml/mojo/assets/43050254/7d20b94d-d2e6-4462-aa94-78535f00588e">

**Comment by andrewssobral** [comment]
@jackcooperusesvim try:
```
modular clean
modular auth $TOKEN
modular install mojo
```

**Comment by jackcooperusesvim** [comment]
No change

**Comment by andrewssobral** [comment]
@jackcooperusesvim weird...no idea 😕

**Comment by jeremyforan** [comment]
FYI: I had an issue when I copied and pasted the install command directly from the web. I used a text editor to make it a single line, which worked.

**Comment by Moosems** [comment]
> It looks like they just added intel too. For some reason my M1 won't run the "modular install mojo" command due to some auth thing but others seem to be able to get that working.

<img width="620" alt="Screen Shot 2023-10-19 at 11 11 28 AM" src="https://github.com/modularml/mojo/assets/95927277/35086ac0-9004-4db6-ae96-3528c71da6a8">

**Comment by jackos** [comment]
Closing now that this is now that macOS has launched on Apple Silicon thanks all, I've raised this separate ticket for Intel based Macs, so we can gauge interest for that: https://github.com/modularml/mojo/issues/1092
