### ISSUE TITLE
[BETA]: Typo in the welcome message.

### ISSUE THREAD

**Issue by aregm** [modularml/mojo#512]
### Bug description

Typo in the install welcome message "For info about this tool, type "modular -help". Should be "--help", though singular dash also works, but is not listed in the help message.

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install modular CLI/mojo on ?
WSL Ubuntu 22.04

- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by guidorice** [comment]
All the cli options/args seem to accept either single `-` or double `--`. 🤷🏽

**Comment by modocache** [comment]
Thanks for the report! While both `-help` and `--help` are valid spellings, I agree with you that the installer should probably print `--help` with two dashes. I'll change this as you suggest, thanks!

**Comment by modocache** [comment]
This will be updated in our next release of the `modular` tool. Thanks!
