### ISSUE TITLE
[BETA]: Failed to install snap from behind a VPN.

### ISSUE THREAD

**Issue by aregm** [modularml/mojo#513]
### Bug description

$ modular install mojo
> #Found release for https://packages.modular.com/mojo @ 0.2.0, installing to /home/user/.modular/pkg/packages.modular.com_mojo
modular: error: failure detected - please run `modular clean` and try again
==========================
Failure Information:
        - http error: failed to reach URL https://cas.modular.com/0/XXXXXXXXXXXXX with cURL error Timeout was reached - Looking for XXXXXXXXXXXXXXX
        - http error: failed to reach URL https://cas.modular.com/0/XXXXXXXXXXXXX with cURL error Timeout was reached - Looking for XXXXXXXXXXXXXXX
==========================

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- Fire on Cisco VPN or Global Protect 
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install modular CLI/mojo on ?
WSL Ubuntu 22.04.2 LTS
- Provide version information for Mojo by pasting the output of `mojo -v`
version 1.0.0+601
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.1.1
```

**Comment by guidorice** [comment]
Pretty sure mojo is not at version `1.0.0+601`?!
 What is the output of this command? 
 
 ```
 file $(which mojo)
 ```

**Comment by jackos** [comment]
Hi @aregm thanks for raising, we have a fix for this and will be releasing it soon

**Comment by aregm** [comment]
> Pretty sure mojo is not at version `1.0.0+601`?! What is the output of this command?
> 
> ```
> file $(which mojo)
> ```

I couldn't install Mojo, so there is only modular exec, not Mojo. It was the version from Snap search, that brought the mojo CD for Juju, which mistakenly assumed to be Modular mojo. Please disregard that comment.

**Comment by jackos** [comment]
Hi @aregm can you please try running:
```bash
modular clean
rm -r $MODULAR_HOME
sudo apt-get install modular
modular install mojo
```
And it should now work, will reopen if you have any further issues

**Comment by aregm** [comment]
Ack. There was a pip error on 'externally-managed-environment'. Worked after a hack - removing /usr/lib/python3.11/EXTERNALLY_MANAGED, but I guess there is some discrepancy between installation docs and actual actions.

**Comment by jackos** [comment]
> Ack. There was a pip error on 'externally-managed-environment'. Worked after a hack - removing /usr/lib/python3.11/EXTERNALLY_MANAGED, but I guess there is some discrepancy between installation docs and actual actions.

OK thanks I haven't tried WSL with the latest SDK, I'll see if I can reproduce
