### ISSUE TITLE
[BETA]  mojo matmul.mojo 

### ISSUE THREAD

**Issue by guidorice** [modularml/mojo#515]
### Bug description

The matmul.mojo example program does not return the expected output, and prints 

> An error occurred in Python.

### Steps to reproduce

```
@guidorice ➜ /workspaces/mojo/examples (main) $ mojo matmul.mojo 
Throughput of a 128x128 matrix multiplication in Python: 
An error occurred in Python.
Throughput of a 512x512 matrix multiplication in Mojo using a naive algorithm: 
5.486891495394973 GFLOP/s <> -9223372036854775808 x speedup over Python
Throughput of a 512x512 matrix multiplication in Mojo using vectorization: 
29.406540250582058 GFLOP/s <> -9223372036854775808 x speedup over Python
Throughput of a 512x512 matrix multiplication in Mojo using the stdlib `vectorize`: 
24.141552979977298 GFLOP/s <> -9223372036854775808 x speedup over Python
Throughput of a 512x512 {vectorized + parallelized} matrix multiplication in Mojo: 
2.7173885207260922 GFLOP/s <> -9223372036854775808 x speedup over Python
Throughput of a 512x512 {tiled + vectorized + parallelized} matrix multiplication in Mojo: 
2.9034890049746509 GFLOP/s <> -9223372036854775808 x speedup over Python
Throughput of a 512x512 {tiled + unrolled + vectorized + parallelized} matrix multiplication in Mojo: 
2.8672076606454677 GFLOP/s <> -9223372036854775808 x speedup over Python
```

PS first impression is it's looking really awesome. Very responsive, lightweight binaries, great CLI interface, repl, help msg. 👍🏽

### System information

- What OS did you do install modular CLI/mojo on ?

On a github workspace, 32GB instance.

```
@guidorice ➜ /workspaces/mojo/examples (main) $ mojo deviceinfo.mojo 
System information: 
    OS          :  linux
    CPU         :  znver3
    Arch        :  x86_64-unknown-linux-gnu
    Num Cores   :  8
    CPU Features:  avx2
```

- Provide version information for Mojo by pasting the output of `mojo -v`

mojo 0.2.0 (4c0ef274)

- Provide Modular CLI version by pasting the output of `modular -v`

modular 0.1.1

**Comment by shashankprasanna** [comment]
Hi @guidorice thank you for reporting!
Unfortunately we've hardcoded alias test_dir = "/root/mojo-examples"
Please change it to alias test_dir = "." or the directory from which you're running mojo matmul.mojo

**Comment by dualvtable** [comment]
Thanks for reporting - we will fix, but please follow the work-around that @shashankprasanna suggested.

**Comment by guidorice** [comment]
That worked- thanks!
