### ISSUE TITLE
[BUG] "no viable expansions found" for sin of SIMD with size > 32

### ISSUE THREAD

**Issue by rho-novatron** [modularml/mojo#52]
## Bug Description

Calling Math.sin on SIMD[DType.f32, 64] throws an "error: Expression [7]:7:1: no viable expansions found", whereas Math.sin on SIMD[DType.f32, 32] returns the sine of the arguments.

### Steps to Reproduce

`sin(SIMD[DType.f32, 64].splat(0))` throws an error, but `sin(SIMD[DType.f32, 32].splat(0))` works.

### Context

11:hugetlb:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod4b4f9d95_3f64_4c2d_9065_61c1abf7a6bd.slice/cri-containerd-33caf9d762db3022d2f3fe5fdfdd12bbcf87af0830ed4bc6de8dde33c98df6ff.scope
10:cpuset:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod4b4f9d95_3f64_4c2d_9065_61c1abf7a6bd.slice/cri-containerd-33caf9d762db3022d2f3fe5fdfdd12bbcf87af0830ed4bc6de8dde33c98df6ff.scope
9:devices:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod4b4f9d95_3f64_4c2d_9065_61c1abf7a6bd.slice/cri-containerd-33caf9d762db3022d2f3fe5fdfdd12bbcf87af0830ed4bc6de8dde33c98df6ff.scope
8:memory:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod4b4f9d95_3f64_4c2d_9065_61c1abf7a6bd.slice/cri-containerd-33caf9d762db3022d2f3fe5fdfdd12bbcf87af0830ed4bc6de8dde33c98df6ff.scope
7:freezer:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod4b4f9d95_3f64_4c2d_9065_61c1abf7a6bd.slice/cri-containerd-33caf9d762db3022d2f3fe5fdfdd12bbcf87af0830ed4bc6de8dde33c98df6ff.scope
6:cpu,cpuacct:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod4b4f9d95_3f64_4c2d_9065_61c1abf7a6bd.slice/cri-containerd-33caf9d762db3022d2f3fe5fdfdd12bbcf87af0830ed4bc6de8dde33c98df6ff.scope
5:perf_event:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod4b4f9d95_3f64_4c2d_9065_61c1abf7a6bd.slice/cri-containerd-33caf9d762db3022d2f3fe5fdfdd12bbcf87af0830ed4bc6de8dde33c98df6ff.scope
4:net_cls,net_prio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod4b4f9d95_3f64_4c2d_9065_61c1abf7a6bd.slice/cri-containerd-33caf9d762db3022d2f3fe5fdfdd12bbcf87af0830ed4bc6de8dde33c98df6ff.scope
3:pids:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod4b4f9d95_3f64_4c2d_9065_61c1abf7a6bd.slice/cri-containerd-33caf9d762db3022d2f3fe5fdfdd12bbcf87af0830ed4bc6de8dde33c98df6ff.scope
2:blkio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod4b4f9d95_3f64_4c2d_9065_61c1abf7a6bd.slice/cri-containerd-33caf9d762db3022d2f3fe5fdfdd12bbcf87af0830ed4bc6de8dde33c98df6ff.scope
1:name=systemd:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod4b4f9d95_3f64_4c2d_9065_61c1abf7a6bd.slice/cri-containerd-33caf9d762db3022d2f3fe5fdfdd12bbcf87af0830ed4bc6de8dde33c98df6ff.scope
0::/

**Comment by Mogball** [comment]
We... haha..., have an instantiation limit, and so anything that does unrolling is going to easily hit it. It will be raised in the next release (slightly), but it is a known issue that we should not be using parameters to do unrolling. Eventually we might just make the limit arbitrarily high. I will close this as "fixed" in the next release but we're moving to a better long-term solution.
