### ISSUE TITLE
[BUG] Documentation links do not direct to actual section in html page

### ISSUE THREAD

**Issue by ksandvik** [modularml/mojo#527]
### Bug description

Documentation links do not direct to actual section in html page

### Steps to reproduce

Click on the link icon in documentation such as  the alias: named parameter expressions on the page https://docs.modular.com/mojo/programming-manual.html that has https://docs.modular.com/mojo/programming-manual.html#alias-named-parameter-expressions as the link

Expected result, browser (Safari in my case) scrolls to the location when clicking on the page.
Current result: Link goes to top part of the document

### System information

```shell
MacOSX 13.5.1, Safari 16.6.
```

**Comment by lattner** [comment]
@scottamain fyi

**Comment by scottamain** [comment]
I cannot reproduce this issue, so need some more information. 

If I understand correctly, @ksandvik , you're saying that, when you (left-)click on the chain-link icon next to this heading, the page scrolls to the top of the page?
![Screenshot 2023-08-28 at 1 04 21 PM](https://github.com/modularml/mojo/assets/1672461/d88dd88f-d4e7-4d96-8dd8-83007ac3d8b1)

I assume this happens for all headings on the page, not just that one link?
If so, can you please tell me if it also happens to you when clicking the header links on this website?
https://quarto.org/docs/get-started/hello/jupyter.html#code-cells

**Comment by ksandvik** [comment]
<img width="956" alt="iDB" src="https://github.com/modularml/mojo/assets/9701765/c03b9187-3a77-4570-b485-975d481e562a">
See screnshot, shows the Safari browser address and what is shown when that address was requested.

**Comment by Mogball** [comment]
fyi @scottamain

**Comment by scottamain** [comment]
Thanks @ksandvik. I think this could be a bug with the Quarto tool we use to generate the docs, but I cannot reproduce it. Can you please tell me if it also happens to you when clicking the header links on this website?
https://quarto.org/docs/get-started/hello/jupyter.html#code-cells

**Comment by ksandvik** [comment]
That link worked. Sorry I can't help out with a better workflow how to trigger this. Maybe it's Safari related?

**Comment by ksandvik** [comment]
I tried some other Link icon entries in https://docs.modular.com/mojo/notebooks/HelloMojo.html, they all have the #<title> entry in the url, but if you copy that to another window, the loading goes always to the top of the Hellomojo.html page. Actually it works in Chrome, oh well.

**Comment by scottamain** [comment]
> That link worked. Sorry I can't help out with a better workflow how to trigger this. Maybe it's Safari related?

Thanks @ksandvik , I just want to be sure about this: Did you try clicking the anchor icon on the other headings [on that page](https://quarto.org/docs/get-started/hello/jupyter.html)? For example, does it work as expected if you click on the anchor for "Rendering" or "Authoring"?

**Comment by ksandvik** [comment]
<img width="325" alt="iDB" src="https://github.com/modularml/mojo/assets/9701765/3703fb55-3d40-4a5a-9cba-3971e59ee96d">
Here's an ex, click on this one and only link will not go anywhere as the safari web position is there already but the link in the address field will change. Copy this and paste to another window (simulating let's say getting a link from an email or discussion board). Loading that link will load the top part of the page, not the section. 

But as mention, this might be a Safari issue, or (then again) Chrome is using something non HTML standard stuff.

**Comment by scottamain** [comment]
@ksandvik I'm quite sure I understand the problem. I'm trying to narrow-down the point of failure: Please try to reproduce the problem here: https://quarto.org/docs/get-started/hello/jupyter.html#code-cells When on that page, does the same problem occur if you click on the anchor for "Rendering" or "Authoring"?

**Comment by ksandvik** [comment]
<img width="552" alt="iDB" src="https://github.com/modularml/mojo/assets/9701765/f51d55c8-2248-43cf-abaf-5d9ecbf3f019">
See screenshot, only one icon.

**Comment by scottamain** [comment]
Thanks @ksandvik but that did not answer my question. What happens when you click that link icon or copy-paste it into a new window?

**Comment by ksandvik** [comment]
Interesting, seems to work now, click on icon does not move (expected), copy link to other browser window, execute, move to the location, title not shown unless scrolling up one line but that's OK. Feel free to close.

**Comment by scottamain** [comment]
Okay thanks so much for all the follow-up on this!
