### ISSUE TITLE
[Feature Request] Introduce `math.bits.rotate_{left,right}`

### ISSUE THREAD

**Issue by lsh** [modularml/mojo#528]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

In `math.bits` add the following methods:
```
fn rotate_left[T: DType](value: SIMD[T, 1]) -> SIMD[T, 1]
fn rotate_right[T: DType](value: SIMD[T, 1]) -> SIMD[T, 1]
fn rotate_left(value: Int) -> Int
fn rotate_right(value: Int) -> Int
```

### What is your motivation for this change?

This is a logical follow up to #499. There are now rotation methods for SIMD, so it would be nice to be able to do those same operations on bits in an integer type.

**Comment by abduld** [comment]
Thanks @lsh for the suggestion. This oversight will be fixed in the next rollout. For now (as a workaround) please use https://docs.modular.com/mojo/stdlib/math/math.html#rotate_bits_left and do `rotate_bits_left(SIMD[DType.index, 1](my_int)).to_int()`
