### ISSUE TITLE
[Feature Request] Implicit true division on integer type

### ISSUE THREAD

**Issue by futureofworld** [modularml/mojo#53]
## Bug Description
when two Int type object divides it gives error `'Int' does not implement the '__truediv__' method`
###  Expected behaviour
- To returns float or int value

### Steps to Reproduce
```
let a: Int = 20
let b: Int = 10
print(a / b)
```
### Expected Answer
**Python** : 2.0 (type **float**) or 
like **c++** :  2 (type **Int**)

And floor division is working properly
```
print(a//b) // output 2
```
Thanks for creating such a powerful language, excited to see more 😄

**Comment by Mogball** [comment]
We're missing the true division method on the integer type.
