### ISSUE TITLE
[BETA]: Language server crash on nonexistent imports

### ISSUE THREAD

**Issue by oskgo** [modularml/mojo#531]
### Bug description

The language server crashed 5 times in under 3 minutes and asked me to make this report.

I expect the language server to survive.

### Steps to reproduce

Use VSCode with the Mojo extension and the following code in a `foo.mojo` file.
```
import nonexistentChewbaccaJohnSnow
nonexistentChewbaccaJohnSnow
```

### System information

```shell
- Windows 11 with Ubuntu in WSL
- mojo 0.2.0 (4c0ef274)
- modular 0.1.2
```

**Comment by River707** [comment]
Thanks for the report! (and nice fake module name). Seems like multiple parser errors combining into a crash, should be a fix in the next release.
