### ISSUE TITLE
[BETA]: Installing mojo fails in directories without write permissions

### ISSUE THREAD

**Issue by tebartsch** [modularml/mojo#533]
### Bug description

Installing `mojo` using `modular` from a directory for which the current user does not have write permissions
yields the following error message

```bash
$ modular install mojo
# Found release for https://packages.modular.com/mojo @ 0.2.0, installing to /home/tebartsch/.modular/pkg/packages.modular.com_mojo
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
modular: error: Permission denied
```

### Steps to reproduce

Run the following steps on a

```bash
curl https://get.modular.com | MODULAR_AUTH=<auth-token> sh -
cd /
modular install mojo
```

Using `strace` gives multiple line similar to
```
openat(AT_FDCWD, "modular-tool-script-redirect-d66a95.tmp", O_RDWR|O_CREAT|O_EXCL|O_CLOEXEC, 0666) = -1 EACCES (Permission denied)
```

### System information

```shell
- What OS did you do install modular CLI/mojo on ?
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian

- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.2.0 (4c0ef274)

- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.1.2
```

**Comment by smuniraj2018** [comment]
@zbowling - Just bringing your attention to this ticket, looks like this priority was recently bumped to p0 recently after todays standup

**Comment by bzcheeseman** [comment]
This should be as simple as ensuring M::TempFile writes to the system tmp directory

**Comment by smuniraj2018** [comment]
@zbowling mentioned in my 1-1 today that he fixed it in a different way but has been taken care off. It will be good for you two to sync on this.

**Comment by zbowling** [comment]
Yep. I'm just setting working directory before executing scripts to the package directory rather system tempdir. It takes care of this (tmp file will be in the package directory) but also takes care of any accidental cases where a script executing pre-uninstall or post-install would make assumptions about the current local directory.

**Comment by Aniketp705** [comment]
I am trying to install mojo since yesterday, but it still won't show the '#Downloads complete' message. What do i do?
![Screenshot (8)](https://github.com/modularml/mojo/assets/126407478/e21f96bd-d0ae-404f-94ec-61bc07aa5db9)

**Comment by zbowling** [comment]
@Aniketp705 that issue not related this bug. We are tracking what you describing across a few other issues. We just lack a progress indicator as mojo is downloading in the background and it appears as if it's hanging on slower connections. It should eventually finish.

**Comment by rivy** [comment]
I'm getting a similar error when trying to install under WinOS/WSL, even within writable directories...

```shell
cd "${HOME}"; modular install mojo
# Found release for https://packages.modular.com/mojo @ 0.2.1, installing to /home/toor/.modular/pkg/packages.modular.com_mojo
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
modular: error: Error setting current path: Permission denied
```

**Comment by Hakan439** [comment]
I also got an error during installation on a M1 Mac:

<img width="950" alt="Screenshot 2024-05-01 at 07 24 13" src="https://github.com/modularml/mojo/assets/19551914/8eb29b84-527c-48ca-8ab5-66c7dcc5cd6d">
