### ISSUE TITLE
[Feature Request] Report more information on python exception

### ISSUE THREAD

**Issue by oskgo** [modularml/mojo#536]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Currently an `Error` caused by an exception in python code AFAICT always has value `An error occurred in Python.`

I'd like for this to additionally contain the stringified python exception.

### What is your motivation for this change?

It is currently very difficult to debug Mojo code that calls Python code, in part because all the information Python gives you is seemingly erased when it crosses the boundary.

### Any other details?

I realize that this would become obsolete once you have polymorphism, since you would then be able to raise a `PythonObject` instead.

Still, I think that putting the exception information inside the error could be a useful temporary solution.

**Comment by jackos** [comment]
This was resolved in `0.4.0`
