### ISSUE TITLE
[BETA]: Some python imports fail in Mojo

### ISSUE THREAD

**Issue by oskgo** [modularml/mojo#537]
### Bug description

A module import that works in python fails in Mojo.

### Steps to reproduce

1. Use pip to install `PyCryptodome`, a cryptography library used in the www.cryptohack.org challenges.
2. Paste the following into a new python file: 
```python
import Crypto.PublicKey.RSA as RSA
print(RSA)
```
3. Run the python file to verify the presence of the RSA module.
4. Paste the following into a new mojo file:
```python
from python import Python as py
def main():
    RSA = py.import_module("Crypto.PublicKey.RSA")
    print(RSA)
```
5. Run the mojo file to verify the failed import

### System information

```shell
- Windows 11 with Ubuntu in WSL
- mojo 0.2.0 (4c0ef274)
- modular 0.1.2
```

**Comment by dualvtable** [comment]
Can you please try explicitly adding the module to the search path - for example:

```bash
Python.add_to_path("<insert-path-to-the-Crypto-module>")
```
That may provide us with a hint as to whether the default paths are being searched or not.

**Comment by oskgo** [comment]
Trying to use `add_to_path` gives me a permission error, so I've instead moved the Crypto folder into the working directory inside another module as follows:
```
.
├── testlib/
│   ├── __init__.py
│   └── Crypto/
│       └── ...
├── test.py
└── test.mojo
```
My `test.py` file looks as follows:
```
import testlib.Crypto.PublicKey.RSA as RSA
print(RSA)
```
and prints
```
<module 'testlib.Crypto.PublicKey.RSA' from '/home/<PATH_TO_WD>/testlib/Crypto/PublicKey/RSA.py'>
```
My `test.mojo` looks as follows:
```
from python import Python as py
def main():
    py.add_to_path(".")
    let two = py.import_module("testlib.Crypto.PublicKey")
    print(two)
    let three = py.import_module("testlib.Crypto.PublicKey.RSA")
    print(three)
```
and prints the following:
```
<module 'testlib.Crypto.PublicKey' from '/home/<PATH_TO_WD>/./testlib/Crypto/PublicKey/__init__.py'>
Unhandled exception caught during execution: An error occurred in Python.
mojo: error: execution exited with a non-zero result: 1
```
It can find the `PublicKey` module just fine, so it shouldn't be a problem with the search. #536 would make this much easier to debug, which is why I made that feature request.

**Comment by oskgo** [comment]
Actually, deleting the contents of the `RSA.py` file makes the Mojo code work as expected, so it is almost certainly the CPython in Mojo failing on the `RSA.py` file for some reason.

**Comment by oskgo** [comment]
`test.py` is ran with the same executable as Mojo is using. I've verified this using `sys.executable`.

**Comment by stumpOS** [comment]
Solution:
Configure mojo to use my Python environment. I followed the following instructions to successfully import the requested packaged.

1. Create a new conda environment.

`conda create -n "FOO" python=3.10`

2. Install the python module to the environment.

 `conda activate FOO"; "conda install -c conda-forge pycryptodome`

3. Verify that the module is installed by creating a python program that uses the environment you just created:

(a) `vim pytest.py`:

```
import Crypto.PublicKey.RSA as RSA

if __name__ == '__main__':
	print(RSA)
```

(b) `python pytest.py`
`<module 'Crypto.PublicKey.RSA' from 'miniconda3/envs/FOO/lib/python3.10/site-packages/Crypto/PublicKey/RSA.py'>`


4. Create the Mojo version of the program:

`vim mojotest.mojo`

```
from python import Python as py

def main():
	RSA = py.import_module("Crypto.PublicKey.RSA")
	print(RSA)
```

5. Run the mojo program with the environment you created:

```
MOJO_PYTHON_LIBRARY=miniconda3/envs/FOO/lib/libpython3.10.dylib PYTHONPATH=miniconda3/envs/FOO/lib/python3.10/site-packages mojo  mojotest.mojo

```

The output should be the same as step 3b.

**Comment by oskgo** [comment]
@stumpOS With an activated conda environment importing RSA works even without setting the environment variables on my end.

Still, this only fixes the symptom. The underlying issue is that python called from mojo has a different `sys.path` than python called directly. I've confirmed this on another computer as well. This might cause other issues in the future.

If you want to keep this closed I'll make a new issue about the underlying issue instead.

**Comment by thestarinsky** [comment]
I was caught by the same problem.
After a long search ,I tried multiple ways like conda .However , this problem remains.

I‘ve been trying transform some of current project based on python to mojo.This problem brought me a lot of troubles.

Some thing i've tried:
1.  Use "pip" install packages with "--target".I simply thought this packages should exist in the directory that mojo used.[Failed]
2.  Create new env called"MOJO_PYTHON_LIBRARY".[Failed]

Since my project used several packages, I strongly recommand  the problem to be solved asap.
Thanks.

**Comment by oskgo** [comment]
@thestarinsky If you are using packages in your current working directory you need to do `Python.add_to_path(".")`.

What error messages are you getting? You should be getting something useful if you're using mojo 0.4.0. 

Can you also print `sys.path` and `sys.executable` when using Python as the entry point and when using Mojo as the entry point?
