### ISSUE TITLE
[BUG] Minor Typo in HelloMojo Notebook in Section: `@always_inline` decorator

### ISSUE THREAD

**Issue by abhinav-upadhyay** [modularml/mojo#54]
## Bug Description
The sentence: " It's important to be able both enabling optimizations we need and disabling optimizations we do not want. "
should have been " It's important to be able to both enable optimizations we need and disable optimizations we do not want." 

### Steps to Reproduce

1. 
2.

**Comment by goldiegadde** [comment]
This is fixed and should be available in the next playground release!
