### ISSUE TITLE
[Feature Request] add `testing.assert_raises`

### ISSUE THREAD

**Issue by lsh** [modularml/mojo#540]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Add testing method to check that a method raises.

### What is your motivation for this change?

It is useful in a testing suite to make sure methods error when expected to.

**Comment by drunkwcodes** [comment]
In pytest, it's called `raises`.

**Comment by lsh** [comment]
And in `unittest` [it's called `assertRaises`](https://docs.python.org/3/library/unittest.html?highlight=assertraises#unittest.TestCase.assertRaises)

**Comment by drunkwcodes** [comment]
IMO `pytest` is superior to `unittest` in all ways.
Mojo should assure knowing this and prevent including in dead batteries.

**Comment by JoeLoser** [comment]
Thanks for filing this issue.  This is something we do plan on including in our testing package sometime.  In the meantime, you can do something like this (this is an example of a negative test case from a string unit test):

```
try:
    _ = atol(String("9.03")) # call your actual API you want to test
    raise Error("Failed to raise when converting string to integer.") # to force a fatal error
except e:
    assert_equal(str(e), "String is not convertible to integer.") # verify assertion message in your case
```

Not as pretty as an `assert_raises` or the like, but it's functional for now.
