### ISSUE TITLE
[BETA]: VS Code in WSL not supporting compilation (Expresions are not yet supported at the file scope level)

### ISSUE THREAD

**Issue by Atosmi** [modularml/mojo#547]
### Bug description

After installing Mojo SDK in WSL Ubuntu, running a basic program is returning the following:
![image](https://github.com/modularml/mojo/assets/97217331/bfc3cd1d-39ea-4b07-9974-fd0b94f5c3bc)

As said in the Modular SDK docs, I want to run mojo files right from my VS Code installed in WSL Ubuntu.

### Steps to reproduce

After typing in a basic function, this error is highlighted:
![image](https://github.com/modularml/mojo/assets/97217331/0042d8ed-789b-47cd-ad57-c3279cf4169d)

The Mojo extension in VS Code marketplace (by Modular) suggested to configure the path to .modular file manually, but the issue is not resolving, as VS Code reports the highlighted text as:  
![image](https://github.com/modularml/mojo/assets/97217331/0d8ef0d2-3582-4398-8831-5ea10bb4472a)
The only working option is to manually type all the code in the terminal, using Mojo REPL. :C
![image](https://github.com/modularml/mojo/assets/97217331/ac7378d0-223a-40a7-af9b-3193c27e657a)

### System information

```shell
I have installed Mojo on WSL Ubuntu, within Microsoft Windows 11.
The Mojo and Modular versions are:
mojo - v : mojo 0.2.0 (4c0ef274)
modular -v : modular 0.1.2
```

**Comment by Saddibek1** [comment]
I think main function will be called automatically

**Comment by jackos** [comment]
Hi @Atosmi as @Saddibek1 said you just need to remove `main()` at the end and it will compile

**Comment by Mogball** [comment]
As @jackos mentioned, in a Mojo file, the main function is called automatically
