### ISSUE TITLE
[BETA]: Can symlinks be ignored if they already exist when updating Mojo

### ISSUE THREAD

**Issue by jackos** [modularml/mojo#558]
### Bug description

When an installation of `mojo` already exists and the user does `modular install mojo` without a `modular clean` first it will raise this error:

```
modular: error: failure detected - please run `modular clean` and try again
==========================
Failure Information:
        - Creating symlink for /home/prinova/.modular/pkg/packages.modular.com_mojo/lib/libMojoJupyter.so.18git -> /home/prinova/.modular/pkg/packages.modular.com_mojo/lib/libMojoJupyter.so failed: File exists
        - Creating symlink for /home/prinova/.modular/pkg/packages.modular.com_mojo/lib/libLLCLRuntimeGlobals.so.18git -> /home/prinova/.modular/pkg/packages.modular.com_mojo/lib/libLLCLRuntimeGlobals.so failed: File exists
        - Creating symlink for /home/prinova/.modular/pkg/packages.modular.com_mojo/lib/libMSupportGlobals.so.18git -> /home/prinova/.modular/pkg/packages.modular.com_mojo/lib/libMSupportGlobals.so failed: File exists
```

If the symlinks already exist can this error be ignored, as the the updated version of `mojo` still works.

### Steps to reproduce

Have mojo `0.2.0` installed and then run `modular install mojo`

### System information

```shell
Reproducible on all systems
```

**Comment by PriNova** [comment]
After a clean install and deleting all folders of modular and mojo seems to fix the issue.
An update of mojo via modular, has leftover files in the modular pkg and `.mojo_cache` folder, which conflicts with the updated version of mojo.

**Comment by iamtimdavis** [comment]
@bzcheeseman @zbowling FYI
