### ISSUE TITLE
Will there be an open source introductory book about mojo somewhere in the future?

### ISSUE THREAD

**Issue by slf188** [modularml/mojo#56]
## Request

Mojo is still in the development stage but I wonder if it would be nice to boost the creation of an open-source introductory book. As someone interested in systems programming, I found it incredibly helpful that Rust has its own [open-source introductory book](https://doc.rust-lang.org/book/title-page.html) which back in the day helped me understand what Rust is capable of.

### Motivation

With an introductory book, imho more people would be able to learn and use Mojo, thus increasing its adoption and community support.

### Description and Requirements

Mojo integrates amazing new features, we can probably highlight those in the book and perhaps integrate practical examples and exercises to help readers apply what they've learned with an integrated editor the way [Will Crichton improved the existing Rust book](https://rust-book.cs.brown.edu/).

Overall, I think it would be a valuable resource for users, especially beginners to have this...why not? :)

**Comment by lattner** [comment]
I would really love to see this, but this isn't something that Modular has time to push on in the immediate future.  This would be amazing for a community effort or for a sufficiently motivated individual to make happen!  I'd particularly love to see a "Mojo for Python programmers" sort of document

**Comment by goldiegadde** [comment]
Thanks @slf188 for the question. Please post in Discussions(General) if you want to hear from others in the community who maybe interested. 
Closing this issue now.
