### ISSUE TITLE
[Feature Request] thread support?

### ISSUE THREAD

**Issue by weijiafs** [modularml/mojo#560]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Does Mojo have plans to support multi-threading and multi-tasking development and become a universal programming language?

### What is your motivation for this change?

I hope Mojo can become a universal language. In addition to developing AI, it can also develop web and database applications.

**Comment by lattner** [comment]
Yes, Mojo has full support for multithreading.  Please check out our recent blog post which scales out to an 88 core machine

**Comment by weijiafs** [comment]
I didn’t find how to create a thread or channel (like go) from the documentation. Will Mojo be designed as a universal language?

**Comment by guidorice** [comment]
@weijiafs I am pretty sure that multi-threading is used in 3 of the example notebooks? The terminology is going to be different than Go lang. Search for "parallelize" in mojo docs.

**Comment by guidorice** [comment]
Also the FAQ item:

> That said, we don’t plan to stop at AI—the north star is for Mojo to support the whole gamut of general-purpose programming over time. For a longer answer, read [Why Mojo](https://docs.modular.com/mojo/why-mojo.html).
