### ISSUE TITLE
[BETA]: 2 mojo files with the same name but different extensions implicitly prioritizes .mojo files

### ISSUE THREAD

**Issue by sa-** [modularml/mojo#562]
### Bug description

Implicit behavior when there are 2 files with different extensions (e.g. x.🔥 or x.mojo)

Described over here: https://discord.com/channels/1087530497313357884/1098713601386233997/threads/1148835501294485554

If it continues to prioritize .mojo it will inevitably become part of someone's [workflow](https://xkcd.com/1172/). This can be nipped in the bud by instead throwing an error that says "duplicate file names found" and failing the package/import step instead of picking one silently or with a warning.

### Steps to reproduce

- Create 2 files testing_testing.🔥 and testing_testing.mojo
- In both files, create a function named `whats_my_extension` that either prints "emoji" or "text" depending on the file
- From a third file, import whats_my_extension from testing_testing

### System information

```shell
n/a
```

**Comment by Mogball** [comment]
Good catch on this one. One of the struggles of supporting multiple file extensions!

**Comment by willghatch** [comment]
This is fixed for the next release.
