### ISSUE TITLE
[Modular CLI]: Unable to install modular on apple silicon m1 air

### ISSUE THREAD

**Issue by aludayalu** [modularml/mojo#569]
### Issue description

I tried to follow the instructions on the modular download page (https://developer.modular.com/download) but was unable to install modular. I wanted to install mojo lang via modular but there seems to be no way of installing it as of now as the script keeps giving an error. Kindly help me install mojo lang on my m1 air as soon as possible. Thank you.

### Steps to reproduce

Run
```
curl https://get.modular.com | \                                          ─╯
  MODULAR_AUTH=mut_174136862cc1439b81509f58004c17b9 \
  sh -
```

Output:
Sorry, this system is not recognized. Please visit https://www.modular.com/mojo to learn about supported platforms. You can also build and run a Mojo container by following instructions at https://github.com/modularml/mojo.

### Version Info

```shell
macOS Ventura
```

**Comment by goldiegadde** [comment]
Mojo support for apple sililcon is being tracked here -> https://github.com/modularml/mojo/issues/510
However you can use it on mac via remote linux system and GH codespaces. 
If you signup at developer.modular.com, you can copy paste canned instructions on how to get started. 
Closing this issue.
