### ISSUE TITLE
[Playground] Support for disassembler like tools

### ISSUE THREAD

**Issue by xintin** [modularml/mojo#57]
## Request
Support for python like disassembler module 
Support for IR inspector tool

### Motivation
While running the benchmarking notebooks, it will be helpful to analyze the bytecode. 
Further, support for IR dump and inspection will be much more appreciated to understand the optimizations like SIMD, unrolling, etc. 

In the tutorial and doc, I tried to find the above two (bytecode analyzer and IR inspector) but could not. If it already exists, feel free to redirect me. Thanks.

### Description and Requirements
1. `dis` module to analyze the bytecode; something like in python  
2. tool to inspect IR.

**Comment by lattner** [comment]
This would be very handy.

**Comment by Mogball** [comment]
Our compiler can already produce intermediate MLIR, LLVMIR, and assembly.

**Comment by lattner** [comment]
Right, but we should have a feature to expose this in the notebook

**Comment by Boyazhang1** [comment]
> Our compiler can already produce intermediate MLIR, LLVMIR, and assembly, but we're not ready to release these tools yet.

Is there an expected timeline for the release of these features?

**Comment by walter-erquinigo** [comment]
Thanks for the report!
We should be able to expose magic commands, e.g. `%%mlir` that can support this exact feature.
We haven't planned for this work yet, but as soon as we do, we'll let you know.

**Comment by Brian-M-J** [comment]
Since the purpose is to understand compiler optimizations, will there also eventually be a way to view [optimization remarks](https://youtu.be/qmEsx4MbKoc)?
