### ISSUE TITLE
[Modular CLI]: unable to install it with no root access

### ISSUE THREAD

**Issue by nacho00112** [modularml/mojo#570]
### Issue description

I wanted to install the CLI to install mojo but i only have home `~` permissions, i can't access to the root `/`, i want to be able to install it for example in `~/.local`

### Steps to reproduce

I tried to execute the commands specified here: https://developer.modular.com/download, but the command to install the CLI failed, it asked me for sudo password that i don't have

### Version Info

```shell
I wasn't able to install it
```

**Comment by bzcheeseman** [comment]
Unfortunately `apt` requires sudo access to install this package. Please contact your system admin about getting this package installed.

**Comment by lattner** [comment]
You can also try installing it in an (e.g.) docker container
