### ISSUE TITLE
[Dev Console]: Discord logo for github Issues Card in get started section

### ISSUE THREAD

**Issue by BestClaws** [modularml/mojo#571]
### Issue description

![Screenshot from 2023-09-07 23-00-27](https://github.com/modularml/mojo/assets/40067018/d1e849d1-b9b0-4981-a216-49fa5be6579a)

Not sure if this is intended but Get Started -> Github Issues section has discord logo

### Steps to reproduce

navigate to https://developer.modular.com/download and scroll towards Get started Section

screenshot in issue description

**Comment by robert-j-webb** [comment]
Thanks! I updated it :)
