### ISSUE TITLE
[BUG]: hello.mojo prints the wrong integers

### ISSUE THREAD

**Issue by itsgifnotjiff** [modularml/mojo#576]
### Bug description

![image](https://github.com/modularml/mojo/assets/50274281/6c058707-b673-4361-9371-bd3af2e8d568)

### Steps to reproduce

I simply installed Moho as instructed on Windows 11 using WSL 22.04, `git clone https://github.com/modularml/mojo.git` and ran `mojo hello.🔥`.

### System information

```shell
-  Windows 11 Home 10.0.22621 Build 22621
- `mojo -v` : mojo 0.2.1 (64d14e85)
- `modular -v` : modular 0.1.4 (6b54d308)
```

**Comment by iamtimdavis** [comment]
The latter one is the Modular CLI, the top is the Mojo SDK. 

We'll update to make this clearer. Thanks!

@zbowling @bzcheeseman

**Comment by bzcheeseman** [comment]
I can't actually read the screenshot, do you mind copying the error(s), please?

**Comment by itsgifnotjiff** [comment]
It's actually just to show that it was supposed to print out 
```
Hello Mojo 🔥!
9
0
-3
```
as per [`hello.🔥`](https://github.com/modularml/mojo/blob/7e667e951008ade31621dbd37217a562ae82472f/examples/hello.%F0%9F%94%A5) but printed out
```
Hello Mojo 🔥!
9
6
3
```

**Comment by drunkwcodes** [comment]
@itsgifnotjiff It's just how `range()` works.
Not a bug.

**Comment by itsgifnotjiff** [comment]
If I could craw under a rock and die I would. I was running a couple of examples at the same time and I had another one testing string literals 
```python
for i in ["hello","world","!"]:
    print(i)
```

which gave me 
```python
hmmm.mojo:3:14: error: 'ListLiteral[StringLiteral, StringLiteral, StringLiteral]' does not implement the '__iter__' method
    for i in ["hello","world","!"]:
             ^
mojo: error: failed to parse the provided Mojo
```
and I mixed them together in my head. I am so sorry for this embarrissing issue, next time I will pay more attention.
