### ISSUE TITLE
[BUG]: __name__ == '__main__' declaration does not work

### ISSUE THREAD

**Issue by nielstenboom** [modularml/mojo#579]
### Bug description

I converted a python script that contained a `'__name__ == '__main__'` declaration and mojo errored on it:

```
op.mojo:9:4: error: use of unknown declaration '__name__'
if __name__ == "__main__":
```

### Steps to reproduce

Run the mojo code:

```python
if __name__ == "__main__":
    print("hello")
```

### System information

```shell
- What OS did you do install Mojo on ?
Ubuntu 20.04

- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.2.1 (64d14e85)

- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.1.4 (6b54d308)
```

**Comment by jordantgh** [comment]
It's not the same idiom in mojo. It currently doesn't have support for top level expressions at all so you just write 

```python
def main():
    print("hello")
```

**Comment by ematejska** [comment]
Duplicate https://github.com/modularml/mojo/issues/187
