### ISSUE TITLE
[Modular CLI]: Installation of Mojo 🔥 is stuck.

### ISSUE THREAD

**Issue by codebyaadi** [modularml/mojo#580]
### Issue description

I tried to install mojo 🔥 on local environment ( Windows ). I have wsl Ubuntu. After completing the modular CLI download. I tried to install mojo using `modular install mojo` but I got stuck here "# Found release for https://packages.modular.com/mojo @ 0.2.1, installing to /home/dark/.modular/pkg/packages.modular.com_mojo". 

### Steps to reproduce

- command - `modular install mojo`
- Image of the command line
![mojoissue](https://github.com/modularml/mojo/assets/100792725/b7d1b010-39f9-407d-b393-8859be4b0648)

- Stuck with this `# Found release for https://packages.modular.com/mojo @ 0.2.1, installing to /home/dark/.modular/pkg/packages.modular.com_mojo`

### Version Info

```shell
- modular 0.1.4 (6b54d308)
- Windows 10
```

**Comment by bzcheeseman** [comment]
The package is pretty large, how fast is your internet?

We're working on compression/etc. to speed this up in the future.

**Comment by ksandvik** [comment]
Also check for the permission flags in that path and does it help if you run it with sudo in front?

**Comment by garam-kim1** [comment]
It takes quite long time after that message

**Comment by codebyaadi** [comment]
Thanks! After running `modular clean` ( I have to use this. Maybe because I previously tried to install and I failed ). Then I run the commant `modular install mojo` and it worked after taking sometime.

**Comment by meicale** [comment]
> ### Issue description
> I tried to install mojo 🔥 on local environment ( Windows ). I have wsl Ubuntu. After completing the modular CLI download. I tried to install mojo using `modular install mojo` but I got stuck here "# Found release for https://packages.modular.com/mojo @ 0.2.1, installing to /home/dark/.modular/pkg/packages.modular.com_mojo".
> 
> ### Steps to reproduce
> * command - `modular install mojo`
> * Image of the command line
>   ![mojoissue](https://user-images.githubusercontent.com/100792725/266419510-b7d1b010-39f9-407d-b393-8859be4b0648.PNG)
> * Stuck with this `# Found release for https://packages.modular.com/mojo @ 0.2.1, installing to /home/dark/.modular/pkg/packages.modular.com_mojo`
> 
> ### Version Info
> ```shell
> - modular 0.1.4 (6b54d308)
> - Windows 10
> ```

How to run the install script on this page?https://developer.modular.com/download I stucked in this and I tried the manual install method, it doesn't work. Same issue is [here](https://github.com/modularml/mojo/issues/589). Thx!

**Comment by devrohitv** [comment]
![image](https://github.com/modularml/mojo/assets/142287858/5651d23a-c96d-410b-b64b-356db0521115)
it got stuck here every time after doing modular clean again and again

**Comment by jackos** [comment]
@devrohitv try the suggestions here: https://github.com/modularml/mojo/issues/538

**Comment by latheeshvm** [comment]
> The package is pretty large, how fast is your internet?
> 
> We're working on compression/etc. to speed this up in the future.
@bzcheeseman hmm, How big exactly? I do have a 200Mbps
