### ISSUE TITLE
[Feature Request] Gentoo support

### ISSUE THREAD

**Issue by geometrylearner** [modularml/mojo#582]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Install Mojo on Gentoo Linux

### What is your motivation for this change?

Seeking for feasibility of Mojo in more general Linux Distros and better reliability.

### Any other details?

`Sorry, this system is not recognized. Please visit https://www.modular.com/mojo to learn about supported platforms. You can also build and run a Mojo container by following instructions at https://github.com/modularml/mojo.` Here is the error report when I run `curl` script.

**Comment by ematejska** [comment]
Duplicate https://github.com/modularml/mojo/issues/187

**Comment by jackos** [comment]
Hi @geometrylearner, we don't have support for Gentoo yet, but for others who have the same request, please upvote this issue!

**Comment by walter-erquinigo** [comment]
We are actively not working on Gentoo, but we have just moved to distributing max/mojo via conda/magic, so this might just work out of the box now. Please reopen this issue if it persists.
