### ISSUE TITLE
[Feature Request] Is it possible to run Mojo in a Docker container on M2 Max silicon?

### ISSUE THREAD

**Issue by devforfu** [modularml/mojo#588]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

I am trying to run Mojo locally on my M2 Max silicon desktop. I know that it is not supported natively, but I thought that running in Docker container would work. However, it looks like it is not the case. Running in a container derived from `ubuntu:latest` returns the error.
```
no packages found for the current target hardware - 
please run `modular host-info` and file a ticket at 
https://github.com/modularml/mojo with your hardware information
```
Here is my Dockerfile.
```Dockerfile
FROM ubuntu:latest

RUN apt-get update -y && \
  apt-get -y install curl gpg-agent && \
  apt-get install -y apt-transport-https && \
  keyring_location=/usr/share/keyrings/modular-installer-archive-keyring.gpg && \
  curl -1sLf 'https://dl.modular.com/bBNWiLZX5igwHXeu/installer/gpg.0E4925737A3895AD.key' |  gpg --dearmor >> ${keyring_location} && \
  curl -1sLf 'https://dl.modular.com/bBNWiLZX5igwHXeu/installer/config.deb.txt?distro=debian&codename=wheezy' > /etc/apt/sources.list.d/modular-installer.list && \
  apt-get update && \
  apt-get install -y modular

RUN modular auth <auth-token> && modular install mojo
```
Does it mean that running Mojo on M2 chips isn't possible at the moment? I don't have in-depth knowledge of how Docker containers work. So, I don't know if it is an expected behavior and this kind of virtualization is just not supported (should use a "real" Linux machine), or I am doing it wrong.

Thank you!

### What is your motivation for this change?

It would be great to have an option of running Mojo in a Docker container for systems that don't support it natively.

**Comment by devforfu** [comment]
[There is a Dockerfile](https://github.com/modularml/mojo/blob/main/examples/docker/Dockerfile.mojosdk) in the repo, but it also fails when I am trying to build a container. This time, however, with a different error.
```
=> ERROR [3/6] RUN curl -fsSL https://repo.anaconda.com/ [...]
------
[...]
9.642 qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```

**Comment by devforfu** [comment]
Ok, it looks like that one is an issue of running Docker on an Apple's silicon. There is a [solution](https://stackoverflow.com/questions/71040681/qemu-x86-64-could-not-open-lib64-ld-linux-x86-64-so-2-no-such-file-or-direc) that helped me to get to the next building stage. (Still running.) Here is the change to the Dockerfile.
```Dockerfile
FROM --platform=linux/amd64 ubuntu:20.04
```

**Comment by jackos** [comment]
@devforfu it will fail when you try to run mojo as x86 emulation doesn't currently work, there's an open feature request for it here: https://github.com/modularml/mojo/issues/510 and we're actively working on native support.

For now you'll have to ssh to an x86-64 machine and install it there.

**Comment by devforfu** [comment]
@jackos ah, I see, thank you!

**Comment by HananyTolba** [comment]
I have just made available a docker imager with mojo ready for use : docker pull hananytolba/mojo:0.2.1 for use docker run -ti  hananytolba/mojo:0.2.1 bash   and inupt mojo

**Comment by getorca** [comment]
same issue, using the dockerfile <https://github.com/modularml/mojo/blob/main/examples/docker/Dockerfile.mojosdk> and opening in a dev container in vs code works.

**Comment by benz0li** [comment]
FYI

* https://github.com/modularml/mojo/discussions/2647
* https://github.com/modularml/mojo/discussions/2648
