### ISSUE TITLE
[BUG]: Windows 11 WSL2 Ubuntu

### ISSUE THREAD

**Issue by MaKeSter333** [modularml/mojo#589]
### Bug description

![image](https://github.com/modularml/mojo/assets/48758871/9bdc5cb4-5c0b-4c91-8921-fdb7e467a4f7)
![image](https://github.com/modularml/mojo/assets/48758871/fc4a8a6a-a791-4f23-9e27-c6cb28d02a4c)
Why is modular not found?

### Steps to reproduce

.

**Comment by bzcheeseman** [comment]
Seems like our script may have failed! Can you try the manual install instructions? They should be further down on the same webpage.

**Comment by MaximBoya** [comment]
I have exactly the same problem. Windows 10, WSL2, Ubuntu 12.04.2 LTS.

**Comment by MaKeSter333** [comment]
> Seems like our script may have failed! Can you try the manual install instructions? They should be further down on the same webpage.

![image](https://github.com/modularml/mojo/assets/48758871/c21c7ff9-d495-427a-a5bb-779797970c44)

**Comment by MaKeSter333** [comment]
![image](https://github.com/modularml/mojo/assets/48758871/75ceb754-67f2-4c9c-8401-6ec19b70fabb)

**Comment by meicale** [comment]
@MaKeSter333  it is a picture. Would you mind pasting the code text. I have the same enviroment and the same problems. Thx!

> ![image](https://user-images.githubusercontent.com/48758871/266444950-75ceb754-67f2-4c9c-8401-6ec19b70fabb.png)

**Comment by meicale** [comment]
> > Seems like our script may have failed! Can you try the manual install instructions? They should be further down on the same webpage.
> 
> ![image](https://user-images.githubusercontent.com/48758871/266442613-c21c7ff9-d495-427a-a5bb-779797970c44.png)

same problems. +1

**Comment by mizoru** [comment]
same issue

**Comment by MaximBoya** [comment]
I managed to solve this problem, I just connected a VPN with an IP address from USA before installing. Is pre-access allowed only for USA residents? I received a 403 message from the download server using my native ip address of the Russian Federation, the same 403 was when I used the Dutch ip.

**Comment by lattner** [comment]
I think this is fixed now?  Could you verify and we can close this if so?  Thanks!

**Comment by MaKeSter333** [comment]
> I think this is fixed now? Could you verify and we can close this if so? Thanks!

Problem fixed. Thanks to everyone who helped
