### ISSUE TITLE
[BUG]: SIMD can create illegal width (3) when init without a value.

### ISSUE THREAD

**Issue by guidorice** [modularml/mojo#593]
### Bug description

If a compile error could be raised, when non-power-of-two size is in the parameter, that would be helpful.

### Steps to reproduce

```mojo
var data = SIMD[DType.float32, 3]()   # note: parameter is non-power-of-two size
for i in range(0, 3):
    data[i] = 42 + i
for i in range(0, 3):
    print(data[i])
```

output:

```
42.0
43.0
44.0
```

### System information

```shell
- What OS did you do install Mojo on ?

Linux mojo-dev 5.10.0-24-cloud-amd64 #1 SMP Debian 5.10.179-5 (2023-08-08) x86_64 GNU/Linux

- Provide version information for Mojo by pasting the output of `mojo -v`

mojo 0.2.1 (64d14e85)

- Provide Modular CLI version by pasting the output of `modular -v`

modular 0.1.4 (6b54d308)
```

**Comment by ematejska** [comment]
@Mogball Where do kernel issues fall? mojo-lang, mojo-stdlib or something else?

**Comment by Mogball** [comment]
stdlib is correct

**Comment by lattner** [comment]
Why should this be an error?  We support SIMD types that are not legal for a target, e.g. SIMD of 12 can be legalized to an 8elt + 4elt vector.

**Comment by guidorice** [comment]
🤔 maybe this is just a docs bug then?

> Constraints: The size of the SIMD vector to be positive and a power of 2. 
>  https://docs.modular.com/mojo/stdlib/builtin/simd.html

**Comment by Mogball** [comment]
@abduld one of the constructors is probably missing the constraint check. It would be easier if structs could have constraints :P

**Comment by Mogball** [comment]
SIMD. One of the constructors is missing _simd_construction_checks

**Comment by abduld** [comment]
Thanks @Mogball . Will take a look.
