### ISSUE TITLE
[Modular CLI]: 

### ISSUE THREAD

**Issue by travisddavies** [modularml/mojo#596]
### Issue description

Installation script doesn't install for arch linux

### Steps to reproduce

command:
curl https://get.modular.com |   MODULAR_AUTH=<>   sh -

error:
sh: line 57: type: dnf: not found
sh: line 62: type: yum: not found
Sorry, this system is not recognized. Please visit https://www.modular.com/mojo to learn about supported platforms. You can also build and run a Mojo container by following instructions at https://github.com/modularml/mojo.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
- What OS did you install modular CLI on ?
```

**Comment by jackos** [comment]
Arch Linux is not yet supported, please upvote this ticket to prioritize it: https://github.com/modularml/mojo/issues/572

See an example of how to build a dockerfile for Ubuntu 22.04: https://github.com/modularml/mojo/blob/main/examples/docker/Dockerfile.mojosdk
