### ISSUE TITLE
[Modular CLI]: modular install mojo on Mac

### ISSUE THREAD

**Issue by makoojogit** [modularml/mojo#600]
### Issue description

"modular install mojo" fails. I get following error.
vscode ➜ /workspaces/ubuntu $ modular install mojo
modular: error: no packages found for the current target hardware - please run `modular host-info` and file a ticket at https://github.com/modularml/mojo with your hardware information

Here is the output from host-info - 

vscode ➜ /workspaces/ubuntu $ modular host-info
  Host Information
  ================

  Target Triple: arm64-unknown-linux
  CPU: generic
  CPU Features: crc, crypto, fp-armv8, lse, neon

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`

vscode ➜ /workspaces/ubuntu $ modular -v
modular 0.1.4 (6b54d308)

- What OS did you install modular CLI on ?
Mac OS Monterey (12.6.3)
```

**Comment by jackos** [comment]
Hi @makoojogit Apple Silicon is not currently supported, you can follow the guide at https://developer.modular.com/download to set up a remote machine. And make sure to upvote this ticket so we prioritize native macOS Apple Silicon support: https://github.com/modularml/mojo/issues/510
