### ISSUE TITLE
[Modular CLI]: Sorry, this system is not recognized. 

### ISSUE THREAD

**Issue by naaive** [modularml/mojo#601]
### Issue description

Sorry, this system is not recognized. Please visit https://www.modular.com/mojo to learn about supported platforms. You can also build and run a Mojo container by following instructions at https://github.com/modularml/mojo.

OS:
<img width="280" alt="image" src="https://github.com/modularml/mojo/assets/73341653/e0b11161-3f80-4ebf-b36c-0b94cc6257b0">

### Steps to reproduce

```
(base) ➜  ~ sudo curl https://get.modular.com | \
  MODULAR_AUTH=mut_9ffe0f36efb748edae81ccd392558688 \
  sh -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3176  100  3176    0     0   8443      0 --:--:-- --:--:-- --:--:--  8491
Sorry, this system is not recognized. Please visit https://www.modular.com/mojo to learn about supported platforms. You can also build and run a Mojo container by following instructions at https://github.com/modularml/mojo.
(base) ➜  ~ 

```

**Comment by bolivarbryan** [comment]
Same issue for me. but I'm using Mac OS Sonoma Beta 
<img width="392" alt="Screenshot 2023-09-07 at 8 40 40 PM" src="https://github.com/modularml/mojo/assets/810092/a9db05a0-6733-4845-95f7-a762b9b9decd">

**Comment by jackos** [comment]
Hi thanks for your interest; please upvote this ticket for Apple Silicon support: https://github.com/modularml/mojo/issues/510

We are currently working on this, the developer console will show you how to set up a remote machine until this is available: https://developer.modular.com/download
