### ISSUE TITLE
[Modular CLI]: modular: error: Could not open cache index 0 size: No such file or directory

### ISSUE THREAD

**Issue by z4y1b2** [modularml/mojo#603]
### Issue description

Cannot install mojo in Ubuntu running in OrbStack.

### Steps to reproduce

Try to install mojo in Ubuntu 23.04 running OrbStack, following installation steps in https://developer.modular.com/download,

but

`modular install mojo`

fails with error:
```
modular: error: Could not open cache index 0 size: No such file or directory
```

### Version Info

```shell
>> modular -v
modular 0.1.4 (6b54d308)

>> uname -a
Linux ubuntu 6.4.13-orbstack-00090-ga4cfdc88d4df #1 SMP Thu Aug 31 05:51:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

OrbStack runs in MacBook Pro M2 Max(64GB RAM, 12 CPU Cores).

**Comment by jackos** [comment]
HI @z4y1b2 Apple Silicon isn't supported yet, even through QEMU or Rosseta x86-64 emulation like OrbStack uses. We're working on native Apple Silicon support, but please upvote this ticket: https://github.com/modularml/mojo/issues/510
