### ISSUE TITLE
[Modular CLI]: unable to install modular cli in Ubuntu 20.04 docker container

### ISSUE THREAD

**Issue by codingfun2022** [modularml/mojo#606]
### Issue description

I failed to install Mojo in a Ubuntu 20.04 docker container with the installation instructions given in <https://developer.modular.com/download>.

I also tried the **Manual installation steps** and the **Distro-specific Setup** step failed with prompt: ``gpg: no valid OpenPGP data found``.

### Steps to reproduce

- Inside a Ubuntu 20.04 docker container.

- Execute the **Distro-specific Setup** step of **Manual installation steps**

  ```bash
  apt-get install -y apt-transport-https &&
  keyring_location=/usr/share/keyrings/modular-installer-archive-keyring.gpg &&
  curl -1sLf 'https://dl.modular.com/bBNWiLZX5igwHXeu/installer/gpg.0E4925737A3895AD.key' |  gpg --dearmor >> ${keyring_location} &&
  curl -1sLf 'https://dl.modular.com/bBNWiLZX5igwHXeu/installer/config.deb.txt?distro=debian&codename=wheezy' > /etc/apt/sources.list.d/modular-installer.list &&
  apt-get update &&
  apt-get install -y modular
  ```

- Got the following output:

  ```text
  Reading package lists... Done
  Building dependency tree       
  Reading state information... Done
  apt-transport-https is already the newest version (2.0.9).
  0 upgraded, 0 newly installed, 0 to remove and 36 not upgraded.
  gpg: no valid OpenPGP data found.
  ```

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`

  `modular` is not installed yet.

- What OS did you install modular CLI on ?

  Ubuntu 20.04 docker container
```

**Comment by SunKing2** [comment]
Here's a Dockerfile that works (I'm not that good with docker, but it functions):

# Start from the Ubuntu 20.04 base image
FROM ubuntu:20.04

# Avoid prompts with apt
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary tools, libraries, and utilities
RUN apt-get update \
    && apt-get install -y \
    software-properties-common \
    build-essential \
    curl \
    vim \
    python3 python3-pip 

# Create a symlink for python -> python3.10
RUN ln -s /usr/bin/python3 /usr/bin/python

RUN pip3 install --upgrade pip
RUN curl https://get.modular.com |   MODULAR_AUTH=mut_bc06f50226964d8eb091be7d09dc6e70   sh -
RUN modular install mojo
RUN echo 'export MODULAR_HOME="/root/.modular"' >> ~/.bashrc
RUN echo 'export PATH="/root/.modular/pkg/packages.modular.com_mojo/bin:$PATH"' >> ~/.bashrc
RUN echo 'PS1="_# "' >> ~/.bashrc


# Verify Python version
RUN python3 --version
RUN python --version

CMD ["/bin/bash"]

**Comment by codingfun2022** [comment]
@SunKing2 Thanks! I tried your Dockerfile but it failed again. With some more attempts, I confirmed that it failed because of the network proxy issue.

After I added the domain ``.modular.com`` into my ``/etc/privoxy/pac.action`` privoxy config, I can install the modular cli now.

The **Install Mojo** step of **Manual installation steps** in <https://developer.modular.com/download> still fails. I will check it later.

**Comment by codingfun2022** [comment]
With more attempts, I successfully installed Mojo in Ubuntu 20.04 docker container!

For the **Manual installation steps** in <https://developer.modular.com/download> to succeed, we need to:

1. Enable VPN or other network proxies for ``.modular.com`` if necessary.
2. Launch docker container with ``docker run --privileged ...``.

Here is my commands:

1. Launch docker container with the following command.

  ```bash
  docker run -it --rm --name john-doe-mojo-docker-env --network host -e http_proxy=${http_proxy} -e https_proxy=${https_proxy} -v ${PWD}:${PWD} --privileged john-doe-docker-env-ubuntu20.04:1.0.0
  ```

2. Execute the **Distro-specific Setup** step.

  ```bash
  apt-get install -y apt-transport-https &&
  keyring_location=/usr/share/keyrings/modular-installer-archive-keyring.gpg &&
  curl -1sLf 'https://dl.modular.com/bBNWiLZX5igwHXeu/installer/gpg.0E4925737A3895AD.key' |  gpg --dearmor >> ${keyring_location} &&
  curl -1sLf 'https://dl.modular.com/bBNWiLZX5igwHXeu/installer/config.deb.txt?distro=debian&codename=wheezy' > /etc/apt/sources.list.d/modular-installer.list &&
  apt-get update &&
  apt-get install -y modular
  ```

3. Execute the **Install Mojo** step.

  ```bash
  modular auth mut_ac77f6c63eee4cc2afdc589ed6de4d8e &&
  modular install mojo
   ```

**Comment by carusyte** [comment]
> With more attempts, I successfully installed Mojo in Ubuntu 20.04 docker container!
> 
> For the **Manual installation steps** in https://developer.modular.com/download to succeed, we need to:
> 
> 1. Enable VPN or other network proxies for `.modular.com` if necessary.
> 2. Launch docker container with `docker run --privileged ...`.
> 
> Here is my commands:
> 
> 1. Launch docker container with the following command.
> 
> ```shell
> docker run -it --rm --name john-doe-mojo-docker-env --network host -e http_proxy=${http_proxy} -e https_proxy=${https_proxy} -v ${PWD}:${PWD} --privileged john-doe-docker-env-ubuntu20.04:1.0.0
> ```
> 
> 2. Execute the **Distro-specific Setup** step.
> 
> ```shell
> apt-get install -y apt-transport-https &&
> keyring_location=/usr/share/keyrings/modular-installer-archive-keyring.gpg &&
> curl -1sLf 'https://dl.modular.com/bBNWiLZX5igwHXeu/installer/gpg.0E4925737A3895AD.key' |  gpg --dearmor >> ${keyring_location} &&
> curl -1sLf 'https://dl.modular.com/bBNWiLZX5igwHXeu/installer/config.deb.txt?distro=debian&codename=wheezy' > /etc/apt/sources.list.d/modular-installer.list &&
> apt-get update &&
> apt-get install -y modular
> ```
> 
> 3. Execute the **Install Mojo** step.
> 
> ```shell
> modular auth mut_ac77f6c63eee4cc2afdc589ed6de4d8e &&
> modular install mojo
> ```

I guess you might want to mask the `modular auth mut_xxxxxxxxxxx`
