### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by liaoran** [modularml/mojo#607]
OS: Ubuntu 22.04 LTS
(1) There is no response when using the automatic installation method, and the modular is not downloaded
(2) Using the manual installation method, it prompts "bash: /usr/share/keyrings/modular-installer-archive-keyring.gpg: Permission denied"

**Comment by codingfun2022** [comment]
You need root or sudo.

**Comment by liaoran** [comment]
> You need root or sudo.
use sudo

**Comment by tianstcht** [comment]
It's cn feature, to automatic method, maybe you should set proxy:
```bash
export http_proxy={ip}:{port}
export https_proxy={ip}:{port}
```
and then maybe you will meet some other problems like me  :<

**Comment by liaoran** [comment]
> It's cn feature, to automatic method, maybe you should set proxy:
> 
> ```shell
> export http_proxy={ip}:{port}
> export https_proxy={ip}:{port}
> ```
> 
> and then maybe you will meet some other problems like me :<

Haha, it's solved, thank you!

**Comment by ematejska** [comment]
Glad it's solved.

**Comment by srchilukoori** [comment]
On Ubuntu 22.04, adding `sudo tee` as seen below worked
`sudp apt-get install -y apt-transport-https &&
  keyring_location=/usr/share/keyrings/modular-installer-archive-keyring.gpg &&
  curl -1sLf 'https://dl.modular.com/bBNWiLZX5igwHXeu/installer/gpg.0E4925737A3895AD.key' |  gpg --dearmor | sudo tee ${keyring_location} &&
  curl -1sLf 'https://dl.modular.com/bBNWiLZX5igwHXeu/installer/config.deb.txt?distro=debian&codename=wheezy' | sudo tee /etc/apt/sources.list.d/modular-installer.list &&
  sudo apt-get update &&
  sudo apt-get install -y modular`
