### ISSUE TITLE
[BUG]: Module rename causing program crash 

### ISSUE THREAD

**Issue by KuldeepSinhChauhan** [modularml/mojo#613]
### Bug description

After renaming a module from `my_pair.mojo` to `mymodule.mojo`, the program crashes with an error indicating it's unable to locate module 'my_pair'. The module contains a struct called MyPair. This issue occurs when trying to run a program written in Mojo language.
**Error Log:**
```
vscode ➜ /workspaces/ubuntu $ mojo hello.🔥 
Included from mypackage/__init__.🔥:1:
mypackage/mymodule.🔥:1:1: error: unable to locate module 'my_pair'
struct MyPair:
^
@"$my_pair"::@MyPair
mojo: /__w/modular/modular/KGEN/lib/MojoParser/DeclResolver.h:160: M::KGEN::LIT::ASTDecl &M::KGEN::LIT::DeclResolver::getDeclForTypeSymbol(mlir::SymbolRefAttr) const: Assertion `it != declForTypeSymbol.end() && "Unknown decl symbol!"' failed.
```
The system is unable to locate the 'my_pair' module and fails the assertion of unknown declaration symbol at /__w/modular/modular/KGEN/lib/MojoParser/DeclResolver.h:160.
Additional errors include failure to open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq and /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq which might be related to system configuration rather than the Mojo language itself.
A stack dump has been provided for further analysis:
```
0.      Program arguments: mojo hello.\360\237\224\245
1.      Crash resolving decl body at loc("hello.\F0\9F\94\A5":4:1)
    >> fn main():
       ^.........
    >>     print("Hello, Mojo!")
    >> 
    >>     # var a: Int = 42
    >>     # print(a)
2.      Crash parsing statement at loc("hello.\F0\9F\94\A5":30:5)
    >>     let mine = MyPair(2, 4)
           ^......................<
```
The crash happens while resolving declaration body and parsing a statement related to MyPair.
Please look into this issue as it prevents the successful execution of the program after a simple module rename operation.

### Steps to reproduce

hello.mojo

```
from mypackage import MyPair


fn main():
    print("Hello, Mojo!")

    let mine = MyPair(2, 4)
    mine.dump()
```

mypackage/mymodule.mojo 

```
struct MyPair:
    var first: Int
    var second: Int

    fn __init__(inout self, first: Int, second: Int):
        self.first = first
        self.second = second

    fn dump(self):
        print(self.first, self.second)
```

mypackage/__init__.mojo 

```
from .mymodule import MyPair

```

### System information

```shell
- What OS did you do install Mojo on ? Mac Intel with DevContainer
- Provide version information for Mojo by pasting the output of `mojo -v` : mojo 0.2.1 (64d14e85)
- Provide Modular CLI version by pasting the output of `modular -v` : modular 0.1.4 (6b54d308)
```

**Comment by willghatch** [comment]
I'm having trouble reproducing this.  When I follow your repro instructions, it works fine for me.

Let me clarify, though:  Your instructions include the file `mypackage/__init__.mojo`, but when you wrote it you didn't put it in backticks, so you have a bolded __init__.  If I leave the underscores off, I get `error: unable to locate module 'mypackage'`, but if I add the underscores everything seems to work.

**Comment by Mogball** [comment]
Closing this as not reproducible
