### ISSUE TITLE
[BUG]: unable to locate module 'builtin' in REPL

### ISSUE THREAD

**Issue by Abusheik008** [modularml/mojo#615]
### Bug description

Unable to run mojo hello world command

Welcome to Mojo! 🔥
Expressions are delimited by a blank line.
Type `:mojo help` for further assistance.
1> print("Hello")
2. 
[User] error: Expression [0]:1:1: unable to locate module 'builtin'
from memory.unsafe import Pointer
^

error: Expression [0]:15:1: could not find builtin 'Error' type
def __mojo_repl_expr_impl__(inout __mojo_repl_arg: __mojo_repl_context__) -> None:
^

error: Expression [0]:12:3: could not find builtin 'Error' type
  except error:
  ^

error: Expression [0]:13:5: use of unknown declaration 'print'
    print("Error:", error.value)
    ^~~~~

error: Expression [0]:17:3: could not find builtin 'Error' type
  def __mojo_repl_expr_body__() -> None:
  ^

error: Expression [0]:18:31: could not find builtin 'Bool' type
    var ___lldb_expr_failed = False
                              ^

expression failed to parse (no further compiler diagnostics)

### Steps to reproduce

- Installed Mojo and tried to run hello world

### System information

```shell
- Ubuntu 22.04
- Modular 0.1.4
- Mojo 0.2.1
```

**Comment by schliffen** [comment]
This could happen if you did not properly set mojo path in the modular config - as in my experience

**Comment by Abusheik008** [comment]
Is it possible to run the 'mojo' command in the command prompt without setting up the PATH variable? By default, when you type a command in the command prompt, the system looks for that command in the directories specified in the PATH variable. If the directory containing the 'mojo' executable is not included in the PATH, the 'mojo' command won't be recognized as a valid command.

**Comment by anehrani** [comment]
Did you try reinstallation?

**Comment by Abusheik008** [comment]
i did still the same error

**Comment by mzggr0914** [comment]
me 2

**Comment by walter-erquinigo** [comment]
This should be now fixed. Just remember that you need to have the modular home in your path to use the REPL properly, as mentioned in the installation guide.
Please reopen if this happens again.
