### ISSUE TITLE
[BUG]: error: unable to locate module 'importlib'

### ISSUE THREAD

**Issue by svihar** [modularml/mojo#618]
### Bug description

Running the following:

```
import importlib

def main():
    print("hello")
```
Results in:

```
hello.mojo:1:8: error: unable to locate module 'importlib'
import importlib
```
Running it in python3 does not show any errors.

### Steps to reproduce

- Copy the above code into a file: ```hello.mojo```
- Run using ```mojo hello.mojo```
- Run using ```python3 hello.mojo```

### System information

```shell
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

mojo 0.2.1 (64d14e85)
modular 0.1.4 (6b54d308)

memory         8GiB System memory
processor      Intel(R) Core(TM) M-5Y71 CPU @ 1.20GHz
bridge         Broadwell-U Host Bridge -OPI
```

**Comment by oskgo** [comment]
You currently have to use the `python` module for python imports. Have a look at https://docs.modular.com/mojo/stdlib/python/python.html and https://docs.modular.com/mojo/programming-manual.html#python-integration

**Comment by svihar** [comment]
```
from python import Python
```

followed by:

```
importlib = Python.import_module("importlib")
```

works for me.

**Comment by ematejska** [comment]
Great, closing.
