### ISSUE TITLE
[BUG]: debug_assert not working in debug build

### ISSUE THREAD

**Issue by Ivo-Balbaert** [modularml/mojo#622]
### Bug description

The [docs](https://docs.modular.com/mojo/stdlib/builtin/debug_assert.html) state that `debug_assert` works in debug builds.
This doesn't seem to work.

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.
The following code (copied from the docs) in debug_assert1.mojo: 
```py
fn test_debug_assert[x: Int](y: Int):
    debug_assert(x == 42, "x is not equal to 42")
    debug_assert(y == 42, "y is not equal to 42")

fn main():
    test_debug_assert[1](2)
I expected it to say: x is not equal to 42
```

When called with `mojo --debug-level full debug_assert1.mojo` doesn't give any output.

The command uses the --debug-level full flag, so I presume this is a debug build. Then the debug_assert should fail, and show the error, but this does not happen.

### System information

```shell
- What OS did you do install Mojo on ? 
Ubuntu 22 in WSL on Windows 11
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.2.1 (64d14e85)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.1.2
```

**Comment by ksandvik** [comment]
Try 
from Assert import debug_assert

**Comment by Mogball** [comment]
Debug assert doesn't work at the moment in the SDK release. This is an oversight on our part. Stay tuned!

**Comment by lattner** [comment]
@Mogball did this get fixed by any chance?

**Comment by Mogball** [comment]
This didn't. Perhaps we need to clarify that `-debug-level full` and "debug" build are different things. Debug assert will trigger warnings with `-D ASSERT_WARNING`

**Comment by Ivo-Balbaert** [comment]
Ok, then this was a misunderstanding of my part. If this clarification is added to the docs (https://docs.modular.com/mojo/stdlib/builtin/debug_assert.html), this issue can be closed.

**Comment by guidorice** [comment]
I just tried `-D ASSERT_WARNING` and found it hard to distinguish stdlib assertions from my own code. Is there any way to print the module + line number where the warnings are coming from?

Example assertions I triggered somehow from stdlib- sorry don't have a clean repro script for this:

```
Assert Warning: rank must be 1
Assert Warning: invalid rank value
```
I guess the same issue exists with `testing.assert_true`, no way to tell where the ASSERT ERROR messages are coming from.

**Comment by JoeLoser** [comment]
We'll clarify this in the docs for `debug_assert` in the library.  Please do see [my comment on this other GitHub issue](https://github.com/modularml/mojo/issues/1425#issuecomment-1858721086) for enabling assertions in the library explicitly.  Right now, users cannot use `debug_assert` with just specifying `-debug-level full`.  The shipped mojo-sdk is always a "release" build in that sense with regard to `debug_assert`.  This is why I added the explicit option for users to specify `-D MOJO_ENABLE_ASSERTIONS` for now.
