### ISSUE TITLE
[Modular CLI]: no *buntu here

### ISSUE THREAD

**Issue by malv-c** [modularml/mojo#625]
### Issue description

it's not difficult
to make a script that download not found deps then compile them before mojo itself
build & install at user need
also if your concern is to avoid idiot forks simply add bootstrapping of build & install and mojo software to take place in encrypted fs & process + put it on the license
it also enable any cpu
thanks

### Steps to reproduce

no apt too

### Version Info

```shell
all
```

**Comment by bzcheeseman** [comment]
Thanks for the feedback! Closing as there's not an actionable ask here.

**Comment by malv-c** [comment]
i hope to be able to replace python with mojo soon
thanks

Le ven. 8 sept. 2023 à 17:46, Aman LaChapelle ***@***.***> a
écrit :
