### ISSUE TITLE
Installation Failing[BUG]: 

### ISSUE THREAD

**Issue by mosicr** [modularml/mojo#627]
### Bug description

root@cs-375400546402-default:~/.modular/pkg/packages.modular.com_mojo/bin# ./mojo
bash: ./mojo: Permission denied
root@cs-375400546402-default:~/.modular/pkg/packages.modular.com_mojo/bin# ls -ltr mojo
-rwxrwxrwx 1 root root 74171968 Sep  8 08:49 mojo

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
root@cs-375400546402-default:~/.modular/pkg/packages.modular.com_mojo/bin# !lsb
lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
root@cs-375400546402-default:~/.modular/pkg/packages.modular.com_mojo/bin# modular -v
modular 0.1.4 (6b54d308)
```

**Comment by ematejska** [comment]
What was the installation command you ran and what what was the output?

**Comment by bzcheeseman** [comment]
We don't officially support Debian yet - please stay and we'll announce when we add it.
