### ISSUE TITLE
Cannot change OS when downloading Mojo

### ISSUE THREAD

**Issue by czheo** [modularml/mojo#628]
Try to download from https://developer.modular.com/download for a different OS but the dropdown will not change. See screenshot:

https://github.com/modularml/mojo/assets/1692400/63c288ce-4ffb-4cf3-b04f-b225287e7c01

**Comment by ismail** [comment]
Note that you are leaking part of your authkey.

**Comment by robert-j-webb** [comment]
I can not replicate this, curious if you get the same experience in an incognito tab? Maybe there's some issue with an extension?
