### ISSUE TITLE
[BUG]: Space in project path not supported

### ISSUE THREAD

**Issue by patchie** [modularml/mojo#630]
### Bug description

I run the following command in WSL(win11): /mnt/c/WSL# /root/.modular/pkg/packages.modular.com_mojo/bin/mojo /mnt/c/WSL/Mojo🔥 test/hello.🔥

Error message: /root/.modular/pkg/packages.modular.com_mojo/bin/mojo: error: no such command '/mnt/c/WSL/Mojo🔥'

So it seems that it doesnt support space in the project path.

As soon as i changed the directory space with a dash, it works.

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

1. Create a path with space
2. create a mojo file
3. try to run it, you will get the error

### System information

```shell
- What OS did you do install Mojo on ? win11(WSL2)
- Provide version information for Mojo by pasting the output of `mojo -v`: mojo 0.2.1 (64d14e85)
- Provide Modular CLI version by pasting the output of `modular -v`: modular 0.1.4 (6b54d308)
```

**Comment by cversek** [comment]
This doesn't look like a real bug to me.  By putting a space in the "path", you are actually sending `/mnt/c/WSL/Mojo🔥` as the first argument to the `mojo` program.

**Comment by Mogball** [comment]
@cversek is correct. You need to surround the whole path in a string or escape the space.
