### ISSUE TITLE
[Dev Console]: Not able to install mojo in windows using using utbuntu LTS

### ISSUE THREAD

**Issue by aviralshastri** [modularml/mojo#631]
### Issue description

![Ubuntu 22 04 2 LTS 08-09-2023 17_06_41](https://github.com/modularml/mojo/assets/104085688/8e63b9a1-f52d-4c34-9216-d34fbc6e613e

when i use "modular install mojo" it gets stucked and i am trying it to get for 2 hours and still its stucked, i have done everything correctly that are given in documentation but still.

### Steps to reproduce

just follow every step from documentation:

install "Ubuntu LTS"

run Ubuntu LTS for wsl: "curl https://get.modular.com | \
  MODULAR_AUTH=mut_53edc179b556456ca0f25bb333f26595 \
  sh - "
  
 then run this in Ubuntu LTS for wsl: "modular install mojo"
 
 now it will be stucked in "TEST: `mojo test_python.mojo`... OK" line

**Comment by spectrvrc** [comment]
Able to replicate this issue with Ubuntu 22.04 LTS on WSL2

**Comment by brahmbones** [comment]
Ahh, ok.   Thats a bummer.  I was stuck in the same place as you with windows 10 and Ubuntu @ the mojo test_python.mojo state.  I changed over to WSL2 from WSL1 and now it is working.  I did leave it run for awhile. (also restarted the computer a couple of times).

**Comment by drunkwcodes** [comment]
Maybe the same issue as https://github.com/modularml/mojo/issues/538 which can be solved.
