### ISSUE TITLE
Cna

### ISSUE THREAD

**Issue by Aliraqimustafa** [modularml/mojo#639]
### Issue description

I can't install mojo using Modular CLI 
![image](https://github.com/modularml/mojo/assets/126193386/17ab2a54-fb5d-4c5c-aa14-8c9feeb07795)

The downloading is stop at "# Found release for https://packages.modular.com/mojo @ 0.2.1, installing to /home/ha12qw/.modular/pkg/packages.modular.com_mojo"

### Steps to reproduce

![image](https://github.com/modularml/mojo/assets/126193386/71dfeaa2-1138-4fb8-baf1-a4d17d7e8e1f)

### Version Info

```shell
- modular == 0.1.4 (6b54d308)
- I use Windows and Ubuntu
```

**Comment by bzcheeseman** [comment]
It can sometimes take a while, what are the parameters of your internet connection?

**Comment by jackos** [comment]
Fixed in a prior release
