### ISSUE TITLE
[BUG]: Address boundary error when running a built binary

### ISSUE THREAD

**Issue by visheratin** [modularml/mojo#643]
### Bug description

When I try a simple code example that imports an arbitrary Python package, running the `.mojo` file from VS Code works fine. But when I build the binary, I get a SIGSEGV error.

### Steps to reproduce

Example code:

```
from python import Python


fn main():
    try:
        let onnxruntime = Python.import_module("onnxruntime")
        print(onnxruntime)
    except:
        pass
```

The command that I use (btw it would be super cool if binaries were fully standalone):

```
MOJO_PYTHON_LIBRARY=/usr/lib/libpython3.8.so ./main
```

The output from the console (in Fish):

```
fish: 'MOJO_PYTHON_LIBRARY=/usr/lib/li…' terminated by signal SIGSEGV (Address boundary error)
```

The output from the console (in Bash):

```
Segmentation fault
```

And the output when I run just `.mojo` file:

```
<module 'onnxruntime' from '/usr/local/lib/python3.8/dist-packages/onnxruntime/__init__.py'>
```

### System information

```shell
- What OS did you do install Mojo on: Ubuntu 20.04.4 on WSL 2
- Provide version information for Mojo: mojo 0.2.1 (64d14e85)
- Provide Modular CLI version: modular 0.1.4 (6b54d308)
```

**Comment by willghatch** [comment]
For what it's worth, on MacOS I don't get a segfault in the same case.  But I do get a segfault with the same binary if I don't provide `MOJO_PYTHON_LIBRARY`.  We'll look into this more.

**Comment by JoeLoser** [comment]
I cannot reproduce this issue if:

1. The Python package is installed in your Python environment
2. `MOJO_PYTHON_LIBRARY` is properly set

Feel free to re-open this issue if you have a better reproducer.
