### ISSUE TITLE
[Modular CLI]: Unable to install Modular CLI

### ISSUE THREAD

**Issue by ParadaCarleton** [modularml/mojo#646]
### Issue description

The Github is missing the instructions to set up a container.

### Steps to reproduce
```bash
[user@user-public ~]$ curl https://get.modular.com | \
  MODULAR_AUTH=**** \
  sh -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3176  100  3176    0     0  14573      0 --:--:-- --:--:-- --:--:-- 14635
sh: line 57: type: rpm: not found
sh: line 62: type: rpm: not found
Sorry, this system is not recognized. Please visit https://www.modular.com/mojo to learn about supported platforms. You can also build and run a Mojo container by following instructions at https://github.com/modularml/mojo.
```

**Comment by bzcheeseman** [comment]
It looks like we might not support your platform, sorry. Can you share more information about what you're running on?

**Comment by rajsecrets01** [comment]
1. actually it takes good amount of time to install at this step, may be mojo is big in file size .
2. now do Restart and then put `modular clean`  and again  `modular install mojo`

**Comment by ParadaCarleton** [comment]
> It looks like we might not support your platform, sorry. Can you share more information about what you're running on?

Arch Linux, so I don't have RPM. Is it possible to install Mojo in a container, like the command line message says?

**Comment by realcarlos** [comment]
> It looks like we might not support your platform, sorry. Can you share more information about what you're running on?

M1 MBP ， same issue

**Comment by goldiegadde** [comment]
Arch Linux is not yet supported and adding support is being tracked in https://github.com/modularml/mojo/issues/572, please upvote this ticket to prioritize it

See an example of how to build a dockerfile for Ubuntu 22.04: https://github.com/modularml/mojo/blob/main/examples/docker/Dockerfile.mojosdk
