### ISSUE TITLE
[Feature Request]: Arch linux support

### ISSUE THREAD

**Issue by Av1nag** [modularml/mojo#647]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Please make it available for arch linux as quickly as possible...thank you

### What is your motivation for this change?

Because Most of us are using Arch distro...we're awaiting for it

**Comment by ematejska** [comment]
Duplicate of https://github.com/modularml/mojo/issues/572
