### ISSUE TITLE
[Modular CLI]: Unable to install Modular CLI

### ISSUE THREAD

**Issue by GMakd** [modularml/mojo#648]
### Issue description

"Sorry, this system is not recognized." on macOS ver 14.0 Beta.

### Version Info

```shell
OS: macOS Sonoma 14.0 Beta 
HW: Apple M1
CMD: curl https://get.modular.com | \
  MODULAR_AUTH=mut_93f3d4fab4c9430aab4e6fcc88d715aa \
  sh -
```

**Comment by changeling** [comment]
Are you looking to install on a remote system, or locally on the M1? If the latter, MacOS/Apple Silicon isn't yet supported:

"This initial release of the SDK supports X86/Linux systems, and we will expand to additional operating systems, hardware, and tool features in upcoming updates."
-- https://www.modular.com/blog/mojo-its-finally-here

**Comment by GMakd** [comment]
I am trying to install on my local dev machine. Thanks for mentioning it, I haven't noticed. 
I am looking forward for local installation.
Best Regards

**Comment by goldiegadde** [comment]
this is tracked in https://github.com/modularml/mojo/issues/510 fyi
