### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by rajjanicodes** [modularml/mojo#649]
### Where is the problem?

https://docs.modular.com/mojo/manual/basics/#function-arguments-and-returns

### What can we do better?

Code:
```
fn add(x: Int, y: Int) -> Int:
    return x + y

z = add(1, 2)
print(z)
```

Running the code given above throws an error:
```
test.mojo:4:1: error: TODO: expressions are not yet supported at the file scope level
z = add(1, 2)
```

I believe this should be

```
fn add(x: Int, y: Int) -> Int:
    return x + y

def main():
    z = add(1, 2)
    print(z)
```

### Anything else?

Confirmed this with Jack Clayton on Modular's Discord server.

**Comment by scottamain** [comment]
You're right, and sorry for the confusion. This document is written in a Jupyter notebook where top-level code is allowed (also you can do it in the Mojo REPL). We will improve this. De-duping with https://github.com/modularml/mojo/issues/578
