### ISSUE TITLE
[BUG]: Download the language without being forced to sign in and accepting your terms

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [modularml/mojo#650]
### Bug description

Would be nice to have something open source given the fact that you have built in on top of open source projects

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by FinnT730** [comment]
Yeah.... I hate the fact that I still need to signup, and likely still need to use their notebook....

**Comment by ematejska** [comment]
Please take a look at our FAQ about open source [here](https://docs.modular.com/mojo/faq.html#open-source).

**Comment by FrancescoSaverioZuppichini** [comment]
> Please take a look at our FAQ about open source [here](https://docs.modular.com/mojo/faq.html#open-source).

Are you really closing it without even explain why directly? At least give a tl;dr of the long corpo doc you posted

**Comment by FinnT730** [comment]
> Please take a look at our FAQ about open source [here](https://docs.modular.com/mojo/faq.html#open-source).

We never said to open source it. We are saying to not force a signup process to get the download. And even then, it will be a Jupyter Notebook, AFAIK. 
You are single handily making me not even consider using this, or even benchmarking it either to get those 7x faster speeds then C++

**Comment by FrancescoSaverioZuppichini** [comment]
> You are single handily making me not even consider using this, or even benchmarking it either to get those 7x faster speeds then C++

Same felling here, crazy to thing that a tool meant for the biggest open source community ever exists is closed and required auth -I thought I've never seen this day

**Comment by FrancescoSaverioZuppichini** [comment]
> Please take a look at our FAQ about open source [here](https://docs.modular.com/mojo/faq.html#open-source).

Reading from the link

*Why not develop Mojo in the open from the beginning?
Mojo is a big project and has several architectural differences from previous languages. We believe a tight-knit group of engineers with a common vision can move faster than a community effort. This development approach is also well-established from other projects that are now open source (such as LLVM, Clang, Swift, MLIR, etc.).*

Which I 100% get it, however you can just make it available to download without an auth and accepting your terms moreover I honestly do not get the cons of having a repo on github with the current version allowing people to report bugs and use it freely expecially since you expect people to use it and keeping it close not only remove adoption but hurt trust at least imho

But mine are empty words, if they choose this way it is what it is - nice project, nice videos - I think I'll skip it for now, let's see in the future - such a waste

**Comment by drunkwcodes** [comment]
Boring thread.

**Comment by FrancescoSaverioZuppichini** [comment]
> Boring thread.

go watch some rick and morty then

**Comment by FinnT730** [comment]
> Boring thread.

Why?
Hell, I can't even use the "compiler".
As of now, as long as I can't test my own suite of benchmarks, their claims are just marketing.
