### ISSUE TITLE
Mojo is Not Downloading

### ISSUE THREAD

**Issue by SulimanAbdulrazzaq** [modularml/mojo#651]
### Bug description

Mojo has released its first version. I have a download error when I download it, it stops at that point in the image below
                                                   ![](https://i.stack.imgur.com/OlUt9.png)

When I waited for it, I could not stand it. I waited a whole day, and this is how to download this for Windows. I tried the  Linux system. but the same error

I walked step by step but I got this error

Does anyone have a solution to this problem?

Windows

**Comment by bzcheeseman** [comment]
Can you give us a little more information about your system?

**Comment by SulimanAbdulrazzaq** [comment]
> Can you give us a little more information about your system?

yeah absolutely
Windows 10 pro
, 64bit ,
processer:i7 5600U,2.60 GHz
ram:16

**Comment by bzcheeseman** [comment]
I think you likely don't have enough RAM (though I'm going to kick it over to the mojo tooling folks to confirm this) - this is a known issue and we are absolutely working on a fix. Please stay tuned!

**Comment by SulimanAbdulrazzaq** [comment]
> I think you likely don't have enough RAM (though I'm going to kick it over to the mojo tooling folks to confirm this) - This is a known issue and we are absolutely working on a fix. Please stay tuned!
Thank you and I hope you solve this problem as soon as possible
Tell me if you fixed the problem and tell me what is the reason because I am 14 years old and have good experience in programming so explain it to me as a beginner.
If so, can you let me know when the issue will be resolved?
How long will ram 16th take to finish installing mojo?
I hope that this problem will be solved as soon as possible.

**Comment by heera9331** [comment]
yes, same error in my system
window - 10 64 bit
processor - ryzen 5, 2500u
ram 12GB

**Comment by byfarm** [comment]
Same error for me:
Windows 10 64 bit
Intel(R) Core(TM) i7-10750H CPU
16GB RAM

**Comment by heera9331** [comment]
Everything is completed successfully, at the last moment terminal stuck, I am still waiting 1-2 hours nothing will happen, please help
![Screenshot 2023-09-09 174145](https://github.com/modularml/mojo/assets/71516269/c25c9d95-7a1d-4432-8425-74ea6a9be777)

**Comment by SulimanAbdulrazzaq** [comment]
> Everything is completed successfully, at the last moment terminal stuck, I am still waiting 1-2 hours nothing will happen, Please help ![Screenshot 2023-09-09 174145](https://user-images.githubusercontent.com/71516269/266779934-c25c9d95-7a1d-4432-8425-74ea6a9be777.png)


Same thing

**Comment by SulimanAbdulrazzaq** [comment]
Same thing


![Cap](https://github.com/modularml/mojo/assets/144490671/9ee758a0-4cfe-4407-a96e-7c8e76bf070a)

**Comment by rajsecrets01** [comment]
I think this issue is on windows , better to use ubuntu for now , wait for the stable sdk for windows.

**Comment by SulimanAbdulrazzaq** [comment]
I don't think so, because it tells me is downloading maybe the file is very big
so I need to wait  to download it or the same file has an error, So The modular team is working to fix this error

**Comment by wrogers3** [comment]
same issue here

Same error for me:
Windows 10 64 bit
AMD Ryzen 7 3700X 8 core  CPU
16GB RAM

**Comment by Arif812** [comment]
I had the same error, but on Codespaces, so I instead moved to 4 cores and it worked.

**Comment by SulimanAbdulrazzaq** [comment]
> I had the same error, but on Codespaces, so I instead moved to 4 cores and it worked.

can you explain more to us

**Comment by Arif812** [comment]
Github Codespaces has a feature to choose how many cores you can choose, I chose 2, and it didn't work, so I moved to 4 cores and it worked. I'm assuming you are not using Github Codespaces, so try using `cat /etc/os-release` on Linux. As for Windows, there is no native support as of right now so I cannot be of assistance.

**Comment by SulimanAbdulrazzaq** [comment]
> 

Oh I am Windows , thank you

**Comment by its-ogawa** [comment]
I have the same problem.

But if 16GB of RAM isn't enough, I can't use it casually.

**Comment by byfarm** [comment]
I upgraded my wsl from version 1 to version 2 and it worked.

**Comment by SulimanAbdulrazzaq** [comment]
> I upgraded my wsl from version 1 to version 2 and it worked.

How Many rams do you have

**Comment by jackos** [comment]
Issue fixed in next release, closing in favor of #538 see [here for workarounds](https://github.com/modularml/mojo/issues/538#issuecomment-1716908244)

**Comment by SulimanAbdulrazzaq** [comment]
> Issue fixed in next release, closing in favor of #538 see [here for workarounds](https://github.com/modularml/mojo/issues/538#issuecomment-1716908244)

But I want to know when the new release will released
