### ISSUE TITLE
[Modular CLI]: unable to install mojo

### ISSUE THREAD

**Issue by martireg** [modularml/mojo#652]
### Issue description

 Got an error when trying to install mojo and different commands on the modular cli

### Steps to reproduce

- Got an error when trying to install mojo and different commands on the modular cli

```bash
ubuntu@instance-20230512-2135:~/mojo$ modular --version
modular 0.1.4 (6b54d308)
ubuntu@instance-20230512-2135:~/mojo$ modular install mojo
modular: error: Could not open cache index 0 size: No such file or directory
ubuntu@instance-20230512-2135:~/mojo$ modular host-info
modular: error: Could not open cache index 0 size: No such file or directory
ubuntu@instance-20230512-2135:~/mojo$ modular auth
modular: error: no token provided

ubuntu@instance-20230512-2135:~/mojo$ neofetch
OS: Ubuntu 22.04.3 LTS aarch64
Host: KVM Virtual Machine virt-4.2
Kernel: 5.15.0-1037-oracle
Uptime: 12 mins
Packages: 2093 (dpkg), 8 (snap)
Shell: bash 5.1.16
Resolution: 1024x768
Terminal: /dev/pts/0
CPU: (4)
GPU: 00:01.0 Red Hat, Inc. Virtio GPU
Memory: 349MiB / 23987MiB

```

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.1.4 (6b54d308)
- What OS did you install modular CLI on ?
OS: Ubuntu 22.04.3 LTS aarch64 (oracle cloud VM)
```

**Comment by bzcheeseman** [comment]
We don't currently support aarch64, sorry. Please stay tuned :)

**Comment by pythoninthegrass** [comment]
From #603:
> HI @z4y1b2 Apple Silicon isn't supported yet, even through QEMU or Rosseta x86-64 emulation like OrbStack uses. We're working on native Apple Silicon support, but please upvote this ticket: #510 

(Also upvoted as an M1 / OrbStack user)

**Comment by IamShubhamGupto** [comment]
> We don't currently support aarch64, sorry. Please stay tuned :)

Is it possible for aarch64 to get support in the next couple of months? Would really benefit from mojo's efficiency for running pipelines on Nvidia Jetsons (aarch64)
