### ISSUE TITLE
Will mojo be available for android[Feature Request]

### ISSUE THREAD

**Issue by AnthonyTheKoala** [modularml/mojo#656]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Dear modular,
I see all the major OS such as Linux, MS Win are supported.  

But what about android?

Thank you
Anthony, Sydney

### What is your motivation for this change?

I would like to write programs in python for the android OS

**Comment by AnthonyTheKoala** [comment]
Put it another way. 
Can a Linux version be downloaded on my android phone AND what additional tasks are needed to make the Linux version of mojo operable on android.

Thank you
Anthony, Sydney

**Comment by drunkwcodes** [comment]
I think it will be figured out soon once it's open source.

**Comment by drannex42** [comment]
I haven't tried it yet, but you *could* install Mojo under something like Termux on android and access it from there, using Termux as a sort of backend container VM for Mojo, same could be said for iOS. 

That, or packaging it inside a WebAssembly build of a Linux distro...

**Comment by b9Joker108** [comment]
> I haven't tried it yet, but you _could_ install Mojo under something like Termux on android and access it from there, using Termux as a sort of backend container VM for Mojo, same could be said for iOS.
> 
> That, or packaging it inside a WebAssembly build of a Linux distro...

I don't really understand these two options, could someone please explain them?
