### ISSUE TITLE
[BUG]: Assumes scaling_cur_freq and scaling_max_freq exist (they don't on WSL Ubuntu 22.04)

### ISSUE THREAD

**Issue by dsharlet** [modularml/mojo#664]
### Bug description

Trying to run `matmul.mojo` example produces this output:
```a$ mojo matrix.mojo
Throughput of a 128x128 matrix multiplication in Python:
[10177:10177:20230909,001227.145988:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[10177:10177:20230909,001227.146032:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.      Program arguments: mojo matrix.mojo
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  mojo      0x00005616d23be957
1  mojo      0x00005616d23bc52e
2  mojo      0x00005616d23bf02f
3  libc.so.6 0x00007f4a97adf520
Segmentation fault
```

I tried to reduce the example as much as possible, but even after stripping out `Benchmark` references, I was still running into this as soon as I ran a program that used `vectorize_unroll`.

### Steps to reproduce

- Copy https://github.com/modularml/mojo/blob/main/examples/matmul.mojo to a local matmul.mojo
- `mojo matmul.mojo`

### System information

```shell
- Windows 11, WSL, Ubuntu 22.04
- mojo 0.2.1 (64d14e85)
- modular 0.1.4 (6b54d308)
```

**Comment by HenryQuan** [comment]
I got the exact issue on Windows 11 WSL Ubuntu 22.04 but only after I exported `MOJO_PYTHON_LIBRARY` to bash. By `unset`ing it, my mojo files could run again successfully.

**Comment by jackos** [comment]
Thanks very much for reporting this back @HenryQuan

**Comment by jackos** [comment]
Could be a variety of issues @dsharlet, please try updating to latest `mojo` binary, setting LLVM_SYMOBLIZER path: https://gist.github.com/trevorhobenshield/6bca58f947ad6115a113a97072df1a73 and reporting back the error if there still is one thanks.
