### ISSUE TITLE
[BUG]: A crash happend in the mojo parser with the current version of the file.

### ISSUE THREAD

**Issue by luxkatana** [modularml/mojo#667]
### Bug description

I used the vscode extension for mojo language support. It gave me this error in vscode
```
A crash happend in the mojo parser with the current version of the file. Please report this issue in https://github.com/modularml/mojo/issues along with all the relevant source codes with the current contents.
```
code:
```py
def fibonanci(n: Int) -> Int:
    if n in [1, 2]:
        return 1
    return fibonanci(n - 1) * n

fn main():
    pass
```
![image](https://github.com/modularml/mojo/assets/57036931/54bc610d-5703-45b6-8396-df1a9138f611)

### Steps to reproduce

```py
def fibonanci(n: Int) -> Int:
    if n in [1, 2]:
        return 1
    return fibonanci(n - 1) * n

fn main():
    pass
```
mojo vscode. Parser crashed report at github

### System information

```shell
os: Windows(WSL)
mojo version: mojo 0.2.1 (64d14e85)
modular version: modular 0.1.4 (6b54d308)
```

**Comment by drunkwcodes** [comment]
Note: your function should be named as "factorial".

**Comment by luxkatana** [comment]
Thats a naming convention mistake. It wanted to continue but I assume it is not that problem.

**Comment by Mogball** [comment]
This also crashes the parser normally. Thanks for reporting!

**Comment by luxkatana** [comment]
> This also crashes the parser normally. Thanks for reporting!

How is that possible? Is it by any chance a reserved keyword?

**Comment by MustardWithRice** [comment]
I suffer from the same problem too

**Comment by Zinwaiyan274** [comment]
I still face that error

**Comment by hazulifidastian** [comment]
This code produce same error.

```
@value  # <-- Error here
struct MyPet:
    var name: String
    var age: Int

    fn __del__(owned self):
        print("Destruct", self.name)


fn main():
    pass
```

### System Information

```
os: Windows 11(WSL 2)
mojo version: mojo 0.6.1 (876ded2e)
modular version: modular modular 0.3.1 (589ce200)
```

**Comment by stumpOS** [comment]
I was unable to reproduce the crash on 0.7. Instead I got the error message "The operation `in` is not yet supported.". I will check to see if there is a feature request open to support this.
