### ISSUE TITLE
[Dev Console]: Modular CLI installation fails, cuda/cudnn "Release" not found

### ISSUE THREAD

**Issue by Silzinc** [modularml/mojo#669]
### Issue description

Hello,
I am using Pop! OS version 22.04 with codename jammy and arch x86_64. I have g++ and clang++ installed, 16 GiB RAM, Python 3.10.12 installed. I tried the command `curl https://get.modular.com | MODULAR_AUTH=<auth_token> sh -` on bash in addition the manual installation commands described [here](https://developer.modular.com/download). I got the following output (sorry my OS is in French) :
```sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3176  100  3176    0     0  49648      0 --:--:-- --:--:-- --:--:-- 50412
Executing the  setup script for the 'modular/installer' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=pop  version=22.04  codename=jammy  arch=x86_64  
 >>>>:
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
   OK: Checking for apt signed-by key support ...
   OK: Importing 'modular/installer' repository GPG keys ...
   OK: Checking if upstream install config is OK ...
   OK: Installing 'modular/installer' repository via apt ...
 NOPE: Updating apt repository metadata cache ...
Failed to update via apt-get update
Réception de :1 file:/var/cuda-repo-ubuntu2204-12-1-local  InRelease
Ign :1 file:/var/cuda-repo-ubuntu2204-12-1-local  InRelease
Réception de :2 file:/var/cudnn-local-repo-ubuntu2204-8.9.4.25  InRelease
Ign :2 file:/var/cudnn-local-repo-ubuntu2204-8.9.4.25  InRelease
Réception de :3 file:/var/cuda-repo-ubuntu2204-12-1-local  Release
Err :3 file:/var/cuda-repo-ubuntu2204-12-1-local  Release
  Fichier non trouvé - /var/cuda-repo-ubuntu2204-12-1-local/Release (2: Aucun fichier ou dossier de ce type)
Réception de :4 file:/var/cudnn-local-repo-ubuntu2204-8.9.4.25  Release
Err :4 file:/var/cudnn-local-repo-ubuntu2204-8.9.4.25  Release
  Fichier non trouvé - /var/cudnn-local-repo-ubuntu2204-8.9.4.25/Release (2: Aucun fichier ou dossier de ce type)
Atteint :5 http://packages.microsoft.com/repos/code stable InRelease
Atteint :7 http://apt.pop-os.org/proprietary jammy InRelease
Atteint :6 https://hub-dist.unity3d.com/artifactory/hub-debian-prod-local stable InRelease
Réception de :8 https://dl.modular.com/public/installer/deb/pop jammy InRelease [5 076 B]
Atteint :9 http://apt.pop-os.org/release jammy InRelease
Atteint :10 https://download.sublimetext.com apt/stable/ InRelease
Atteint :11 http://apt.pop-os.org/ubuntu jammy InRelease
Atteint :12 http://apt.pop-os.org/ubuntu jammy-security InRelease
Atteint :13 http://apt.pop-os.org/ubuntu jammy-updates InRelease
Atteint :14 http://apt.pop-os.org/ubuntu jammy-backports InRelease
Lecture des listes de paquets…
E: Le dépôt file:/var/cuda-repo-ubuntu2204-12-1-local  Release ne contient plus de fichier Release.
E: Le dépôt file:/var/cudnn-local-repo-ubuntu2204-8.9.4.25  Release ne contient plus de fichier Release.
W: https://hub.unity3d.com/linux/repos/deb/dists/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
 ^^^^: ... Failed to update via apt-get update - Context above.
 !!!!: Oh no, your setup failed! :-( ... But we might be able to help. :-)
 !!!!: 
 !!!!: You can contact Modular for further assistance.
 !!!!:
```
From what I understand, it seems I don't have the `/var/cuda-repo-ubuntu2204-12-1-local/Release` and `/var/cudnn-local-repo-ubuntu2204-8.9.4.25/Release` file/repos, or that I cannot fetch it (not sure what the command is supposed to do).

I don't really know what to do to solve it at this point and I did not find another issue about this specific installation problem. Thank you kindly if you can solve this.

### Steps to reproduce

`curl https://get.modular.com | MODULAR_AUTH=<auth_token> sh -`

**Comment by SimplyYummy** [comment]
The issue you're encountering looks related to `apt-get update` failing to update your package metadata. This failure isn't directly related to the `modular` installation but seems to be blocking it. Specifically, the problem is with these two local repositories:

1. `/var/cuda-repo-ubuntu2204-12-1-local`
2. `/var/cudnn-local-repo-ubuntu2204-8.9.4.25`

Both of these repositories appear to be missing their `Release` files, causing the update to fail.


Here are some steps you can take to troubleshoot this issue:


### Step 1: Remove or Comment Out Problematic Repositories

Edit your `/etc/apt/sources.list` and `/etc/apt/sources.list.d/*.list` files to remove or comment out the lines referring to the problematic repositories.

1. **Backup your current sources lists just in case:**

    ```bash
    sudo cp /etc/apt/sources.list /etc/apt/sources.list.backup
    sudo cp -r /etc/apt/sources.list.d /etc/apt/sources.list.d.backup
    ```

2. **Edit the main sources list:**

    ```bash
    sudo nano /etc/apt/sources.list
    ```

    Comment out lines referring to the problematic repositories by placing a `#` at the beginning of each line.

3. **Edit additional sources:**

    You might also find these lines in files inside the `/etc/apt/sources.list.d/` directory. Check there as well:

    ```bash
    sudo nano /etc/apt/sources.list.d/some-file.list
    ```

    Again, comment out the lines referring to the problematic repositories.

### Step 2: Run `apt-get update` Again

After editing these files, try running `apt-get update` again to see if the issue is resolved:

```bash
sudo apt-get update
```

### Step 3: Re-Run the Modular Installer

If `apt-get update` runs without any issues, try running the Modular installer again.

### Step 4: Revert Changes If Needed

If things go south, you can always revert your changes:

```bash
sudo cp /etc/apt/sources.list.backup /etc/apt/sources.list
sudo cp -r /etc/apt/sources.list.d.backup/* /etc/apt/sources.list.d/
```

**Please note that manually editing system configuration files can be risky; always make sure to backup any file you intend to edit.**

**Comment by Silzinc** [comment]
This worked like butter, thank you !

**Comment by SimplyYummy** [comment]
Also noting that PopOS isn't technically support at the moment. Please see the system requirements on the `get-started` docs page. https://docs.modular.com/mojo/manual/get-started/#system-requirements

```
System requirements
To use the Mojo SDK, you need a system that meets these specifications:

Ubuntu 20.04/22.04 LTS
x86-64 CPU and a minimum of 8 GiB memory
Python 3.8 - 3.10
g++ or clang++ C++ compiler
```

**Comment by SimplyYummy** [comment]
Great, Good to hear! @Silzinc

**Comment by jli113** [comment]
does mojo support AMD cards?
