### ISSUE TITLE
[Feature Request] Reinitialize PythonObject with list and tuple literals

### ISSUE THREAD

**Issue by JunzhiShen** [modularml/mojo#67]
### Motivation
**[Python Integration]** Init python object of lists/tuples with Mojo ListLiteral.

### Description and Requirements

Mojo code like this:
`let list_mojo = [1]`
`list_python  = list_mojo`

I will get error msg like following: 

`error: Expression [3]:17:20: 'ListLiteral[[!kgen.declref<_"$Int"::_Int>]]' does not implement the '__copyinit__' method
    list_python  = list_mojo`

I think Mojo is a superset of python, it should support work like A language which type system work well.

**Comment by Mogball** [comment]
`list_mojo` in this case is not a python object and cannot be reassigned because it's a specific parameterized list literal type. This folds into a larger issue about literal promotion that we need to solve, so I'm closing in favour of tracking that issue specifically.
