### ISSUE TITLE
[Docs] cap in Pointer[T].alloc

### ISSUE THREAD

**Issue by spoonbobo** [modularml/mojo#671]
### Where is the problem?

https://docs.modular.com/mojo/programming-manual.html#mojo-types-are-just-parameter-expressions

### What can we do better?

Can anyone explain `self.cap = size * 2` this line of code? For what purposes it was multiplied by 2 and use in allocation?

From my side, I've tried
```
fn __init__(inout self, size: Int, value: T):
        # weird when size does not multiply with 2 it also works
        self.cap = 1
        self.size = size
        self.data = Pointer[T].alloc(self.cap)
        for i in range(self.size):
```

The example also works (all elements got printed out), any rule of thumb in Pointer allocating memory in there?

**Comment by Ivo-Balbaert** [comment]
cap represents a capacity, a reserved memory space for the array,  2 x size is just a reasonable guess

**Comment by spoonbobo** [comment]
Thanks @Ivo-Balbaert , but how come with `self.cap = 1` it still works?

**Comment by Ivo-Balbaert** [comment]
The __init__ method is where this type is defined. The value 1 is indeed ridiculous for an Array, so it should contain something like:
if self.cap < size:
    self.cap = 2 x size

**Comment by scottamain** [comment]
Thanks for reporting this! Indeed, the `cap` value here is not necessary (although it might be useful for other data types that have flexible sizes). I'll remove `cap` and just use `size` for this example.

**Comment by scottamain** [comment]
This will be fixed in the next docs update. Thanks again!

**Comment by spoonbobo** [comment]
@scottamain my pleasure to contribute! fyr yesterday I created a [PR](https://github.com/modularml/mojo/pull/721) to improve our examples too, feel free to check out :)
