### ISSUE TITLE
[Modular CLI]: Can't install `mojo`

### ISSUE THREAD

**Issue by Nusab19** [modularml/mojo#674]
### Issue description

When I try to install mojo by the following command,
`modular install mojo`, it stucks there for couple of minutes. Then I get this error message.
Note: It consumes around 100KB/s while stuck.

```
# Found release for https://packages.modular.com/mojo @ 0.2.1, installing to /home/nusab19/.modular/pkg/packages.modular.com_mojo
modular: error: failure detected - please run `modular clean` and try again
==========================
Failure Information:
        - http error: failed to reach URL https://cas.modular.com/0/zzsBU4M7_PRni9RkhDaLIwddriI8kZ-IN3tuHdHRgcA with cURL error Timeout was reached - Looking for zzsBU4M7_PRni9RkhDaLIwddriI8kZ-IN3tuHdHRgcA
        - http error: failed to reach URL https://cas.modular.com/0/3gaIj2AlD3uvLG96tTQVO02qw_EwfMb9NxuPbkal7AM with cURL error Timeout was reached - Looking for 3gaIj2AlD3uvLG96tTQVO02qw_EwfMb9NxuPbkal7AM
        - http error: failed to reach URL https://cas.modular.com/0/IL1yVe7xxx6YS8jL85AIzLbh5iqTqXuIx8sZCaP1HW0 with cURL error Timeout was reached - Looking for IL1yVe7xxx6YS8jL85AIzLbh5iqTqXuIx8sZCaP1HW0
        - http error: failed to reach URL https://cas.modular.com/0/q5b6U54yqL_Sb6JVpXnitj4-6jq4SZqtvSKvwOP_GdU with cURL error Timeout was reached - Looking for q5b6U54yqL_Sb6JVpXnitj4-6jq4SZqtvSKvwOP_GdU
        - http error: failed to reach URL https://cas.modular.com/0/wjAzLkHpboXqCL5JxH1BQiy9z8_-gbEN5djiTr7q1EM with cURL error Timeout was reached - Looking for wjAzLkHpboXqCL5JxH1BQiy9z8_-gbEN5djiTr7q1EM
        - http error: failed to reach URL https://cas.modular.com/0/m0ZaP4BF9UO159jwf44Qt-wDuhxiP7RZHTjylxUNEs8 with cURL error Timeout was reached - Looking for m0ZaP4BF9UO159jwf44Qt-wDuhxiP7RZHTjylxUNEs8
==========================
```

My internet connection is not so slow and not so fast. It's about 10 Mb/s. I don't have issues downloading other things, but when installing **mojo**, I get this. I've tried this couple of times.

### Steps to reproduce

Follow steps 1, 2 and 3 from https://developer.modular.com/download

And in the 4th step, the error occurs.

### Version Info

```shell
- Modular CLI version: `modular 0.1.4 (6b54d308)`
- OS: 
nusab19@DESKTOP-OII6U4H
-----------------------
OS: Ubuntu 22.04.2 LTS on Windows 10 x86_64
Kernel: 4.4.0-19041-Microsoft
Uptime: 45 mins
Packages: 568 (dpkg)
Shell: bash 5.1.16
Terminal: Windows Terminal
CPU: 12th Gen Intel i5-1235U (12) @ 1.300GHz
Memory: 5401MiB / 7865MiB
```

**Comment by JustFrederik** [comment]
@Nusab19 i think the download links where down. I had the same issue 10 minutes ago, but it works now

**Comment by IAmKachi** [comment]
It's quite slow... I don't know why. If you encounter an error, run `modular clean` before making another attempt

**Comment by Nusab19** [comment]
> It's quite slow... I don't know why. If you encounter an error, run `modular clean` before making another attempt

I did that every time. Nothing changed.

**Comment by Nusab19** [comment]
@JustFrederik The way they are letting people download mojo is kinda annoying.
I've never seen any website forcing people to **sign up** to download a programming language.

**Comment by aarsalannazari** [comment]
# Found release for https://packages.modular.com/mojo @ 0.2.1, installing to /home/arsalan/.modular/pkg/packages.modular.com_mojo
ll lib\

;
modular: error: failure detected - please run `modular clean` and try again
==========================
Failure Information:
        - http error: failed to reach URL https://cas.modular.com/0/zzsBU4M7_PRni9RkhDaLIwddriI8kZ-IN3tuHdHRgcA with cURL error Timeout was reached - Looking for zzsBU4M7_PRni9RkhDaLIwddriI8kZ-IN3tuHdHRgcA
        - http error: failed to reach URL https://cas.modular.com/0/3gaIj2AlD3uvLG96tTQVO02qw_EwfMb9NxuPbkal7AM with cURL error Timeout was reached - Looking for 3gaIj2AlD3uvLG96tTQVO02qw_EwfMb9NxuPbkal7AM
        - http error: failed to reach URL https://cas.modular.com/0/IL1yVe7xxx6YS8jL85AIzLbh5iqTqXuIx8sZCaP1HW0 with cURL error Timeout was reached - Looking for IL1yVe7xxx6YS8jL85AIzLbh5iqTqXuIx8sZCaP1HW0
        - http error: failed to reach URL https://cas.modular.com/0/q5b6U54yqL_Sb6JVpXnitj4-6jq4SZqtvSKvwOP_GdU with cURL error Timeout was reached - Looking for q5b6U54yqL_Sb6JVpXnitj4-6jq4SZqtvSKvwOP_GdU
        - http error: failed to reach URL https://cas.modular.com/0/wjAzLkHpboXqCL5JxH1BQiy9z8_-gbEN5djiTr7q1EM with cURL error Timeout was reached - Looking for wjAzLkHpboXqCL5JxH1BQiy9z8_-gbEN5djiTr7q1EM
        - http error: failed to reach URL https://cas.modular.com/0/BIk47S55RIPZ7NnUP4jGFzs00J-5NWLwWpLZ8Dvst24 with cURL error Couldn't resolve host name - Looking for BIk47S55RIPZ7NnUP4jGFzs00J-5NWLwWpLZ8Dvst24
        - http error: failed to reach URL https://cas.modular.com/0/m0ZaP4BF9UO159jwf44Qt-wDuhxiP7RZHTjylxUNEs8 with cURL error Timeout was reached - Looking for m0ZaP4BF9UO159jwf44Qt-wDuhxiP7RZHTjylxUNEs8
==========================

**Comment by aarsalannazari** [comment]
`# Found release for https://packages.modular.com/mojo @ 0.2.1, installing to /home/arsalan/.modular/pkg/packages.modular.com_mojo
ll lib\

;
modular: error: failure detected - please run `modular clean` and try again
==========================
Failure Information:
        - http error: failed to reach URL https://cas.modular.com/0/zzsBU4M7_PRni9RkhDaLIwddriI8kZ-IN3tuHdHRgcA with cURL error Timeout was reached - Looking for zzsBU4M7_PRni9RkhDaLIwddriI8kZ-IN3tuHdHRgcA
        - http error: failed to reach URL https://cas.modular.com/0/3gaIj2AlD3uvLG96tTQVO02qw_EwfMb9NxuPbkal7AM with cURL error Timeout was reached - Looking for 3gaIj2AlD3uvLG96tTQVO02qw_EwfMb9NxuPbkal7AM
        - http error: failed to reach URL https://cas.modular.com/0/IL1yVe7xxx6YS8jL85AIzLbh5iqTqXuIx8sZCaP1HW0 with cURL error Timeout was reached - Looking for IL1yVe7xxx6YS8jL85AIzLbh5iqTqXuIx8sZCaP1HW0
        - http error: failed to reach URL https://cas.modular.com/0/q5b6U54yqL_Sb6JVpXnitj4-6jq4SZqtvSKvwOP_GdU with cURL error Timeout was reached - Looking for q5b6U54yqL_Sb6JVpXnitj4-6jq4SZqtvSKvwOP_GdU
        - http error: failed to reach URL https://cas.modular.com/0/wjAzLkHpboXqCL5JxH1BQiy9z8_-gbEN5djiTr7q1EM with cURL error Timeout was reached - Looking for wjAzLkHpboXqCL5JxH1BQiy9z8_-gbEN5djiTr7q1EM
        - http error: failed to reach URL https://cas.modular.com/0/BIk47S55RIPZ7NnUP4jGFzs00J-5NWLwWpLZ8Dvst24 with cURL error Couldn't resolve host name - Looking for BIk47S55RIPZ7NnUP4jGFzs00J-5NWLwWpLZ8Dvst24
        - http error: failed to reach URL https://cas.modular.com/0/m0ZaP4BF9UO159jwf44Qt-wDuhxiP7RZHTjylxUNEs8 with cURL error Timeout was reached - Looking for m0ZaP4BF9UO159jwf44Qt-wDuhxiP7RZHTjylxUNEs8
==========================`

this is my error

**Comment by JustFrederik** [comment]
@Nusab19 you mean after setting the auth token it needs some time to generate the download links? I agree the auth stuff is kinda ridiculous.

**Comment by Nusab19** [comment]
@JustFrederik I was talking about this actually.
![image](https://github.com/modularml/mojo/assets/85403795/7493b10a-c319-4dad-9e03-e3aed7fd0ec4)

**Comment by JustFrederik** [comment]
@Nusab19 i know. You need to sign up there. Get an auth token which you need to set with modular auth. to be able to install packages. My therory for this issue was that after signing up modular needs a while to validate your download links or something and that’s why it’s failing. Could be absolutely wrong tho.

**Comment by IKHUpy** [comment]
@Nusab19 try double checking your authentication by command "modular config-list". if its somehow empty. try reinstalling modular from scratch.

p.s. I'm stuck with "modular install mojo" step haha

**Comment by IKHUpy** [comment]
I tried installing Mojo in WSL via VSCode and it worked. Somehow my remote server doesn't.

**Comment by jackos** [comment]
This is due to connection speed, it's a 350mb download and times out after 10mins, we're working on reducing the size of the download. Duplicate closing in favour of: https://github.com/modularml/mojo/issues/598

**Comment by JustFrederik** [comment]
@jackos i got this error after a few seconds.

**Comment by Nusab19** [comment]
> 

It's not empty, it has something like this:
`user.id = mut_5dc3ede93dsfgsd5a248a1efd2312312312`

And I'm also stuck in `modular install mojo` :)

**Comment by Nusab19** [comment]
> 

Instead of reducing the file size, wouldn't it be easier and efficient to increase the timeout?

Or let the user pass it while downloading it?
Like,
`modular install mojo --timeout 30` ( meaning 30 minutes )

**Comment by Nusab19** [comment]
> @Nusab19 i know. You need to sign up there. Get an auth token which you need to set with modular auth. to be able to install packages. My therory for this issue was that after signing up modular needs a while to validate your download links or something and that’s why it’s failing. Could be absolutely wrong tho.

It's network issue + their server's issue. With a decent speed, you can download it. But sometimes even when I have a good speed, the server doesn't serve the file well.

So, it downloads in 50KB/s even though I have 2MB/s bandwith.

**Comment by Nusab19** [comment]
> @Nusab19 i know. You need to sign up there. Get an auth token which you need to set with modular auth. to be able to install packages. My therory for this issue was that after signing up modular needs a while to validate your download links or something and that’s why it’s failing. Could be absolutely wrong tho.

It's network issue + their server's issue. With a decent speed, you can download it. But sometimes even when I have a good speed, the server doesn't serve the file well.

So, it downloads in 50KB/s even though I have 2MB/s bandwidth.

**Comment by calvincaniSA** [comment]
Tried everything I cannot install Mojo. Modular installed fine but trying to install Mojo takes forever but never downloads anything. You just get a bunch of errors. How are you then supposed to use it if you cannot download it. I have a fairly good fiber connection

**Comment by Nusab19** [comment]
@calvincaniSA Lemme guess, you have <=8 GB ram?

What I figured out is this is mainly a ram problem.

**Comment by calvincaniSA** [comment]
I have 8GB ram. Well honestly it's like seeing a product in the window but you cannot buy it because they won't open the door for you.

**Comment by Nusab19** [comment]
> I have 8GB ram. Well honestly it's like seeing a product in the window but you cannot buy it because they won't open the door for you. 

Exactly!

I was so excited to try out mojo. But couldn’t.

There’s one way though.
You can use Github codespace. But you have to chose the 16 GB version. 8 GB will have the same issue.

**Comment by jackos** [comment]
@calvincaniSA @Nusab19 just tested next release as working on 8gb ram 2 core machine on codespaces. Thanks for your patience.
