### ISSUE TITLE
[Modular CLI]: Can't install mojo, llvm problem

### ISSUE THREAD

**Issue by tinyhare** [modularml/mojo#677]
### Issue description

When I install mojo, I get an error:
```
root@house:~# modular install mojo
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: modular install mojo
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  modular   0x000055c59f3de567
1  modular   0x000055c59f3dc21e
2  modular   0x000055c59f3dec2f
3  libc.so.6 0x00007f512c43c4b0
4  modular   0x000055c5a040f710
5  modular   0x000055c59f799e78
6  modular   0x000055c59f39a4ad
7  modular   0x000055c59f398fe0
8  libc.so.6 0x00007f512c423a90
9  libc.so.6 0x00007f512c423b49 __libc_start_main + 137
10 modular   0x000055c59f39868e
Illegal instruction (core dumped)
```
After I install llvm 
```

root@house:~# apt install llvm
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  llvm
0 upgraded, 1 newly installed, 0 to remove and 12 not upgraded.
Need to get 3,826 B of archives.
After this operation, 112 kB of additional disk space will be used.
Get:1 http://mirrors.huaweicloud.com/repository/ubuntu lunar/universe amd64 llvm amd64 1:15.0-56~exp2 [3,826 B]
Fetched 3,826 B in 0s (22.2 kB/s)
Selecting previously unselected package llvm.
(Reading database ... 311232 files and directories currently installed.)
Preparing to unpack .../llvm_1%3a15.0-56~exp2_amd64.deb ...
Unpacking llvm (1:15.0-56~exp2) ...
Setting up llvm (1:15.0-56~exp2) ...
Processing triggers for man-db (2.11.2-1) ...
root@house:~# modular install mojo
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: modular install mojo
 #0 0x000055968281c567 (/usr/bin/modular+0x4ee567)
 #1 0x000055968281a21e (/usr/bin/modular+0x4ec21e)
 #2 0x000055968281cc2f (/usr/bin/modular+0x4eec2f)
 #3 0x00007ff91f23c4b0 (/lib/x86_64-linux-gnu/libc.so.6+0x3c4b0)
 #4 0x000055968384d710 (/usr/bin/modular+0x151f710)
 #5 0x0000559682bd7e78 (/usr/bin/modular+0x8a9e78)
 #6 0x00005596827d84ad (/usr/bin/modular+0x4aa4ad)
 #7 0x00005596827d6fe0 (/usr/bin/modular+0x4a8fe0)
 #8 0x00007ff91f223a90 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
 #9 0x00007ff91f223b49 call_init ./csu/../csu/libc-start.c:128:20
#10 0x00007ff91f223b49 __libc_start_main ./csu/../csu/libc-start.c:347:5
#11 0x00005596827d668e (/usr/bin/modular+0x4a868e)
Illegal instruction (core dumped)
root@house:~# 
```

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.
Manual installation steps at https://developer.modular.com/download

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
root@house:~# modular -v
modular 0.1.4 (6b54d308)
- What OS did you install modular CLI on ?
root@house:~# cat /etc/issue
Ubuntu 23.04 \n \l
```

**Comment by bzcheeseman** [comment]
I would have expected to see some crash reporting messages, this is interesting. We'll look into it, thank you for reporting.

**Comment by ayunillariy** [comment]
I have a similar problem:

|  \/  | ___   __| |_   _| | __ _ _ __
 | |\/| |/ _ \ / _` | | | | |/ _` | '__|
 | |  | | (_) | (_| | |_| | | (_| | |
 |_|  |_|\___/ \__,_|\__,_|_|\__,_|_|

Welcome to the Modular CLI!
For info about this tool, type "modular --help".

To install Mojo🔥, type "modular install mojo".


Stack dump:
0.      Program arguments: modular install mojo
 #0 0x0000563ed2092567 (/usr/bin/modular+0x4ee567)
 #1 0x0000563ed209021e (/usr/bin/modular+0x4ec21e)
 #2 0x0000563ed2092c2f (/usr/bin/modular+0x4eec2f)
 #3 0x00007f4c1663b140 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x13140)
 #4 0x0000563ed30a44a7 (/usr/bin/modular+0x15004a7)
 #5 0x0000563ed30a3f85 (/usr/bin/modular+0x14fff85)
 #6 0x0000563ed30a51d5 (/usr/bin/modular+0x15011d5)
 #7 0x0000563ed247558d (/usr/bin/modular+0x8d158d)
 #8 0x0000563ed246bf90 (/usr/bin/modular+0x8c7f90)
 #9 0x0000563ed204e7b4 (/usr/bin/modular+0x4aa7b4)
#10 0x0000563ed204cfe0 (/usr/bin/modular+0x4a8fe0)
#11 0x00007f4c160eed0a __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x23d0a)
#12 0x0000563ed204c68e (/usr/bin/modular+0x4a868e)
Instrucción ilegal

- Provide Modular CLI version by pasting the output of `modular -v`
illaycloud@q4os-desktop:~$ modular -v
modular 0.1.4 (6b54d308)

 - What OS did you install modular CLI on ?
 illaycloud@q4os-desktop:~$ cat /etc/issue
Debian GNU/Linux 11 \n \l

**Comment by Javier32** [comment]
I have the same problem :(

**Comment by Schnebi78** [comment]
same Problem here:  

Stack dump:
0.	Program arguments: modular install mojo
 #0 0x000055ecd6fa1567 (/usr/bin/modular+0x4ee567)
 #1 0x000055ecd6f9f21e (/usr/bin/modular+0x4ec21e)
 #2 0x000055ecd6fa1c2f (/usr/bin/modular+0x4eec2f)
 #3 0x00007ff939b4f520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x000055ecd7fd2710 (/usr/bin/modular+0x151f710)
 #5 0x000055ecd735ce78 (/usr/bin/modular+0x8a9e78)
 #6 0x000055ecd6f5d4ad (/usr/bin/modular+0x4aa4ad)
 #7 0x000055ecd6f5bfe0 (/usr/bin/modular+0x4a8fe0)
 #8 0x00007ff939b36d90 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
 #9 0x00007ff939b36e40 call_init ./csu/../csu/libc-start.c:128:20
#10 0x00007ff939b36e40 __libc_start_main ./csu/../csu/libc-start.c:379:5
#11 0x000055ecd6f5b68e (/usr/bin/modular+0x4a868e)
Ungültiger Maschinenbefehl

Version:
 modular -v
modular 0.1.4 (6b54d308)

OS:
cat /etc/issue
Linux Mint 21.2 Victoria \n \l

At first I have to install llvm, too.

**Comment by tinyhare** [comment]
I find that on Ubuntu 23.04 the default Python version is 3.11，and mojo not support it. is this the reason?

**Comment by gryznar** [comment]
Strange. For me 3.11 works

**Comment by Ceesaxp** [comment]
Same here:

```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: modular auth mut_...
 #0 0x000055921ec86bb7 (/usr/bin/modular+0x4eebb7)
 #1 0x000055921ec8486e (/usr/bin/modular+0x4ec86e)
 #2 0x000055921ec8727f (/usr/bin/modular+0x4ef27f)
 #3 0x00007f75ace5afd0 (/lib/x86_64-linux-gnu/libc.so.6+0x3bfd0)
 #4 0x000055921fdc7830 (/usr/bin/modular+0x162f830)
 #5 0x000055921fdc7b5b (/usr/bin/modular+0x162fb5b)
 #6 0x000055921f064a45 (/usr/bin/modular+0x8cca45)
 #7 0x000055921ec487aa (/usr/bin/modular+0x4b07aa)
 #8 0x00007f75ace461ca (/lib/x86_64-linux-gnu/libc.so.6+0x271ca)
 #9 0x00007f75ace46285 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x27285)
#10 0x000055921ec4855e (/usr/bin/modular+0x4b055e)
Illegal instruction
```

Environment:

```
$ python3 --version                                                                          
Python 3.11.2
$ cat /etc/issue
Debian GNU/Linux 12 \n \l

$ uname -a
Linux debian 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

Modular linked against:

```
$ ldd /usr/bin/modular
	linux-vdso.so.1 (0x00007ffd00ba0000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f79f5dcd000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f79f5dc8000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f79f2f21000)
	libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007f79f5d95000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f79f5d90000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f79f5d6f000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f79f2c00000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f79f5d4f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f79f2a1f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f79f5dda000)
```

Tried to re-run the whole installation from start with 
```
curl https://get.modular.com | \
  MODULAR_AUTH=mut_... \
  sh -
```

Same result…
