### ISSUE TITLE
[Feature Request] Mojo Extension Top Level Completions

### ISSUE THREAD

**Issue by jackos** [modularml/mojo#679]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Currently there are no completions for the top-level scope:

<img width="425" alt="Screenshot 2023-09-09 at 10 44 11 am" src="https://github.com/modularml/mojo/assets/77730378/abd8fc23-de6a-4171-9bc2-f77be76056ec">

This makes the extension appear to not be working to some users: https://discord.com/channels/1087530497313357884/1149917174543171598/1150118375721275603

### What is your motivation for this change?

Code discovery, would be really nice to see everything available from the global scope.

**Comment by jackos** [comment]
@River707

**Comment by mbougarne** [comment]
It doesn't work on my side on VS Code 1.81.1

**Comment by River707** [comment]
This should be available in the next release!
