### ISSUE TITLE
[BUG]: Completions hanging on systems with low RAM

### ISSUE THREAD

**Issue by jackos** [modularml/mojo#680]
### Bug description

It appears to only occur on systems with RAM at 8GB or less, even though it doesn't appear the RAM is completely depleted, the extension hangs when trying to use any completions, two examples of users `free -g` results:

```
total        used        free      shared  buff/cache   available
Mem:              7           2           1           0           3           4
Swap:             1           0           1
```
```
               total        used        free      shared  buff/cache   available
Mem:               8           0           8           0           0           8
Swap:              3           0           3
```

**Comment by jackos** [comment]
@River707

**Comment by jackos** [comment]
Relevant discord thread: https://discord.com/channels/1087530497313357884/1149917174543171598/1149923838310764666

**Comment by Sarctiann** [comment]
From vscode-extension perspective

![screenshot](https://github.com/modularml/mojo/assets/49457785/163afea7-1ced-4fb1-bfc0-445cebbd0c36)

I tested in

* Linux machine (KDE-Neon (ubuntu22.x/janny) i3-10gen | 8GB RAM)
* Macbook Pro (M1 Pro 16 GB RAM) with GitHub Codespace (4-core • 16GB RAM • 32GB)

**Comment by Sarctiann** [comment]
![image](https://github.com/modularml/mojo/assets/49457785/ab7b7316-5a38-42d9-b165-273dbc980fd1)
These commands doesn't work either

**Comment by jackos** [comment]
The issue was systems with low cores deadlocking, fixed in the next release.
