### ISSUE TITLE
[Docs] 404 page's go home button leads to the wrong page

### ISSUE THREAD

**Issue by KirovClassBattlecruiser** [modularml/mojo#681]
### Where is the problem?

[The "page not found" page you get when accessing any non existing page on modular.com](https://www.modular.com/c)

### What can we do better?

In the "page not found" page, you get a "Go Home" button.
Unfortunately it sends to [the wrong page](https://www.modular.com/dev/old-home),
seemingly the old "home" page of the website now only accessible to modular devs

### Anything else?

Found this while looking for yet another issue on the website
I'll open an issue when i find on which page it is again

**Comment by jackos** [comment]
@scottamain

**Comment by scottamain** [comment]
This is on the product website. FYI @e-a-johnson

**Comment by ematejska** [comment]
This is now fixed so closing out.
