### ISSUE TITLE
[Docs] The "Entreprise? Contact sales" button of the signup page sends to a page that's been moved

### ISSUE THREAD

**Issue by KirovClassBattlecruiser** [modularml/mojo#682]
### Where is the problem?

[In the signup page](https://developer.modular.com/signup) and, it leads to [this page](https://www.modular.com/sales)

### What can we do better?

The correct "sales" page is this https://www.modular.com/contact/sales
But in the signup page, the "Entreprise? Contact sales" button leads to this https://www.modular.com/sales
I assume you guys moved the page but didn't update all buttons

### Anything else?

Maybe there are more buttons to go to sales that lead to the old page

**Comment by scottamain** [comment]
FYI @robert-j-webb

**Comment by iamtimdavis** [comment]
Fixed. Thanks @KirovClassBattlecruiser 🤘🏼
