### ISSUE TITLE
[Docs] Typo in the download page

### ISSUE THREAD

**Issue by KirovClassBattlecruiser** [modularml/mojo#684]
### Where is the problem?

[The download page](https://developer.modular.com/download)

### What can we do better?

In the "get started" section when you scroll down, there is "code and notebook"s.
Well, it says:

> Explore some of Mojo's standard **libary** and powerful features with these `.mojo` source files and Jupyter notebooks.

There's a typo, it's "library" not "libary"

### Anything else?

Found 2 other issues when looking for where i first founf this issue

**Comment by scottamain** [comment]
Thank you, this will be fixed in the next update.
