### ISSUE TITLE
Update --help for cli package update

### ISSUE THREAD

**Issue by Omicronlawful** [modularml/mojo#687]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

An updater for mojo. It would probably just fetch the latest version run mojo -v and it the versions are different run modular uninstall, clean and install

### What is your motivation for this change?

Since modular is its own package manager mojo won't update with apt update

**Comment by bzcheeseman** [comment]
You can run `modular update mojo`

**Comment by Omicronlawful** [comment]
@bzcheeseman its missing in modular —help

**Comment by bzcheeseman** [comment]
You're right, will fix in the next release. Thanks!
