### ISSUE TITLE
[Feature Request]: Sample Implementation of Machine Learning Models and Algorithms

### ISSUE THREAD

**Issue by PrashantDixit-dev** [modularml/mojo#688]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Sample Implementation of Machine Learning Models and Algorithms to testing performance of mojo.

### What is your motivation for this change?

To check performance of mojo and perform comparison of it with Python and C++

**Comment by lattner** [comment]
We have a few examples and will be expanding this over time, but right now the broader mojo community is doing great here, check out llama2.🔥 for example
