### ISSUE TITLE
[BUG]: String concatenation is very slow compared to python

### ISSUE THREAD

**Issue by andresnowak** [modularml/mojo#691]
### Bug description

# String concatenation is very slow compared to python
**The time is measured concatenating 250,000 values**

### Example 1 (Float)
float = 30034.4543
Time spent in example 1: 283474 ms

### Example 2 (Int)
int = 30034
Time spent in example 2: 84447 ms

### Example 3 (Small Int)
small int = 30
Time spent in example 3: 33938 ms

### Example 4 (String)
string = abcdefghijkl
Time spent in example 4: 288278 ms

### Example 1 (Float)
float = 30034.4543
Time spent in example 1: 99.91 ms

### Example 2 (Int)
int = 30034
Time spent in example 2: 45.78 ms

### Example 3 (Small Int)
small int = 30
Time spent in example 3: 44.56 ms

### Example 4 (String)
string = abcdefghijkl
Time spent in example 4: 17.40 ms

# And string conversion seems to be a little bit faster or the same
**so the problem seems to be the concatenation of big strings**

## Mojo time
conversion of float = 17,000,000,000.330

Time spent in conversion: 0.023220000000000001 ms
Time spent in conversion: 23.219999999999999 micro second

## Python time
conversion of float = 17,000,000,000.330

Time spent in example 4: 0.04 ms
Time spent in example 4: 43.39 micro second

## Mojo concatenation example

```py
from time import now


fn example_1():
    var a = String("")
    for i in range(250_000):
        a += String(30034.4543)
    # print(a)


fn example_2():
    var a = String("")
    for i in range(250_000):
        a += String(30034)
    # print(a)


fn example_3():
    var a = String("")
    for i in range(250_000):
        a += String(30)
    # print(a)

fn example_4():
    var a = String("")
    for i in range(250_000):
        a += "abcdefghijkl"
    # print(a)


fn main():
    var eval_begin: Int = now()
    example_1()
    var eval_end: Int = now()
    print("Time spent in example 1:", (eval_end - eval_begin) // 1000000, "ms")

    eval_begin = now()
    example_2()
    eval_end = now()
    print("Time spent in example 2:", (eval_end - eval_begin) // 1000000, "ms")

    eval_begin = now()
    example_3()
    eval_end = now()
    print("Time spent in example 3:", (eval_end - eval_begin) // 1000000, "ms")

    eval_begin = now()
    example_4()
    eval_end = now()
    print("Time spent in example 4:", (eval_end - eval_begin) // 1000000, "ms")
```

## Python concatenation example

```py
import time


def example_1():
    a = ""
    for i in range(250_000):
        a += str(30034.4543)
    # print(a)


def example_2():
    a = ""
    for i in range(250_000):
        a += str(30034)
    # print(a)


def example_3():
    a = ""
    for i in range(250_000):
        a += str(30)
    # print(a)


def example_4():
    a = ""
    for i in range(250_000):
        a += "abcdefghijkl"
    # print(a)


eval_start = time.time()
example_1()
eval_end = time.time()
print(f"Time spent in example 1: {(eval_end - eval_start) * 1000:.2f} ms")


eval_start = time.time()
example_2()
eval_end = time.time()
print(f"Time spent in example 2: {(eval_end - eval_start) * 1000:.2f} ms")

eval_start = time.time()
example_3()
eval_end = time.time()
print(f"Time spent in example 3: {(eval_end - eval_start) * 1000:.2f} ms")

eval_start = time.time()
example_4()
eval_end = time.time()
print(f"Time spent in example 4: {(eval_end - eval_start) * 1000:.2f} ms")
```
## Mojo conversion example
```py
from time import now
fn main():
    let eval_begin = now()
    let num: FloatLiteral = 17_000_000_000.330
    let val = String(num)
    print(val)
    let eval_end = now()
    print("Time spent in example 1:", (eval_end - eval_begin) / 1000000, "ms")
    print("Time spent in example 1:", (eval_end - eval_begin) / 1000, "micro second")
```

## Python conversion example
```py
eval_start = time.time()
num = 17_000_000_000.330
val = str(num)
eval_end = time.time()
print(f"Time spent in example 4: {(eval_end - eval_start) * 1000:.2f} ms")
print(f"Time spent in example 4: {(eval_end - eval_start) * 1000000:.2f} micro second")
```

### System information

```shell
- What OS did you do install Mojo on ? Pop!_OS 22.04 LTS
- Provide version information for Mojo by pasting the output of `mojo -v`: mojo 0.2.1 (64d14e85)

- Provide Modular CLI version by pasting the output of `modular -v`: modular 0.1.4 (6b54d308)
```

**Comment by nmrtv** [comment]
The first 3 functions are irrelevant, and in the 4th you are comparing apples to oranges. Python str is immutable, mojo String is mutable. I don't know how it would be better to do this in mojo (using StringLiteral, allocating memory before concatenation, etc...) but this example is very unpythonic and probably very "unmojic".

**Comment by willghatch** [comment]
Thank you for the report.  We are actively working on various optimizations, so performance should improve over time across the board.  I'm going to go ahead and close this for now, since it fits under the umbrella of performance that we are already prioritizing.
