### ISSUE TITLE
[Mojo]: modular install mojo command failure

### ISSUE THREAD

**Issue by jangwonpark74** [modularml/mojo#693]
### Issue description

When I initiate modular install mojo command,
even though the python3.10.12 and its requirement's are satisfied, the mojo --help command execution failed. 

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

➜  mojo_ws git:(main) ✗ modular install mojo
# Found release for https://packages.modular.com/mojo @ 0.2.1, installing to /home/jason/.modular/pkg/packages.modular.com_mojo
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
Defaulting to user installation because normal site-packages is not writeable

Requirement already satisfied: find_libpython==0.3.0 in /home/jason/.local/lib/python3.10/site-packages (from -r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 1)) (0.3.0)
Requirement already satisfied: papermill==2.4.0 in /home/jason/.local/lib/python3.10/site-packages (from -r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.4.0)
Requirement already satisfied: jupyter_client>=8.3.0 in /usr/local/lib/python3.10/dist-packages (from -r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (8.3.0)
Requirement already satisfied: nbformat>=5.1.2 in /usr/local/lib/python3.10/dist-packages (from papermill==2.4.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (5.9.2)
Requirement already satisfied: nbclient>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from papermill==2.4.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.8.0)
Requirement already satisfied: entrypoints in /usr/lib/python3/dist-packages (from papermill==2.4.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.4)
Requirement already satisfied: tenacity in /home/jason/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (8.2.3)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from papermill==2.4.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (8.0.3)
Requirement already satisfied: ansiwrap in /home/jason/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.8.4)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from papermill==2.4.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (5.4.1)
Requirement already satisfied: tqdm>=4.32.2 in /home/jason/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (4.66.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from papermill==2.4.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.31.0)
Requirement already satisfied: traitlets>=5.3 in /usr/local/lib/python3.10/dist-packages (from jupyter_client>=8.3.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (5.9.0)
Requirement already satisfied: tornado>=6.2 in /usr/local/lib/python3.10/dist-packages (from jupyter_client>=8.3.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (6.3.3)
Requirement already satisfied: pyzmq>=23.0 in /usr/local/lib/python3.10/dist-packages (from jupyter_client>=8.3.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (25.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from jupyter_client>=8.3.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (2.8.2)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.10/dist-packages (from jupyter_client>=8.3.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (5.3.1)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.10/dist-packages (from jupyter-core!=5.0.*,>=4.12->jupyter_client>=8.3.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (3.10.0)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.10/dist-packages (from nbformat>=5.1.2->papermill==2.4.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (4.19.0)
Requirement already satisfied: fastjsonschema in /usr/local/lib/python3.10/dist-packages (from nbformat>=5.1.2->papermill==2.4.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.18.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->jupyter_client>=8.3.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (1.16.0)
Requirement already satisfied: textwrap3>=0.9.2 in /home/jason/.local/lib/python3.10/site-packages (from ansiwrap->papermill==2.4.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.9.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->papermill==2.4.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (1.26.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->papermill==2.4.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (3.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->papermill==2.4.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (3.2.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->papermill==2.4.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2020.6.20)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.30.2)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (23.1.0)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.9.2)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2023.7.1)

TEST: `mojo --help`... ERROR
Traceback (most recent call last):
  File "/home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 342, in <module>
    main()
  File "/home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 338, in main
    tester.test(args.test_jupyter)
  File "/home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 269, in test
    self.test_mojo_help()
  File "/home/jason/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 94, in test_mojo_help
    assert "mojo" in self.run_mojo("--help")[0]
AssertionError
modular: error: failed to run python: 
➜  mojo_ws git:(main) ✗ mojo --help
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: mojo --help
 #0 0x0000559840facf17 (/home/jason/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5bcf17)
 #1 0x0000559840faaaee (/home/jason/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5baaee)
 #2 0x0000559840fad5ef (/home/jason/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5bd5ef)
 #3 0x00007ff2b7042520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x0000559842922850 (/home/jason/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1f32850)
 #5 0x0000559842922abb (/home/jason/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x1f32abb)
 #6 0x0000559841372c09 (/home/jason/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x982c09)
 #7 0x0000559840f5723a (/home/jason/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x56723a)
 #8 0x00007ff2b7029d90 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
 #9 0x00007ff2b7029e40 call_init ./csu/../csu/libc-start.c:128:20
#10 0x00007ff2b7029e40 __libc_start_main ./csu/../csu/libc-start.c:379:5
#11 0x0000559840f5712e (/home/jason/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x56712e)
[1]    20020 illegal hardware instruction (core dumped)  mojo --help

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`


$ modular -v
modular 0.1.4 (6b54d308)

- What OS did you install modular CLI on ?
$ uname -a
Linux Jellfish 6.2.0-32-generic #32~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 18 10:40:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

- Learning Ubuntu 22.04 in Oracle VM VirtualBox
AMD CPU 7800x3d
```

**Comment by gokomer** [comment]
I have the same issue in ubuntu 23.04

**Comment by vesko2020** [comment]
I have the same issue in Ubuntu 22.04

**Comment by smallSwed** [comment]
I have the same issue in Ubuntu 20.04 with python3.8 (on Oracle VM VirtualBox) i7-11800H

**Comment by SethWhalen94** [comment]
I have the same issue on Ubuntu 20.04 VM

**Comment by mrasore98** [comment]
I have the same issue in Ubuntu 22.04 (on Oracle VM VirtualBox) Intel i7-12800H

**Comment by jackos** [comment]
Resolved in nightly release by https://github.com/modularml/mojo/commit/b6776222dbd1e2e72a5e6f772d01b35fee7ea0d9. Mojo now finds libpython using the python executable on the top of `PATH`

You can test before the official release with `modular install nightly/mojo`. For environments like vscode codespaces that have a python on the top of `PATH` without a dynamic `libpython.so` you can activate a virtual environment to use a different version e.g. the system Python is able to link to a dynamic libpython: 
```bash
/usr/bin/python3 -m venv ~/venv
source ~/venv/bin/activate
```
Please reopen if you have any further issues.
