### ISSUE TITLE
Two Uncaught Exceptions

### ISSUE THREAD

**Issue by sarvex** [modularml/mojo#701]
Type: <b>Bug</b>

Install Mojo Extention
Open Running Extensions View

Extension version: 0.2.1
VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:07.438Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (1.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ematejska** [comment]
What kind of exceptions did you get? Can you provide more info?

**Comment by lattner** [comment]
closing as "not actionable", please reopen if you have more details
