### ISSUE TITLE
[Mojo]: failure on the command `modular install mojo`

### ISSUE THREAD

**Issue by xuyxu** [modularml/mojo#704]
### Issue description

When running `modular install mojo`, the program throws the following exception when running unit tests. I am sure that the `python` command works as expected in the terminal.

## Detail

![image](https://github.com/modularml/mojo/assets/22359569/676a464a-3bbf-4333-be26-1fe7a2feae5d)

## Environment
* Python Version: 3.10.12
* GCC Version: 11.4

### Steps to reproduce

Simply run `modular install mojo` in the terminal.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
0.1.4 (6b54d308)

- What OS did you install modular CLI on ?
Ubuntu 22.04.3 LTS
```

**Comment by gryznar** [comment]
Your `modular` version is outdated. Try to update it via:
```bash
sudo apt-get update
sudo apt-get install modular
```
and retry

**Comment by jackos** [comment]
Resolved in nightly release by https://github.com/modularml/mojo/commit/b6776222dbd1e2e72a5e6f772d01b35fee7ea0d9. Mojo now finds libpython using the python executable on the top of `PATH`

You can test before the official release with `modular install nightly/mojo`. For environments like vscode codespaces that have a python on the top of `PATH` without a dynamic `libpython.so` you can activate a virtual environment to use a different version e.g. the system Python is able to link to a dynamic libpython: 
```bash
/usr/bin/python3 -m venv ~/venv
source ~/venv/bin/activate
```
Please reopen if you have any further issues.
