### ISSUE TITLE
[Dev Console]: print("Hello world") error

### ISSUE THREAD

**Issue by male110** [modularml/mojo#705]
### Issue description

windows 11,ubuntu WSL

`root@DESKTOP-8SJBKD6:~# mojo
Welcome to Mojo! 🔥
Expressions are delimited by a blank line.
Type `:mojo help` for further assistance.
1> print("Hello, world!")
2.
[User] error: Expression [0]:1:1: unable to locate module 'builtin'
from memory.unsafe import Pointer
^

error: Expression [0]:15:1: could not find builtin 'Error' type
def __mojo_repl_expr_impl__(inout __mojo_repl_arg: __mojo_repl_context__) -> None:
^

error: Expression [0]:12:3: could not find builtin 'Error' type
  except error:
  ^

error: Expression [0]:13:5: use of unknown declaration 'print'
    print("Error:", error.value)
    ^~~~~

error: Expression [0]:17:3: could not find builtin 'Error' type
  def __mojo_repl_expr_body__() -> None:
  ^

error: Expression [0]:18:31: could not find builtin 'Bool' type
    var ___lldb_expr_failed = False
                              ^

expression failed to parse (no further compiler diagnostics)
1>`

### Steps to reproduce

- Add screenshots if possible, to help explain the problem.
- Include anything that might help us debug the issue.

**Comment by Mariobagi** [comment]
Ok

**Comment by Arif812** [comment]
Did you exit with Ctrl-D, and if you did, try running `modular clean` and then use `modular install mojo`.
