### ISSUE TITLE
[Modular CLI]: 

### ISSUE THREAD

**Issue by happymilf** [modularml/mojo#707]
### Issue description

The installation stops for testing. Nothing else happens. I waited for about 7 hours

### Steps to reproduce

![Снимок экрана 2023-09-10 150846](https://github.com/modularml/mojo/assets/44862413/854713c3-fccb-4505-8ba9-9958c065d65c)

### Version Info

```shell
- modular 0.1.4 (6b54d308)
- WSL Ubuntu 22/04 ?
```

**Comment by Arif812** [comment]
Can you use `cat /etc/os-release` in your terminal please?

**Comment by happymilf** [comment]
![Снимок экрана 2023-09-10 193711](https://github.com/modularml/mojo/assets/44862413/489a5074-2241-4673-aae2-781b61b4d921)

**Comment by Arif812** [comment]
Try using `modular uninstall mojo` then use: 
`modular auth mut_9d4f138242134b45babd2ea9d576fb11 &&
modular install mojo`

**Comment by happymilf** [comment]
Nothing changed…

**Comment by happymilf** [comment]
worked on Ubuntu 20.04.6

**Comment by jackos** [comment]
Closing in favor of: https://github.com/modularml/mojo/issues/538

But thanks @happymilf for the tip, I'll report that back to the other ticket
