### ISSUE TITLE
[Docs] Gramatical error in language basics page

### ISSUE THREAD

**Issue by shabeebk** [modularml/mojo#708]
### Where is the problem?

https://docs.modular.com/mojo/manual/basics/#:~:text=If%20you%20want%20the%20arguments%20to%20be%20mutable%2C%20you%20need%20to%20declare%20the%20argument%20convention%20is%20inout.

### What can we do better?

It looks like the usage of the word `is` is not suitable in this line. Maybe, `as` works. 

### Anything else?

Suggestion:

If you want the arguments to be mutable, you need to declare the argument convention as `inout`.

**Comment by PrethamMuthappa** [comment]
in which line? there is a lot of "is"

**Comment by shabeebk** [comment]
This line: https://docs.modular.com/mojo/manual/basics/#:~:text=If%20you%20want%20the%20arguments%20to%20be%20mutable%2C%20you%20need%20to%20declare%20the%20argument%20convention%20is%20inout

**Comment by KSSaiTeja** [comment]
can i fix it?

**Comment by scottamain** [comment]
Thank you, this will be fixed in the next update.
