### ISSUE TITLE
[Mojo]: Ubuntu basic mojo install stalls

### ISSUE THREAD

**Issue by rcplane** [modularml/mojo#709]
### Issue description

Ubuntu 22.04 basic installation `modular install mojo` stalls for many minutes after TEST: mojo test_python.mojo ... OK

`modular install mojo
# Found release for https://packages.modular.com/mojo @ 0.2.1, installing to /home/ubuntu/.modular/pkg/packages.modular.com_mojo
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
Requirement already satisfied: find_libpython==0.3.0 in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from -r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 1)) (0.3.0)
Requirement already satisfied: papermill==2.4.0 in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from -r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.4.0)
Requirement already satisfied: jupyter_client>=8.3.0 in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from -r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (8.3.1)
Requirement already satisfied: nbclient>=0.2.0 in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from papermill==2.4.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.8.0)
Requirement already satisfied: nbformat>=5.1.2 in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from papermill==2.4.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (5.9.2)
Requirement already satisfied: requests in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from papermill==2.4.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.27.1)
Requirement already satisfied: click in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from papermill==2.4.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (8.1.7)
Requirement already satisfied: ansiwrap in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from papermill==2.4.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.8.4)
Requirement already satisfied: tenacity in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from papermill==2.4.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (8.2.3)
Requirement already satisfied: tqdm>=4.32.2 in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from papermill==2.4.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (4.63.0)
Requirement already satisfied: entrypoints in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from papermill==2.4.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.4)
Requirement already satisfied: pyyaml in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from papermill==2.4.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (6.0.1)
Requirement already satisfied: pyzmq>=23.0 in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from jupyter_client>=8.3.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (25.1.1)
Requirement already satisfied: traitlets>=5.3 in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from jupyter_client>=8.3.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (5.9.0)
Requirement already satisfied: tornado>=6.2 in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from jupyter_client>=8.3.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (6.3.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from jupyter_client>=8.3.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (5.3.1)
Requirement already satisfied: importlib-metadata>=4.8.3 in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from jupyter_client>=8.3.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (6.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from jupyter_client>=8.3.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (2.8.2)
Requirement already satisfied: zipp>=0.5 in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from importlib-metadata>=4.8.3->jupyter_client>=8.3.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (3.16.2)
Requirement already satisfied: platformdirs>=2.5 in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter_client>=8.3.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (2.5.2)
Requirement already satisfied: fastjsonschema in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from nbformat>=5.1.2->papermill==2.4.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.18.0)
Requirement already satisfied: jsonschema>=2.6 in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from nbformat>=5.1.2->papermill==2.4.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (4.19.0)
Requirement already satisfied: referencing>=0.28.4 in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.30.2)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2023.7.1)
Requirement already satisfied: attrs>=22.2.0 in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (23.1.0)
Requirement already satisfied: rpds-py>=0.7.1 in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.10.2)
Requirement already satisfied: six>=1.5 in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from python-dateutil>=2.8.2->jupyter_client>=8.3.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (1.16.0)
Requirement already satisfied: textwrap3>=0.9.2 in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from ansiwrap->papermill==2.4.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.9.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from requests->papermill==2.4.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from requests->papermill==2.4.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2022.9.24)
Requirement already satisfied: idna<4,>=2.5 in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from requests->papermill==2.4.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/ubuntu/miniconda3/lib/python3.9/site-packages (from requests->papermill==2.4.0->-r /home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (1.26.8)
Testing `MODULAR_HOME=/home/ubuntu/.modular`
* `/home/ubuntu/.modular/pkg/packages.modular.com_mojo/bin/mojo`...
TEST: `mojo --help`... OK
TEST: `mojo run --help`... OK
TEST: `mojo build test_mandelbrot.mojo`... OK
TEST: `mojo build test_python.mojo`... OK
TEST: `mojo demangle`... OK
TEST: `mojo format`... OK
TEST: `mojo package`... OK
TEST: `mojo test_mandelbrot.mojo`... OK
TEST: `mojo test_python.mojo`... OK
^CTEST: `mojo repl`... ERROR
Traceback (most recent call last):
  File "/home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 342, in <module>
    main()
  File "/home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 338, in main
    tester.test(args.test_jupyter)
  File "/home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 275, in test
    self.test_mojo_repl()
  File "/home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 185, in test_mojo_repl
    out_data, err_data = repl.communicate(
  File "/home/ubuntu/miniconda3/lib/python3.9/subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/home/ubuntu/miniconda3/lib/python3.9/subprocess.py", line 1979, in _communicate

(base) ubuntu@b :~$     ready = selector.select(timeout)
  File "/home/ubuntu/miniconda3/lib/python3.9/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt`

### Steps to reproduce

On Ubuntu 22.04
Install Modular CLI
`modular install mojo`

### Version Info

```shell
modular -v
modular 0.1.4 (6b54d308)

cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.3 LTS"

uname -r
5.15.0-83-generic
```

**Comment by jnordberg** [comment]
Seeing same thing on Ubuntu 20.04.6 LTS (5.15.0-72-generic)

**Comment by Arif812** [comment]
There is distro specific setup for Ubuntu 20.04 or later:
`apt-get install -y apt-transport-https &&
  keyring_location=/usr/share/keyrings/modular-installer-archive-keyring.gpg &&
  curl -1sLf 'https://dl.modular.com/bBNWiLZX5igwHXeu/installer/gpg.0E4925737A3895AD.key' |  gpg --dearmor >> ${keyring_location} &&
  curl -1sLf 'https://dl.modular.com/bBNWiLZX5igwHXeu/installer/config.deb.txt?distro=debian&codename=wheezy' > /etc/apt/sources.list.d/modular-installer.list &&
  apt-get update &&
  apt-get install -y modular
  `
  Keep in mind this is *as root*

**Comment by LHRchina** [comment]
> 

Event though I setup the mojo manually, still encounter this Error

**Comment by LHRchina** [comment]
> There is distro specific setup for Ubuntu 20.04 or later: `apt-get install -y apt-transport-https && keyring_location=/usr/share/keyrings/modular-installer-archive-keyring.gpg && curl -1sLf 'https://dl.modular.com/bBNWiLZX5igwHXeu/installer/gpg.0E4925737A3895AD.key' | gpg --dearmor >> ${keyring_location} && curl -1sLf 'https://dl.modular.com/bBNWiLZX5igwHXeu/installer/config.deb.txt?distro=debian&codename=wheezy' > /etc/apt/sources.list.d/modular-installer.list && apt-get update && apt-get install -y modular ` Keep in mind this is _as root_

Event though I setup the mojo manually, still encounter this Error

**Comment by Arif812** [comment]
Try using `modular uninstall mojo`, then once again, use `modular install mojo`

**Comment by rcplane** [comment]
Tried this, removing and reinstalling Modular CLI. Problem still happening.
Since I have flexibility, is there a known good OS target or a way to drill into (or disable) this repl test to provide helpful feedback?

**Comment by rcplane** [comment]
Have
python -V
Python 3.9.12

**Comment by rcplane** [comment]
> Try using `modular uninstall mojo`, then once again, use `modular install mojo`

modular uninstall mojo
modular: error: could not find the installed package path in the config

The mojo package and command line mojo are not successfully installed due to the stalling repl test.

**Comment by bzcheeseman** [comment]
Try `modular clean` and then retry - that will wipe out all your state and reinstall. There's a decent chance that the REPL test will continue to hang though, because we (unfortunately, and hopefully temporarily) require more RAM than 13GiB.

**Comment by Arif812** [comment]
The best option is to use Codespaces.

**Comment by kiwionly** [comment]
I facing the almost the same thing, it will hang when running `mojo test_python` , then I stop it with Ctrl ^C

![image](https://github.com/modularml/mojo/assets/174617/845a5534-e264-44f8-85d7-e13dc2415f7e)

This is the memory usage before interrupt : 

![image](https://github.com/modularml/mojo/assets/174617/7394db8c-2ffd-4a5d-8b82-12c84099bc59)

Platform : wsl ubuntu 22.04 , Windows 10

**Comment by rcplane** [comment]
Tried scaling up to 62GB memory on the same instance with no change after modular clean.
Will look into codespaces next.
<img width="1076" alt="Screenshot 2023-09-16 at 8 28 17 AM" src="https://github.com/modularml/mojo/assets/1978942/4168f3d1-ab57-486a-b51e-0a118e675260">

**Comment by Arif812** [comment]
I used 4 cores, 16GB RAM, 32GB storage on Codespaces, was successful

**Comment by kiwionly** [comment]
Try to install on codespace (free trial) on 8GB RAM , 2 cores: 

![image](https://github.com/modularml/mojo/assets/174617/276b295a-d98d-439e-88e8-2e0982bb9636)

It just hang there :

![image](https://github.com/modularml/mojo/assets/174617/41994690-c800-48ac-a5ac-071f7579e2c4)

Seem like it not because of low memory, it just idle ( I screen shot it after 1 hour )

![image](https://github.com/modularml/mojo/assets/174617/97653639-315c-41f5-8e5a-2c5bf16fafca)

**Comment by jackos** [comment]
Closing in favor of: https://github.com/modularml/mojo/issues/538

**Comment by rustspeak** [comment]
s'il  vous  plait    je  voulais les  commandes  pour  intsller  mojo   dans  unbutu  une  commande  a jour
