### ISSUE TITLE
[BUG]: order declaration,resolve candidate,one with @staticmethod

### ISSUE THREAD

**Issue by rd4com** [modularml/mojo#711]
### Bug description

If the @staticmethod is declared above it doesnt work, but if its below it works
i don't know if its a bug , there is mention of order in 
https://docs.modular.com/mojo/programming-manual.html
section: Overloading on parameters

### Steps to reproduce

```
fn is_float(inout self)->Bool:
    return self.o._value.is_float()

@staticmethod   #defined with the static above fail resolve candidate
def is_float(o:object):
     return o._value.is_float()
```

### System information

```shell
- modular 0.1.4 (6b54d308)
- mojo 0.2.1 (64d14e85)
```

**Comment by Mogball** [comment]
@laszlokindrat can you take a look?

**Comment by laszlokindrat** [comment]
Thanks for opening this issue! I wasn't sure exactly what your struct looks like, but I was able to reproduce a crash with this example:
```mojo
struct MyStruct:
    var o: object

    fn __init__(inout self, o: object):
        self.o = o

    fn is_float(inout self) -> Bool:
        return self.o._value.is_float()

    @staticmethod
    def is_float(o: object):
        return o._value.is_float()


def main():
    var a = MyStruct(object())
    _ = a.is_float()
```
I fixed the bug, so this should work correctly in the next release. Please continue to file tickets if you run into issues with this!

**Comment by rd4com** [comment]
thank you so much, iam glad i've been usefull in some ways,
sorry also that the example was not precise enough, i will be precise next time
keep up the good work !!!
