### ISSUE TITLE
[BUG]: Mojo REPL Crash and Parsing Failure during Gauss-Jordan Elimination

### ISSUE THREAD

**Issue by mattfaltyn** [modularml/mojo#712]
### Bug description

**Notebook Cell 5** error: The Mojo REPL has crashed and attempted recovery. If the REPL behaves inconsistently, please restart to ensure correct behavior.
expression failed to parse (no further compiler diagnostics)

### Steps to reproduce

The notebook can be found in this [repo](https://github.com/mattfaltyn/linear-mojobra/blob/main/mat-inv.ipynb).

The objective of this notebook is to build upon the [Matmul tutorial notebook](https://github.com/modularml/mojo/blob/main/examples/notebooks/Matmul.ipynb) by implementing various linear algebra algorithms in Mojo.

### System information

```shell
- Device Specifications
  - Processor: 
    - Type: AMD Ryzen Threadripper PRO 5955WX 
    - Cores: 16
    - Speed: 4.00 GHz
  - Installed RAM: 
    - Total: 256 GB
    - Usable: 256 GB
  - System Type: 
    - OS: 64-bit operating system, Windows 11 using WSL2 (Ubuntu 22.04.3 LTS)
    - Processor Architecture: x64-based
- mojo 0.2.1
- modular 0.1.4
```

**Comment by River707** [comment]
Thank you for reporting this and including a good example of the issue! I can see this as well, we'll take a look.

**Comment by Mogball** [comment]
Closing this because it's too old and the code  no longer works :(
