### ISSUE TITLE
[BUG]: Importing numpy doesnt work

### ISSUE THREAD

**Issue by ashercn97** [modularml/mojo#713]
### Bug description

I used this code:

```
from python import Python 

fn we() raises:
    var np: PythonObject = Python.import_module("numpy")
    print('hi')

def main():
    np = we()
```

and got this error:
```
Unhandled exception caught during execution: An error occurred in Python.
mojo: error: execution exited with a non-zero result: 1
```
unsure what it means.

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

I ran that code in a folder, i ahve the extension installed, i did mojo and then the file name

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`


mojo 0.2.1 (64d14e85)
modular 0.1.4 (6b54d308)
i installed it on windows but using the linux like WSL thing
```

**Comment by KirovClassBattlecruiser** [comment]
did you run "pip install numpy" in the terminal of your WSL?

**Comment by MadAlex1997** [comment]
Also, Mojo does not return by default so for your we function you would need to end it with `return np`.

**Comment by ashercn97** [comment]
Ohh okay ty, lemme work on that

**Comment by ashercn97** [comment]
@MadAlex1997  its not letting me return np

**Comment by ashercn97** [comment]
something about python object

**Comment by ashercn97** [comment]
And now when i wrote this code (its rlly bad but I wanted to test something)

```
from python import Python 
from tensor import Tensor, TensorSpec, TensorShape
from utils.index import Index
from random import rand

let height = 10
let arr1 = rand[DType.float32](height)
let arr2 = rand[DType.float32](height)

def calculateDistance():
    length = height
    a = arr1 
    b = arr2 
    s = []
    for i in range(length):
        dist = a[i] - b[i]
        dist =  dist * dist 
        print(dist)
    return 1 
def main():

    output = calculateDistance()
```

it gave me this error:

```
(some stuff)scaling_cur_freq: No such file or directory (2)
(some stuff)
(some stuff) scaling_max_freq: No such file or directory (2)
(some stuff)ERROR directory_reader_posix.cc:42] opendir /home/username/.modular/crashdb/attachments/(some letters): No such file or directory (2)
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.      Program arguments: mojo test.mojo
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  mojo      (nums)
1  mojo      (num)
2  mojo      (nums)
3  libc.so.6(num)
4  libc.so.6(nums)
Segmentation fault
```

**Comment by MadAlex1997** [comment]
I think that is just a common compiler error, I have a issue written for something kind of similiar. But other than that you aren't defining dist before using it, Assuming you aren't using a notebook you cannot define variables at the file scope they need to be in a function, and you are importing things then not using them. Maybe take this to the discord as your top-level post is not really a bug and there are a lot more people there to help.

**Comment by ashercn97** [comment]
@MadAlex1997  Okay ty. I will close this now
