### ISSUE TITLE
[Feature Request] Implement `__pow__` on `object`

### ISSUE THREAD

**Issue by mccrow2018** [modularml/mojo#722]
### Bug description

Function I defined won't allow me to process the power of a variable, for example

> def func(x):
    return x**2 + 4*x + 5

and gets the error:

> error: Expression [5]:6:13: 'object' does not implement the '__pow__' method
    return x**2 + 4*x + 5
           ~^
expression failed to parse (no further compiler diagnostics)

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by ematejska** [comment]
As a workaround for now try func (x: Int).

**Comment by laszlokindrat** [comment]
Thanks for filing the ticket! This should be implemented in the next release.
