### ISSUE TITLE
[BUG]: error: unable to locate module 'Math'

### ISSUE THREAD

**Issue by Smit-create** [modularml/mojo#723]
### Bug description

```
$ cat hello.mojo
from Math import sqrt

fn main():
    let n: Int = 1000_000
    print(n)
    print(sqrt(n)
```

Help required: How can install the Math package so that mojo finds it?

### Steps to reproduce

Error message:
```
$ mojo hello.mojo
hello.mojo:5:6: error: unable to locate module 'Math'
from Math import sqrt
     ^
mojo: error: failed to parse the provided Mojo
```

### System information

```shell
- What OS did you do install Mojo on ?

22.04.1-Ubuntu
```
- Provide version information for Mojo by pasting the output of `mojo -v`
```
$ mojo --version
mojo 0.2.1 (64d14e85)
```
- Provide Modular CLI version by pasting the output of `modular -v`
```
$ modular -v
modular 0.1.4 (6b54d308)
```
```

**Comment by drunkwcodes** [comment]
The module names are changed to all lower case recently.

`from math import sqrt` should do.

**Comment by Smit-create** [comment]
Thanks. I was following the guide here: https://www.modular.com/blog/an-easy-introduction-to-mojo-for-python-programmers
