### ISSUE TITLE
[Feature Request]: Build jupyter env locally

### ISSUE THREAD

**Issue by dp-dingzhaohan** [modularml/mojo#726]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Hi! I have tried to build a private cloud jupyter lab environment on ubuntu 20.04. 
Blow is my operation, and it seems that doesn't work
1. install anaconda, ipykernel
2. install mojo using official command shell
3. exec "jupyter kernelspec list" to get kernel name : mojo-jupyter-kernel
4. python -m ipykernel install --user --name "mojo-jupyter-kernel" 
5. start up jupyter lab and try mojo code
6. I get syntaxerror

And I found that mojo isn't in jupyter kernel support list: https://github.com/jupyter/jupyter/wiki/Jupyter-kernels.
It will be awesome if you release a package such as "pip install bash_kernel" 👍 
Thanks!

### What is your motivation for this change?

I think it will help mojo let more people know and try it !
And I believe that there is a lot of companies and instituations will deploy mojo in prod env.

**Comment by vishuv** [comment]
```
FROM ubuntu:22.04

ARG DEFAUL_TZ=America/Los_Angeles
ENV DEFAULT_TZ=$DEFAULT_TZ

RUN apt-get update \
   && DEBIAN_FRONTEND=noninteractive $DEFAULT_TZ apt-get install -y \
   tzdata \
   vim \
   sudo \
   curl \ 
   python3 \
   pip \
   && python3 -m pip install \
         jupyterlab \
         ipykernel \
         matplotlib \
         ipywidgets         

ARG AUTH_KEY=DEFAULT_KEY
ENV AUTH_KEY=$AUTH_KEY

RUN curl https://get.modular.com | MODULAR_AUTH=$AUTH_KEY sh - \
    && modular install mojo

ARG MODULAR_HOME="/root/.modular"
ENV MODULAR_HOME=$MODULAR_HOME
ENV PATH="$PATH:$MODULAR_HOME/pkg/packages.modular.com_mojo/bin"
# RUN conda init 
RUN jupyter labextension disable "@jupyterlab/apputils-extension:announcements"
WORKDIR /home/mojo/
CMD ["jupyter", "lab", "--ip='*'", "--NotebookApp.token=''", "--NotebookApp.password=''","--allow-root"]
# docker build --build-arg AUTH_KEY=mut_3166339a3108407b9fd04aed01eb0b1d --pull -t modular/mojo-v0.2 --file Dockerfile.mojosdk .
```
I am using this docker file and it works for me.

**Comment by mahimairaja** [comment]
@vishuv Does this docker image works without exposing the port?

**Comment by vishuv** [comment]
Yeah port needs to be exposed while running. Inside the container Jupyter runs on 8888

**Comment by dp-dingzhaohan** [comment]
Can you please push a image to docker hub? Thanks ! @vishuv

**Comment by River707** [comment]
For now, we're only focused on releasing the Jupyter kernel as part of the SDK, you should be able to install as noted above with simply `modular install mojo`. We should definitely add Mojo to that table though, nice callout! @jackos

**Comment by jackos** [comment]
@dp-dingzhaohan you can also [clone this repo](https://github.com/modularml/mojo)

And follow the [instructions here](https://github.com/modularml/mojo/blob/main/examples/README.md#mojo-sdk-container) to build a container. 

Essentially it's just:
```
cd mojo/examples
docker compose up -d
```
Then you can open Jupyter by going to: http://127.0.0.1:8888/lab
