### ISSUE TITLE
"Illegal Instruction" in Ubuntu WSL2

### ISSUE THREAD

**Issue by QyuJ123456** [modularml/mojo#727]
### Bug description

"Illegal Instruction" when I run "mojo" in WSL2
![Snipaste_2023-09-11_18-39-50](https://github.com/modularml/mojo/assets/107286173/a110bfc6-e7e5-4c54-8fef-31264b185359)

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by Arif812** [comment]
Try using different terminals. I've been seeing this for a while, and the only thing I see in common is "unknown-linux"

**Comment by QyuJ123456** [comment]
> Try using different terminals. I've been seeing this for a while, and the only thing I see in common is "unknown-linux"

So how do you deal with this problem?

**Comment by Mogball** [comment]
The CLI seems to be incorrectly detecting the system configuration and erroneously installing the `mojo` binary. Bumping this over to the CLI folks.

**Comment by bzcheeseman** [comment]
Unfortunately this is gonna be hard to debug. Do you happen to know the CPU architecture you are using? i.e. `skylake` or `haswell`

**Comment by ematejska** [comment]
Thank you for trying out Mojo.  The installation experience has significantly changed and we're closing out all the old issues with the old installer.  To try out our new installation experience using "magic", please see: https://docs.modular.com/mojo/manual/get-started.
