### ISSUE TITLE
[Docs] expressions are not yet supported at the file scope level

### ISSUE THREAD

**Issue by AiharaMahiru** [modularml/mojo#728]
### Where is the problem?

https://docs.modular.com/mojo/manual/basics/#function-arguments-and-returns

### What can we do better?

sample code, the interpreter pointed out that: expressions are not yet supported at the file scope level.This seems to be a place for undetermined methods?
The variable `z` I can define using let or var, while `print` needs to be embedded in the `main` function.
Platform is Ubuntu22.04 on Windows11 WSL2 , development tools are VScode.

### Anything else?

Sample code:
fn add(x: Int, y: Int) -> Int:
    return x + y

z = add(1, 2)
print(z)

**Comment by zefengzhang123** [comment]
i meet this problem as well!!!!!!!!!!!!!!!!!!!!!!!!
could somebody give us a hand?

**Comment by AiharaMahiru** [comment]
> 

Hey bro, have you tried using mojo to call python modules, my side of the program shows an error!

**Comment by Mogball** [comment]
The example in the documentation is written assuming a notebook environment, which at the moment has different rules for top level code. I agree this can be confusing. @scottamain any ideas on how we can improve the distinction in the docs?

**Comment by AiharaMahiru** [comment]
> The example in the documentation is written assuming a notebook environment, which at the moment has different rules for top level code. I agree this can be confusing. @scottamain any ideas on how we can improve the distinction in the docs?

Is it possible to submit additional multilingual documentation via pull requests?

**Comment by zefengzhang123** [comment]
sorry, add the main function not "and"

**Comment by zefengzhang123** [comment]
mojo, like C and C++ requires the "main" function

**Comment by AiharaMahiru** [comment]
> mojo, like C and C++ requires the "main" function

Yes, I think it's acceptable, it would make the program "potentially" neater.

**Comment by scottamain** [comment]
Thanks for the feedback. As mentioned, this does in a notebook environment (or REPL) but it's bad for copy-pasting code.

I think it is also not ideal to include a `main()` function every time we want to show a basic code snippet, so I think the solution is to simply separate pieces of code that should not be pasted together in a Mojo source file. For example, a function definition is one snippet, and the call to that function is separate.

This is also a dupe issue with https://github.com/modularml/mojo/issues/578

**Comment by sedsadegh** [comment]
try this:
____________________
fn main():
   fn add(x: Int, y: Int) -> Int:
      return x + y

   var z = add(1, 2)
   print(z)
   ______________________
   this is working for me
