### ISSUE TITLE
[BUG]: Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it)

### ISSUE THREAD

**Issue by aviralshastri** [modularml/mojo#729]
### Bug description

When i am trying to take input from user and print output after addition of the users inputs its gives me this error: 

"Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it)" 

This is the code:

from python import Python

fn main() raises:
    let user_input1= Python.evaluate("input('Num 1: ')").to_float64()
    let user_input2= Python.evaluate("input('Num 2: ')").to_float64()
    let add= user_input1 + user_input2
    print(add)

This is the error:

Num 1: 66
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.      Program arguments: mojo test.mojo
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  mojo                 0x000055dccc040717
1  mojo                 0x000055dccc03e2ee
2  mojo                 0x000055dccc040def
3  libc.so.6            0x00007f44ed442520
4  libpython3.10.so.1.0 0x00007f44ca32834f PyModule_GetDict + 15
5  libpython3.10.so.1.0 0x00007f4474001381 PyModule_GetDict + 18446744072263405633
Segmentation fault (core dumped)

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by ematejska** [comment]
Thank you for filing this.  This is a known issue right now.

**Comment by sigrace1111** [comment]
same issue , how to fix it,now?

**Comment by JoeLoser** [comment]
The above gist from @jackos should work fine for setting `LLVM_SYMBOLIZER_PATH` so that you get symbolicated parts of the trace where possible.  Do note that we currently ship the mojo-sdk without debug symbols, so you won't get the full symbolicated parts if there is a crash inside Modular code.  We may revisit this in the future, but that is the case for today.

Please feel free to re-open this issue if the suggestion from @jackos does not work or we can help debug your specific problem.  Thanks!

**Comment by thphuc** [comment]
Looks like the suggestion from @jackos is for Linux? Do we have a similar suggestion for Mac OS?

**Comment by BrettFraley** [comment]
I just hit this issue on Ubuntu 23.10 Mantic as well and will report back. Thanks.

**Comment by NiklausParcell** [comment]
Has this issue been fixed and is there a solution to this?

**Comment by jackos** [comment]
@NiklausParcell does this work for you? https://gist.github.com/trevorhobenshield/6bca58f947ad6115a113a97072df1a73

**Comment by smashcoder2003** [comment]
I am having the same issue on Mac-Sonoma 14.5
