### ISSUE TITLE
[BUG]: Consumption of struct works only on definition of __del__

### ISSUE THREAD

**Issue by ivellapillil** [modularml/mojo#734]
### Bug description

I expect the following code to raise compile time error:
```
struct Mo:
    var x: Int

    fn __init__(inout self, a: Int):
        self.x = a

    #fn __del__(owned self):
    #    pass

def take(owned x: Mo):
    print(x.x) 

def main():
    var l: Mo = Mo(100)
    take(l^)
    l.x = 10
    print("Again " + String(l.x))

```
However, it compiles successfully. 

If I uncomment the ```__del__``` method, then it shows:

```
error: value 'l' cannot be consumed, because 'l.x' is used later
    take(l^)

```

I would have expected moving a location should not be dependent on definition of a destructor. 

### Steps to reproduce

Compile with the above code.

### System information

```shell
x86_64
Ubuntu 22.04.2 LTS
Linux-5.19.0-38-generic-x86_64-with-glibc2.35
mojo 0.2.1 (64d14e85)

modular 0.1.4 (6b54d308)
```

**Comment by Mogball** [comment]
This is super weird. I'll take a look.

**Comment by Mogball** [comment]
@stumpOS when you have some free cycles, could you take a look at this?

**Comment by lattner** [comment]
This is likely a checklifetimes problem, I'll investigate.

**Comment by lattner** [comment]
Indeed good catch, CheckLifetimes is currently ignoring types that don't have a destructor for liveness analysis.  The rationale is that there is no codegen need to know whether something is alive, and the parser does various simplifications for trivial types.  As you mention, codegen isn't all that matters though.

The solution here is to tighten up checklifetimes thing to work on actually-trivial types and not just destructor-less things.  The parser should also reject the transfer operator on trivial types.
