### ISSUE TITLE
[Modular CLI]: Do follow Freedesktop's XDG Base Directory Specification

### ISSUE THREAD

**Issue by gdonval** [modularml/mojo#739]
### Issue description

`modular` behaves like a punk, trying to dump state and garbage in `~/.modular`.

Please follow the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). The minimum would be following `$XDG_CONFIG_HOME/modular` (falling back to `~/.config/modular` if not set). You could also use `$XDG_STATE_HOME/modular` to store auth tokens for the time being (defaults to `~/.local/state/modular`). I am not sure yet where mojo is eventually installed, but `$XDG_DATA_HOME/modular/mojo` (defaulting to `~/.local/share/modular`) would probably be the right place for a user install.

### Steps to reproduce

- `rm -rf ~/.modular`
- `chmod -R a-w ~/`
- `modular auth XXX`
modular: error: ~/.modular could not be created: Permission denied

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.1.4 (6b54d308)

- What OS did you install modular CLI on ?
Ubuntu
```

**Comment by zbowling** [comment]
A partial workaround today is to set MODULAR_HOME to your $XDG_CONFIG_HOME. 

Eg:
```shell
export MODULAR_HOME="$XDG_STATE_HOME/modular"
modular auth ...
modular install ...
```

**Comment by bzcheeseman** [comment]
Closing since a workaround exists, and this is not on our roadmap.

**Comment by gdonval** [comment]
Put it on your roadmap. Not following standards is not "playing nicely".

Your workaround is just that, a workaround. If what you were providing was a toaster, I would be complaining that providing a toaster with a UK power plug in the US does not make sense: follow the standards. Your workaround is akin to telling people to have a UK power socket fitted in your US home, when what I ask for is a converter on the plug you provide.

**Comment by ksandvik** [comment]
There is a workaround and the future of the installation system could change.

**Comment by gdonval** [comment]
Not if you don't put it on your roadmap.

Changing a custom, Modular-specific, environment variable is not following the standard. I'm not even sure why you think that is. The default should be `.config/modular` or `$XDG_CONFIG_HOME/modular` with your custom variable overriding that if set.

The fix is super easy, if the code wasn't closed, I could provide one in 20 minutes max, without having had a look at the code before.

The problem with this is that if left alone, there will be always someone to complain in the dev team that `~/.modular` has always been the place and it will be rejected because "users would be confused". Modular is offensive to Linux users, not playing along, forcing them to do something special (i.e. fitting UK power sockets in US homes) to get it work as intended. Just provide the right power cable.
