### ISSUE TITLE
[Feature Request] Improved messaging on how to exit REPL

### ISSUE THREAD

**Issue by flaar94** [modularml/mojo#740]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

This may be a bit pedestrian, but I think it would be better if you could make a bit clearer how to exit the REPL, maybe add it directly in the welcome message (or just mention the need to prefix commands with a colon). Alternatively, it could be added more prominently in the help message (currently buried in an example)

### What is your motivation for this change?

Spent a couple minutes trying to figure out how to leave the REPL, getting flashbacks to when I was a baby programmer and trying to leave VIM

**Comment by drunkwcodes** [comment]
Is the KeyboardInterrupt(Ctrl+C) not working for you?

Hi, I notict that you are also a flasker, nice to meet you, @flaar94.

**Comment by flaar94** [comment]
Hi! It's been ages since I've done anything in Flask :), but I've been meaning to get back into it and maybe package some stuff I've been working on into a web app

Checking: ctrl+C does work for me! I didn't try ctrl C when I was trying to exit, in hindsight probably because in the Python REPL that just interrupts the interpreter, and doesn't exit the REPL. Maybe I'm just too afflicted with Python brain then. What I tried was exit(), exit, quit(), quit, q(), q, then I tried to skim the help message (missed the example), then I searched online, and finally got flashbacks to VIM and tried :q and it worked!

**Comment by drunkwcodes** [comment]
Oh, that's a lot of tries!

By the way, I have a [skeleton project](https://github.com/drunkwcodes/matty_web) for you, hope that it could help: 
It has login, register, session management out-of-the-box, even a profile page!

And this is my [MojoPI Project](https://github.com/drunkwcodes/mojopi).
It is currently supporting API docs with `flask-restx`, maybe a good reference for you.

Any feedback is welcome.

Welcome to join me and mojo community!

**Comment by flaar94** [comment]
Thanks! That is actually very useful. I'll check them both out tomorrow

**Comment by walter-erquinigo** [comment]
I have a fix ready that will be available in a future release.

**Comment by drunkwcodes** [comment]
@walter-erquinigo Additional: KeyboardInterrupt is useful in canceling halting programs. 

Please change quitting shortcut from ctrl-c to ctrl-d, thanks.
It is same with ipython and Ubuntu python3 REPL.

**Comment by walter-erquinigo** [comment]
You should be able to exit the REPL with both ctrl-c and ctrl-d. Let me know if that doesn't work for you.

**Comment by drunkwcodes** [comment]
I wish I can continue in REPL after I pressed ctrl-c.

**Comment by walter-erquinigo** [comment]
Could you submit another issue for that? :)

**Comment by drunkwcodes** [comment]
@walter-erquinigo It's just a little suggestion.
I'm not hurry for that.

Maybe it is a good first issue after you open source the REPL.

**Comment by walter-erquinigo** [comment]
Actually the REPL is built on top of LLDB's REPL support, just like the swift REPL. This means that the ctrl-c behavior is something that could be proposed to LLDB proper via a patch. I encourage you to do that!

**Comment by drunkwcodes** [comment]
@walter-erquinigo Alright!

I had a glance on [REPL.cpp L86](https://github.com/llvm/llvm-project/blob/347b3f120903fcdc255b78177cb584e4c0aa4b54/lldb/source/Expression/REPL.cpp#L86)

It looks like ctrl-c is prevented to quit already.
Is that line omitted?

**Comment by walter-erquinigo** [comment]
@drunkwcodes  That sounds like an LLDB bug :) Probably that function is not doing what it should.
