### ISSUE TITLE
[Mojo]:  error while loading shared libraries

### ISSUE THREAD

**Issue by icebergwater** [modularml/mojo#744]
### Issue description

Hello,everyone:

I write the code:

`
from python import Python

fn main() raises:
  let _os = Python.import_module("os")
  let result=_os.system("ls -al")
  print(result)
`

and build the code to a binary file by the cli tool:  mojo build

`mojob build python_test.mojo`

And copy the binary file: python_test to another ubuntu linux os,run try to run it.

It show the error:

`./run_mojo_example: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory`

the build code server os info:

Ubuntu 22.04.1 LTS
mojo 0.2.1 (64d14e85)
Python 3.10.12

the another os info:

Ubuntu 14.04
Python 3.6.8

Thanks for advance!

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### Version Info

```shell
root@dev-temp-0:/home/ubuntu/mojo_example# mojo --version
mojo 0.2.1 (64d14e85)
root@dev-temp-0:/home/ubuntu/mojo_example# modular --version
modular 0.1.4 (6b54d308)
```

**Comment by drunkwcodes** [comment]
@icebergwater Note: multi-line code needs 3 backticks.

I'm also curious about this.

**Comment by icebergwater** [comment]
I am sorry for the code format

This is  error the snap:

![image](https://github.com/modularml/mojo/assets/8638848/756086d5-1c8a-42ef-8194-8c7999f0c087)

Build the code:

<img width="658" alt="image" src="https://github.com/modularml/mojo/assets/8638848/bc6c1f17-de40-4363-9b4c-20fd215b8395">

Scp to another ubuntu linux and run it:

![image](https://github.com/modularml/mojo/assets/8638848/fee17061-f71f-458c-90c0-c60a00809395)


Thanks

**Comment by jackos** [comment]
Hi @icebergwater can you try:

```bash
modular clean
modular install mojo
```
And then if that doesn't work, show the output of:
```
ls /usr/lib/libtinfo*
```

**Comment by jackos** [comment]
Closing after no response, make sure to update to latest cli if you run into this issue:

```
modular clean
sudo apt update
sudo apt install modular
modular install mojo
```
