### ISSUE TITLE
[Feature Request] add support for AlmaLinux 8 /9 , to gain enterprise usage environment

### ISSUE THREAD

**Issue by ghost** [modularml/mojo#746]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

[Feature Request] add support for AlmaLinux 8 /9 , to gain enterprise usage environment

### What is your motivation for this change?

[Feature Request] add support for AlmaLinux 8 /9 , to gain enterprise usage environment

### Any other details?

[Feature Request] add support for AlmaLinux 8 /9 , to gain enterprise usage environment

**Comment by trotsky1997** [comment]
Wow, will mojo with flask will being a new backend paradigm?

**Comment by walter-erquinigo** [comment]
Thank you for reporting this. I'm closing this for now. Eventually we'll include other OS - architectures.
