### ISSUE TITLE
[BUG]: hello, I can't install mojo on ubuntu 22

### ISSUE THREAD

**Issue by nosovdmitry007** [modularml/mojo#751]
### Bug description

sudo curl https://get.modular.com | \
  MODULAR_AUTH=mut_3930f6b80a244247bd63b0de84d0b20d \
  sh -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3176  100  3176    0     0   8979      0 --:--:-- --:--:-- --:--:--  8997
Executing the  setup script for the 'modular/installer' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=ubuntu  version=22.04  codename=jammy  arch=x86_64  
 >>>>:
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
  RUN: Importing 'modular/installer' repository GPG keys ...gpg: Внимание: небезопасный владелец домашнего каталога '/home/dima/.gnupg'
   OK: Checking for apt signed-by key support ...
   OK: Importing 'modular/installer' repository GPG keys ...
   OK: Checking if upstream install config is OK ...
   OK: Installing 'modular/installer' repository via apt ...
 NOPE: Updating apt repository metadata cache ...
Failed to update via apt-get update
Игн:1 cdrom://Ubuntu 22.04 LTS _Jammy Jellyfish_ - Release amd64 (20220419) jammy InRelease
Ошб:2 cdrom://Ubuntu 22.04 LTS _Jammy Jellyfish_ - Release amd64 (20220419) jammy Release
  Используйте apt-cdrom, чтобы APT смог распознать данный CD-ROM. apt-get update не используется для добавления новых CD-ROM
Сущ:3 http://ru.archive.ubuntu.com/ubuntu jammy InRelease
Сущ:4 http://ru.archive.ubuntu.com/ubuntu jammy-updates InRelease
Сущ:5 http://ru.archive.ubuntu.com/ubuntu jammy-backports InRelease
Сущ:6 http://ru.archive.ubuntu.com/ubuntu jammy-proposed InRelease
Сущ:7 https://download.docker.com/linux/ubuntu jammy InRelease
Пол:8 https://dl.modular.com/public/installer/deb/ubuntu jammy InRelease [5,076 B]
Сущ:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Сущ:10 http://archive.ubuntu.com/ubuntu jammy InRelease
Сущ:11 http://security.ubuntu.com/ubuntu jammy-security InRelease
Сущ:12 http://packages.ros.org/ros2/ubuntu jammy InRelease
Сущ:13 https://ppa.launchpadcontent.net/lumas/photoqt/ubuntu jammy InRelease
Игн:14 https://ppa.launchpadcontent.net/ubuntu-desktop/ubuntu-make/ubuntu jammy InRelease
Сущ:15 http://apt.postgresql.org/pub/repos/apt jammy-pgdg InRelease
Игн:16 http://apt.postgresql.org/pub/repos/apt -pgdg InRelease
Ошб:17 http://apt.postgresql.org/pub/repos/apt -pgdg Release
  404  Not Found [IP: 217.196.149.55 80]
Ошб:18 https://ppa.launchpadcontent.net/ubuntu-desktop/ubuntu-make/ubuntu jammy Release
  404  Not Found [IP: 185.125.190.52 443]
Чтение списков пакетов…
E: Репозиторий «cdrom://Ubuntu 22.04 LTS _Jammy Jellyfish_ - Release amd64 (20220419) jammy Release» не содержит файла Release.
W: Цель Packages (main/binary-amd64/Packages) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель Packages (main/binary-i386/Packages) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель Packages (main/binary-all/Packages) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель Translations (main/i18n/Translation-en_US) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель Translations (main/i18n/Translation-en) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель Translations (main/i18n/Translation-ru) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель Translations (main/i18n/Translation-en_GB) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель DEP-11 (main/dep11/Components-amd64.yml) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель DEP-11 (main/dep11/Components-all.yml) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель DEP-11-icons-small (main/dep11/icons-48x48.tar) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель DEP-11-icons (main/dep11/icons-64x64.tar) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель DEP-11-icons-hidpi (main/dep11/icons-64x64@2.tar) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель CNF (main/cnf/Commands-amd64) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель CNF (main/cnf/Commands-all) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
E: Репозиторий «http://apt.postgresql.org/pub/repos/apt -pgdg Release» не содержит файла Release.
E: Репозиторий «https://ppa.launchpadcontent.net/ubuntu-desktop/ubuntu-make/ubuntu jammy Release» не содержит файла Release.
W: Цель Packages (main/binary-amd64/Packages) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель Packages (main/binary-i386/Packages) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель Packages (main/binary-all/Packages) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель Translations (main/i18n/Translation-en_US) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель Translations (main/i18n/Translation-en) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель Translations (main/i18n/Translation-ru) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель Translations (main/i18n/Translation-en_GB) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель DEP-11 (main/dep11/Components-amd64.yml) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель DEP-11 (main/dep11/Components-all.yml) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель DEP-11-icons-small (main/dep11/icons-48x48.tar) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель DEP-11-icons (main/dep11/icons-64x64.tar) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель DEP-11-icons-hidpi (main/dep11/icons-64x64@2.tar) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель CNF (main/cnf/Commands-amd64) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
W: Цель CNF (main/cnf/Commands-all) настроена несколько раз: в /etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-jammy.list:1 и в /etc/apt/sources.list.d/python.list:1
 ^^^^: ... Failed to update via apt-get update - Context above.
 !!!!: Oh no, your setup failed! :-( ... But we might be able to help. :-)
 !!!!: 
 !!!!: You can contact Modular for further assistance.
 !!!!: 

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.

 sudo curl https://get.modular.com | \
  MODULAR_AUTH=mut_3930f6b80a244247bd63b0de84d0b20d \
  sh -

- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
distro=ubuntu  version=22.04  codename=jammy  arch=x86_64
```

**Comment by happymilf** [comment]
Попробуй запустить на Ubuntu 20. У меня с версией 22 тоже были проблемы

**Comment by smuniraj2018** [comment]
Please run apt-get update. Looks like something in your system is broken.

**Comment by jackos** [comment]
Hi @happymilf there are problems with outdated apt packages, please follow this guide to fix them: https://linuxhint.com/apt_get_fix_missing_broken_packages/

**Comment by nosovdmitry007** [comment]
Hi Managed to deliver using the following commands:

 sudo  apt-get install -y apt-transport-https &&
  curl  'https://dl.modular.com/bBNWiLZX5igwHXeu/installer/gpg.0E4925737A3895AD.key' |tac | tac | sudo gpg --armor  -o /usr/share/keyrings/modular-installer-archive-keyring.gpg &&
  curl -sl 'https://dl.modular.com/bBNWiLZX5igwHXeu/installer/config.deb.txt?distro=debian&codename=wheezy' > sudo /etc/apt/sources.list.d/modular-installer.list &&
  sudo apt-get update &&
  sudo apt-get install -y modular
