### ISSUE TITLE
[Feature Request] Docker / Apple Silicon host

### ISSUE THREAD

**Issue by loretoparisi** [modularml/mojo#758]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

When running `modular install mojo`

```bash
root@3870e28c2a09:/app# modular install mojo
modular: error: no packages found for the current target hardware - please run `modular host-info` and file a ticket at https://github.com/modularml/mojo with your hardware information
```

Host Information:
```bash
  Host Information
  ================

  Target Triple: arm64-unknown-linux
  CPU: generic
  CPU Features: crc, crypto, fp-armv8, lse, neon
```

### What is your motivation for this change?

Support Docker / host Apple Silicon

### Any other details?

Following the Dockerfile used

```Dockerfile
FROM ubuntu:23.04

ENV ROOT_APPLICATION /app
ENV HOST=0.0.0.0
ENV PORT=8000

WORKDIR $ROOT_APPLICATION

RUN apt-get update && apt-get install -y \
    software-properties-common \
    build-essential \
    pkg-config \
    ninja-build \
    libopenblas-dev \
    python3-pip \
    curl

COPY . $ROOT_APPLICATION

RUN curl https://get.modular.com | \
  MODULAR_AUTH=mut_c6464664cc674dcbaaee3f8027305b46 \
  sh -
#RUN modular install mojo

EXPOSE 8000

CMD ["bash"]
```

**Comment by DmarshalTU** [comment]
i will add my two cent, i tried to run the mojo instalation om mac m1 based on limactl and "fake" my arch with local ubuntu vm, module cli was installed :

`modular 0.1.4 (6b54d308)`

but when i tried to run modular install mojo:

`PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: modular install mojo
 #0 0x000055bb4b6fb567 (/usr/bin/modular+0x4ee567)
 #1 0x000055bb4b6f921e (/usr/bin/modular+0x4ec21e)
 #2 0x000055bb4b6fbc2f (/usr/bin/modular+0x4eec2f)
 #3 0x00007f34dfa3c4b0 (/lib/x86_64-linux-gnu/libc.so.6+0x3c4b0)
 #4 0x000055bb4c72c710 (/usr/bin/modular+0x151f710)
 #5 0x000055bb4bab6e78 (/usr/bin/modular+0x8a9e78)
 #6 0x000055bb4b6b74ad (/usr/bin/modular+0x4aa4ad)
 #7 0x000055bb4b6b5fe0 (/usr/bin/modular+0x4a8fe0)
 #8 0x00007f34dfa23a90 (/lib/x86_64-linux-gnu/libc.so.6+0x23a90)
 #9 0x00007f34dfa23b49 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x23b49)
#10 0x000055bb4b6b568e (/usr/bin/modular+0x4a868e)
Illegal instruction (core dumped)`

**Comment by jackos** [comment]
That's a really cool experiment @DmarshalTU, unfortunately it won't work through QEMU or Rosetta emulation, but please upvote this ticket to show support for native Apple Silicon support: https://github.com/modularml/mojo/issues/510
