### ISSUE TITLE
[BUG]: Compilation error: 'hlcf.for.yield' op specifies 0 branch inputs but target expected 1 along control-flow edge from here

### ISSUE THREAD

**Issue by gujuriu** [modularml/mojo#760]
### Bug description

The following code:
```
fn main():
    var n: Int = 0
    while n < 1_000_000_000:
        n += 1
        # if n > 1_000_000_000:
        #     break

    print(n)
```

will cause the compiler `mojo build b.mojo` to throw the following error:
```
b.mojo:3:5: error: 'hlcf.for.yield' op specifies 0 branch inputs but target expected 1 along control-flow edge from here
    while n < 1_000_000_000:
    ^
b.mojo:3:5: note: see current operation: "hlcf.for.yield"(%18) {operandSegmentSizes = array<i32: 1, 0, 0>} : (index) -> ()
b.mojo:3:5: note: to end of parent operation here
mojo: error: failed to run the pass manager
```
If I uncomment lines 5 & 6, the compilation will be successful. I created a new function and I tried to call call it after the line with `n += 1` but it makes no difference, if I move the print statement inside the while loop or if I delete it ...will compile just fine but that's not my point.

### Steps to reproduce

- create a file called 'b.mojo' with the code from bug description, save it and run the following command in the folder where you saved the file: `mojo build b.mojo`
- expected: build to be successful
- actual: build process will throw an error (see description from above)

### System information

```shell
- OS "Ubuntu 22.04.2 LTS" installed in Windows 10 x64 via WSL2
- mojo 0.2.1 (64d14e85)
- modular 0.1.4 (6b54d308)
```

**Comment by Mogball** [comment]
@weiweichen can you please take a look?
