### ISSUE TITLE
[Modular CLI]: Using deb on Fedora via DNF fails with missing dependency

### ISSUE THREAD

**Issue by Abdelkader-gnichi** [modularml/mojo#761]
### Issue description

after setting up the  MODULAR_HOME and PATH environment variables on Fedora 38 i can't use the REPL, when i type mojo in my terminal it shows that this command is not found, Furthermore i can't run a simple mojo file in vscode containing only a print("hello wold").

### Steps to reproduce

- the CLI installation process in my Fedora 38 system is all right.
- then i setup MODULAR_HOME and PATH environment variables like shown in the Hello, world! section in the mojo website
- unfortunately after that when i use the mojo command in my terminal to use the REPL it output that this command it's not found .
- In addition to that i can't run a simple mojo file that contains a print("hello world") statement in vscode (i already install the mojo extension in vscode) .

### Version Info

```shell
- modular: /lib64/libtinfo.so.6: no version information available (required by modular)
modular 0.1.4 (6b54d308)
- Fedora 38 ?
```

**Comment by AlmirNeeto99** [comment]
Have you tried `sudo apt install libtinfo6`?

**Comment by Abdelkader-gnichi** [comment]
> Have you tried `sudo apt install libtinfo6`?
> 
> And then running mojo?

no i don't try that but i'm using fedora so i use dnf instead of apt to install a package. 
and any way i will install libtinfo6 and tell you what happen, thank you very much.

**Comment by Abdelkader-gnichi** [comment]
> Have you tried `sudo apt install libtinfo6`?
> 
> And then running mojo?

ok in fedora to install libtinfo6 you must install  ncurses-libs instead and it provides the libtinfo6 package by default, so the ncurses-libs (which provides the libtinfo6 package) package is already installed in my system and till can't use the mojo command or even i can't run any .mojo file in vscode.

**Comment by zbowling** [comment]
Unfortunately we can't directly support dnf for installing debs on non-Debian based linux distros but RPMs are planned.
