### ISSUE TITLE
[Dev Console]: [6324:6324:20230913,004942.890870:ERROR file_io_posix.cc:144] 

### ISSUE THREAD

**Issue by gsshawn** [modularml/mojo#763]
### Issue description

pythontest.mojo:
from python import Python
fn main():
    try:
        print("start")
        let np = Python.import_module("numpy")
        let ar = np.arange(15).reshape(3, 5)
        print(ar)
        print(ar.shape)
    except e:
        print(e.value)
        print("could not find module")

mojo pythontest.mojo
start
[6324:6324:20230913,004942.890870:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[6324:6324:20230913,004942.890979:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.      Program arguments: mojo pythontest.mojo
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  mojo      0x0000560fd8b94957
1  mojo      0x0000560fd8b9252e
2  mojo      0x0000560fd8b9502f
3  libc.so.6 0x00007f92bb07e520
Segmentation fault

### Steps to reproduce

- Add screenshots if possible, to help explain the problem.
- Include anything that might help us debug the issue.

**Comment by jackos** [comment]
Try this: https://gist.github.com/trevorhobenshield/6bca58f947ad6115a113a97072df1a73

**Comment by ematejska** [comment]
Closing out this issue. Please let us know if you need more help after the suggestion above.
