### ISSUE TITLE
Unable to use C/C++ Interop on Ubuntu 

### ISSUE THREAD

**Issue by mahimairaja** [modularml/mojo#767]
#### VERSION:
`
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
`

I tried to execute a `C` code using mojo, I have g++ installed in my machine but still I am not able to execute the program.

### Program:
```python
from "math.h" import cos

print(cos(0))
```

### Console  output
``` bash
$ mojo hello.mojo 
```

``` bash
hello.mojo:1:6: error: expected module name
from "math.h" import cos
     ^
mojo: error: failed to parse the provided Mojo
```

**Comment by ematejska** [comment]
Thanks for filing.  This is on our roadmap: [C/C++ Interop](https://docs.modular.com/mojo/roadmap.html#cc-interop)

**Comment by programmingmaster434** [comment]
And Im also Getting this error

**Comment by slagernate** [comment]
any more clarity on the eta for this? Thanks!
