### ISSUE TITLE
[BUG]: Compile hashlib errors using mojo on ubuntu

### ISSUE THREAD

**Issue by main1015** [modularml/mojo#768]
### Bug description

Unable to import the hashlib library for the system

### Steps to reproduce

My code is as follows
hello.mojo
`
from python import Python

fn main() raises:
    let hashlib = Python.import_module("hashlib")
    print("Hello, world!")
`
I execute the sub-file
`mojo hello.mojo`

Execution results
`
ERROR:root:code for hash blake2b was not found.
Traceback (most recent call last):
  File "/usr/lib/python3.10/hashlib.py", line 261, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python3.10/hashlib.py", line 129, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/usr/lib/python3.10/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type blake2b
ERROR:root:code for hash blake2s was not found.
Traceback (most recent call last):
  File "/usr/lib/python3.10/hashlib.py", line 261, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python3.10/hashlib.py", line 129, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/usr/lib/python3.10/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type blake2s
Hello, world!

`

I execute in python and it is completely fine

### System information

```shell
My python version is: Python 3.10.12
My mojo version is: mojo 0.2.1 (64d14e85)
My system is：
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

**Comment by jackos** [comment]
@main1015  try installing [miniconda](https://docs.conda.io/projects/miniconda/en/latest/) and doing:
```
conda create -yn py311 python=3.11 numpy matplotlib
conda activate py311

export MOJO_PYTHON_LIBRARY="$(ls $(conda info --base)/envs/py311/lib/libpython*)"
echo "export MOJO_PYTHON_LIBRARY=$MOJO_PYTHON_LIBRARY" >> ~/.bashrc
```
