### ISSUE TITLE
[BUG]: Mojo VS Code extension results in error dialog when debugging

### ISSUE THREAD

**Issue by ngocngoan** [modularml/mojo#769]
### Bug description

I have been installed successfully the [Mojo extension for VS Code](https://marketplace.visualstudio.com/items?itemName=modular-mojotools.vscode-mojo). But, when I have started to debug source [hello](https://github.com/modularml/mojo/blob/main/examples/hello.%F0%9F%94%A5), then VS Code showed an error dialog:
![Screenshot from 2023-09-13 14-24-54](https://github.com/modularml/mojo/assets/18467776/b6602d0e-afe7-4aad-90b1-1ff684d2dc66)

### Steps to reproduce

- Install the latest Mojo extension.
- Reload VS Code.
- Clone example source from https://github.com/modularml/mojo.git
- Set the debug configuration in the file `.vscode/launch.json` with the following content:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "mojo-lldb",
            "request": "launch",
            "name": "Debug",
            "program": "${workspaceRoot}/examples/hello.🔥",
            "args": [],
            "env": [],
            "cwd": "${workspaceRoot}"
        }
    ]
}
```
- hit F5 button

### System information

- OS
```shell
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

- Vscode
```shell
Version: 1.82.1
Commit: 6509174151d557a81c9d0b5f8a5a1e9274db5585
Date: 2023-09-08T08:41:36.199Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.2.0-32-generic
```

- Mojo version
```shell
mojo 0.2.1 (64d14e85)
```

- Provide Modular CLI version
```shell
modular 0.1.4 (6b54d308)
```

**Comment by jackos** [comment]
Hi @ngocngoan thanks for reporting, it's an experimental feature and is still being worked on, but we can leave this open until it's working for everyone.

**Comment by jradxl** [comment]
Found same. Pity! I'll be patient
J

**Comment by mqbojee** [comment]
Is there a requirement for system architecture? We also get this error and can't use debugger.

**Comment by ngocngoan** [comment]
The same error on the M1 Mac 

<img width="514" alt="Screenshot 2023-10-19 at 23 56 41" src="https://github.com/modularml/mojo/assets/18467776/227212ae-3ff8-4634-b757-6cb7aa2e5222">

**Comment by gmerendino** [comment]
Found same.

**Comment by River707** [comment]
Debugging is not yet fully released as part of the SDK, but is coming very soon! @walter-erquinigo

**Comment by walter-erquinigo** [comment]
This will be fixed in the upcoming release on Linux, and Mac will be supported in the following release.

Thanks for the report!
