### ISSUE TITLE
[Modular CLI]: failed to run 'modular install mojo': failed to reach URL https://packages.modular.com/mojo/1.root.json with cURL error SSL connect error

### ISSUE THREAD

**Issue by carusyte** [modularml/mojo#771]
### Issue description

As captioned, it seems that the URL is returning HTTP error 400.

### Steps to reproduce

modular clean
modular install mojo

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.1.4 (6b54d308)
- What OS did you install modular CLI on ?
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```

**Comment by A-yb** [comment]
Me too!  (ubuntu 22.04)

**Comment by franchesoni** [comment]
same

**Comment by fortunewalla** [comment]
This is for Red Hat 9

```
$ modular install mojo
modular: /lib64/libtinfo.so.6: no version information available (required by modular)
modular: error: http error: failed to reach URL https://packages.modular.com/mojo/1.root.json with cURL error Problem with the SSL CA cert (path? access rights?) -
```

**Comment by DavidChan0519** [comment]
me too(Ubuntu-20.04), come from China

**Comment by fortunewalla** [comment]
> Your SSL certs are incorrect somehow. Usually you can fix this on ubuntu with the ca-certificates package.

#### I tried to update `ca-certificates` but it is already updated.

```
$ sudo dnf install ca-certificates
Updating Subscription Management repositories.
Last metadata expiration check: 0:01:54 ago on Tue 19 Sep 2023 07:06:25 AM IST.
Package ca-certificates-2023.2.60_v7.0.306-90.1.el9_2.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!

$ sudo dnf update ca-certificates
Updating Subscription Management repositories.
Last metadata expiration check: 0:04:14 ago on Tue 19 Sep 2023 07:06:25 AM IST.
Dependencies resolved.
Nothing to do.
Complete!

```

#### I tried to install again but same error.

```
$ modular install mojo
modular: /lib64/libtinfo.so.6: no version information available (required by modular)
modular: error: http error: failed to reach URL https://packages.modular.com/mojo/1.root.json with cURL error Problem with the SSL CA cert (path? access rights?) -
```

**Comment by malar-coinbase** [comment]
It is serving invalid certs.
<img width="1314" alt="Screenshot 2023-09-20 at 2 08 57 PM" src="https://github.com/modularml/mojo/assets/127215186/db38f6fa-e8ef-4abe-a99f-94c159e50de6">

**Comment by carusyte** [comment]
Finally managed to build a docker image and VS Code dev container which seems workable. Hope it could be of some help to those facing similar issue wanting to jumpstart. 

[https://github.com/carusyte/mojo-play](https://github.com/carusyte/mojo-play)

**Comment by BeeCodeB** [comment]
Related issue: https://github.com/modularml/mojo/issues/889

Modular seems to have problems with mojo-sdk installs inside modular-cli installs on bare metal computer systems running Ubuntu/GNU Linux OS?

**Comment by julwrites** [comment]
Similar issue here on Macbook Pro M2? 

`modular: error: http error: failed to reach URL https://packages.modular.com/mojo/1.root.json with cURL error SSL peer certificate or SSH remote key was not OK`

**Comment by BeeCodeB** [comment]
On the Mojo website they state it is supposed to be a firewall error. It's definitely not. It is entirely not a problem on the user side. They hasle and struggle to understand the concept of installation of a programming level outside a container *environment* - as they call it. They then confluate the situation of cloud installs with local installs and it results in a haze of problem search -- there's a lack of analysis from a higher plane of *abstraction* ..

**Comment by dafu-wu** [comment]
> Similar issue here on Macbook Pro M2?
> 
> `modular: error: http error: failed to reach URL https://packages.modular.com/mojo/1.root.json with cURL error SSL peer certificate or SSH remote key was not OK`

any update?

**Comment by liudonghua123** [comment]
Me too on almalinux 9.2. See details on https://github.com/modularml/mojo/issues/938#issuecomment-1845255863.

**Comment by akerenyi** [comment]
Same issue.
```
Modular version: modular 0.3.1 (589ce200)
Hardware: Apple M1 MacBook Pro (2020)
OS: macOS 14.2 (23C64) Sonoma
```

**Comment by tm65** [comment]
Same issue on WSL Ubuntu 22.04

**Comment by andybergon** [comment]
Same on:
```
macOS 14.2.1
modular 0.4.1 (2d8afe15)
```

**Comment by xiaoaiwhc** [comment]
For this issue, a proxy which can bypass GFW could help you. Given that a VPN is ready, you can set up the proxy in WSL2 as the following commands:
`host_ip=$(cat /etc/resolv.conf |grep "nameserver" |cut -f 2 -d " ")`
`export http_proxy=http://$host_ip:your_vpn_port`
`export https_proxy=http://$host_ip:your_vpn_port`

**Comment by ematejska** [comment]
Thank you for trying out Mojo.  The installation experience has significantly changed and we're closing out all the old issues with the old installer.  To try out our new installation experience using "magic", please see: https://docs.modular.com/mojo/manual/get-started.
