### ISSUE TITLE
[Modular CLI]: http error: failed to reach URL https://cas.modular.com/0/UPIL1ruIyvACcPFEhM2zaS07qL6HU8X-WwR5STwZNNc with cURL error SSL connect error - Looking for UPIL1ruIyvACcPFEhM2zaS07qL6HU8X-WwR5STwZNNc

### ISSUE THREAD

**Issue by A-yb** [modularml/mojo#772]
### Issue description

Failed to run the “ **modular install mojo** ”command

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.1.4 (6b54d308)

- What OS did you install modular CLI on ?
ubuntu 22.04.3 LTS
```

**Comment by KingSann** [comment]
may be missing ssh keys, try `ssh-keygen` and run it again?

**Comment by bzcheeseman** [comment]
Please install the ca-certificates package and try again :) It looks like you're missing a root certificate.

**Comment by ematejska** [comment]
Thank you for trying out Mojo.  The installation experience has significantly changed and we're closing out all the old issues with the old installer.  To try out our new installation experience using "magic", please see: https://docs.modular.com/mojo/manual/get-started.
