### ISSUE TITLE
[Modular CLI]: 

### ISSUE THREAD

**Issue by duanqixin1** [modularml/mojo#774]
### Issue description

I was setting up Mojo on Windows, following https://developer.modular.com/download.
I have already Installed VS Studio Code, the WSL extension in VS Code and the Mojo extension in VS Code.
I have already installed Ubuntu 22.04 for WSL and I opened it.
In the Ubuntu terminal, I have already installed the Modular CLI.
But when I tried to install the Mojo SDK using command "modular install mojo" in the Ubuntu terminal in WSL, it just printed one line:
"# Found release for https://packages.modular.com/mojo @ 0.2.1, installing to /home/dqx/.modular/pkg/packages.modular.com_mojo"
About five minutes later, it doesn't change.
< img width="853" alt="屏幕截图 2023-09-13 192226" src="https://github.com/modularml/mojo/assets/87155975/951d02df-1271-4258-b61a-16caad7873f1">
When I search https://packages.modular.com/mojo at the Edge browser, it just said, "HTTP ERROR 400"
By the way, I could use Youtube and Twitter normally.
I wonder how can I fix it.
Thank you!

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.
I was setting up Mojo on Windows, following https://developer.modular.com/download.
I have already Installed VS Studio Code, the WSL extension in VS Code and the Mojo extension in VS Code.
I have already installed Ubuntu 22.04 for WSL and I opened it.
In the Ubuntu terminal, I have already installed the Modular CLI.
But when I tried to install the Mojo SDK using command "modular install mojo" in the Ubuntu terminal in WSL, it just printed one line:
"# Found release for https://packages.modular.com/mojo @ 0.2.1, installing to /home/dqx/.modular/pkg/packages.modular.com_mojo"
About five minutes later, it doesn't change.
< img width="853" alt="屏幕截图 2023-09-13 192226" src="https://github.com/modularml/mojo/assets/87155975/951d02df-1271-4258-b61a-16caad7873f1">
When I search https://packages.modular.com/mojo at the Edge browser, it just said, "HTTP ERROR 400"
By the way, I could use Youtube and Twitter normally.
I wonder how can I fix it.
Thank you!

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
- What OS did you install modular CLI on ?
The Modular CLI version is "modular 0.1.4 (6b54d308)".
The OS I install modular CLI on is "Ubuntu 22.04.2 LTS".
```

**Comment by duanqixin1** [comment]
<img width="853" alt="屏幕截图 2023-09-13 192226" src="https://github.com/modularml/mojo/assets/87155975/101be8a2-5fe5-41ee-acbe-940d8b32ff2c">

**Comment by bzcheeseman** [comment]
Yes - we're working on compressing the files (and adding a progress bar) so this should happen less often in the future. Please stay tuned.
