### ISSUE TITLE
[Modular CLI]: 

### ISSUE THREAD

**Issue by DungDeta** [modularml/mojo#775]
### Issue description

When i try to install Mojo from Modular it got stuck at this line : TEST: `mojo test_python.mojo`... OK 
![image](https://github.com/modularml/mojo/assets/127428218/9307a876-8d34-401a-a5fa-76d25360d3a7)
I use Acer Nitro 5 2021 with R5 5600H and windows 10

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
- What OS did you install modular CLI on ?
```

**Comment by abhinav-tyagi03** [comment]
I have got the same problem.
I am trying to install mojo on WSL Ubuntu 22.04.2 LTS
Modular Version :- modular 0.1.4 (6b54d308)
I don't know if this issue is due to my bad college wifi or if mojo requires more than 16GiB of memory.

**Comment by drunkwcodes** [comment]
Duplicate of #538

**Comment by jackos** [comment]
Closing in favor of #538 try the tips here @DungDeta : https://github.com/modularml/mojo/issues/538#issuecomment-1716908244
