### ISSUE TITLE
Self contained binary tarball for local installation.

### ISSUE THREAD

**Issue by keyboard-penman** [modularml/mojo#777]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

I would like for the devs to provide the option of simply downloading the Mojo SDK as a self contained tarball, containing the compiled toolchain.

### What is your motivation for this change?

The current method of downloading and installing the SDK, as of release a few days ago,  via `apt` has failed to work on several (Linux) systems, with no standard solutions in sight, causing poor user experience. This, if anything, hurts the language's adoption, that too for a relatively trivial reason.

Moreover, being able to download the SDK in my prescribed format is the most convenient of all options in general, if for nothing else other than the fact that after the initial download, installation on a system is no longer contingent on internet connectivity. It simplifies the whole thing and is overall, just neater.

**Comment by bzcheeseman** [comment]
Thanks for the feedback, but we currently aren't planning on supporting this option.
