### ISSUE TITLE
[BUG]: sys.param_env.env_get_string doesn't work

### ISSUE THREAD

**Issue by cheburakshu** [modularml/mojo#781]
### Bug description

```
vscode ➜ ~/mojito $ echo $USER
vscode
vscode ➜ ~/mojito $ mojo
Welcome to Mojo! 🔥
Expressions are delimited by a blank line.
Type `:mojo help` for further assistance.
1> import sys
2. sys.param_env.is_defined["USER"]()
3. 
3> 
4> sys.param_env.env_get_string["USER"]()
5. 
[User] error: Expression [1]:6:1: no viable expansions found
fn __lldb_expr__1(inout __mojo_repl_arg: __mojo_repl_context__):
^

Expression [1]:8:28:   call expansion failed - no concrete specializations
    __mojo_repl_expr_impl__(__mojo_repl_arg)
                           ^

Expression [1]:12:1:     no viable expansions found
def __mojo_repl_expr_impl__(inout __mojo_repl_arg: __mojo_repl_context__) -> None:
^

Expression [1]:20:26:       call expansion failed - no concrete specializations
  __mojo_repl_expr_body__()
                         ^

Expression [1]:14:3:         no viable expansions found
  def __mojo_repl_expr_body__() -> None:
  ^

Expression [1]:17:41:           call expansion failed - no concrete specializations
    sys.param_env.env_get_string["USER"]()
                                        ^


expression failed to parse (no further compiler diagnostics)
4> 
```

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ? Dev Container vscode
- Provide version information for Mojo by pasting the output of `mojo -v`

vscode ➜ ~/mojito $ mojo -v
mojo 0.2.1 (64d14e85)
```
- Provide Modular CLI version by pasting the output of `modular -v`

```
vscode ➜ ~/mojito $ modular -v
modular 0.1.4 (6b54d308)
vscode ➜ ~/mojito $ 
```
```
```

**Comment by cheburakshu** [comment]
yes, os.getenv works. If sys.param_env shouldn't be used, better to remove the redundant fn as it doesn't work and causes confusion. If there special cases where sys.param_env is supposed to be used, better to add documentation to that effect.

**Comment by abduld** [comment]
`sys.param_env` is meant to get compile-time parameters. So if you do 

```
from sys.param_env import env_get_int


fn main():
    print(env_get_int["MAGIC_NUMBER"]())
```

Then running

```
mojo -D MAGIC_NUMBER=42 r.mojo
```

would print 42

**Comment by cheburakshu** [comment]
oh nice. this even works as a compile time constant for a parameter. Please add it to the docs (current docs don't say anything about this feature, at least I couldn't locate it), as it can help vectorize many functions if the parameter value is known at compile time and can be passed in instead of being hard coded.


```
from sys.param_env import env_get_int

alias a: Int = env_get_int["MAGIC_NUMBER", 0]()

@parameter
fn foo[num: Int]():
    print(num)

fn main():
    foo[a]()
```

```
mojo -D MAGIC_NUMBER=42 foo.mojo 
42
```
