### ISSUE TITLE
mac intel  cannot recognize 

### ISSUE THREAD

**Issue by mullerhai** [modularml/mojo#792]
### Issue description

(base) Mac-mini:~ zhanghaining$ curl https://get.modular.com |   [redacted]   sh -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3176  100  3176    0     0    973      0  0:00:03  0:00:03 --:--:--   974
Sorry, this system is not recognized. Please visit https://www.modular.com/mojo to learn about supported platforms. You can also build and run a Mojo container by following instructions at https://github.com/modularml/mojo.

### Steps to reproduce

- Add screenshots if possible, to help explain the problem.
- Include anything that might help us debug the issue.

**Comment by robert-j-webb** [comment]
We don't currently have support for mac right now.
