### ISSUE TITLE
[Feature Request] Support iterating variadic types

### ISSUE THREAD

**Issue by scottamain** [modularml/mojo#793]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Although Mojo accepts variadic function arguments, it seems that it cannot iterate on them the way Python does.

For example, here's how Python can iterate a variadic argument:

```
def add(*nums):
    total = 0
    for num in nums:
        total += num
    return total

z = add(1, 2, 3)
print(z)
```
It prints `6`.

But when converted to Mojo:

```
fn add(*nums: Int) -> Int:
    var total: Int = 0
    for num in nums:
        total += num
    return total

let z = add(1, 2, 3)
print(z)
```
It prints:

```
error: Expression [9]:3:16: 'variadic<!kgen.declref<_"$builtin"::_"$int"::_Int>>' does not implement the '__iter__' method
    for num in nums:
               ^
```

### What is your motivation for this change?

Feature parity with Python's features for variadic function arguments.

**Comment by Mogball** [comment]
Thanks for filing! I'll take a look
