### ISSUE TITLE
[Modular CLI]: 

### ISSUE THREAD

**Issue by ramzikhantouchi** [modularml/mojo#800]
### Issue description

when i run modular install mojo. it shows an error 

modular: error: http error: failed to reach URL https://packages.modular.com/mojo/1.root.json with cURL error Couldn't resolve host name - 

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
- What OS did you install modular CLI on ?
```

**Comment by bzcheeseman** [comment]
Can you give the exact shell command you ran?

**Comment by smuniraj2018** [comment]
seems like duplicate of #670 but still waiting to get response for Aman's question

**Comment by jackos** [comment]
Resolved in a prior release
