### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by DerVogel101** [modularml/mojo#808]
### Bug description

I tried running this Code to get the fibonacci sequence and the time it took to calculate it, i tried it in python too and got this output:
218922995834555169026
in mojo i got this output:
-2437933049959450366

### Steps to reproduce

```
from python import Python

def main():
    
    def fibonacci(n):
        var a = 0 
        var b = 1
        for _ in range(n - 2):
            let temp = b
            b = a + b
            a = temp
        return b
    let tim = Python.import_module("time")

    let startzeit = tim.time()
    print(fibonacci(100))
    let endzeit = tim.time()

    print(endzeit - startzeit)
```

### System information

```shell
- Ubuntu 22.04.2 LTS
- mojo 0.2.1 (64d14e85)
- modular 0.1.4 (6b54d308)
```

**Comment by gryznar** [comment]
I am almost sure, that Mojo does not support very long integers as Python does. So you encountered here overflow

**Comment by railswarm** [comment]
As @gryznar stated, you need at least 68 bits to store `218922995834555169026` as unsigned integer, so an overflow occurs. Try to calculate using Python integers:
```mojo
from python import Python

def main():
    
    fn fibonacci(n: Int) raises -> PythonObject:
        let int = Python.import_module("builtins").int

        var a: PythonObject = int(0) 
        var b: PythonObject = int(1)
        for _ in range(n - 2):
            let temp = b
            b = a + b
            a = temp
        return b
    
    let tim = Python.import_module("time")

    let startzeit = tim.time()
    print(fibonacci(100))
    let endzeit = tim.time()

    print(endzeit - startzeit)
```
```bash
$ mojo run ./fib100.mojo
218922995834555169026
0.00010943412780761719
$ mojo run ./fib1000.mojo
26863810024485359386146727202142923967616609318986952340123175997617981700247881689338369654483356564191827856161443356312976673642210350324634850410377680367334151172899169723197082763985615764450078474174626
0.0006704330444335938
```

**Comment by gryznar** [comment]
Downside of this solution is big reduce in term of speed if I am not wrong

**Comment by railswarm** [comment]
Sure. In practice, you won't notice any significant performance overheads until messing with some really heavy job like matrix multiplication, tensors, etc. That's where the `Int` or SIMD `Int64` shines. I think we may need some custom MLIR-based types.

Like this:
```mojo
@register_passable
struct BigInt:
    var value: __mlir_type.si128 # ui128 for BigUInt
    ...
```

Also see #776
