### ISSUE TITLE
[Feature Request]: Testing Support

### ISSUE THREAD

**Issue by MamadouSDiallo** [modularml/mojo#812]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Mojo should add built-in testing capacity. 

Add blocks directly to the modules (files) similar to Rust or Zig or other modern languages. 

Have scrips such as "mojo test", "mojo ./.../..", etc, to run specific modules

Have controls at the block level to run, skip, etc. selected tests

### What is your motivation for this change?

This will tremendously boost the development experience and be on par with the "new" modern compiled languages.

**Comment by River707** [comment]
Thanks for filing this! Testing is definitely something people expect from a modern language, and we're actively looking into what that could look like for mojo.
