### ISSUE TITLE
[BUG]: pandas dataframe error

### ISSUE THREAD

**Issue by sailfish009** [modularml/mojo#815]
### Bug description

A simple example of creating a pandas dataframe throws an error, unlike Python.

### Steps to reproduce

If you uncomment line in the code below, you will get an error. 

```
from python import Python

fn main() raises:
    let pd = Python.import_module("pandas")
    var df = pd.DataFrame([1,2,3])
    df.columns = ['A']
    # df['B'] = [4,5,6]  # error case 1
    print(df)
```

```
from python import Python

fn main() raises:
    let pd = Python.import_module("pandas")
    # let df = pd.DataFrame({ 'A': [1,2,3], 'B': [4,5,6] })  # error case 2
```

```
from python import Python

fn main() raises:
    let pd = Python.import_module("pandas")
    let d = Python.dict()
    d['A']=[1, 2, 3]
    d['B']=[4, 5, 6]
    let df_1 = pd.DataFrame(d.pyObject)
    let df_2 = pd.DataFrame.from_dict(d.pyObject)
    # let df_3 = pd.DataFrame.from_dict(d)  # error case 3
    print(df_1)
    print(df_2)
```

### System information

```shell
- ubuntu 22.04
- latest mojo
- latest modular
```

**Comment by railswarm** [comment]
Hello. The fun part is that you can call dunder method directly and this
```mojo
fn main():
    ...
    df.columns = ['A']
    df.__setitem__('B', [4,5,6])
    ...
```
works like a charm with some strange mutability effect (you can change mutable `var` to immutable `let` for `df`).
```bash
$ mojo run pandas.mojo
pandas.mojo:8:23: warning: 'PythonObject' value is unused
        df.__setitem__('B', [4,5,6])
        ~~~~~~~~~~~~~~^~~~~~~~~~~~~~
        _ =
   A  B
0  1  4
1  2  5
2  3  6
```
You can suppress the warning (`df.__setitem__` returns `None`) using the discard pattern:
```mojo
fn main():
    ...
    _ = df.__setitem__('B', [4,5,6])
    ...
```
Even Python `dict` won't work without this hack:
```mojo
from python import Python

fn main() raises:
    var dict = Python.import_module("builtins").dict # try to change "var" to "let"
    let x = dict()
    x['1'] = 1 # error: expression must be mutable in assignment
    # ^ change this line to "_ = x.__setitem__('1', 1)"
    print(x['1']) # __getitem__ works without hacks
```
So, mutability here is completely broken.

**Comment by Zidane786** [comment]
I am getting an error even when I try to run 

```
from python import Python

fn main():
    try:
        let pd = Python.import_module("pandas")
        var df = pd.DataFrame([1,2,3])
        df.columns = ['A']
        # df['B'] = [4,5,6]  # error case 1
        _ = df.__setitem__('B', [4,5,6])
        print(df)
    except e:
        print(e.value)
```

Error Message:-
```
mojo_pandas.mojo:14:9: warning: 'df' was declared as a 'var' but never mutated, consider switching to a 'let'
        var df = pd.DataFrame([1,2,3])
        ^
An error occurred in Python.
```

I don't know why I get this error I tried the combination recommended by error then also getting an error.

**Comment by Zidane786** [comment]
> I am getting an error even when I try to run
> 
> ```
> from python import Python
> 
> fn main():
>     try:
>         let pd = Python.import_module("pandas")
>         var df = pd.DataFrame([1,2,3])
>         df.columns = ['A']
>         # df['B'] = [4,5,6]  # error case 1
>         _ = df.__setitem__('B', [4,5,6])
>         print(df)
>     except e:
>         print(e.value)
> ```
> 
> Error Message:-
> 
> ```
> mojo_pandas.mojo:14:9: warning: 'df' was declared as a 'var' but never mutated, consider switching to a 'let'
>         var df = pd.DataFrame([1,2,3])
>         ^
> An error occurred in Python.
> ```
> 
> I don't know why I get this error I tried the combination recommended by error then also getting an error.

Its solved there was a problem because I have not install pandas using pip

**Comment by HananyTolba** [comment]
To create a pandas dataframe with mojo, here is a concise and simple implementation: 

```

from python import Python

fn main() raises:
    let pd = Python.import_module("pandas")
    let np = Python.import_module("numpy")
    let size = 10
    let data = np.random.rand(size,3)
    let df =  pd.DataFrame(data, np.arange(size), ['col1', 'col2', 'col3'])
    print(df.head())

```

**Comment by sailfish009** [comment]
> To create a pandas dataframe with mojo, here is a concise and simple implementation:
> 
> ```
> 
> from python import Python
> 
> fn main() raises:
>     let pd = Python.import_module("pandas")
>     let np = Python.import_module("numpy")
>     let size = 10
>     let data = np.random.rand(size,3)
>     let df =  pd.DataFrame(data, np.arange(size), ['col1', 'col2', 'col3'])
>     print(df.head())
> ```

There are many real-world scenarios where you don't want to add columns at creation time.

**Comment by HananyTolba** [comment]
otherwise you could override the column names after creating the dataframe:

```
let data2 = np.random.rand(10,3)
let df2 =  pd.DataFrame(data2)
df2.columns = ['col1', 'col2', 'col3']
print(df2.head(3))
```

**Comment by duwanqiebi** [comment]
When modifying a DataFrame column, I also encountered this error: `expression must be mutable in assignment`. 
Are there any solution?

**Comment by jackos** [comment]
Thanks for the example workarounds @HananyTolba, @sailfish009 please see our rough edges dicts aren't yet supported: https://docs.modular.com/mojo/roadmap.html#small-independent-features
