### ISSUE TITLE
[Modular CLI]: Errors in the docker file

### ISSUE THREAD

**Issue by glebfrank** [modularml/mojo#816]
### Issue description

There are a couple of errors in the docker file provided in this repository at [examples/docker/Dockerfile.mojosdk](https://github.com/modularml/mojo/blob/main/examples/docker/Dockerfile.mojosdk). 

At line 23:

`ARG DEFAUL_TZ=America/Los_Angeles`

`DEFAUL_TZ` is used instead of `DEFAULT_TZ`.

Further, at line 27:

`&& DEBIAN_FRONTEND=noninteractive $DEFAULT_TZ apt-get install -y \ `

`$DEFAULT_TZ` is used on its own in front of the apt-get command. Presumably something like `TZ=$DEFAULT_TZ` was intended.

The two errors almost cancel each other. Because of the first error, `DEFAULT_TZ` is actually unset, and so it doesn't matter that it's used incorrectly. But the ability of setting the time zone through an arg is broken.

Not sure if this is the correct area for this issue, this is the closest one I could find.

### Steps to reproduce

- Download the docker file.
- Run `docker build --build-arg AUTH_KEY=<YOUR_AUTH_KEY> --build-arg DEFAUL_TZ=America/Anchorage --file=Dockerfile.mojosdk .` This uses the variable as specified in the ARG directive at line 23.
- The time zone parameter will have no effect. 
- It will also have no effect if you specify it as DEFAULT_TZ. In this case, you will see the warning message: `[Warning] One or more build-args [DEFAULT_TZ] were not consumed`

### Version Info

```shell
modular 0.1.4 (6b54d308)
```

**Comment by bzcheeseman** [comment]
@jackos do you mind taking a look at this one?

**Comment by dualvtable** [comment]
Oops - I can take this one as I probably made a typo there. I also plan to add some verbiage into the Dockerfile about copyright/license.

**Comment by dualvtable** [comment]
Thanks for reporting this issue. The reference Dockerfile has been updated with some changes.
