### ISSUE TITLE
[BUG]: DynamicVector vector in the loop doesn't call for destructor

### ISSUE THREAD

**Issue by zverianskii** [modularml/mojo#819]
### Bug description

This will lead to a memory usage explosion. Could be solved by adding `vec._del_old()` at the end of each cycle, so looks like the destructor is not called.

```mojo
from utils.vector import DynamicVector

@value
@register_passable("trivial")
struct Point:
    var row: Int

fn main():
  for i in range(1000000):
    var vec = DynamicVector[Point]()
    vec.resize(0)
    for j in range(1000):
      vec.push_back(Point(0))
```

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ? Ubuntu
- Provide version information for Mojo by pasting the output of `mojo -v` mojo 0.2.1 (64d14e85)
- Provide Modular CLI version by pasting the output of `modular -v` modular 0.1.4 (6b54d308)
```

**Comment by willghatch** [comment]
Thanks!  For now, you can work around this with `DynamicVector`'s `_del_old()` method to manually destroy it.

**Comment by JoeLoser** [comment]
Closing this for now as `DynamicVector` is a collection type that destroys its elements automatically in the destructor now as of v0.6.0.  If you still see any issues related to this, please feel free to open another issue.  Thanks!
