### ISSUE TITLE
[Feature Request] modular-cli install mojo progress bar

### ISSUE THREAD

**Issue by Tom-jm03** [modularml/mojo#824]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

I would like to have a progress bar for installing through the modular-cli. While having a very bad internet connection or a slow download, you don't know how much is already downloaded/how much is left.

### What is your motivation for this change?

My motivation for this change is, to know how much is already downloaded.
I was sitting for hours and didn't know how the download was going.

**Comment by AlmirNeeto99** [comment]
They already know mojo installation needs as progress bar.

![image](https://github.com/modularml/mojo/assets/26326407/fbf990b3-525a-405a-a207-5bb52e7732b6)

You can find this information here: https://docs.modular.com/mojo/roadmap.html#mojo-sdk-known-issues

**Comment by Tom-jm03** [comment]
Oh okay. I looked into the issues and didn't found anything about a progress bar.
