### ISSUE TITLE
can't install mojo

### ISSUE THREAD

**Issue by LucasHillebrand** [modularml/mojo#825]
### Issue description

when i try to install it says that there is no package found for my hardware:
![image](https://github.com/modularml/mojo/assets/71591567/503601f1-e8ad-4709-8552-c500c1963eb9)

hardware:
![image](https://github.com/modularml/mojo/assets/71591567/a2f9f1b6-ccef-4a58-9ad2-56994e52f4f2)

### Steps to reproduce

- curl https://get.modular.com | \
  MODULAR_AUTH=[key]\
  sh -
- sudo bash
- modular auth [key] &&
modular install mojo

### Version Info

```shell
- 0.1.4
```

**Comment by AlmirNeeto99** [comment]
Your print looks incomplete.
I can't see the error.

**Comment by LucasHillebrand** [comment]
![image](https://github.com/modularml/mojo/assets/71591567/cd1588f6-b37e-4b25-8d24-b00fc1011686)

**Comment by BoxFishLab** [comment]
![image](https://github.com/modularml/mojo/assets/22937526/833f1490-ade1-4c5d-9e27-78f7d359b8a5)
It seems that the execution succeeded, but the program is no longer executing

**Comment by bzcheeseman** [comment]
This is an issue we've seen with smaller machines in the past. Handing-off to the mojo folks to de-duplicate.

**Comment by walter-erquinigo** [comment]
We should handle timeouts of the REPL better, especially when running the self tests. I'll see what we can do there.

**Comment by walter-erquinigo** [comment]
@River707 , you've added better handling of timeouts and errors already, right?

**Comment by modocache** [comment]
Thanks for the report! We've added many additional improvements here, including better timeouts, and a lot more descriptive errors, so I think we can close this for now. If the issue occurs again please open a new report. We also collect diagnostic info (provided you haven't opted-out), and are fixing installation issues like this one as we see them.
