### ISSUE TITLE
What is the license of Mojo🔥?

### ISSUE THREAD

**Issue by amdjedbens** [modularml/mojo#84]
The fact that the Mojo license has been absent as it seems is really unusual, couldn't the dev team eventually add a license that would be proprietary?

At the time of writing this question, I couldn't find the answer either:
- On this repo https://github.com/modularml/mojo (no 'LICENSE' file)
- In the FAQs, or even on their entire website https://docs.modular.com/mojo/faq.html

**Comment by amdjedbens** [comment]
Thanks, looking forward to reading that.
Personally, I would be careful about giving consideration & investing time in a language in which there isn't a publicly accessible reference implementation.

**Comment by goldiegadde** [comment]
Thanks for the question @amdjedbens, yes @dom96 is right. Mojo is not opensourced yet, see docs.modular.com/mojo/faq for further details. 
Closing this issue now. In the future please use Discussions for such questions.

**Comment by jackos** [comment]
Link to the SDK license here: https://www.modular.com/legal/mojo

**Comment by jackos** [comment]
@arthurevans or @scottamain could we please add a link to the SDK license in the Mojo FAQ, had an additional comment in another ticket from someone that couldn't find it.

**Comment by Sharktheone** [comment]
Maybe it'd make sense to add a `LICENSE` or at leased a `SDK_LICENSE` file to repository

**Comment by jackos** [comment]
Hi @amdjedbens this is now in the Mojo FAQ here: https://docs.modular.com/mojo/faq.html#what-are-the-license-terms-for-the-sdk

And I raised your suggestion @Sharktheone thanks
