### ISSUE TITLE
[BUG]: incorrect installation on my Linux system

### ISSUE THREAD

**Issue by BeeCodeB** [modularml/mojo#845]
### Bug description

https://developer.modular.com/download
Mojo SDK now available!

~$ sudo apt install curl 
~$ keyring_location=/usr/share/keyrings/modular-installer-archive-keyring.gpg && curl -1sLf 'https://dl.modular.com/bBNWiLZX5igwHXeu/installer/gpg.0E4925737A3895AD.key' |  gpg --dearmor >> ${keyring_location} && curl -1sLf 'https://dl.modular.com/bBNWiLZX5igwHXeu/installer/config.deb.txt?distro=debian&codename=wheezy'
~$ modular auth mut_2ffd1529eac24626a2d85004e4867217 && modular install mojo
~$ 

### Steps to reproduce

```
# Found release for https://packages.modular.com/mojo @ 0.2.1, installing to /home/verwalter/.modular/pkg/packages.modular.com_mojo
modular: error: failure detected - please run `modular clean` and try again
==========================
Failure Information:
	- Creating symlink for /home/verwalter/.modular/pkg/packages.modular.com_mojo/lib/liblldb.so.18.0.0git -> /home/verwalter/.modular/pkg/packages.modular.com_mojo/lib/liblldb.so failed: File exists
	- Creating symlink for /home/verwalter/.modular/pkg/packages.modular.com_mojo/lib/libMojoJupyter.so.18git -> /home/verwalter/.modular/pkg/packages.modular.com_mojo/lib/libMojoJupyter.so failed: File exists
	- Creating symlink for /home/verwalter/.modular/pkg/packages.modular.com_mojo/lib/liblldb.so.18.0.0git -> /home/verwalter/.modular/pkg/packages.modular.com_mojo/lib/liblldb.so.18git failed: File exists
	- Creating symlink for /home/verwalter/.modular/pkg/packages.modular.com_mojo/lib/libKGENCompilerRTShared.so.18git -> /home/verwalter/.modular/pkg/packages.modular.com_mojo/lib/libKGENCompilerRTShared.so failed: File exists
	- Creating symlink for /home/verwalter/.modular/pkg/packages.modular.com_mojo/lib/libMojoLLDB.so.18git -> /home/verwalter/.modular/pkg/packages.modular.com_mojo/lib/libMojoLLDB.so failed: File exists
	- Creating symlink for /home/verwalter/.modular/pkg/packages.modular.com_mojo/lib/libLLCLRuntimeGlobals.so.18git -> /home/verwalter/.modular/pkg/packages.modular.com_mojo/lib/libLLCLRuntimeGlobals.so failed: File exists
	- Creating symlink for /home/verwalter/.modular/pkg/packages.modular.com_mojo/lib/libMSupportGlobals.so.18git -> /home/verwalter/.modular/pkg/packages.modular.com_mojo/lib/libMSupportGlobals.so failed: File exists
==========================

```

### System information

```shell
Modular CLI version: modular 0.1.4 (6b54d308)
    System: Ubuntu Version 23.04 (Lunar Lobster) 64-bit Kernel Linux 6.2.0-32-generic x86_64 MATE 1.26.0
    Python: 3.11.4
    gcc: (Ubuntu 12.3.0-1ubuntu1~23.04) 12.3.0
    clang: Ubuntu clang version 15.0.7
```

**Comment by AlmirNeeto99** [comment]
Have you tried `mojo clean` and the trying installing again?

**Comment by AlmirNeeto99** [comment]
Are you inside an environment or are you using plain `bash`?

**Comment by BeeCodeB** [comment]
Thank you for your question; I use a terminal emulator software of my Linux operating system (OS) installed on computer hardware (this is called a computer system, cf. virtual machine, below), that gives me access to a shell software, that is bash in my case, while using my graphical desktop. 

P.S.: Well, the formulation of your question isn't precise enough. Assuming one could use bash be it installed in an OS environment provided by an operating system (OS) on a virtual machine [:virtual environment] or in an environment provided by an operating system (OS) on computer hardware [:computer system], and with or without a graphical interface [:command line interface (cli) environment vs graphical user interface (gui) environment].

**Comment by bzcheeseman** [comment]
This sounds like other python-related issues we're already working on. Please stay tuned, we hope to have these fixed soon.
