### ISSUE TITLE
[Modular CLI]: Why there is no progress bar while installing?

### ISSUE THREAD

**Issue by immmor** [modularml/mojo#846]
### Issue description

Can we add a progress bar while running this command?
`modular install mojo`

### Steps to reproduce

modular install mojo

### Version Info

```shell
mojo 0.2.1
```

**Comment by AlmirNeeto99** [comment]
It's already in the roadmap.

See here: https://docs.modular.com/mojo/roadmap.html#mojo-sdk-known-issues

![image](https://github.com/modularml/mojo/assets/26326407/08c94678-16a2-4be6-bc36-e3ae946e3b14)

**Comment by bzcheeseman** [comment]
We're working on making the install better actively. Please stay tuned!
