### ISSUE TITLE
[BUG]: Python integration

### ISSUE THREAD

**Issue by LuisYordano** [modularml/mojo#847]
### Bug description

I am testing import module numpy in mojo.

I execute the command : **from python import Python** I get the following :

![Error_import_module_python](https://github.com/modularml/mojo/assets/13818395/707f4311-d755-4ca6-90f5-669a01559064)

-----
If I run the following code there is an error:

![Error_python_interop](https://github.com/modularml/mojo/assets/13818395/8f7a3eb2-b1de-49a5-9b2d-4dff6c58a8f0)

Thank you in advance.

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ? Ubuntu 22.04
- Provide version information for Mojo by pasting the output of `mojo -v` : mojo 0.2.1 (64d14e85)

- Provide Modular CLI version by pasting the output of `modular -v` : modular 0.1.4 (6b54d308)
```

**Comment by walter-erquinigo** [comment]
@LuisYordano , top level expression are not supported. So you should create a `fn main()` function and move your code there, except for the `import` of course.

Besides that, the REPL automatically imports the Python module, but your code shouldn't theoretically fail because of that. I'll figure out what we can do there.

**Comment by LuisYordano** [comment]
Hi @walter-erquinigo, I have continued investigating and these are the results:

The command in REPL should be: **from python.python import Python**

![Selection_076](https://github.com/modularml/mojo/assets/13818395/aa69c723-7e23-4101-9149-2a0ca94bce89)

In mojo programs I have three variants, the first two work well and the third fails:

**Variant 1:**
![Selection_077](https://github.com/modularml/mojo/assets/13818395/ee4e6320-bbab-46db-99ff-4ceb59639693)

**Variant 2:**
![Selection_078](https://github.com/modularml/mojo/assets/13818395/6b72e5cc-0df8-4079-9631-f9fbc9405ad6)

**Variant 3:**  I changed from **def** to **fn** in main() - ERROR:
![Selection_079](https://github.com/modularml/mojo/assets/13818395/f83e2324-0aac-4117-a2aa-8f0aa6cf15bc)

Could you give an example of Python integration, importing numpy with a fn main?

**Comment by walter-erquinigo** [comment]
Hi @LuisYordano ,

Thank you for noticing that the import should be done differently. In your REPL expression, you don't need to include the import, as it's done automatically. In fact, your code should just be

```
let np = Python.import_module("numpy") 
```
I have verified that we do

```
from memory.unsafe import Pointer
from python.python import Python
from python.object import PythonObject
```
on behalf of the user for every expression. This is a behavior that only exists in the REPL.

Besides that, your variant 3 code should be

```
from python.python import Python

fn main() raises:
   let np = Python.import_module("numpy") 
   let a = np.array([1, 2, 3])
   print(a)
```

Notice the `raises` keyword, which is used to tell the compiler that you know that this function might raise an exception.

Can we consider this issue closed, then? :)

**Comment by LuisYordano** [comment]
Of course @walter-erquinigo.

**Comment by LuisYordano** [comment]
Thank you!!!
