### ISSUE TITLE
[Docs] Clearer docs on using param_env to set compile-time values

### ISSUE THREAD

**Issue by arthurevans** [modularml/mojo#857]
### Where is the problem?

https://docs.modular.com/mojo/stdlib/sys/param_env.html

### What can we do better?

As described in https://github.com/modularml/mojo/issues/781#issuecomment-1726659113, it's not clear from the API docs how param_env is used. A few extra sentences & a code example here would come in handy.

When we revise the docs on parameterization, we could also add a reference there as well.

**Comment by scottamain** [comment]
Also FYI: https://github.com/modularml/modular/issues/21670

**Comment by arthurevans** [comment]
Yep. We'll do further updates when the APIs are renamed. But for now, addressed this issue in https://github.com/modularml/modular/pull/22066
