### ISSUE TITLE
[Feature Request] Add f-string support

### ISSUE THREAD

**Issue by Kratosix** [modularml/mojo#86]
I seem to not use f-strings in Mojo, for example Here's my code
`let g = 54
print(f'{g}')`

And I seem to be getting this error
 _error: Expression [6]:17:12: expected ')' in call argument list
    print(f'{g}')
           ^_

Is there anyway to fix this issue, thanks for your patience.

**Comment by binarycache** [comment]
None of the python formatting works.

Neither .format nor %

**Comment by Kratosix** [comment]
Ok that's really cool, when will this be allowed to be used. THANKS

**Comment by arthurevans** [comment]
A limited subset of `String.format()` is now supported. It's documented here: https://docs.modular.com/mojo/stdlib/collections/string/format/ and this API doc page will be updated as new support is added.
