### ISSUE TITLE
[BUG]: `Tensor` has no `__mul__` method 🤯

### ISSUE THREAD

**Issue by cheburakshu** [modularml/mojo#864]
### Bug description

Quite astonished that even after extensive blogs and examples of matmul that kind of made the case for Mojo and ModularML creation, tensor multiplication has been left as an exercise for the reader.

Kindly suggest the best algorithm be implemented as a method in the `Tensor` type.

```py

# Tensor multiplication

from tensor import Tensor
from utils.index import Index


var t = Tensor[DType.float32](2, 2)
t[Index(0, 0)] = 0
t[Index(0, 1)] = 1
t[Index(1, 0)] = 2
t[Index(1, 1)] = 3

var t2 = Tensor[DType.float32](2, 2)
t2[Index(0, 0)] = 0
t2[Index(0, 1)] = 1
t2[Index(1, 0)] = 2
t2[Index(1, 1)] = 3

t * t2
```

```
error: Expression [3]:31:7: 'Tensor[f32]' does not implement the '__mul__' method
    t * t2
    ~ ^

expression failed to parse (no further compiler diagnostics)
```

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
Hosted Jupyter notebook
```

**Comment by gabrieldemarmiesse** [comment]
@cheburakshu  it seems that now Tensor supports `__mul__`: https://docs.modular.com/mojo/stdlib/tensor/tensor#__mul__ if this is what you wanted, can you close this issue?

**Comment by cheburakshu** [comment]
ok
