### ISSUE TITLE
[Modular CLI MOJO installation]: 

### ISSUE THREAD

**Issue by Ashishprasa** [modularml/mojo#866]
### Issue description

# When trying to download mojo, the execution is getting stuck when going to this link, and the package is not downloading at all. It's not responding with any response
## https://packages.modular.com/mojo
![welcome-bhai-ye-to-koi-response-hi-nahi-de-raha-hai](https://github.com/modularml/mojo/assets/105356967/625758ec-838a-44fb-bf75-d3e473b48866)

### Steps to reproduce

When trying to download mojo, the execution is getting stuck when going to this link, and the package is not downloading at all. It's not responding any response

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
`latest Version`
- What OS did you install modular CLI on ?
`WSL Ubuntu`
```

**Comment by SimplyYummy** [comment]
Looks similar to https://github.com/modularml/mojo/issues/774 and a few others. 

You can try `modular clean` and then `modular install mojo` again to see if it helps.

**Comment by Ashishprasa** [comment]
Thank you, it is working @SimplyYummy
