### ISSUE TITLE
[BUG]: Let and var are wrong in defining specifications in design semantics

### ISSUE THREAD

**Issue by InfernalAzazel** [modularml/mojo#868]
### Bug description

Below is the official documentation:
let and var declarations
Inside a def in Mojo, you may assign a value to a name and it implicitly creates a function scope variable just like in Python. This provides a very dynamic and low-ceremony way to write code, but it is a challenge for two reasons:

Systems programmers often want to declare that a value is immutable for type-safety and performance.
They may want to get an error if they mistype a variable name in an assignment.
To support this, Mojo provides scoped runtime value declarations: let is immutable, and var is mutable. These values use lexical scoping and support name shadowing:

```python
def your_function(a, b):
    let c = a
    # Uncomment to see an error:
    # c = b  # error: c is immutable

    if c != b:
        let d = b
        print(d)

your_function(2, 3)
```
Description of the recommendation:

Let immutable definition It is more appropriate to use the keyword const, on the contrary, let definition is mutable, so that the meaning is very clear and does not feel weird and awkward.

If you write a mojo after writing js, it's very bad, let is immutable, and conflicts with the inherent philosophy.

-  const is immutable, and let is mutable.

```python
def your_function(a, b):
    const c = a
    # Uncomment to see an error:
    # c = b  # error: c is immutable

    if c != b:
        const d = b
        print(d)

your_function(2, 3)
```

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by SimplyYummy** [comment]
Here is some of the discussions relating to this:
https://github.com/modularml/mojo/issues/280#issuecomment-1566300145
https://github.com/modularml/mojo/discussions/338
https://github.com/modularml/mojo/blob/main/proposals/lifetimes-keyword-renaming.md
