### ISSUE TITLE
[Dev Console]: Cannot import python libraries

### ISSUE THREAD

**Issue by venkateshns** [modularml/mojo#869]
### Issue description

Cannot import python libraries 

![image](https://github.com/modularml/mojo/assets/119554874/61c1d07e-8c56-4216-b3fd-7071f2c2b055)

**Comment by SimplyYummy** [comment]
The issue is that you need to always have a main() function at the moment when using the `modular cli` tool, which is different from the jupyter playground which doesn't require a main function. This will work:

```
fn main() raises:
    from python import Python
    let np = Python.import_module("numpy")
    let a = np.array ([1, 2, 3])
    print(a)
```
