### ISSUE TITLE
[BUG]: mojo: error: Permission denied

### ISSUE THREAD

**Issue by binno22** [modularml/mojo#871]
### Bug description

help, plz

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by ematejska** [comment]
Thanks for filing a bug. If you're still having issues, please open a ticket with the information requested to allow us to help.
