### ISSUE TITLE
[BUG]: Does this count as memory leak?

### ISSUE THREAD

**Issue by cheburakshu** [modularml/mojo#876]
### Bug description

Hosted jupyter notebook:

Here the reference to mutable variable `a`, private to function `f` is returned to the caller. I expected this to fail but it works. I am not using `owned`, `borrowed`, `inout` keywords that are exclusive to fn signature. Please let me know what the lifetime rules are for variable `a`.

```
fn f() -> Pointer[Int]:
    var a: Int = 1
    return Pointer[Int].address_of(a)

var b: Pointer[Int]
b = f()
print(b.load(0))
b.store(0, 2)
print(b.load(0))
```

Output:
```
1
2
```

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by cheburakshu** [comment]
fwiw, rust would treat a similar code as error and not compile due to lifetime issues.

```rust
fn main() {
    let b = f();
    println!("{}", *b);
}

fn f() -> &mut i32 {
    let mut a: i32 = 42;
    return &mut a;
}
```

**Comment by Mogball** [comment]
The `Pointer` type as it is today is unsafe. You'll note that the `Pointer` type is from the `memory.unsafe` module. When Mojo has proper lifetime support, returning a reference to a local variable will be invalid, but using an unsafe pointer is still allowed.
