### ISSUE TITLE
[Docs] Typo in HeapArray example text?

### ISSUE THREAD

**Issue by meersuri** [modularml/mojo#878]
### Where is the problem?

https://docs.modular.com/mojo/programming-manual.html#the-__copyinit__-__moveinit__-and-__takeinit__-special-methods

### What can we do better?

Refer to the sentence "If you are curious how `existing` can be passed into the `__copyinit__` method without itself creating a copy, check out the section on [Borrowed arguments](https://docs.modular.com/mojo/programming-manual.html#immutable-arguments-borrowed) below"

This sentence seems to refer to the HeapArray example where `__copyinit__` is defined and takes a param called `other`, but the text mentions `existing`, which is not referred to anywhere before this point. It seems that `existing` should be replaced with `other`

**Comment by scottamain** [comment]
Thank you! This will be fixed in the next update.
