### ISSUE TITLE
[Docs] Typo about surprising results from reference sharing?

### ISSUE THREAD

**Issue by meersuri** [modularml/mojo#879]
### Where is the problem?

https://docs.modular.com/mojo/programming-manual.html#why-argument-conventions-are-important

### What can we do better?

The second paragraph starts with "This Python approach provides a comfortable programming model for most people, but it requires all values to be heap-allocated (and results are occasionally surprising results due to reference sharing)"

The part in the parens mentions 'results' twice which makes it sound odd. Omitting the second 'results' would make it sound natural IMO

**Comment by scottamain** [comment]
Thank you! This will be fixed in the next update.
