### ISSUE TITLE
[Feature Request] Compile time check for duplicate files names with different extensions.

### ISSUE THREAD

**Issue by yail259** [modularml/mojo#885]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Currently it is allowed to have two files hello.mojo and hello.🔥 in the same folder. These are treated as different mojo files by mojo. Add a check to discourage having this sort of duplication in the same folder. This then allows for automatic conversion from  hello.mojo to hello.🔥 or vice versa.

### What is your motivation for this change?

Having two files with the same name is a bad practice that should be discouraged. The 🔥 extension is the best feature of Mojo but is very difficult to type in the terminal.

**Comment by Mogball** [comment]
This should already be fixed! Having two files with the same name but different extension will result in an error. I think it might have fallen into the next release.
