### ISSUE TITLE
[BUG]: creating Tensor in a function raises 'free(): invalid pointer'

### ISSUE THREAD

**Issue by mikowals** [modularml/mojo#891]
### Bug description

Creating a Tensor from the data of another Tensor inside of a function raises an error.  The error is usually 'free() invalid pointer' but is sometimes 'munmap_chunk(): invalid pointer'.   Running the code about 5 times is probably enough times to see both errors get reported.

### Steps to reproduce

In the Mojo playground this code:
```
from tensor import Tensor,TensorShape
from random import rand

fn foo(a: Tensor[DType.float32]):
    print("foo")

fn forward(weights: Tensor[DType.float32]):
    let a = Tensor[DType.float32](weights.data().offset(5), TensorShape(5))
    foo(a)
    print(1)
    
let x = rand[DType.float32](TensorShape(2, 5))

forward(x)
```

Gives the following output
```
foo
free(): invalid pointer
error: Execution was interrupted, reason: signal SIGABRT.
The process has been left at the point where it was interrupted, use "thread return -x" to return to the state before expression evaluation.
```
So the function `foo` completes successfully but the error throws before the next line executes.

The code executes fine if I do the same steps without putting them in the  `forward()`  function.  Like this:
```
from tensor import Tensor,TensorShape
from random import rand

fn foo(a: Tensor[DType.float32]):
    print("foo")
    
let x = rand[DType.float32](TensorShape(2, 5))

let a = Tensor[DType.float32](x.data().offset(5), TensorShape(5))
foo(a)
print(1)
```

output will be:
```
foo
1
```

This is a reproduction of an error found trying to move [llama2.mojo from its own Matrix struct to Tensor](https://github.com/tairov/llama2.mojo/pull/20).

### System information

```shell
The reproduction is in the Mojo playground.
```

**Comment by tairov** [comment]
Thanks @mikowals for raising this. 
Just for consistency, did you try to reproduce this bug via latest mojo compiler ?

**Comment by cheburakshu** [comment]
The reason being, Mojo requires the value to be mutable to get its address, I don't know why (not sure if it is documented somewhere).

```
fn get_addr(val: Int):
    let c: Pointer[Int]
    c = Pointer[Int].address_of(val)


get_addr(1)
```

Output:

```
error: Expression [4]:3:32: invalid call to 'address_of': argument #0 must be mutable in order to pass as a by-ref argument
    c = Pointer[Int].address_of(val)
        ~~~~~~~~~~~~~~~~~~~~~~~^~~~~

Expression [0]:1:1: function declared here
var __lldb_repl_python__ = Python()
^

expression failed to parse (no further compiler diagnostics)
```

If I make it mutable by adding `owned` modifier, it will work:

```
fn get_addr(owned val: Int):
    let c: Pointer[Int]
    c = Pointer[Int].address_of(val)


get_addr(1)
```

**Comment by Mogball** [comment]
The doc for the `Tensor` type constructor being called states

```
Initializes a Tensor from the pointer and shape provided. The caller
relinquishes the ownership of the pointer being passed in.
```

The line

```python
fn forward(weights: Tensor[DType.float32]):
    let a = Tensor[DType.float32](weights.data().offset(5), TensorShape(5))
```

Is causing an ownership conflict because both `weights` and `a` think they own the underlying memory. When `a` is destructed, `free` is called on the pointer, which since it's offset by 5 from the base pointer, confuses the memory allocator.

**Comment by cheburakshu** [comment]
So, what is mojo doing when the signature is changed to `owned`? Is it relinquishing an invalid reference? https://github.com/modularml/mojo/issues/891#issuecomment-1731594442

**Comment by Mogball** [comment]
The call to `forward` is creating a copy of the tensor value, including the underlying memory. That copy is owned by the function `forward`
