### ISSUE TITLE
[Feature Request] typeof

### ISSUE THREAD

**Issue by Klebestreifen** [modularml/mojo#894]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Implement a way to get the type of a variable. Either as a string or even to pass it as a generic argument.

### What is your motivation for this change?

I am in the process of learning the language. At the moment I was trying to understand the type system in more detail, so I wanted to get the type name of various variables. Unfortunately I have not found a possibility. Below is an example how I imagined it. I hope I didn't miss anything in the documentation.

### Any other details?

```mojo
fn main():
    let test = [1, 2, 3]
    print("The type of", test, "is:", typeof(test))  # is ListLiteral[Int, Int, Int]
```

**Comment by gryznar** [comment]
Maybe it will be better to just use `type` as in Python? Or `type_of` if it would be a problem with compatibility?

**Comment by willghatch** [comment]
For learning, another feature that you can use is the LSP (Language Server Protocol) server, eg. through the VSCode extension.  It can show you the types of variables.  Eg. in VSCode I think you will see it if you hover your mouse cursor over an identifier.

**Comment by YichengDWu** [comment]
> meaning they must define a __type__ method that returns 
It should be __class__ instead. Let's be consistent with Python.

**Comment by YichengDWu** [comment]
`identity` is confusing as there is an `id` function in Python.

There's already `__type_of` in mojo btw.  Adding `__name__` seems to be a better fit for this issue.

**Comment by lattner** [comment]
name is tracked in https://github.com/modularml/mojo/issues/187 and we have `__type_of(x)` already, so closing this.
