### ISSUE TITLE
[BUG]: Dangling pointer

### ISSUE THREAD

**Issue by cheburakshu** [modularml/mojo#895]
### Bug description

Hosted juypter instance:

Pointer `c` should become invalid when the underlying pointer `b`'s ownership is transferred. I verified `b` is invalidated after transfer but not `c`.

```py
fn transfer(owned ptr: Pointer[Int]):
    ...


fn test():
    var b: Pointer[Int]
    let c: Pointer[Pointer[Int]]
    var a: Int = 1
    b = Pointer[Int].address_of(a)
    c = Pointer[Pointer[Int]].address_of(b)
    
    # c is a pointer to b
    print('c before transfer = ', c.load(0).load(0))

    transfer(b^)

    # both c and b should be invalid here
    print('c after  transfer = ', c.load(0).load(0))

test()
```

```
c before transfer =  1
c after  transfer =  1
```

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by Mogball** [comment]
`Pointer` is unsafe at the moment. You will notice that it is from the module `memory.unsafe.Pointer`. Mojo doesn't have more sophisticated lifetime support at the moment.

**Comment by cheburakshu** [comment]
sounds good. I found this documented 👍 
https://docs.modular.com/mojo/roadmap.html#ownership-and-lifetimes
