### ISSUE TITLE
[Docs] Typo and readability fix

### ISSUE THREAD

**Issue by jmssmth** [modularml/mojo#897]
### Where is the problem?

https://docs.modular.com/mojo/manual/basics/#argument-mutability-and-ownership

### What can we do better?

In the linked section, first paragraph, the second sentence reads:

> So the following is a quick introduction to you can share references to values through function arguments.

I believe it should be updated to read:

> The following is a quick introduction so you can share references to values through function arguments.

**Comment by scottamain** [comment]
Thank you! This will be improved in the next update.
