### ISSUE TITLE
[BUG]: mojo build produces dynamically linked binary

### ISSUE THREAD

**Issue by adaszko** [modularml/mojo#898]
### Bug description

Hi 👋

The docs say the output binary should be [statically linked](https://docs.modular.com/mojo/manual/get-started/hello-world.html#build-an-executable-binary).  Yet, `mojo build hello.mojo` produces a dynamically linked one.

### Steps to reproduce

```
$ cat hello.mojo
fn main():
   print("Hello, world!")
```

```
$ mojo build hello.mojo
```

```
root@ubuntu2204:/home/vagrant# file hello
hello: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=9803aa2e90c14186546f5c1226d855b490404d90, for GNU/Linux 3.2.0, not stripped
```

```
$ ldd hello
        linux-vdso.so.1 (0x00007ffd90fe1000)
        libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007efcabda0000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007efcabb74000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007efcaba8d000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007efcaba6d000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007efcab845000)
        /lib64/ld-linux-x86-64.so.2 (0x00007efcabde1000)
```

### System information

```shell
$ uname -a
Linux ubuntu2204.localdomain 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

```
root@ubuntu2204:/home/vagrant# mojo --version
mojo 0.3.0 (f64f9601)
```

**Comment by lattner** [comment]
@scottamain @arthurevans  this is correct, we should change this to say "Create a statically compiled binary" instead of "statically-linked"

**Comment by lattner** [comment]
We do statically link together all the mojo code, but that's not really the nuance we're going for.  We can eventually investigate a `clang -static` mode in the future if there is demand, but until then we should be precise in terminology.

**Comment by adaszko** [comment]
I see, thank you for clarifying!  I'm leaving the issue to be closed once the documentation is updated.

**Comment by zscgo** [comment]
Hope Static Linking, Doesn't depend on other filie at runtime.
