### ISSUE TITLE
[BUG]: StaticTuple gets initialized to random values

### ISSUE THREAD

**Issue by cheburakshu** [modularml/mojo#899]
### Bug description

Hosted jupyter env:

Static Tuple gets initialized to random values whereas simd works right.
Also, notice the inconsistency in function signature when representing the same data (Array of 4 numbers) using different data types, `[count, type]` vs `[type, count]`, will be nice if they can share a similar signature.

```py
from utils.static_tuple import StaticTuple
var a: StaticTuple[4, Int] = StaticTuple[4, Int]()
a[0] = 1
print(a[0], a[1], a[2], a[3])

var b: SIMD[DType.int32, 4] = SIMD[DType.int32, 4]()
b[0] = 1
print(b[0], b[1], b[2], b[3])
```

Output:

```py
1 140289346657552 8295742030185001760 7017568532949067120
1 0 0 0
```

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by JoeLoser** [comment]
Right now, this is "working as intended" since the constructor for `StaticTuple` explicitly states it constructs an empty (undefined) tuple.  If you wish to initialize the `StaticTuple` with some default values, look at the other two constructors.  For example,

```
from utils.static_tuple import StaticTuple

fn main():
    var a: StaticTuple[4, Int] = StaticTuple[4, Int](7, 7, 7, 7) # Initialize the `StaticTuple` all with 7s
    print(a[0], a[1], a[2], a[3]) # verify all 7s in there
    a[0] = 42 # update just one element index
    print(a[0], a[1], a[2], a[3])
    a[2] = 23 # update a different element index
    print(a[0], a[1], a[2], a[3])
```

I agree this is perhaps "surprising" behavior, but we have many types right now in the stdlib with constructors who don't default value initialize their elements.  In other words, we form a clear distinction between "constructed, but uninitialized types" and "constructed _and initialized_ types".  FYI @abduld @ConnorGray as this relates back to a conversation we had last week.

**Comment by gryznar** [comment]
@JoeLoser how about difference in position of arguments?
![image](https://github.com/modularml/mojo/assets/90425096/5a7a9c7e-5486-425f-8cc6-246b45c4ef5e)
This can be easily fixed and will increase consistency

**Comment by JoeLoser** [comment]
> @JoeLoser how about difference in position of arguments? ![image](https://private-user-images.githubusercontent.com/90425096/291724303-5a7a9c7e-5486-425f-8cc6-246b45c4ef5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMjUyNjIsIm5iZiI6MTcwMzAyNDk2MiwicGF0aCI6Ii85MDQyNTA5Ni8yOTE3MjQzMDMtNWE3YTljN2UtNTQ4Ni00MjVmLThjYzYtMjQ2YjQ1YzRlZjVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDIyMjkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmOWY5OTQ4YzAzNDI5NzdkZjA2NjlhNmVhYTEyNmYzZTUwYzgxMDk4YTkyMjZhNThlZjkwODZhNTAwNWJkYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8mXbQ0Ai1d4RtjuqtGB7m4EX0xyJL2eqwSYwR6Tx5Hg) This can be easily fixed and will increase consistency

I do agree with that - in general, we want consistency, and types should be before sizes in this case.  I opened https://github.com/modularml/mojo/issues/1521 to reflect that request.
