### ISSUE TITLE
Hey everyone 👋,

### ISSUE THREAD

**Issue by ShayanKml** [modularml/mojo#903]
Hey everyone 👋,

We are very excited to [announce that Mojo](https://www.modular.com/blog/mojo-its-finally-here)🔥 is now available for [download](https://developer.modular.com/signup) locally to your machine! ❤️‍🔥🚀

Beyond a compiler, the Mojo SDK includes **a full set of developer and IDE tools 🛠 that make it easy to build and iterate on Mojo applications.** It is available on Linux/X86 today and we will be adding Mac and Windows support (and many other features) in the weeks ahead.

Get started now on [www.modular.com](http://www.modular.com), download our [VS code extension](https://marketplace.visualstudio.com/items?itemName=modular-mojotools.vscode-mojo), and see our [Mojo examples in Github](https://github.com/modularml/mojo/tree/main/examples) and [changelog](https://docs.modular.com/mojo/changelog.html#v0.2.1-2023-09-07) for additional details! 

**Let’s build the future together!🔥**

_Originally posted by @goldiegadde in https://github.com/modularml/mojo/discussions/568_

**Comment by cversek** [comment]
@ShayanKml 
I don't speak for Modular, but from a  community perspective it is considered abusive to raise an issue to just to say hello.  This is not a discord chat or even a forum.  You should only be posting information about any bugs or other problems with the project you may have found here and following the provided templates, e.g.:  
https://github.com/modularml/mojo/tree/main/.github/ISSUE_TEMPLATE

The number of open and closed issues is a measure of developer responsiveness, project quality, and stability... so next time please think before you click comment.

**Comment by ShayanKml** [comment]
> @ShayanKml I don't speak for Modular, but from a community perspective it is considered abusive to raise an issue just to say hello. This is not a discord chat or even a forum. You should only be posting information about any bugs or other problems with the project you may have found here and following the provided templates, e.g.: https://github.com/modularml/mojo/tree/main/.github/ISSUE_TEMPLATE
> 
> The number of open and closed issues is a measure of developer responsiveness, project quality, and stability... so next time please think before you click comment.

That was an unwanted mistake, and I cannot delete my comment!

**Comment by cversek** [comment]
No problem,  please come back when you do find a bug... There are quite a few left 😉
