### ISSUE TITLE
[BUG]: Mojo 🔥 VSCode extension v0.3.0 is reporting incorect issues and eats loads of RAM

### ISSUE THREAD

**Issue by gujuriu** [modularml/mojo#904]
### Bug description

Since I've upgraded to mojo v0.3.0 (SDK) and VSCode extension with the same version, some errors are sowing up (in problems tab) and syntax is highlighted with red on some of the the code on every notebook from this repo (I did `git pull`, I'm up to date with latest changes and I did not modified any line of code in any .ipynb), here are some issues, usually call to functions or struct init, e.g.:
- in file `mojo/examples/notebooks/BoolMLIR.ipynb` on the cell with `let b = OurBool()` (just below the cell with `struct OurBool:` which has `fn __init__(inout self):` I'm getting this error highlighted by Mojo 🔥 VSCode extension v0.3.0 `'OurBool' does not implement any '__init__' methods in 'let' initializer mojo`
- in file `mojo/examples/notebooks/Matmul.ipynb` on 3rd cell with code `python_gflops = benchmark_matmul_python(128, 128, 128).to_float64()` I'm getting this error `use of unknown declaration 'benchmark_matmul_python' mojo`, same even for functions defined with fn, even if you run the cells... the error does not disappear

None of the .mojo or .🔥 files from examples folder have this issue, this happens only in .ipynb files.

Also the more severe part for me is the following:
In my Ubuntu from WSL where I have Modular and Mojo installed, with just a terminal open and htop will show memory usage ~500 - 520M, additionally, if I open VSCode (with no tabs open), memory usage is around ~760M

If I just open "mojo/examples/notebooks/Matmul.ipynb" from this repo, memory usage jumps from ~760 to ~990G (when Mojo extension for VSCode is v0.2.1) and 2.41G if Mojo extension for VSCode is v0.3.0, on problems tab I can see 4234 problems on current open file

If I try to run a cell (using Mojo kernel) that involves code (e.g. not the 1st cell with %%python, I'll run the one with imports, 4th one with code), (when Mojo extension for VSCode is v0.2.1 cell will run in <1 sec. and mem usage will go up to ~1.07G), if Mojo extension for VSCode is v0.3.0, CPU usage pegs at ~95% or more for few seconds and memory usage is now 6.84G, cell execution is ~7.4 sec. 

If I run the same cell again (the one with imports), (will execute quick and mem usage will go up by 0.01G when Mojo extension for VSCode is v0.2.1), if Mojo extension for VSCode is v0.3.0, cell will execute in ~7 sec. and memory usage is now at 6.83G

If I restart the kernel of this Matmul.ipynb, memory usage drops at ~6.72G

If I try to run most of the cells from this notebook, by the end of it I'll run out of memory (>15.7 GB of RAM will be used).

### Steps to reproduce

Steps to reproduce the issue, clone this repo, open VSCode, install latest (currently v0.3.0) Mojo 🔥 VSCode extension in VSCode, open `mojo/examples/notebooks/HelloMojo.ipynb` from the folder/repo that you've just cloned, open problems tab (menu View -> Problems)
Expected: to see 0 problems
Actual: there are 74 problems for this files
If I switch to Mojo 🔥 VSCode extension v0.2.1 I have 0 problems on any .ipnyb files

- Visual Studio Code:
Version: 1.82.2 (system setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

* the following VSCode extensions are installed and enabled in WSL:
  + Python Extension Pack v1.7.0 - which is a bundle of 7 extensions:
	- autoDocstring - Python Docstring Generator v0.6.1
	- Python v2023.16.0
	- Jinja v0.0.8
	- Django v1.13.0
	- IntelliCode v1.2.30
	- Python Indent v1.18.0
	- Python Environment Manager v1.2.4
  + Jupyter v2023.8.1002501831 - which is a bundle of 4 extensions:
	- Jupyter Keymap v1.1.2
	- Jupyter Notebook Renderers v1.0.17
	- Jupyter Slide Show v0.1.5
	- Jupyter Cell Tags v0.1.8
  + IntelliCode API Usage Examples v0.2.8
  + Pylance v2023.9.20
  + Git Graph v1.30.0
  + WSL v0.81.4
  + Error Lens v3.13.0
  + Mojo 🔥 v0.2.1 (or v0.3.0)

![image](https://github.com/modularml/mojo/assets/46481465/0f88fc97-74af-4727-8b46-7f51f71bf4e1)

### System information

```shell
- OS "Ubuntu 22.04.2 LTS" installed in Windows 10 x64 via WSL2
- mojo 0.3.0 (f64f9601)
- modular 0.1.4 (6b54d308)
```

**Comment by River707** [comment]
Thank you for the really detailed issue report! There are two big issues here:

* Notebook support in the LSP is something that we're still working out. The 0.3 release supported a small set of scenarios, but the next release should fix a lot of the issues you see here.

* The mojo compiler can be a bit too anxious to use cpu/memory, which makes the LSP over-consume resources. We'll be digging into this over the next few releases, thanks for reporting it!

**Comment by River707** [comment]
This one should be resolved now!
