### ISSUE TITLE
[BUG]: FPUtils.pack

### ISSUE THREAD

**Issue by jiahzhang** [modularml/mojo#908]
### Bug description

I'm a newbie, so not sure if I'm doing this correctly. I'm trying to generate FP64 numbers with something like this
```
fn gen_good_number() -> Float64:
    let upper_mantissa = (1 << FPUtils.mantissa_width[DType.float64]()) - 1
    let lower_mantissa = 1
    let mantissa = random.random_ui64(lower_mantissa, upper_mantissa)
    let upper_exponent = (1 << FPUtils.exponent_width[DType.float64]()) - 2
    let lower_exponent = 0
    let exponent = random.random_ui64(lower_exponent, upper_exponent)
    
    let number: Float64 = FPUtils.pack[DType.float64](False, exponent.to_int(), mantissa.to_int())
    return number
```

For some reason the only, number I get back is 0.0. Am I using `pack` correctly?

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

see above

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`

Mojo Playground (I assume latest release?)
```

**Comment by willghatch** [comment]
This is fixed, and the fix will be included in a future release.  However, we might also make the FPUtils struct private, it seems it wasn't really intended to be public.

**Comment by jiahzhang** [comment]
I guess it's up to you guys since I'm not a developer :smile:. I find FPUtils to be pretty useful for casting between integer and float while working with underlying bits. The whole "examining mantissa/exponent" is useful as well.
