### ISSUE TITLE
[Docs] Grammar bug

### ISSUE THREAD

**Issue by meersuri** [modularml/mojo#909]
### Where is the problem?

https://docs.modular.com/mojo/programming-manual.html#register_passable-struct-decorator

### What can we do better?

Second half of the following sentence is in singular form instead of plural - 

"The \_\_init__ and \_\_copyinit__ methods of this type are implicitly static (like \_\_new__ in Python) and returns its result by-value instead of taking inout self."

Could be changed to -

"The \_\_init__ and \_\_copyinit__ methods of this type are implicitly static (like \_\_new__ in Python) and return their results by-value instead of taking inout self."

**Comment by iamtimdavis** [comment]
Thanks for the report

@scottamain @arthurevans

**Comment by jackos** [comment]
Fixed in latest release thanks
