### ISSUE TITLE
[Docs] training a model 

### ISSUE THREAD

**Issue by bitdom8** [modularml/mojo#914]
### Where is the problem?

can't find a train model code

### What can we do better?

Could you please provide a simple code for training a model with cehckpoints?

**Comment by jackos** [comment]
Hi @bitdom8 this isn't available right now, the AI Engine is focused on inference, and to do training in Mojo you'll have to start from a very low level, you can see some examples of this here: https://github.com/mojicians/awesome-mojo#ai

**Comment by scottamain** [comment]
@bitdom8, in addition to what @jackos said, I just want to be sure you understand that this GitHub repo and issue tracker is about the Mojo programming language, which is not a machine learning framework, so there are no plans to provide this sort of feature. The Modular AI Engine is not publicly available yet, and as Jack said, it currently is for inference only. You might find this blog post helpful: https://www.modular.com/blog/whats-the-difference-between-the-ai-engine-and-mojo

**Comment by bitdom8** [comment]
Hi @scottamain so we still use Python Pytorch for training purposes then export it to use with mojo lang? By machine learning framework, did you also include deep learning?

**Comment by bitdom8** [comment]
Ach ok, you refer Modular AI Engine  for deep learning and machine learning framework. Thanks @scottamain
