### ISSUE TITLE
[Docs] Make it easier to identify private packages/modules 

### ISSUE THREAD

**Issue by tic-top** [modularml/mojo#915]
### Where is the problem?

runtime libray document 

### What can we do better?

I want to know what's inside the runtime.llcl like is there a num_thread() function to get the thread number, and how to set runtime

**Comment by jackos** [comment]
Hi @tic-top the lower level parts of `runtime.llcl` are currently in flux and so aren't quite ready for documentation, once it stabilizes we'll release documentation and tutorials on how to use it. Leaving this open until then :)

**Comment by Yelinz** [comment]
Maybe add just a little note somewhere in the official docs, that it isnt ready yet, I spent quite a while trying to figure this out.

**Comment by scottamain** [comment]
Thanks for the feedback! We agree that the usage/availability of some APIs in the standard library is confusing, so we're going to improve this by making "private" modules more identifiable and include a notice in each module description to emphasize that they are not intended for public use (although you may still access them, we won't necessarily document them).

**Comment by scottamain** [comment]
I'm pretty sure we solved this a while ago. Please reopen if you still see issues.
