### ISSUE TITLE
[BUG]: Print statement doesn't work on owned variables

### ISSUE THREAD

**Issue by aymansyam** [modularml/mojo#918]
### Bug description

This works:
```
fn add(owned x: Int, inout y: Int) -> Int:
    x += 1
    return x + y

def main():
    let a = 1
    var b = 2
    print(a)
    print(add(a, b))
```
    
Output:
```
1
4
```
    
But add a print statement at the bottom and it crashes::
```
def main():
    let a = 1
    var b = 2
    print(a)
    print(add(a, b))
    print(a)
```

```
error: use of uninitialized value 'a'
    print(a)
         ^
/home/ayman/mojo_test/hello.mojo:6:5: note: 'a' declared here
    let a = 1
    ^
mojo: error: failed to run the pass manager
```

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
Windows
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.3.0 (f64f9601)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.1.4 (6b54d308)
```

**Comment by gabrieldemarmiesse** [comment]
Since the value `a` is owned by the function `add`, `main` doesn't own `a` it after the call to `add`, thus the compiler doestroys is following the ASAP policy. See the relevant section in the documentation: https://docs.modular.com/mojo/programming-manual.html#transfer-arguments-owned-and 

See the example with the description:

> Notice that if you uncomment the second call to use_ptr(), you get an error because the p value has been transferred to the take_ptr() function and, thus, the p value is destroyed.

Which is very very close to your bug report. I'm surprised that the compiler doesn't force you to write `print(add(a^, b))` instead of `print(add(a, b))` though.

**Comment by aymansyam** [comment]
Okay that makes sense.. I did not realize that taking ownership means the variable is completely destroyed. I have to be very careful so that people don't steal my variables now! :D

**Comment by gabrieldemarmiesse** [comment]
When you want to use the variable afterwards, you should copy your variable. You can keep one variable and give the other to the function add.

**Comment by ematejska** [comment]
Should there be a compiler error added?

**Comment by Mogball** [comment]
Thanks for reporting this! Closing this as a dup of [#747](https://github.com/modularml/mojo/issues/747)

**Comment by gabrieldemarmiesse** [comment]
Hooo I see, I was wrong, sorry for that @aymansyam
