### ISSUE TITLE
[BUG] Building a file without `main` results in confusing error message

### ISSUE THREAD

**Issue by AnuAnu22** [modularml/mojo#921]
### Bug description

abhik@abhik-Destop:~/Desktop$ mojo Hello.mojo
mojo: error: module does not `@export` any symbols; nothing to codegen
![Screenshot from 2023-09-25 08-29-47](https://github.com/modularml/mojo/assets/129385032/09d0c011-32ab-443f-a148-fb98e4911f48)

### Steps to reproduce

-Run the program in Ubuntu 22.04 LTS
-Run it in VScode
![Screenshot from 2023-09-25 08-29-47](https://github.com/modularml/mojo/assets/129385032/57195872-3601-437e-803a-e9945a1bad59)

### System information

```shell
- Ubuntu 22.04 LTS
- mojo 0.3.0
- modular 0.1.4 (6b54d308)
```

**Comment by Mogball** [comment]
Hey @AnuAnu22 , thanks for filing an issue! This is actually intended behaviour -- your file doesn't define a `main` function, so the compiler doesn't know what code to execute. We should improve the error message. cc @modocache @River707

**Comment by willghatch** [comment]
This error message has been improved, and will be in the next release.
