### ISSUE TITLE
[Feature Request] Support Mojo for ARM/Nvidia Jetson Platforms

### ISSUE THREAD

**Issue by sundar-subramaniyan** [modularml/mojo#923]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

I'd like to have Mojo supported on Nvidia Jetson Platforms. I am not sure if AARCH64 (ARMv8) is supported already and perhaps the target is just not recognized by modular upon trying to install mojo.

On the Nvidia Jetson AGX Xavier Platform running Ubuntu 20.04, modular doesn't support installing Mojo.
It says the following:

```
$ modular install mojo
modular: error: no packages found for the current target hardware - please run `modular host-info` and file a ticket at https://github.com/modularml/mojo with your hardware information
```

The following is the host information I got by running "modular host-info".

 ```
 Host Information
 ================

 Target Triple: aarch64-unknown-linux
 CPU: carmel
 CPU Features: aes, crc, crypto, fp-armv8, fullfp16, lse, neon, ras, rdm, sha2
```

### What is your motivation for this change?

To get mojo running on ARM based platforms such as Nvidia Jetson, etc. 

### Any other details?

As of now, this is all I have.

**Comment by jbritton-iti** [comment]
I would like to suggest an option to list supported target triples.

**Comment by adnanwahab** [comment]
+1 - would heavily use this on multiple jetsons.

**Comment by bluevisor** [comment]
"modular install max" seems to work, as of today.

**Comment by walter-erquinigo** [comment]
Thank you for reporting this. I'm closing this for now. Eventually we'll include other OS - architectures.
