### ISSUE TITLE
[Modular CLI]: Unrecognized system

### ISSUE THREAD

**Issue by Efendo** [modularml/mojo#924]
### Issue description

i tried to install the modular CLI (curl https://get.modular.com | \
  MODULAR_AUTH=[that number] \
  sh -)

but i got:
Sorry, this system is not recognized. Please visit https://www.modular.com/mojo to learn about supported platforms. You can also build and run a Mojo container by following instructions at https://github.com/modularml/mojo.

### Steps to reproduce

run that command to install the CLI on x86-64 mac mini

### Version Info

```shell
- I dont have the CLI (because of the error)
- i tried to install it on x86-64 Mac Mini (end of 2014 model)
```

**Comment by jackos** [comment]
Hi @Efendo macOS is not yet supported, you can install it into a docker container, example here: https://github.com/modularml/mojo/blob/main/examples/docker/Dockerfile.mojosdk

closing in favor of #510
