### ISSUE TITLE
[BUG]: unable to locate module 'TargetInfo'

### ISSUE THREAD

**Issue by changhui-tech** [modularml/mojo#925]
### Bug description

Tried:
from TargetInfo import simdbitwidth
print(simdbitwidth())

But get error:

error: Expression [1]:1:6: unable to locate module 'TargetInfo'
from TargetInfo import simdbitwidth
     ^

expression failed to parse (no further compiler diagnostics)

### Steps to reproduce

code in both VSCode and Playground shows the error above:

from TargetInfo import simdbitwidth
print(simdbitwidth())

### System information

```shell
OS: WSL2 Ubuntu 22.04.2 LTS
mojo 0.3.0 (f64f9601)
modular 0.1.4 (6b54d308)
```

**Comment by Mogball** [comment]
@changhui-tech thanks for filing! The module is now called `sys.info`. Please use `from sys.info import simdbitwidth`,
