### ISSUE TITLE
[BUG]: raises returns a StringRef

### ISSUE THREAD

**Issue by igorgue** [modularml/mojo#926]
### Bug description

When you have a function that returns a `StringRef` and it raises an error the function will return the value of that error.

Is this expected behavior?

### Steps to reproduce

```py
fn test() raises -> StringRef:
    raise Error("Test")


fn main() raises:
    let res = test()

    print(res)  # prints "Test"
```

### System information

```shell
- Pop!_OS 22.04 LTS based on Ubuntu 22.04 LTS
- mojo 0.3.0 (f64f9601)
- modular 0.1.4 (6b54d308)
```

**Comment by Mogball** [comment]
This is not expected and to an extent is a known bug, but we did not realize that this could be one manifestation of the bug. Thanks for finding this @igorgue ! We'll look into it.
