### ISSUE TITLE
I am having a issue regarding the 00PS concepts in mojo

### ISSUE THREAD

**Issue by Dev00kushal** [modularml/mojo#928]
### Issue description

I am getting erros regrading the OOPS concepts 

    struct Student:
          var age : Int
          var final_marks : Float16 

    fn __init__(inout self, name: String, age : Int , final_marks :Float16, rhs:Student):
        self.name = name
        self.age = age
        self.final_marks: float = final_marks

    fn hasPassed(final_marks:Float16, rhs:Student)-> String:
        if(final_marks >= 40):
            print "The student has passed the module"
        else:
            print "You have failed the module"

    fn isLegit(age: Int, rhs:Student)-> Int:
        if(age >= 18):
            return True
        else:
            print "You haven't reached the age to become a student of the uni"
    fn main():
           print(Student.isLegit(30))

**Comment by Mogball** [comment]
Is this a bug?

**Comment by Dev00kushal** [comment]
Yes  it is showing me this error
![image](https://github.com/modularml/mojo/assets/127578046/950b7a05-b31f-451a-8450-2f5f218dc0db)

**Comment by Mogball** [comment]
Hey, it looks like you're not defining the member functions correctly for the `Student` struct. The first argument of member functions must be `self`. If you have additional questions, please check out our discord https://discord.com/channels/1087530497313357884/1149739720146952292 or post a discussion
