### ISSUE TITLE
[Dev Console]: Invalid command

### ISSUE THREAD

**Issue by ysh-rawat-11** [modularml/mojo#934]
### Issue description

getting invalid command in the compiler 
but working on run button

### Steps to reproduce

- Add screenshots if possible, to help explain the problem.
- Include anything that might help us debug the issue.
![image](https://github.com/modularml/mojo/assets/112065069/15a561f2-3b93-47b9-bef4-4fb0db9da625)

**Comment by aerosolwzt** [comment]
I also have this problem, do you know how to slove it?
getting invalid command in the compiler
but working on vscode run button

**Comment by ematejska** [comment]
mojo team, we need more feedback about what needs to be fixed.

**Comment by Mogball** [comment]
I hit this locally. There might be an issue with how the `mojo` tool parses commandline flags @modocache

**Comment by modocache** [comment]
Sorry it took me a while to respond. This seems very tricky. For one thing, all errors coming from `mojo` are prefixed with:

```
mojo: error:
```

So, for example, if you try to invoke `mojo` with a subcommand that doesn't exist, you'll see this error:

```
mojo: error: no such command 'dance'
```

And if you attempt to run `mojo` on a file that doesn't exist, you'll see:

```
mojo: error: cannot open input file '/Users/brian/tmp/l.mojo': No such file or directory
```

But in the screenshot, however, I see:

```
Invalid command "l.mojo"
```

I'm not sure what part of your system is producing this message, but I'm fairly certain it's not `mojo`. My first guess was that `mojo` wasn't on your PATH, but the errors I get on Ubuntu and macOS don't print "Invalid command":

```
# On Ubuntu
$ mojo l.mojo
Command 'mojo' not found, but can be installed with:
sudo snap install mojo                 # version 1.0.0+601, or
sudo apt  install libmojolicious-perl  # version 9.22+dfsg-1
See 'snap info mojo' for additional versions.
```

```
# On macOS
% mojo l.mojo                  
zsh: command not found: mojo
```

Maybe you have `mojo` aliased to some other command, some sort of program that would print the error message `Invalid command "l.mojo"`? I will need more information to help you debug this. A good start would be responding with the results of what @jackos recommended:

```
uname -a
which mojo
```

Please post these as a comment and re-open the issue when you do, @ysh-rawat-11 -- thanks!
(And @aerosolwzt, could you please create a separate issue, and include more information when you do? Please follow the instructions in the new issue templates to provide us with enough details to help -- thanks!)
