### ISSUE TITLE
[Feature Request] binary build via `mojo build` could not run directly on other os

### ISSUE THREAD

**Issue by liudonghua123** [modularml/mojo#935]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

Hi, I tried to build a simple mojo app which use numpy. And I copied the binary to another os, it could not run directly. I have to install python and related packages like numpy.

```mojo
from python import Python

def main():
    # This is equivalent to Python's `import numpy as np`
    let np = Python.import_module("numpy")

    # Now use numpy as if writing in Python
    array = np.array([1, 2, 3])
    print(array)
```

```
┌──(liudonghua㉿DESKTOP-DELL)-[/mnt/c/Users/Liu.D.H]
└─$ ldd /mnt/d/hello_numpy
        linux-vdso.so.1 (0x00007ffe3f9ef000)
        libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007f2573171000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2572f1b000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2572e3c000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2572e18000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2572c36000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f25731e9000)

┌──(liudonghua㉿DESKTOP-DELL)-[/mnt/c/Users/Liu.D.H]
└─$ /mnt/d/hello_numpy
Mojo/Python interoperability error: Unable to locate a suitable libpython, please set `MOJO_PYTHON_LIBRARY`
Segmentation fault

┌──(liudonghua㉿DESKTOP-DELL)-[/mnt/c/Users/Liu.D.H]
└─$ sudo apt install python3 python-is-python3 python3-dev python3-pip

┌──(liudonghua㉿DESKTOP-DELL)-[/mnt/c/Users/Liu.D.H]
└─$ find-python-for-mojo() {
    libpath=$(python3 -c 'import sysconfig; print(sysconfig.get_config_var("LIBDIR"))')
    pythonlib=$(ls $libpath | grep "libpython3.*[0-9]\.so$")
    export MOJO_PYTHON_LIBRARY=${libpath}/${pythonlib}
}

┌──(liudonghua㉿DESKTOP-DELL)-[/mnt/c/Users/Liu.D.H]
└─$ find-python-for-mojo

┌──(liudonghua㉿DESKTOP-DELL)-[/mnt/c/Users/Liu.D.H]
└─$ echo $MOJO_PYTHON_LIBRARY
/usr/lib/x86_64-linux-gnu/libpython3.11.so

┌──(liudonghua㉿DESKTOP-DELL)-[/mnt/c/Users/Liu.D.H]
└─$ /mnt/d/hello_numpy
Unhandled exception caught during execution: An error occurred in Python.

┌──(liudonghua㉿DESKTOP-DELL)-[/mnt/c/Users/Liu.D.H]
└─$ pip install numpy

┌──(liudonghua㉿DESKTOP-DELL)-[/mnt/c/Users/Liu.D.H]
└─$ /mnt/d/hello_numpy
[1 2 3]

```

### What is your motivation for this change?

I wish the generated binary could run directly, no need to install python3-dev and dependencies, all the needed libraries are included in the binary.

**Comment by zscgo** [comment]
Hope it can be done.This is a blessing for programmers.

**Comment by gryznar** [comment]
As for now, Mojo is using CPython internally to execute Python code. So there is no way currently to package such code into single binary in an easy way

**Comment by fooofei** [comment]
hope mojo can package python files and python .so files to mojo executable binary

**Comment by River707** [comment]
Thanks for filing! We're still working a bit through different mojo compilation models, and how we package things together. No direct updates, but this is something we're actively thinking through!

**Comment by Moosems** [comment]
One idea is to, in compilation, take the code inside the libraries and compile them as mojo code (because eventually all normal python will be valid mojo) going layer by layer until all code is compiled and then bundle all of that together instead of even trying to actually deal with raw python

**Comment by walter-erquinigo** [comment]
As of now, this feature is not part of the roadmap, so we won't be working on this in the foreseeable future. However, we are working a new python integration that might make this more feasible.
