### ISSUE TITLE
VS Code remote development mojo SDK MODULAR_HOME variable issue

### ISSUE THREAD

**Issue by tbuckworth** [modularml/mojo#940]
I am using VS Code on Windows, SSH'd into a Linux box running Ubuntu.

On the Linux box, I have successfully installed the mojo SDK:

`which mojo` returns:
`/root/.modular/pkg/packages.modular.com_mojo/bin/mojo`

`echo $MODULAR_HOME` returns this
`/root/.modular`

When I try to run a .mojo file in VS Code, it says 

> The Mojo🔥 development environment was not found. If the Mojo SDK is installed, please set the MODULAR_HOME environment variable to the appropriate path, or set the `mojo.modularHomePath` configuration. If you do not have it installed, would you like to install it?

This gives the option to open the setting, which I have done:

![image](https://github.com/modularml/mojo/assets/55180288/279705b7-bed9-4f2f-bc2a-e69b88d2f383)

But when I try to run .mojo file, the same issue arises.

**Comment by jackos** [comment]
Hi @tbuckworth do you get an error when you try to run `mojo` in the terminal?

**Comment by f33rn44nd00** [comment]
Hi, @tbuckworth, I'm having the same problem, mojo runs just fine in the Ubuntu terminal, I think this path refers to a location inside the virtual machine so mojo won't just run inside VScode unless you are in the correct environment? 
Sorry if that's wrong, I'm not very familiar with Ubuntu virtual machines but on my PC mojo commands work only when I go the Ubuntu env in VScode, otherwise I get the same error.
@jackos, this notification appears whenever I am not in the Ubuntu environment on VSCode, is it possible to disable it?

**Comment by jackos** [comment]
@f33rn44nd00 that's true, if you're on Windows running WSL you want to path to be relative to your ubuntu installation, which is generally: `/home/ubuntu/.modular`

To turn of the message you can run this command:
<img width="601" alt="Screenshot 2023-09-29 at 8 27 36 am" src="https://github.com/modularml/mojo/assets/77730378/5500ce33-9309-4374-8724-9d35250cdc95">

But it's best to set your `MODULAR_HOME` env var correctly so you don't get the problem on different machines.

**Comment by f33rn44nd00** [comment]
The notifications stopped showing when I manually copied the path to the extension settings in VSCode. Thanks @jackos

**Comment by tbuckworth** [comment]
> Hi @tbuckworth do you get an error when you try to run `mojo` in the terminal?

Hi @jackos I can run mojo fine in the terminal, but only as root. Could it be that not being root on VSCode is the issue? 

Though I'm not sure how to run remote development with root privileges.

I had to be root to install mojo, but it's odd I can't run it without being root user.

**Comment by tbuckworth** [comment]
Apologies didn't mean to close then

**Comment by Andrew011002** [comment]
Hey @tbuckworth I was able to run mojo through windows WSL on vscode. What I did was run the command you did above `echo $MODULAR_HOME` and then copy & pasted the path in the _Mojo: Modular Home Path_ for the User, Remote [WSL: Ubuntu], and Workspace tabs (just for a sanity check). My path was `/home/andrew/.modular` and I was getting interpreter warnings for invalid syntax when I wasn't before. I'm not sure if this was exactly the problem you were facing, but I hope it helps.

**Comment by tbuckworth** [comment]
> Hey @tbuckworth I was able to run mojo through windows WSL on vscode. What I did was run the command you did above `echo $MODULAR_HOME` and then copy & pasted the path in the _Mojo: Modular Home Path_ for the User, Remote [WSL: Ubuntu], and Workspace tabs (just for a sanity check). My path was `/home/andrew/.modular` and I was getting interpreter warnings for invalid syntax when I wasn't before. I'm not sure if this was exactly the problem you were facing, but I hope it helps.

Thanks @Andrew011002 . I am facing a different issue as i'm not using WSL, but remote hosting a Windows VS Code session from a Linux pc

**Comment by walter-erquinigo** [comment]
@tbuckworth , does the issue persist if you place the setting at the `Remote [SSH: mah]` level instead of `Workspace`?

![Image](https://github.com/modularml/mojo/assets/1613874/adb03bde-685c-4bb4-9f55-9620c907c593)

Besides that, that removing the trailing `/` in your setting path fix the issue?

And finally, is `mojo run` the only feature that is broken? Can you still hover over code and see docstrings?

**Comment by SaiNikhil1258** [comment]
> @tbuckworth , does the issue persist if you place the setting at the `Remote [SSH: mah]` level instead of `Workspace`?
> 
> ![Image](https://private-user-images.githubusercontent.com/1613874/275959969-adb03bde-685c-4bb4-9f55-9620c907c593.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxOTM3NjgsIm5iZiI6MTcwODE5MzQ2OCwicGF0aCI6Ii8xNjEzODc0LzI3NTk1OTk2OS1hZGIwM2JkZS02ODVjLTRiYjQtOWY1NS05NjIwYzkwN2M1OTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTdUMTgxMTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzRjODQ5N2RmNjAyN2U2MWIyMjRmN2E1YmNiMGQ1OGIwZjAwZTMxN2JjZTVkMzQyNzZhNTJjMzYyYjg4Y2ZhMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Z4vemfEJ7ABjucFceCgUbhtM5gsl6CeaAOZQKXXc4Hg)
> 
> Besides that, that removing the trailing `/` in your setting path fix the issue?
> 
> And finally, is `mojo run` the only feature that is broken? Can you still hover over code and see docstrings?

i have used the `/home/nikhil/.modular` but this didn't work when i used the `/root/.modular/` setting this path seems to be working

**Comment by RudeScotsman** [comment]
I am struggling with the same issue and cannot resolve it. I am on Windows 11 and have installed mojo on Ubuntu 22.04.4 LTS and mojo test programs run fine from the ubuntu command line. I have installed the mojo SDK on vscode and I can run mojo fine from the (ubuntu) terminal in vscode but trying to run mojo programs from the vscode editor throws the 'mojo development  environment was not found'. I have set MODULAR_HOME within vscode to the value I see from ubuntu CLI.

I must be missing something simple?

**Comment by walter-erquinigo** [comment]
@RudeScotsman , thanks for the report. Did you make sure that the modularHomePath setting is set at the `Remote SSH` level?

**Comment by RudeScotsman** [comment]
@walter-erquinigo - thanks for the reply. How do I set modularHomePath at the Remote SSH level?

My mojo.modularHomePath is set to /home/<my user name>/.modular and this path is the same when I echo MODULAR_HOME on the ubuntu CLI within vs code and the running ubuntu session on my PC.

Do I need the Remote SSH extension within vs code?

I am using the correct terminal within vs code, see below.

![image](https://github.com/modularml/mojo/assets/27415963/54b9a05f-d4d4-432e-a479-242416741c72)

**Comment by levalencia** [comment]
I am facing the same issue.  I have Windows with Ubuntu WSL.

My modular path is:
/home/levm38/.modular

I tried in vs code the same path and it says it cant find the development environment.

I also tried a NETWORK PATH like this:
\\wsl.localhost\Ubuntu-22.04\home\levm38\.modular

same problem!

So I cant use MOJO yet!

**Comment by RudeScotsman** [comment]
@levalencia - I got it working by using the Remote Explorer in vs code.

On my PC I have Ubuntu 22.04.3 LTS installed and I run this app and install mojo. Within this app I have a dir for all my mojo files and they run fine.

When I fire up vs code I click on Remote Explorer.

![image](https://github.com/modularml/mojo/assets/27415963/c4cff7ce-d92d-4d8e-ac0d-31a26d494b6c)

You can then connect to your ubuntu session running on your PC and run the mojo files you have within your ubuntu app.

I think you need the Remote - SSH extension installed for this to work.

On the status bar you should see something like this:

![image](https://github.com/modularml/mojo/assets/27415963/9c1911a2-f9a5-4242-9322-33b115763572)

I think this is what Walter was talking about above, setting the remote ssh level but not sure. Anyhow, this works for me and I can now tinker with mojo remotely from vs code.


References:

- https://code.visualstudio.com/docs/remote/ssh

**Comment by walter-erquinigo** [comment]
Given that the SSH Extension works as a good solution, I'll be closing this issue. Anyone feel free to reopen if they encounter similar issues.

As a final note, the team is planning to work on a more automated SDK configuration process for VSCode, which should help alleviate the friction reported in this issue.

**Comment by antonl321** [comment]
Some good news form me.
I got vscode working on wsl2  as follow:
in a project that was initialised with magic for a mojo project ( magic init hello-world --format mojoproject):
magic shell
magic add ipykernel
vscode .
open a new notebook, open a cell  put in it print("hellow world")
select the local mojo kernel , i.e. has the path   .magic/<etc>  NOT the user level one  with path  ~/.modular/<etc> 
and bingo the cell processing worked for me!
before adding ipykernel vscode was getting in an infinite loop.

versions details:
(hello-world-2) syla@syla-laptop:~/Apps/mojo/hello-world-2$ magic --version
magic 0.3.1 - (based on pixi 0.29.0)
(hello-world-2) syla@syla-laptop:~/Apps/mojo/hello-world-2$ mojo --version
mojo 24.5.0 (e8aacb95)
