### ISSUE TITLE
[Feature Request]: Kali Linux Support

### ISSUE THREAD

**Issue by Mohamed-Bloul** [modularml/mojo#942]
### Bug description

![Screenshot 2023-09-28 at 1 26 10 PM](https://github.com/modularml/mojo/assets/134459251/e9c44212-4670-4585-a89d-fe8b38810d87)

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by ematejska** [comment]
Thank you for trying out Mojo.  The installation experience has significantly changed and we're closing out all the old issues with the old installer.  To try out our new installation experience using "magic", please see: https://docs.modular.com/mojo/manual/get-started.
