### ISSUE TITLE
[Feature Request] Support for Raspberry Pi

### ISSUE THREAD

**Issue by mikekppp** [modularml/mojo#945]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

The Raspberry Pi platform represents a broad range of ARM-based devices used for experimentation and easy deployment of embedded systems. While the mainstream (supported) OS is based on Debian, there are unique aspects to the platform that may require specific 'tweaks' to Mojo (or more specifically, the development environment) to support this platform. I will grant that this platform may be covered by current plans for Linux support (I have not tried to install the Mojo platform on a Pi), but nonetheless this Github issue may represent a tracking point to insure that Mojo does work on a Pi.  I know that the Raspberry Pi organization would be very supportive of this effort, especially in terms of offering yet another educational opportunity for students to program on their platform.

### What is your motivation for this change?

Raspberry Pis are ubiquitous in the DIY and Maker communities for their cost and ease of use.  Mojo support for this platform would not only offer a broad (and large) audience the opportunity to use the language, but engages a community of contributors who would gladly invest time in improving/furthering the goals of Modular and Mojo.

**Comment by mikekppp** [comment]
I would differentiate my request in terms of putting together a nice package for the RPi (and similar ARM-based SBCs).  Python is already a significant learning tool on this platform, so this is more than just making sure Mojo works on ARM64 Linux.

**Comment by LCrossman** [comment]
I am totally keen on this!

Raspberry Pi 5 specs:
64-bit quad core Cortex A76 processor
8GB LPDDR4X SDRAM 

> sudo apt install modular
_E: unable to locate package modular_

**Comment by hacknug** [comment]
According to #1093 support for arm64 was added in v24.01. There is no mention of it on [the changelog](https://docs.modular.com/mojo/changelog#v241-2024-02-29) so I'm not sure if this can be closed or not.

**Comment by johndelavega** [comment]
> According to #1093 support for arm64 was added in v24.01. There is no mention of it on [the changelog](https://docs.modular.com/mojo/changelog#v241-2024-02-29) so I'm not sure if this can be closed or not.

Has anyone tried running a binary generated for arm64 on Raspberry Pi?
A simple Hello World is a good start.
A host computer builder need not be Pi for now.

**Comment by LCrossman** [comment]
Hi,  I have installed modular and mojo
Linux raspberrypi 6.6.20+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.20-1+rpt1 (2024-03-07) aarch64 GNU/Linux
for Debian Bookworm aarch64 on Raspberry Pi 5 
mojo-aarch64-unknown-linux-gnu-24.2.0-c2427bc5-release-11-0.tar.gz
and can confirm mojo is running hello world
under mojo --version mojo 24.2.0

```
pi@raspberrypi:~ $ mojo hello.mojo
Hello, world!
```

**Comment by walter-erquinigo** [comment]
Thank you for reporting this. I'm closing this for now. Eventually we'll include other OS - architectures.
