### ISSUE TITLE
[BUG]: range(2, 1) behaves differently to Python

### ISSUE THREAD

**Issue by helehex** [modularml/mojo#946]
### Bug description

The range(start, end) acts strange, but not when inside another loop.

the strange part is this:
When **end** is one less than **start**, it still runs

### Steps to reproduce

fn main():

    for j in range(5,11):
        for i in range(8, j):
            print("8,", j, " ~", i) #--- prints what you would expect
    
    for i in range(8, 5):
        print("8,5 ~ ", i) #--- prints nothing

    for i in range(8, 6):
        print("8,6 ~ ", i) #--- prints nothing

    for i in range(8, 7):
        print("8,7 ~ ", i) #--- prints 8

    for i in range(8, 8):
        print("8,8 ~ ", i) #--- prints nothing

    for i in range(8, 9):
        print("8,9 ~ ", i) #--- prints 8

    for i in range(8, 10):
        print("8,10 ~ ", i) #--- prints 8, 9

### System information

```shell
- wsl ubuntu 2
- mojo 0.3.1 (a3eed7c8)
- modular 0.2.0 (355ea9c0)
```

**Comment by jackos** [comment]
In Python this doesn't print anything:
```python
for i in range(2, 1):
    print(i)
```
But in mojo it prints `2`

**Comment by weiweichen** [comment]
Fixed with PR ⬆️
