### ISSUE TITLE
[BUG]: Installing Mojo on Ubuntu 22-04.2 on Oracle VirtualBox 7.0.10

### ISSUE THREAD

**Issue by vesko2020** [modularml/mojo#947]
### Bug description

I was able to install the latest Modular (0.2.0). 
Installation of Mojo (0.3.1) has completed, but reported problem with 'testing mojo' (all items in the test), It reported that mojo was installed. When i try to run mojo i got error 'Illegal instruction (core dumped)'

The following errors show up during testing mojo:
[mojo] Testing: `mojo --help` [FAIL]

[mojo] Testing: `mojo run --help` [FAIL]

[mojo] Testing: `mojo build test_mandelbrot.mojo` [FAIL]

[mojo] Testing: `mojo build test_python.mojo` [FAIL]

[mojo] Testing: `mojo demangle` [FAIL]

[mojo] Testing: `mojo format` [FAIL]

[mojo] Testing: `mojo package` [FAIL]

[mojo] Testing: `mojo test_mandelbrot.mojo` [FAIL]

[mojo] Testing: `mojo test_python.mojo` [FAIL]

[mojo] Testing: `mojo repl` [FAIL]

[mojo] Some components may have been installed successfully, but others may not work as expected. Please submit an issue to https://github.com/modularml/mojo and include the full output of the command you just ran.

🔥 Mojo installed! 🔥

Mojo's Python virtual environment created at /home/vesko/.modular/pkg/packages.modular.com_mojo/venv

F.Y.I. In previous version of Modular/Mojo I had problem with Installation on WSL2. Installation of latest version was ok without any problem.

Thank you for that. 
Vesko

### Steps to reproduce

modular install mojo

### System information

```shell
- What OS did you do install Mojo on ?  Ubuntu 22-04.2 on Oracle VirtualBox
- Provide version information for Mojo by pasting the output of `mojo -v`: Illegal instruction (core dumped)
- Provide Modular CLI version by pasting the output of `modular -v`: modular 0.2.0 (355ea9c0)
```

**Comment by jackos** [comment]
@vesko2020 can you please show the full error message you get when you try to run `mojo`?

**Comment by vesko2020** [comment]
Hi Jackos,
Thanks you for fast respond. As I told you, when I try to run mojo (mojo -v) i get error:
`mojo -v`: Illegal instruction (core dumped). That is all.
If you want I could reinstall mojo and show you full log of installation.
Thanks,
Vesko

**Comment by jackos** [comment]
Two things here, Oracle VirtualBox has problems, users haven't been able to successfully install on there, if you're on Windows use WSL2 instead, if you're on Linux use Docker.

Also a lot of installation errors have been fixed recently, try a fresh Ubuntu 22.04 on Docker/WSL2 and it should work for you.

**Comment by vesko2020** [comment]
Thanks you a lot.
Vesko

**Comment by jackos** [comment]
Closing as VirtualBox support isn't planned before Windows and macOS native support, which will resolve issues.
