### ISSUE TITLE
[BUG]: num_cores from Runtime library shows 2 cores when system has 4 cores

### ISSUE THREAD

**Issue by VMois** [modularml/mojo#950]
### Bug description

In Mojo 0.3.1 when num_cores is called on a system with 4 cores, it returns number 2. It did not happen in Mojo 0.2.1

### Steps to reproduce

Run this Mojo snippet.

```python
from runtime.llcl import num_cores

fn main():
    print(num_cores())
```

On Github Codespaces with 4 cores (verified with lscpu), it will output two.

### System information

```shell
- What OS did you do install Mojo on ? 
Ubuntu (Github Codespaces instance with 4 cores)

- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.3.1 (a3eed7c8)

- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.1.4 (6b54d308)
```

**Comment by VMois** [comment]
Part of the output of strace of Mojo snippet.

```
...
01:27:45.706265 sched_getaffinity(0, 128, [0, 1, 2, 3]) = 8 <0.000019>
01:27:45.706355 openat(AT_FDCWD, "/proc/cpuinfo", O_RDONLY|O_CLOEXEC) = 3 <0.000022>
01:27:45.706443 read(3, "processor\t: 0\nvendor_id\t: Authen"..., 16384) = 3813 <0.000053>
01:27:45.706566 read(3, "processor\t: 3\nvendor_id\t: Authen"..., 16384) = 1271 <0.000025>
01:27:45.706650 read(3, "", 16384)      = 0 <0.000013>
...
```

**Comment by gujuriu** [comment]
Hi @VMois, what you posted might be similar with [this discussion](https://github.com/modularml/mojo/discussions/911).

**Comment by VMois** [comment]
> Hi @VMois, what you posted might be similar with [this discussion](https://github.com/modularml/mojo/discussions/911).

Thank you for the pointer. Looks like my instance has two threads per core. So only two physical cores

```bash
$ lscpu | egrep "Model name|Socket|Thread|NUMA|CPU\(s\)"
CPU(s):                             4
On-line CPU(s) list:                0-3
Thread(s) per core:                 2
Socket(s):                          1
NUMA node(s):                       1
Model name:                         AMD EPYC 7763 64-Core Processor
NUMA node0 CPU(s):                  0-3
```

But then I am still curious why Mojo version 0.2.1 shows 4 cores and current 0.3.1 shows 2 cores.

**Comment by akirchhoff-modular** [comment]
This was an intentional change. Before, `num_cores` returned the number of threads. Now, it returns the number of physical cores, as the name might imply. We do not currently expose an API to get the number of threads, but if that would be useful to you, you could open a new issue as a feature request.

Note that `runtime.llcl` is considered internal and is intentionally undocumented, so there may be more breaking changes here without notice in the future. We may provide a supported alternative in the future.
