### ISSUE TITLE
[Docs] Small typo

### ISSUE THREAD

**Issue by Yelinz** [modularml/mojo#956]
### Where is the problem?

https://docs.modular.com/mojo/stdlib/algorithm/functional.html#elementwise

### What can we do better?

`out_chain (OutputChainPtr): The our chain to attach results to.`

Should probably be 

`out_chain (OutputChainPtr): The out chain to attach results to.`

### Anything else?

Maybe even keep it consistent with the other modules such as 
https://docs.modular.com/mojo/stdlib/builtin/dtype.html#dispatch_floating
` out_chain (OutputChainPtr): The output chain used to report errors.`
Either out or output, but not mixing them

**Comment by scottamain** [comment]
Thank you! This will be fixed in the next update.
