### ISSUE TITLE
[Modular CLI]: Cannot install   modular cli 

### ISSUE THREAD

**Issue by moritz-braun** [modularml/mojo#959]
### Issue description

I attempted to  install   modular cli+mojo on ubuntu  23-04 using the instructions given on 
https://developer.modular.com/download
This was not successful the output of the curl command was:

 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3176  100  3176    0     0   4636      0 --:--:-- --:--:-- --:--:--  4636
[sudo] password for braunm: 
Executing the  setup script for the 'modular/installer' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=ubuntu  version=23.04  codename=lunar  arch=x86_64  
 >>>>:
  RUN: Checking for apt dependency 'apt-transport-https' ...dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 77009 package 'play':
 missing 'Maintainer' field
 NOPE: Checking for apt dependency 'apt-transport-https' ...
 NOPE: Updating apt repository metadata cache ...
Failed to update via apt-get update
Get:1 http://security.ubuntu.com/ubuntu lunar-security InRelease [109 kB]
Hit:2 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:3 http://bw.archive.ubuntu.com/ubuntu lunar InRelease
Ign:4 https://ppa.launchpadcontent.net/juju/stable/ubuntu lunar InRelease
Get:5 http://bw.archive.ubuntu.com/ubuntu lunar-updates InRelease [109 kB]
Hit:6 https://packages.microsoft.com/repos/edge stable InRelease
Err:7 https://ppa.launchpadcontent.net/juju/stable/ubuntu lunar Release
  404  Not Found [IP: 185.125.190.52 443]
Get:8 http://security.ubuntu.com/ubuntu lunar-security/main amd64 DEP-11 Metadata [7408 B]
Get:9 http://bw.archive.ubuntu.com/ubuntu lunar-backports InRelease [99.8 kB]
Get:10 http://security.ubuntu.com/ubuntu lunar-security/universe amd64 DEP-11 Metadata [12.3 kB]
Get:11 http://bw.archive.ubuntu.com/ubuntu lunar-updates/main amd64 Packages [439 kB]
Get:12 http://bw.archive.ubuntu.com/ubuntu lunar-updates/main i386 Packages [226 kB]
Get:13 http://bw.archive.ubuntu.com/ubuntu lunar-updates/main amd64 DEP-11 Metadata [81.3 kB]
Get:14 http://bw.archive.ubuntu.com/ubuntu lunar-updates/restricted i386 Packages [24.7 kB]
Get:15 http://bw.archive.ubuntu.com/ubuntu lunar-updates/restricted amd64 Packages [358 kB]
Get:16 http://bw.archive.ubuntu.com/ubuntu lunar-updates/universe amd64 Packages [804 kB]
Get:17 http://bw.archive.ubuntu.com/ubuntu lunar-updates/universe amd64 DEP-11 Metadata [52.8 kB]
Get:18 http://bw.archive.ubuntu.com/ubuntu lunar-updates/multiverse amd64 Packages [6328 B]
Get:19 http://bw.archive.ubuntu.com/ubuntu lunar-backports/universe amd64 DEP-11 Metadata [13.2 kB]
Reading package lists...
E: The repository 'https://ppa.launchpadcontent.net/juju/stable/ubuntu lunar Release' does not have a Release file.
 ^^^^: ... Failed to update via apt-get update - Context above.
 !!!!: Oh no, your setup failed! :-( ... But we might be able to help. :-)
 !!!!: 
 !!!!: You can contact Modular for further assistance.
 !!!!: 

It seems the line is described in th line starting with E:
I tried to get around this by installing  juju from another source but that did not work.
Please assist!

Regards

Moritz 

### Steps to reproduce

See above ; it happened after the curl command 

### Version Info

```shell
`
- What OS did you install modular CLI on ?
OS was ubuntu 23-04
```

**Comment by alew3** [comment]
same error here on Ubuntu 22.10

curl https://get.modular.com | \
  MODULAR_AUTH=mut_bb3d7dddef0d4d2480076ec20874c78f \
  sh -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3176  100  3176    0     0  12801      0 --:--:-- --:--:-- --:--:-- 12806
Executing the  setup script for the 'modular/installer' repository ...

 NOPE: Checking for required executable 'curl' ...
 ^^^^: ... curl is not installed, but is required by this script.
 !!!!: Oh no, your setup failed! :-( ... But we might be able to help. :-)
 !!!!: 
 !!!!: You can contact Modular for further assistance.
 !!!!: 
 !!!!: Last 20 log lines from .csm_setup_jJi6zyfbS (might not be errors, nor even relevant):
 !!!!:

**Comment by smuniraj2018** [comment]
There is something wrong with what you are trying to install from https://ppa.launchpadcontent.net/juju/stable/ubuntu.

**Comment by moritz-braun** [comment]
Dear smuniraj2018

Sorry this is not  a solution.
I cannot fix this myself.
Please help me to fix the juju that is being used to install  mojo!

**Comment by moritz-braun** [comment]
This is likely affecting  many ubuntu users please help!
