### ISSUE TITLE
[Feature Request] VSCode extension should fill symbols outline view

### ISSUE THREAD

**Issue by guidorice** [modularml/mojo#960]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

VSCode extension reports "No symbols found in document {filename}.mojo" when I browse the outline panel.
This is kind of a standard feature for language extensions. Adding this support would bring it on par with other languages like Python, for example.

### What is your motivation for this change?

Better user experience for VSCode extension.

### Any other details?

mojo v0.3.1

**Comment by River707** [comment]
This should be fixed in the next release!

**Comment by guidorice** [comment]
This is working great in mojo 0.6! Thanks @River707
