### ISSUE TITLE
[BUG]: Can't import python modules

### ISSUE THREAD

**Issue by hellspawn679** [modularml/mojo#961]
### Bug description

i am unable to import any python code even the code given in examples i even went through these steps https://github.com/modularml/mojo/issues/551
but still it is giving me error 

### Steps to reproduce

code :

from python import Python
fn main() raises:
    let np =Python.import_module("numpy")
    let arr=np.array([1,2,3])
    print(arr*2)

error :
[3931:3931:20230930,181344.119430:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[3931:3931:20230930,181344.119513:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.      Program arguments: /home/kali/.modular/pkg/packages.modular.com_mojo/bin/mojo /home/kali/hello.mojo
#0 0x0000556ef47bd797 (/home/kali/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5bc797)
#1 0x0000556ef47bb36e (/home/kali/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5ba36e)
#2 0x0000556ef47bde6f (/home/kali/.modular/pkg/packages.modular.com_mojo/bin/mojo+0x5bce6f)
#3 0x00007f65b9366520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
Segmentation fault

screenshot :
![Screenshot 2023-09-30 181636](https://github.com/modularml/mojo/assets/112504479/bb90876f-9843-49e7-b7d4-d14334e8b216)

### System information

```shell
i am using windows 11 and running this on wsl 
OS: Ubuntu 22.04.3 LTS on Windows 10 x86_64 
Kernel: 5.15.90.1-microsoft-standard-WSL2 
Uptime: 59 mins 
Packages: 585 (dpkg), 7 (snap) 
Shell: bash 5.1.16 
CPU: AMD Ryzen 5 5600H with Radeon Graphics (12) @ 3.293GHz 
GPU: 3586:00:00.0 Microsoft Corporation Device 008e 
Memory: 1852MiB / 7613MiB
mojo version - mojo 0.3.1 (a3eed7c8)
modular version - modular 0.2.0 (355ea9c0)
```

**Comment by oskgo** [comment]
Try following the steps in this comment: https://github.com/modularml/mojo/issues/537#issuecomment-1718038049
