### ISSUE TITLE
[BUG]: Mojo fails to handle imported python functions with keyword arguments

### ISSUE THREAD

**Issue by oskgo** [modularml/mojo#964]
### Bug description

Mojo behaves unexpectedly when calling python code with keyword arguments.

The code is seemingly never called, and if the result is stored in a variable code that interacts with this variable also starts acting unexpectedly.

In the example code below I would expect to either get an error, or have `0` and `200` printed, but instead nothing is printed.

### Steps to reproduce

`test.mojo`:
```python
from python import Python

def main():
    Python.add_to_path(".")
    let p = Python.import_module("test").foo(a=0)
    print(p)
    p = 200
    print(p)
```
`test.py`:
```python
def foo(a):
    return a
```

### System information

```shell
- Windows 11 with Ubuntu in WSL
- mojo 0.3.1 (a3eed7c8)
- modular 0.1.4 (6b54d308)
```

**Comment by jackos** [comment]
Thanks for raising @oskgo this is being worked on

**Comment by asdfng** [comment]
Was this resolved in a commit?

**Comment by gryznar** [comment]
@jackos is fix to that going to be introduced in 0.7?

**Comment by karthikgk97** [comment]
Any update on this issue?

**Comment by XRTIDE** [comment]
0.7版本尚未修复!

**Comment by laszlokindrat** [comment]
This should work as of version 24.2. Please open a new ticket if you run into any problems!
