### ISSUE TITLE
[BUG]: i am install by command "modular auth mut_a7ae3fd2456d43ad9ca26184acc7e312 && modular install mojo".

### ISSUE THREAD

**Issue by EuLeEr** [modularml/mojo#965]
### Bug description

 got repeatedly error http error: failed to reach URL https://cas.modular.com/0/r7Uh_7YudP025MOQM_uMTbA5iOdIlKqnoXgfywB20_Y with cURL error Timeout was reached

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by Sharktheone** [comment]
You maybe should remove your modular auth token from the title. 😅 I'm not shure if you can reset your token on the modular website, but if you find something there, you definitely should do that.

**Comment by EuLeEr** [comment]
> You maybe should remove your modular auth token from the title. 😅 I'm not shure if you can reset your token on the modular website, but if you find something there, you definitely should do that.

No, thats wrong working service command  "modular install mojo" - error 
Failure Information:
        - http error: failed to reach URL https://cas.modular.com/0/bueXLcXkZfEuNjzSWkN74f3bbf-nRaCTpAATTkZvFdU with cURL error Timeout was reached - Looking for bueXLcXkZfEuNjzSWkN74f3bbf-nRaCTpAATTkZvFdU
        - http error: failed to reach URL https://cas.modular.com/0/r7Uh_7YudP025MOQM_uMTbA5iOdIlKqnoXgfywB20_Y with cURL error Timeout was reached - Looking for r7Uh_7YudP025MOQM_uMTbA5iOdIlKqnoXgfywB20_Y

**Comment by Sharktheone** [comment]
first, this looks to me like #598.

I also don't mean the URL to be your auth token, but in the title the "mut_xxxxx..."

**Comment by EuLeEr** [comment]
Thanks, Done ! ;-)
