### ISSUE TITLE
[BUG]: Keyword arguments in struct not working as intended

### ISSUE THREAD

**Issue by charlielu05** [modularml/mojo#967]
When struct is created in Mojo with keyword argument instead of positional argument, it seems to fail and lose reference to the data passed in.

An example:
```
struct MyPair:
    var first: Int
    var second: Int

    fn __init__(inout self, first: Int, second: Int):
        self.first = first
        self.second = second

    fn dump(self):
        print(self.first, self.second)

fn main():
	let a = MyPair(first=1, second=2)
	a.dump()
```
When executed either using the CLI or built binary, this results in an empty printout.

Changing the variable `let a = MyPair(1, 2)` works and prints out `1 2`

Using mojo version 0.3.0
DevContainer (official microsoft DevContainer python image 3-10) on Intel Mac VSCode

This bug has also been reported by one other user on Discord (https://discord.com/channels/1087530497313357884/1156835051129024522)

**Comment by lattner** [comment]
@laszlokindrat can you take a look at this?

**Comment by charlielu05** [comment]
Upgraded to mojo version 0.4.0 and this problem seems to have been fixed :)

**Comment by laszlokindrat** [comment]
Hi @charlielu05, thanks for checking in on this! Indeed, I am actively working on improving this area, so bugs might be fixed before they are discovered externally. Regardless, please continue to file tickets if you run into issues!
