### ISSUE TITLE
[BUG] Python interop doesn't support `**`

### ISSUE THREAD

**Issue by lattner** [modularml/mojo#97]
This looks like the Python object just needs to implement the right operator methods and forward them on:
```
error: Expression [7]:6:13: 'object' does not implement the '__pow__' method
    return a**34
           ~^
```

I'm sure we're missing other ones too.  @stumpOS can you take a look plz?

**Comment by lattner** [comment]
also missing  division and fdiv lshift

**Comment by sinsniwal** [comment]
They work if statically typed. Maybe Mojo converts statically typed def into fn; even modulo is not working
![Screenshot 2023-05-11 at 4 01 27 PM](https://github.com/modularml/mojo/assets/50590413/b2f8d6c3-7fbc-4dd3-a989-3ba101a33b1e)

**Comment by Mogball** [comment]
This is actually the Mojo object, not the PythonObject. I think they're both missing `__pow__` and some other methods.

**Comment by lattner** [comment]
This is fixed and will be included in the next update!
