### ISSUE TITLE
[Modular CLI]: Mojo installation Stuck after collecting all the packages.

### ISSUE THREAD

**Issue by sahill3** [modularml/mojo#970]
### Issue description

- I installed Ubuntu 22.04 LTS from the Windows store. 
- Ran this "curl https://get.modular.com | \
  MODULAR_AUTH=mut_0a7faa04b9f441fab56458c174fdf2eb \
  sh -" command on Ubuntu. 
-Then ran the "modular install mojo command".
- The installation gets stuck here (See screenshot below).
![Screenshot (120)](https://github.com/modularml/mojo/assets/101180617/cd83ff2d-4484-4349-89c3-ed8221cacfe3)
- I think it's because of the WSL.exe version, I can't switch to Version 2. 
- I waited for around 40 mins. No change.
- Also I am getting this error after installing modular. Not sure if they are related.
![mojo 2](https://github.com/modularml/mojo/assets/101180617/526b9a84-4a37-4777-af0d-2ae185274d29)

### Steps to reproduce

> curl https://get.modular.com | \
  MODULAR_AUTH=mut_0a7faa04b9f441fab56458c174fdf2eb \
  sh -
> modular clean
> modular install mojo

### Version Info

```shell
Ubuntu Version 22.04 LTS
WSL 0.2.1
```

**Comment by smuniraj2018** [comment]
We officially support just WSL2. Please upgrade and retry again
