### ISSUE TITLE
[Modular CLI]:  Mojo is not getting installed

### ISSUE THREAD

**Issue by DarknetRises** [modularml/mojo#971]
### Issue description

I can not install mojo after installing the modular CLI

### Steps to reproduce

![Screenshot (83)](https://github.com/modularml/mojo/assets/140790384/41545158-6c6f-4094-b85a-33ef9391c1e3)

curl https://get.modular.com | \
  MODULAR_AUTH=mut_75b6246cb06a4cd3a0bf499b3063c8b5 \
  sh -

After installing the modular client and typing "modular install mojo" it is showing this error

### Version Info

```shell
modular 0.2.0 (355ea9c0)
version 0.2.1
```

**Comment by smuniraj2018** [comment]
can you try modular clean and reinstall it?

**Comment by DarknetRises** [comment]
ok i will try that
