### ISSUE TITLE
[BUG] Parser crash when using type defined in module with same name as current file

### ISSUE THREAD

**Issue by dguidara** [modularml/mojo#972]
### Bug description

Using the sample code for tensor in VS code with the Mojo extension,  the parser crashes.   
![image](https://github.com/modularml/mojo/assets/7413915/b0180deb-91b9-430b-ad53-374acab875e5)

### Steps to reproduce

 - Paste the sample tensor code into a new mojo file.

```python
from tensor import Tensor, TensorSpec, TensorShape
from utils.index import Index
from random import rand

let height = 256
let width = 256
let channels = 3

let image = rand[DType.float32](height, width, channels)

let spec = TensorSpec(DType.float32, height, width)
var gray_scale_image = Tensor[DType.float32](spec)

for y in range(height):
  for x in range(width):
    let r = image[y,x,0]
    let g = image[y,x,1]
    let b = image[y,x,2]
    gray_scale_image[Index(y,x)] = 0.299 * r + 0.587 * g + 0.114 * b

print(gray_scale_image.shape().__str__())
```

```shell
- What OS did you do install Mojo on ?
Ubuntu 22.0.4.2 on WSL2
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.3.1 (a3eed7c8)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.2.0 (355ea9c0)
```

**Comment by dguidara** [comment]
Issue caused by my sample file being called tensor.  That masked the builtin tensor module.   I renamed the file and it worked fine.

**Comment by Mogball** [comment]
Thanks for filing! I've managed to reduce this to a smaller repro.

```python
# filename: tensor.mojo
from random import rand


fn main():
    _ = rand[DType.float32](3, 3, 3)

```

It seems the parser is choking because it thinks that the current file called `tensor.mojo` provides the definition for the Tensor type returned by `rand`.

**Comment by Mogball** [comment]
Closing in favour of #1248
