### ISSUE TITLE
[BUG]: Mojo Is downloading stops

### ISSUE THREAD

**Issue by SulimanAbdulrazzaq** [modularml/mojo#973]
### Bug description

Mojo Is downloading stops when it reaches this point 
![Capture](https://github.com/modularml/mojo/assets/144490671/ee8f8f9b-1ae6-45e5-8a2f-a3b216a2def9)

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
Windows 10 pro
, 64bit ,
processer:i7 5600U,2.60 GHz
ram:16
```

**Comment by Sharktheone** [comment]
Looks simmilar to #970

**Comment by smuniraj2018** [comment]
Yes. Please refer to #970. Closing this as its a duplicate
