### ISSUE TITLE
[Modular CLI]: Python module_import for torch throws error

### ISSUE THREAD

**Issue by manupatet** [modularml/mojo#974]
### Issue description

Trying a matmul using torch python module. It fails saying this:

`error: Execution was interrupted, reason: internal c++ exception breakpoint(-4)..
The process has been left at the point where it was interrupted, use "thread return -x" to return to the state before expression evaluation.`

I tried to follow instructions given for importing modules. Am I missing something ?

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
```
from python import Python

let torch = Python.import_module("torch")
let plt = Python.import_module("matplotlib.pyplot")

X = torch.randn(1000, 100)
W = torch.randn(100, 20)
Y = X * W
```

- If applicable, add screenshots to help explain the problem.

![image](https://github.com/modularml/mojo/assets/8785195/6448921f-7025-4ce2-931c-029916330e21)

- Include anything else that might help us debug the issue.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.2.0 (355ea9c0)
- What OS did you install modular CLI on ?
Debian bullseye slim (on docker)
```

**Comment by bzcheeseman** [comment]
We don't officially support Debian. This also looks like a PyTorch issue, not a modular cli or mojo issue because we don't use C++ exceptions.

**Comment by manupatet** [comment]
Is there a recommended way to get torch to work with mojo?

**Comment by bzcheeseman** [comment]
@jackos might have some suggestions, I don't know of one

**Comment by jackos** [comment]
Also we should be returning the correct error:
```
 raceback (most recent call last):
  File "/Users/jack/src/pytorch-test/main.py", line 5, in <module>
    Y = X * W
RuntimeError: The size of tensor a (100) must match the size of tensor b (20) at non-singleton dimension 1
```
Looks like a problem with handling C++ exceptions, or might be PyTorch specific, I've raised an internal ticket for that.

**Comment by manupatet** [comment]
My bad. I was trying `@` matmul (and casually replaced @ with a `*`) which totally flipped the meaning.

Is matmul operation planned to be supported, or are there any alternates?

Sorry for the confusion. The error for matmul is correctly bubbled up. 
![image](https://github.com/modularml/mojo/assets/8785195/ae1b7f8e-ad31-4784-82ed-cfc717388728)

**Comment by jackos** [comment]
@manupatet no worries at all it raised the problem of how we handle C++ exceptions.

Yes I think the matmul operator on PythonObject should be something we can support given that this already works:
```python
@value
struct Foo:
    fn __matmul__(self, other: Self):
        print("@ operator works!")

fn main():
    let a = Foo()
    let b = Foo()
    a @ b
```
Raise a feature request if you like
