### ISSUE TITLE
[BUG]: Error installing with ASDF

### ISSUE THREAD

**Issue by igorgue** [modularml/mojo#977]
### Bug description

When using ASDF the installer prints an error:

```
$ modular clean && modular install mojo

# Found release for https://packages.modular.com/mojo @ 0.3.1
# Installing to /home/igor/.modular/pkg/packages.modular.com_mojo
# Downloading artifacts. Please wait...
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
No version is set for command python3
Consider adding one of the following versions in your config file at 
python 3.10.12
python 3.11.4
python 3.11.5
modular: error: failed to run python: Program could not be executed
```

Mojo does install, and works, but I think on the previous version, it used to check for some python dependencies and that's what's failing.

### Steps to reproduce

- Install asdf plugin for python and install python with it
- set global to python latest
- install mojo (clean then install)

### System information

```shell
- Pop OS 20.04
- mojo 0.3.1 (a3eed7c8) (after the error)
- modular 0.2.0 (355ea9c0)
```

**Comment by igorgue** [comment]
I installed it with system's Python and gather all the deps from your output and installed it like this:

```
pip install wcwidth textwrap2 pure-eval ptyprocess pickleshare find_libpython fastjsonschema executing backcall urllib3 traitlets tqdm tornado tenacity six rpds-py pyzmq pyyaml pygments psutil prompt-toolkit platformdirs pexpect parso packaging nest-asyncio idna exceptiongroup entrypoints decorator debugpy click charset-normalizer certifi attrs ansiwrap requests referencing python-dateutil matplotlib-inline jupyter-core jedi comm asttokens stack-data jupyter_client jsonschema-specifications jsonschema ipython nbformat ipykernel nbclient papermill
```

And added this to my env vars:

```
export MOJO_PYTHON_LIBRARY="$HOME/.asdf/installs/python/3.11.5/lib/libpython3.so"
```

Is there something else I need to workaround it?

**Comment by igorgue** [comment]
@jackos but I do have a `.tools-version` in my system and python does execute with the right version...

My workaround works so far, but I do not think asdf is setup incorrectly since I use that for other things and python dev, so the shell does know what `python3` is (the one on `asdf`) but `modular` does not... I'm sure it's something about the way some scripts are run by the installer or the env is not getting loaded properly.

**Comment by jackos** [comment]
Sorry @igorgue Pop OS is currently unsupported and so is asdf, if you'd like to see either supported please raise a feature request, so we can see how many people are interested.

**Comment by igorgue** [comment]
@jackos no biggie since I got a workaround, **Pop OS** btw is the same as **Ubuntu 20.04** that you guys support and it works perfectly for me if I use system's Python.

**Comment by jackos** [comment]
Good to know, thanks heaps @igorgue!

**Comment by mosheduminer** [comment]
I also just encountered this issue, running on Ubuntu 22.04 in WSL. `python` and `python3` work as expected, but installing mojo fails as described above.

**Comment by tungh2** [comment]
Same issue with installing mojo on Mac when asdf is existed.

**Comment by tungh2** [comment]
Found the solution, similar to what @igorgue shared but only one step is necessary. Other packages will be automatically installed.

Replace python path in asdf with yours.

```
export MOJO_PYTHON_LIBRARY="$HOME/.asdf/installs/python/3.10.7/lib/libpython3.10.a"
```

**Comment by igorgue** [comment]
@tungh2 that didn't work for me.

```sh
   modular clean                                                                                                                        
   export MOJO_PYTHON_LIBRARY=/home/igor/.asdf/installs/python/3.12.0/lib/libpython3.12.so                                                                                                                 
   modular install mojo                                                                                                                 
# Found release for https://packages.modular.com/mojo @ 0.4.0
# Installing to /home/igor/.modular/pkg/packages.modular.com_mojo
# Downloading artifacts. Please wait...
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
No version is set for command python3
Consider adding one of the following versions in your config file at 
python 3.10.12
python 3.11.4
python 3.11.5
python 3.12.0
modular: error: failed to run python: Program could not be executed
```

**Comment by NaokiMatsuzaki** [comment]
I had the same issue on Mac with ASDF python plugin. A solution using direnv in issue #1077 worked for me.
`asdf direnv shell python system -- modular install mojo`


>```
>$ asdf direnv shell python 3.11.3 -- modular install mojo
>...
>$ mojo
>Welcome to Mojo! 🔥
>``` 
>
>_Originally posted by @hofstee in https://github.com/modularml/mojo/issues/1077#issuecomment-1773978018_

**Comment by tungh2** [comment]
@igorgue python 3.12 seems to introduce new underlying issue. I will test again with that version.

**Comment by igorgue** [comment]
@NaokiMatsuzaki but then you can't use your asdf install inside of `mojo` and you have to add `MOJO_PYTHON_LIBRARY` later on and install the artifacts modular installs as well.

**Comment by hofstee** [comment]
@igorgue  You might need to set the environment variable (I didn’t try without), but running that line alone will install all the artifacts automatically with the modular installer.

**Comment by NaokiMatsuzaki** [comment]
@igorgue I can switch asdf python and system python with the following script. I saved it as ~/.local/bin/launch_mojo.
```
#!/bin/sh
base_dir="$HOME/.asdf/installs/python"
python_version=`asdf current python | head -n 1 | tr -s ' ' | cut -d ' ' -f2 | head`
case $python_version in
  "system")
    mojo
    ;;
  *)
    MOJO_PYTHON_LIBRARY=`find $base_dir/$python_version/lib -name "libpython*" | head -n1`
    env MOJO_PYTHON_LIBRARY=$MOJO_PYTHON_LIBRARY mojo
    ;;
esac
```

```
~/work/mojo via 🐍 v3.12.0
❯ asdf local python system

~/work/mojo via 🐍 v3.11.6
❯ launch_mojo
Welcome to Mojo! 🔥

Expressions are delimited by a blank line.
Type `:quit` to exit the REPL and `:mojo help` for further assistance.

  1> %%python
  2. import sys
  3. import numpy as np
  4. print(sys.version)
  5. print(np.__version__)
  6.
3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)]
1.23.5
(PythonObject) np = {
  (PyObjectPtr) py_object = {
    (DTypePointer[si8]) value = {
      (pointer<scalar<si8>>) address = 0x0000000104372430
    }
  }
}
(PythonObject) sys = {
  (PyObjectPtr) py_object = {
    (DTypePointer[si8]) value = {
      (pointer<scalar<si8>>) address = 0x00000001041eaca0
    }
  }
}
  6>^D

❯ asdf local python 3.12.0

~/work/mojo via 🐍 v3.12.0
❯ launch_mojo
Welcome to Mojo! 🔥

Expressions are delimited by a blank line.
Type `:quit` to exit the REPL and `:mojo help` for further assistance.

  1> %%python
  2. import sys
  3. import numpy as np
  4. print(sys.version)
  5. print(np.__version__)
  6.
3.12.0 (main, Oct 25 2023, 08:10:26) [Clang 17.0.3 ]
1.26.1
(PythonObject) np = {
  (PyObjectPtr) py_object = {
    (DTypePointer[si8]) value = {
      (pointer<scalar<si8>>) address = 0x00000001010cfe20
    }
  }
}
(PythonObject) sys = {
  (PyObjectPtr) py_object = {
    (DTypePointer[si8]) value = {
      (pointer<scalar<si8>>) address = 0x000000010104fc90
    }
  }
}
  6>^D
```
