### ISSUE TITLE
[Modular CLI]: installation fails on Ubuntu 22.04.3

### ISSUE THREAD

**Issue by dbalabka** [modularml/mojo#982]
### Issue description

It seems that modular has a required dependency on `libxml2-dev` version that can be satisfied:
```
libxml2-dev : Depends: libxml2 (= 2.9.13+dfsg-1ubuntu0.3) but 2.9.14+dfsg-0+ubuntu18.04.1+deb.sury.org+1 is to be installed
```

### Steps to reproduce

- Install the latest version of Ubuntu 22.04.3 LTS
- Following installation steps from https://developer.modular.com/download

**Comment by dbalabka** [comment]
Following solve the problem:
```
sudo apt install libxml2=2.9.13+dfsg-1ubuntu0.3
```

**Comment by bzcheeseman** [comment]
Glad you found the solution!
