### ISSUE TITLE
[BUG]: no packages found for the current target hardware

### ISSUE THREAD

**Issue by Michael-McD** [modularml/mojo#983]
### Bug description

Can install "modular" but can't install "mojo" in an Ubuntu virtual machine on a Mac.

### Steps to reproduce

$ modular install mojo

$modular: error: no packages found for the current target hardware - please run `modular host-info` and file a ticket at https://github.com/modularml/mojo with your hardware information

### System information

```shell
- OS: MAC OS, VMWare Fusion virtual machine running Ubuntu 23.04
- Modular --version -> modular 0.2.0 (355ea9c0)
```

**Comment by ematejska** [comment]
Thank you for trying out Mojo.  The installation experience has significantly changed and we're closing out all the old issues with the old installer.  To try out our new installation experience using "magic", please see: https://docs.modular.com/mojo/manual/get-started.
