### ISSUE TITLE
user input 

### ISSUE THREAD

**Issue by Jain-sahab848** [modularml/mojo#985]
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

user input in any datatype

### What is your motivation for this change?

This language is not user-friendly. Essential functions missing like user input, list etc

**Comment by willghatch** [comment]
We absolutely plan to add missing features like lists and input.  We are missing many important features because the language is still very young!  This issue isn't really clear about a specific actionable feature, so I'm going to close it.  Thanks!
