### ISSUE TITLE
[BUG]: Access Index out of bounds of Tensor gives random values. 

### ISSUE THREAD

**Issue by dguidara** [modularml/mojo#991]
### Bug description

Accessing an index in a tensor that does not exist gives a random value.   I would expect some sort of exception to be thrown.

### Steps to reproduce

from tensor import Tensor, TensorShape, TensorSpec
from utils.index import Index
from random import rand

def main():
    
    let spec2 = TensorSpec(DType.int32, 2, 2)
    let test = Tensor[DType.float32](spec2)
    
    #test[Index(0,0)]  = 1
    #test[4] = 3
    for i in range(2):
        for j in range(2):
            print(i, j)
            print(test[i,j])

    print(5, 6)
    print(test[5,6])
  
![image](https://github.com/modularml/mojo/assets/7413915/996d59df-80d7-44a5-9faa-1e2f61cfc158)

### System information

```shell
- What OS did you do install Mojo on ?
Ubuntu 22.0.4.2 on WSL2
- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.3.1 (a3eed7c8)
- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.2.0 (355ea9c0)
```

**Comment by bethebunny** [comment]
We're working on a better solution for Tensors generally. The stdlib wants to move more in the direction you're suggesting, having exceptions being thrown when you do something unsafe with them, however many of the types, including Tensor, were designed with performance in mind first, meaning no bounds checking.
