### ISSUE TITLE
[Modular CLI]: coredump during mojo installation

### ISSUE THREAD

**Issue by cooloney** [modularml/mojo#993]
### Issue description

base) ➜  ~ modular auth mut_43fb1ff75cb648acaa1b439600e5a433 &&
modular install mojo
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.	Program arguments: modular install mojo
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  modular   0x000055af33481bb7
1  modular   0x000055af3347f86e
2  modular   0x000055af3348227f
3  libc.so.6 0x00007fb18b79c520
4  modular   0x000055af342f7fe7
5  modular   0x000055af342f7ac5
6  modular   0x000055af342f8d15
7  modular   0x000055af33869fdd
8  modular   0x000055af3385cab0
9  modular   0x000055af334456a2
10 modular   0x000055af33443ec3
11 libc.so.6 0x00007fb18b783d90
12 libc.so.6 0x00007fb18b783e40 __libc_start_main + 128
13 modular   0x000055af3344355e
[1]    21121 illegal hardware instruction (core dumped)  modular install mojo

### Steps to reproduce

base) ➜  ~ modular auth mut_43fb1ff75cb648acaa1b439600e5a433 &&
modular install mojo
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.	Program arguments: modular install mojo
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  modular   0x000055af33481bb7
1  modular   0x000055af3347f86e
2  modular   0x000055af3348227f
3  libc.so.6 0x00007fb18b79c520
4  modular   0x000055af342f7fe7
5  modular   0x000055af342f7ac5
6  modular   0x000055af342f8d15
7  modular   0x000055af33869fdd
8  modular   0x000055af3385cab0
9  modular   0x000055af334456a2
10 modular   0x000055af33443ec3
11 libc.so.6 0x00007fb18b783d90
12 libc.so.6 0x00007fb18b783e40 __libc_start_main + 128
13 modular   0x000055af3344355e
[1]    21121 illegal hardware instruction (core dumped)  modular install mojo

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`

~ modular -v
modular 0.2.0 (355ea9c0)
```
- What OS did you install modular CLI on ?
Ubuntu 22.04
```

**Comment by smuniraj2018** [comment]
Can you please share your hardware details on which system did you try?

**Comment by QuentiumYT** [comment]
The solution is to remove the `~/.modular/` folder, it should be a problem with the files inside. After that, you'll have to use `modular auth <token>` again and install mojo `modular install mojo`
(Posting here so people will find this solution directly instead of looking into all related issues)

**Comment by jackos** [comment]
Resolved in a prior release
