### ISSUE TITLE
[Modular CLI]: Downloading from cas.modular.com fails after "modular install mojo"

### ISSUE THREAD

**Issue by df2tr** [modularml/mojo#995]
### Issue description

Fetching install files from cas.modular.com fails.

# Found release for https://packages.modular.com/mojo @ 0.3.1
# Installing to /root/.modular/pkg/packages.modular.com_mojo
# Downloading artifacts. Please wait...
modular: error: failure detected - please run `modular clean` and try again
==========================
Failure Information:
	- http error: failed to reach URL https://cas.modular.com/0/y0n0fMU54q4yFbdGiUYtWOSJHaoPqxAMJ7VNo6w-NtA with cURL error Couldn't resolve host name - Looking for y0n0fMU54q4yFbdGiUYtWOSJHaoPqxAMJ7VNo6w-NtA
	- http error: failed to reach URL https://cas.modular.com/0/CUfoqCZfiQmDvhX2DD7snw1BfGQZP4KNXUi5YMhdiXY with cURL error Couldn't resolve host name - Looking for CUfoqCZfiQmDvhX2DD7snw1BfGQZP4KNXUi5YMhdiXY
	- http error: failed to reach URL https://cas.modular.com/0/Id8Ckp7y8jX1ayLabEBsSX7mmBX5LIIEGiZZwfg0QFw with cURL error Couldn't resolve host name - Looking for Id8Ckp7y8jX1ayLabEBsSX7mmBX5LIIEGiZZwfg0QFw
	- http error: failed to reach URL https://cas.modular.com/0/XxEUI-aSAOKI1ZZBrR_HtlUtSVk9DT4W9EdWN1oC7Vw with cURL error Couldn't resolve host name - Looking for XxEUI-aSAOKI1ZZBrR_HtlUtSVk9DT4W9EdWN1oC7Vw
==========================

### Steps to reproduce

Use Ubuntu 22.04.3 LTS connected via LAN to a internet router (FRITZ!Box 7490) and type 

sudo apt-get update
sudo apt-get install modular
modular install mojo

in a shell.

### Version Info

```shell
modular cli version 0.2.0 (355ea9c0)
OS: Ubuntu 22.04.3 LTS
```

**Comment by gryznar** [comment]
Upgrading to 0.3.1 requires `modular clean` as trace suggests :)

**Comment by df2tr** [comment]
Yes, thank you, however I had already tried the command, which did not bring any improvement. After running it, there is always after some time of waiting the message on the console that no files can be downloaded.

# Found release for https://packages.modular.com/mojo @ 0.3.1
# Installing to /home/user/.modular/pkg/packages.modular.com_mojo
# Downloading artifacts. Please wait...
modular: error: failure detected - please run `modular clean` and try again
==========================
Failure Information:
	- http error: failed to reach URL https://cas.modular.com/0/jbGnFgc0lT64GcFJf2jsxqKtj3mMbVf3WapbZ3hKbWc with cURL error Couldn't resolve host name - Looking for jbGnFgc0lT64GcFJf2jsxqKtj3mMbVf3WapbZ3hKbWc
	- http error: failed to reach URL https://cas.modular.com/0/GE8HpAFwz5_5PUWKtN0WzK0FaKZKg4fbSx0soFF1-GQ with cURL error Couldn't resolve host name - Looking for GE8HpAFwz5_5PUWKtN0WzK0FaKZKg4fbSx0soFF1-GQ
	- http error: failed to reach URL https://cas.modular.com/0/bIVLoTLTAivg53c-grik5lQ1HY-g4A3yVSyDjBWeUwM with cURL error Couldn't resolve host name - Looking for bIVLoTLTAivg53c-grik5lQ1HY-g4A3yVSyDjBWeUwM
	- http error: failed to reach URL https://cas.modular.com/0/ocIa8anUzsCpF_2ww4Pt2t5RvEnrZZ070TMJC9QRTPE with cURL error Couldn't resolve host name - Looking for ocIa8anUzsCpF_2ww4Pt2t5RvEnrZZ070TMJC9QRTPE
	- http error: failed to reach URL https://cas.modular.com/0/hYooNIUbWTc8X-UWLX4AQsKA9j1Z0S2DQu9pegzizQc with cURL error Couldn't resolve host name - Looking for hYooNIUbWTc8X-UWLX4AQsKA9j1Z0S2DQu9pegzizQc

**Comment by Sharktheone** [comment]
Looks similar to #670 and #889

**Comment by jackos** [comment]
Closing in favor of https://github.com/modularml/mojo/issues/670

@df2tr note that some users have reported using a VPN fixes this issue.

**Comment by BlackHo0d** [comment]
Thank you for the response
