### ISSUE TITLE
[Dev Console]: Support .deb install option

### ISSUE THREAD

**Issue by silvasean** [modularml/mojo#996]
### Issue description

Hello, due to my organization's security policies, adding the external apt repository is not possible on my machine (and plain `sudo apt-get install modular` doesn't either). I have been successfully using VSCode though via their plain .deb installer (`sudo dpkg -i foo.deb`). I'm wondering if the modular SDK could support such an install option as well.

### Steps to reproduce

Follow Linux instructions at https://developer.modular.com/download
On my machine, I get the following results:

1.

`sudo apt-get install modular` -->
`E: Unable to locate package modular`

2.

```
apt-get install -y apt-transport-https &&
  keyring_location=/usr/share/keyrings/modular-installer-archive-keyring.gpg &&
  curl -1sLf 'https://dl.modular.com/bBNWiLZX5igwHXeu/installer/gpg.0E4925737A3895AD.key' |  gpg --dearmor >> ${keyring_location} &&
  curl -1sLf 'https://dl.modular.com/bBNWiLZX5igwHXeu/installer/config.deb.txt?distro=debian&codename=wheezy' > /etc/apt/sources.list.d/modular-installer.list &&
  apt-get update &&
  apt-get install -y modular
```
--> error about not allowing external repositories

**Comment by Sharktheone** [comment]
You can download modular directly from the [repository](https://dl.modular.com/public/installer/deb/debian/pool/any-version/main/m/mo/modular_0.2.0/modular-0.2.0-amd64.deb). This is also the way, how we got Modular on Arch

**Comment by silvasean** [comment]
Thanks, that worked!!
