### ISSUE TITLE
[BUG]: install

### ISSUE THREAD

**Issue by BlackHo0d** [modularml/mojo#997]
### Bug description

I can't download Mojo on my Macbook(Intel). I stoped on the 4th step can't install Modular CLI

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ?
- Provide version information for Mojo by pasting the output of `mojo -v`
- Provide Modular CLI version by pasting the output of `modular -v`
```

**Comment by ematejska** [comment]
Native Mac support is not available.  Are you installing in the VSCode terminal per the instructions to take advantage of Codespaces?  If this is failing, would you be able to please provide the error message?

**Comment by BlackHo0d** [comment]
Thank you for a fas response. I've already dealt with problems with
instillation.
I'm glad to be a part of Mojo community

**Comment by ematejska** [comment]
Great!  Let us know if you encounter more problems.

**Comment by BlackHo0d** [comment]
Hi, I have a problem with installing mojo SDK. 
When I've written in Terminal(in VC code)  'modular install mojo' 
I got: vscode ➜ /workspaces/Ubuntu $ modular install mojo
# Found release for https://packages.modular.com/mojo @ 0.4.0
# Installing to /home/vscode/.modular/pkg/packages.modular.com_mojo
# Downloading artifacts. Please wait...
modular: error: failure detected - please run `modular clean` and try again
==========================
Failure Information:
        - Creating symlink for /home/vscode/.modular/pkg/packages.modular.com_mojo/lib/liblldb.so.18.0.0git -> /home/vscode/.modular/pkg/packages.modular.com_mojo/lib/liblldb.so failed: File exists
        - Creating symlink for /home/vscode/.modular/pkg/packages.modular.com_mojo/lib/libMojoJupyter.so.18git -> /home/vscode/.modular/pkg/packages.modular.com_mojo/lib/libMojoJupyter.so failed: File exists
        - Creating symlink for /home/vscode/.modular/pkg/packages.modular.com_mojo/lib/liblldb.so.18.0.0git -> /home/vscode/.modular/pkg/packages.modular.com_mojo/lib/liblldb.so.18git failed: File exists
        - Creating symlink for /home/vscode/.modular/pkg/packages.modular.com_mojo/lib/libKGENCompilerRTShared.so.18git -> /home/vscode/.modular/pkg/packages.modular.com_mojo/lib/libKGENCompilerRTShared.so failed: File exists
        - Creating symlink for /home/vscode/.modular/pkg/packages.modular.com_mojo/lib/libMojoLLDB.so.18git -> /home/vscode/.modular/pkg/packages.modular.com_mojo/lib/libMojoLLDB.so failed: File exists
        - Creating symlink for /home/vscode/.modular/pkg/packages.modular.com_mojo/lib/libLLCLRuntimeGlobals.so.18git -> /home/vscode/.modular/pkg/packages.modular.com_mojo/lib/libLLCLRuntimeGlobals.so failed: File exists
        - Creating symlink for /home/vscode/.modular/pkg/packages.modular.com_mojo/lib/libMSupportGlobals.so.18git -> /home/vscode/.modular/pkg/packages.modular.com_mojo/lib/libMSupportGlobals.so failed: File exists
        - http error: failed to reach URL https://cas.modular.com/0/XWOPjPQpTXw5rl5d_3iNdw8IWB4hif3ppDS8Efjhqkw with cURL error Timeout was reached - Looking for XWOPjPQpTXw5rl5d_3iNdw8IWB4hif3ppDS8Efjhqkw
==========================

What should I do to fix it ? I use Macbook pro on Intel

**Comment by Sharktheone** [comment]
Looks like #670. Maybe you can find a fix there. I think a VPN helps somehow.

**Comment by BlackHo0d** [comment]
I've been trying to install Mojo SDK using VPN but got the same error.
Still trying.

**Comment by Sharktheone** [comment]
Have you tried executing `modular clean` before `modular install mojo`?

**Comment by BlackHo0d** [comment]
Yeah, it didn't work. I'm trying it again, still hoping it'll work

**Comment by BlackHo0d** [comment]
still not working..

**Comment by Sharktheone** [comment]
I haven't used a VPN for downloading mojo, can you maybe send another Error log, even if they seem to be the same? (And please run `modular clean` again before sending)

**Comment by BlackHo0d** [comment]
Sure, I'll try again

**Comment by BlackHo0d** [comment]
Failure Information:
        - http error: failed to reach URL https://cas.modular.com/0/xnvEJlCJKtoZB5TOFuL77x5fgzT8p5Ol68H4uazm6O4 with cURL error Timeout was reached - Looking for xnvEJlCJKtoZB5TOFuL77x5fgzT8p5Ol68H4uazm6O4
        - http error: failed to reach URL https://cas.modular.com/0/JIUSVJZEIqnkhI2ChMnS7i0mfrBQ3kyNkW8dJSUPV3s with cURL error Timeout was reached - Looking for JIUSVJZEIqnkhI2ChMnS7i0mfrBQ3kyNkW8dJSUPV3s
        - http error: failed to reach URL https://cas.modular.com/0/xzmkI9Xc04mvbPwhSbmBMwJ1haMC6V8GizBC7T9HBKo with cURL error Timeout was reached - Looking for xzmkI9Xc04mvbPwhSbmBMwJ1haMC6V8GizBC7T9HBKo
        - http error: failed to reach URL https://cas.modular.com/0/XWOPjPQpTXw5rl5d_3iNdw8IWB4hif3ppDS8Efjhqkw with cURL error Timeout was reached - Looking for XWOPjPQpTXw5rl5d_3iNdw8IWB4hif3ppDS8Efjhqkw
        - http error: failed to reach URL https://cas.modular.com/0/nuDwXhUin3vvcPssVPO8qL4XjHqEU8CnbnCCP5pGdz8 with cURL error Timeout was reached - Looking for nuDwXhUin3vvcPssVPO8qL4XjHqEU8CnbnCCP5pGdz8
==================

I got this

**Comment by Sharktheone** [comment]
Hmm, I'm not sure, how vs code handles this, but can you reach the internet from the VS Code shell?

**Comment by BlackHo0d** [comment]
I really don't know how to do it actually. Can you send me a link to the video or website or just explain it to me ?

**Comment by BlackHo0d** [comment]
vscode ➜ /workspaces/Ubuntu $ modular install mojo
# Found release for https://packages.modular.com/mojo @ 0.4.0
# Installing to /home/vscode/.modular/pkg/packages.modular.com_mojo
# Downloading artifacts. Please wait...
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.10-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: /home/vscode/.modular/pkg/packages.modular.com_mojo/venv/bin/python3

modular: error: failed to run python: 


Can anyone explain what does it mean? What should I do with this ?

**Comment by Sharktheone** [comment]
It says, you need to install the `python3.10-venv` package from apt, you can do this with `sudo apt install python3.10-venv` also mentioned in the output.

**Comment by BlackHo0d** [comment]
Thank you for your help, I did it. 

🔥 Mojo installed! 🔥

Finally, after more than 30 attempts did this

**Comment by BlackHo0d** [comment]
Well, Mojo installed but there's another problem
I wrote: print('Hello') and nothing happened
I installed mojo and other needed extensions, why doesn't it work ?

**Comment by Sharktheone** [comment]
I guess, you are using the mojo repl in your terminal. In the repl you need press your enter key twice.
